### ISSUE TITLE
Exception due to lazy initialization recursion when loading codegen assembly

### ISSUE THREAD

**Issue by randa1** [dotnet/orleans#1063]
Hi,

We're working with the latest master version of Orleans and we've run into this issue when working with `GrainClient` that communicates with `TestingSiloHost` in our tests (NUnit).
When the clients loads the codegen assembly (`OrleansCodeGenAssembly` if I'm not mistaken) it seems that the assembly load callback tries to access the `Lazy<T>` valueFactory which has caused the loading of the assembly in the first place.

This causes the following exception:
```
System.InvalidOperationException occurred
 _HResult=-2146233079
 _message=ValueFactory attempted to access the Value property of this instance.
 HResult=-2146233079
 IsTransient=false
 Message=ValueFactory attempted to access the Value property of this instance.
 Source=mscorlib
 StackTrace:
      at System.Lazy`1.CreateValue()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Lazy`1.get_Value()
 InnerException: 
```

I'm positive this happens in the `GrainClient` execution and not in the Silo since I've inspected `AppDomain.CurrentDomain` and saw that it's the tests app domain.

This is the stack trace of the exception, you can see the circular call in it pretty clearly:
![stacktrace](https://cloud.githubusercontent.com/assets/3209338/11339114/902e75d4-9200-11e5-92f0-8d8bf44309b2.png)

I'm guessing this issue was introduced by the recent changes to codegen (paging @ReubenBond).

Thanks.

**Comment by randa1** [comment]
Actually this doesn't seem to be a breaking issue, as the Silos continues running afterwards. My bad.
