### ISSUE TITLE
Not able to start 2 secondary SILOS : 2nd one throws exception

### ISSUE THREAD

**Issue by angshuman-agarwal** [dotnet/orleans#1114]
Hi,
Do not know if I am doing anything wrong here. I built the latest source and fired up 1 Primary and 2 secondary SILOS on same machine. The second SILO throws exception :-1: 

```
OrleansHost.exe Primary
OrleansHost.exe Secondary
OrleansHost.exe Secondary --> throws exception
```
**OrleansConfiguration.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<OrleansConfiguration xmlns="urn:orleans">
  <Globals>
    <StorageProviders>
      <Provider Type="Orleans.Storage.MemoryStorage" Name="MemoryStore" />
      <Provider Type="Orleans.Storage.MemoryStorage" Name="Default" />
      <!--<Provider Type="Orleans.Storage.AzureTableStorage" Name="AzureStore" />-->
    </StorageProviders>
    <SeedNode Address="localhost" Port="22222"/>
    <Messaging ResponseTimeout="30s"/>
  </Globals>
  <Defaults>
    <Networking Address="localhost" Port="22222"/>
    <ProxyingGateway Address="localhost" Port="40000" />
    <Tracing DefaultTraceLevel="Info" TraceToConsole="true" TraceToFile="{0}-{1}.log" PropagateActivityId="false" BulkMessageLimit="1000">
       <TraceLevelOverride LogPrefix="Application" TraceLevel="Info" />
       <!--
       <TraceLevelOverride LogPrefix="Runtime.Dispatcher" TraceLevel="Verbose" />
       <TraceLevelOverride LogPrefix="AssemblyLoader.Silo" TraceLevel="Warning" />
       -->
    </Tracing>
    <Statistics MetricsTableWriteInterval="30s" PerfCounterWriteInterval="30s" LogWriteInterval="300s" WriteLogStatisticsToTable="true" StatisticsCollectionLevel="Info"/>
  </Defaults>
<Override Node="Primary">
    <Networking Address="localhost" Port="22222" />
    <ProxyingGateway Address="localhost" Port="30000" />
  </Override>
  <Override Node="Secondary">
    <Networking Address="localhost" Port="11112" />
    <ProxyingGateway Address="localhost" Port="30002" />
  </Override>
</OrleansConfiguration>
```
**Exception:**
```
[2015-12-06 21:48:57.825 GMT     7	ERROR  	100071	Dispatcher	127.0.0.1:11112]	!!!!!!!!!! SelectTarget failed with One or more errors occurred.	
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__42`1.MoveNext() in C:\Users\ANGSHUMAN\Documents\orleans\src\Orleans\Runtime\GrainReference.cs:line 343
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.<FullLookup>d__95.MoveNext() in C:\Users\ANGSHUMAN\Documents\orleans\src\OrleansRuntime\GrainDirectory\LocalGrainDirectory.cs:line 754
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass0_0`1.<<QueueTask>b__0>d.MoveNext() in C:\Users\ANGSHUMAN\Documents\orleans\src\OrleansRuntime\Scheduler\ShedulerExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.Placement.RandomPlacementDirector.<OnSelectActivation>d__1.MoveNext() in C:\Users\ANGSHUMAN\Documents\orleans\src\OrleansRuntime\Placement\RandomPlacementDirector.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.Placement.PlacementDirectorsManager.<SelectOrAddActivation>d__11.MoveNext() in C:\Users\ANGSHUMAN\Documents\orleans\src\OrleansRuntime\Placement\PlacementDirectorsManager.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.Dispatcher.<AddressMessage>d__31.MoveNext() in C:\Users\ANGSHUMAN\Documents\orleans\src\OrleansRuntime\Core\Dispatcher.cs:line 564
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Runtime.Dispatcher.<AsyncSendMessage>d__29.MoveNext() in C:\Users\ANGSHUMAN\Documents\orleans\src\OrleansRuntime\Core\Dispatcher.cs:line 523
Exc level 1: System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request S127.0.0.1:11112:187134504Catalog@S0000000e->S127.0.0.1:22222:0DirectoryService@S0000000a #3: global::Orleans.Runtime.IRemoteGrainDirectory:LookUp(). Target History is: <S127.0.0.1:22222:0:DirectoryService:@S0000000a>
[2015-12-06 21:48:58.586 GMT     7	WARNING	101215	Scheduler.MembershipOracle.WorkItemGroup	127.0.0.1:11112]	Task [Id=63, Status=RanToCompletion] in WorkGroup [SystemTarget: S127.0.0.1:11112:187134504MembershipOracle@S0000000f] took elapsed time 0:00:00.7574081 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/1, ManagedThreadId=7, Executing Task Id=63 Status=RanToCompletion for 00:00:00.7602078 on WorkItem=System*WorkItemGroup:Name=MembershipOracle,WorkGroupStatus=Running Executing for 00:00:00.7602078. .>	
[2015-12-06 21:49:03.637 GMT    10	INFO   	100632	MembershipFactory	127.0.0.1:11112]	-Waiting for membership table provider to initialize. Going to sleep for 00:00:05 and re-try to reconnect.	

```

_Do I need to explicitly specify all the secondary SILOS in the config (while forming a cluster) ?_

**Comment by gabikliot** [comment]
> Do I need to explicitly specify all the secondary SILOS in the config (while forming a cluster)

In this setting (dev cluster) yes, you do. Each secondary needs a different name: Secondary1, Secondary2, ... and each secondary needs a different port (both networking and proxying).

**Comment by angshuman-agarwal** [comment]
>In this setting (dev cluster) yes, you do. 
I am more confused now. So, what is the proper setting which is not a "Dev cluster" ? Can you please point me to any documentation on _Dev v/s Prod clusters_ on the XML configs ?

**Comment by gabikliot** [comment]
http://dotnet.github.io/orleans/Step-by-step-Tutorials/Cloud-Deployment

**Comment by angshuman-agarwal** [comment]
Thanks but link is does not seem to work - http://dotnet.github.io/orleans/Step-by-step-Tutorials/

**Comment by angshuman-agarwal** [comment]
Thanks but link is does not seem to work - http://dotnet.github.io/orleans/Step-by-step-Tutorials/

**Comment by angshuman-agarwal** [comment]
Thanks but link is does not seem to work - http://dotnet.github.io/orleans/Step-by-step-Tutorials/

**Comment by angshuman-agarwal** [comment]
Thanks !
