### ISSUE TITLE
json.net nuget reference missing from Microsoft.Orleans.Client and Microsoft.Orleans.Server nugets

### ISSUE THREAD

**Issue by amccool** [dotnet/orleans#1125]
Microsoft.Orleans.Client nuget needs a reference to json.net nuget.
same with Microsoft.Orleans.Server.

Without manually adding the json.net nuget to a executable project the TypeManager cant load grain references.

perhaps this dependency belongs elsewhere (CodeGen?)

1.1.0-beta2

Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Exception = System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.CodeGenerator.CodeGeneratorCommon.<GetTypesWithImplementations>b__9(Assembly _)
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__1`1.MoveNext()
   at Orleans.CodeGenerator.CodeGeneratorCommon.GetTypesWithImplementations(Type[] markerAttributes)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssemblies(Assembly[] inputs)

[2015-12-09 19:21:21.483 GMT    10      WARNING 103801  CodeGenerator   ]
Exception generating code for input assemblies:
ProvingGroundActorDirect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Exception:
Exc level 0: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.CodeGenerator.CodeGeneratorCommon.<GetTypesWithImplementations>b__9(Assembly _)
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__1`1.MoveNext()
   at Orleans.CodeGenerator.CodeGeneratorCommon.GetTypesWithImplementations(Type[] markerAttributes)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssemblies(Assembly[] inputs)
Exc level 1: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

**Comment by sergeybykov** [comment]
Already resolved by https://github.com/dotnet/orleans/pull/1113.
