### ISSUE TITLE
SILO : Could not load file or assembly 'Antlr3.Runtime, Version=3.1.3.42154'

### ISSUE THREAD

**Issue by angshuman-agarwal** [dotnet/orleans#1222]
Hi,
I thought nuget packages will fetch the dependencies. I get this exception when I try to access a grain which is in a different csproj (I had added the GrainImpl & GrainInsterface references to the SILO csproj) - 

```
2016-01-01-14.00.27.719ZZ
ERROR starting Orleans silo name=ANGSHUMAN Exception=
Exc level 0: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.Runtime.TypeUtils.GetTypes(Assembly assembly, Func`2 whereFunc)
   at Orleans.Runtime.TypeUtils.GetTypes(Func`2 whereFunc)
   at Orleans.Runtime.SiloAssemblyLoader.GetGrainClassTypes(Boolean strict)
   at Orleans.Runtime.GrainTypeManager.Start(Boolean strict)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo()
Exc level 1: System.IO.FileNotFoundException: Could not load file or assembly 'Antlr3.Runtime, Version=3.1.3.42154, Culture=neutral, PublicKeyToken=3a9cab8f8d22bfb7' or one of its dependencies. The system cannot find the file specified.
Exc level 1: System.IO.FileNotFoundException: Could not load file or assembly 'Antlr3.Runtime, Version=3.1.3.42154, Culture=neutral, PublicKeyToken=3a9cab8f8d22bfb7' or one of its dependencies. The system cannot find the file specified.
Exc level 1: System.IO.FileNotFoundException: Could not load file or assembly 'Antlr3.Runtime, Version=3.1.3.42154, Culture=neutral, PublicKeyToken=3a9cab8f8d22bfb7' or one of its dependencies. The system cannot find the file specified.
Exc level 1: System.IO.FileNotFoundException: Could not load file or assembly 'Antlr3.Runtime, Version=3.1.3.42154, Culture=neutral, PublicKeyToken=3a9cab8f8d22bfb7' or one of its dependencies. The system cannot find the file specified.
Exc level 1: System.IO.FileNotFoundException: Could not load file or assembly 'Antlr3.Runtime, Version=3.1.3.42154, Culture=neutral, PublicKeyToken=3a9cab8f8d22bfb7' or one of its dependencies. The system cannot find the file specified.
```

NB: Adding Antlr to the SILO project works fine.

```
Install-Package Antlr -Version 3.1.3.42154
```

**Comment by gabikliot** [comment]
The grain implementation classes, as well as all their dependencies, have to be copied to the execution folder (folder where you will run the OrleansSilo Host exe) [or in the sub folder Applications inside the execution folder]. The are multiple ways to achieve that, non of them is Orleans specific.
One is to have a post build step, another is to add dependencies and mark "Copy Always" in VS. You can add dependencies in different ways. Either directly to your host project or indirectly. 

All those are general ways in Visual Studio and .NET about managing build results and deploying them not execution, nothing Orleans specific.
You can use the Hello World sample as an example of one way how this can be achived.

**Comment by angshuman-agarwal** [comment]
Thanks !
