### ISSUE TITLE
OutsideRuntimeClient caught an UnobservedException

### ISSUE THREAD

**Issue by angshuman-agarwal** [dotnet/orleans#1223]
HI,
I have a Client, Producer and Host(SILO). As the name suggests, the Producer triggers a real time data stream and the client subscribes via _IAsyncObserver_ interface. But, sometimes I am getting this exception in the Producer.exe. Not able to judge why and when does this happen ? 

**Producer**
```
var priceGrain = GrainClient.GrainFactory.GetGrain<IPriceGrain>(currentTicker.Name);

// this will stream the prices internally by GetStream > OnNextAsync
priceGrain.SetPrice(currentTicker);
```

**Client (Observer)**
```
public class PriceObserver : IAsyncObserver<IPrice>
    {
        private Subject<IPrice> _subject = new Subject<IPrice>();

        public Task OnCompletedAsync()
        {
            return TaskDone.Done;
        }

        public Task OnErrorAsync(Exception ex)
        {
            return TaskDone.Done;
        }

        public Task OnNextAsync(IPrice item, StreamSequenceToken token = null)
        {
            _subject.OnNext(item);
            return TaskDone.Done;
        }

        public IObservable<IPrice> GetPriceStream()
        {
            return _subject.AsObservable();
        }

        public async Task Subscribe(string symbol)
        {
            var grain = GrainClient.GrainFactory.GetGrain<IPriceGrain>(symbol);
            var stream = await grain.GetStream();
            await stream.SubscribeAsync(this);
        }
    }
```

**Exception in Producer**
```
[2016-01-02 01:45:15.700 GMT     6	WARNING	100011	OutsideRuntimeClient	169.183.186.52:0]	No callback for response message: Response S127.0.0.1:30000:0*grn/897503DF/00000000+IDWR.L@7eeed688->*cli/8a87b88e@0888a0ac #1428: global::GrainInterfaces.IPriceGrain:SetPrice()	
[2016-01-02 01:45:26.095 GMT     2	ERROR  	100007	OutsideRuntimeClient	169.183.186.52:0]	!!!!!!!!!! OutsideRuntimeClient caught an UnobservedException.	
Exc level 0: System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request *cli/8a87b88e@0888a0ac->S127.0.0.1:30000:0*grn/897503DF/00000000+IDWR.L #1656: global::GrainInterfaces.IPriceGrain:SetPrice(). Target History is: <S127.0.0.1:30000:0:*grn/897503DF/00000000+IDWR.L:>
[2016-01-02 01:45:26.105 GMT     2	ERROR  	100005	UnobservedExceptionHandler	169.183.186.52:0]	!!!!!!!!!! UnobservedExceptionsHandlerClass Caught an UnobservedTaskException event sent by [Id=9255, Status=Faulted]. Exception = 
Exc level 0: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
Exc level 1: System.AggregateException: One or more errors occurred.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__0`1.MoveNext()
Exc level 2: System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request *cli/8a87b88e@0888a0ac->S127.0.0.1:30000:0*grn/897503DF/00000000+IDWR.L #1656: global::GrainInterfaces.IPriceGrain:SetPrice(). Target History is: <S127.0.0.1:30000:0:*grn/897503DF/00000000+IDWR.L:>	
[2016-01-02 01:45:26.108 GMT     2	ERROR  	100006	UnobservedExceptionHandler	169.183.186.52:0]	!!!!!!!!!! Exception remained UnObserved!!! The subsequent behaivour depends on the ThrowUnobservedTaskExceptions setting in app config and .NET version.	
[2016-01-02 01:45:26.109 GMT     2	ERROR  	100007	OutsideRuntimeClient	169.183.186.52:0]	!!!!!!!!!! OutsideRuntimeClient caught an UnobservedException.	
Exc level 0: System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request *cli/8a87b88e@0888a0ac->S127.0.0.1:30000:0*grn/897503DF/00000000+ETD.PA #1525: global::GrainInterfaces.IPriceGrain:SetPrice(). Target History is: <S127.0.0.1:30000:0:*grn/897503DF/00000000+ETD.PA:>
[2016-01-02 01:45:26.111 GMT     2	ERROR  	100005	UnobservedExceptionHandler	169.183.186.52:0]	!!!!!!!!!! UnobservedExceptionsHandlerClass Caught an UnobservedTaskException event sent by [Id=8600, Status=Faulted]. Exception = 
Exc level 0: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
Exc level 1: System.AggregateException: One or more errors occurred.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__0`1.MoveNext()
```

**Comment by gabikliot** [comment]
Producer needs to `await` the `priceGrain.SetPrice(currentTicker)`.

**Comment by angshuman-agarwal** [comment]
Hi,
I did that, but when I **shutdown the Client**, I get this exception from the **Producer**  :

```
Response did not arrive on time in 00:00:30 for message: Request *cli/2b6d288f@2f0222af->S127.0.0.1:30000:0*grn/897503DF/00000000+IDWR.L #121: global::GrainInterfaces.IPriceGrain:SetPrice(). Target History is: <S127.0.0.1:30000:0:*grn/897503DF/00000000+IDWR.L:>
```

![image](https://cloud.githubusercontent.com/assets/1796126/12075419/30ca70ba-b178-11e5-99b7-856d9823c0af.png)

**Comment by gabikliot** [comment]
When you shutdown the client you should call Uninitialize.

**Comment by angshuman-agarwal** [comment]
Thanks @gabikliot  - My bad! I **should have** noticed this. That is resolved. 
But one more thing I noticed in _log of SILO_ after this fix. Whenever the client is being shutdown, it logs an exception like below. Is it something expected ? 

```
[2016-01-02 21:17:35.925 GMT    42	WARNING	101024	Runtime.Messaging.GatewayAcceptor	127.0.0.1:11111]	Exception while completing a receive from 127.0.0.1:4729	
Exc level 0: System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor.ReceiveCallback(IAsyncResult result)
[2016-01-02 21:17:35.937 GMT    36	WARNING	101306	Runtime.Messaging.GatewaySender/GatewaySiloSender_2	127.0.0.1:11111]	Exception sending to client at 127.0.0.1:4729: System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(IList`1 buffers, SocketFlags socketFlags)
   at Orleans.Runtime.Messaging.Gateway.GatewaySender.Send(Message msg, Socket sock)	
Exc level 0: System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(IList`1 buffers, SocketFlags socketFlags)
   at Orleans.Runtime.Messaging.Gateway.GatewaySender.Send(Message msg, Socket sock)
[2016-01-02 21:17:35.945 GMT    42	INFO   	101302	Orleans.Messaging.Gateway	127.0.0.1:11111]	Recorded closed socket from endpoint 127.0.0.1:4729, client ID *cli/5b3e50af.	
```

Looks like the server was sending the response to the associated client but got a close connection request at that moment and hence threw an exception instead ?

**Comment by gabikliot** [comment]
No, that is fine.
The server/gateway has a pending async receive on the socket (always trying to receive). So when client just closes the socket the gw gets a socket error and closes the socket too. 

As for send, same way - the gw was indeed trying to send something to the client (probably stream message) and the client just decided to Uninitialzie in the middle of it. So the server gets sending socket error.

We can do a more graceful socket shutdown in both cases I guess, but there is no real bad impact of this. The socket is closed correctly in both cases (` Recorded closed socket from endpoint 127.0.0.1:4729, client ID`), no leaking resources. Just a redundant in this case warning in the log.

**Comment by angshuman-agarwal** [comment]
Got it. Thanks.

**Comment by gabikliot** [comment]
:+1:
