### ISSUE TITLE
Uninformative error message when initializing AzureClient

### ISSUE THREAD

**Issue by astaror** [dotnet/orleans#1230]
Trying to launch AzureClient in real environment, and instead of get everything up and working (like in emulator) getting following error messages:

EventName="FormattedMessageEvent" FormattedMessage="Client.Initialize failed with exc -- {0}. Will try again" Argument0="One or more errors occurred." TraceSource="w3wp.exe"

EventName="FormattedMessageEvent" FormattedMessage="Error starting Orleans Azure client application -- {0} -- bailing. {1}" Argument0="Could not Initialize Client for DeploymentId=fca6faa3151640c2bdeeb08eb2d02bf5. Last exception=One or more errors occurred." Argument1="
Exc level 0: Orleans.Runtime.OrleansException: Could not Initialize Client for DeploymentId=fca6faa3151640c2bdeeb08eb2d02bf5. Last exception=One or more errors occurred.
Exc level 1: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Orleans.GrainClient.InternalInitialize(ClientConfiguration config, OutsideRuntimeClient runtimeClient)
   at Orleans.Runtime.Host.AzureClient.InitializeImpl_FromConfig(ClientConfiguration config)
Exc level 2: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.Diagnostics.TraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String format, Object[] args)
   at System.Diagnostics.TraceInternal.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
   at Orleans.Runtime.TraceLogger.Initialize(ITraceConfiguration config, Boolean configChange)
   at Orleans.OutsideRuntimeClient..ctor(ClientConfiguration cfg, GrainFactory grainFactory, Boolean secondary)
   at Orleans.GrainClient.DoInternalInitialize(ClientConfiguration config, OutsideRuntimeClient runtimeClient)
   at Orleans.GrainClient.<>c__DisplayClass1.<InternalInitialize>b__0(Object state)" TraceSource="w3wp.exe"

Sadly none of them brings me any useful information about what happens

**Comment by sergeybykov** [comment]
I believe https://github.com/dotnet/orleans/pull/1194 was meant to improve the error message. Can you try with the latest master?

**Comment by astaror** [comment]
Thank you, Sergey!
I updated to latest build (1.2.0).
I can't confirm error message was improved, but now WebRole properly connecting to WorkerRole and no error messages are appearing :)
Thank you once more!

**Comment by sergeybykov** [comment]
Hmm, it didn't work with 1.1.0, and now it does with master? It would help to know what's changed.

**Comment by gabikliot** [comment]
It "clearly" says: "Exc level 2: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list." in `Orleans.Runtime.TraceLogger.Initialize`.

It was fixed in https://github.com/dotnet/orleans/pull/1134.
