### ISSUE TITLE
v1.1.0 not working with VB in Azure Worker Role

### ISSUE THREAD

**Issue by BenjaminGibbs** [dotnet/orleans#1237]
I tried to update my codebase from V1.0.10 to V1.1.0 before Christmas but when I did so the client and the server would not seem to connect.

So have come back to the problem now I am back at work, here is what I see and how I can replicate it.

So I have a new project (Client Web Role, Host Worker Role, Grains Project, Interface Project) pretty much all standard stuff using V.1.0.10 and it all works as expected and fine.

When I upgrade to V1.10.0, (being VB I have to remove two nugets from the grain and interface project so it just leaves the Orleans core nugget.) The web client just hangs and does not connect.

So I see the following:
-The Client does not progress past the line of code `AzureClient.Initialize`
-The azure membership table is populated with data from the host.
-No log is created on the client.
-The following is output in to the console...

```
iisexpress.exe Information: 0 : Pausing 00:00:05 awaiting silo and gateways registration for Deployment=deployment27(86)
iisexpress.exe Error: 0 : iisexpress.exe Error: 0 : Client.Initialize failed with exc -- One or more errors occurred.. Will try again
iisexpress.exe Error: 0 : Client.Initialize failed with exc -- One or more errors occurred.. Will try again
```
and then eventually this appears...
```
iisexpress.exe Error: 0 : Error starting Orleans Azure client application -- Could not Initialize Client for DeploymentId=deployment27(86). Last exception=One or more errors occurred. -- bailing. 
Exc level 0: Orleans.Runtime.OrleansException: Could not Initialize Client for DeploymentId=deployment27(86). Last exception=One or more errors occurred.
Exc level 1: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Orleans.GrainClient.InternalInitialize(ClientConfiguration config, OutsideRuntimeClient runtimeClient)
   at Orleans.Runtime.Host.AzureClient.InitializeImpl_FromConfig(ClientConfiguration config)
Exc level 2: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.Diagnostics.TraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String format, Object[] args)
   at System.Diagnostics.TraceInternal.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
   at Orleans.Runtime.TraceLogger.Initialize(ITraceConfiguration config, Boolean configChange)
   at Orleans.OutsideRuntimeClient..ctor(ClientConfiguration cfg, GrainFactory grainFactory, Boolean secondary)
   at Orleans.GrainClient.DoInternalInitialize(ClientConfiguration config, OutsideRuntimeClient runtimeClient)
   at Orleans.GrainClient.<>c__DisplayClass1.<InternalInitialize>b__0(Object state)
```

**Comment by BenjaminGibbs** [comment]
This looks like it is the same as #1230 and @gabikliot says it was fixed in #1134 - Hoping so.

**Comment by gabikliot** [comment]
It's definitely the same issue and indeed was fixed.

**Comment by gabikliot** [comment]
@Sergeybykov, it almost feels like we need to patch 1.1.0, otherwise people will keep hitting those and some may just walk away without trying latest master.

**Comment by ReubenBond** [comment]
@gabikliot would releasing 1.1.1 be sufficient?

**Comment by gabikliot** [comment]
sure. which ever the guys prefer.

**Comment by sergeybykov** [comment]
I think we should patch v1.1.0 indeed and release v1.1.1. DO we just need https://github.com/sebastianburckhardt/orleans/commit/41649d0347081fc7aeae3fc02d340fd13d1f4246 cherry-picked?

**Comment by gabikliot** [comment]
yes
