### ISSUE TITLE
GrainClient initialization fails quickly when no silos are available yet

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#1299]
Since merging #1017, the dev/test experience for `GrainClient` is a little rough. If I start a client + silo simultaneously from VS, then the client will fail to initialize several times before the silo completes its own initialization. This behavior is worse than before and the error is opaque.

Initialization throws this exception from https://github.com/dotnet/orleans/blob/8cf4d8efb018c84558cb7e4b67f42f1647c26bc2/src/Orleans/Runtime/OutsideRuntimeClient.cs#L291:
```
The target silo became unavailable for message: 
Request *cli/4dc05db6@976b71aa->S192.168.0.20:30000:190892127TypeManagerId@S00000011
#2: global::Orleans.Runtime.ITypeManager:GetTypeCodeMap(). 
Target History is: <S192.168.0.20:30000:190892127:TypeManagerId:@S00000011>
```

Could we have `GrainClient` wait until it successfully identifies an active silo before continuing with initialization?

**Comment by gabikliot** [comment]
@reubenbond, can you please share the client log, with this setup and those errors?

**Comment by ReubenBond** [comment]
Repro doesn't require starting a silo at all, so here's [the log](https://gist.github.com/ReubenBond/f5c640dc0d2ca1a697b6) for just the client.
The logs don't seem to include this entry, which I can see in the console:
```
[2016-01-19 20:47:38.403 GMT     4      INFO    100000  OutsideRuntimeClient    127.0.0.1:0]    OutsideRuntimeClient.ConstructorReset(): client Id *cli/caf01f89

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Orleans.Runtime.SiloUnavailableException: The target silo became unavailable for message: Request *cli/caf01f89@a1747d89->S192.168.0.20:30000:190896762TypeManagerId@S00000011 #2: global::Orleans.Runtime.ITypeManager:GetTypeCodeMap(). Target History is: <S192.168.0.20:30000:190896762:TypeManagerId:@S00000011>
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__0`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Orleans.OutsideRuntimeClient.StartInternal()
   at Orleans.OutsideRuntimeClient.Start()
   at Orleans.GrainClient.DoInternalInitialize(ClientConfiguration config, OutsideRuntimeClient runtimeClient)
   at Orleans.GrainClient.<>c__DisplayClass1.<InternalInitialize>b__0(Object state)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Orleans.GrainClient.InternalInitialize(ClientConfiguration config, OutsideRuntimeClient runtimeClient)
   at Orleans.GrainClient.Initialize(ClientConfiguration config)
   at Web.Startup.Configuration(IAppBuilder app) in C:\dev\Otterpop\Web\Startup.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at Web.Program.Main(String[] args) in C:\dev\app\Web\Program.cs:line 29
```

**Comment by gabikliot** [comment]
I think I understand what happens here:
1) You had a running service (most probably in your local dev cluster, not in Azure).
2) You stopped it abruptly (or it just failed), without a graceful shutdown.
3) Some silos were left in the table in the Active mode.
4) You restarted the cluster with the same deployment id (`dev`)
5) the client started before the silo did, it found the record for previous Active silo and tried to connect to it. Since the silo was not up yet, it fails to connect to it. 
6) In the meanwhile, the silo maybe restarts, marks it old record as dead and client gives up on trying to connect to this silo since this silo is dead now.
7) This instance of a client fails and restarts, but later on we create a new client and it eventually connects correctly.

Is my Sherlock description correct? You clearly cannot validate 6, but you can validate 1-4 and most importantly 7.
Basically, and please correct if I am wrong, all works fine, the client connects correctly at the end, what changed is while client is trying to connect you now see a weird exceptions about Dead silos, while before you saw Timeouts. And of course, none of that would happen in prod in Azure since you would be using a new deployment id each re-deploy.

**So there is no bugs, all works correctly, just our logging became more obscure.** Right?

We can definitekky improve the logging in this scenario. There are multiple ways we can go about it, like have different logging in different stages of client life-cycle,...
But I think the simplest way is:
catch the exception throw in https://github.com/dotnet/orleans/blob/8cf4d8efb018c84558cb7e4b67f42f1647c26bc2/src/Orleans/Runtime/OutsideRuntimeClient.cs#L291:, analyse it and if it is indeed `Orleans.Runtime.SiloUnavailableException`, just in this case of client init, re-throw a more meaningful exception, like "Client failed to connect to the cluster, since did not yet find any alive silo. Please retry". Do the same if exc is a timeout exc. If it is anything else, re-throw as is.

What do you think?

**Comment by ReubenBond** [comment]
Closing because I haven't had time to pursue this. Can reopen if someone else runs into it. I think you're right, Gabi: it's not a functionality bug.

**Comment by nadyai** [comment]
Hi, 
I have experienced the same problem. The problem occurs during debugging. Clean, rebuild, restart (studio, machine) wasn't helping.
Temp solution for me is to catch the first exception and try to Initialise one more time. The second time everything is fine and I don't have exception... Looks like if GrainClient.Initialize fails, it does some helpful cleaning...
try
{
                GrainClient.Initialize(AppDomain.CurrentDomain.BaseDirectory + "\\ClientConfiguration.xml");
}
catch (Exception e)
{
                Console.WriteLine(e);
}
GrainClient.Initialize(AppDomain.CurrentDomain.BaseDirectory + "\\ClientConfiguration.xml");

**Comment by HokkyTj** [comment]
Start the server then you can debug the client.
