### ISSUE TITLE
TestingSiloHost - UniTest fails randomly with exceptions

### ISSUE THREAD

**Issue by angshuman-agarwal** [dotnet/orleans#1310]
Hi,
The UnitTests fail randomly with the following error on build server and locally too sometimes. I have followed the document on UnitTest [here](http://dotnet.github.io/orleans/Step-by-step-Tutorials/Unit-Testing-Grains). Not able to think why it is so random. I am using Orleans 1.1.0.

```
  [2016-01-21 11:30:47.017 GMT    11	INFO   	100294	SystemStatus	127.0.0.1:22223]	SystemStatus=Terminated	
  [2016-01-21 11:30:47.017 GMT    11	INFO   	100294	SystemStatus	127.0.0.1:22223]	SystemStatus=Terminated	
  [2016-01-21 11:30:47.017 GMT    11	INFO   	100413	Silo	127.0.0.1:22223]	Silo is Stopped()	
  [2016-01-21 11:30:47.017 GMT    11	INFO   	100413	Silo	127.0.0.1:22223]	Silo is Stopped()

...
....


Runtime.GrainDirectory.AdaptiveDirectoryCacheMaintainer`1 that runs on managed thread 16	
  [2016-01-21 11:30:47.037 GMT    77	INFO   	100328	Runtime.Watchdog	127.0.0.1:22223]	Stopping AsyncAgent Runtime.Watchdog that runs on managed thread 77	
  [2016-01-21 11:30:47.060 GMT    11	INFO   	100294	SystemStatus	127.0.0.1:22222]	SystemStatus=ShuttingDown	
  [2016-01-21 11:30:47.060 GMT    11	INFO   	100294	SystemStatus	127.0.0.1:22222]	SystemStatus=ShuttingDown	
  [2016-01-21 11:30:47.060 GMT    11	INFO   	100417	Silo	127.0.0.1:22222]	Silo starting to Shutdown()	
  [2016-01-21 11:30:47.060 GMT    11	INFO   	100417	Silo	127.0.0.1:22222]	Silo starting to Shutdown()	
  [2016-01-21 11:30:47.063 GMT    85	INFO   	100606	MembershipOracle	127.0.0.1:22222]	-ShutDown	
  [2016-01-21 11:30:47.063 GMT    85	INFO   	100606	MembershipOracle	127.0.0.1:22222]	-ShutDown	
  [2016-01-21 11:30:47.070 GMT    89	INFO   	102927	ReminderService	127.0.0.1:22222]	Stopping reminder system target	
  [2016-01-21 11:30:47.070 GMT    89	INFO   	102927	ReminderService	127.0.0.1:22222]	Stopping reminder system target	
  [2016-01-21 11:30:47.074 GMT    11	INFO   	100545	Catalog	127.0.0.1:22222]	DeactivateAllActivations.	
  [2016-01-21 11:30:47.074 GMT    11	INFO   	100545	Catalog	127.0.0.1:22222]	DeactivateAllActivations.	
  [2016-01-21 11:30:47.083 GMT    11	INFO   	100541	Catalog	127.0.0.1:22222]	DeactivateActivations: total 1 to shutdown, out of them 1 promptly, 0 later when become idle and 0 are already being destroyed or invalid.	
  [2016-01-21 11:30:47.083 GMT    11	INFO   	100541	Catalog	127.0.0.1:22222]	DeactivateActivations: total 1 to shutdown, out of them 1 promptly, 0 later when become idle and 0 are already being destroyed or invalid.	
  [2016-01-21 11:30:47.087 GMT    11	INFO   	100503	Catalog	127.0.0.1:22222]	Starting DestroyActivations #0 of 1 activations	
  [2016-01-21 11:30:47.087 GMT    11	INFO   	100503	Catalog	127.0.0.1:22222]	Starting DestroyActivations #0 of 1 activations	
  [2016-01-21 11:30:47.110 GMT    91	WARNING	100506	Catalog	127.0.0.1:22222]	AllActiveSilos SiloStatusOracle.GetApproximateSiloStatuses empty	
  [2016-01-21 11:30:47.110 GMT    91	WARNING	100506	Catalog	127.0.0.1:22222]	AllActiveSilos SiloStatusOracle.GetApproximateSiloStatuses empty	
  [2016-01-21 11:30:47.115 GMT    85	INFO   	100147	Dispatcher	127.0.0.1:22222]	Intermediate NonExistentActivation for message NewPlacement Request S127.0.0.1:22222:191071838*grn/4D0D8712/00000000+ISF.L@975366a0->S127.0.0.1:22222:191071838*grn/716E8E94/e8009d81+SMSProvider_Price@6174f6bc #117: global::Orleans.Streams.IPubSubRendezvousGrain:UnregisterProducer()	
  [2016-01-21 11:30:47.115 GMT    85	INFO   	100147	Dispatcher	127.0.0.1:22222]	Intermediate NonExistentActivation for message NewPlacement Request S127.0.0.1:22222:191071838*grn/4D0D8712/00000000+ISF.L@975366a0->S127.0.0.1:22222:191071838*grn/716E8E94/e8009d81+SMSProvider_Price@6174f6bc #117: global::Orleans.Streams.IPubSubRendezvousGrain:UnregisterProducer()	
  Grain directory is stopping
  Exception = System.InvalidOperationException: Grain directory is stopping
     at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterAsyncImpl(ActivationAddress addr, Boolean force)
     at Orleans.Runtime.Dispatcher.<>c__DisplayClass4.<<ReceiveMessage>b__0>d__6.MoveNext()
  
  [2016-01-21 11:30:47.118 GMT    88	WARNING	101535	Dispatcher	127.0.0.1:22222]	Failed to un-register NonExistentActivation S127.0.0.1:22222:191071838*grn/716E8E94/e8009d81+SMSProvider_Price@6174f6bc	
  Exc level 0: System.InvalidOperationException: Grain directory is stopping
     at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterAsyncImpl(ActivationAddress addr, Boolean force)
     at Orleans.Runtime.Dispatcher.<>c__DisplayClass4.<<ReceiveMessage>b__0>d__6.MoveNext()
  [2016-01-21 11:30:47.118 GMT    88	WARNING	101535	Dispatcher	127.0.0.1:22222]	Failed to un-register NonExistentActivation S127.0.0.1:22222:191071838*grn/716E8E94/e8009d81+SMSProvider_Price@6174f6bc	
  Exc level 0: System.InvalidOperationException: Grain directory is stopping
     at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterAsyncImpl(ActivationAddress addr, Boolean force)
     at Orleans.Runtime.Dispatcher.<>c__DisplayClass4.<<ReceiveMessage>b__0>d__6.MoveNext()
  [2016-01-21 11:30:47.125 GMT    88	INFO   	101031	Dispatcher	127.0.0.1:22222]	Trying to forward after Non-existent activation, ForwardCount = 0. Message NewPlacement Request S127.0.0.1:22222:191071838*grn/4D0D8712/00000000+ISF.L@975366a0->S127.0.0.1:22222:191071838*grn/716E8E94/e8009d81+SMSProvider_Price@6174f6bc #117: 
```

**Comment by somnathnitb** [comment]
Are the tests which uses orleans streams fail intermittently?

**Comment by gabikliot** [comment]
This looks like an error in the log, not an actual exception that escapes outside the silo. This particular log error is also sort of legit - some benign shutdown race, which we handle correctly.  
So if tests are failing, you need to provide more info.
