### ISSUE TITLE
Problems following Running in a Stand-Alone Silo Tutorial

### ISSUE THREAD

**Issue by apuchkov** [dotnet/orleans#1317]
I added Microsoft.Orleans.OrleansHost NuGet package to my grains collection project.

Then I updated Start Action by filling in "Start external program" and "Working directory":
![image](https://cloud.githubusercontent.com/assets/150003/12515492/b50d3334-c0f6-11e5-99a0-281f957bae91.png)

When I click Ctrl + F5 Host console window appears for a split second with errors below and closes by itself.
![orleanshost](https://cloud.githubusercontent.com/assets/150003/12515476/9362fda4-c0f6-11e5-8ef8-5275f0242fc1.png)

I guess the problem is that OrleansHost cannot find a configuration file. However, tutorial page doesn't say how configuration file should be set up. 

I tried to copy DevTestServerConfiguration.xml from SiloHost project to bin\Debug folder of grain collection project and rename it to orleans.config.

It went further, but still didn't start successfully. Log files it produced are listed below.

**CWI-ALEX-StartupError-2016-01-22-16.10.44.411Z.txt**
```
2016-01-22-16.10.44.411ZZ
ERROR starting Orleans silo name=CWI-ALEX Exception=
Exc level 0: System.MissingMethodException: Method not found: 'System.String Orleans.Runtime.TypeUtils.GetParseableName(System.Type, System.String, Boolean, Boolean)'.
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssemblies(Assembly[] inputs)
   at Orleans.CodeGeneration.CodeGeneratorManager.GenerateAndCacheCodeForAllAssemblies()
   at Orleans.Runtime.GrainTypeManager.Start(Boolean strict)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo()
```

**CWI-ALEX-2016-01-22-16.10.41.159Z.log**
```
[2016-01-22 16:10:43.172 GMT     1	INFO   	100404	Silo	127.0.0.1:11111]	Silo starting with GC settings: ServerGC=False GCLatencyMode=Interactive	
[2016-01-22 16:10:43.176 GMT     1	WARNING	100405	Silo	127.0.0.1:11111]	Note: Silo not running with ServerGC turned on or with GCLatencyMode.Batch enabled - recommend checking app config : <configuration>-<runtime>-<gcServer enabled="true"> and <configuration>-<runtime>-<gcConcurrent enabled="false"/>	
[2016-01-22 16:10:43.177 GMT     1	INFO   	100403	Silo	127.0.0.1:11111]	-------------- Initializing Primary silo on host CWI-ALEX MachineName CWI-ALEX at 127.0.0.1:11111, gen 191175043 --------------	
[2016-01-22 16:10:43.192 GMT     1	INFO   	100415	Silo	127.0.0.1:11111]	Starting silo CWI-ALEX with runtime Version='1.1.2.0 (Release).' .NET version='4.0.30319.42000' Is .NET 4.5=True OS version='Microsoft Windows NT 6.2.9200.0' Config= 
Config File Name: C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\orleans.config
Host: CWI-ALEX
Start time: 2016-01-22 16:10:43.179 GMT
Primary node: 127.0.0.1:11111
Platform version info:
   .NET version: 4.0.30319.42000
   Is .NET 4.5=True
   OS version: Microsoft Windows NT 6.2.9200.0
   GC Type=Client GCLatencyMode=Interactive
Global configuration:
   System Ids:
      ServiceId: 00000000-0000-0000-0000-000000000000
      DeploymentId: apuchkov
   Subnet: 
   Seed nodes: 127.0.0.1:11111
   Messaging:
       Response timeout: 00:30:00
       Maximum resend count: 0
       Resend On Timeout: False
       Maximum Socket Age: 10675199.02:48:05.4775807
       Drop Expired Messages: True
       Silo Sender queues: 8
       Gateway Sender queues: 8
       Use standard (.NET) serializer: False
       Use fallback json serializer: False
       Buffer Pool Buffer Size: 4096
       Buffer Pool Max Size: 10000
       Buffer Pool Preallocation Size: 250
       Use Message Batching: False
       Max Message Batching Size: 10
       Maximum forward count: 2
   Liveness:
      LivenessEnabled: True
      LivenessType: MembershipTableGrain
      ProbeTimeout: 00:00:10
      TableRefreshTimeout: 00:01:00
      DeathVoteExpirationTimeout: 00:02:00
      NumMissedProbesLimit: 3
      NumProbedSilos: 3
      NumVotesForDeathDeclaration: 2
      UseLivenessGossip: True
      IAmAliveTablePublishTimeout: 00:05:00
      NumMissedTableIAmAliveLimit: 2
      MaxJoinAttemptTime: 00:05:00
      ExpectedClusterSize: 20
   SystemStore:
      SystemStore ConnectionString: null
      Reminders ConnectionString: null
   Application:
      Defaults:
         Deactivate if idle for: 02:00:00

   PlacementStrategy: 
         Default Placement Strategy: RandomPlacement
         Deployment Load Publisher Refresh Time: 00:00:01
         Activation CountBased Placement Choose Out Of: 2
   Grain directory cache:
      Maximum size: 1000000 grains
      Initial TTL: 00:00:30
      Maximum TTL: 00:04:00
      TTL extension factor: 2.00
      Directory Caching Strategy: Adaptive
   Grain directory:
      Lazy deregistration delay: 00:01:00
      Client registration refresh: 00:05:00
   Reminder Service:
       ReminderServiceType: ReminderTableGrain
   Consistent Ring:
       Use Virtual Buckets Consistent Ring: True
       Num Virtual Buckets Consistent Ring: 30
   Providers:
       StorageProviders:
           Name=MemoryStore, Type=Orleans.Storage.MemoryStorage, Properties=[]

Silo configuration:
   Silo Name: CWI-ALEX
   Generation: 191175043
   Host Name or IP Address: localhost
   DNS Host Name: CWI-ALEX
   Port: 11111
   Subnet: 
   Preferred Address Family: InterNetwork
   Proxy Gateway: 127.0.0.1:30000
   IsPrimaryNode: True
   Scheduler: 
         Max Active Threads: 8
         Processor Count: 8
         Delay Warning Threshold: 00:00:10
         Activation Scheduling Quantum: 00:00:00.1000000
         Turn Warning Length Threshold: 00:00:00.2000000
         Inject More Worker Threads: False
         MinDotNetThreadPoolSize: 200
         .NET thread pool sizes - Min: Worker Threads=8 Completion Port Threads=8
         .NET thread pool sizes - Max: Worker Threads=32767 Completion Port Threads=1000
         .NET ServicePointManager - DefaultConnectionLimit=200 Expect100Continue=False UseNagleAlgorithm=False
   Load Shedding Enabled: False
   Load Shedding Limit: 95
   SiloShutdownEventName: 
   Debug: 
   Tracing: 
     Default Trace Level: Info
     TraceLevelOverrides:
         Application ==> Info
     Trace to Console: True
     Trace File Name: C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\CWI-ALEX-2016-01-22-16.10.41.159Z.log
     Write Messaging Traces: False
     LargeMessageWarningThreshold: 85000
     PropagateActivityId: False
     BulkMessageLimit: 5
   Statistics: 
     MetricsTableWriteInterval: 00:00:30
     PerfCounterWriteInterval: 00:00:30
     LogWriteInterval: 00:05:00
     WriteLogStatisticsToTable: True
     StatisticsCollectionLevel: Info

	
[2016-01-22 16:10:43.227 GMT     1	WARNING	103801	CodeGenerator	127.0.0.1:11111]	Exception generating code for input assembly OrleansDependencyInjection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Exception: 
Exc level 0: System.MissingMethodException: Method not found: 'System.String Orleans.Runtime.TypeUtils.GetParseableName(System.Type, System.String, Boolean, Boolean)'.
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssembly(Assembly input)	
Exc level 0: System.MissingMethodException: Method not found: 'System.String Orleans.Runtime.TypeUtils.GetParseableName(System.Type, System.String, Boolean, Boolean)'.
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssembly(Assembly input)
[2016-01-22 16:10:43.238 GMT     1	INFO   	100445	Silo	127.0.0.1:11111]	Successfully loaded Orleans.Runtime.Startup.ConfigureStartupBuilder from OrleansDependencyInjection.dll	
[2016-01-22 16:10:43.294 GMT     1	WARNING	100447	Silo	127.0.0.1:11111]	Caught a FileNotFoundException calling ConfigureStartup(). Ignoring it. {0}	
Exc level 0: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
   at Orleans.Runtime.Startup.ConfigureStartupBuilder.ConfigureStartup(String startupTypeName)
   at Orleans.Runtime.Startup.ConfigureStartupBuilder.Orleans.Runtime.Startup.IStartupBuilder.ConfigureStartup(String startupTypeName)
   at Orleans.Runtime.Silo..ctor(String name, SiloType siloType, ClusterConfiguration config, ILocalDataStore keyStore)
[2016-01-22 16:10:43.910 GMT     1	INFO   	100000	Scheduler.OrleansTaskScheduler	127.0.0.1:11111]	Starting OrleansTaskScheduler with 8 Max Active application Threads and 1 system thread.	
[2016-01-22 16:10:43.918 GMT     1	INFO   	101010	Runtime.Messaging.IncomingMessageAcceptor	127.0.0.1:11111]	Opened a listening socket at address 127.0.0.1:11111	
[2016-01-22 16:10:43.925 GMT     1	INFO   	101010	Runtime.Messaging.GatewayAcceptor	127.0.0.1:11111]	Opened a listening socket at address 127.0.0.1:30000	
[2016-01-22 16:10:43.948 GMT     1	INFO   	100000	VirtualBucketsRingProvider	127.0.0.1:11111]	Starting VirtualBucketsRingProvider on silo S127.0.0.1:11111:191175043/x522B047C.	
[2016-01-22 16:10:43.980 GMT     1	INFO   	103003	VirtualBucketsRingProvider	127.0.0.1:11111]	Added Server S127.0.0.1:11111:191175043/x522B047C. Current view: [S127.0.0.1:11111:191175043 -> <MultiRange: Size=x100000000, %Ring=100.000%>]	
[2016-01-22 16:10:43.984 GMT     1	INFO   	103005	VirtualBucketsRingProvider	127.0.0.1:11111]	-NotifyLocalRangeSubscribers about old <(0 0], Size=x100000000, %Ring=100.000%> new <MultiRange: Size=x100000000, %Ring=100.000%> increased? True	
[2016-01-22 16:10:44.007 GMT     1	INFO   	100294	SystemStatus	127.0.0.1:11111]	SystemStatus=Created	
[2016-01-22 16:10:44.009 GMT     1	INFO   	100422	Silo	127.0.0.1:11111]	-------------- Started silo S127.0.0.1:11111:191175043, ConsistentHashCode 522B047C --------------	
[2016-01-22 16:10:44.012 GMT     1	INFO   	100441	OrleansSiloHost	127.0.0.1:11111]	Silo shutdown event name: CWI-ALEX-Shutdown	
[2016-01-22 16:10:44.013 GMT     1	INFO   	100442	OrleansSiloHost	127.0.0.1:11111]	Created and set shutdown event CWI-ALEX-Shutdown	
[2016-01-22 16:10:44.017 GMT     1	INFO   	100294	SystemStatus	127.0.0.1:11111]	SystemStatus=Starting	
[2016-01-22 16:10:44.019 GMT     1	INFO   	100401	Silo	127.0.0.1:11111]	Silo Start()	
[2016-01-22 16:10:44.020 GMT     1	INFO   	100430	Silo	127.0.0.1:11111]	Configured ThreadPool.SetMinThreads() to values: 200,200. Previous values are: 8,8.	
[2016-01-22 16:10:44.022 GMT     1	INFO   	100436	Silo	127.0.0.1:11111]	Configured .NET ServicePointManager to Expect100Continue=False, DefaultConnectionLimit=200, UseNagleAlgorithm=False to improve Azure storage performance.	
[2016-01-22 16:10:44.040 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	Searching for assemblies in C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug...	
[2016-01-22 16:10:44.055 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	User assembly ignored: C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\GrainInterfaces1.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2016-01-22 16:10:44.217 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	User assembly ignored: C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\Microsoft.CodeAnalysis.CSharp.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2016-01-22 16:10:44.290 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	User assembly ignored: C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\Microsoft.CodeAnalysis.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2016-01-22 16:10:44.305 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	User assembly ignored: C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\Newtonsoft.Json.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2016-01-22 16:10:44.307 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	User assembly ignored: C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\Orleans.dll
	* Assembly filename is excluded.	
[2016-01-22 16:10:44.308 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	User assembly ignored: C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\OrleansCodeGenerator.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2016-01-22 16:10:44.310 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	User assembly ignored: C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\OrleansDependencyInjection.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2016-01-22 16:10:44.311 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	User assembly ignored: C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\OrleansRuntime.dll
	* Assembly filename is excluded.	
[2016-01-22 16:10:44.320 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	User assembly ignored: C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\System.Collections.Immutable.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2016-01-22 16:10:44.333 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	User assembly ignored: C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\System.Reflection.Metadata.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2016-01-22 16:10:44.334 GMT     1	WARNING	101705	AssemblyLoader.Silo	127.0.0.1:11111]	Unable to find directory C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\Applications; skipping.	
[2016-01-22 16:10:44.335 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	Loading assembly C:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\bin\Debug\Grains1.dll...	
[2016-01-22 16:10:44.359 GMT     1	WARNING	103801	CodeGenerator	127.0.0.1:11111]	Exception generating code for input assembly Grains1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Exception: 
Exc level 0: System.MissingMethodException: Method not found: 'System.String Orleans.Runtime.TypeUtils.GetParseableName(System.Type, System.String, Boolean, Boolean)'.
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssembly(Assembly input)	
Exc level 0: System.MissingMethodException: Method not found: 'System.String Orleans.Runtime.TypeUtils.GetParseableName(System.Type, System.String, Boolean, Boolean)'.
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssembly(Assembly input)
[2016-01-22 16:10:44.367 GMT     1	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:11111]	1 assemblies loaded.	
[2016-01-22 16:10:44.386 GMT     1	WARNING	103801	CodeGenerator	127.0.0.1:11111]	Exception generating code for input assemblies:
OrleansDependencyInjection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Grains1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Exception: 
Exc level 0: System.MissingMethodException: Method not found: 'System.String Orleans.Runtime.TypeUtils.GetParseableName(System.Type, System.String, Boolean, Boolean)'.
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssemblies(Assembly[] inputs)	
Exc level 0: System.MissingMethodException: Method not found: 'System.String Orleans.Runtime.TypeUtils.GetParseableName(System.Type, System.String, Boolean, Boolean)'.
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssemblies(Assembly[] inputs)
[2016-01-22 16:10:44.396 GMT     1	ERROR  	100439	Silo	127.0.0.1:11111]	!!!!!!!!!! Exception during Silo.Start	
Exc level 0: System.MissingMethodException: Method not found: 'System.String Orleans.Runtime.TypeUtils.GetParseableName(System.Type, System.String, Boolean, Boolean)'.
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssemblies(Assembly[] inputs)
   at Orleans.CodeGeneration.CodeGeneratorManager.GenerateAndCacheCodeForAllAssemblies()
   at Orleans.Runtime.GrainTypeManager.Start(Boolean strict)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
[2016-01-22 16:10:44.407 GMT     1	ERROR  	100105	OrleansSiloHost	127.0.0.1:11111]	!!!!!!!!!! ERROR starting Orleans silo name=CWI-ALEX Exception=
Exc level 0: System.MissingMethodException: Method not found: 'System.String Orleans.Runtime.TypeUtils.GetParseableName(System.Type, System.String, Boolean, Boolean)'.
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssemblies(Assembly[] inputs)
   at Orleans.CodeGeneration.CodeGeneratorManager.GenerateAndCacheCodeForAllAssemblies()
   at Orleans.Runtime.GrainTypeManager.Start(Boolean strict)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo()	
Exc level 0: System.MissingMethodException: Method not found: 'System.String Orleans.Runtime.TypeUtils.GetParseableName(System.Type, System.String, Boolean, Boolean)'.
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssemblies(Assembly[] inputs)
   at Orleans.CodeGeneration.CodeGeneratorManager.GenerateAndCacheCodeForAllAssemblies()
   at Orleans.Runtime.GrainTypeManager.Start(Boolean strict)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo()
[2016-01-22 16:10:44.416 GMT     2	WARNING	100220	Silo	127.0.0.1:11111]	Process is exiting	
```

**Comment by sergeybykov** [comment]
Confirmed. This piece of the tutorial is seriously broken with the current version of the codebase.

Thanks for reporting it, @apuchkov!

**Comment by sergeybykov** [comment]
I see several issues here.

1.The projects created with the VSIX reference Orleans NuGet packages 1.1.0. When I follow the step of adding https://www.nuget.org/packages/Microsoft.Orleans.OrleansHost, it comes as 1.2.0 along with its dependencies, and the version mismatch causes the "Method not found" error.

2. OrleansConfiguration.xml is missing.

3. Even if I manually drag OrleansConfiguration.xml from existing Dev/Test Host project, it has a couple of providers defined that implicitly require https://www.nuget.org/packages/Microsoft.Orleans.OrleansProviders.

**Comment by CAH-FlyChen** [comment]
how can i fix this manually？

**Comment by ynevet** [comment]
Guys, any guidance of how to solve it? Thanks :)

**Comment by sergeybykov** [comment]
I updated http://dotnet.github.io/orleans/Step-by-step-Tutorials/Running-in-a-Stand-alone-Silo to the sequence that should work. We should significantly simplify it in 1.2.0 by switching to programmatic config.

Please confirm that the current version of the guide works for you with 1.1.3 NuGets.

**Comment by ynevet** [comment]
Excellent, it's working now.

I downloaded the Microsoft.Orleans.Server nuget package into the Grains project and change the ProxyingGateway port setting to 30000.

Thanks Sergey!

**Comment by sergeybykov** [comment]
@ynevet Thanks for verifying it!
