### ISSUE TITLE
Code generator exits with error code 3 when struct contains a static variable

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#1447]
Hi folks,

here I have a very strange issue which is very easy to reconstruct:

Create a new _GrainInterface_ project.

Add the following struct:

````csharp
namespace GrainInterfaces
{
	public struct MyStruct
	{
		public static readonly MyStruct? Empty = null;
	}
}
````

The code generator exits with error code 3.

Here is the contents of the generated error.txt file:

[--- SNIP --->>--- SNIP --->>--- SNIP --->>--- SNIP --->

Could not load file or assembly 'GrainInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.UnitySerializationHolder.GetRealObject(StreamingContext context)

   at Orleans.CodeGeneration.GrainClientGenerator.CreateGrainClient(CodeGenOptions options)
   at Orleans.CodeGeneration.GrainClientGenerator.CreateGrainClientAssembly(CodeGenOptions options)
   at Orleans.CodeGeneration.GrainClientGenerator.RunMain(String[] args)

]--- SNIP ---<<--- SNIP ---<<--- SNIP ---<<--- SNIP ---<

The error disappears if I change the read-only static variable into a property:

````csharp
namespace GrainInterfaces
{
	public struct MyStruct
	{
		public static MyStruct? Empty => null;
	}
}
````

The error with the static variable also appears if the struct is in a separate assembly as in my case. Fortunately it's not a third-party assembly, otherwise I would have a problem here.

**Comment by peter-perot** [comment]
Seems to be a compiler bug and not an Orleans issue. See discussion at https://github.com/dotnet/orleans/pull/1603.

**Comment by sergeybykov** [comment]
I think we should close this one, and keep https://github.com/dotnet/orleans/issues/1447 open until the compiler bug is fixed.

**Comment by peter-perot** [comment]
I opened a ticket here: https://github.com/dotnet/roslyn/issues/10126

Discussion at stackoverflow here: http://stackoverflow.com/questions/36222117/maybe-a-c-sharp-compiler-bug-in-visual-studio-2015
