### ISSUE TITLE
Cannot use Orleans in C# interactive window

### ISSUE THREAD

**Issue by amamh** [dotnet/orleans#1489]
I'm trying to find a way to quickly test my server changes. I thought of running from C# interactive window in VS.

I can connect fine, but once I try to get a grain I get the following error:

		> var g = GrainClient.GrainFactory.GetGrain<ICountryCostsGrain>(0);
		GenericArguments[0], 'Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax', on 'Microsoft.CodeAnalysis.SeparatedSyntaxList`1[TNode]' violates the constraint of type parameter 'TNode'.
		Exception = System.TypeLoadException: GenericArguments[0], 'Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax', on 'Microsoft.CodeAnalysis.SeparatedSyntaxList`1[TNode]' violates the constraint of type parameter 'TNode'.
		   at Orleans.CodeGenerator.GrainReferenceGenerator.GenerateClass(Type grainType, Action`1 onEncounteredType)
		   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
		   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssembly(Assembly input)

		[2016-02-22 12:08:52.058 GMT     6	WARNING	103801	CodeGenerator	169.183.186.58:0]	Exception generating code for input assembly Citi.Equities.Stella.Server.GrainInterfaces, Version=1.0.0.6, Culture=neutral, PublicKeyToken=null
		Exception: 
		Exc level 0: System.TypeLoadException: GenericArguments[0], 'Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax', on 'Microsoft.CodeAnalysis.SeparatedSyntaxList`1[TNode]' violates the constraint of type parameter 'TNode'.
		   at Orleans.CodeGenerator.GrainReferenceGenerator.GenerateClass(Type grainType, Action`1 onEncounteredType)
		   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
		   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssembly(Assembly input)	
		Exc level 0: System.TypeLoadException: GenericArguments[0], 'Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax', on 'Microsoft.CodeAnalysis.SeparatedSyntaxList`1[TNode]' violates the constraint of type parameter 'TNode'.
		   at Orleans.CodeGenerator.GrainReferenceGenerator.GenerateClass(Type grainType, Action`1 onEncounteredType)
		   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
		   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssembly(Assembly input)
		System.TypeLoadException: GenericArguments[0], 'Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax', on 'Microsoft.CodeAnalysis.SeparatedSyntaxList`1[TNode]' violates the constraint of type parameter 'TNode'.
		   at Orleans.CodeGenerator.GrainReferenceGenerator.GenerateClass(Type grainType, Action`1 onEncounteredType)
		   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
		   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssembly(Assembly input)
		   at Orleans.CodeGeneration.CodeGeneratorManager.GenerateAndCacheCodeForAssembly(Assembly input)
		   at Orleans.GrainFactory.MakeCaster(Type interfaceType)
		   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
		   at Orleans.GrainFactory.Cast(IAddressable grain, Type interfaceType)
		   at Orleans.GrainFactory.Cast[TGrainInterface](IAddressable grain)
		   at Orleans.GrainFactory.GetGrain[TGrainInterface](Int64 primaryKey, String grainClassNamePrefix)
		   at Submission#6.<<Initialize>>d__0.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__19.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.<>c__DisplayClass44_0.<<ExecuteOnUIThread>b__0>d.MoveNext()

Seems to be something about codegen.

**Is this currently a limitation or is there a way to run from C# interactive or a similar environment (shell)?**

**Comment by ReubenBond** [comment]
Which version of Orleans are you using? Would you be open to adding your company to the [Who Is Using Orleans](https://dotnet.github.io/orleans/Who-Is-Using-Orleans) page? You can do so by editing [this page](https://github.com/dotnet/orleans/blob/gh-pages/Who-Is-Using-Orleans.md).

**Comment by amamh** [comment]
@ReubenBond Hey, unfortunately we are no longer using it. There were some team changes and the project was cancelled.

I think the version was 1.1.2

**Comment by angshuman-agarwal** [comment]
@RubenBond I think Orleans needs more visibility and bit of marketing on its capabilities (like C#). As developers we are convinced but sometimes it becomes too hard to convince the outdated management. When we say Orleans, I see blank faces. Hope you understand the dilemma and the irony.

**Comment by ReubenBond** [comment]
Closed because the user is no longer using Orleans and hence doesn't have the issue. If someone else wants to explore this then they can open  a new issue.
