### ISSUE TITLE
Unsupported type 'Orleans.Runtime.GrainInterfaceMap' encountered. Perhaps you need to mark it [Serializable]

### ISSUE THREAD

**Issue by raunakm** [dotnet/orleans#1522]
I am trying out a simple client server type Orlean app on my local box where Silos are hosted in Orleans Dev/Test Host and my client is just simple Console

My host starts up correctly and from the client logs it seems client is able to connect to Host but throws following exception at Orleans.GrainClient.Initialize(). It seems I am missing something obvious but cannot pin point it. 
Both Host and the Client have reference to required interfaces

`!!!!!!!!!! Exception deserializing message body	
Exc level 0: System.Runtime.Serialization.SerializationException: Unsupported type 'Orleans.Runtime.GrainInterfaceMap' encountered. Perhaps you need to mark it [Serializable] or define a custom serializer for it?
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.Deserialize(BinaryTokenStreamReader stream)
   at Orleans.Runtime.Message.DeserializeBody(List`1 bytes)`

**Comment by sergeybykov** [comment]
I suspect you might have a version mismatch between the silo nd the client. Please check that you are referencing same version of NuGet packages in both projects.

**Comment by raunakm** [comment]
I knew I was missing something obvious. Thanks for pointing it out. It works now.
