### ISSUE TITLE
Grain Access Violation : "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

### ISSUE THREAD

**Issue by ozang** [dotnet/orleans#1548]
Hi, 

I got System.AccessViolationException after getting  a grain reference and call an interface method. What could be the problem?  

```
public interface IxGrain : IGrainWithGuidKey, IGrain, IAddressable
{
 	Task<string> Test();
}

 public class xGrain : Grain, IxGrain
 {
 	public Task<string> Test()
 	{
 		return Task.FromResult("Test String");
 	}
 }
 

 if (!GrainClient.IsInitialized) 
 {
 	GrainClient.Initialize("DevTestClientConfiguration.xml");
 }
 var xService = GrainClient.GrainFactory.GetGrain<IxGrain>(Guid.NewGuid());
 Task<string> result = xService.Test();
```

**Comment by sergeybykov** [comment]
What the call stack in the exception? I can't imagine Orleans being the culprit here but am curious.

**Comment by ozang** [comment]
Somehow Grain is corrupted.

```
   at Portfolio.AppService.ApplicationServiceImpls.PortfolioAppServiceImpl_ClientApi.TestOrleans() in ***\Portfolio.AppService\ApplicationServiceImpls\PortfolioAppServiceImpl_ClientApi.cs:line 269
   at InformixPofConcept.OrleansTest.TestOrleans() in ***\OrleansTest.cs:line 18
   at InformixPofConcept.Program.Main(String[] args) in ***\InformixPofConcept\Program.cs:line 24
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by sergeybykov** [comment]
I don't see any Orleans code on the stack.
