### ISSUE TITLE
Strange new issue starting silo

### ISSUE THREAD

**Issue by philippecp** [dotnet/orleans#1661]
For some reason I can no longer start an orleans silo. I haven't changed anything in code but now I get the following exception:

2016-04-07-13.35.15.496ZZ
ERROR starting Orleans silo name=[MyMachineName] Exception=
Exc level 0: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Orleans.Runtime.SocketManager.GetAcceptingSocketForEndpoint(IPEndPoint address)
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor..ctor(MessageCenter msgCtr, IPEndPoint here, SocketDirection socketDirection)
   at Orleans.Runtime.Messaging.MessageCenter.Initialize(IPEndPoint here, Int32 generation, IMessagingConfiguration config, ISiloPerformanceMetrics metrics)
   at Orleans.Runtime.Silo..ctor(String name, SiloType siloType, ClusterConfiguration config, ILocalDataStore keyStore)
   at Orleans.Runtime.Silo..ctor(String name, SiloType siloType, ClusterConfiguration config)
   at Orleans.Runtime.Host.SiloHost.InitializeOrleansSilo()2016-04-07-13.35.15.496ZZ
ERROR starting Orleans silo name=[MyMachineName] Exception=
Exc level 0: System.InvalidOperationException: Cannot start silo [MyMachineName] due to prior initialization error
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo()

Did anyone ever encounter something like this?

**Comment by philippecp** [comment]
Ok, found the problem. Turns out RedGate Ants Profiler also uses port 22222 which is the default port for orleans.

**Comment by jthelin** [comment]
X-ref: https://github.com/dotnet/orleans/issues/1663
