### ISSUE TITLE
Getting Error When running Orleans Service with SqlServer liveness 

### ISSUE THREAD

**Issue by dev-4488** [dotnet/orleans#1764]
Error:
Orleans.Runtime.OrleansException: Forwarding failed: tried to forward message NewPlacement Request S127.0.0.1:11111:200056186_cli/659ba489@d447fdbe->S127.0.0.1:11111:200056186_grn/CB1BA62C/00000000+1@126abf87 #16[ForwardCount=2]: global::ATI.Silo.Grains.SpeedGame.Interfaces.IMessageProcessorGrain:ProcessHubMessageJSON() for 2 times after Non-existent activation to invalid activation. Rejecting now. 
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ATI.Silo.SignalR.Adapter.SignalrAdapter.<Deserialize>d__c.MoveNext()
---> (Inner Exception #0) Orleans.Runtime.OrleansException: Forwarding failed: tried to forward message NewPlacement Request S127.0.0.1:11111:200056186_cli/659ba489@d447fdbe->S127.0.0.1:11111:200056186_grn/CB1BA62C/00000000+1@126abf87 #16[ForwardCount=2]: global::ATI.Silo.Grains.SpeedGame.Interfaces.IMessageProcessorGrain:ProcessHubMessageJSON() for 2 times after Non-existent activation to invalid activation. Rejecting now.

Client Configuration:
![image](https://cloud.githubusercontent.com/assets/13965580/15280731/711de884-1b51-11e6-8ed7-802e5f2a344c.png)

Server Configuration:

![image](https://cloud.githubusercontent.com/assets/13965580/15280751/ac1ef5cc-1b51-11e6-8caf-1abbf9f3013a.png)

Deployment Model:
Two Silo services running with above configuration on a load balanced environment
One of the instance always successfully process the message while other give the above mentioned EXCEPTION.
Also when we bring down the 1st instance the second one still logs error and does not process the messages.

Any pointers??

**Comment by sergeybykov** [comment]
Do you start two silos on the same node, both as 127.0.0.1:11111?

**Comment by dev-4488** [comment]
Yes, that part is incorrect .Got to know about it by looking at the documentation.
It is done now, in updated configuration we have left address to blank so the service makes entry using the IP of the machine.
However if you can point me to any documentation providing the meaning of various values in Status column in [OrleansMembershipTable] . it will be really helpful.
Thanks

**Comment by sergeybykov** [comment]
Is it working now? https://github.com/dotnet/orleans/blob/master/src/Orleans/Runtime/SiloStatus.cs has the `SiloStatus` enum values.

**Comment by dev-4488** [comment]
Thanks sergeybykov, for your inputs.
It is working now , but one of the instances logs this error in server log file:


Exception getting a sending socket to endpoint S172.26.61.80:11111:201155554	
Exc level 0: System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 172.26.61.80:11111
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Orleans.Runtime.SocketManager.SendingSocketCreator(IPEndPoint target)
   at Orleans.Runtime.LRU`2.Get(TKey key)
   at Orleans.Runtime.Messaging.SiloMessageSender.GetSendingSocket(Message msg, Socket& socket, SiloAddress& targetSilo, String& error)
[2016-05-17 04:35:39.073 GMT    20	VERBOSE 	101008	Runtime.Messaging.SiloMessageSender/PingSender	172.26.61.74:11111]	Silo S172.26.61.74:11111:201155708 is rejecting message: S172.26.61.74:11111:201155708. Reason = Request S172.26.61.74:11111:201155708MembershipOracle@S0000000f->S172.26.61.80:11111:201155554MembershipOracle@S0000000f #2: global::Orleans.Runtime.IMembershipService:Ping()	
[2016-05-17 04:35:39.089 GMT    20	VERBOSE 	100000	Message	172.26.61.74:11111]	Creating Transient rejection with info 'Silo S172.26.61.74:11111:201155708 is rejecting message: Request S172.26.61.74:11111:201155708MembershipOracle@S0000000f->S172.26.61.80:11111:201155554MembershipOracle@S0000000f #2: global::Orleans.Runtime.IMembershipService:Ping(). Reason = Exception getting a sending socket to endpoint S172.26.61.80:11111:201155554' for Request S172.26.61.74:11111:201155708MembershipOracle@S0000000f->S172.26.61.80:11111:201155554MembershipOracle@S0000000f #2: global::Orleans.Runtime.IMembershipService:Ping() at:
   at Orleans.Runtime.Message.CreateRejectionResponse(RejectionTypes type, String info)
   at Orleans.Runtime.Messaging.MessageCenter.SendRejection(Message msg, RejectionTypes rejectionType, String reason)
   at Orleans.Runtime.Messaging.SiloMessageSender.FailMessage(Message msg, String reason)
   at Orleans.Runtime.Messaging.SiloMessageSender.OnGetSendingSocketFailure(Message msg, String error)
   at Orleans.Messaging.OutgoingMessageSender.Process(Message msg)
   at Orleans.Runtime.AsynchQueueAgent`1.RunNonBatching()
   at Orleans.Runtime.AsynchQueueAgent`1.Run()
   at Orleans.Runtime.AsynchAgent.AgentThreadProc(Object obj)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

I know it not related to Orleans, but any pointers why it is occurring ?

**Comment by sergeybykov** [comment]
>Exception getting a sending socket to endpoint S172.26.61.80:11111

Apparently, it was trying to open a socket connection to this IP:port, and failed. Either the target silo wasn't there or a firewall prevented it from connecting. Can't tell more. But it's pretty basic IP networking here, no magic from Orleans.

**Comment by dev-4488** [comment]
Thanks sergeybykov

**Comment by dev-4488** [comment]
[2016-05-18 15:09:10.832 GMT    35	WARNING	100157	CallbackData	172.26.61.80:0]	Response did not arrive on time in 00:01:00 for message: Request *cli/5432d4b3@d3e79baa->S172.26.61.184:30000:201279460*grn/CB1BA62C/00000000+1 #67: global::ATI.Silo.Grains.SpeedGame.Interfaces.IMessageProcessorGrain:ProcessHubMessageJSON(). Target History is: <S172.26.61.184:30000:201279460:*grn/CB1BA62C/00000000+1:>. About to break its promise.

We have set the settings to use resend count of 2 also timeout value is 1 mins.
However once the service starts logging the exception , it never recovers from that and all the following messages log the same exception?

**Comment by sergeybykov** [comment]
@dev-4488 This one seems to have fallen through the cracks. Is this still an issue or you already resolved it?

**Comment by dev-4488** [comment]
Thanks Sergey for following up on this , yeah we were able to get it running.

**Comment by sergeybykov** [comment]
Thanks for confirming!

**Comment by vyshkant** [comment]
> Thanks sergeybykov, for your inputs.
> It is working now , but one of the instances logs this error in server log file:
> 
> Exception getting a sending socket to endpoint S172.26.61.80:11111:201155554
> Exc level 0: System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 172.26.61.80:11111
> I know it not related to Orleans, but any pointers why it is occurring ?

@dev-4488 What have you eventually done to get it working? (I mean this network error `Exception getting a sending socket to endpoint S172.26.61.80:11111:201155554`)
