### ISSUE TITLE
Warning from AssemblyLoader

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [dotnet/orleans#1781]
We have grains which need to access DB2 on zOS. For that we use IBM's ODBC driver and their wrapping of that driver for .net
However the first time we access the DB2, we get this warning from Orleans. I am not sure how to interpret this:

23-05-2016 21:23:54,521 WARN - AssemblyLoader encountered an exception loading types from assembly 'IBM.Data.DB2, Version=9.7.4.4, Culture=neutral, PublicKeyToken=7c307b91aa13d208': System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, TraceLogger logger) 
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, TraceLogger logger)

**Comment by jdom** [comment]
It's probably harmless. It just means that Orleans had some issues scanning the assembly for grain implementations, interfaces and serializable classes. If you have none of those in that assembly (which I guess that's true, since that's just IBM's wrapper from what you said), then you can safely ignore it.

**Comment by FenrisWolfAtMiddleEarth** [comment]
Ok. Thanks
