### ISSUE TITLE
Registering a timer in a grain from within Task.Run

### ISSUE THREAD

**Issue by t-rasmud** [dotnet/orleans#1824]
I am trying to register a timer in a grain and run into a null reference exception in the **Orleans.Runtimer.GrainTimer** constructor. Details are as follows:

Timer is registered using the statement:
` this.RegisterTimer(StartLeaderElection, null, TimeSpan.FromSeconds(2 + this.Random.Next(10)), TimeSpan.FromSeconds(2 + this.Random.Next(10)));`

where `StartLeaderElection` is defined as:
```
private Task StartLeaderElection(object args)
{
    this.BecomCandidate();
    return TaskDone.Done;
}
```
Exception details:
```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=OrleansRuntime
  StackTrace:
       at Orleans.Runtime.GrainTimer..ctor(Func`2 asyncCallback, Object state, TimeSpan dueTime, TimeSpan period, String name)
       at Orleans.Runtime.ActivationData.RegisterTimer(Func`2 asyncCallback, Object state, TimeSpan dueTime, TimeSpan period)
       at Orleans.Timers.TimerRegistry.RegisterTimer(Grain grain, Func`2 asyncCallback, Object state, TimeSpan dueTime, TimeSpan period)
       at Orleans.Grain.RegisterTimer(Func`2 asyncCallback, Object state, TimeSpan dueTime, TimeSpan period)
       at Raft.Grains.Server.BecomeFollower() in D:\PSharpModels\Orleans\Samples\OrleansRaft\Raft.Grains\Server.cs:line 180
       at Raft.Grains.Server.<>c__DisplayClass17_0.<Configure>b__0() in D:\PSharpModels\Orleans\Samples\OrleansRaft\Raft.Grains\Server.cs:line 155
       at System.Threading.Tasks.Task.Execute()
  InnerException: 

```

**Comment by gabikliot** [comment]
I think the reason is that you are calling the StartLeaderElection outside the Orleans scheduler.
Where this method is being called? Can you share the full grain method code that calls this method?

**Comment by t-rasmud** [comment]
```
  [Reentrant]
    public class Server : Grain<int>, IServer
    {
        public async Task Configure(int id, List<int> serverIds, int clusterId)
        {
            await Task.Run(() =>
            {
                if (this.Servers.Count == 0)
                {
                    ......
                    this.BecomeFollower();
                }
            });
        }

        private void BecomeFollower()
        {
                this.ElectionTimer = this.RegisterTimer(StartLeaderElection, null,
                    TimeSpan.FromSeconds(2 + this.Random.Next(10)), TimeSpan.FromSeconds(2 + this.Random.Next(10)));
        }

        private Task StartLeaderElection(object args)
        {
            this.BecomCandidate();
            return TaskDone.Done;
        }
    }
```

**Comment by gabikliot** [comment]
You cannot use task.run inside grain. it uses thread pool and breaks grain single threaded execution. Just remove it completely, you don't need it.

**Comment by gabikliot** [comment]
http://dotnet.github.io/orleans/Advanced-Concepts/External-Tasks-and-Grains
