### ISSUE TITLE
SQL Cluster OrleansMembershipTable Insert

### ISSUE THREAD

**Issue by hammie1010** [dotnet/orleans#1868]
When starting a SQL cluster the I get the following error message:

ERROR starting Orleans silo name=**TradingSilo** Exception=
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo(Boolean catchExceptions)
Exc level 1: Orleans.Runtime.OrleansException: -Silo S127.0.0.1:11111:204294043 failed to update its status to Joining in the table due to failures (socket failures or table read/write failures) after 32 attempts: ExecuteWithRetries has exceeded its max execution time of 00:05:00. Now is 2016-06-22 12:26:12.552 GMT, started at 2016-06-22 12:20:56.850 GMT, passed 00:05:15.7025671
   at Orleans.Runtime.MembershipService.MembershipOracle.<UpdateMyStatusGlobal>d__45.MoveNext()

 I checked the orleans tables - I have 1 record in [OrleansMembershipVersionTable] but nothing in the [OrleansMembershipTable] table.  When running SQL profiler the insert that is generated never passes in the SiloName so it always fails. I know my Silo has a name.  Am I missing something else? This is all version 1.2.2.0.

`exec sp_executesql N'
SET XACT_ABORT, NOCOUNT ON;
DECLARE @ROWCOUNT AS INT;
BEGIN TRANSACTION;
INSERT INTO OrleansMembershipTable
(
DeploymentId,
Address,
Port,
Generation,
SiloName,
HostName,
Status,
ProxyPort,
StartTime,
IAmAliveTime
)
SELECT 
@DeploymentId,
@Address,
@Port,
@Generation,
@SiloName,
@HostName,
@Status,
@ProxyPort,
@StartTime,
@IAmAliveTime
WHERE NOT EXISTS
(
SELECT 1
FROM
OrleansMembershipTable
WHERE 
DeploymentId = @DeploymentId AND @DeploymentId IS NOT NULL
AND Address = @Address AND @Address IS NOT NULL
AND Port = @Port AND @Port IS NOT NULL
AND Generation = @Generation AND @Generation IS NOT NULL
);

UPDATE OrleansMembershipVersionTable
SET
Timestamp = GETUTCDATE(),
Version = Version + 1
WHERE
DeploymentId = @DeploymentId AND @DeploymentId IS NOT NULL
AND Version = @Version AND @Version IS NOT NULL
AND @@ROWCOUNT > 0;

SET @ROWCOUNT = @@ROWCOUNT;
IF @ROWCOUNT = 0
ROLLBACK TRANSACTION
ELSE
COMMIT TRANSACTION
SELECT @ROWCOUNT;
',N'@DeploymentId nvarchar(8),@IAmAliveTime datetime,@HostName nvarchar(15),@Address nvarchar(9),@Port int,@Generation int,@StartTime datetime,@Status int,@ProxyPort int,@Version int',@DeploymentId=N'TestSilo',@IAmAliveTime='2016-06-22 02:02:59.407',@HostName=N'DESKTOP-U9HVGOI',@Address=N'127.0.0.1',@Port=11111,@Generation=204256950,@StartTime='2016-06-22 02:02:36.773',@Status=2,@ProxyPort=30000,@Version=0`

**Comment by hammie1010** [comment]
I was using the wrong CreateTableScripts.
