### ISSUE TITLE
Orleans Silo Internal Failure

### ISSUE THREAD

**Issue by sbrohi** [dotnet/orleans#1907]
Hi,

We recently found an issue with our Orleans cluster in which a silo committed suicide due to being marked as dead by another silo due to the silo stalling for approximately 20 seconds. My assumption is that the silo died because it consumed too much memory. We have a server with 6 GB RAM allocated for it, but the silo itself typically consumes 5-6 GB RAM.

Based on this, I have some questions:

1. What would you attribute this high memory consumption to be a result of ?
2. What should I look for in my log file to determine if high memory consumption is present ?
3. Are there any configuration options in Orleans to optimize memory utilization by the cluster? 

If there is any more detail requested, I can provide it.

Below is the message we see right after the silo commits suicide:

**2016-07-06 13:19:38,408: [Runtime.Scheduler.WorkerPoolThread/System.5] ERROR [2016-07-06 18:19:38.408 GMT    12	ERROR  	100627	MembershipOracle	10.0.17.XXX:11111]	!!!!!!!!!! I have been told I am dead, so this silo will commit suicide! I should be Dead according to membership table (in CleanupTableEntries): entry = SiloAddress=S10.0.17.XXX:11111:205520835 Status=Dead.	
2016-07-06 13:19:39,549: [Runtime.Scheduler.WorkerPoolThread/System.5] ERROR [2016-07-06 18:19:39.549 GMT    12	ERROR  	100627	MembershipOracle	10.0.17.XXX:11111]	!!!!!!!!!! INTERNAL FAILURE! About to crash! Fail message is: I have been told I am dead, so this silo will commit suicide! I should be Dead according to membership table (in CleanupTableEntries): entry = SiloAddress=S10.0.17.XXX:11111:205520835 Status=Dead.
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Orleans.Runtime.TraceLogger.Fail(ErrorCode errorCode, String message)
   at Orleans.Runtime.MembershipService.MembershipOracle.KillMyselfLocally(String reason)
   at Orleans.Runtime.MembershipService.MembershipOracle.<CleanupTableEntries>d__65.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Orleans.Runtime.MembershipService.MembershipOracle.CleanupTableEntries(MembershipTableData table)
   at Orleans.Runtime.MembershipService.MembershipOracle.<ProcessTableUpdate>d__55.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Orleans.Runtime.MembershipService.MembershipOracle.ProcessTableUpdate(MembershipTableData table, String caller, Boolean logAtInfoLevel)
   at Orleans.Runtime.MembershipService.MembershipOracle.<<OnGetTableUpdateTimer>b__7d>d__7e.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Orleans.Runtime.MembershipService.MembershipOracle.<OnGetTableUpdateTimer>b__7d(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.RunTask(Task task)
   at Orleans.Runtime.Scheduler.WorkItemGroup.Execute()
   at Orleans.Runtime.Scheduler.WorkerPoolThread.Run()
   at Orleans.Runtime.AsynchAgent.AgentThreadProc(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)	
2016-07-06 13:20:00,580: [Runtime.Watchdog] WARN  [2016-07-06 18:20:00.580 GMT    28	WARNING	100150	Watchdog	10.0.17.XXX:11111]	.NET Runtime Platform stalled for 00:00:20.5317256 - possibly GC? We are now using total of 6004MB memory. gc=574, 214, 46	
2016-07-06 13:20:00,596: [Runtime.Scheduler.WorkerPoolThread/System.5] ERROR [2016-07-06 18:20:00.596 GMT    12	ERROR  	100001	MembershipOracle	10.0.17.XXX:11111]	!!!!!!!!!! INTERNAL FAILURE! Application mini-dump written to file C:\Windows\system32\ApplicationService-MiniDump-2016-07-06-18-19-39-689Z.dmp	
2016-07-06 13:20:00,940: [Runtime.Scheduler.WorkerPoolThread/1] WARN  [2016-07-06 18:20:00.940 GMT     9	WARNING	101215	Scheduler.DirectoryCacheValidator.WorkItemGroup	10.0.17.XXX:11111]	Task [Id=737358, Status=RanToCompletion] in WorkGroup [SystemTarget: S10.0.17.XXX:11111:205520835DirectoryCacheValidator@S0000000b] took elapsed time 0:00:22.0513687 for execution, which is longer than 00:00:00.4000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/1, ManagedThreadId=9, Executing Task Id=737358 Status=RanToCompletion for 00:00:22.0629789>	
2016-07-06 13:20:01,065: [Runtime.Scheduler.WorkerPoolThread/System.5] ERROR [2016-07-06 18:20:01.065 GMT    12	ERROR  	100002	MembershipOracle	10.0.17.XXX:11111]	!!!!!!!!!! INTERNAL FAILURE! Process crashing!	
2016-07-06 13:43:32,923: [Runtime.Watchdog] WARN  [2016-07-06 18:43:32.923 GMT    28	WARNING	100150	Watchdog	10.0.17.XXX:11111]	.NET Runtime Platform stalled for 00:23:15.0764007 - possibly GC? We are now using total of 6009MB memory. gc=574, 214, 46	
2016-07-06 13:43:32,938: [Runtime.GrainDirectory.AdaptiveDirectoryCacheMaintainer`1] INFO  [2016-07-06 18:43:32.938 GMT    18	INFO   	100328	Runtime.GrainDirectory.AdaptiveDirectoryCacheMaintainer`1	10.0.17.XXX:11111]	Stopping AsyncAgent Runtime.GrainDirectory.AdaptiveDirectoryCacheMaintainer`1 that runs on managed thread 18	
2016-07-06 13:43:32,970: [Runtime.Watchdog] ERROR [2016-07-06 18:43:32.970 GMT    28	ERROR  	101212	Runtime.Scheduler.WorkerPoolThread/System.5	10.0.17.XXX:11111]	!!!!!!!!!! Worker pool thread Runtime.Scheduler.WorkerPoolThread/System.5 (ManagedThreadId=12) has been busy for long time: Executing Task Id=737369 Status=Running for 00:23:54.8741207	
2016-07-06 13:43:32,970: [Runtime.Watchdog] WARN  [2016-07-06 18:43:32.970 GMT    28	WARNING	102603	Watchdog	10.0.17.XXX:11111]	Watchdog had 2 Health Check Failure(s) out of 2 Health Check Participants.	
2016-07-06 13:43:38,189: [Runtime.Watchdog] WARN  [2016-07-06 18:43:38.189 GMT    28	WARNING	100150	Watchdog	10.0.17.XXX:11111]	.NET Runtime Platform stalled for 00:00:05.2190385 - possibly GC? We are now using total of 6012MB memory. gc=574, 214, 46	
2016-07-06 13:44:45,409: [5] INFO  [2016-07-06 18:44:45.393 GMT     5	INFO   	100404	Silo	10.0.17.XXX:11111]	Silo starting with GC settings: ServerGC=True GCLatencyMode=Batch	
2016-07-06 13:44:45,424: [5] INFO  [2016-07-06 18:44:45.424 GMT     5	INFO   	100403	Silo	10.0.17.XXX:11111]	-------------- Initializing Secondary silo on host appXXX MachineName appXXX at 10.0.17.XXX:11111, gen 205526685 --------------	
2016-07-06 13:44:45,455: [5] INFO  [2016-07-06 18:44:45.455 GMT     5	INFO   	100415	Silo	10.0.17.XXX:11111]	Starting silo appXXX_11111 with runtime Version='1.0.10.0 (Release).' .NET version='4.0.30319.42000' Is .NET 4.5=True OS version='Microsoft Windows NT 6.2.9200.0' Config= 
Config File Name: D:\Application\OrleansConfiguration.xml**

**Comment by shayhatsor** [comment]
Other silos couldn't communicate with the silo and announced it dead in the membership table. The silo killed itself once it performed the periodical membership table refresh. This happens when the silo is able to communicate with the membership table, but other silos aren't able to communicate with it (at least not quick enough).
At first glance, this seemed like a memory leak to me that caused the process to be in constant GC. But I don't think that's the case because the silo probably would have crashed with out of memory exception before other silos had the time to announce it as dead. 
To assert if this was a memory leak, you can use the generated crash dump to investigate.
To assert if this was a network split, look for the entry for the crashed silo in the membership table. Look at the IAmAlive field to see if the silo was able to signal it's alive, and compare that with the times the silos have reported it dead.
There are configuration values for the memory consumption of Orleans, but these are only for Orleans managed structures (mostly grains). Also, a silo that uses all the machine memory could just mean it is working in full capacity.
I hope this helps.

**Comment by sergeybykov** [comment]
In our experience, it's not the amount of allocated but the number of allocated objects and complexity of the object graph is what makes Gen2 GC get slow. This is a general issue with .NET (and other similar managed memory systems).

The recommendations to reduce the Gen2 pressure are as follows.

1. Reduce the number of allocated objects by using different data types and data structures or by leveraging object pooling.
2. Reduce lifetime of allocated objects.
2a. Orleans specific - reduce activation idle time settings from the default 2 hours to a lower value that would still work for your application - http://dotnet.github.io/orleans/Advanced-Concepts/Activation-Garbage-Collection.
2b. Explicitly release unneeded objects where possible.

To analyze where those efforts would pay off, we usually take a memory dump of process in the slow GC state and look at the number of allocated objects by type. This helps narrow down the scope.
