### ISSUE TITLE
mechanism to create/expose SynchronizationContext for grain communications for use by provider/consumer extensions

### ISSUE THREAD

**Issue by danvanderboom** [dotnet/orleans#2048]
What would be involved in creating a SynchronizationContext that would be compatible with and permit communication between grains and Orleans custom extensions like TelemetryConsumers, StorageProviders, etc?

Or beyond my speculation as to possible solutions, here are the facts (the call referenced at the very bottom of the stack trace was a grain method call on a grain reference object):

Trying to send a message Request S127.0.0.1:22222:208636476-> #51:  on a silo not from within grain and not from within system target (RuntimeContext is not set to SchedulingContext) RuntimeContext.Current=null TaskScheduler.Current=System.Threading.Tasks.ThreadPoolTaskScheduler
Exception = System.Data.InvalidExpressionException: Trying to send a message Request S127.0.0.1:22222:208636476-> #51:  on a silo not from within grain and not from within system target (RuntimeContext is not set to SchedulingContext) RuntimeContext.Current=null TaskScheduler.Current=System.Threading.Tasks.ThreadPoolTaskScheduler
   at Orleans.Runtime.InsideRuntimeClient.SendRequestMessage(GrainReference target, Message message, TaskCompletionSource`1 context, Action`2 callback, String debugContext, InvokeMethodOptions options, String genericArguments)
   at Orleans.Runtime.GrainReference.InvokeMethod_Impl(InvokeMethodRequest request, String debugContext, InvokeMethodOptions options)
   at Orleans.Runtime.GrainReference.InvokeMethodAsync[T](Int32 methodId, Object[] arguments, InvokeMethodOptions options, SiloAddress silo)
   at Orleans.TelemetryConsumers.MetricsTracker.OrleansCodeGenClusterMetricsGrainReference.ReportSiloStatistics(MetricsSnapshot snapshot) in C:\Source\Orleans.TelemetryConsumers.MetricsTracker\Orleans.TelemetryConsumers.MetricsTracker\Properties\orleans.codegen.cs:line 71
   at Orleans.TelemetryConsumers.MetricsTracker.MetricsTrackerTelemetryConsumer.SampleMetrics(Object state) in C:\Source\Orleans.TelemetryConsumers.MetricsTracker\Orleans.TelemetryConsumers.MetricsTracker\MetricsTrackerTelemetryConsumer.cs:line 169

**Comment by danvanderboom** [comment]
I figured it out! In my IMetricsTelemetryConsumer implementation's constructor, I asynchronously call a Task-returning "message pump" method which wakes up every x seconds to collect metrics for the silo and pass those details up to the singleton ClusterMetricsGrain (where they're aggregated for the cluster and made available to other inquiring grains).
