### ISSUE TITLE
Issue upgrading to 1.1.3

### ISSUE THREAD

**Issue by philreindl** [dotnet/orleans#2086]
I'm in the process of getting all of the nuget packages upgraded.  I've taken orleans from 1.1.2 to 1.1.3 and am seeing a new exception that appears to be causing the clients to fail to initialize.

`
Error starting Orleans Azure client application -- Could not Initialize Client for DeploymentId=deployment29(1505). Last exception=Could not load type 'Orleans.CodeGeneration.GrainInterfaceUtils' from assembly 'Orleans, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. -- bailing. 
Exc level 0: Orleans.Runtime.OrleansException: Could not Initialize Client for DeploymentId=deployment29(1505). Last exception=Could not load type 'Orleans.CodeGeneration.GrainInterfaceUtils' from assembly 'Orleans, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Exc level 1: System.TypeLoadException: Could not load type 'Orleans.CodeGeneration.GrainInterfaceUtils' from assembly 'Orleans, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateForAssemblies(List`1 assemblies, Boolean runtime)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssemblies(Assembly[] inputs)
   at Orleans.CodeGeneration.CodeGeneratorManager.GenerateAndCacheCodeForAllAssemblies()
   at Orleans.Runtime.AssemblyProcessor.Initialize()
   at Orleans.Serialization.SerializationManager.Initialize(Boolean useStandardSerializer, List`1 serializationProviders, Boolean useJsonFallbackSerializer)
   at Orleans.OutsideRuntimeClient..ctor(ClientConfiguration cfg, GrainFactory grainFactory, Boolean secondary)
   at Orleans.GrainClient.DoInternalInitialize(ClientConfiguration config, OutsideRuntimeClient runtimeClient)
   at Orleans.GrainClient.<>c__DisplayClass1.<InternalInitialize>b__0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Orleans.GrainClient.InternalInitialize(ClientConfiguration config, OutsideRuntimeClient runtimeClient)
   at Orleans.Runtime.Host.AzureClient.InitializeImpl_FromConfig(ClientConfiguration config)
`

The main takeaway from that stack trace is
**Could not load type 'Orleans.CodeGeneration.GrainInterfaceUtils'**

Is there a package I need to include?  Anything else I should be looking for?

Thanks
Phil

**Comment by sergeybykov** [comment]
Check that you upgraded all of the references NuGet packages to 1.1.3 and that you don't have a mixture of 1.1.2 and 1.1.3.

**Comment by philreindl** [comment]
I double checked in nuget and in the packages directory.  Every reference to orleans is as 1.1.3.

What package is that type defined in?  Are there any known versions of dependent packages that are incompatible?  Is it possible that I've got an incompatible version of some other nuget package installed?

**Comment by jdom** [comment]
Did you try cleaning your output folder and rebuilding everything? I wonder if there is a remnant DLL there that is being loaded dynamically that is of a different version. These kind of errors have always been related to assembly version mismatch in some of the projects or in the OrleansHost.exe.
Also, do you have any other pre-built custom provider that needs to be rebuilt too?

**Comment by philreindl** [comment]
@jdom That was it, thanks!  I had been assuming that Build->Clean did that already.
