### ISSUE TITLE
OutOfMemoryException in context with performance counters

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#2448]
I saw the following log message in one of our silo deployment which is just for demo purposes (i.e. it's only used every few days) and does not use much memory:

```
Exc level 0: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample oldSample, CounterSample newSample)
   at System.Diagnostics.PerformanceCounter.NextValue()
   at Orleans.Runtime.RuntimeStatisticsGroup.get_AvailableMemory()
   at Orleans.Runtime.SiloRuntimeStatistics..ctor(ISiloPerformanceMetrics metrics, DateTime dateTime)
   at Orleans.Runtime.DeploymentLoadPublisher.<PublishStatistics>d__14.MoveNext()
```

Maybe this issue is related to [SO question 3266777](http://stackoverflow.com/questions/3266777/how-to-solve-memory-leak-caused-by-system-diagnostics-performancecounter) or [30184585](http://stackoverflow.com/questions/30184585/how-to-fix-outofmemoryexception-for-performancecountercategory-getinstancename).

**Comment by sergeybykov** [comment]
We've seen perf counters getting corrupted sometimes for no apparent reason. So I'm not really surprised.
