### ISSUE TITLE
Improve error message when membership provider generates consistent failures

### ISSUE THREAD

**Issue by vincentshow** [dotnet/orleans#2488]
follow this doc [Using Consul as a Membership Provider](http://dotnet.github.io/orleans/Documentation/Runtime-Implementation-Details/Consul-Deployment.htm)
1. Start consul success with result:
D:\Program Files\consul>Consul.exe agent -server -bootstrap -data-dir "C:\Consul
\Data" -client=127.0.0.1 -bind=127.0.0.1 -ui
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
           Version: 'v0.7.1'
         Node name: 'win测试机'
        Datacenter: 'dc1'
            Server: true (bootstrap: true)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>
2. Config silo and start it, the exe pause on _siloHost.StartOrleansSilo() method, and the console show 
[2016-12-06 10:16:36.810 GMT    15	INFO   	100603	MembershipOracle	127.0.0.1:22222]	MembershipOracle starting on host = win测试机 address = S127.0.0.1:22222:218715348 at 2016-12-06 10:16:36.711 GMT, backOffMax = 00:00:20
3. Wait 5 minutes, error occured:
2016-12-06-10.03.29.066ZZ
ERROR starting Orleans silo name=win测试机 Exception=
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo(Boolean catchExceptions)
Exc level 1: System.TimeoutException: ExecuteWithRetries has exceeded its max execution time of 00:05:00. Now is 2016-12-06 10:03:28.844 GMT, started at 2016-12-06 09:58:27.936 GMT, passed 00:05:00.9073926
   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

Environment: os win7 sp1, Orleans 1.3.1, consul 0.7.1, vs2015 community update3
Thanks

**Comment by sergeybykov** [comment]
I suspect the silo is unable to communicate with Consul for some reason, e.g. the membership provider for Consul isn't properly configured. Aren't there other info/warning/error statements in the log?

**Comment by vincentshow** [comment]
[2016-12-06 10:15:48.140 GMT     8	INFO   	100404	Silo	127.0.0.1:22222]	Silo starting with GC settings: ServerGC=True GCLatencyMode=Batch	
[2016-12-06 10:15:48.149 GMT     8	INFO   	100403	Silo	127.0.0.1:22222]	-------------- Initializing Secondary silo on host win测试机 MachineName win测试机 at 127.0.0.1:22222, gen 218715348 --------------	
[2016-12-06 10:15:48.170 GMT     8	INFO   	100415	Silo	127.0.0.1:22222]	Starting silo win测试机 with the following configuration= 
Config File Name: E:\src\Demo.SiloHoster\bin\Debug\OrleansConfiguration.xml
Host: win测试机
Start time: 2016-12-06 10:15:48.152 GMT
Primary node: null
Platform version info:
   Orleans version: 1.3.1.0 (Release).
   .NET version: 4.0.30319.42000
   Is .NET 4.5=True
   OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
   GC Type=Server GCLatencyMode=Batch
Global configuration:
   System Ids:
      ServiceId: 00000000-0000-0000-0000-000000000000
      DeploymentId: MyOrleansDeployment
   Subnet: 
   Seed nodes: 
   Messaging:
       Response timeout: 00:30:00
       Maximum resend count: 0
       Resend On Timeout: False
       Maximum Socket Age: 10675199.02:48:05.4775807
       Drop Expired Messages: True
       Silo Sender queues: 8
       Gateway Sender queues: 8
       Client Drop Timeout: 00:01:00
       Buffer Pool Buffer Size: 4096
       Buffer Pool Max Size: 10000
       Buffer Pool Preallocation Size: 250
       Use Message Batching: False
       Max Message Batching Size: 10
       Maximum forward count: 2
   Liveness:
      LivenessEnabled: True
      LivenessType: Custom
      ProbeTimeout: 00:00:10
      TableRefreshTimeout: 00:01:00
      DeathVoteExpirationTimeout: 00:02:00
      NumMissedProbesLimit: 3
      NumProbedSilos: 3
      NumVotesForDeathDeclaration: 2
      UseLivenessGossip: True
      ValidateInitialConnectivity: True
      IAmAliveTablePublishTimeout: 00:05:00
      NumMissedTableIAmAliveLimit: 2
      MaxJoinAttemptTime: 00:05:00
      ExpectedClusterSize: 20
   MultiClusterNetwork: N/A
   SystemStore:
      SystemStore ConnectionString: http://localhost:8500
      Reminders ConnectionString: http://localhost:8500
   Application:
      Defaults:
         Deactivate if idle for: 02:00:00

   PlacementStrategy: 
         Default Placement Strategy: RandomPlacement
         Deployment Load Publisher Refresh Time: 00:00:01
         Activation CountBased Placement Choose Out Of: 2
   Grain directory cache:
      Maximum size: 1000000 grains
      Initial TTL: 00:00:30
      Maximum TTL: 00:04:00
      TTL extension factor: 2.00
      Directory Caching Strategy: Adaptive
   Grain directory:
      Lazy deregistration delay: 00:01:00
      Client registration refresh: 00:05:00
   Reminder Service:
       ReminderServiceType: Disabled
   Consistent Ring:
       Use Virtual Buckets Consistent Ring: True
       Num Virtual Buckets Consistent Ring: 30
   Providers:
       No providers configured.
Silo configuration:
   Silo Name: win测试机
   Generation: 218715348
   Host Name or IP Address: localhost
   DNS Host Name: win测试机
   Port: 22222
   Subnet: 
   Preferred Address Family: InterNetwork
   Proxy Gateway: 127.0.0.1:30000
   IsPrimaryNode: False
   Scheduler: 
         Max Active Threads: 8
         Processor Count: 8
         Delay Warning Threshold: 00:00:10
         Activation Scheduling Quantum: 00:00:00.1000000
         Turn Warning Length Threshold: 00:00:00.2000000
         Inject More Worker Threads: False
         MinDotNetThreadPoolSize: 200
         .NET thread pool sizes - Min: Worker Threads=8 Completion Port Threads=8
         .NET thread pool sizes - Max: Worker Threads=32767 Completion Port Threads=1000
         .NET ServicePointManager - DefaultConnectionLimit=200 Expect100Continue=False UseNagleAlgorithm=False
   Load Shedding Enabled: False
   Load Shedding Limit: 95
   SiloShutdownEventName: 
   Debug: 
   Tracing: 
     Default Trace Level: Info
     TraceLevelOverrides: None
     Trace to Console: True
     Trace File Name: E:\src\Demo.SiloHoster\bin\Debug\win测试机-2016-12-06-10.15.47.028Z.log
     LargeMessageWarningThreshold: 85000
     PropagateActivityId: False
     BulkMessageLimit: 5
   Statistics: 
     MetricsTableWriteInterval: 00:00:30
     PerfCounterWriteInterval: 00:00:30
     LogWriteInterval: 00:05:00
     WriteLogStatisticsToTable: True
     StatisticsCollectionLevel: Info

	
[2016-12-06 10:15:48.210 GMT     8	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:22222]	Searching for assemblies in E:\src\Demo.SiloHoster\bin\Debug...	
[2016-12-06 10:15:48.251 GMT     8	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:22222]	User assembly ignored: E:\src\Demo.SiloHoster\bin\Debug\Consul.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
...same as above...
[2016-12-06 10:15:48.555 GMT     8	WARNING	101705	AssemblyLoader.Silo	127.0.0.1:22222]	Unable to find directory E:\src\Demo.SiloHoster\bin\Debug\Applications; skipping.	
[2016-12-06 10:15:48.559 GMT     8	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:22222]	Loading assembly E:\src\Demo.SiloHoster\bin\Debug\OrleansProviders.dll...	
[2016-12-06 10:15:48.574 GMT     8	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:22222]	Loading assembly E:\src\Demo.SiloHoster\bin\Debug\Demo.Grains.dll...	
[2016-12-06 10:15:48.587 GMT     8	INFO   	100000	AssemblyLoader.Silo	127.0.0.1:22222]	2 assemblies loaded.	
[2016-12-06 10:15:50.259 GMT     8	INFO   	100000	Scheduler.OrleansTaskScheduler	127.0.0.1:22222]	Starting OrleansTaskScheduler with 8 Max Active application Threads and 1 system thread.	
[2016-12-06 10:15:50.282 GMT     8	INFO   	101010	Runtime.Messaging.IncomingMessageAcceptor	127.0.0.1:22222]	Opened a listening socket at address 127.0.0.1:22222	
[2016-12-06 10:15:50.289 GMT     8	INFO   	101010	Runtime.Messaging.GatewayAcceptor	127.0.0.1:22222]	Opened a listening socket at address 127.0.0.1:30000	
[2016-12-06 10:15:50.308 GMT     8	INFO   	100000	VirtualBucketsRingProvider	127.0.0.1:22222]	Starting VirtualBucketsRingProvider on silo S127.0.0.1:22222:218715348/x2548967F.	
[2016-12-06 10:15:50.338 GMT     8	INFO   	103003	VirtualBucketsRingProvider	127.0.0.1:22222]	Added Server S127.0.0.1:22222:218715348/x2548967F. Current view: [S127.0.0.1:22222:218715348 -> <MultiRange: Size=x100000000, %Ring=100.000%>]	
[2016-12-06 10:15:50.341 GMT     8	INFO   	103005	VirtualBucketsRingProvider	127.0.0.1:22222]	-NotifyLocalRangeSubscribers about old <(0 0], Size=x100000000, %Ring=100.000%> new <MultiRange: Size=x100000000, %Ring=100.000%> increased? True	
[2016-12-06 10:15:50.362 GMT     8	INFO   	100294	SystemStatus	127.0.0.1:22222]	SystemStatus=Created	
[2016-12-06 10:15:50.364 GMT     8	INFO   	100422	Silo	127.0.0.1:22222]	-------------- Started silo S127.0.0.1:22222:218715348, ConsistentHashCode 2548967F --------------	
[2016-12-06 10:15:50.365 GMT     8	INFO   	100288	OrleansSiloHost	127.0.0.1:22222]	Successfully initialized Orleans silo 'win测试机' as a Secondary node.	
[2016-12-06 10:16:36.283 GMT     8	INFO   	100441	OrleansSiloHost	127.0.0.1:22222]	Silo shutdown event name: win测试机-Shutdown	
[2016-12-06 10:16:36.286 GMT     8	INFO   	100442	OrleansSiloHost	127.0.0.1:22222]	Created and set shutdown event win测试机-Shutdown	
[2016-12-06 10:16:36.292 GMT     8	INFO   	100294	SystemStatus	127.0.0.1:22222]	SystemStatus=Starting	
[2016-12-06 10:16:36.294 GMT     8	INFO   	100401	Silo	127.0.0.1:22222]	Silo Start()	
[2016-12-06 10:16:36.295 GMT     8	INFO   	100430	Silo	127.0.0.1:22222]	Configured ThreadPool.SetMinThreads() to values: 200,200. Previous values are: 8,8.	
[2016-12-06 10:16:36.297 GMT     8	INFO   	100436	Silo	127.0.0.1:22222]	Configured .NET ServicePointManager to Expect100Continue=False, DefaultConnectionLimit=200, UseNagleAlgorithm=False to improve Azure storage performance.	
[2016-12-06 10:16:36.350 GMT     8	INFO   	101711	AssemblyLoader.Silo	127.0.0.1:22222]	Loaded grain type summary for 8 types: 
Grain class Orleans.Providers.Orleans.Providers.MemoryStreamQueueGrain [1359359215 (0x51062CEF)] from OrleansProviders.dll implementing interfaces: Orleans.Providers.Orleans.Providers.IMemoryStreamQueueGrain [1158152105 (0x4507FFA9)]
Grain class Orleans.Runtime.Management.Orleans.Runtime.Management.ManagementGrain [1954798034 (0x7483D9D2)] from OrleansRuntime.dll implementing interfaces: Orleans.Runtime.Orleans.Runtime.IManagementGrain [-1734666656 (0x989B1660)]
Grain class Orleans.Runtime.MembershipService.Orleans.Runtime.MembershipService.GrainBasedMembershipTable [-2103923544 (0x8298ACA8)] from OrleansRuntime.dll implementing interfaces: Orleans.Orleans.IMembershipTableGrain [-1256503757 (0xB51B4633)]
Grain class Orleans.Runtime.ReminderService.Orleans.Runtime.ReminderService.GrainBasedReminderTable [-55315191 (0xFCB3F509)] from OrleansRuntime.dll implementing interfaces: Orleans.Orleans.IReminderTableGrain [-1135060418 (0xBC585A3E)]
Grain class Orleans.Storage.Orleans.Storage.MemoryStorageGrain [819348208 (0x30D642F0)] from OrleansRuntime.dll implementing interfaces: Orleans.Storage.Orleans.Storage.IMemoryStorageGrain [577125491 (0x22663C73)]
Grain class Orleans.Streams.Orleans.Streams.PubSubRendezvousGrain [1903070868 (0x716E8E94)] from OrleansRuntime.dll implementing interfaces: Orleans.Streams.Orleans.Streams.IPubSubRendezvousGrain [1746702088 (0x681C8F08)]
Grain class Demo.Grains.Demo.Grains.GameDataGrain [1823053115 (0x6CA9953B)] from Demo.Grains.dll implementing interfaces: Demo.GrainInterfaces.Demo.GrainInterfaces.IGameDataGrain [-611975212 (0xDB85FFD4)]
Grain class Demo.Grains.Demo.Grains.GameMsgGrain [-1193476155 (0xB8DCFFC5)] from Demo.Grains.dll implementing interfaces: Demo.GrainInterfaces.Demo.GrainInterfaces.IGameMsgGrain [-1294729149 (0xB2D40043)]
	
[2016-12-06 10:16:36.370 GMT    21	INFO   	100000	Runtime.Scheduler.WorkerPoolThread/System.9	127.0.0.1:22222]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/System.9 on managed thread 21	
[2016-12-06 10:16:36.377 GMT    13	INFO   	100000	Runtime.Scheduler.WorkerPoolThread/0	127.0.0.1:22222]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/0 on managed thread 13	
[2016-12-06 10:16:36.385 GMT    15	INFO   	100000	Runtime.Scheduler.WorkerPoolThread/2	127.0.0.1:22222]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/2 on managed thread 15	
[2016-12-06 10:16:36.385 GMT    14	INFO   	100000	Runtime.Scheduler.WorkerPoolThread/1	127.0.0.1:22222]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/1 on managed thread 14	
[2016-12-06 10:16:36.425 GMT    19	INFO   	100000	Runtime.Scheduler.WorkerPoolThread/6	127.0.0.1:22222]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/6 on managed thread 19	
[2016-12-06 10:16:36.411 GMT    17	INFO   	100000	Runtime.Scheduler.WorkerPoolThread/4	127.0.0.1:22222]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/4 on managed thread 17	
[2016-12-06 10:16:36.410 GMT    16	INFO   	100000	Runtime.Scheduler.WorkerPoolThread/3	127.0.0.1:22222]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/3 on managed thread 16	
[2016-12-06 10:16:36.475 GMT    22	INFO   	100000	Runtime.Messaging.IncomingMessageAcceptor	127.0.0.1:22222]	Starting AsyncAgent Runtime.Messaging.IncomingMessageAcceptor on managed thread 22	
[2016-12-06 10:16:36.541 GMT    30	INFO   	100000	Runtime.Messaging.IncomingMessageAgent/Ping	127.0.0.1:22222]	Starting AsyncAgent Runtime.Messaging.IncomingMessageAgent/Ping on managed thread 30	
[2016-12-06 10:16:36.549 GMT    29	INFO   	100000	Runtime.Messaging.IncomingMessageAgent/System	127.0.0.1:22222]	Starting AsyncAgent Runtime.Messaging.IncomingMessageAgent/System on managed thread 29	
[2016-12-06 10:16:36.448 GMT    20	INFO   	100000	Runtime.Scheduler.WorkerPoolThread/7	127.0.0.1:22222]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/7 on managed thread 20	
[2016-12-06 10:16:36.530 GMT    24	INFO   	100000	Runtime.Messaging.SiloMessageSender/SystemSender	127.0.0.1:22222]	Starting AsyncAgent Runtime.Messaging.SiloMessageSender/SystemSender on managed thread 24	
[2016-12-06 10:16:36.418 GMT    18	INFO   	100000	Runtime.Scheduler.WorkerPoolThread/5	127.0.0.1:22222]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/5 on managed thread 18	
[2016-12-06 10:16:36.503 GMT    23	INFO   	100000	Runtime.Messaging.SiloMessageSender/PingSender	127.0.0.1:22222]	Starting AsyncAgent Runtime.Messaging.SiloMessageSender/PingSender on managed thread 23	
[2016-12-06 10:16:36.558 GMT    31	INFO   	100000	Runtime.Messaging.IncomingMessageAgent/Application	127.0.0.1:22222]	Starting AsyncAgent Runtime.Messaging.IncomingMessageAgent/Application on managed thread 31	
[2016-12-06 10:16:36.571 GMT     8	INFO   	100000	Orleans.GrainDirectory.LocalGrainDirectory	127.0.0.1:22222]	Start (SeverityLevel=Info)	
[2016-12-06 10:16:36.606 GMT    22	INFO   	100328	Runtime.Messaging.IncomingMessageAcceptor	127.0.0.1:22222]	Stopping AsyncAgent Runtime.Messaging.IncomingMessageAcceptor that runs on managed thread 22	
[2016-12-06 10:16:36.627 GMT    28	INFO   	100000	Runtime.GrainDirectory.GlobalSingleInstanceActivationMaintainer	127.0.0.1:22222]	Starting AsyncAgent Runtime.GrainDirectory.GlobalSingleInstanceActivationMaintainer on managed thread 28	
[2016-12-06 10:16:36.606 GMT    27	INFO   	100000	Runtime.GrainDirectory.AdaptiveDirectoryCacheMaintainer`1	127.0.0.1:22222]	Starting AsyncAgent Runtime.GrainDirectory.AdaptiveDirectoryCacheMaintainer`1 on managed thread 27	
[2016-12-06 10:16:36.667 GMT    28	INFO   	100328	Runtime.GrainDirectory.GlobalSingleInstanceActivationMaintainer	127.0.0.1:22222]	Stopping AsyncAgent Runtime.GrainDirectory.GlobalSingleInstanceActivationMaintainer that runs on managed thread 28	
[2016-12-06 10:16:36.709 GMT     8	INFO   	100000	MembershipFactory	127.0.0.1:22222]	Creating membership oracle for type=Custom	
[2016-12-06 10:16:36.713 GMT     8	INFO   	100000	MultiClusterOracleFactory	127.0.0.1:22222]	Skip multicluster oracle creation (no multicluster network configured)	
[2016-12-06 10:16:36.745 GMT    13	INFO   	100507	Catalog	127.0.0.1:22222]	Before collection#1: memory=15MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
[2016-12-06 10:16:36.749 GMT    13	INFO   	100508	Catalog	127.0.0.1:22222]	After collection#1: memory=15MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0075716.	
[2016-12-06 10:16:36.810 GMT    15	INFO   	100603	MembershipOracle	127.0.0.1:22222]	MembershipOracle starting on host = win测试机 address = S127.0.0.1:22222:218715348 at 2016-12-06 10:16:36.711 GMT, backOffMax = 00:00:20	
[2016-12-06 10:17:36.758 GMT    20	INFO   	100507	Catalog	127.0.0.1:22222]	Before collection#2: memory=21MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
[2016-12-06 10:17:36.761 GMT    20	INFO   	100508	Catalog	127.0.0.1:22222]	After collection#2: memory=21MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0032384.	
[2016-12-06 10:18:36.768 GMT    21	INFO   	100507	Catalog	127.0.0.1:22222]	Before collection#3: memory=27MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
[2016-12-06 10:18:36.769 GMT    21	INFO   	100508	Catalog	127.0.0.1:22222]	After collection#3: memory=27MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0018711.	
[2016-12-06 10:19:36.746 GMT    21	INFO   	100507	Catalog	127.0.0.1:22222]	Before collection#4: memory=34MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
[2016-12-06 10:19:36.747 GMT    21	INFO   	100508	Catalog	127.0.0.1:22222]	After collection#4: memory=34MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0014794.	
[2016-12-06 10:20:36.757 GMT    14	INFO   	100507	Catalog	127.0.0.1:22222]	Before collection#5: memory=40MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
[2016-12-06 10:20:36.758 GMT    14	INFO   	100508	Catalog	127.0.0.1:22222]	After collection#5: memory=40MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0014259.	
[2016-12-06 10:21:36.765 GMT    13	INFO   	100507	Catalog	127.0.0.1:22222]	Before collection#6: memory=46MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
[2016-12-06 10:21:36.766 GMT    13	INFO   	100508	Catalog	127.0.0.1:22222]	After collection#6: memory=46MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0013982.	
[2016-12-06 10:21:43.302 GMT    21	ERROR  	100646	MembershipOracle	127.0.0.1:22222]	!!!!!!!!!! MembershipFailedToStart	
Exc level 0: System.TimeoutException: ExecuteWithRetries has exceeded its max execution time of 00:05:00. Now is 2016-12-06 10:21:43.300 GMT, started at 2016-12-06 10:16:40.271 GMT, passed 00:05:03.0291280
   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext()
...same as above....
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.MembershipService.MembershipOracle.<Start>d__28.MoveNext()
[2016-12-06 10:21:43.311 GMT     8	ERROR  	100439	Silo	127.0.0.1:22222]	!!!!!!!!!! Exception during Silo.Start	
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
Exc level 1: System.TimeoutException: ExecuteWithRetries has exceeded its max execution time of 00:05:00. Now is 2016-12-06 10:21:43.300 GMT, started at 2016-12-06 10:16:40.271 GMT, passed 00:05:03.0291280
   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext()
...same as above...
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.MembershipService.MembershipOracle.<Start>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
...same as above...
[2016-12-06 10:21:48.956 GMT     8	ERROR  	100105	OrleansSiloHost	127.0.0.1:22222]	!!!!!!!!!! ERROR starting Orleans silo name=win测试机 Exception=
Exc level 0: System.SystemException: Failed to start Orleans silo 'win测试机' as a Secondary node
   at Demo.SiloHoster.OrleansHostWrapper.Run() in E:\src\Demo.SiloHoster\OrleansHostWrapper.cs:line 44	
Exc level 0: System.SystemException: Failed to start Orleans silo 'win测试机' as a Secondary node
   at Demo.SiloHoster.OrleansHostWrapper.Run() in E:\src\Demo.SiloHoster\OrleansHostWrapper.cs:line 44
[2016-12-06 10:22:36.779 GMT    21	INFO   	100507	Catalog	127.0.0.1:22222]	Before collection#7: memory=56MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
[2016-12-06 10:22:36.781 GMT    21	INFO   	100508	Catalog	127.0.0.1:22222]	After collection#7: memory=56MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0016864.	
[2016-12-06 10:23:36.788 GMT    21	INFO   	100507	Catalog	127.0.0.1:22222]	Before collection#8: memory=62MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
[2016-12-06 10:23:36.790 GMT    21	INFO   	100508	Catalog	127.0.0.1:22222]	After collection#8: memory=62MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0015978.	
[2016-12-06 10:24:36.798 GMT    21	INFO   	100507	Catalog	127.0.0.1:22222]	Before collection#9: memory=68MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
[2016-12-06 10:24:36.800 GMT    21	INFO   	100508	Catalog	127.0.0.1:22222]	After collection#9: memory=68MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0021767.	
[2016-12-06 10:25:36.808 GMT    21	INFO   	100507	Catalog	127.0.0.1:22222]	Before collection#10: memory=74MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.

**Comment by vincentshow** [comment]
OrleansConfiguration.xml
-----------------------------------------------------------------
<OrleansConfiguration xmlns="urn:orleans">
  <Globals>
    <SystemStore SystemStoreType="None" DataConnectionString="http://localhost:8500" DeploymentId="MyOrleansDeployment" />
  </Globals>
  <Defaults>
    <Networking Address="localhost" Port="22222" />
    <ProxyingGateway Address="localhost" Port="30000" />
  </Defaults>
</OrleansConfiguration>

Startup method
---------------------------------------------------------------------
public bool Run()
        {
            bool ok = false;

            try
            {
                var _config = new ClusterConfiguration();
                _config.StandardLoad();

                _siloHost = new SiloHost(System.Net.Dns.GetHostName(), _config);

                _siloHost.Config.Globals.LivenessType = GlobalConfiguration.LivenessProviderType.Custom;
                _siloHost.Config.Globals.MembershipTableAssembly = "OrleansConsulUtils";
                _siloHost.Config.Globals.ReminderServiceType = GlobalConfiguration.ReminderServiceProviderType.Disabled;

                _siloHost.InitializeOrleansSilo();
                var startedok = _siloHost.StartOrleansSilo();
                if (!startedok)
                    throw new SystemException(String.Format("Failed to start Orleans silo '{0}' as a {1} node", _siloHost.Name, _siloHost.Type));
            }
            catch (Exception exc)
            {
                _siloHost.ReportStartupError(exc);
                var msg = string.Format("{0}:\n{1}\n{2}", exc.GetType().FullName, exc.Message, exc.StackTrace);
                Console.WriteLine(msg);
            }

            return ok;
        }

**Comment by vincentshow** [comment]
this is trace log
[win测试机-2016-12-06-10.15.47.028Z.txt](https://github.com/dotnet/orleans/files/635451/win.-2016-12-06-10.15.47.028Z.txt)

**Comment by vincentshow** [comment]
I've connected to my consul successfully by Consul client SDK whose version is same as orleans used.

Consul log:
-------------------------------------------------------------------------------------------
D:\Program Files\consul>Consul.exe agent -server -bootstrap -data-dir "C:\Consul
\Data" -client=127.0.0.1 -bind=127.0.0.1 -ui
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
           Version: 'v0.7.1'
         Node name: 'win测试机'
        Datacenter: 'dc1'
            Server: true (bootstrap: true)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false

Test Code
--------------------------------------------------------------------------------------
`static void Main(string[] args)
        {
            using (var _client = new Consul.ConsulClient(config => config.Address = new Uri("http://localhost:8500")))
            {
                var _myService = _client.Catalog.Datacenters().Result;
                Console.WriteLine(JsonConvert.SerializeObject(_myService.Response));
            }
            Console.ReadLine();
            return;
}`

Test result:
----------------------------
["dc1"]

**Comment by vincentshow** [comment]
Got it! The problem is OrleansConsulUtils.dll downloaded from Nuget. I've started silo host successfully after replacing  OrleansConsulUtils.dll with the local compiled one. And when I trying to run client with the one got from nuget, error occured:
 [2016-12-07 08:13:41.386 GMT     4	ERROR  	100319	OutsideRuntimeClient	]	!!!!!!!!!! OutsideRuntimeClient constructor failed.	
Exc level 0: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Consul.QueryResult`1<Consul.KVPair[]>> Consul.IKVEndpoint.List(System.String)'.

Does OrleansConsulUtils limit the Consul.dll version? I use the latest version 0.7.3

**Comment by sergeybykov** [comment]
From src\NuGet\Microsoft.Orleans.OrleansConsulUtils.nuspec:
> dependency id="Consul" version="0.6.4.1"

Not sure if there were breaking changes in the Consul library.

**Comment by attilah** [comment]
Yes there was a breaking change with this commit and the specific line which fails: https://github.com/PlayFab/consuldotnet/commit/33639dc742190011fbbf1a1d5a12649c6297cdea#diff-1bf84057428740c661334d09509d7b3aL43

All the remote API calls in 0.7.0 of Consul was modified to accept a parameter of ```CancellationToken``` hence the ```MethodNotFoundException```.

IMO It is safe to recompile out Consul library with the latest Consul nuget library for 1.4.

For now @vincentshow I think you can solve this by directly reference the newer Consul nuget package and provide a ```BindingRedirect``` element to the newer version. It can work, but not 100% sure.

**Comment by sergeybykov** [comment]
A PR to move OrleansConsulUtils to the latest version of Consul would be great.

**Comment by vincentshow** [comment]
Thanks. Little request, the error log written by silohost can be more accurate like the cilent one.

**Comment by attilah** [comment]
@vincentshow would you like to contribute a fix for this issue?

**Comment by vincentshow** [comment]
@attilah Sorry for the late answer for you. I'm busy with an online product upgrade of my company using .net core stack in which consul is used too. I can contribute in whatever way next month if you don't mind.

**Comment by attilah** [comment]
@vincentshow sounds like a plan! It is low prio, but would be nice if you can contribute!

**Comment by sergeybykov** [comment]
Silo startup has been seriously redone in 2.0.0. This shouldn't be relevant anymore.
