### ISSUE TITLE
Custom Serialization

### ISSUE THREAD

**Issue by bmchilds** [dotnet/orleans#2572]
I have a PCL class that I need to serialize.  I cannot mark it as serializable so I'm trying to use the orleans serialization.

[assembly: KnownType(typeof(Core.Collections.ReadOnlySet<>))]
[assembly: KnownAssembly("Core.Collections")]

which generates a valid (looking) stub for serialization but when I return an instance of my type I get the following exception from OrleansHost

[2017-01-06 19:18:03.851 GMT     6      WARNING 101531  InsideRuntimeClient     127.0.0.1:11111]    Exception trying to send a response: Type 'Core.Collections.ReadOnlySet`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' in Assembly 'Core.Collections, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.

Any clues to what I'm doing wrong?

**Comment by ReubenBond** [comment]
Hi @bmchilds could you post more of the stack trace if it's available? Is the serializer containing the generated serializer loaded?

**Comment by bmchilds** [comment]
Hi, for sure, here it is

Type 'Core.Collections.ReadOnlySet`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' in Assembly 'Core.Collections, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
Exception = System.Runtime.Serialization.SerializationException: Type 'Core.Collections.ReadOnlySet`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' in Assembly 'Core.Collections, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at Orleans.Serialization.BinaryFormatterSerializer.DeepCopy(Object source)
   at Orleans.Serialization.SerializationManager.FallbackSerializationDeepCopy(Object obj)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original)
   at Orleans.Serialization.SerializationManager.DeepCopy(Object original)
   at Orleans.Runtime.InsideRuntimeClient.SafeSendResponse(Message message, Object resultObject)

**Comment by bmchilds** [comment]
ReadOnlySet is a generic hashset underneath the covers.  I register the custom serializer as follows but orleans seems to ignore the registration.

public static void Register()
        {
            MethodInfo serializer, copier, deserializer;
            GetSerializationMethods(typeof(ReadOnlySetSerializer_T_1<>), out copier, out serializer, out deserializer);

            SerializationManager.Register(typeof(ReadOnlySet<>),
                        (DeepCopier)copier.CreateDelegate(typeof(DeepCopier)),
                        (Serializer)serializer.CreateDelegate(typeof(Serializer)),
                        (Deserializer)deserializer.CreateDelegate(typeof(Deserializer)), true);
        }

**Comment by ReubenBond** [comment]
@bmchilds So it seems that the fallback serializer is being used, meaning either:
* The `ReadOnlySet<T>` is contained in some other type which Orleans doesn't have a serializer for (but is marked as `[Serializable]`
* The assembly containing the generated serializer isn't loaded
Where is your `Register()` method being called?

**Comment by bmchilds** [comment]
The register is called when the orleans client is initialized from SerializationManager.FindSerializationInfo.

**Comment by ReubenBond** [comment]
@bmchilds this exception is happening on the silo, not the client. Can you confirm that the assembly containing the generated serialzier is loaded on the silo?

**Comment by bmchilds** [comment]
Yes, the register is being called when the silo initializes.  There is an exception being thrown that may be the cause based on your previous commment.  Newtonsoft.Json 8.0.0.0 doesn't exist because orleans is linked to a different version.

Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Exception = System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, Logger logger)

[2017-01-06 23:02:26.193 GMT     9      WARNING 101723  AssemblyProcessor       127.0.0.1:11111]    AssemblyLoader encountered an exception loading types from assembly 'Service.Data.Notification, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null': System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, Logger logger)
Exc level 0: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, Logger logger)
Exc level 1: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
[2017-01-06 23:02:27.825 GMT     9      WARNING 101215  Scheduler.WorkItemGroup 127.0.0.1:11111]    Task [Id=1034, Status=RanToCompletion] in WorkGroup [Activation: S127.0.0.1:11111:221439692*grn/7A0C5A70/00000000+estimates.302.2T.01-0R29-342@e5a1d384 #GrainType=Grains.EstimateGrain Placement=RandomPlacement State=Valid] took elapsed time 0:00:05.1257158 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/3, ManagedThreadId=9, Executing Task Id=1034 Status=RanToCompletion for 00:00:05.1299516 on WorkItem=WorkItemGroup:Name=[Activation: S127.0.0.1:11111:221439692*grn/7A0C5A70/00000000+estimates.302.2T.01-0R29-342@e5a1d384 #GrainType=Grains.EstimateGrain Placement=RandomPlacement],WorkGroupStatus=Running Executing for 00:00:05.1305182. .>

**Comment by ReubenBond** [comment]
@bmchilds you can increase logging verbosity to Verbose3 and see if that helps.
```xml
<Defaults>
    <Tracing DefaultTraceLevel="Verbose3" ... />
  </Defaults>
```
Or in programmatic config:
```C#
config.Defaults.DefaultTraceLevel = Severity.Verbose3
```
Can you show me the method/line in your code which is throwing? What's the signature of that method and what's being sent back to the client?

**Comment by bmchilds** [comment]
I isolated just the ReadOnlySet class and was able to use the custom serializer with no problems.  I'm now guessing it is what you said before: ...is contained in some other type which Orleans doesn't have a serializer for (but is marked as [Serializable]).  Thanks for your help.

**Comment by ReubenBond** [comment]
@bmchilds is this issue resolved?

**Comment by bmchilds** [comment]
Yes, thank you very much for your help.  You pointed me in the right
direction.

**Comment by ReubenBond** [comment]
No worries, thanks :)
