### ISSUE TITLE
Can't set global grain GC limit to anything less than 1 minute

### ISSUE THREAD

**Issue by yevhen** [dotnet/orleans#271]
Orleans documentation states that default collection age limit could be set to seconds (s) and even milliseconds (ms). However, when trying to set it to be anything less than 1 minute, the silo refuses to boot, giving back a sea of exceptions.

The exceptions are coming from multiple places:

```
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:20.139 GMT    19	WARNING	100534	Catalog	127.0.0.1:11111]	Failed to InvokeActivate for [Activation: S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@c04db18a #GrainType=Orleans.Runtime.ReminderService.GrainBasedReminderTable State=Invalid].	
Exc level 0: System.ArgumentException: timeout must be at least 00:01:00, but it is 00:00:10
Parameter name: timeout
   at Orleans.Runtime.ActivationCollector.MakeTicketFromTimeSpan(TimeSpan timeout)
   at Orleans.Runtime.ActivationCollector.ScheduleCollection(ActivationData item)
   at Orleans.Runtime.Catalog.<InitActivation>d__2b.MoveNext()
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:20.159 GMT    16	WARNING	100147	Dispatcher	127.0.0.1:11111]	Intermediate warning for NonExistentActivation from Catalog.GetOrCreateActivation for message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@c04db18a #14: Orleans.Orleans.IReminderTable:ReadRows()	
Exc level 0: Orleans.Runtime.Catalog+NonExistentActivationException: Non-existent activation: [ActivationAddress: S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@c04db18a, Full GrainId: [GrainId: *grn/FCB3F509/0000000000000000000000000000303903fffffffcb3f509-0xBB9ED002, IdCategory: Grain, BaseTypeCode: -55315191 (xFCB3F509), PrimaryKey: 12345 (x3039), UniformHashCode: 3147747330 (0xBB9ED002)], Full ActivationId: @4ffebb20c2fac9d2bb8e8832c04db18a0000000000000000], grain type: .
   at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Task& activatedPromise)
   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message)
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:20.169 GMT    11	WARNING	100147	Dispatcher	127.0.0.1:11111]	Intermediate warning for NonExistentActivation from Catalog.GetOrCreateActivation for message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@c04db18a #15: Orleans.Orleans.IReminderTable:ReadRows()	
Exc level 0: Orleans.Runtime.Catalog+NonExistentActivationException: Non-existent activation: [ActivationAddress: S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@c04db18a, Full GrainId: [GrainId: *grn/FCB3F509/0000000000000000000000000000303903fffffffcb3f509-0xBB9ED002, IdCategory: Grain, BaseTypeCode: -55315191 (xFCB3F509), PrimaryKey: 12345 (x3039), UniformHashCode: 3147747330 (0xBB9ED002)], Full ActivationId: @4ffebb20c2fac9d2bb8e8832c04db18a0000000000000000], grain type: .
   at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Task& activatedPromise)
   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message)
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:20.209 GMT    12	WARNING	100147	Dispatcher	127.0.0.1:11111]	Intermediate warning for NonExistentActivation from Catalog.GetOrCreateActivation for message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@c04db18a #18: Orleans.Orleans.IReminderTable:ReadRows()	
Exc level 0: Orleans.Runtime.Catalog+NonExistentActivationException: Non-existent activation: [ActivationAddress: S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@c04db18a, Full GrainId: [GrainId: *grn/FCB3F509/0000000000000000000000000000303903fffffffcb3f509-0xBB9ED002, IdCategory: Grain, BaseTypeCode: -55315191 (xFCB3F509), PrimaryKey: 12345 (x3039), UniformHashCode: 3147747330 (0xBB9ED002)], Full ActivationId: @4ffebb20c2fac9d2bb8e8832c04db18a0000000000000000], grain type: .
   at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Task& activatedPromise)
   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message)
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:20.189 GMT    17	WARNING	100147	Dispatcher	127.0.0.1:11111]	Intermediate warning for NonExistentActivation from Catalog.GetOrCreateActivation for message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@c04db18a #16: Orleans.Orleans.IReminderTable:ReadRows()	
Exc level 0: Orleans.Runtime.Catalog+NonExistentActivationException: Non-existent activation: [ActivationAddress: S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@c04db18a, Full GrainId: [GrainId: *grn/FCB3F509/0000000000000000000000000000303903fffffffcb3f509-0xBB9ED002, IdCategory: Grain, BaseTypeCode: -55315191 (xFCB3F509), PrimaryKey: 12345 (x3039), UniformHashCode: 3147747330 (0xBB9ED002)], Full ActivationId: @4ffebb20c2fac9d2bb8e8832c04db18a0000000000000000], grain type: .
   at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Task& activatedPromise)
   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message)
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:20.149 GMT    14	WARNING	100147	Dispatcher	127.0.0.1:11111]	Intermediate warning for NonExistentActivation from Catalog.GetOrCreateActivation for message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@c04db18a #13: Orleans.Orleans.IReminderTable:ReadRows()	
Exc level 0: Orleans.Runtime.Catalog+NonExistentActivationException: Non-existent activation: [ActivationAddress: S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@c04db18a, Full GrainId: [GrainId: *grn/FCB3F509/0000000000000000000000000000303903fffffffcb3f509-0xBB9ED002, IdCategory: Grain, BaseTypeCode: -55315191 (xFCB3F509), PrimaryKey: 12345 (x3039), UniformHashCode: 3147747330 (0xBB9ED002)], Full ActivationId: @4ffebb20c2fac9d2bb8e8832c04db18a0000000000000000], grain type: .
   at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Task& activatedPromise)
   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message)
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:20.559 GMT    14	WARNING	101220	Scheduler.WorkItemGroup	127.0.0.1:11111]	WorkItemGroup is being stoped while still active. workItemCount = 8 WorkItemGroup:Name=[Activation: S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #GrainType=Orleans.Runtime.ReminderService.GrainBasedReminderTable],State=Running. Currently QueuedWorkItems=8; Total EnQueued=11; Total processed=2; Quantum expirations=0; TaskRunner=ActivationTaskScheduler-13:Queued=8; SchedulingContext=[Activation: S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #GrainType=Orleans.Runtime.ReminderService.GrainBasedReminderTable State=Invalid]
 Called from    at Orleans.Runtime.Scheduler.WorkItemGroup.ReportWorkGroupProblemWithBacktrace(String what, ErrorCode errorCode)
   at Orleans.Runtime.Scheduler.WorkItemGroup.Stop()
   at Orleans.Runtime.Scheduler.OrleansTaskScheduler.UnregisterWorkContext(ISchedulingContext context)
   at Orleans.Runtime.Catalog.UnregisterMessageTarget(ActivationData activation)
   at Orleans.Runtime.Catalog.<InitActivation>d__2b.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<Run>b__0(Object state)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at Orleans.Runtime.Scheduler.OrleansTaskScheduler.RunTask(Task task)
   at Orleans.Runtime.Scheduler.TaskWorkItem.Execute()
   at Orleans.Runtime.Scheduler.WorkerPoolThread.Run()
   at Orleans.Runtime.AsynchAgent.AgentThreadProc(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
	
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:20.629 GMT    14	WARNING	100534	Catalog	127.0.0.1:11111]	Failed to InvokeActivate for [Activation: S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #GrainType=Orleans.Runtime.ReminderService.GrainBasedReminderTable State=Invalid].	
Exc level 0: System.ArgumentException: timeout must be at least 00:01:00, but it is 00:00:10
Parameter name: timeout
   at Orleans.Runtime.ActivationCollector.MakeTicketFromTimeSpan(TimeSpan timeout)
   at Orleans.Runtime.ActivationCollector.ScheduleCollection(ActivationData item)
   at Orleans.Runtime.Catalog.<InitActivation>d__2b.MoveNext()
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:20.819 GMT    16	WARNING	101032	Dispatcher	127.0.0.1:11111]	Forwarding failed: tried to forward message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #16[ForwardCount=2]: Orleans.Orleans.IReminderTable:ReadRows() for 2 times after Non-existent activation to invalid activation. Rejecting now.	
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:20.889 GMT    16	WARNING	101032	Dispatcher	127.0.0.1:11111]	Forwarding failed: tried to forward message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #31[ForwardCount=2]: Orleans.Orleans.IReminderTable:ReadRows() for 2 times after Non-existent activation to invalid activation. Rejecting now.	
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:20.939 GMT    16	WARNING	101032	Dispatcher	127.0.0.1:11111]	Forwarding failed: tried to forward message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #14[ForwardCount=2]: Orleans.Orleans.IReminderTable:ReadRows() for 2 times after Non-existent activation to invalid activation. Rejecting now.	
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:21.019 GMT    16	WARNING	101032	Dispatcher	127.0.0.1:11111]	Forwarding failed: tried to forward message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #15[ForwardCount=2]: Orleans.Orleans.IReminderTable:ReadRows() for 2 times after Non-existent activation to invalid activation. Rejecting now.	
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:21.099 GMT    16	WARNING	101032	Dispatcher	127.0.0.1:11111]	Forwarding failed: tried to forward message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #18[ForwardCount=2]: Orleans.Orleans.IReminderTable:ReadRows() for 2 times after Non-existent activation to invalid activation. Rejecting now.	
HelloWorldNuget.vshost.exe Error: 0 : [2015-03-26 23:01:21.099 GMT    11	ERROR  	102920	ReminderService	127.0.0.1:11111]	!!!!!!!!!! Failed to read rows from table.	
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.ReminderService.LocalReminderService.<ReadTableAndStartTimers>d__2d.MoveNext()
Exc level 1: Orleans.Runtime.OrleansException: Forwarding failed: tried to forward message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #16[ForwardCount=2]: Orleans.Orleans.IReminderTable:ReadRows() for 2 times after Non-existent activation to invalid activation. Rejecting now. 
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:21.379 GMT    11	WARNING	101215	Scheduler.ReminderService.WorkItemGroup	127.0.0.1:11111]	Task [Id=1, Status=RanToCompletion] in WorkGroup [SystemTarget: S127.0.0.1:11111:165106875ReminderService@S00000010] took elapsed time 0:00:00.4354176 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/1, ManagedThreadId=11, Executing Task Id=1 Status=RanToCompletion for 00:00:00.4700007>	
HelloWorldNuget.vshost.exe Error: 0 : [2015-03-26 23:01:21.579 GMT    11	ERROR  	102920	ReminderService	127.0.0.1:11111]	!!!!!!!!!! Failed to read rows from table.	
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.ReminderService.LocalReminderService.<ReadTableAndStartTimers>d__2d.MoveNext()
Exc level 1: Orleans.Runtime.OrleansException: Forwarding failed: tried to forward message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #31[ForwardCount=2]: Orleans.Orleans.IReminderTable:ReadRows() for 2 times after Non-existent activation to invalid activation. Rejecting now. 
HelloWorldNuget.vshost.exe Warning: 0 : [2015-03-26 23:01:21.649 GMT    11	WARNING	101215	Scheduler.ReminderService.WorkItemGroup	127.0.0.1:11111]	Task [Id=2, Status=RanToCompletion] in WorkGroup [SystemTarget: S127.0.0.1:11111:165106875ReminderService@S00000010] took elapsed time 0:00:00.2041221 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/1, ManagedThreadId=11, Executing Task Id=2 Status=RanToCompletion for 00:00:00.2100003>	
HelloWorldNuget.vshost.exe Error: 0 : [2015-03-26 23:01:21.669 GMT    19	ERROR  	102920	ReminderService	127.0.0.1:11111]	!!!!!!!!!! Failed to read rows from table.	
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.ReminderService.LocalReminderService.<ReadTableAndStartTimers>d__2d.MoveNext()
Exc level 1: Orleans.Runtime.OrleansException: Forwarding failed: tried to forward message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #14[ForwardCount=2]: Orleans.Orleans.IReminderTable:ReadRows() for 2 times after Non-existent activation to invalid activation. Rejecting now. 
HelloWorldNuget.vshost.exe Error: 0 : [2015-03-26 23:01:21.719 GMT    19	ERROR  	102920	ReminderService	127.0.0.1:11111]	!!!!!!!!!! Failed to read rows from table.	
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.ReminderService.LocalReminderService.<ReadTableAndStartTimers>d__2d.MoveNext()
Exc level 1: Orleans.Runtime.OrleansException: Forwarding failed: tried to forward message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #15[ForwardCount=2]: Orleans.Orleans.IReminderTable:ReadRows() for 2 times after Non-existent activation to invalid activation. Rejecting now. 
HelloWorldNuget.vshost.exe Error: 0 : [2015-03-26 23:01:21.759 GMT    19	ERROR  	102920	ReminderService	127.0.0.1:11111]	!!!!!!!!!! Failed to read rows from table.	
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.ReminderService.LocalReminderService.<ReadTableAndStartTimers>d__2d.MoveNext()
Exc level 1: Orleans.Runtime.OrleansException: Forwarding failed: tried to forward message Request S127.0.0.1:11111:165106875ReminderService@S00000010->S127.0.0.1:11111:165106875*grn/FCB3F509/00003039@60b513b3 #18[ForwardCount=2]: Orleans.Orleans.IReminderTable:ReadRows() for 2 times after Non-existent activation to invalid activation. Rejecting now. 
```

You can reproduce this by setting the following configuration in `HelloWorldNuget` sample:

```xml
<Application>
  <Defaults>
    <Deactivation AgeLimit="10s"/>
  </Defaults>
</Application>
```

Orleans version is 1.0.5.

**Comment by gabikliot** [comment]
Yes, right.
We should definitely do the following two things:
1) Match the docs to the code. 
2) Fail early with clear exception, and not late with a bunch of them.
Will fix soon.

As for the actual limit - we want to keep it at 1 minute. There is some background activity related to how frequently we collect inactive activations, so we don't want to run it too frequency, yet do want to collect as soon as possible after it become idle.

**Comment by gabikliot** [comment]
Yevgeny, I could not find that: "Orleans documentation states that default collection age limit could be set to seconds (s) and even milliseconds (ms)."

Could you please point me to the page you are referring to?

**Comment by yevhen** [comment]
Sure, it's here http://dotnet.github.io/orleans/Advanced-Concepts/Activation-Garbage-Collection
See Configuration section (next to How Activation-GC Works).

**Comment by gabikliot** [comment]
It just says you can specify time in milli seconds, does not say anything about allowed value. But it also does not specify limitations, which is wrong. Just added "The minimal allowed age limit is 1 minute."

**Comment by gabikliot** [comment]
That was a fun one!
We had the check for minimal allowed Activation CG AgeLimit when config is loaded (causing silo to fail to start early if misconfigured), but the check was performed only under DEBUG for some reason. As a result silo started misconfigured and was failing to activate new grains later on.
HelloWorldNuget, as all samples, consume Release dlls, so the check was compiled out.

Fix is here: https://github.com/dotnet/orleans/pull/274.
Thanks @yevhen for spotting this out.

**Comment by gabikliot** [comment]
Looks like we can close it now, with #274 merged, @yevhen ?

**Comment by yevhen** [comment]
Yep!
