### ISSUE TITLE
Having a null grain reference as a property on a GrainState object results in an exception

### ISSUE THREAD

**Issue by ElanHasson** [dotnet/orleans#2750]
Having a Grain state object fails to persist if a grain Interface property is unset (`null`)

Solution is to set EventGrainState.Metadata.Owner = to a grain reference.

**Code:**
```csharp
 public class EventGrainState
    {
        public bool IsInitialized { get; set; }
        public ObjectMetadata Metadata { get; set; } = new ObjectMetadata();
        public string Name { get; set; }
        public EventData Data { get; set; } = new EventData();
        public TimeSpan Interval { get; set; }
    }
   public class ObjectMetadata
    {
        public DateTime CreatedDate { get; internal set; }
        public DateTime ModifiedDate { get; internal set; }
        public IUserGrain Owner { get; internal set; }
    }
    public class EventData
    {
        public string EventType { get; set; }
        public string Parameters { get; set; }
    }
```

**Stack Trace:**

```Cannot pass null as an argument to AsReference
Parameter name: grain
   at Orleans.GrainExtensions.AsReference[TGrainInterface](IAddressable grain)
   at NRC.Services.Scheduler.Grains.OrleansCodeGenNRC_Services_Scheduler_Grains_ObjectMetadataSerializer.DeepCopier(Object original)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original)
   at NRC.Services.Scheduler.Grains.OrleansCodeGenNRC_Services_Scheduler_Grains_EventGrainStateSerializer.DeepCopier(Object original)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original)
   at Orleans.OrleansCodeGenOrleans_GrainStateSerializer`1.DeepCopier(Object original)
   at Orleans.Serialization.SerializationManager.<>c__DisplayClass61_0.<Register>b__0(Object obj)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original)
   at Orleans.Serialization.SerializationManager.DeepCopy(Object original)
   at Orleans.Runtime.GrainReference.InvokeMethodAsync[T](Int32 methodId, Object[] arguments, InvokeMethodOptions options, SiloAddress silo)
   at Orleans.Storage.OrleansCodeGenMemoryStorageGrainReference.WriteStateAsync(String grainType, String grainId, IGrainState grainState)
   at Orleans.Storage.MemoryStorage.<WriteStateAsync>d__21.MoveNext()
```

**Comment by ReubenBond** [comment]
Just to clarify, you're using 2.0 Technical Preview, correct?

**Comment by ElanHasson** [comment]
Correct. Sorry I forgot to include.
