### ISSUE TITLE
SqlServerStorageTests.WriteReadWriteRead100StatesInParallel test failing

### ISSUE THREAD

**Issue by jdom** [dotnet/orleans#2790]
Getting the following error when running the functionals lately:
`WriteReadWriteRead100StatesInParallel [0:37.528] Failed: Orleans.Storage.InconsistentStateException: Version conflict (WriteState): ServiceId=00000000-0000-0000-0000-000000000000 ProviderName=System.Data.SqlClient_StorageProvider GrainType=UnitTests.StorageTests.Relational.TestDataSets.GrainTypeGenerator+TestGrainGenericWithGuidKey'1[[System.Double, mscorlib]] GrainId=33900 ETag=.`

@veikkoeeva / @shayhatsor do you know of anything that changed in the relational code that might be causing this?
Full stacktrace below:

```
Orleans.Storage.InconsistentStateException
Version conflict (WriteState): ServiceId=00000000-0000-0000-0000-000000000000 ProviderName=System.Data.SqlClient_StorageProvider GrainType=UnitTests.StorageTests.Relational.TestDataSets.GrainTypeGenerator+TestGrainGenericWithGuidKey`1[[System.Double, mscorlib]] GrainId=33900 ETag=.
   at Orleans.Storage.AdoNetStorageProvider.<WriteStateAsync>d__43.MoveNext() in D:\projects\orleans\src\OrleansSQLUtils\Storage\Provider\AdoNetStorageProvider.cs:line 449
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at UnitTests.StorageTests.Relational.CommonStorageTests.<Store_WriteRead>d__9`1.MoveNext() in D:\projects\orleans\test\TesterInternal\StorageTests\CommonStorageTests.cs:line 157
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at UnitTests.StorageTests.Relational.CommonStorageTests.<>c__DisplayClass5_1.<<PersistenceStorage_WriteReadWriteReadStatesInParallel>b__1>d.MoveNext() in D:\projects\orleans\test\TesterInternal\StorageTests\CommonStorageTests.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at UnitTests.StorageTests.Relational.CommonStorageTests.<PersistenceStorage_WriteReadWriteReadStatesInParallel>d__5.MoveNext() in D:\projects\orleans\test\TesterInternal\StorageTests\CommonStorageTests.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at UnitTests.StorageTests.Relational.RelationalStorageTests.<Relational_WriteReadWriteRead100StatesInParallel>d__25.MoveNext() in D:\projects\orleans\test\TesterSQLUtils\StorageTests\Relational\RelationalStorageTests.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at UnitTests.StorageTests.Relational.SqlServerStorageTests.<WriteReadWriteRead100StatesInParallel>d__4.MoveNext() in D:\projects\orleans\test\TesterSQLUtils\StorageTests\Relational\SqlServerStorageTests.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 227
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90


```

**Comment by veikkoeeva** [comment]
@jdom Which version this is? It looks like the `throw` is initiated [here](https://github.com/dotnet/orleans/blob/master/src/OrleansSQLUtils/Storage/Provider/AdoNetStorageProvider.cs#L445), but the line is different. The version check fails, the reasoning is [here](https://github.com/dotnet/orleans/blob/master/src/OrleansSQLUtils/Storage/Provider/AdoNetStorageProvider.cs#L473) and together with the tests [here](https://github.com/dotnet/orleans/blob/master/test/TesterInternal/StorageTests/CommonStorageTests.cs#L58) it might clue in as to why this might happen.

I don't know of any changes. The `ETag` field suggests the tag is `null` during the conflict, which suggests it'd be the first write that somehow fails. In the script [here](https://github.com/dotnet/orleans/blob/master/src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql#L771) the version given is assigned to the SQL variable, which is then returned and compared in the provider code. This would mean two grains with the same ID (the `i` counter in the test `.Select`) would be the same. I wonder why could that be as apparently there aren't two sets of tests being run in parallel. Or other option being the table isn't cleared and the old test results are in, and the tests then fail since the situation look like if the "Orleans grain state" isn't in sync that in persistent storage, i.e. it hasn't be read in to the cluster.

**Comment by jdom** [comment]
I think the fix is simpler. Looks like it was colliding with some leftover data from other tests in the same run, because this line [here](https://github.com/dotnet/orleans/blob/master/test/TesterInternal/StorageTests/CommonStorageTests.cs#L58) was not using the grainId created in the previous line (which effectively isolates it from colliding with other tests).
Not sure which is the other test using the same colliding grain ID, but it is clear that's the case, because running the test in isolation works, but if I run all the tests in SqlServerStorageTests, then that's when this test fails. And since we don't clear the table per test, but per fixture entire, this all makes sense.

The line being the one after the exception is thrown is something that I've seen several times, so that's OK, and we are both looking at the latest version in master.

Thanks a lot for helping me look into it, I'll submit a PR right away

**Comment by jdom** [comment]
BTW, this code was slightly changed by @ReubenBond in #2599, but I'm not sure how that change made this test start failing anyway, as the change does look like it's still doing the same thing. It might be just pure luck in the order of the tests being run.

**Comment by veikkoeeva** [comment]
@jdom Yes, the range could be picked better or some other coordination mechanism. It's very good you spotted it and could roll the sleeves, much appreciated. :)

**Comment by jdom** [comment]
Hmmm, I now get a different failure in this test (cannot reproduce if I run it locally):

```
System.Data.SqlClient.SqlException : Transaction (Process ID 87) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
Stack trace
at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.SqlUtils.RelationalStorage.<ExecuteReaderAsync>d__13`1.MoveNext() in D:\build\_work\2\s\src\OrleansSQLUtils\Storage\RelationalStorage.cs:line 228
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.SqlUtils.RelationalStorage.<ExecuteAsync>d__14`1.MoveNext() in D:\build\_work\2\s\src\OrleansSQLUtils\Storage\RelationalStorage.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.SqlUtils.RelationalStorage.ReadAsync[TResult](String query, Action`1 parameterProvider, Func`4 selector, CancellationToken cancellationToken, CommandBehavior commandBehavior) in D:\build\_work\2\s\src\OrleansSQLUtils\Storage\RelationalStorage.cs:line 139
at Orleans.Storage.AdoNetStorageProvider.<WriteStateAsync>d__43.MoveNext() in D:\build\_work\2\s\src\OrleansSQLUtils\Storage\Provider\AdoNetStorageProvider.cs:line 438
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.StorageTests.Relational.CommonStorageTests.<Store_WriteRead>d__9`1.MoveNext() in D:\build\_work\2\s\test\TesterInternal\StorageTests\CommonStorageTests.cs:line 157
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.StorageTests.Relational.CommonStorageTests.<>c__DisplayClass5_1.<<PersistenceStorage_WriteReadWriteReadStatesInParallel>b__1>d.MoveNext() in D:\build\_work\2\s\test\TesterInternal\StorageTests\CommonStorageTests.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.StorageTests.Relational.CommonStorageTests.<PersistenceStorage_WriteReadWriteReadStatesInParallel>d__5.MoveNext() in D:\build\_work\2\s\test\TesterInternal\StorageTests\CommonStorageTests.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.StorageTests.Relational.RelationalStorageTests.<Relational_WriteReadWriteRead100StatesInParallel>d__25.MoveNext() in D:\build\_work\2\s\test\TesterSQLUtils\StorageTests\Relational\RelationalStorageTests.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.StorageTests.Relational.SqlServerStorageTests.<WriteReadWriteRead100StatesInParallel>
```

Could this be related to the fact that in our CI build we run each test assembly concurrently and for some reason they don't have the correct isolation for the transactions?

**Comment by veikkoeeva** [comment]
@jdom The storage operations run in sepate transactions (see the `BEGIN TRANSACTION` in the script), which is unlikely the problem in this case (reading the stack trace) unless other storage table tests could run simulatenously. This is not the case, as far as I know, since they're within the same fixture (e.g. SqlServer tests). Also the most likely violation would be that of version number mismatch. 

Deadlocking isn't completely avoidable in the `INSERT` case, since the DB need to add entries to the index (according to my best knowledge). The test stresses the database quite heavily in this regard and the less resources the DB has, the more apparent the problem becomes in case multiple `INSERT` cases are running concurrently (within fractions of milliseconds, I would suppose). I would say that if this becomes a problem, we could safely put less write operations exactly concurrently by introducing a small random delay before the first `INSERT` for each grain or just make less concurrent operations (reduce the range counter).

That being written, the query is somewhat sensitive for the case when one inserts with the same hash IDs concurrently, as they hit the same rows and places in index. I don't think this could be the case except in hash collision tests which will deadlock "easily" in case multiple (exactly) concurrent IDs being inserted. This case should be covered on how Orleans works and hopefully avoiding a case where, say, same grain is concurrently activated 100 times and all instances try to get to the DB.

One thing also might affect, but I didn't notice anything when examining the queries on the engines I had, could be to use index hint on `UPDATE` (example: http://stackoverflow.com/questions/24975353/sql-server-how-to-hint-an-index-on-an-update-command), but the `UPDATE` already picked that exact index since the parameters hit straight to it.

**Comment by veikkoeeva** [comment]
@jdom Have you run these tests in the CI before and is the CI machine more or less powerful now? That could explain if there are failures on this. This is more stress testing than testing for correctness, I suppose, though one needs to have correct results too.

**Comment by veikkoeeva** [comment]
@jdom At least one more thing, I considered adding retries in case of deadlocks, but I didn't since it would have been extra work to:
a) Check what is the error code for each of the backends (they don't have the same code for deadlock).
b) To write a test to induce a deadlock artificially to check the error code doesn't change between drivers and is detected.
c) To write the actual retry code.

It might make sense to do do this. I think deadlocks are unusual under normal operations, but not impossible. In a really bad and constrained scenario, e.g. a broken disk system or something, one would experience them anyhow and would need to take precaution, so trying to eradicate them in hopes of not seeing them ever would be futile.

**Comment by jdom** [comment]
To be fair, you and Shay are the domain experts here. I mainly brought this to your attention, but I can't really help on what is the best solution, as I don't have the familiarity. What I would want asap is to get this test not failing any more that breaks our entire test run. If that means making it less stressful, and potentially create a stressful test that we temporarily skip until we improve the runtime, or that we actually avoid deadlocks altogether as you suggested later, I don't really mind. But I'd like to know what is the best way to get rid of the test failure for now in a way that this doesn't just hide the problem (if you think there is actually one that needs addressing) under the rug.
Any suggestions that we can implement ASAP?

**Comment by veikkoeeva** [comment]
@jdom Make the test less stressing.

Options to do that:
- Reduce the count concurrent grains
- Recude the count the grains do the read-write cycle in the `for` loop.
- Add a slight random delay before the initial `INSERT` to scatter them.
- Do any combination of the above three.

All of the actions will still allow a slight chance of a deadlocking failure if the resources are scarce enough.

Without seeing the actual deadlock graph, I'm fairly certain the problem manifests from the tight `for` loop and simultaneous `INSERTs`, since the `INSERT` takes heavier locks. The correctness part can be tested even with two grains, I believe, just to see there are no "data races" (in some sense) when the tight loop runs.

I might be able to look into this tomorrow briefly if the above suggestions don't work. Otherwise I'm rather tied over the weekend unfortunately.
