### ISSUE TITLE
Incompatible NuGet packages in Microsoft.Orleans.Server

### ISSUE THREAD

**Issue by wattsm** [dotnet/orleans#2795]
Following the steps described in the [tutorial for running a standalone silo](http://dotnet.github.io/orleans/Tutorials/Running-in-a-Stand-alone-Silo.html) causes the grain project to have incompatible versions of NuGet packages.

I noticed that the `Templates.Grains` and `Templates.Interfaces` NuGet packages referenced in the [minimal application tutorial](http://dotnet.github.io/orleans/Tutorials/Minimal-Orleans-Application.html) are deprecated and so used the `Microsoft.Orleans.OrleansCodeGenerator.Build` package for both the interface and grain projects.

When the grain project is run using `OrleansHost.exe` the silo does start but there are a lot of errors and warnings in the logs. Firstly this:

```
[2017-02-27 13:59:02.177 GMT     1  WARNING 101723  AssemblyProcessor   127.0.0.1:11111]    AssemblyLoader encountered an exception loading types from assembly 'Microsoft.CodeAnalysis, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35': System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, Logger logger)   
Exc level 0: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, Logger logger)
```

Followed by a lot of these:

```
Exc level 1: System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.Metadata, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Looking at the NuGet packages for the solution in Visual Studio I can see that there are two versions of `System.Reflection.Metadata` referenced - v1.2 from `Microsoft.Orleans.Core` and v1.3 from `Microsoft.Orleans.OrleansCodeGenerator`, via `Microsoft.CodeAnalysis.CSharp`. 

I have tried updating all NuGet packages to their latest versions. This causes the silo to exit almost immediately:

```
[2017-02-28 08:24:26.415 GMT     1	ERROR  	100105	OrleansSiloHost	]	!!!!!!!!!! ERROR starting Orleans silo name=XXXX Exception=
Exc level 0: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Orleans.Runtime.Silo..ctor(SiloInitializationParameters initializationParams)
   at Orleans.Runtime.Silo..ctor(String name, SiloType siloType, ClusterConfiguration config)
   at Orleans.Runtime.Host.SiloHost.InitializeOrleansSilo()	
Exc level 0: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Orleans.Runtime.Silo..ctor(SiloInitializationParameters initializationParams)
   at Orleans.Runtime.Silo..ctor(String name, SiloType siloType, ClusterConfiguration config)
   at Orleans.Runtime.Host.SiloHost.InitializeOrleansSilo()
```

I have also tried consolidating the NuGet packages to the highest referenced version which makes no obvious difference.

I created a solution from scratch with just the interfaces and grains projects to illustrate the problem here: https://github.com/wattsm/orleans-error-example. The various attempted fixes can be found in their own branches.

Any suggestions or advice appreciated. Thanks!

**EDIT**

This is actually much easier to reproduce. Create a new project in Visual Studio, add the `Microsoft.Orleans.Server` package, set `OrleansHost.exe` as the startup action and run. You will see the errors above.

I've added a branch, `all-in-one` which contains the project `OrleansExample.Server` as an example, to my repository: https://github.com/wattsm/orleans-error-example

**Comment by sergeybykov** [comment]
>This is actually much easier to reproduce. Create a new project in Visual Studio, add the Microsoft.Orleans.Server package, set OrleansHost.exe as the startup action and run. You will see the errors above.

I did just that. When I was adding `Microsoft.Orleans.Server` package, I made sure the `Dependency behavior` option is set to `Lowest`.
I added your `OrleansConfiguration.xml` from https://github.com/wattsm/orleans-error-example/blob/master/OrleansErrorExample/OrleansErrorExample.Grains/OrleansConfiguration.xml, set `Debug` action to `Start external program` pointing to `bin\Debug\OrleansHost.exe` and set `Working directory` to `bin\Debug`.

After that OrleansHost.exe started a silo just fine. What is the difference I wonder between what you and I did? `Dependency behavior`?

**Comment by wattsm** [comment]
Hi @sergeybykov, thanks for having a look at this.

I just tried the same process again, making sure the NuGet dependency behaviour was lowest and I get the same result. I did not explicitly set the working directory to `bin\Debug` but after doing so I still get the same warnings and errors.

I'm using VS 2015, NuGet v3.4.4.1321, the class library is targeting .Net v4.6 and I'm installing v1.4.0 of the `Microsoft.Orleans.Server` package.

My `packages.config` looks like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0" targetFramework="net46" />
  <package id="Microsoft.CodeAnalysis.Common" version="1.3.2" targetFramework="net46" />
  <package id="Microsoft.CodeAnalysis.CSharp" version="1.3.2" targetFramework="net46" />
  <package id="Microsoft.Extensions.DependencyInjection" version="1.0.0" targetFramework="net46" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="1.0.0" targetFramework="net46" />
  <package id="Microsoft.Orleans.Core" version="1.4.0" targetFramework="net46" />
  <package id="Microsoft.Orleans.CounterControl" version="1.4.0" targetFramework="net46" />
  <package id="Microsoft.Orleans.OrleansCodeGenerator" version="1.4.0" targetFramework="net46" />
  <package id="Microsoft.Orleans.OrleansHost" version="1.4.0" targetFramework="net46" />
  <package id="Microsoft.Orleans.OrleansProviders" version="1.4.0" targetFramework="net46" />
  <package id="Microsoft.Orleans.OrleansRuntime" version="1.4.0" targetFramework="net46" />
  <package id="Microsoft.Orleans.OrleansTelemetryConsumers.Counters" version="1.4.0" targetFramework="net46" />
  <package id="Microsoft.Orleans.Server" version="1.4.0" targetFramework="net46" />
  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net46" />
  <package id="System.AppContext" version="4.1.0" targetFramework="net46" />
  <package id="System.Collections" version="4.0.11" targetFramework="net46" />
  <package id="System.Collections.Concurrent" version="4.0.12" targetFramework="net46" />
  <package id="System.Collections.Immutable" version="1.2.0" targetFramework="net46" />
  <package id="System.ComponentModel" version="4.0.1" targetFramework="net46" />
  <package id="System.Console" version="4.0.0" targetFramework="net46" />
  <package id="System.Diagnostics.Debug" version="4.0.11" targetFramework="net46" />
  <package id="System.Diagnostics.FileVersionInfo" version="4.0.0" targetFramework="net46" />
  <package id="System.Diagnostics.StackTrace" version="4.0.1" targetFramework="net46" />
  <package id="System.Diagnostics.Tools" version="4.0.1" targetFramework="net46" />
  <package id="System.Dynamic.Runtime" version="4.0.11" targetFramework="net46" />
  <package id="System.Globalization" version="4.0.11" targetFramework="net46" />
  <package id="System.IO.FileSystem" version="4.0.1" targetFramework="net46" />
  <package id="System.IO.FileSystem.Primitives" version="4.0.1" targetFramework="net46" />
  <package id="System.Linq" version="4.1.0" targetFramework="net46" />
  <package id="System.Linq.Expressions" version="4.1.0" targetFramework="net46" />
  <package id="System.Reflection" version="4.1.0" targetFramework="net46" />
  <package id="System.Reflection.Metadata" version="1.3.0" targetFramework="net46" />
  <package id="System.Reflection.Primitives" version="4.0.1" targetFramework="net46" />
  <package id="System.Resources.ResourceManager" version="4.0.1" targetFramework="net46" />
  <package id="System.Runtime" version="4.1.0" targetFramework="net46" />
  <package id="System.Runtime.Extensions" version="4.1.0" targetFramework="net46" />
  <package id="System.Runtime.Handles" version="4.0.1" targetFramework="net46" />
  <package id="System.Runtime.InteropServices" version="4.1.0" targetFramework="net46" />
  <package id="System.Runtime.Numerics" version="4.0.1" targetFramework="net46" />
  <package id="System.Security.Cryptography.Algorithms" version="4.2.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Encoding" version="4.0.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Primitives" version="4.0.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.1.0" targetFramework="net46" />
  <package id="System.Text.Encoding" version="4.0.11" targetFramework="net46" />
  <package id="System.Text.Encoding.CodePages" version="4.0.1" targetFramework="net46" />
  <package id="System.Text.Encoding.Extensions" version="4.0.11" targetFramework="net46" />
  <package id="System.Threading" version="4.0.11" targetFramework="net46" />
  <package id="System.Threading.Tasks" version="4.0.11" targetFramework="net46" />
  <package id="System.Threading.Tasks.Parallel" version="4.0.1" targetFramework="net46" />
  <package id="System.Threading.Thread" version="4.0.0" targetFramework="net46" />
  <package id="System.Xml.ReaderWriter" version="4.0.11" targetFramework="net46" />
  <package id="System.Xml.XDocument" version="4.0.11" targetFramework="net46" />
  <package id="System.Xml.XmlDocument" version="4.0.1" targetFramework="net46" />
  <package id="System.Xml.XPath" version="4.0.1" targetFramework="net46" />
  <package id="System.Xml.XPath.XDocument" version="4.0.1" targetFramework="net46" />
</packages>
```

**Comment by sergeybykov** [comment]
The difference appears to be that my project targeted .NET 4.5. After I re-created it for 4.6, I'm getting the assembly load errors and warnings, but the silo still starts.

**Comment by wattsm** [comment]
The silo does start, however I think the warnings/errors that occur during startup prevent it from functioning correctly. For example, if you add a storage provider then it will crash during startup.

Configuration:

```xml
<?xml version="1.0" encoding="utf-8"?>
<OrleansConfiguration xmlns="urn:orleans">
  <Globals>
    <SeedNode Address="localhost" Port="11111" />
    <StorageProviders>
      <Provider Type="Orleans.Storage.MemoryStorage" Name="MemoryStorage"  />
    </StorageProviders>
  </Globals>
  <Defaults>
    <Networking Address="localhost" Port="11111" />
    <ProxyingGateway Address="localhost" Port="30000" />
  </Defaults>
</OrleansConfiguration>
```

Error:

```
[2017-03-01 18:16:09.750 GMT     1	ERROR  	100439	Silo	127.0.0.1:11111]	!!!!!!!!!! Exception during Silo.Start	
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
Exc level 1: Orleans.Runtime.OrleansException: Provider of type Orleans.Storage.MemoryStorage name MemoryStorage was not loaded.Please check that you deployed the assembly in which the provider class is defined to the execution folder.
   at Orleans.Providers.ProviderLoader`1.ValidateProviders()
   at Orleans.Providers.ProviderLoader`1.LoadProviders(IDictionary`2 configs, IProviderManager providerManager)
   at Orleans.Runtime.Storage.StorageProviderManager.LoadStorageProviders(IDictionary`2 configs)
   at Orleans.Runtime.Silo.<DoStart>b__96_1()
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
[2017-03-01 18:16:09.755 GMT     1	ERROR  	100105	OrleansSiloHost	127.0.0.1:11111]	!!!!!!!!!! ERROR starting Orleans silo name=Home-PC Exception=
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo(Boolean catchExceptions)
Exc level 1: Orleans.Runtime.OrleansException: Provider of type Orleans.Storage.MemoryStorage name MemoryStorage was not loaded.Please check that you deployed the assembly in which the provider class is defined to the execution folder.
   at Orleans.Providers.ProviderLoader`1.ValidateProviders()
   at Orleans.Providers.ProviderLoader`1.LoadProviders(IDictionary`2 configs, IProviderManager providerManager)
   at Orleans.Runtime.Storage.StorageProviderManager.LoadStorageProviders(IDictionary`2 configs)
   at Orleans.Runtime.Silo.<DoStart>b__96_1()
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()	
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo(Boolean catchExceptions)
Exc level 1: Orleans.Runtime.OrleansException: Provider of type Orleans.Storage.MemoryStorage name MemoryStorage was not loaded.Please check that you deployed the assembly in which the provider class is defined to the execution folder.
   at Orleans.Providers.ProviderLoader`1.ValidateProviders()
   at Orleans.Providers.ProviderLoader`1.LoadProviders(IDictionary`2 configs, IProviderManager providerManager)
   at Orleans.Runtime.Storage.StorageProviderManager.LoadStorageProviders(IDictionary`2 configs)
   at Orleans.Runtime.Silo.<DoStart>b__96_1()
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
[2017-03-01 18:16:09.762 GMT     2	WARNING	100220	Silo	127.0.0.1:11111]	Process is exiting	
```

The same error occurs if you add the assembly name to the configuration file, i.e. `Orleans.Storage.MemoryProvider, OrleansProviders`, and the `OrleansProviders.dll` is referenced by the project and present in the `bin\Debug` directory.

**Comment by sergeybykov** [comment]
@attilah is convinced this is caused by missing binding redirects in OrleansHost.exe.config for all implicit dependencies that have different versions.

**Comment by attilah** [comment]
I took a look at this and adding the 2 binding redirects from ```app.config``` to ```OrleansHost.exe.config``` fixes the issue and the silo starts all green.

```
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.0.0" newVersion="1.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reflection.Metadata" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.3.0.0" newVersion="1.3.0.0" />
      </dependentAssembly>
```

I'll incorporate these additions into the config file.

**Comment by raghav710** [comment]
For anyone searching for this. I am using Orleans assemblies v1.5.3 and my Orleans.Host.exe failed on startup saying that the assembly System.IO.FileSystem v4.0.1.0 was not found. Copy pasting the binding redirect for that assembly from the app.config of the grain collection (grain interface implementation) project to the Orleans.Host.exe.config worked for me. Thanks @attilah
