### ISSUE TITLE
Enum type is not supported in Grain Method?

### ISSUE THREAD

**Issue by ZhaoXiangXML** [dotnet/orleans#2832]
I'm using Orleans 2.0.0-preview2-201703021703, on .Net Core 1.1.1, on Windows.

So I've a Grain like this:

```
    public interface IConfig : IGrainWithIntegerKey
	{
		Task<int> GetConfig(string key);
	}
```

And it works just fine.

However if I have:

```

	[Serializable]
	public enum Tunnel
	{
		Unknown,
		PC,
		IOS,
		Android
	}

	Task<int> GetConfigWithTunnel(string key, Tunnel tunnel);
```

It does not work.

The SiloHost has the following log when startup:

```
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Exception = System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, Logger logger)

[2017-03-09 14:42:10.516 GMT    13      WARNING 101723  ProviderTypeLoader      127.0.0.1:11112]    AssemblyLoader encountered an exception loading types from assembly 'OrleansCodeGen, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null': System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, Logger logger)
Exc level 0: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, Logger logger)
Exc level 1: System.TypeLoadException: Method 'GetConfigWithTunnel' in type 'StreetballServer.Interface.OrleansCodeGenConfigReference' from assembly 'OrleansCodeGen, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

And there's an exception when I try to call `var config = GrainFactory.GetGrain<IConfig>(0);`:

```
Exc level 0: System.InvalidOperationException: Cannot find generated GrainReference class for interface 'StreetballServer.Interface.IConfig'
   at Orleans.Runtime.TypeMetadataCache.GetGrainReferenceType(Type interfaceType)
   at Orleans.GrainFactory.MakeCaster(Type interfaceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orleans.GrainFactory.Cast(IAddressable grain, Type interfaceType)
   at Orleans.GrainFactory.Cast[TGrainInterface](IAddressable grain)
   at Orleans.GrainFactory.GetGrain[TGrainInterface](Int64 primaryKey, String grainClassNamePrefix)
```

So it appears I can't use enum in parameter, is that so?

**Comment by ZhaoXiangXML** [comment]
My enum is defined in another assembly, and I'm using the default serializer

**Comment by ReubenBond** [comment]
Thanks, Zhao, I'm looking into it.
I cannot repro on v1.5, but I'm trying on v2.0. Are you targeting .NET 4.6 or .NET Core?

**Comment by ZhaoXiangXML** [comment]
I think I found the cause of this problem, the main projects (interfaces, grains, silohost) I have are using .net core 1.1.1 and Visual Studio 2017, however the project which defined the enum is a Windows Class Library created in Visual Studio 2015, the Target framework is "Unity 3.5 .net Subset Base Class Libraries".

Things work fine if the enum is in an library created by Visual Studio 2017, .net core or .net standard.

Guess I need another way to share code between Orleans and Unity.

**Comment by ZhaoXiangXML** [comment]
[HelloWorld.NetCore.zip](https://github.com/dotnet/orleans/files/832895/HelloWorld.NetCore.zip)

This is the code to reproduce this issue

**Comment by ReubenBond** [comment]
Oh, Unity is not supported at this time. Unity runs on Mono & types may be implemented differently between Mono / .NET / .NET Core, so we cannot be sure that they're compatible with each other.

**Comment by ZhaoXiangXML** [comment]
Thanks.

I've solved my problem with "Shared Project"
