### ISSUE TITLE
The extension.vsixmanifest of Orleans Tools for Visual Studio contains invalid child element <Reference>

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [dotnet/orleans#2835]
After installing version 1.4.0 of Orleans Tools for Visual Studio **2015**, Extensions and Updates window has become inaccessible; instead it displays error message `"The input source is not correctly formatted"`.

Looks like `C:\Users\<user_name>\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\<random_id>\extension.vsixmanifest` file contains this invalid element:
```xml
  <Reference Id="NuPackToolsVsix.Microsoft.67e54e40-0ae3-42c5-a949-fddf5739e7a5" MinVersion="1.7.30402.9028">
    <Name>NuGet Package Manager</Name>
    <MoreInfoUrl>http://docs.nuget.org/</MoreInfoUrl>
  </Reference>
```
Because of this, entire Extensions and Updates feature has become unusable. You cannot even remove the offending extension using the 'legal' way - you must delete extension folder manually.

I dont know about VS2017, but this `<Reference>` element is not a part of XML schema of VS2015: if you open this file using any schema-validating parser, it will complain: `The specified node 
cannot be inserted as the valid child of this node, because the specified node is the wrong type.`

**Comment by attilah** [comment]
Hi @0xfeeddeadbeef !

I'm seeing the same issue, even after updating the NuGet VSIX for VS2015 to the latest (3.5) version from [here](https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix).

But what I see is that not WE're the one causing the problem, check the output windows's stack trace:

```
3/10/2017 9:49:45 AM: System.Xml.XmlException: The input source is not correctly formatted.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   at System.Xml.XmlBufferReader.ReadValue(XmlBinaryNodeType nodeType, ValueHandle value)
   at System.Xml.XmlBinaryReader.ReadNode()
   at System.Xml.XmlBinaryReader.Read()
   at System.Xml.XmlBaseReader.MoveToContent()
   at Microsoft.VisualStudio.ExtensionManager.BinaryHelper.ReadXmlElementList(BinaryReader reader)
   at Microsoft.VisualStudio.ExtensionManager.CachedInstalledExtension.Read(BinaryReader reader, String installPath)
   at Microsoft.VisualStudio.ExtensionManager.CachedInstalledExtensionList.ReadCachedInstalledExtension(Package cacheFile, CachedInstalledExtensionListIndexEntry indexEntry, Func`2 getAssetData)
   at Microsoft.VisualStudio.ExtensionManager.CachedInstalledExtensionList.<>c__DisplayClass91_0.<GetEnumerator>b__0(Package cacheFile, CachedInstalledExtensionListIndexEntry indexEntry)
   at Microsoft.VisualStudio.ExtensionManager.CachedInstalledExtensionList.ForEachEntry(Action`2 entryAction, Boolean readExtensionData, Boolean preview)
   at Microsoft.VisualStudio.ExtensionManager.CachedInstalledExtensionList.GetEnumerator()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.PartitionedInstalledExtensionList.GetEnumerator()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at WebExtensionPack.VSPackage.<>c__DisplayClass3_0.<GetMissingExtensions>b__0(KeyValuePair`2 product) in C:\projects\webextensionpack\src\VSPackage.cs:line 114
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at WebExtensionPack.VSPackage.GetMissingExtensions(IVsExtensionManager manager, DataStore store) in C:\projects\webextensionpack\src\VSPackage.cs:line 114
   at WebExtensionPack.VSPackage.<Install>d__1.MoveNext() in C:\projects\webextensionpack\src\VSPackage.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebExtensionPack.VSPackage.<<Initialize>b__0_0>d.MoveNext() in C:\projects\webextensionpack\src\VSPackage.cs:line 29
```

Could you please confirm that you've the ```Web Extension Pack``` installed and this is the problem you see?

@madskristensen can you take a look, why ```Web Extension Pack``` fails after our extension is installed?

For me it does not makes sense that this extension reading our stuff :-)

**Comment by 0xfeeddeadbeef** [comment]
@attilah This has nothing to do with NuGet, - it's the XML schema - the `<Reference>` element should not be there in Orlean Tools' vsixmanifest at all - it is invalid according to `http://schemas.microsoft.com/developer/vsx-schema/2011` XSD schema (at least in VS2015, it might be valid in VS2017).

As for Web Extension Pack, it is trying to get list of all other installed extensions from Visual Studio, and fails to do so, because Visual Studio is unable to read all manifests due to invalid XML in Orelans vsixmanifest.

**Comment by attilah** [comment]
@0xfeeddeadbeef it has something to do with NuGet VSIX, check the docs please: [NuGet VSIX](https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/visual-studio-templates)

This is needed if the templates are installing NuGet packages.

And it is there for ages. The XSD is not relevant IMHO. The XML itself is valid and VS2017 works well. I ask around about this, because it seems that not even @madskristensen's package is the problem, but it can be a VS problem with new packages which contains the VS2017 specific metadata (VSIX has a new schema, but it is backward compatible back to 2013).

**Comment by attilah** [comment]
This is the node what breaks VS2015, but it is required in VS2017 VSIXs.

```
  <Prerequisites>
    <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.0,16.0)" DisplayName="Visual Studio core editor" />
  </Prerequisites>
```

The other two files required by VS2017 is the 2 json files in the package.

If you remove this node and the two json files from the VSIX everything will work as expected.

I'll reach out to the VS team about this issue. Thanks for reporting @0xfeeddeadbeef!

**Comment by attilah** [comment]
Here are the [steps](https://blogs.msdn.microsoft.com/orleans/2017/03/10/fix-visual-studio-2015-with-orleans-tools/) to fix the VS 2015 problem until we release an updated VSIX.

**Comment by sergeybykov** [comment]
This has been fixed in the newly published version of the VSIX - https://visualstudiogallery.msdn.microsoft.com/36903961-63bd-4eec-9ca4-cf2319dc75f4?redir=0.
