### ISSUE TITLE
StatisticsCollectionLevel >= Verbose2 causes silo initialization to fail

### ISSUE THREAD

**Issue by zitmen** [dotnet/orleans#2928]
Hi,

when I put the following line into my Silo.config.xml, the silo init fails with exception and the silo can't be started. If I simply change it to `Verbose` or a higher, it works.
`<Statistics PerfCounterWriteInterval="30s" LogWriteInterval="15m" StatisticsCollectionLevel="Verbose3" />`

I tracked the issue to here:
https://github.com/dotnet/orleans/blob/80693aeffe4d89e24569afd34b91c015a336e7be/src/OrleansRuntime/Scheduler/WorkerPoolThread.cs#L104
https://github.com/dotnet/orleans/blob/8d6153f46763a3ec97db483142ce17b9d90dc9c9/src/Orleans/Statistics/SchedulerStatisticsGroup.cs#L80

The `lockable` is null, because the `Init` method was never called.

Thanks,
Martin

PS: Just for completeness, this is the error log:
```
Silo.exe Error: 0 : [2017-04-11 12:30:16.698 GMT     3	ERROR  	100105	OrleansSiloHost	135.128.217.36:11111]	!!!!!!!!!! ERROR starting Orleans silo name=MyPC Exception=
Exc level 0: System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.Enter(Object obj)
   at Orleans.Runtime.SchedulerStatisticsGroup.RegisterWorkingThread(String threadName)
   at Orleans.Runtime.Scheduler.WorkerPoolThread..ctor(WorkerPool gtp, OrleansTaskScheduler sched, Int32 threadNumber, Boolean system)
   at Orleans.Runtime.Scheduler.WorkerPool..ctor(OrleansTaskScheduler sched, Int32 maxActiveThreads, Boolean enableWorkerThreadInjection)
   at Orleans.Runtime.Scheduler.OrleansTaskScheduler..ctor(Int32 maxActiveThreads, TimeSpan delayWarningThreshold, TimeSpan activationSchedulingQuantum, TimeSpan turnWarningLengthThreshold, Boolean injectMoreWorkerThreads, LimitValue maxPendingItemsLimit)
   at Orleans.Runtime.Scheduler.OrleansTaskScheduler..ctor(NodeConfiguration config)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Orleans.Runtime.ServiceCollectionExtensions.<>c__0`2.<AddFromExisting>b__0_1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Orleans.Runtime.Silo.<>c.<.ctor>b__92_4(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Orleans.Runtime.Silo.<>c.<.ctor>b__92_2(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Orleans.Runtime.Silo..ctor(SiloInitializationParameters initializationParams)
   at Orleans.Runtime.Host.SiloHost.InitializeOrleansSilo()
```

**Comment by sergeybykov** [comment]
@zitmen Is this by chance the same as #2762? Can you reproduce this in `master`?

**Comment by zitmen** [comment]
@sergeybykov This is not happening anymore with `master`.
