### ISSUE TITLE
ConfigUtilities.ToParseableTimeSpan() and ConfigUtilities.ParseTimeSpan() doesn't handle TimeSpan.MaxValue

### ISSUE THREAD

**Issue by JacobSnyder** [dotnet/orleans#2933]
We are using the EventHub Stream Provider.  We wanted to effectively disable the built-in event retry policy that is provided by Orleans because we have our own custom retry policy implemented in our Grains that conflicts with the default retry policy.

To do this, we essentially constructed our `PersistentStreamProviderConfig` in the below manner.  By setting the max delivery time to `TimeSpan.MaxValue`, we effectively disable the default retry policy.
```C#
new PersistentStreamProviderConfig()
{
    // <snip>...
    MaxEventDeliveryTime = TimeSpan.MaxValue,
};
```

However, when the silo goes to start, it fails with the following error (slight omissions added between angle brackets):
```
Exception:System.AggregateException: One or more errors occurred. ---> 
Orleans.Providers.ProviderInitializationException: Exception initializing provider Name=<MyStreamProviderName> Type=[<MyStreamProviderName>, <MyStreamProviderType>] ---> 
System.OverflowException: TimeSpan overflowed because the duration is too long.
   at System.TimeSpan.Interval(Double value, Int32 scale)
   at Orleans.Runtime.Configuration.ConfigUtilities.ParseTimeSpan(String input, String errorMessage)
   at Orleans.Streams.PersistentStreamProviderConfig..ctor(IProviderConfiguration config)
   at Orleans.Providers.Streams.Common.PersistentStreamProvider`1.<Init>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Providers.ProviderLoader`1.<InitProviders>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at Orleans.Providers.ProviderLoader`1.<InitProviders>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Streams.StreamProviderManager.<LoadStreamProviders>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
```

I tracked this down to what looks like an issue with how `PersistentStreamProviderConfig` serializes itself in `WriteProperties` and then deserializes itself in the constructor.  `MaxEventDeliveryTime` is a `TimeSpan`.  It uses `ConfigUtilities.ToParseableTimeSpan()` to serialize this values and `ConfigUtilities.ParseTimeSpan()` to deserialize this value.  It appears that when `ConfigUtilities.ParseTimeSpan()` attempts to deserialize large values, it hits the `OverflowException` we're seeing.

As an aside, it appears that `TimeSpan.Parse("10675199.02:48:05.4764032")` is that highest value that can successfully be used (`TimeSpan.Parse("10675199.02:48:05.4764033")` fails with the `OverflowException`).

This is a pretty low-priority issue, but it was worth at least reporting the issue.  In the mean time, we've worked around this by setting `MaxEventDeliveryTime` to half of `TimeSpan.MaxValue` which should still be more than sufficient.

**Comment by ReubenBond** [comment]
Seems familiar... #4 :) If you can find the time, perhaps you could submit a PR

Thanks for reporting
