### ISSUE TITLE
Error=KeyValueTooLarge using AzureTableStorage and a generic grain interface

### ISSUE THREAD

**Issue by rikbosch** [dotnet/orleans#2939]
Using a generic grain interface and Azure Table Storage as provider results in a KeyValueTooLarge error response from Azure Table Storage.

log:
```
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo(Boolean catchExceptions)
Exc level 1: Orleans.Providers.ProviderInitializationException: Exception initializing provider Name=SqlProjectionsBootstrapProvider Type=[SqlProjectionsBootstrapProvider, Ao.Core.Grains.Projections.SqlProjectionsBootstrapProvider]
   at Orleans.Providers.ProviderLoader`1.<InitProviders>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.BootstrapProviderManager.PluginManager`1.<LoadAndInitPluginProviders>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.BootstrapProviderManager.<LoadAppBootstrapProviders>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
Exc level 2: Orleans.Runtime.OrleansException: Error from storage provider during WriteState for grain Type=Ao.Core.Grains.Projections.SqlProjectionGrain`1[[Ao.Core.Grains.Projections.SqlOrderListProjection, Ao.Core.Grains, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] Pk=*grn/78B50F77/0000000000000000000000000000000006075b0578b50f77+SqlOrderListProjection-0x5889E094 Id=GrainReference:*grn/78B50F77/00000000+SqlOrderListProjection<[Ao.Core.Grains.Projections.SqlOrderListProjection, Ao.Core.Grains, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]> Error=KeyValueTooLarge 
```
Grain interface:
```csharp
namespace Ao.Core.Grains.Projections
{
 public interface ISqlProjectionGrain<T> : IGrainWithStringKey
        where T: SqlProjection,new()
    {
        Task Connect();
        Task Disconnect();
    }
}
```

Looking at the exception I see the AssemblyQualifiedName of the generic parameter is used in the grainreference.

Is there any way to influence this behavior?

**Comment by veikkoeeva** [comment]
@rikbosch Not for the time being.

I see there is `Ao.Core.Grains.Projections.SqlProjectionGrain`, so I deduce you have a ADO.NET storage present. You could try ADO.NET storage as it doesn't have a length limitation (as long as it fits to `NVARCHAR(MAX)` in SQL Server or equivalent in others) and you would avoid See also https://github.com/dotnet/orleans/issues/1998, which might become a problem.

Depending on what `project` means there, you could perhaps have some synergy with `Storage` table when using application specific projections.

**Comment by sergeybykov** [comment]
@rikbosch You can take the Azure Table provider code, and tweak it to construct keys differently, and then use your version of the provider instead of the included one. Or switch to another provider, e.g. the Azure Blob one.

**Comment by DixonDs** [comment]
@sergeybykov but is there really need to use fully qualified names for generic type params? I looks like it is the same issue as https://github.com/dotnet/orleans/issues/2483

**Comment by sergeybykov** [comment]
>@sergeybykov but is there really need to use fully qualified names for generic type params? I looks like it is the same issue as #2483

In general, I think we need fully qualified type names to correctly resolve them and differentiate grains of different types. We could switch to a more compact representation of them, and that's what #2483. For example, we could consider hashing of type arguments into an `int`, but that may have implications for reverse lookup and troubleshooting, e.g. in case the type isn't there later for some reason. That's what we need to decide in #2483. Here I merely suggested workarounds in the meantime.
