### ISSUE TITLE
InvalidDataException: UniqueKey hex strings cannot contain more than one + separator.

### ISSUE THREAD

**Issue by AwsomeCode** [dotnet/orleans#2943]
Hi I am migrating from MemoryStorage to MongodbStorage for PubSubStore
Orleans Version 1.4.1,
For MongodbStorageProvider I am using.
https://github.com/dotnet/orleans/tree/master/Samples/StorageProviders/StorageProviders

Issue is happening after rebooting silo and calling IAsyncStream.OnNextAsync(),
With clean database and fresh silo everything is working fine.

Error log
**[2017-04-15 11:07:40.383 GMT     9      WARNING 101215  Scheduler.WorkItemGroup 10.0.0.5:41111] Task [Id=1538, Status=RanToCompletion] in WorkGroup [Activation: S10.0.0.5:41111:229950422*grn/716E8E94/9bfc8a90+SMSProvider_OnConnect@7083c396 #GrainType=Orleans.Streams.PubSubRendezvousGrain Placement=RandomPlacement State=Create] took elapsed time 0:00:00.2804139 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/2, ManagedThreadId=9, Executing Task Id=1538 Status=RanToCompletion for 00:00:00.2810116 on WorkItem=WorkItemGroup:Name=[Activation: S10.0.0.5:41111:229950422*grn/716E8E94/9bfc8a90+SMSProvider_OnConnect@7083c396 #GrainType=Orleans.Streams.PubSubRendezvousGrain Placement=RandomPlacement],WorkGroupStatus=Running Executing for 00:00:00.2900123. .>**

**UniqueKey hex strings cannot contain more than one + separator.**
Exception = System.IO.InvalidDataException: UniqueKey hex strings cannot contain more than one + separator.
   at Orleans.Runtime.UniqueKey.Parse(String input)
   at Orleans.Runtime.GrainReference..ctor(SerializationInfo info, StreamingContext context)
   at Void .ctor(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)(Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType, IDictionary`2& extensionData)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target)
   at Samples.StorageProviders.BaseJSONStorageProvider.ConvertFromStorageFormat(IGrainState grainState, String entityData)
   at Samples.StorageProviders.BaseJSONStorageProvider.<ReadStateAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<SetupActivationState>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Orleans.Runtime.Catalog.<InitActivation>d__59.MoveNext()

[2017-04-15 11:07:40.388 GMT    11      WARNING 100533  Catalog 10.0.0.5:41111] Failed to SetupActivationState for [Activation: S10.0.0.5:41111:229950422*grn/716E8E94/9bfc8a90+SMSProvider_OnConnect@7083c396 #GrainType=Orleans.Streams.PubSubRendezvousGrain Placement=RandomPlacement State=Invalid].
Exc level 0: System.IO.InvalidDataException: UniqueKey hex strings cannot contain more than one + separator.
   at Orleans.Runtime.UniqueKey.Parse(String input)
   at Orleans.Runtime.GrainReference..ctor(SerializationInfo info, StreamingContext context)
   at Void .ctor(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)(Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType, IDictionary`2& extensionData)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target)
   at Samples.StorageProviders.BaseJSONStorageProvider.ConvertFromStorageFormat(IGrainState grainState, String entityData)
   at Samples.StorageProviders.BaseJSONStorageProvider.<ReadStateAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<SetupActivationState>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Orleans.Runtime.Catalog.<InitActivation>d__59.MoveNext()
[2017-04-15 11:07:40.436 GMT    11      INFO    101033  Dispatcher      10.0.0.5:41111] Forwarding 1 requests to old address S10.0.0.5:41111:229950422*grn/716E8E94/9bfc8a90+SMSProvider_OnConnect@7083c396 after Failed SetupActivationState.

[2017-04-15 11:07:40.469 GMT    10      INFO    101031  Dispatcher      10.0.0.5:41111] Trying to forward after Failed SetupActivationState, ForwardCount = 0. Message NewPlacement Request S10.0.0.5:41111:229950422*grn/57D735F/00000000++919933221103@4ae77885->S10.0.0.5:41111:229950422*grn/716E8E94/9bfc8a90+SMSProvider_OnConnect@7083c396 #19: global::Orleans.Streams.IPubSubRendezvousGrain:RegisterProducer().

[2017-04-15 11:07:40.577 GMT     7      WARNING 101032  Dispatcher      10.0.0.5:41111] Forwarding failed: tried to forward message NewPlacement Request S10.0.0.5:41111:229950422*grn/57D735F/00000000++919933221103@4ae77885->S10.0.0.5:41111:229950422*grn/716E8E94/9bfc8a90+SMSProvider_OnConnect@c0c9bf9e #19[ForwardCount=2]: global::Orleans.Streams.IPubSubRendezvousGrain:RegisterProducer() for 2 times after Failed SetupActivationState to invalid activation. Rejecting now.

**Comment by ReubenBond** [comment]
@AwsomeCode could you share the storage provider code being used here?

**Comment by AwsomeCode** [comment]
Hi @ReubenBond  I am using MongodbStorageProvider below is the source. BaseJSONStorageProvider is base class of MongodbStorageProvider. https://github.com/dotnet/orleans/blob/master/Samples/StorageProviders/StorageProviders/MongoDBStorageProvider.cs

**Comment by ReubenBond** [comment]
@AwsomeCode I've opened a PR with an updated version of that sample in #2957 as well as a fix to allow multiple `+` symbols in UniqueKeys (and therefore grain keys) in #2956

**Comment by AwsomeCode** [comment]
Hi @ReubenBond Thanks for the fixes. Currently I switched to observers. But at that time I tried Azure Table for PubSubStore alos. And I got same exceptions after rebooting silo, but I don't have logs for it currently.

**Comment by ReubenBond** [comment]
Fixed in #2956
