### ISSUE TITLE
Tests fail for both SqlServer and Postgres

### ISSUE THREAD

**Issue by xclayl** [dotnet/orleans#3019]
SQL Server Error (for the init test in this case):

Test Name:	UnitTests.SqlStatisticsPublisherTests.SqlServerStatisticsPublisherTests.SqlStatisticsPublisher_SqlServer_Init
Test FullName:	UnitTests.SqlStatisticsPublisherTests.SqlServerStatisticsPublisherTests.SqlStatisticsPublisher_SqlServer_Init
Test Source:	 : line 0
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at UnitTests.SqlStatisticsPublisherTests.SqlStatisticsPublisherTestsBase..ctor(ConnectionStringFixture fixture, TestEnvironmentFixture environment)
   at UnitTests.SqlStatisticsPublisherTests.SqlServerStatisticsPublisherTests..ctor(ConnectionStringFixture fixture, TestEnvironmentFixture environment)
----- Inner Stack Trace -----
   at UnitTests.SqlStatisticsPublisherTests.StatisticsPublisherProviderRuntime.get_ServiceProvider()
   at Orleans.Providers.SqlServer.SqlStatisticsPublisher.<Init>d__16.MoveNext()
Result Message:	
System.AggregateException : One or more errors occurred.
---- System.NotImplementedException : The method or operation is not implemented.

The Postgres test error is very similar:

Test Name:	UnitTests.SqlStatisticsPublisherTests.PostgreSqlStatisticsPublisherTests.SqlStatisticsPublisher_PostgreSql_Init
Test FullName:	UnitTests.SqlStatisticsPublisherTests.PostgreSqlStatisticsPublisherTests.SqlStatisticsPublisher_PostgreSql_Init
Test Source:	 : line 0
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at UnitTests.SqlStatisticsPublisherTests.SqlStatisticsPublisherTestsBase..ctor(ConnectionStringFixture fixture, TestEnvironmentFixture environment)
   at UnitTests.SqlStatisticsPublisherTests.PostgreSqlStatisticsPublisherTests..ctor(ConnectionStringFixture fixture, TestEnvironmentFixture environment)
----- Inner Stack Trace -----
   at UnitTests.SqlStatisticsPublisherTests.StatisticsPublisherProviderRuntime.get_ServiceProvider()
   at Orleans.Providers.SqlServer.SqlStatisticsPublisher.<Init>d__16.MoveNext()
Result Message:	
System.AggregateException : One or more errors occurred.
---- System.NotImplementedException : The method or operation is not implemented.

It's true that the property StatisticsPublisherProviderRuntime.ServiceProvider throws a NotImplementedException. I'm not sure what the code should do in order to fix it.  Any thoughts here?

**Comment by veikkoeeva** [comment]
@xclayl I think this has never functioned in tests and it's one of the remeaining black holes we didn't yet plug with @shayhatsor and others. Mind you, the way statistics and telemetry are stored is in need of some heavy overhaul too. I am not sure there is a ticket for that yet. If there aren't maybe I finally, really should get around writing one. :(

**Comment by shayhatsor** [comment]
To correct @veikkoeeva, this test used to pass, including all other tests in the file.

**Comment by veikkoeeva** [comment]
Can this be closed? I remember the statistics publishing interfaces etc. were removed.
