### ISSUE TITLE
Question regarding exception I am getting infrequently about Grain Directory.

### ISSUE THREAD

**Issue by loneshark99** [dotnet/orleans#3027]
From time to time, we see this exception. Can some give some insight into what this exception means, since it does not happen all the time. Application works and then from time to time some calls fail. 

Just have some questions.

Does it mean that one of the machine in the Orleans cluster was down, in which case why would the traffic go to that machine? 

Any suggestion on how this can be fixed?

Thanks.

Exception
Message="Orleans.Runtime.OrleansException:  System.InvalidOperationException: **_# Grain directory is stopping_**
  at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription)
at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.<LookupAsync>d__99.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass0_0`1.<<QueueTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Placement.RandomPlacementDirector.<OnSelectActivation>d__1.MoveNext()
 End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Orleans.Runtime.Placement.PlacementDirectorsManager.<SelectOrAddActivation>d__11.MoveNext()

**Comment by centur** [comment]
From our experience: such exception happens when cluster is being stopped. E.g. production and staging cloud services are running in parallel. Then Staging is being explicitly stopped. 
Because we are running some scheduler-driven jobs - there is a chance that such job kicks in right before silo receives `Stop()` call, so your message is already in a mail box of some grain, awaiting to be processed but suddenly all grains receive a shutdown request and are being deactivated. Thus all pending tasks are being aborted with exception and scheduler logs such exception like above.

This is just a theory, not a 100% knowledge what is happening there. We tend to ignore such messages (I hope it's a right thing to do...)

**Comment by veikkoeeva** [comment]
I wonder if the cases @centur mentioned could be singled out and additiona information provided for the (likely) cause?

**Comment by sergeybykov** [comment]
@loneshark99 Looks like these errors come from the inherent races between one silo shutting down while another silo or silos still sending messages to it (in this case to the grain directory partition). It should auto-recover very quickly.

**Comment by loneshark99** [comment]
Thanks for the info.
