### ISSUE TITLE
EventHub provider and latest version of Microsoft Azure Service Bus  v4.1.1 (WindowsAzure.ServiceBus nuget)

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#3062]
Just want to flag this issue for the future release or anyone who stepped on the same problem as we did and make error text search-able.

`Microsoft.Orleans.OrleansServiceBus` v1.4.1 is not compartible with `WindowsAzure.ServiceBus` major version upgrade v4. (v.4.1.1 as per today)
By definition `Microsoft.Orleans.OrleansServiceBus` 1.4.1 depends on `WindowsAzure.ServiceBus`  v3.3.2.

It's safe to upgrade dependance to the latest v3 ( v3.4.6 as per today), but if you have to upgrade `WindowsAzure.ServiceBus`  to a major v4 version - it breaks EH Stream provider and you'll see this error in your logs:

```
WaWorkerHost.exe Error: 0 :
[2017-05-29 04:39:01.833 GMT    39    ERROR      103303    PullingAgentSystemTarget/FF/c8a2d58b-BullclipEventHub    127.0.0.1:11111]    !!!!!!!!!! QueueAdapterReceiver bullclipeventhub-0-0x00000000 failed to Initialize.    
Exc level 0: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.ServiceBus.Messaging.EventHubReceiver> Microsoft.ServiceBus.Messaging.EventHubConsumerGroup.CreateReceiverAsync(System.String, System.String, Boolean)'.
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.<CreateReceiver>d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.CreateReceiver(EventHubPartitionSettings partitionSettings, String offset, Logger logger)
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.<Initialize>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OrleansTaskExtentions.<SafeExecute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OrleansTaskExtentions.<LogException>d__0.MoveNext() (View on Seq)
```

Simple fix for this is to downgrade back to major v3 version.

**Comment by DixonDs** [comment]
Related to https://github.com/dotnet/orleans/issues/2910

**Comment by xiazen** [comment]
Thanks for the heads up!
