### ISSUE TITLE
NullReferenceException roundtrip GrainReference with jsonserializer

### ISSUE THREAD

**Issue by rikbosch** [dotnet/orleans#3063]
Hi,

We get the following exception when activating a previously explicitly subscribed grain from a bootstrapprovider.

The grain has a generic type definition.. which I think is the problem.

Exception / stacktrace
```csharp
Forwarding failed: tried to forward message NewPlacement Request S127.0.0.1:30065:233753838*grn/DEB21CF7/00000000+SqlCustomerListProjection@546b769f->S127.0.0.1:30065:233753838*grn/716E8E94/d5a85bb8+DomainEvents_$all@ac9b33b3 #12[ForwardCount=2]: global::Orleans.Streams.IPubSubRendezvousGrain:GetAllSubscriptions() for 2 times after Failed SetupActivationState to invalid activation. Rejecting now. System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Serialization.GrainReferenceConverter.CreateCaster(Type grainReferenceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orleans.Serialization.GrainReferenceConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Orleans.Storage.AdoNetStorageProvider.<>c__DisplayClass42_0.<<ReadStateAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.SqlUtils.RelationalStorage.<SelectAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.SqlUtils.RelationalStorage.<ExecuteReaderAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.SqlUtils.RelationalStorage.<ExecuteAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.SqlUtils.RelationalStorage.ReadAsync[TResult](String query, Action`1 parameterProvider, Func`4 selector, CancellationToken cancellationToken, CommandBehavior commandBehavior)
   at Orleans.Storage.AdoNetStorageProvider.<ReadStateAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<SetupActivationState>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<InitActivation>d__65.MoveNext()
```

using AzureQueueStreamProviderV2 with the following configuration:
```csharp
    clusterConfiguration.Globals.RegisterStreamProvider<AzureQueueStreamProviderV2>(StreamProviders.DomainEventStreamProvider,
                new Dictionary<string, string>
                {
                    { "PubSubType", "ExplicitGrainBasedAndImplicit" },
                    { "NumQueues", "4" },
                    { "GetQueueMessagesTimerPeriod", "250ms" },
                    { "DataConnectionString", azureConnectionString },
                    { "DeploymentId","test" }
                });
```

The code in OnActivateAsync of the generic grain:
```
       public override async Task OnActivateAsync()
        {
            _projection = new T();
            _projector = new ConnectedProjector<SqlDatabase>(Resolve.WhenEqualToHandlerMessageType(_projection.Handlers));
       
            //resume any active subscriptions
            var handles = await GetStreamProvider(StreamProviders.DomainEventStreamProvider)
                .GetStream<object>(StreamIds.DomainEventStreamId, StreamNamespaces.GlobalDomainEvents)
                .GetAllSubscriptionHandles();

            if (handles.Any())
            {
                _isConnected = true;
                await Task.WhenAll(handles.Select(x => x.ResumeAsync(this)));
            }
           
            await base.OnActivateAsync();
        }

```
edit:

and the json state for the pubsubrendevousgrain
```json
{
	"$id": "1",
	"$type": "Orleans.Streams.PubSubGrainState, OrleansRuntime",
	"Producers": {
		"$type": "System.Collections.Generic.HashSet`1[[Orleans.Streams.PubSubPublisherState, Orleans]], System.Core",
		"$values": [{
			"$id": "2",
			"$type": "Orleans.Streams.PubSubPublisherState, Orleans",
			"Stream": {
				"$id": "3",
				"$type": "Orleans.Streams.StreamId, Orleans",
				"Guid": "a8d99256-d3eb-4055-b85b-a8d558423e3f",
				"ProviderName": "DomainEvents",
				"Namespace": "$all"
			},
			"producerReference": "GrainReference=464c696cb98571a655c48af2fa861fb401000000000000ff SystemTarget=127.0.0.1:30058@233749568"
		}]
	},
	"Consumers": {
		"$type": "System.Collections.Generic.HashSet`1[[Orleans.Streams.PubSubSubscriptionState, Orleans]], System.Core",
		"$values": [{
			"$id": "4",
			"$type": "Orleans.Streams.PubSubSubscriptionState, Orleans",
			"SubscriptionId": {
				"$id": "5",
				"$type": "Orleans.Runtime.GuidId, Orleans",
				"Guid": "2f1df279-c17b-494d-8f1c-29e4c8b7de45"
			},
			"Stream": {
				"$ref": "3"
			},
			"consumerReference": "GrainReference=0000000000000000000000000000000006f320efdeb21cf7+SqlOrderListProjection GenericArguments=[Ao.Core.Grains.Orderlist.SqlOrderListProjection, Ao.Core.Grains, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]"
		},
		{
			"$id": "6",
			"$type": "Orleans.Streams.PubSubSubscriptionState, Orleans",
			"SubscriptionId": {
				"$id": "7",
				"$type": "Orleans.Runtime.GuidId, Orleans",
				"Guid": "842305d5-43dd-4344-8af0-31c861bad126"
			},
			"Stream": {
				"$ref": "3"
			},
			"consumerReference": "GrainReference=0000000000000000000000000000000006560f11deb21cf7+SqlCustomerListProjection GenericArguments=[Ao.Core.Grains.Customer.SqlCustomerListProjection, Ao.Core.Grains, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]"
		}]
	}
}```

**Comment by rikbosch** [comment]
@ReubenBond I've investigated this further and it is introduced in 1.5.1-beta.

Looking at the ```GrainReferenceConverter```, there is this function:

```csharp
    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            var key = serializer.Deserialize<string>(reader);
            if (string.IsNullOrWhiteSpace(key)) return null;

            var result = GrainReference.FromKeyString(key, null);  // !!! <<  Shouldn't  IGrainReferenceConverter be used here?
             this.grainFactory.BindGrainReference(result);
            return Casters.GetOrAdd(objectType, CreateCasterDelegate)(result);
        }

```

**Comment by rikbosch** [comment]
update: this test reproduces the problem. It has nothing to do with generics.
```csharp
 public class GrainReferenceJsonStorageTests : HostedTestClusterEnsureDefaultStarted
    {
        public GrainReferenceJsonStorageTests(ITestOutputHelper output, DefaultClusterFixture fixture) : base(fixture)
        {
           
        }

        [Fact]
        public void CanRoundTripGrainReference()
        {
            var serializer = new OrleansStorageDefaultJsonSerializer(
                OrleansJsonSerializer.GetDefaultSerializerSettings(HostedCluster.SerializationManager,
                    HostedCluster.GrainFactory), "UseJsonFormat");
            var deserializer = new OrleansStorageDefaultJsonDeserializer(
                OrleansJsonSerializer.GetDefaultSerializerSettings(HostedCluster.SerializationManager,
                    HostedCluster.GrainFactory), "UseJsonFormat");


            var grain = HostedCluster.GrainFactory.GetGrain<ISimpleGrain>(GetRandomGrainId());
            var input = new GenericGrainReferenceHolder()
            {
                Reference = grain as GrainReference //this is how its done in PubSubSubscriptionState constructor
            };
        
            var json = serializer.Serialize(input);

            var output = (GenericGrainReferenceHolder)deserializer.Deserialize(json, typeof(GenericGrainReferenceHolder));

            Assert.Equal(input.Reference,output.Reference);
        }

        [Serializable]
        public class GenericGrainReferenceHolder
        {
            [JsonProperty]
            public GrainReference Reference { get; set; }
        }
    }
```

**Comment by ReubenBond** [comment]
That's does seem like a bug, thanks for tracking it down, @rikbosch.

From what I can tell initially, the concrete type information of the GrainReference is not being serialized, and this is what's causing the issue on deserialization. If we were to serialize the ref as a json object instead of as a string, maybe JSON.NET would be able to insert concrete type information into the object.

**Comment by rikbosch** [comment]
The offending line is

```
   private static GrainFactory.GrainReferenceCaster CreateCaster(Type grainReferenceType)
        {
            var interfaceType = grainReferenceType.GetTypeInfo().GetCustomAttribute<GrainReferenceAttribute>().TargetType;
            return GrainCasterFactory.CreateGrainReferenceCaster(interfaceType, grainReferenceType);
        }
```

The type does not have a GrainReferenceAttribute. Maybe because it is explicitly downcasted to a GrainReference?

**Comment by veikkoeeva** [comment]
I'm not into that much details, but would this occur in every storage provider or just the ADO.NET one?

**Comment by ReubenBond** [comment]
@rikace it's because the type is `GrainReference` and not the concrete, runtime implementation of the grain reference. I'm still looking into the fix. Fixing it on full .NET is simple, since we can just remove that serializer and use the `ISerializable` implementation in `GrainReference`. On .NET Standard (for 2.0 builds), we cannot rely on `ISerializable`, however, since `StreamingContext` is unusable (has no `Context` property for us to flow the runtime through). So I'm looking into the best way to fix this for both platforms.
