### ISSUE TITLE
JSON serialization fails for Dictionary<GrainReference, DateTime>

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#3133]
See details below:
```
Newtonsoft.Json.JsonSerializationException occurred
  HResult=0x80131500
  Message=Could not convert string 'GrainReference:*grn/901FCCD4/69f6c279' to dictionary key type 'Orleans.Runtime.GrainReference'. Create a TypeConverter to convert from the string to the key type object. Path 'GrainReference:*grn/901FCCD4/69f6c279', line 1, position 41.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at DefaultCluster.Tests.General.GrainReferenceTest.NewtonsoftJsonSerialiseRoundtrip(Object obj) in C:\OSS\orleans\test\DefaultCluster.Tests\GrainReferenceTest.cs:line 164
   at DefaultCluster.Tests.General.GrainReferenceTest.TestGrainReferenceSerialization(Int32 id, Boolean resolveBeforeSerialize, Boolean useJson) in C:\OSS\orleans\test\DefaultCluster.Tests\GrainReferenceTest.cs:line 113
   at DefaultCluster.Tests.General.GrainReferenceTest.GrainReference_Json_Serialization() in C:\OSS\orleans\test\DefaultCluster.Tests\GrainReferenceTest.cs:line 98

Inner Exception 1:
JsonSerializationException: Error converting value "GrainReference:*grn/901FCCD4/69f6c279" to type 'Orleans.Runtime.GrainReference'. Path 'GrainReference:*grn/901FCCD4/69f6c279', line 1, position 41.

Inner Exception 2:
ArgumentException: Could not cast or convert from System.String to Orleans.Runtime.GrainReference.
```

I can post the exact failing test later, but it is pretty much just serialization and deserialization of `Dictionary<GrainReference, DateTime>`. The version is 1.4.2.

**Comment by ReubenBond** [comment]
@DixonDs I'm a little confused by the stack trace. Are you seeing this failure while running the `GrainReference_Json_Serialization` test locally, unmodified?

**Comment by DixonDs** [comment]
@ReubenBond sorry for confusion, I did modify that test just to reproduce the issue quickly on Orleans codebase (and so ensuring that it is not specific to my Orleans setup).

Here is a failing test for the issue (put it into `DefaultCluster.Tests.General.GrainReferenceTest`):

```
[Fact, TestCategory("Serialization"), TestCategory("JSON")]
public async Task GrainReference_Json_Serialization_Dictionary()
{
    var grain = HostedCluster.GrainFactory.GetGrain<ISimpleGrain>(GetRandomGrainId());
    await grain.SetA(56820);

    var inputReference = (GrainReference)grain;
    var input = new Dictionary<GrainReference, DateTime> { { inputReference, DateTime.UtcNow } };

    var output = NewtonsoftJsonSerializeRoundtrip(input);

    var outputReference = output.Keys.First();
    Assert.Equal(inputReference, outputReference);
    Assert.Equal(56820, await ((ISimpleGrain)outputReference).GetA());
}
```

**Comment by ReubenBond** [comment]
I'm not sure how to support this kind of thing, @DixonDs - JSON dictionaries can only have string keys, so whatever goes into the dictionary must be convertible to a string, but GrainReferences cannot be converted with full fidelity since they need to have a specific type serialized alongside them in order to be recoverable.
