### ISSUE TITLE
Orleans 1.5.0 incompatible with Microsoft.CodeAnalysis 2.3

### ISSUE THREAD

**Issue by kogir** [dotnet/orleans#3233]
When I upgrade Microsoft.CodeAnalysis from 2.2 to 2.3, I get the following error initializing a `GrainClient`:

```
Must include private members unless emitting a ref assembly.
Parameter name: IncludePrivateMembers

   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, CancellationToken cancellationToken)
   at Orleans.CodeGenerator.CodeGeneratorCommon.CompileAssembly(GeneratedSyntax generatedSyntax, String assemblyName, Boolean emitDebugSymbols)
   at Orleans.CodeGenerator.RoslynCodeGenerator.CompileAndLoad(GeneratedSyntax generatedSyntax, Boolean emitDebugSymbols)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssemblies(Assembly[] inputs)
   at Orleans.Runtime.AssemblyProcessor.Initialize()
   at Orleans.OutsideRuntimeClient.ConsumeServices(IServiceProvider services)
   at Orleans.ClientBuilder.Build()
   at RealArtists.ShipHub.Common.OrleansAzureClient.<CreateOrleansClient>d__19.MoveNext() in C:\Code\RealArtists\shiphub-server\RealArtists.ShipHub.Common\OrleansAzureClient.cs:line 81
```

Rolling back to Microsoft.CodeAnalysis 2.2 gets everything working again. Not a critical issue for us.

I build the client like so:

```csharp
Configuration = new ClientConfiguration {
  GatewayProvider = ClientConfiguration.GatewayProviderType.AzureTable,
  DeploymentId = DeploymentId,
  DataConnectionString = DataConnectionString,
  TraceFilePattern = "false",
  TraceToConsole = false,
  ResponseTimeout = ResponseTimeout,
  FallbackSerializationProvider = typeof(ILBasedSerializer).GetTypeInfo(),
};
```

```csharp
var client = new ClientBuilder()
  .UseConfiguration(Configuration)
  .AddClusterConnectionLostHandler((sender, e) => Log.Info("Orleans cluster connection lost."))
  .Build();
await client.Connect();
```

**Comment by attilah** [comment]
This is exactly the same issue, linking it for future tracking: https://github.com/dotnet/roslyn/issues/20873

**Comment by kogir** [comment]
Thanks! That was a super fast turnaround. Looking forward to this in 1.5.1.

**Comment by jcouv** [comment]
Sorry about that. 
We're tracking the Roslyn compat break with issue https://github.com/dotnet/roslyn/issues/20873. Most likely we are going to have to stick to that change and document it. The default value was wrong and it could not be left that way once functionality was hooked up to it.
