### ISSUE TITLE
"Index out of Range" exception thrown while adding a message to a queue.

### ISSUE THREAD

**Issue by luciobemquerer** [dotnet/orleans#3255]
I had this exception thrown when I called `IAsyncStream.OnNextAsync()` to put a new message on the stream. 

This happened during a (very) long running procedure where all the communication is done using messages over streams backed by Azure Queues. So, this same call has succeeded at least 10K times before during the same long running procedure, and suddenly threw this exception. After that, I started the procedure again and it run successfully for another few thousand iterations. 

It seems to be a transient service failure, that could probably be addressed with a retrial logic. I wonder if this retrial logic should be implemented in the `AzureQueueDataManager` itself, or in the code calling `IAsyncStream.OnNextAsync()`.

Looking for ideas on how to handle this. Is not a very critical issue, since it doesn't happen too often. The problem for us, currently, is that this error interrupts (and fails) a procedure that was running for a few hours already.

```
System.AggregateException: Error doing AddQueueMessage for Azure storage queue depl-e27de72580214e40ae9d64586180023e-wfservicetasks-0 
Exception = Microsoft.WindowsAzure.Storage.StorageException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs:line 77
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndFastCopyTo[T](IAsyncResult fastCopyToResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 185
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AzureUtils.AzureQueueDataManager.<AddQueueMessage>d__17.MoveNext()
Request Information
RequestID:
RequestDate:
StatusMessage:
 ---> Microsoft.WindowsAzure.Storage.StorageException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs:line 77
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndFastCopyTo[T](IAsyncResult fastCopyToResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 185
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AzureUtils.AzureQueueDataManager.<AddQueueMessage>d__17.MoveNext()
   --- End of inner exception stack trace ---
   at Orleans.AzureUtils.AzureQueueDataManager.ReportErrorAndRethrow(Exception exc, String operation, ErrorCode errorCode)
   at Orleans.AzureUtils.AzureQueueDataManager.<AddQueueMessage>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Providers.Streams.AzureQueue.AzureQueueAdapter`1.<QueueMessageBatchAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DBCloud.ActorCollection.Workflows.Grains.WorkflowRunnerGrain.<startServiceTask>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DBCloud.Core.Workflows.Steps.WorkflowServiceTaskStep`1.<Start>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DBCloud.Core.Workflows.Workflow.<startNextStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DBCloud.Core.Workflows.Workflow.<Start>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DBCloud.Core.Workflows.Steps.WorkflowParallelStep`1.<startPendingItemWorkflows>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DBCloud.Core.Workflows.Steps.WorkflowParallelStep`1.<onParallelItemCompleted>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DBCloud.Core.Workflows.Workflow.<startNextStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DBCloud.Core.Workflows.Workflow.<onWorkflowStepCompleted>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DBCloud.Core.Workflows.Steps.WorkflowServiceTaskStep`1.<OnServiceTaskCompleted>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DBCloud.ActorCollection.Workflows.Grains.WorkflowRunnerGrain.<OnServiceTaskCompleted>d__11.MoveNext()
---> (Inner Exception #0) Microsoft.WindowsAzure.Storage.StorageException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs:line 77
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndFastCopyTo[T](IAsyncResult fastCopyToResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 185
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AzureUtils.AzureQueueDataManager.<AddQueueMessage>d__17.MoveNext()
Request Information
RequestID:
RequestDate:
StatusMessage:
<---

```

**Comment by attilah** [comment]
This error is not related to Orleans as you also see it. It seems to be a regression in Azure Storage based on this issue: https://github.com/Azure/azure-storage-net/issues/471 

Could you please confirm the version of Azure Storage you are using?

To answer your question I think that such retry logic should be handled at application level, because it can be done a lot of ways and there are libraries out there already which can make it even easier.

**Comment by sergeybykov** [comment]
If the exception is thrown while trying to publish a message (that's how I understood), then it's the application's responsibility to decide whether or not to retry. There are major downsides to having the framework retry under the covers. That's why we don't do that.

**Comment by centur** [comment]
Well. this exception belongs to Azure Storage library, but we are operating with Virtual Streams - this is Orleans abstraction. At that point we don't know which implementation is configured for this particular stream. Also stream implementation can be changed and this means that error handling that was built in application is irrelevant. 
Technically, Streams abstraction provides an interface and special callback - OnError which can be invoked correctly for corresponding implementations. Otherwise it's hard to reason about the code as we have to cater for any stream implementation bugs in our code. One day we can switch stream implementation to EventHub or SMS - and this means that all application-level error handling that is already in for a specific stream stream implementation will be some kind of snake oil.

I understand that every abstraction in the library leaks to a certain point (e.g. AQ and SMS behave differently) but at least those abstractions must shield users from underlying library errors, aren't they ?

**Comment by DixonDs** [comment]
I think it could be done similarly to storage providers when they wrap specific exceptions into some custom exception common for all implementation. Then the application logic can reason about this custom exception without compromising the abstraction.

**Comment by sergeybykov** [comment]
>But still from a general architecture perspective - I don't understand why you insist that we must handle this particular exception type in our app: this exception belongs to Azure Storage library, but we are operating with Virtual Streams - this is pure Orleans abstraction. At that point we don't know which implementation is configured for this particular stream. Also stream implementation can be changed and this means that error handling that was built in application is irrelevant.

I look at it this way - there may be many reasons for a publishing call to fail, some may be transient, some permanent. The framework cannot be smart enough to analyze all possible situation and retry where it makes sense. Hence, it simply bubbles the error up to the caller to decide.

Note that `OnError` has a different meaning - it is for signaling a 'logical' error with a virtual stream between publisher and subscribers and in some cases between the framework and subscribers. In the above failure case, the framework cannot even deliver an `OnError` to subscribers because it would require adding a message to the queue anyway.

I see a potential value in defining two classes of wrapper exceptions: for transient and permanent errors. That would require stream providers to wrap any exception into one of those. Would be a 'soft-breaking' change though.
