### ISSUE TITLE
Type load exception on OrleansCodeGen class that we know exists in assemblies in AppDomain

### ISSUE THREAD

**Issue by b4barnett** [dotnet/orleans#3266]
Hi, we're having some problems loading a orleans gen'd type after adding a new project

We're using Orleans 1.41

Unit test project depends on assemblies **A** and **B**, **B** is a newly introduced feature, both **A** and **B** contain grains. 
**A** and **B** both depend on a common project **C** to provide functionality common to both.

Since we've created unit tests for project **B**, unrelated tests in Project **A** are now failing due to the TypeLoadException for a few CodeGen object, an example of which is in the stacktrace below

If we remove any inheritance or interface realization in the Unit test project that depend on **B** (so that the objects in **B** do not go through the Orleans code generation) then we do not encounter this error

The app domain at the point of failure contains multiple "OrleansCodeGen" assemblies, one of which does contain the type it is looking for, the only difference being the extra generated classes from assembly **B**.

Apologise we don't have any code examples to show but this spans a number of classes.

Any ideas as to why it cannot find the type that does actually exist?

`System.AggregateException : One or more errors occurred.
  ----> System.AggregateException : One or more errors occurred.
  ----> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.TypeLoadException : Could not load type 'PromotionPlanning.Domain.OrleansCodeGenPromotionActorReference' from assembly 'OrleansCodeGen, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Threading.Tasks.Task'1.GetResultCore(Boolean waitCompletionNotification)
   at KSS.PS3.Tests.DataAccess.CandidatePromotionsSteps.GivenIApproveRejectPromotionsInPlan(String approvePromotionIdsStr, String rejectPromotionIdsStr, Nullable'1 planId) in C:\dev\Application\Testing\Tests\DataAccess\CandidatePromotionsSteps.cs:line 241
   at KSS.PS3.Tests.DataAccess.CandidatePromotionsSteps.GivenIApprovePromotionX(Int32 promotionId) in C:\dev\Application\Testing\Tests\DataAccess\CandidatePromotionsSteps.cs:line 260
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at KSS.PS3.Tests.PromotionsForecasting.Tests.PromotionApprovalStatusNotificationFeature.ScenarioCleanup()
   at KSS.PS3.Tests.PromotionsForecasting.Tests.PromotionApprovalStatusNotificationFeature._01_PromotionApproval() in C:\dev\Application\Testing\Tests\PromotionsForecasting\Tests\DHD-29684 Promotion Approval Status Notification.feature:line 32
--AggregateException`

`Server stack trace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Utilities.GrainThreadMarshallingProxy.Intercept(IInvocation invocation) in C:\dev\Application\Common\Utilities\GrainThreadMarshallingProxy.cs:line 54
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IForecastSubscriptionContextProxy.BeginSubscription(String expectedCorrelationId, IForecastableActor planActor)
   at PromotionPlanning.Domain.Approvals.ApprovalsActor.<BeginPromotionApproval>d__32.MoveNext() in C:\dev\Application\Services\PromotionPlanning\Domain\Approvals\ApprovalsActor.cs:line 598
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
   at PromotionPlanning.Domain.Approvals.ApprovalsActor.<BeginPlanOrPromotionApproval>d__30.MoveNext() in C:\dev\Application\Services\PromotionPlanning\Domain\Approvals\ApprovalsActor.cs:line 574
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
   at PromotionPlanning.Domain.Approvals.ApprovalsActor.<Approve>d__22.MoveNext() in C:\dev\Application\Services\PromotionPlanning\Domain\Approvals\ApprovalsActor.cs:line 276
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.PublicOrleansTaskExtensions.<BoxAwait>d__8'1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.InsideRuntimeClient.<Invoke>d__59.MoveNext()`

`Exception rethrown at [0]: 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.PublicOrleansTaskExtensions.<BoxAwait>d__8'1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.InsideRuntimeClient.<Invoke>d__59.MoveNext()
`
`Exception rethrown at [1]: 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.PublicOrleansTaskExtensions.<BoxAwait>d__8'1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.InsideRuntimeClient.<Invoke>d__59.MoveNext()
--TargetInvocationException
   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at Orleans.Serialization.BinaryFormatterSerializer.DeepCopy(Object source, ICopyContext context)
   at Orleans.Serialization.SerializationManager.FallbackSerializationDeepCopy(Object obj, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopy(Object original)
   at Orleans.Runtime.GrainReference.InvokeMethodAsync[T](Int32 methodId, Object[] arguments, InvokeMethodOptions options, SiloAddress silo)
   at PromotionPlanning.Domain.Approvals.OrleansCodeGenForecastSubscriptionContextReference.BeginSubscription(String expectedCorrelationId, IForecastableActor planActor)
   at Castle.Proxies.Invocations.IForecastSubscriptionContext_BeginSubscription.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Utilities.GrainThreadMarshallingProxy.<>c__DisplayClass8_0.<Intercept>b__0() in C:\dev\Application\Common\Utilities\GrainThreadMarshallingProxy.cs:line 49
   at System.Threading.Tasks.Task.Execute()
--TypeLoadException
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Castle.DynamicProxy.Serialization.ProxyObjectReference.DeserializeTypeFromString(String key)
   at Castle.DynamicProxy.Serialization.ProxyObjectReference.RecreateInterfaceProxy(String generatorType)
   at Castle.DynamicProxy.Serialization.ProxyObjectReference..ctor(SerializationInfo info, StreamingContext context)`

**Comment by ReubenBond** [comment]
Are you saying that unit tests in project B are passing, but unit tests in project A are failing?
The first thing I would do is upgrade to [1.4.2](https://github.com/dotnet/orleans/releases/tag/v1.4.2), which fixed issues in that area.
Failing that, what happens if you install the [build-time code generation package](https://preview.nuget.org/packages/Microsoft.Orleans.OrleansCodeGenerator.Build/) into A & B?

**Comment by b4barnett** [comment]
hanks for getting back to me Reuben 

Not all of A's test fail, but this is quite a mature project with many tests, all of B's test pass successfully but it is a very new project with only a few tests (that do all pass).

Moving to 1.4.2 did not resolve the issue, and I had compilation issues when trying to move everything to CodeGen.Build ( I can give it another go if it would help ).

Neither project A or B had any reference to the CodeGeneration assembly, only the unit test project had a reference (our belief was that because the unit test project inherited/realized some classes/interfaces then orleans would code generate that project), I don't know if not including the CodeGeneration assembly was by design or just not considered but adding the CodeGeneration assembly did not help.

I've noticed that multiple OrleansCodeGen assemblies are being generated and I believe that there is a problem with those and the System.Type.GetType method that the Castle interceptor is using.

Shortened Example

Assembly - Defined types

OrleansCodeGen - PromotionPlanning.Interfaces.OrleansCodeGenEventMonitorReminderReference
				 PromotionPlanning.Interfaces.OrleansCodeGenEventMonitorReminderMethodInvoker
		 
OrleansCodeGen - PromotionPlanning.Domain.OrleansCodeGenPromotionActorReference


These are reprensentative of what appears in the AppDomain.

so when I try

`System.Type.GetType( "dunnhumby.PriceStrat.PromotionPlanning.Interfaces.OrleansCodeGenEventMonitorReminderReference, OrleansCodeGen, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null", true, true ); //Finds the type successfully
System.Type.GetType( "dunnhumby.PriceStrat.PromotionPlanning.Domain.OrleansCodeGenPromotionActorReference, OrleansCodeGen, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null", true, true ); //will throw because it doesn't exist in the first OrleansCodeGen assembly`

This doesn't really explain why it will then work for the intercepter when it comes to it, or why it will stop working after code generation for project B is performed. 

after the project B is added the defined types look more like this, with the new code being the first generated (and why the code above will both throw an exception)

Assembly - Defined types

OrleansCodeGen - PromotionPlanning.Interfaces.OrleansCodeGenEventMonitorReminderReference
				 PromotionPlanning.Interfaces.OrleansCodeGenEventMonitorReminderMethodInvoker
				 
OrleansCodeGen - dunnhumby.PriceStrat.PricingPlanning.Interfaces.CommandModel.OrleansCodeGenPricingPlanningServiceCommandsReference
				 
OrleansCodeGen - PromotionPlanning.Domain.OrleansCodeGenPromotionActorReference

**Comment by b4barnett** [comment]
I retried using the `Microsoft.Orleans.OrleansCodeGenerator.Build` and the tests are all now passing. I do feel that the runtime and compile time compliation should have the same behaviour

**Comment by b4barnett** [comment]
Hi,
We removed the interceptor so now it's just a grain in Project A making a call to another grain in project B and are still having the TypeLoad issue

**Comment by b4barnett** [comment]
@ReubenBond would it be possible to have the Orleans code generation check if it has already generated an assembly in the past an then append a counter or have the code gen name the assembly with a unique identifier each time, both would allow us to load types no matter how many assemblies have been code gen'd

**Comment by ReubenBond** [comment]
@b4barnett unfortunately, because the assembly name is used in type identifiers, it must be consistent between different silos - that's why they all use the same assembly name.

I believe the issue you're seeing when using runtime codegen is that the assemblies are not loaded (and therefore not processed) by the time the silo is receiving a call containing the generated type. You can fix this by using the `[assembly: KnownAssemby(typeof(MyGrainRefInSomeAssembly))]` attribute, which will cause the assembly to be loaded and processed during startup

**Comment by b4barnett** [comment]
Hi @ReubenBond the issue still occurs, I checked the assemblies loaded in the AppDomain and there is still multiple code gen assemblies, just so I'm clear that I'm using it correctly.

Test project - 
Has the Orleans runtime code generation package
Hints using the KnownAssembly to all the assemblies that have grains or are called by grains (so that the serializers are generated too)

Grain projects - 
Do not have any code generation packages attached

**Comment by ReubenBond** [comment]
Multiple codegen assemblies is the correct behavior. Is there a reason to avoid build-time codegen?
If that's an issue, make sure that all assemblies are loaded within all AppDomains before starting the silos & clients.

**Comment by b4barnett** [comment]
OK thanks @ReubenBond, there was a preference to use the runtime but nobody can give me a reason so we're just going to use the build time.
