### ISSUE TITLE
MSBuild RemoteDebugger or IntelliTrace makes orleans.dll break our worker role

### ISSUE THREAD

**Issue by JoshStardock** [dotnet/orleans#327]
When we try to build our project using msbuild and using /p:configuration=Debug orleans.dll causes our worker role in Azure not to start.

Is there a work around or fix for this?

**Comment by sergeybykov** [comment]
This shouldn't be happening. Can you provide more details about why the role fails to start?

**Comment by gabikliot** [comment]
Also, does exactly the same setup when compiled with Release starts? Did you actually try to compile yourself in Release and deploy?

**Comment by JoshStardock** [comment]
The same exact setup works when compiled with release starts, although the properties we set with msbuild are different.  Here are the full parameters we use on msbuild when the role will NOT startup
/p:Configuration=Debug`
/p:DeployOnBuild=True `
/p:DeployTarget=Package `
/p:OutputPath=C:\Output`
/p:DeployIisAppPath=$ApplicationName `
/p:TargetProfile=Cloud `
/p:publishDir=C:\Dir `
/p:EnableIntelliTrace=True`
/p:IntelliTraceConnectionString="""BaseEndpoint=core.windows.net;Protocol=https;AccountName=$storageAccountName;AccountKey=$StorageKey""" `
/p:IntelliTraceCollectionCabPath="C:\IntelliTrace\IntelliTraceCollection.cab" `
/p:DefaultCloudToolsPath="C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Windows Azure Tools\2.5\\" `
/p:CloudToolsInstallPath="C:\Program Files (x86)\Microsoft Azure Tools\Visual Studio 12.0\2.5\\" `
/p:AzureDeployEnvironment=Cloud `
/p:EnableRemoteDebugger=true `
/p:VSX64RemoteDebuggerPath="C:\Program Files\Microsoft Visual Studio 12.0\Common7\IDE\Remote Debugger\x64\\" `
/p:RemoteDebuggerConnectorCertificateThumbprint="$thumbprint" `
/p:RemoteDebuggerConnectorVersion="2.5" `
/t:publish `
/p:VisualStudioVersion=12.0 `
/verbosity:$verbosity


Here are the parameters we use when the orleans worker role DOES startup:
/p:Configuration=Release `
/p:DeployOnBuild=True `
/p:DeployTarget=Package `
/p:OutputPath=$AppOutputDir `
/p:DeployIisAppPath=$ApplicationName `
/p:TargetProfile=Cloud `
/p:publishDir=$MSBuildPubDir\ `
/p:VisualStudioVersion=12.0 `
/p:DefaultCloudToolsPath="C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Windows Azure Tools\2.5\\" `
/p:CloudToolsInstallPath="C:\Program Files (x86)\Microsoft Azure Tools\Visual Studio 12.0\2.5\\" `
/t:publish `
/verbosity:$verbosity

**Comment by gabikliot** [comment]
Maybe you can try building with exactly the same properties and only change /p:Configuration=Debug  and see if that works?

**Comment by JoshStardock** [comment]
Ok will do, give me just a minute.

**Comment by sergeybykov** [comment]
Why is the role failing to start? Are you getting any specific errors, anything in the log. Orleans codebase shouldn't be sensitive to debug vs. release.

**Comment by JoshStardock** [comment]
[2015-04-14 19:14:40.839 GMT     4	INFO   	100423	OrleansSiloHost	]	Setting silo type Secondary	
[2015-04-14 19:14:45.203 GMT    11	INFO   	100801	OrleansSiloInstanceManager	]	Attached to Azure storage table OrleansSiloInstances	
[2015-04-14 19:14:46.468 GMT    10	INFO   	100836	OrleansSiloInstanceManager	]	Initialized schema for Azure storage table OrleansSiloInstances	
[2015-04-14 19:14:46.500 GMT    10	WARNING	100815	OrleansSiloInstanceManager	]	Slow access to Azure Table OrleansSiloInstances for InitTable, which took 00:00:05.2861109.	
[2015-04-14 19:14:46.515 GMT     4	INFO   	100434	OrleansSiloHost	]	Setting silo Liveness Provider Type=AzureTable	
[2015-04-14 19:14:46.531 GMT     4	INFO   	100434	OrleansSiloHost	]	Setting silo Reminder Service Provider Type=AzureTable	
[2015-04-14 19:14:46.531 GMT     4	INFO   	100434	OrleansSiloHost	]	Setting Expected Cluster Size to=1	
[2015-04-14 19:14:46.546 GMT     4	INFO   	100270	OrleansSiloInstanceManager	]	Registering silo instance: OrleansSilo [ Deployment=9d8408a332c84abe908e3034d020c7d6 LocalEndpoint=10.238.72.97 LocalPort=11111 Generation=166734880 Host=RD00155D55F1CE Status=Created ProxyPort=30000 Primary= RoleName=Tachyon.Orleans Instance=Tachyon.Orleans_IN_0 UpgradeZone=0 FaultZone=0 StartTime=2015-04-14 19:14:41.011 GMT IAmAliveTime=]	
[2015-04-14 19:14:46.765 GMT     4	INFO   	100406	OrleansSiloHost	]	Setting Deployment Id to 9d8408a332c84abe908e3034d020c7d6 and data connection string to DefaultEndpointsProtocol=https;AccountName=tachyondev;AccountKey=<--SNIP-->	
[2015-04-14 19:14:46.781 GMT     4	INFO   	100407	OrleansSiloHost	]	Setting silo endpoint address to 10.238.72.97:11111:166734880	
[2015-04-14 19:14:46.796 GMT     4	INFO   	100408	OrleansSiloHost	]	Setting silo proxy endpoint address to 10.238.72.97:30000	
[2015-04-14 19:14:46.812 GMT     4	INFO   	100403	OrleansSiloHost	]	Initializing Silo Tachyon.Orleans_IN_0 on host=RD00155D55F1CE CPU count=1 running .NET version='4.0.30319.34014' Is .NET 4.5=True OS version='Microsoft Windows NT 6.2.9200.0'	
[2015-04-14 19:14:46.812 GMT     4	INFO   	100404	OrleansSiloHost	]	Silo running with GC settings: ServerGC=False GCLatencyMode=Batch	
[2015-04-14 19:14:46.812 GMT     4	WARNING	100405	OrleansSiloHost	]	Note: Silo not running with ServerGC turned on - recommend checking app config : <configuration>-<runtime>-<gcServer enabled="true"> and <configuration>-<runtime>-<gcConcurrent enabled="false"/>	
[2015-04-14 19:15:01.733 GMT     4	INFO   	100403	Silo	10.238.72.97:11111]	-------------- Initializing Secondary silo on RD00155D55F1CE at 10.238.72.97:11111, gen 166734880 --------------	
[2015-04-14 19:15:01.889 GMT     4	INFO   	100415	Silo	10.238.72.97:11111]	Starting silo Tachyon.Orleans_IN_0 with runtime Version='1.0.0.0 IsRelease.' Config= 
Config File Name: E:\approot\OrleansConfiguration.xml
Host: RD00155D55F1CE
Start time: 2015-04-14 19:15:01.733 GMT
Primary node: null
Platform version info:
   .NET version: 4.0.30319.34014
   Is .NET 4.5=True
   OS version: Microsoft Windows NT 6.2.9200.0
   GC Type=Client GCLatencyMode=Batch
Global configuration:
   System Ids:
      ServiceId: 00000000-0000-0000-0000-000000000000
      DeploymentId: 9d8408a332c84abe908e3034d020c7d6
   Subnet: 
   Seed nodes: 
   Messaging:
       Response timeout: 00:00:30
       Maximum resend count: 0
       Resend On Timeout: False
       Maximum Socket Age: 10675199.02:48:05.4775807
       Drop Expired Messages: True
       Silo Sender queues: 1
       Gateway Sender queues: 1
       Use standard (.NET) serializer: False
       Buffer Pool Buffer Size: 4096
       Buffer Pool Max Size: 10000
       Buffer Pool Preallocation Size: 250
       Use Message Batching: False
       Max Message Batching Size: 10
       Maximum forward count: 2
   Liveness:
      LivenessEnabled: True
      LivenessType: AzureTable
      ProbeTimeout: 00:00:10
      TableRefreshTimeout: 00:01:00
      DeathVoteExpirationTimeout: 00:02:00
      NumMissedProbesLimit: 3
      NumProbedSilos: 3
      NumVotesForDeathDeclaration: 2
      UseLivenessGossip: True
      IAmAliveTablePublishTimeout: 00:05:00
      NumMissedTableIAmAliveLimit: 2
      MaxJoinAttemptTime: 00:05:00
      ExpectedClusterSize: 1
   SystemStore:
      ConnectionString: DefaultEndpointsProtocol=https;AccountName=tachyondev;AccountKey=<--SNIP-->
   Application:
      Defaults:
         Deactivate if idle for: 02:00:00

   PlacementStrategy: 
         Default Placement Strategy: RandomPlacement
         Deployment Load Publisher Refresh Time: 00:00:01
         Activation CountBased Placement Choose Out Of: 2
   Grain directory cache:
      Maximum size: 1000000 grains
      Initial TTL: 00:00:30
      Maximum TTL: 00:04:00
      TTL extension factor: 2.00
      Directory Caching Strategy: Adaptive
   Grain directory:
      Lazy deregistration delay: 00:01:00
      Client registration refresh: 00:05:00
   Reminder Service:
       ReminderServiceType: AzureTable
   Consistent Ring:
       Use Virtual Buckets Consistent Ring: True
       Num Virtual Buckets Consistent Ring: 30
   Providers:
       BootstrapProviders:
           Name=TachyonBootstrap, Type=Tachyon.Grains.TachyonBootstrap, Properties=[]

Silo configuration:
   Silo Name: Tachyon.Orleans_IN_0
   Generation: 166734880
   Host Name or IP Address: 10.238.72.97
   DNS Host Name: RD00155D55F1CE
   Port: 11111
   Subnet: 
   Preferred Address Family: InterNetwork
   Proxy Gateway: 10.238.72.97:30000
   IsPrimaryNode: False
   Scheduler: 
         Max Active Threads: 1
         Processor Count: 1
         Delay Warning Threshold: 00:00:10
         Activation Scheduling Quantum: 00:00:00.1000000
         Turn Warning Length Threshold: 00:00:00.2000000
         Inject More Worker Threads: False
         MinDotNetThreadPoolSize: 200
         .NET thread pool sizes - Min: Worker Threads=1 Completion Port Threads=1
         .NET thread pool sizes - Max: Worker Threads=32767 Completion Port Threads=1000
         .NET ServicePointManager - DefaultConnectionLimit=200 Expect100Continue=False UseNagleAlgorithm=False
   Load Shedding Enabled: False
   Load Shedding Limit: 95
   Debug: 
   Tracing: 
     Default Trace Level: Info
     TraceLevelOverrides:
         Application ==> Info
     Trace to Console: True
     Trace File Name: E:\approot\Tachyon.Orleans_IN_0-2015-04-14-19.14.40.073Z.log
     Write Messaging Traces: False
     LargeMessageWarningThreshold: 85000
     PropagateActivityId: False
     BulkMessageLimit: 1000
   Statistics: 
     MetricsTableWriteInterval: 00:00:30
     PerfCounterWriteInterval: 00:00:30
     LogWriteInterval: 00:05:00
     WriteLogStatisticsToTable: True
     StatisticsCollectionLevel: Info

	
[2015-04-14 19:15:06.710 GMT     4	INFO   	100000	Scheduler.OrleansTaskScheduler	10.238.72.97:11111]	Starting OrleansTaskScheduler with 1 Max Active application Threads and 1 system thread.	
[2015-04-14 19:15:07.002 GMT     4	INFO   	101010	Runtime.Messaging.IncomingMessageAcceptor/1	10.238.72.97:11111]	Opened a listening socket at address 10.238.72.97:11111	
[2015-04-14 19:15:07.048 GMT     4	INFO   	101010	Runtime.Messaging.GatewayAcceptor/1	10.238.72.97:11111]	Opened a listening socket at address 10.238.72.97:30000	
[2015-04-14 19:15:08.230 GMT     4	INFO   	100000	VirtualBucketsRingProvider	10.238.72.97:11111]	Starting VirtualBucketsRingProvider on silo S10.238.72.97:11111:166734880/x9109DDF2.	
[2015-04-14 19:15:08.527 GMT     4	INFO   	103003	VirtualBucketsRingProvider	10.238.72.97:11111]	Added Server S10.238.72.97:11111:166734880/x9109DDF2. Current view: [S10.238.72.97:11111:166734880 -> <MultiRange: Size=x100000000, %Ring=100.000%>]	
[2015-04-14 19:15:08.527 GMT     4	INFO   	103005	VirtualBucketsRingProvider	10.238.72.97:11111]	-NotifyLocalRangeSubscribers about old <(0 0], Size=x100000000, %Ring=100.000%> new <MultiRange: Size=x100000000, %Ring=100.000%> increased? True	
[2015-04-14 19:15:08.683 GMT     4	INFO   	100294	SystemStatus	10.238.72.97:11111]	SystemStatus=Created	
[2015-04-14 19:15:08.683 GMT     4	INFO   	100422	Silo	10.238.72.97:11111]	-------------- Started silo S10.238.72.97:11111:166734880, ConsistentHashCode 9109DDF2 --------------	
[2015-04-14 19:15:08.699 GMT     4	INFO   	100288	OrleansAzureSilo	10.238.72.97:11111]	Successfully initialized Orleans silo 'Tachyon.Orleans_IN_0' as a Secondary node.	
[2015-04-14 19:15:08.699 GMT     4	INFO   	100292	OrleansAzureSilo	10.238.72.97:11111]	Starting Orleans silo 'Tachyon.Orleans_IN_0' as a Secondary node.	
[2015-04-14 19:15:08.907 GMT     4	INFO   	100294	SystemStatus	10.238.72.97:11111]	SystemStatus=Starting	
[2015-04-14 19:15:08.907 GMT     4	INFO   	100401	Silo	10.238.72.97:11111]	Silo Start()	
[2015-04-14 19:15:08.922 GMT     4	INFO   	100430	Silo	10.238.72.97:11111]	Configured ThreadPool.SetMinThreads() to values: 200,200. Previous values are: 1,1.	
[2015-04-14 19:15:08.922 GMT     4	INFO   	100436	Silo	10.238.72.97:11111]	Configured .NET ServicePointManager to Expect100Continue=False, DefaultConnectionLimit=200, UseNagleAlgorithm=False to improve Azure storage performance.	
[2015-04-14 19:15:09.368 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	Searching for assemblies in E:\approot...	
[2015-04-14 19:15:12.247 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\AutoMapper.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:12.263 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\AutoMapper.Net4.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:13.169 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\EntityFramework.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:13.294 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\EntityFramework.SqlServer.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:13.310 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\JsonPatch.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:13.435 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.Data.Edm.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:13.622 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.Data.OData.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:13.732 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.Data.Services.Client.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:14.513 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.ServiceBus.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:14.544 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.Threading.Tasks.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:14.560 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.Threading.Tasks.Extensions.Desktop.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:14.575 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.Threading.Tasks.Extensions.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:14.575 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.WindowsAzure.CloudDrive.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:14.591 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.WindowsAzure.Configuration.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:14.591 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.WindowsAzure.Diagnostics.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:14.700 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.WindowsAzure.ServiceRuntime.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:14.841 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.WindowsAzure.Storage.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:14.997 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Microsoft.WindowsAzure.StorageClient.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.028 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\MonAgentListener.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.138 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Newtonsoft.Json.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.138 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Orleans.dll
	* Assembly filename is excluded.	
[2015-04-14 19:15:15.138 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\OrleansAzureUtils.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.185 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\OrleansRuntime.dll
	* Assembly filename is excluded.	
[2015-04-14 19:15:15.372 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\RazorEngine.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.435 GMT     4	ERROR  	101716	AssemblyLoader.Silo	10.238.72.97:11111]	!!!!!!!!!! An unexpected exception occurred while attempting to load an assembly.	
Exc level 0: System.BadImageFormatException: Could not load file or assembly 'file:///E:\approot\sdkencryptedappticket.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.ReflectionOnlyLoadFrom(String assemblyFile)
   at Orleans.Runtime.AssemblyLoader.ReflectionOnlyLoadAssembly(String pathName, Assembly& assembly, String[]& complaints)
[2015-04-14 19:15:15.435 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\sdkencryptedappticket.dll
	* An unexpected exception occurred while attempting to load an assembly.	
[2015-04-14 19:15:15.450 GMT     4	ERROR  	101716	AssemblyLoader.Silo	10.238.72.97:11111]	!!!!!!!!!! An unexpected exception occurred while attempting to load an assembly.	
Exc level 0: System.BadImageFormatException: Could not load file or assembly 'file:///E:\approot\sdkencryptedappticket64.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.ReflectionOnlyLoadFrom(String assemblyFile)
   at Orleans.Runtime.AssemblyLoader.ReflectionOnlyLoadAssembly(String pathName, Assembly& assembly, String[]& complaints)
[2015-04-14 19:15:15.450 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\sdkencryptedappticket64.dll
	* An unexpected exception occurred while attempting to load an assembly.	
[2015-04-14 19:15:15.466 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Stardock.CryptoUtil.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.528 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Stardock.Net.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.544 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Stardock.Services.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.607 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\System.Net.Http.Formatting.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.622 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\System.Runtime.Caching.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.654 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\System.Spatial.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.794 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\System.Web.Http.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.841 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\System.Web.Razor.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.888 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Tachyon.Azure.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.903 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Tachyon.Common.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.950 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Tachyon.DAL.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:15.966 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Tachyon.DTOs.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:16.075 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Tachyon.Grains.Interfaces.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:16.075 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\Tachyon.Orleans.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:16.107 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	User assembly ignored: E:\approot\WebSocket4Net.dll
	* Assembly does not contain any acceptable grain types.
	* Assembly contains no types assignable from Orleans.Providers.IProvider.	
[2015-04-14 19:15:16.123 GMT     4	WARNING	101705	AssemblyLoader.Silo	10.238.72.97:11111]	Unable to find directory E:\approot\Applications; skipping.	
[2015-04-14 19:15:16.123 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	Loading assembly E:\approot\OrleansProviders.dll...	
[2015-04-14 19:15:16.169 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	Loading assembly E:\approot\Tachyon.Grains.dll...	
[2015-04-14 19:15:16.560 GMT     4	INFO   	100000	AssemblyLoader.Silo	10.238.72.97:11111]	2 assemblies loaded.	
[2015-04-14 19:15:17.454 GMT     4	ERROR  	100439	Silo	10.238.72.97:11111]	!!!!!!!!!! Exception during Silo.Start	
Exc level 0: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at Orleans.Runtime.SiloAssemblyLoader.GetGrainClassTypes(Boolean strict)
   at Orleans.Runtime.GrainTypeManager.InitializeGrainClassData(SiloAssemblyLoader loader, Boolean strict)
   at Orleans.Runtime.GrainTypeManager.Start(Boolean strict)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
[2015-04-14 19:15:17.466 GMT     4	ERROR  	100105	OrleansSiloHost	10.238.72.97:11111]	!!!!!!!!!! ERROR starting Orleans silo name=Tachyon.Orleans_IN_0 Exception=
Exc level 0: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at Orleans.Runtime.SiloAssemblyLoader.GetGrainClassTypes(Boolean strict)
   at Orleans.Runtime.GrainTypeManager.InitializeGrainClassData(SiloAssemblyLoader loader, Boolean strict)
   at Orleans.Runtime.GrainTypeManager.Start(Boolean strict)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo()	
Exc level 0: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at Orleans.Runtime.SiloAssemblyLoader.GetGrainClassTypes(Boolean strict)
   at Orleans.Runtime.GrainTypeManager.InitializeGrainClassData(SiloAssemblyLoader loader, Boolean strict)
   at Orleans.Runtime.GrainTypeManager.Start(Boolean strict)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo()
[2015-04-14 19:15:17.482 GMT     4	ERROR  	100285	OrleansAzureSilo	10.238.72.97:11111]	!!!!!!!!!! Failed to start Orleans silo 'Tachyon.Orleans_IN_0' as a Secondary node.	
[2015-04-14 19:15:18.278 GMT     2	WARNING	100220	Silo	10.238.72.97:11111]	Process is exiting

**Comment by JoshStardock** [comment]
We just ran a build with the same parameters I posted earlier with the exception of the following change:
/p:Configuration=Release

So we can rule that out and isolate it to IntelliTrace or RemoteDebugger.  Have you seen this be an issue?

**Comment by sergeybykov** [comment]
Oh! Disable IntelliTrace. This is known bug in VS, fixed in Update 5.

**Comment by gabikliot** [comment]
:+1:

**Comment by JoshStardock** [comment]
We will disable IntelliTrace, thank you so much for the help!

**Comment by sergeybykov** [comment]
You are welcome. It's always fun to pull your hair when it's actually IL being rewritten underneath your code. :-)

**Comment by gabikliot** [comment]
Feels lie we can close this, right?

**Comment by JoshStardock** [comment]
I will close it.
