### ISSUE TITLE
Client streamsubscription in testcluster does not receive events

### ISSUE THREAD

**Issue by rikbosch** [dotnet/orleans#3292]
Hi,

I'm researching a failure in our test-suites using test-cluster.

Streamsubscription in the testclient seem to die / stop receiving new events.

Looking at the primary / secundary and client logs of the testcluster I see a lot of `OrleansMessageRejectionException`  coming from `SimpleMessageStreamProducer`:

```
[2017-08-10 09:01:04.781 GMT     9	INFO   	100540	Catalog	127.0.0.1:25245]	DeactivateActivationOnIdle: [Activation: S127.0.0.1:25245:240051557*grn/716E8E94/00000000+DomainEvents_$tenant@5c9f9495 #GrainType=Orleans.Streams.PubSubRendezvousGrain Placement=RandomPlacement State=Deactivating] later when become idle.	
[2017-08-10 09:01:04.781 GMT    19	INFO   	100540	Catalog	127.0.0.1:25245]	DeactivateActivationOnIdle: [Activation: S127.0.0.1:25245:240051557*grn/716E8E94/d5a85bb8+DomainEvents_$all@32566787 #GrainType=Orleans.Streams.PubSubRendezvousGrain Placement=RandomPlacement State=Deactivating] later when become idle.	
[2017-08-10 09:01:04.781 GMT    71	INFO   	100540	Catalog	127.0.0.1:25245]	DeactivateActivationOnIdle: [Activation: S127.0.0.1:25245:240051557*grn/716E8E94/00000000+DomainEvents_$tenant@295efc88 #GrainType=Orleans.Streams.PubSubRendezvousGrain Placement=RandomPlacement State=Deactivating] later when become idle.	
[2017-08-10 09:01:04.782 GMT     9	INFO   	100503	Catalog	127.0.0.1:25245]	Starting DestroyActivations #2 of 1 activations	
[2017-08-10 09:01:04.781 GMT    53	INFO   	100540	Catalog	127.0.0.1:25245]	DeactivateActivationOnIdle: [Activation: S127.0.0.1:25245:240051557*grn/716E8E94/00000000+DomainEvents_$tenant@7cc466a4 #GrainType=Orleans.Streams.PubSubRendezvousGrain Placement=RandomPlacement State=Deactivating] later when become idle.	
[2017-08-10 09:01:04.782 GMT    19	INFO   	100503	Catalog	127.0.0.1:25245]	Starting DestroyActivations #3 of 1 activations	
[2017-08-10 09:01:04.782 GMT    71	INFO   	100503	Catalog	127.0.0.1:25245]	Starting DestroyActivations #4 of 1 activations	
[2017-08-10 09:01:04.784 GMT    71	INFO   	100539	Catalog	127.0.0.1:25245]	Done FinishDestroyActivations #2 - Destroyed 1 Activations.	
[2017-08-10 09:01:04.784 GMT     9	INFO   	100539	Catalog	127.0.0.1:25245]	Done FinishDestroyActivations #4 - Destroyed 1 Activations.	
[2017-08-10 09:01:04.791 GMT    53	INFO   	100539	Catalog	127.0.0.1:25245]	Done FinishDestroyActivations #5 - Destroyed 1 Activations.	
[2017-08-10 09:01:04.803 GMT    15	WARNING	101032	Dispatcher	127.0.0.1:25245]	Forwarding failed: tried to forward message NewPlacement Request S127.0.0.1:25245:240051557*grn/584B3456/00000000+job-015dcb60-16b4-4d3b-b197-9cb5017446b4@26304a91->S127.0.0.1:25245:240051557*grn/716E8E94/00000000+DomainEvents_$tenant@2eff8aa8 #5748[ForwardCount=2]: global::Orleans.Streams.IPubSubRendezvousGrain:UnregisterProducer() for 2 times after Duplicate activation to invalid activation. Rejecting now.	
[2017-08-10 09:01:04.808 GMT     4	WARNING	103402	SimpleMessageStreamProducer`1	127.0.0.1:25245]	Ignoring unhandled exception during PubSub.UnregisterProducer	
Exc level 0: Orleans.Runtime.OrleansMessageRejectionException: Forwarding failed: tried to forward message NewPlacement Request S127.0.0.1:25245:240051557*grn/584B3456/00000000+job-015dcb60-16b4-4d3b-b197-9cb5017446b4@26304a91->S127.0.0.1:25245:240051557*grn/716E8E94/00000000+DomainEvents_$tenant@2eff8aa8 #5748[ForwardCount=2]: global::Orleans.Streams.IPubSubRendezvousGrain:UnregisterProducer() for 2 times after Duplicate activation to invalid activation. Rejecting now. 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.<Cleanup>d__28.MoveNext()
[2017-08-10 09:01:04.811 GMT    15	WARNING	101032	Dispatcher	127.0.0.1:25245]	Forwarding failed: tried to forward message NewPlacement Request S127.0.0.1:25245:240051557*grn/35507F3/00000000+driver-015dcb60-124e-4193-bf9c-cdc075057de1@038157b3->S127.0.0.1:25245:240051557*grn/716E8E94/00000000+DomainEvents_$tenant@9366549d #5719[ForwardCount=2]: global::Orleans.Streams.IPubSubRendezvousGrain:UnregisterProducer() for 2 times after Duplicate activation to invalid activation. Rejecting now.	
[2017-08-10 09:01:04.812 GMT    71	WARNING	103402	SimpleMessageStreamProducer`1	127.0.0.1:25245]	Ignoring unhandled exception during PubSub.UnregisterProducer	
Exc level 0: Orleans.Runtime.OrleansMessageRejectionException: Forwarding failed: tried to forward message NewPlacement Request S127.0.0.1:25245:240051557*grn/35507F3/00000000+driver-015dcb60-124e-4193-bf9c-cdc075057de1@038157b3->S127.0.0.1:25245:240051557*grn/716E8E94/00000000+DomainEvents_$tenant@9366549d #5719[ForwardCount=2]: global::Orleans.Streams.IPubSubRendezvousGrain:UnregisterProducer() for 2 times after Duplicate activation to invalid activation. Rejecting now. 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.<Cleanup>d__28.MoveNext()

```

full logs: https://gist.github.com/rikbosch/3641097bcfbfedb1f4e310e0d9d73eea

what could cause this?

**Comment by rikbosch** [comment]
We have fixed the issue caused by removing the reentrant  attribute.  I'm however still curious about the exceptions in our logs.

**Comment by xiazen** [comment]
Just to confirm. You have fixed the 

> Streamsubscription in the testclient seem to die / stop receiving new events.

by removing reentrant attribute. And you are just curious about why the exception  in the logs happen?

**Comment by xiazen** [comment]
The exception means failed to forward UnregisterProducer response to an activation because it is a duplicated activation. Duplicated activation often happen when there's disruption events happening in the cluster, such as host shutdown, or cluster resizing.

**Comment by xiazen** [comment]
But duplicated activation is supposed to be rare, and will clear itself up in a short period of time. Is this what you are seeing?

**Comment by rikbosch** [comment]
Yes, thank you for your response. I think the duplicated activation is
caused by the spinning up of the testcluster silo's.

This issue can be closed I think.
