### ISSUE TITLE
OrleansJsonSerializer can not be used as IExternalSerializer

### ISSUE THREAD

**Issue by elqueffo** [dotnet/orleans#3331]
OrleansJsonSerializer can not be used as SerializationProvider even though it implements IExternalSerializer and is mentioned as a possible provider  in the [documentation.](https://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Serialization.html)

System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Orleans.Serialization.SerializationManager.<RegisterSerializationProviders>b__112_0(TypeInfo typeInfo)

We have custom json converters for various application specific types that we need to use to pass calls over the wire. Currently we can not use the provided OrleansJsonSerializer that also contains orleans specific type converters, and we can not add these orleans converters to any custom IExternalSerializer either because they are internal.

Repro:

            config.Globals.SerializationProviders.Add(typeof(OrleansJsonSerializer).GetTypeInfo());

or

            clientConfig.SerializationProviders.Add(typeof(OrleansJsonSerializer).GetTypeInfo());

**Comment by ReubenBond** [comment]
Fixed in #3627

**Comment by talarari** [comment]
Any chance of getting this releases on 1.5.x? We won't be upgrading to 2.0 in the very near future and this is helpful for us now.

**Comment by ReubenBond** [comment]
@talarari there are no current plans to back port it, but you could use a modified version of the code to have your own IExternalSerializer based on these fixes
