### ISSUE TITLE
.NetCore2.0 Runtime Codegen fail in Orleans TP3

### ISSUE THREAD

**Issue by bluexo** [dotnet/orleans#3404]
When I build a .net core 2.0 application with Orleans , I already add reference Orleans.OrleanCodeGenerator to my Client and Server , but  the orleans client and server not  load the grains dll , and occur this error :

```
Unhandled Exception: System.ArgumentException: Cannot find an implementation class for grain interface: Orleans.Interface.IPlayerGrain. Make sure the grain assembly was correctly deployed and loaded in the silo.
   at Orleans.GrainFactory.GetGrainClassData(Type interfaceType, String grainClassNamePrefix)
   at Orleans.GrainFactory.GetGrain[TGrainInterface](Int64 primaryKey, String grainClassNamePrefix)
   at Orleans.Client.Program.Main(String[] args) in C:\Users\Administrator\Documents\visual studio 2017\Projects\OrleansCore\Orleans.Client\Program.cs:line 14
```
thats my code :

Interface :
``` C#
    public interface IPlayerGrain : IGrainWithIntegerKey
    {
        Task SayHello(string content);
    }
```
Grain : 
``` C#
    public class PlayerGrain : IPlayerGrain
    {
        public Task SayHello(string content)
        {
            Console.WriteLine($"Say {content} to {this.GetPrimaryKeyLong()}");
            return Task.CompletedTask;
        }
    }
```
Client : 
``` C#
    var config = ClientConfiguration.LocalhostSilo();
    GrainClient.Initialize(config);
    var player = GrainClient.GrainFactory.GetGrain<IPlayerGrain>(1000);
    player.SayHello("Hi!!!");
    Console.WriteLine("Press any key to terminate!");
    Console.ReadKey();
```
Server:
``` C#
    var config = ClusterConfiguration.LocalhostPrimarySilo();
    var siloHost = new SiloHost("Orleans",config);
    siloHost.InitializeOrleansSilo();
    siloHost.StartOrleansSilo(true);
    Console.WriteLine("Press any key to terminate!");
    Console.ReadKey();
```

**Comment by ReubenBond** [comment]
@bluexo make sure that the DLLs are loaded before starting your client + silo

**Comment by bluexo** [comment]
@ReubenBond  I publish the project to ONE folder and run it , but the error still exsits , has another way to build the project ? Need I manual load DLLs ?

**Comment by Cherrs** [comment]
client引用Microsoft.Orleans.Client，版本2.0.0-preview*
server引用Microsoft.Orleans.Server，版本2.0.0-preview*
然后你再试下
我之前按照例子里的方式引用跟你一样，没有加载dll

**Comment by bluexo** [comment]
@Cherrs 你自己测试过TP3了？ .net core 2.0 不支持 Build code generator 只支持 Runtime code generator ， 你要是不引用 Oreans.OrleansCodeGenerator 不可能正确调用 Grain ， 你说的方法我试过了，不行的

**Comment by Cherrs** [comment]
@bluexo Orleans.Client和Server本身引用了Microsoft.Orleans.OrleansCodeGenerator，只要引用Client和Server就可以了。
[https://github.com/Cherrs/demo](我刚上传的demo)，result.png里有完成的截图。

**Comment by Cherrs** [comment]
@bluexo 我知道为什么我能运行了，因为我是publish，我配置的3个节点，直接publish之后修改配置文件运行的。我测试dotnet run运行是会出现你那个问题。

**Comment by csyszf** [comment]
@bluexo My project works well when use `IClusterClient`
``` csharp
private async Task InitSiloAsync()
{
    Console.WriteLine("silo initing");

    var config = ClientConfiguration.LocalhostSilo();
    config.FallbackSerializationProvider = typeof(ILBasedSerializer).GetTypeInfo();
    client = new ClientBuilder().UseConfiguration(config).Build();
    await client.Connect();
    Console.WriteLine("connected");
}
```

**Comment by sunnycase** [comment]
You should write `PlayerGrain : Grain`.

**Comment by larsfjerm** [comment]
Can report of same issues here.
