### ISSUE TITLE
Problem in deserializing DocumentClientException

### ISSUE THREAD

**Issue by yzhao174** [dotnet/orleans#3422]
DocumentClientException thrown from CosmosDB library doesn't have a public constructor. The message of this exception won't be deserialized by grain caller function. This makes logging and debugging more complex. 

My current work around is to create a wrapper class on top of DocumentClientException. Is there a better way of doing this?

**Comment by sergeybykov** [comment]
#2633 should have enabled transparent serialization of non-serializable exception.
>This is an extension to ILBasedSerializer and therefore will only be enabled if that is the configured FallbackSerializationProvider. This it the default on .NET Core, but not Full .NET.

**Comment by yzhao174** [comment]
Thanks Sergey. Is there any code sample that I could look at to make it work with DocumentClientException ? Or I should just upgrade the orleans version and it is natively supported?

**Comment by sergeybykov** [comment]
This change was already in 1.4.0. You just need to set `MessagingConfiguration.FallbackSerializationProvider` to `typeof(ILBasedSerializer)` in your configuration code.

**Comment by yzhao174** [comment]
I am using 1.15.0 and it seems ILBasedSerializer takes forever to finish. I am trying to see what's happening there

**Comment by yzhao174** [comment]
Exception thrown: 'System.NotSupportedException' in Orleans.dll
Exception thrown: 'System.NotSupportedException' in OrleansRuntime.dll
ControlPlane.StatelessSilo.exe Error: 0 : [2017-09-19 21:26:14.318 GMT    43	ERROR  	101017	Runtime.Messaging.GatewayAcceptor	127.0.0.1:22222]	!!!!!!!!!! Exception trying to process 459 bytes from endpoint 127.0.0.1:31003	
Exc level 0: System.NotSupportedException: ILSerializerTypeToken of 65 is not supported.
   at Orleans.Serialization.ILBasedSerializer.ReadType(ILSerializerTypeToken token, IDeserializationContext context, Type expectedType)
   at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.FallbackDeserializer(IDeserializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeDictionary[K,V](Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeGenericDictionary(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Runtime.Message.HeadersContainer.Deserializer(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeMessageHeaders(IDeserializationContext context)
   at Orleans.Runtime.IncomingMessageBuffer.TryDecodeMessage(Message& msg)
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor.ReceiveCallbackContext.ProcessReceived(SocketAsyncEventArgs e)
Exception thrown: 'System.NotSupportedException' in OrleansRuntime.dll
ControlPlane.StatelessSilo.exe Error: 0 : [2017-09-19 21:26:14.342 GMT    43	ERROR  	101027	Runtime.Messaging.GatewayAcceptor	127.0.0.1:22222]	!!!!!!!!!! ProcessReceivedBuffer exception with RemoteEndPoint 127.0.0.1:31003: 	
Exc level 0: System.NotSupportedException: ILSerializerTypeToken of 65 is not supported.
   at Orleans.Serialization.ILBasedSerializer.ReadType(ILSerializerTypeToken token, IDeserializationContext context, Type expectedType)
   at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.FallbackDeserializer(IDeserializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeDictionary[K,V](Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeGenericDictionary(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Runtime.Message.HeadersContainer.Deserializer(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeMessageHeaders(IDeserializationContext context)
   at Orleans.Runtime.IncomingMessageBuffer.TryDecodeMessage(Message& msg)
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor.ReceiveCallbackContext.ProcessReceived(SocketAsyncEventArgs e)
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor.ProcessReceive(SocketAsyncEventArgs e)

**Comment by sergeybykov** [comment]
Did you configure `FallbackSerializationProvider` identically on both the silo and the client side?

**Comment by yzhao174** [comment]
I only configure it in Silo. I will try to test again with client side configured. Thanks

**Comment by sergeybykov** [comment]
Serialization setting on the client and silo sides must match for things to work.

**Comment by sergeybykov** [comment]
@yzhao174 Did you get it to work after all?

**Comment by yzhao174** [comment]
I tried to add serialization settings on both sides.
Client:
`Globals.OrleansClient.Configuration.FallbackSerializationProvider = typeof(ILBasedSerializer).GetTypeInfo();`
Server:
`config.Globals.FallbackSerializationProvider = typeof(ILBasedSerializer).GetTypeInfo();
`
It seems after I add it on server side, call to grains take forever to complete:
```
IHelloEnvironment grainRef = Globals.OrleansClient.GetGrain<IHelloEnvironment>(id);
string response = await grainRef.RequestDetails();
```

**Comment by ReubenBond** [comment]
Hi, @yzhao174, apologies for not getting back to you. If this is still unresolved, would you be able to provide us with logs? I believe there's a serialization error of some kind but I'd like to diagnose it.

**Comment by ReubenBond** [comment]
Closing for now. @yzhao174 please re-open if you are still hitting this issue and we can solve it together
