### ISSUE TITLE
ArgumentNullException in System.Buffer.BlockCopy

### ISSUE THREAD

**Issue by shanegrueling** [dotnet/orleans#3466]
Hey,

after we added our second silo to our cluster the following error started appearing.

```
[2017-09-28 12:35:27.659 GMT   165    ERROR      101030    Message    192.168.0.5:11111]    !!!!!!!!!! Exception deserializing message body    
Exc level 0: System.ArgumentNullException: Value cannot be null.
Parameter name: src
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Orleans.Serialization.SerializationManager.DeserializeArray(Type resultType, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeInvokeMethodRequest(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, BinaryTokenStreamReader stream)
   at Orleans.Runtime.Message.DeserializeBody(SerializationManager serializationManager, List`1 bytes)
```

@ReubenBond looked at it but couldn't find where this is happening in Orleans code. The DeserializeArray doesn't call BlockCopy.

The only other error we get is that a IEnumerable is null that gets send from one grain to another is null despite it not being possible because Grain B sends a new List<> to Grain A.
Might be related, might not be.

**Orleans Version: 1.5.1**
**.NET Version: 4.6.1**

If there is anything I can add don't hesitate to ask.

Regards,
Chen

**Comment by ReubenBond** [comment]
It would be interesting to debug when this happens so you can get a better idea of the stack trace and locals. Is it still occurring, @shanegrueling? Apologies for the slow response.

Possibly what's happening is that BlockCopy is being called by the runtime somewhere - maybe we'd need to see disassembled code to see the specifics. If it's possible to create a repro project, I'd like to get to the bottom of this.

**Comment by ReubenBond** [comment]
Closing for now: we can reopen if this is still an issue.
