### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by TuoNiao** [dotnet/orleans#3474]
I publish the orleans silio on windows by using below command with no build errors

dotnet publish -c Release -r centos.7-x64

but when I try to start the program on CentOS 7 I always receive below Error messages

Bad IL format.
Exception = System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Orleans.Runtime.AssemblyLoader.ReflectionOnlyLoadAssembly(String pathName, Assembly& assembly, String[]& complaints)

[2017-09-30 06:14:29.834 GMT     2	ERROR  	101716	AssemblyLoader.Silo	10.129.236.87:5100]	!!!!!!!!!! An unexpected exception occurred while attempting to load an assembly.	
Exc level 0: System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Orleans.Runtime.AssemblyLoader.ReflectionOnlyLoadAssembly(String pathName, Assembly& assembly, String[]& complaints)

my orleans version is 2.0.0-preview3-20170913, Please help

**Comment by attilah** [comment]
The error is happening, because ReflectionOnly assembly loading is not available in .Net Core regardless of the platform you're running on (https://github.com/dotnet/coreclr/issues/9624).

On the other hand, we did not test cross platform for the latest preview, since that was out of scope for it.

Currently we're reworking out assembly scanning/loading and we plan to include this in the 2.0 Beta release.

One thing when running on other platforms than Windows is to make sure that you've build time code generation for your grain interfaces, so runtime codegen - which will fail for the above reasons - is not involved when running your Silo.

Please let me know if you've runtime codegen enabled and was still failing, also if you can test the same published code for Windows to help decide is it an xplat or .Net Core issue.

**Comment by attilah** [comment]
Closing, since I think there are no outstanding questions and the questioned part is rewritten fully in then next release.

Please file a new issue and attach this one if a similar error would happen with the next release.
