### ISSUE TITLE
Host Silo and client under the same ASP.NET project

### ISSUE THREAD

**Issue by Kimserey** [dotnet/orleans#3476]
**Is it possible to host Silo and client under the same project?**

I am using Consul membership provider with one Silo, here is my Silo configuration:

```
{
      "Globals": {
            "DeploymentId": "clusterOne",
            "LivenessType": "Custom",
            "DataConnectionString": "http://localhost:8500",
            "MembershipTableAssembly": "OrleansConsulUtils",
            "ReminderServiceType": "Disabled"
       },
      "Defaults": {
        "HostNameOrIPAddress": "localhost",
        "Port": 30007,
        "ProxyGatewayEndpoint": {
          "Address": "localhost",
          "Port": 40007
        }
      }
}
```

And this is my client configuration:

```
 Platform version info:
   Orleans version: 1.5.1.0 (Release).
   .NET version: 4.0.30319.42000
   OS version: Microsoft Windows NT 6.2.9200.0
   App config file: C:\Projects\OrleansClusterConsul\OrleansClient1\bin\Debug\net47\OrleansClient1.exe.Config
   GC Type=Server GCLatencyMode=Batch
   Host: ...
   Processor Count: 8
Client Configuration:
   Config File Name: 
   Start time: 2017-10-01 06:01:15.810 GMT
   Gateway Provider: Custom
   Gateways: Unspecified
   Preferred Gateway Index: -1
   GatewayListRefreshPeriod: 00:01:00
   Azure:
      DeploymentId: clusterOne
      DataConnectionString: http://localhost:8500
   Preferred Address Family: InterNetwork
   DNS Host Name: ...
   Client Name: Client
   Tracing: 
     Default Trace Level: Info
     TraceLevelOverrides: None
     Trace to Console: True
     Trace File Name: C:\Projects\OrleansClusterConsul\OrleansClient1\Client-2017-10-01-06.01.12.311Z.log
     LargeMessageWarningThreshold: 85000
     PropagateActivityId: False
     BulkMessageLimit: 5
   Statistics: 
     MetricsTableWriteInterval: 00:00:30
     PerfCounterWriteInterval: -00:00:00.0010000
     LogWriteInterval: 00:05:00
     WriteLogStatisticsToTable: True
     StatisticsCollectionLevel: Info
   Messaging:
       Response timeout: 00:30:00
       Maximum resend count: 0
       Resend On Timeout: False
       Maximum Socket Age: 10675199.02:48:05.4775807
       Drop Expired Messages: True
       Client Sender Buckets: 8192
       Buffer Pool Buffer Size: 4096
       Buffer Pool Max Size: 10000
       Buffer Pool Preallocation Size: 250
       Fallback serializer: 
   .NET: 
       .NET thread pool sizes - Min: Worker Threads=8 Completion Port Threads=8
       .NET thread pool sizes - Max: Worker Threads=1023 Completion Port Threads=1000
   Providers:
       No providers configured.
```

But as soon as I initialize the client and access a grain, the silo gets confused and treats its own address as the proxy port and hence marks itself as suspected dead in Consul.

_There is no issue when the client and silo is separated._

Please see error below, localhost:30003 being the silo port while localhost:40007 being the proxy gateway.

```
[16:55:39 ERR] Runtime - 10.0.75.1:0: Exception when trying to get GrainInterfaceMap for silos S127.0.0.1:30007:244544048
Orleans.Runtime.OrleansMessageRejectionException: Silo S127.0.0.1:40007:244544048 is rejecting message: Request S127.0.0.1:40007:244544048TypeManagerId@S00000011->S127.0.0.1:30007:244544048TypeManagerId@S00000011 #59: global::Orleans.Runtime.ISiloTypeManager:GetSiloTypeCodeMap(). Reason = Target S127.0.0.1:30007:244544048 silo is known to be dead
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass0_0`1.<<QueueTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.TypeManager.<GetTargetSiloGrainInterfaceMap>d__22.MoveNext()
```

**Comment by Kimserey** [comment]
I changed the membership provider from ConsulUtils to SqlUtils and it

**Comment by Kimserey** [comment]
_Sorry I closed the issue by mistake._

**Comment by sergeybykov** [comment]
@Kimserey Sorry about such a late response. Have you already figured this out?

**Comment by Kimserey** [comment]
Thanks for the reply @sergeybykov. 

Shortly after testing and confirming that the problem came from using Consul as membership provider, I moved my membership provider from Consul to SqlUtils therefore I am not sure if the issue remains.

**Comment by sergeybykov** [comment]
I'll close it then. Feel free to reopen if you run into it again.
