### ISSUE TITLE
how support .net core 2.0 ?

### ISSUE THREAD

**Issue by chenzuo** [dotnet/orleans#3477]
Warning NU1701 has used the ".NET Framework, Version = v4.6.1" instead of the project target framework ".NETCoreApp, Version = v2.0" to restore the package "Microsoft.Orleans.Core 1.5.1". This package may not be fully compatible with the project. XUnitTestProject1 D: \ Work \ 2017 \ Complany \ GameCore \ XUnitTestProject1 \ XUnitTestProject1.csproj 1

**Comment by sergeybykov** [comment]
Are you trying to use 1.5.1 in a .NET Core project? That won't work. You can try the latest Tech Preview release instead - https://blogs.msdn.microsoft.com/orleans/2017/09/13/announcing-orleans-2-0-tech-preview-3/.

**Comment by chenzuo** [comment]
ths！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zahidiqb** [comment]
@sergeybykov 

Using the pre-release version "2.0.0-preview4-20171025"
I get the following exception:

System.InvalidOperationException occurred
  HResult=0x80131509
  Message=**Cannot find generated GrainReference class for interface** 'GrainInterfaces.IInteractionGrain'
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Orleans.Runtime.TypeMetadataCache.GetGrainReferenceType(Type interfaceType)
   at Orleans.GrainFactory.MakeCaster(Type interfaceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orleans.GrainFactory.Cast(IAddressable grain, Type interfaceType)
   at Orleans.GrainFactory.Cast[TGrainInterface](IAddressable grain)
   at Orleans.GrainFactory.GetGrain[TGrainInterface](Guid primaryKey, String grainClassNamePrefix)
   at Orleans.ClusterClient.GetGrain[TGrainInterface](Guid primaryKey, String grainClassNamePrefix)
   at ClinetDotnetCore.Program.Main(String[] args) in ...



I am running client and server after publishing and the both dlls containing interfaces and implementations are located in the same folder (bin\Release\PublishOutput) but still I get the error. 
Maybe I'm missing any configuration ??
