### ISSUE TITLE
VersionAwarePlacementStrategy Exception

### ISSUE THREAD

**Issue by yzhao174** [dotnet/orleans#3543]
I am trying to create a customized placement strategy. Following the sample, that I copied the implementation of VersionAwarePlacementStrategy/VersionAwarePlacementDirector/VersionAwareStrategyAttribute and apply the attribute to one of my Grain:
```
[VersionAwareStrategy]
    public class ProbeTestGrain : Grain, IProbeTestGrain
    {
        public Task<int> DivideByTwo(int input)
        {
            return Task.FromResult(input / 2);
        }
    }
```

The strategy is added to service:
```
services.AddSingleton<IPlacementDirector<VersionAwarePlacementStrategy>, VersionAwarePlacementDirector>();
```

When I try to build and connect the OrleansClient. Exception is thrown
```
Globals.OrleansClient = new ClientBuilder()
                .UseConfiguration(config)
                .AddServiceFabric(siloServiceUri)
                .AddClientInvokeCallback(CopyContextToOrleansContext)
                .Build();
            await Globals.OrleansClient.Connect();
```
```
System.TypeAccessException: 'Named type "ControlPlane.OrleansSafeUpgrade.VersionAwarePlacementStrategy" is invalid: Type string "ControlPlane.OrleansSafeUpgrade.VersionAwarePlacementStrategy" cannot be resolved.'

   at Orleans.Serialization.BinaryTokenStreamReader.ReadSpecifiedTypeHeader(SerializationManager serializationManager)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.OrleansCodeGenOrleans_Runtime_GrainClassDataSerializer.Deserializer(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeDictionary[K,V](Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.OrleansCodeGenOrleans_Runtime_GrainInterfaceMapSerializer.Deserializer(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, BinaryTokenStreamReader stream)
   at Orleans.Runtime.Message.DeserializeBody(SerializationManager serializationManager, List`1 bytes)
   at Orleans.Runtime.Message.GetDeserializedBody(SerializationManager serializationManager)
   at Orleans.Runtime.GrainReference.ResponseCallback(Message message, TaskCompletionSource`1 context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OutsideRuntimeClient.<StartInternal>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OutsideRuntimeClient.<Start>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.ClusterClient.<Connect>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Gaming.Common.OrleansUtil.OrleansWebFrontendDecorator.<InitializeOrleans>d__4.MoveNext() in E:\Enlistments\XCloud\XcloudSvc\src\Common\OrleansUtil\OrleansWebFrontendDecorator.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Gaming.Common.OrleansUtil.OrleansWebFrontendDecorator.BeforeCreateServiceListener() in E:\Enlistments\XCloud\XcloudSvc\src\Common\OrleansUtil\OrleansWebFrontendDecorator.cs:line 32
   at Microsoft.Azure.Gaming.Common.ServiceFabric.StatelessWebFrontend.CreateServiceInstanceListeners() in E:\Enlistments\XCloud\XcloudSvc\src\Common\ServiceFabric\StatelessFrontend.cs:line 34
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.<OpenCommunicationListenersAsync>d__20.MoveNext()
```

Am I missing anything?

**Comment by ReubenBond** [comment]
@yzhao174 the `VersionAwarePlacementStrategy` type must be accessible from the client, so include that in some shared assembly.

**Comment by yzhao174** [comment]
Thanks for the quick answer. Could you explain a little more? I do build VersionAwarePlacementStrategy in a separate assembly and include it in the silo service code. Do I need to include it somewhere else?

**Comment by ReubenBond** [comment]
@yzhao174 the stack trace is coming from your Web frontend, isn't it? It's complaining that it cannot deserialize the placement strategy.

In the current release of Orleans, the placement strategy types must be known to clients as well as silos.

**Comment by yzhao174** [comment]
Hmm. It works, thanks. But I have to explicitly load the assembly, for example by creating an object from that assembly. Otherwise it still throws the exception even that assembly is referenced.

**Comment by ReubenBond** [comment]
Thanks, @yzhao174. In the upcoming version 2.0 we've made assembly loading explicit so these kinds of issues should not arise.
