### ISSUE TITLE
Could not load file or assembly OrleansTestingHost

### ISSUE THREAD

**Issue by ifle** [dotnet/orleans#3690]
During initialization of TestCluster in Version=1.5.2.0, I have Could not load file or assembly error.
I have repro. You can download it
https://www.dropbox.com/s/keg8zmupvosodpq/ClassLibrary1.zip?dl=0

```C#
System.IO.FileNotFoundException : Could not load file or assembly 'OrleansTestingHost, Version=1.5.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Runtime.Serialization.FormatterServices.LoadAssemblyFromString(String assemblyName)
   at System.Reflection.MemberInfoSerializationHolder..ctor(SerializationInfo info, StreamingContext context)
   at System.AppDomain.remove_UnhandledException(UnhandledExceptionEventHandler value)
   at Orleans.TestingHost.AppDomainSiloHandle.UnloadAppDomain(AppDomain appDomain)
   at Orleans.TestingHost.AppDomainSiloHandle.Create(String siloName, SiloType type, ClusterConfiguration config, NodeConfiguration nodeConfiguration, IDictionary`2 additionalAssemblies, String applicationBase)
   at Orleans.TestingHost.TestCluster.StartOrleansSilo(TestCluster cluster, SiloType type, ClusterConfiguration clusterConfig, NodeConfiguration nodeConfig)
   at Orleans.TestingHost.TestCluster.<InitializeAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.TestingHost.TestCluster.<DeployAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Orleans.TestingHost.TestCluster.Deploy(IEnumerable`1 siloNames)
   at ClassLibrary1.Class1.Orleans_Test() in d:\Dev\ClassLibrary1\Class1.cs:line 19

----------------------------- STARTING NEW UNIT TEST SILO HOST: Orleans.TestingHost.TestCluster -------------------------------------
Starting a new silo in app domain Primary with config Config File Name: 
Host: TLV-PC-XXX
Start time: 2017-11-20 11:22:01.535 GMT
Primary node: 127.0.0.1:25580
Platform version info:
   Orleans version: 1.5.2.0 (Release).
   .NET version: 4.0.30319.42000
   OS version: Microsoft Windows NT 10.0.14393.0
   App config file: d:\Dev\ClassLibrary1\bin\Debug\ClassLibrary1.dll.config
   GC Type=Server GCLatencyMode=Interactive
Global configuration:
   System Ids:
      ServiceId: 00000000-0000-0000-0000-000000000000
      DeploymentId: testdepid-2017-11-20t11-22-01-25580-235
   Subnet: 
   Seed nodes: 127.0.0.1:25580
   Messaging:
       Response timeout: 00:00:30
       Maximum resend count: 0
       Resend On Timeout: False
       Maximum Socket Age: 10675199.02:48:05.4775807
       Drop Expired Messages: True
       Silo Sender queues: 8
       Gateway Sender queues: 8
       Client Drop Timeout: 00:01:00
       Buffer Pool Buffer Size: 4096
       Buffer Pool Max Size: 10000
       Buffer Pool Preallocation Size: 250
       Maximum forward count: 2
       Fallback serializer: 
   Liveness:
      LivenessEnabled: True
      LivenessType: MembershipTableGrain
      ProbeTimeout: 00:00:10
      TableRefreshTimeout: 00:01:00
      DeathVoteExpirationTimeout: 00:02:00
      NumMissedProbesLimit: 3
      NumProbedSilos: 3
      NumVotesForDeathDeclaration: 2
      UseLivenessGossip: True
      ValidateInitialConnectivity: True
      IAmAliveTablePublishTimeout: 00:05:00
      NumMissedTableIAmAliveLimit: 2
      MaxJoinAttemptTime: 00:05:00
      ExpectedClusterSize: 2
   MultiClusterNetwork: N/A
   SystemStore:
      SystemStore ConnectionString: UseDevelopmentStorage=true
      Reminders ConnectionString: UseDevelopmentStorage=true
   Application:
      Defaults:
         Deactivate if idle for: 02:00:00

   PlacementStrategy: 
         Default Placement Strategy: RandomPlacement
         Deployment Load Publisher Refresh Time: 00:00:01
         Activation CountBased Placement Choose Out Of: 2
   Grain directory cache:
      Maximum size: 1000000 grains
      Initial TTL: 00:00:30
      Maximum TTL: 00:04:00
      TTL extension factor: 2.00
      Directory Caching Strategy: Adaptive
   Grain directory:
      Lazy deregistration delay: 00:01:00
      Client registration refresh: 00:05:00
   Reminder Service:
       ReminderServiceType: ReminderTableGrain
   Consistent Ring:
       Use Virtual Buckets Consistent Ring: True
       Num Virtual Buckets Consistent Ring: 30
   Providers:
       No providers configured.
Silo configuration:
   Silo Name: Primary
   Generation: 0
   Host Name or IP Address: loopback
   DNS Host Name: TLV-PC-XXX
   Port: 25580
   Subnet: 
   Preferred Address Family: InterNetwork
   Proxy Gateway: 127.0.0.1:41635
   IsPrimaryNode: True
   Scheduler: 
         Max Active Threads: 8
         Processor Count: 8
         Delay Warning Threshold: 00:00:10
         Activation Scheduling Quantum: 00:00:00.1000000
         Turn Warning Length Threshold: 00:00:00.2000000
         Inject More Worker Threads: False
         MinDotNetThreadPoolSize: 200
         .NET thread pool sizes - Min: Worker Threads=8 Completion Port Threads=8
         .NET thread pool sizes - Max: Worker Threads=32767 Completion Port Threads=1000
         .NET ServicePointManager - DefaultConnectionLimit=200 Expect100Continue=False UseNagleAlgorithm=False
   Load Shedding Enabled: False
   Load Shedding Limit: 95
   SiloShutdownEventName: 
   Debug: 
   Tracing: 
     Default Trace Level: Info
     TraceLevelOverrides: None
     Trace to Console: True
     Trace File Name: 
     LargeMessageWarningThreshold: 85000
     PropagateActivityId: False
     BulkMessageLimit: 5
   Statistics: 
     MetricsTableWriteInterval: 00:00:30
     PerfCounterWriteInterval: 00:00:30
     LogWriteInterval: 00:05:00
     WriteLogStatisticsToTable: True
     StatisticsCollectionLevel: Info
```

**Comment by jdom** [comment]
I'll try to download the repro app to help troubleshoot, but the most likely case is that you are using a different version of some assembly than us, and it's missing a binding redirect.
Trying adding this to your test project's csproj:
```
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>  
<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType> 
```

Also, you might try troubleshooting using `fuslogvw.exe` to see exactly what failed to load and why

**Comment by ifle** [comment]
I've added the redirects directives to my csproj file and still have this error.

**Comment by ifle** [comment]
This error is only reproduced when using nunit. With xunit all works as expected.

**Comment by sergeybykov** [comment]
Looks like a nunit issue. I don't see what we can do here.
