### ISSUE TITLE
Pulling agent throwing exception when calling `DeliverBatch` in cluster mode

### ISSUE THREAD

**Issue by jonathansant** [dotnet/orleans#3699]
We have modified the existent `SQSStreamProvider` to accept custom messages from external producers to our Orleans system. We are using DynamoDb as a PubSubStore to persist stream subscriptions.

It appears that when we are running in a cluster of 4 servers, the messages start being dequeued but the `PersistentPullingAgent` starts throwing the following exceptions when trying to dispatch the message:

`Unexpected error sending message Request S10.0.2.6:10300:249048697???/84a63e80@S84a63e80->S10.0.2.5:10300:249048687*grn/E2A099FD/00000000+PLAYER-bc85eb85-e75e-43e3-9ca9-26c46e2105e3@bec1c2a2 #2743: global::Orleans.Streams.IStreamConsumerExtension:DeliverBatch()`

Is this indicative of something?

Since SQS messages are "read-once" do the silos (in a cluster) coordinate internally so that queues are dequeued by just one silo?

**Comment by sergeybykov** [comment]
Are there any other errors/warnings in the logs?

>Since SQS messages are "read-once" do the silos (in a cluster) coordinate internally so that queues are dequeued by just one silo?

Yes, there's a pluggable queue balancer component responsible for distributing queues across silos in the cluster.

**Comment by jonathansant** [comment]
Thanks for your reply,

> pluggable queue balancer

 is that something we need to configure or does it come out of the box?


other errors I'm observing:
`Exception while trying to deliver msgs to stream prod-hrzn-common-balances-v1-7032d660-c36a-5ec2-913e-79e13f2c79bc-BigDataProvider in PersistentStreamPullingAgentGrain.RunConsumerCursor`

`Unexpected error sending message NewPlacement Request S10.0.1.4:10300:248972412???/b1f195a0@Sb1f195a0->S10.0.1.6:10300:248972412*grn/E2A099FD/00000000+PLAYER-b5054c53-24ae-43e1-9f01-a3a2aaf1ac48@1469c08c #8526: global::Orleans.Streams.IStreamConsumerExtension:DeliverBatch()`

**Comment by sergeybykov** [comment]
>is that something we need to configure or does it come out of the box?

You get the default one if you don't configure anything, which is good for most cases.

**Comment by sergeybykov** [comment]
>Unexpected error sending message NewPlacement Request S10.0.1.4:10300:248972412???/b1f195a0@Sb1f195a0->S10.0.1.6:10300:248972412*grn/E2A099FD/00000000+PLAYER-b5054c53-24ae-43e1-9f01-a3a2aaf1ac48@1469c08c #8526: global::Orleans.Streams.IStreamConsumerExtension:DeliverBatch()

Is there something in the logs of `10.0.1.6:10300` correlated with this error?

**Comment by jonathansant** [comment]
Can you please point me to some reading about the queue balancer or provide some more detail. Thanks in advance.

**Comment by jonathansant** [comment]
> Is there something in the logs of 10.0.1.6:10300 correlated with this error?

Ran some more tests (with new deployments) and I am getting the following on one server:

`Unexpected error sending message Request S10.0.2.8:10300:249074997???/0e822fb1@S0e822fb1->S10.0.2.12:10300:249074980*grn/E2A099FD/00000000+PLAYER-6bd73638-5ed3-43c2-88a8-28c45b7477ac@f79e7d97 #4681: global::Orleans.Streams.IStreamConsumerExtension:DeliverBatch()`

`Exception while trying to deliver msgs to stream staging-hrzn-common-balances-v1-19531cec-1f24-5135-94e3-a1bbe71eed29-BigDataProvider in PersistentStreamPullingAgentGrain.RunConsumerCursor`

and on the other silo I get the following in the `OnError` for the stream subscription/resume:
`Stream provider failed to deliver an event. StreamProvider:BigDataProvider Stream:staging-hrzn-common-balances-v1-19531cec-1f24-5135-94e3-a1bbe71eed29-BigDataProvider`

Running locally in debug works so it _seems_ that it isn't in user logic to process the message. On the server, it works with one silo but not with multiple.

**Comment by xiazen** [comment]
Most documentation for queue balancer is in xml comment on code. I pasted as follows.

in Orleans.Streams.StreamQueueBalancerType class
 ```
/// <summary>
        /// Stream queue balancer that uses consistent ring provider for load balancing
        /// </summary>
        public static Type ConsistentRingBalancer = typeof(ConsistentRingQueueBalancer);

        /// <summary>
        /// Stream queue balancer that uses the cluster configuration to determine deployment information for load balancing.  
        /// It does not support dynamic changes to global (full) cluster configuration.
        /// This Balancer does use the information from Membership oracle about currently active (alive) silos 
        /// and rebalances queues from non active silos.
        /// </summary>
        public static Type DynamicClusterConfigDeploymentBalancer = typeof(DynamicClusterConfigDeploymentBalancer);

        /// <summary>
        /// Stream queue balancer that uses the cluster configuration to determine deployment information for load balancing.  
        /// It does not support dynamic changes to global (full) cluster configuration.
        /// This Balancer does NOT use the information from Membership oracle about currently active silos.
        /// That is, it does not rebalance queues based on dymanic changes in the cluster Membership.
        /// </summary>
        public static Type StaticClusterConfigDeploymentBalancer = typeof(StaticClusterConfigDeploymentBalancer);

        /// <summary>
        /// Stream queue balancer that uses the cluster configuration to determine deployment information for load balancing.  
        /// This balancer supports queue balancing in cluster auto-scale scenario, unexpected server failure scenario, and try to support ideal distribution 
        /// </summary>
        public static Type ClusterConfigDeploymentLeaseBasedBalancer = typeof(ClusterConfigDeploymentLeaseBasedBalancer);
```
in Orleans.Streams.Azure.StreamQueueBalancerType class
 ```
public class StreamQueueBalancerType
    {
        /// <summary>
        /// Stream queue balancer that uses Azure deployment information and silo statuses from Membership oracle for load balancing.  
        /// Requires silo running in Azure.
        /// This Balancer uses both the information about the full set of silos as reported by Azure role code and 
        /// the information from Membership oracle about currently active (alive) silos and rebalances queues from non active silos.
        /// </summary>
        public static Type DynamicAzureDeploymentBalancer = typeof(DynamicAzureDeploymentBalancer);

        /// <summary>
        /// Stream queue balancer that uses Azure deployment information for load balancing. 
        /// Requires silo running in Azure.
        /// This Balancer uses both the information about the full set of silos as reported by Azure role code but 
        /// does NOT use the information from Membership oracle about currently alive silos. 
        /// That is, it does not rebalance queues based on dymanic changes in the cluster Membership.
        /// </summary>
        public static Type StaticAzureDeploymentBalancer = typeof(StaticAzureDeploymentBalancer);

        /// <summary>
        ///  Stream queue balancer that uses Azure deployment information for load balancing. 
        /// Requires silo running in Azure.
        /// This balancer supports queue balancing in cluster auto-scale scenario, unexpected server failure scenario, and try to support ideal distribution 
        /// </summary>
        public static Type AzureDeploymentLeaseBasedBalancer = typeof(AzureDeploymentLeaseBasedBalancer);
    }
```

The default is `ConsistentRingBalancer`, which use consistent hashing algorithm to balance queue to silos. It balance well if the queue count is big , compared to silo count relatively. How many queues in your cluster?

**Comment by xiazen** [comment]
Your error message doesn't seem like to be queue balancer related. It seem more delivery related, in pulling agents. Do you see any stack trace for the delivery exception?

**Comment by xiazen** [comment]
You are also welcome to attach the log files, in which you see those exceptions.

**Comment by jonathansant** [comment]
Unfortunately, stack traces are `null`. Not sure if it's a problem with our logging system or they're actually null. 

Any pointers as to what might cause a delivery failure in a cluster? I would put my two cents would on serialization but I'm not sure.

Any recommendations where we can add more logging within our `StreamProvider` implementation?
e.g.: `SqsAdapterReceiver`, `SqsBatchContainer`

**Comment by jonathansant** [comment]
[logs.zip](https://github.com/dotnet/orleans/files/1497597/logs.zip)

**Comment by jonathansant** [comment]
We also ran some more tests and now we are a 100% sure that the issue occurs when the silo in charge of the queue is different than the silo that hosts the grain. We have seen logs where the grains where spawned on the same silo and it was working just fine.

**Comment by sergeybykov** [comment]
@jonathansant Is it possible that the events you are sending aren't serializable?

**Comment by xiazen** [comment]
You can add some logging to your `ICacheDataAdapter`, especially where it deserialize a cached message to a batch container for delivery.

**Comment by jonathansant** [comment]
They're  json strings.

**Comment by jonathansant** [comment]
I have set up a local cluster on my machine and I couldn't replicate the error. I have now set it up on to machines at the office. and I may be replicating the issue. Below is an exception I'm currently getting which is still somewhat cryptic. 

Will update later on with more results.

```
Orleans.Runtime.Silo[100102]
      Silo caught an UnobservedException with context==null.
System.InvalidOperationException: The underlying collection was modified from outside of the BlockingCollection<T>.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.<GetConsumingEnumerable>d__68.MoveNext()
   at Microsoft.Extensions.Logging.Console.Internal.ConsoleLoggerProcessor.ProcessLogQueue()
   at Microsoft.Extensions.Logging.Console.Internal.ConsoleLoggerProcessor.ProcessLogQueue(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
fail: Orleans.UnobservedExceptionsHandlerClass[100005]
      UnobservedExceptionsHandlerClass Caught an UnobservedTaskException event sent by [Id=88319, Status=Faulted]. Exception =
      Exc level 0: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The underlying collection was modified from outside of the BlockingCollection<T>.)
      Exc level 1: System.InvalidOperationException: The underlying collection was modified from outside of the BlockingCollection<T>.
         at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
         at System.Collections.Concurrent.BlockingCollection`1.<GetConsumingEnumerable>d__68.MoveNext()
         at Microsoft.Extensions.Logging.Console.Internal.ConsoleLoggerProcessor.ProcessLogQueue()
         at Microsoft.Extensions.Logging.Console.Internal.ConsoleLoggerProcessor.ProcessLogQueue(Object state)
         at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
fail: Orleans.UnobservedExceptionsHandlerClass[100006]
      Exception remained UnObserved!!! The subsequent behavior depends on the ThrowUnobservedTaskExceptions setting in app config and .NET version.
```

**Comment by jonathansant** [comment]
Pasting the actual exception thrown by the silo (as already mentioned the events in the BatchContainer are strings):

```
Unexpected error sending message Request S10.81.1.123:10300:249591904???/b2dccca5@Sb2dccca5->S10.81.1.148:10300:249590549*grn/E2A099FD/00000000+PLAYER-e90666ac-63df-429c-898a-c826549c88a7@65b38eb7 
#108: global::Orleans.Streams.IStreamConsumerExtension:DeliverBatch()
System.ArgumentException: No serializer found for object of type Action from assembly System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e. 
Perhaps you need to mark it [Serializable] or define a custom serializer for it?
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Task`1Serializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at WinHttpRequestStateSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at CancellationCallbackInfoSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeArray(Array array, ISerializationContext context, Type expected, Type et)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at SparselyPopulatedArrayFragment`1Serializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at SparselyPopulatedArray`1Serializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeArray(Array array, ISerializationContext context, Type expected, Type et)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Linked1CancellationTokenSourceSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at CancellationCallbackInfoSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeArray(Array array, ISerializationContext context, Type expected, Type et)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at SparselyPopulatedArrayFragment`1Serializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at SparselyPopulatedArray`1Serializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeArray(Array array, ISerializationContext context, Type expected, Type et)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at CancellationTokenSourceSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at HttpClientSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeArray(Array array, ISerializationContext context, Type expected, Type et)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at HttpClientCacheSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at UnmarshallerSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at ErrorHandlerSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at CallbackHandlerSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at SignerSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at CredentialsRetrieverSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at RetryHandlerSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at CallbackHandlerSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at EndpointResolverSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at MarshallerSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at CallbackHandlerSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at ErrorCallbackHandlerSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at MetricsHandlerSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at RuntimePipelineSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at AmazonCloudWatchLogsClientSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at CloudWatchLogSinkSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeArray(Array array, ISerializationContext context, Type expected, Type et)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at SerilogLoggerSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at LoggerInformationSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeArray(Array array, ISerializationContext context, Type expected, Type et)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at SqsBatchContainerSerializer(Object , ISerializationContext , Type )
   at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.BuiltInTypes.SerializeImmutable[T](Object original, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.BuiltInTypes.SerializeInvokeMethodRequest(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.Serialize(Object raw, IBinaryTokenStreamWriter stream)
   at Orleans.Runtime.Message.Serialize(SerializationManager serializationManager, Int32& headerLengthOut, Int32& bodyLengthOut)
   at Orleans.Messaging.OutgoingMessageSender.Process(Message msg)
```

**Comment by xiazen** [comment]
Looks like some type from System.Private.CoreLib in your batch container implementation is not serializable. If that type does not to be serialized, you can mark it as `NonSerialized`.

**Comment by ReubenBond** [comment]
@jonathansant I *believe* that your modified `SqsBatchContainer` has a field to hold some kind of logger, but that field is not marked as `[NonSerialized]`. Please add that attribute and try again.

**Comment by jonathansant** [comment]
@ReubenBond  indeed it was the logger thanks for your help
