### ISSUE TITLE
JsonSerialisationException on activating grain using sql storage

### ISSUE THREAD

**Issue by rikbosch** [dotnet/orleans#3706]
Hi,

We (sometimes) receiving this exception, when activating a Grain, which state has a reference to another grain.

```csharp
OrleansMessageRejectionException: Forwarding failed: tried to forward message NewPlacement Request S127.0.0.1:30053:249064824*cli/87c06cbf@141c1cba->S127.0.0.1:30053:249064824*grn/AED0BD6F/00000000+email-SYSADMIN@e16d9fb5 #20[ForwardCount=2]: global::Ao.Core.Grains.Interfaces.Identity.IGrainIndexGrain<TGrainType>:Get() for 2 times after Failed SetupActivationState to invalid activation. Rejecting now. Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'Ao.Core.Grains.Interfaces.Identity.OrleansCodeGenUserGrainReference, Ao.Core.Grains.Interfaces'. Path 'Grain.$type', line 1, position 190. ---> Newtonsoft.Json.JsonSerializationException: Could not find type 'Ao.Core.Grains.Interfaces.Identity.OrleansCodeGenUserGrainReference' in assembly 'Ao.Core.Grains.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(TypeNameKey typeNameKey)
at Newtonsoft.Json.Utilities.ThreadSafeStore`2.AddValue(TKey key)
at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
--- End of inner exception stack trace ---
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Orleans.Serialization.GrainReferenceConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Orleans.Storage.AdoNetStorageProvider.<>c__DisplayClass42_0.<<ReadStateAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.SqlUtils.RelationalStorage.<SelectAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.SqlUtils.RelationalStorage.<ExecuteReaderAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.SqlUtils.RelationalStorage.<ExecuteAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.SqlUtils.RelationalStorage.ReadAsync[TResult](String query, Action`1 parameterProvider, Func`4 selector, CancellationToken cancellationToken, CommandBehavior commandBehavior)
at Orleans.Storage.AdoNetStorageProvider.<ReadStateAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Catalog.<SetupActivationState>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Catalog.<InitActivation>d__66.MoveNext()
```

this is the state stored in the storage table:

```json
{
    "$id": "1",
    "$type": "Ao.Core.Grains.Identity.IndexGrainState, Ao.Core.Grains",
    "Grain": {
        "$type": "Ao.Core.Grains.Interfaces.Identity.OrleansCodeGenUserGrainReference, Ao.Core.Grains.Interfaces",
        "GrainId": "0000000000000000000000000000000006ffffffbabf2644+user-27a072d8-a17c-4f4a-bd03-26c415f0c951",
        "GenericArguments": ""
    }
}
```

**Comment by ReubenBond** [comment]
@rikbosch I assume this is no longer an issue. Sorry that I didn't get to this in a reasonable amount of time. Did you manage to resolve it, or is it ancient history?

**Comment by rikbosch** [comment]
We resolved it by explicitly saving AsReference() in the state.
