### ISSUE TITLE
Is Dictionary<T1,T2> a supported property type for object transmitted via Orleans Streams?

### ISSUE THREAD

**Issue by Kimserey** [dotnet/orleans#3815]
Is `Dictionary<T1,T2>` a supported property type for object transmitted via Orleans Streams?

After adding a dictionary in my object, I am having the following warning after emitting a new event to the stream via `_myStream.OnNextAsync(...)`:

```
warn: Runtime.Messaging.GatewaySender/GatewaySiloSender_0[101029]
      Unexpected error serializing message Response S127.0.0.1:40000:0*grn/7922BDF8/26cc54b8@8cb8bc9f->*cli/2467f0b4@9f8fcb91 #5: global::OrleansNetCoreTest.Interfaces.IBankAccount:Deposit() on the gateway
System.Runtime.Serialization.SerializationException: Type 'System.NullReferenceException' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Boolean check)
   at Orleans.Serialization.BinaryFormatterSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.Serialize(Object raw, IBinaryTokenStreamWriter stream)
   at Orleans.Runtime.Message.Serialize(SerializationManager serializationManager, Int32& headerLengthOut, Int32& bodyLengthOut)
   at Orleans.Runtime.Messaging.Gateway.GatewaySender.Send(Message msg, Socket sock)
```

Here is my object:

```    
    public enum TransactionType
    {
        Credit,
        Debit
    }

    public class TransactionEvent
    {
        public TransactionType Type { get; set; }
        public double Amount { get; set; }
        public Dictionary<string, string> Data { get; set; }
    }
```

**Comment by jason-bragg** [comment]
Some quick questions:
What version of Orleans are you using?
What stream provider are you using?

@ReubenBond is more familiar with our serialization logic, but I believe you'll need to mark your data type as serializable.

    [Serializable]
    public class TransactionEvent
    {
        ...
    }

And if you still see issues try explicitly marking the type for serializer codegen.

    [assembly: GenerateSerializer(typeof(TransactionEvent))]

**Comment by Kimserey** [comment]
I am not sure what happened but it seems to work now. I will close it for now thanks a lot!

----

Regardless I will still provide the information:

> What version of Orleans are you using?

Orleans 2.0 beta 2

> What stream provider are you using?

AddAzureQueueStreamProviderV2

```
config.AddAzureQueueStreamProviderV2("my-provider", connectionString: "UseDevelopmentStorage=true");
```

> I believe you'll need to mark your data type as serializable

I tried (but now it doesn't matter, it works without specifying any attribute)
