### ISSUE TITLE
[Question] - IExternalSerializer issue

### ISSUE THREAD

**Issue by dazinator** [dotnet/orleans#3882]
Just seeking some advice on how to get to the bottom of this problem.
I can see my custom serialiser is serialising my object on the client side, and deserialising it on the server side.
I can see my grain is then activated on the server side.
However after activation, my grain method on the server side is not actually invoked. The client instead reports an exception. I can't find anywhere to intercept this exception which I assume is happening on the server side but I am not sure. The stack trace isn't particularly hepful:

```
> Result StackTrace:	
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OrleansTaskExtentions.<<ToTypedTask>g__ConvertAsync4_0>d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Csla.Orleans.OrleansDataPortalProxy.<Update>d__8.MoveNext() in C:\Users\Darrell\Source\Repos\Csla.Orleans\src\Csla.Orleans\OrleansDataPortalProxy.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.DataPortal`1.<DoUpdateAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.DataPortal`1.<UpdateAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.DataPortal.<UpdateAsync>d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.BusinessBase`1.<SaveAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.BusinessBase`1.<SaveAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.BusinessBase`1.<SaveAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Csla.Orleans.Tests.ConfigureTests.<Can_Create>d__4.MoveNext() in C:\Users\Darrell\Source\Repos\Csla.Orleans\Csla.Orleans.Tests\ConfigureTests.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
```

My serialiser only deserialises types that implement a particular interface `IMobileObject`. I have noticed other types like `InvokeRequest` which are orleans types, that my serialiser returns `false` for when orlenas asks it if it can serialise them. Because of this my serialiser only takes responsibility for serialising the types that I am interested in - I am assuming that this is ok because the fallback serialisation methods will handle those other types?

I guess I am just wondering how I go about diagnosing why the grain method isn;t being invoked - how can I get some more detailed information? Starting with whether the server is reporting the exception (as I suspect as it happens after grain activation) or whether it purely happening on the client side.

**Comment by ReubenBond** [comment]
> Because of this my serialiser only takes responsibility for serialising the types that I am interested in - I am assuming that this is ok because the fallback serialisation methods will handle those other types?

Yes, you've done the right thing :)

Do you see logs on the server? You ought to be able to see exceptions there.

This doesn't necessarily look like a serialization issue to me - there's a NullReferenceException in your stack dump but I don't see serialization in the stack.

Could you run the test under a debugger with the option to catch First Chance Exceptions?

By the way, this line here is incorrect: you should call connect once for each client and the client should be shared with all consumers in your application and should live for the duration of your application.
https://github.com/dazinator/Csla.Orleans/blob/e10bbbd77e5cd93931e702b31a6ee51a49eea337/src/Csla.Orleans/OrleansDataPortalProxy.cs#L22

The client will throw if you try to initialize it multiple times

**Comment by dazinator** [comment]
@ReubenBond Thanks for the pointers, I will try these things out in a few days time.

**Comment by dazinator** [comment]
So I have the logs from the server now, having set up serilog.

The relevent section is here:

```
Exception during Grain method call of message: NewPlacement Request S127.0.0.1:11111:254107003*cli/34188fbf@7ae369b7->S127.0.0.1:11111:254107003*grn/DF38DBB6/00000000@cac41586 #4: global::Csla.Orleans.IOrleansGrainDataPortalServer:Update()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Csla.Orleans.OrleansCodeGenOrleansGrainDataPortalServerMethodInvoker.<Invoke>d__0.MoveNext() in C:\Users\darre\Source\Repos\Csla.Orleans\src\Csla.Orleans\obj\Debug\netstandard2.0\Csla.Orleans.orleans.g.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.GrainMethodInvoker.<Invoke>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.InsideRuntimeClient.<Invoke>d__72.MoveNext()
```

The full log is here: https://gist.github.com/dazinator/607b5bc8e1b16644faf60e13a236b1bd

It looks like the problem is happening in the generate .g.cs file.

**Comment by dazinator** [comment]
Ok I have found my problem... I should slap myself in the face.

My orleans serialiser is writing a long for the size, but then reads an int! subsequently the bytes are off by 4 bits when it tries to deserialise the message..

:-(

**Comment by dazinator** [comment]
All working nicely.. Thanks for your patience. It all turned out to be a fault in my serialiser :-)

**Comment by ReubenBond** [comment]
Just glad that you god it sorted, @dazinator :)
