### ISSUE TITLE
Could not load file or assembly 'OrleansAWSUtils, Culture=neutral, PublicKeyToken=null' on macOS High Sierra with dotnet core

### ISSUE THREAD

**Issue by Kimserey** [dotnet/orleans#3985]
I am trying to run a **Silo** with the following configuration:

- AWS utils for MembershipTableAssembly
- System: macOS
- dotnet core

But I am getting a `FileNotFoundException` exception even though the .dll is definitely referenced.

Here is the code for the silo:

```
var config = new ClusterConfiguration();

config.Globals.LivenessType = GlobalConfiguration.LivenessProviderType.Custom;
config.Globals.MembershipTableAssembly = "OrleansAWSUtils";

config.Globals.RegisterStorageProvider<DynamoDBStorageProvider>(
      "Default",
      new Dictionary<string, string> {
            { "DataConnectionString", "Service=http://localhost:8000" },
            { "UseJsonFormat", "true" }
      });

var silo = SiloHostBuilder.CreateDefault()
        .UseConfiguration(config)
        .ConfigureApplicationParts(a =>
              a.AddApplicationPart(typeof(User).Assembly)
                   .WithReferences())
        .UseDynamoDBMembership((DynamoDBMembershipOptions opt) => {
              opt.ConnectionString = "Service=http://localhost:8000"
         })
        .ConfigureLogging(b => b.AddConsole())
        .Build();

silo.StartAsync().Wait();
```

And am getting the following error:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'OrleansAWSUtils, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Orleans.Messaging.LegacyGatewayListProviderConfigurator.CreateInstanceWithParameterlessConstructor[T](String assemblyName)
   at Orleans.Runtime.MembershipService.LegacyMembershipConfigurator.ConfigureServices(GlobalConfiguration configuration, IServiceCollection services)
   at Orleans.Hosting.LegacyClusterConfigurationExtensions.AddLegacyClusterConfigurationSupport(IServiceCollection services, ClusterConfiguration configuration)
   at Orleans.Hosting.CoreHostingExtensions.<>c__DisplayClass3_0.<UseConfiguration>b__0(HostBuilderContext context, IServiceCollection services)
   at Orleans.Hosting.ServiceProviderBuilder.BuildServiceProvider(HostBuilderContext context)
   at Orleans.Hosting.SiloHostBuilder.Build()
   at AWSOrleansTest.Program.Main(String[] args) in /Users/kim.lam/Projects/aws-orleans-test/AWSOrleansTest/Program.cs:line 29
```

**Comment by sergeybykov** [comment]
In 2.0.0-beta3 we've broken OrleansAWSUtils.dll into 4 separate assemblies for clustering, persistence, reminders, and streaming. OrleansAWSUtils is just a meta-package now, and there's no OrleansAWSUtils.dll anymore. For cluster membership, it should be Orleans.Clustering.DynamoDB now.

**Comment by Kimserey** [comment]
Perfect,
