### ISSUE TITLE
New grain Implementation is not loaded after its first upgrade

### ISSUE THREAD

**Issue by yzhao174** [dotnet/orleans#4028]
We are running Orleans 2.0 on ServiceFabric cluster. When we try to add a new interface/implementation of a grain or change the name of existing interface/implementation, it will fail with error message:

> {"error":{"innererror":"System.ArgumentException: Cannot find an implementation class for grain interface: Fog.GrainInterfaces.IFogFailureManagementGrain. Make sure the grain assembly was correctly deployed and loaded in the silo.
  at Orleans.GrainFactory.GetGrainClassData(Type interfaceType, String grainClassNamePrefix)
  at Orleans.GrainFactory.GetGrain[TGrainInterface](Guid primaryKey, String grainClassNamePrefix)
  at Orleans.ClusterClient.GetGrain[TGrainInterface](Guid primaryKey, String grainClassNamePrefix)
  at Fog.GrainInterfaces.GrainFactoryExtension.GetFogFailureManagementGrainReference(IGrainFactory grainFactory, Guid key) in C:\\BA\\185\\s\\src\\ControlPlane\\Fog.GrainInterfaces\\GrainFactoryExtension.cs:line 37
  at Fog.Frontend.Controllers.BatchController.ThrowIfFailureOn(AzureRegion regionId, String accountName, String poolId, String methodName) in C:\\BA\\185\\s\\src\\ControlPlane\\Fog.Frontend\\Controllers\\BatchController.cs:line 49
  at Fog.Frontend.Controllers.BatchController.<CreatePool>d__6.MoveNext() in C:\\BA\\185\\s\\src\\ControlPlane\\Fog.Frontend\\Controllers\\BatchController.cs:line 186\r\n--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Gaming.Common.WebApi.RootMessageHandler.<SendAsync>d__5.MoveNext() in C:\\BA\\185\\s\\src\\Common\\Common.WebApi\\RootMessageHandler.cs:line 52","code":null,"message":null}}

3 scenarios:
1. If we deploy the new code cleanly from scratch, everything is working
2. If we have old version in ServiceFabric and we make an upgrade with this new version, then new grain is not loaded
3. If we have old version in ServiceFabric and we make an upgrade with this new version, and upgrade again, everything is working. New grain is loaded. This is just to make the same upgrade twice.

**Comment by yzhao174** [comment]
Have you found the root cause of this? Is there any setting of cache that could have been missed out?

**Comment by benjaminpetit** [comment]
When you say you are changing the name of the interface/implementation, do you use the `TypeCodeOverrideAttribute` to force the type code that was computed with the previous naming? Otherwise it's expected that you will break things.

Do you reproduce this issue locally (without SF)?

**Comment by yzhao174** [comment]
Our project deploys to ServiceFabric cluster. The issue only happens when we make an upgrade from one version to another that has interface name change or new interface name. We don't reproduce it locally as we cannot perform the upgrade action.
Is it recommended that all Grain interface and Grain classes to have TypeCodeOverrideAttribute? Do you have an example of using TypeCodeOverrideAttribute?

**Comment by benjaminpetit** [comment]
I don't think we have any doc/sample on that, it's a pretty advanced topic.

`TypeCodeOverrideAttribute` should be used when you want to change the name of existing grain interfaces/implementation.

In Orleans, grain interfaces and implementations are identified by their type code. This type code is a basically a hash of the interface/class name. So if you are changing the name, the type code change.

In your situation, yes, you should force the TypeCode, but you should be careful to not create a type code conflict (two interfaces/class with the same type code)

**Comment by yzhao174** [comment]
So basically I need to put TypeCodeOverrideAttribute on all GrainInterface to make sure they don't conflict. Does it only apply to Interface, or it has to be on both interface and class? Does interface and class share the same type code or different?

Another thing I still don't understand. This happens after the upgrade completes. Theoretically, when upgrade completes, which means all silos and clients have restarted, they would load the new type code, right?  Or is the typecode stored in external storage like storage account?

**Comment by ReubenBond** [comment]
Orleans cannot tell if `IMyGrainOne` and `IMyGrainTwo` are unrelated or if one was renamed to the other at some point. There's no algorithm which could reliably identify that without somehow storing something in your source code to indicate that it was renamed. It just appears like another grain.

Type codes aren't stored anywhere explicitly, but they're part of the grain id, so they're included in `GrainReference`s.

Interfaces and classes do not share the same type code. You should give each a different type code.

Hope that helps

**Comment by yzhao174** [comment]
Thanks to both your answers. That helps me understand the grain mapping. Then what happens to a new grain type? It's not renaming, but a completely new grain interface and class. Why it is still not loaded, or at least not detected by the runtime, after upgrade.

**Comment by yzhao174** [comment]
Ok. It's very interesting. I found after the first grain code upgrade in service fabric cluster, I only need to restart each node again to make Orleans load the new grain type. So what happens is:
1) I initiate the upgrade
2) ServiceFabric goes though each node one by one, shutting down silo and restarting silo with new code
3) After upgrade, theoretically each node is running the new code and the services have been all restarted. But the grain type is not loaded
4) I manually restart all the nodes again
5) Then everything is working. Grain type is loaded

I am wondering if the grain type is cached somewhere outside the silo, like registerykey or network cache?

**Comment by benjaminpetit** [comment]
What do you mean by "but the grain type is not loaded"?

**Comment by yzhao174** [comment]
3. After upgrade, theoretically each node is running the new code and the services have been all restarted. But the grain type is not loaded.
I mean it throws exception "Cannot find an implementation class for grain interface"

**Comment by hanxinimm** [comment]
I have the same Exception 

Cannot find an implementation class for grain interface: Labor.Public.IQueryHandler.IAdvertiseQueryHandler. Make sure the grain assembly was correctly deployed and loaded in the silo.C:\SfDevCluster\Data\_App\_Node_0\PublicAppType_App10\StatelessWebApiQueryServicePkg.Code.1.0.0\StatelessWebApiQueryService.dll

**Comment by benjaminpetit** [comment]
Took it offline with @yzhao174 

The issue is that if you try to update both silo and client at the same time, new clients are more likely to start before the new silos, so they get an outdated typemap.

Since we don't refresh the typemap on the clients, you have to restart them to get a typemap up-to-date. I will open an issue to see if it makes sense to implement a mechanism to refresh it on clients.
