### ISSUE TITLE
Could not load type 'Orleans.ObserverSubscriptionManager`1' from assembly 'Orleans.Core, Version=2.0.0.0

### ISSUE THREAD

**Issue by KTazayan** [dotnet/orleans#4094]
I'm getting exception described below when try to use client observers (the simple implementation as described here https://dotnet.github.io/orleans/Documentation/Getting-Started-With-Orleans/Observers.html).
`System.TypeLoadException: Could not load type 'Orleans.ObserverSubscriptionManager`1' from assembly 'Orleans.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at GrainCollection.Office365PurchaseTransaction.<OnActivateAsync>d__2.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at GrainCollection.Office365PurchaseTransaction.OnActivateAsync()
   at Orleans.Grain.<Participate>b__31_0(CancellationToken ct)
   at Orleans.LifecycleExtensions.Observer.OnStart(CancellationToken ct)
   at Orleans.LifecycleObservable.<WrapExecution>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.LifecycleObservable.<OnStart>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Orleans.Runtime.Catalog.<CallGrainActivate>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.<Execute>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<InitActivation>d__61.MoveNext()
info: Orleans.Runtime.Dispatcher[101033]`

I'm using v2.0.0-rc1 version hosted in .NET Core console application. If ObserverSubscriptionManager is obsolete and moved to the legacy package as described here https://github.com/dotnet/orleans/pull/3999 and isn't works correctly with the new version of framework

What approach I should use to be able to use push-based model for notifications from the cluster to the client?

**Comment by ReubenBond** [comment]
@KTazayan it sounds as though either not all of the assemblies were updated to 2.0.0-rc1 or there's something stale in the build output. Could you double check that everything has been upgraded and then run a full clean and try again?

**Comment by sergeybykov** [comment]
Does look like a version mismatch to me - a project thinks that `ObserverSubscriptionManager` is in `Orleans.Core`, where it used to be, while it is actually in `Orleans.Core.Legacy` now.

**Comment by ReubenBond** [comment]
Users generally favor streams for pushing to clients, but either way is fine in my opinion.

**Comment by KTazayan** [comment]
Ok, thank you.
