### ISSUE TITLE
Docker Deployment Client Connection Failed

### ISSUE THREAD

**Issue by beckjin** [dotnet/orleans#4125]
I Follow the Sample:

https://github.com/dotnet/orleans/tree/master/Samples/2.0/docker-aspnet-core

Silo has been successful, but the client connection failed

![image](https://user-images.githubusercontent.com/7261408/36946992-d457a3b2-2000-11e8-9fb9-99eabc37296d.png)

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (The target silo became unavailable for message: Request *cli/193b298f@0e75cbb3->S172.22.0.3:30000:257871284*stg/17/00000011@S00000011 #2: . Target History is: <S172.22.0.3:30000:257871284:*stg/17/00000011:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Client.Program.Main(String[] args) in D:\jinbiao\OrleansSamples\OrleansDocker\Client\Program.cs:line 34

内部异常 1:
SiloUnavailableException: The target silo became unavailable for message: Request *cli/193b298f@0e75cbb3->S172.22.0.3:30000:257871284*stg/17/00000011@S00000011 #2: . Target History is: <S172.22.0.3:30000:257871284:*stg/17/00000011:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.

**Comment by benjaminpetit** [comment]
Could you share your config?

**Comment by beckjin** [comment]
Silo:
```
namespace Silo
{
    class Program
    {
        private static ISiloHost silo;
        private static readonly ManualResetEvent siloStopped = new ManualResetEvent(false);

        static void Main(string[] args)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("Config/appsettings.json", false, true);
            var configuration = builder.Build();

            silo = new SiloHostBuilder()
                 .Configure(options => options.ClusterId = configuration.GetSection("ClusterId").Value)
                 .UseAdoNetClustering(options =>
                 {
                     options.AdoInvariant = "System.Data.SqlClient";
                     options.ConnectionString = configuration.GetSection("ConnectionString").Value;
                 })
                 .ConfigureEndpoints(siloPort: 11111, gatewayPort: 30000)
                 .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(HelloGrain).Assembly).WithReferences())
                 .ConfigureLogging(log => log.SetMinimumLevel(LogLevel.Warning).AddConsole())
                 .Build();

            Task.Run(StartSilo);

            AssemblyLoadContext.Default.Unloading += context =>
            {
                Task.Run(StopSilo);
                siloStopped.WaitOne();
            };
            siloStopped.WaitOne();
        }

        private static async Task StartSilo()
        {
            await silo.StartAsync();
            Console.WriteLine("Silo started");
        }

        private static async Task StopSilo()
        {
            await silo.StopAsync();
            Console.WriteLine("Silo stopped");
            siloStopped.Set();
        }
    }
}
```

Client:
```
namespace Client
{
    class Program
    {
        static void Main(string[] args)
        {
            var builder = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("Config/appsettings.json", false, true);
            var configuration = builder.Build();

            var client = new ClientBuilder()
               .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IHelloGrain).Assembly))
               .ConfigureCluster(options =>  options.ClusterId = configuration.GetSection("ClusterId").Value)
               .UseAdoNetClustering(options =>
               {
                   options.AdoInvariant = "System.Data.SqlClient";
                   options.ConnectionString = configuration.GetSection("ConnectionString").Value;
               })
               .Build();

            StartClientWithRetries(client).Wait();

            var friend = client.GetGrain<IHelloGrain>(0);
            for (int i = 0; i < 10; i++)
            {
                var response = friend.SayHello("Good morning, my friend" + i).Result;
                Console.WriteLine("\n{0}\n", response);
                Thread.Sleep(500);
            }
            Console.ReadLine();
        }

        private static async Task StartClientWithRetries(IClusterClient client)
        {
            for (var i = 0; i < 5; i++)
            {
                try
                {
                    await client.Connect();
                    return;
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
                await Task.Delay(TimeSpan.FromSeconds(5));
            }
        }
    }
}

```

appsettings.json:
```
{
  "ConnectionString": "Data Source=.;Database=OrleansStorage;User ID=sa;Password=123456;Pooling=true;Max Pool Size=32767;Min Pool Size=0;",
  "ClusterId": "orleans-docker"
}
```

**Comment by beckjin** [comment]
@benjaminpetit , Is there any progress in this problem?

**Comment by beckjin** [comment]
![default](https://user-images.githubusercontent.com/7261408/37875963-bee64988-3078-11e8-85fb-3717d0679957.PNG)

This is the address inside the docker, so it should not be connected.

**Comment by benjaminpetit** [comment]
Client and silo should be on the same network layer in Docker. If it is not possible, you could setup manually the published IP/port in the silo builder, and use port forwarding, but I don't recommend that.
