### ISSUE TITLE
Interesting shutdown behaviour

### ISSUE THREAD

**Issue by bboyle1234** [dotnet/orleans#4151]
Repo to reproduce observations
https://github.com/bboyle1234/OrleansSiloShutdownIssue

# OrleansSiloShutdownIssue

An interesting investigation of console app shutdown behaviour. Now that I've come this far with the experiment, it looks like it may have nothing to do with Orleans itself. 

If the `Console.CancelKeyPressed` event handler returns before the `static void Main(string[] args)` method returns, the console app hangs.

In this project, the Orleans silo shutdown triggers `_siloShutdownEvent.Set()`. The two methods mentioned above are waiting on that event before they can return. If there are no `Thread.Sleep(100)` statements in the code, it's a random race to the finish. When `Main` finishes first, the program exits gracefully. When `Console.CancelKeyPress` finishes first, the program hangs.

I've added a bool flag that you can change to determine the race winner so you can see both outcomes. 

Either way, Orleans emits the following warning: 

```
warn: Orleans.Runtime.Catalog[100502]
      UnregisterManyAsync 1 failed.
System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterOrPutInForwardList(IEnumerable`1 addresses, UnregistrationCause cause, Int32 hopCount, Dictionary`2& forward, List`1 tasks, String context)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.<UnregisterManyAsync>d__107.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.<Execute>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<FinishDestroyActivations>d__76.MoveNext()
warn: Orleans.Runtime.Catalog[100502]
      UnregisterManyAsync 2 failed.
System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterOrPutInForwardList(IEnumerable`1 addresses, UnregistrationCause cause, Int32 hopCount, Dictionary`2& forward, List`1 tasks, String context)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.<UnregisterManyAsync>d__107.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by bboyle1234** [comment]
Fix for the shutdown issue was this code: 
```
    Console.CancelKeyPress += (s, a) => {
        a.Cancel = true;
        Task.Run(StopSilo);
    };
```
I"m not sure what to do about the log warning though

**Comment by benjaminpetit** [comment]
So let me check if I understood: no issue with ctrl+c if you set the `Cancel` flag to true, correct?

I think the warning here is meaningless, since you only have one silo in your cluster.

**Comment by bboyle1234** [comment]
Yes, correct. The best fix is to set the `Cancel` flag to true.
Would you be ok with adding the documentation tag to this issue to get this knowledge snippet documented?

**Comment by sergeybykov** [comment]
@bboyle1234 Would you like to contribute the doc snippet?

**Comment by bboyle1234** [comment]
https://github.com/bboyle1234/orleans/pull/1

**Comment by sergeybykov** [comment]
@bboyle1234 Thanks for writing it up! Can you submit it as a PR against https://github.com/dotnet/orleans/tree/gh-pages?

**Comment by bboyle1234** [comment]
@sergeybykov, I think I did ... the link I posted above is to a pull request. Did I get it wrong somehow? (Still learning)

**Comment by sergeybykov** [comment]
@bboyle1234 You submitted it against your fork of Orleans - https://github.com/bboyle1234/orleans, instead of https://github.com/dotnet/orleans/. I can easily pull your commits and submit a PR with them against https://github.com/dotnet/orleans/, but I thought you might want to do that yourself to practice.

**Comment by bboyle1234** [comment]
https://github.com/dotnet/orleans/pull/4201

Thanks

**Comment by bboyle1234** [comment]
Regarding shutdown in a docker container: 
When debugging in Visual Studio inside the container, the SIGTERM signal seems to be sent to the VSDEBUG process in the container, NOT the silo host application. The result is that the VSDEBUG process is terminated, without the silo host application ever getting to pass through a graceful shutdown process.

Do you have any inside knowledge about how to bubble the event into the silo host application during debugging, or do you think documentation should simply make the user "aware" that the issue will exist during debugging?

**Comment by jms69** [comment]
There was another related discussion earlier.

So which is the right way to handle a cancel?   This way or this way https://github.com/dotnet/orleans/issues/4043?

Scaling silo containers up and down needs this to work properly.

**Comment by benjaminpetit** [comment]
> When debugging in Visual Studio inside the container, the SIGTERM signal seems to be sent to the VSDEBUG process in the container, NOT the silo host application. The result is that the VSDEBUG process is terminated, without the silo host application ever getting to pass through a graceful shutdown process.
> Do you have any inside knowledge about how to bubble the event into the silo host application during debugging, or do you think documentation should simply make the user "aware" that the issue will exist during debugging?

Yes I saw this, I don't have any workaround for the moment... we should add that to the doc

> So which is the right way to handle a cancel? This way or this thread way #4043?
> Scaling silo containers up and down needs this to work properly.

If you are using Linux container, you should call silo.Stop() when `AssemblyLoadContext.Default.Unloading` is fired. It's not called (yet?) in windows containers

**Comment by ReubenBond** [comment]
Resolved by #10582, which updated the shutdown guide for the current Generic Host model. Applications should run Orleans using Run/RunAsync and rely on the host lifetime to observe termination requests and await silo shutdown; they should not add the separate process-exit handler pattern discussed here.

Current documentation: https://dotnet.github.io/orleans/docs/host/configuration-guide/shutting-down-orleans/
