### ISSUE TITLE
Dns.GetHostAddressesAsync failure preventing Silo start

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#4158]
I'm getting the following stack trace when attempting to start a silo. I believe the cause is the default value for `AdvertisedIPAddress` in `EndpointOptions`. I'm trying to run the silo (rc1)  in an AWS Fargate (managed container service) task. I can try to troubleshoot the underlying error more, but I'm pretty sure I'll need to set the `AdvertisedIPAddress` manually anyways, so having the default specified in a different manner (as suggested in https://github.com/dotnet/orleans/issues/4115) may make more sense.

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Configuration.ConfigUtilities.<ResolveIPAddress>d__18.MoveNext()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at Orleans.Configuration.EndpointOptions..ctor()
--- End of inner exception stack trace ---
at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance[T]()
at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy`1.CreateValue()
at Orleans.Runtime.LocalSiloDetails..ctor(IOptions`1 siloOptions, IOptions`1 clusterOptions, IOptions`1 siloEndpointOptions)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at Orleans.Configuration.ServiceCollectionExtensions.<>c__0`2.<AddFromExisting>b__0_1(IServiceProvider sp)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
at Orleans.Runtime.Configuration.SiloClusteringValidator.ValidateConfiguration()
at Orleans.Hosting.SiloHostBuilder.ValidateSystemConfiguration(IServiceProvider serviceProvider)
at Orleans.Hosting.SiloHostBuilder.Build()
```

**Comment by benjaminpetit** [comment]
Fixed with #4171

**Comment by rwhitmire** [comment]
I believe there is a bug in the logic that attempts to determine which IPAddress to advertise when deploying to AWS Fargate.

```
.ConfigureEndpoints(22222, 40000, listenOnAnyHostAddress: true)
```

With this configuration, the AdvertisedIPAddress was being set to a 169.* IP address I don't recognize. My node's private IP address begins with 172.*

```
var nodeIps = NetworkInterface.GetAllNetworkInterfaces()
    .SelectMany(iface => iface.GetIPProperties().UnicastAddresses)
    .Select(addr => addr.Address)
    .ToList();

foreach (var ipAddress in nodeIps)
{
    Console.WriteLine($"{ipAddress}");
}
```

Running this code on Fargate logs

```
172.31.68.161      <- this is the one i want
169.254.172.42    <- this is the one being selected
127.0.0.1
```

Let me know if there's any additional information I can provide to assist!

**Comment by jsteinich** [comment]
@rwhitmire I'm just looping through the interfaces myself to select the correct one, i.e.
```c#
var siloAddress = NetworkInterface.GetAllNetworkInterface
    .SelectMany(iface => iface.GetIPProperties().UnicastAddresses)
    .Select(addr => addr.Address)
    .FirstOrDefault(ip => ip.ToString().StartsWith("172"));
...
builder.ConfigureEndpoints(siloAddress, siloPort, gatewayPort, true);
```

Technically the method that gets called internally to `ConfigureEnpoints`; `Config.ResolveIPAddress`, does have a subnet parameter, so it could be exposed with another extension method. It may be worth submitting a PR adding it.

**Comment by rwhitmire** [comment]
OK, that's similar to what I'm doing as a workaround. If I can find time this week, I'll look into something more elegant.

**Comment by benjaminpetit** [comment]
Yes this is "expected". But you can now plug your own logic to determine the IP address to use.

> Technically the method that gets called internally to `ConfigureEnpoints`; `Config.ResolveIPAddress`, does have a subnet parameter, so it could be exposed with another extension method. It may be worth submitting a PR adding it.

The `subnet` parameter isn't really a subnet parameter: more a "ip prefix" like your example.

I am not against adding helper methods :)
