### ISSUE TITLE
System.TypeAccessException: Named type "..." is invalid: Type string "..." cannot be resolved.

### ISSUE THREAD

**Issue by alexandrnikitin** [dotnet/orleans#4188]
I believe I encounter a bug. It seems Orleans doesn't work well with generic type that is located in another project. Could be related to #4012 
I've prepared a minimal repro project for the case: https://github.com/alexandrnikitin/orleans-repro-4188

To reproduce:

```
cd \samples\GoogleHashcode2018
>BuildAndRun.ps1
```
Observe Client console app output. The following exception appears:

```
System.AggregateException: One or more errors occurred. (Named type "DMCTS.Grains.NodeView`1<Rides.MakeRideAction>" is invalid: Type string "Rides.MakeRideAction" cannot be resolved.) ---> System.TypeAccessException: Named type "DMCTS.Grains.NodeView`1<Rides.MakeRideAction>" is invalid: Type string "Rides.MakeRideAction" cannot be resolved.
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadSpecifiedTypeHeader(IBinaryTokenStreamReader this, SerializationManager serializationManager)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, IBinaryTokenStreamReader stream)
   at Orleans.Runtime.Message.GetDeserializedBody(SerializationManager serializationManager)
   at Orleans.Runtime.GrainReferenceRuntime.ResponseCallback(Message message, TaskCompletionSource`1 context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OrleansTaskExtentions.<<ToTypedTask>g__ConvertAsync4_0>d`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Rides.Client.Program.<DoClientWork>d__3.MoveNext() in C:\projects\my\DistributedMonteCarloTreeSearch.NET\samples\GoogleHashcode2018\Rides.Client\Program.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rides.Client.Program.<RunMainAsync>d__1.MoveNext() in C:\projects\my\DistributedMonteCarloTreeSearch.NET\samples\GoogleHashcode2018\Rides.Client\Program.cs:line 26
---> (Inner Exception #0) System.TypeAccessException: Named type "DMCTS.Grains.NodeView`1<Rides.MakeRideAction>" is invalid: Type string "Rides.MakeRideAction" cannot be resolved.
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadSpecifiedTypeHeader(IBinaryTokenStreamReader this, SerializationManager serializationManager)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, IBinaryTokenStreamReader stream)
   at Orleans.Runtime.Message.GetDeserializedBody(SerializationManager serializationManager)
   at Orleans.Runtime.GrainReferenceRuntime.ResponseCallback(Message message, TaskCompletionSource`1 context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OrleansTaskExtentions.<<ToTypedTask>g__ConvertAsync4_0>d`1.MoveNext()<---
```

**Comment by ReubenBond** [comment]
@alexandrnikitin the project containing `MakeRideAction` needs to have the `Microsoft.Orleans.OrleansCodeGenerator.Build` package installed.

Alternatively, the `DMCTS.GrainInterfaces` project can have an assembly level attribute to instruct the code generator to generate code for `Rides` also, like so:
```C#
[assembly: KnownAssembly(typeof(Rides.MakeRideAction))]`
```

**Comment by alexandrnikitin** [comment]
Great! It helped! Thank you for the prompt response.
