### ISSUE TITLE
[2.0 RC2] Ado.Net reminders provider is broken in RC2

### ISSUE THREAD

**Issue by AdamWyzgol** [dotnet/orleans#4207]
After upgrade to RC2 I have exception when using Ado.Net reminders provider. I configure it as:

```
        .UseAdoNetReminderService(options =>
         {
                 options.ConnectionString = ConnectionString;
                 options.Invariant = "System.Data.SqlClient";
          })
```

and on `_siloHost = builder.Build();` I got: 
```
Orleans.Runtime.OrleansConfigurationException
  HResult=0x80131500
  Message=Invalid AdoNetReminderTableOptions values for AdoNetReminderTable. Invariant is required.
  Source=Orleans.Reminders.AdoNet
  StackTrace:
   at Orleans.Configuration.AdoNetReminderTableOptionsValidator.ValidateConfiguration()
   at Orleans.Hosting.SiloHostBuilder.ValidateSystemConfiguration(IServiceProvider serviceProvider)
   at Orleans.Hosting.SiloHostBuilder.Build()
   at <....>.Orleans.Start() in <....>\Orelans.cs:line 53
   at <....>.Program.Service.Start() in <....>\Program.cs:line 28
   at <....>.Program.<>c.<Main>b__1_3(Service tc) in <....>\Program.cs:line 53
   at Topshelf.ServiceConfiguratorExtensions.<>c__DisplayClass2_0`1.<WhenStarted>b__0(T service, HostControl control)
   at Topshelf.Builders.DelegateServiceBuilder`1.DelegateServiceHandle.Start(HostControl hostControl)
   at Topshelf.Hosts.ConsoleRunHost.Run()

```

**Comment by ReubenBond** [comment]
Thank you for reporting! I'll submit a PR soon.

As a work-around, please use this code to your builder:
```C#
.UseAdoNetReminderService(default(Action<AdoNetReminderTableOptions>))
.Configure<AdoNetReminderTableOptions>(options =>
{
  options.ConnectionString = ConnectionString;
  options.Invariant = "System.Data.SqlClient";
})
```
