### ISSUE TITLE
Intermittent failures of ControllableAdapter* tests

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#4220]
ControllableAdapterEchoTest
ControllableAdapterFactoryEchoTest

**Comment by sergeybykov** [comment]
https://orleans.visualstudio.com/Orleans/_build/index?buildId=9139&_a=summary&tab=ms.vss-test-web.test-result-details

>Error message
Assert.Equal() Failure\r\nExpected: 2\r\nActual: 1
Stack trace
at UnitTests.StreamingTests.ControllableStreamProviderTests.<ControllableAdapterEchoTestRunner>d__5.MoveNext() in D:\build\agent\_work\15\s\test\Tester\StreamingTests\ControllableStreamProviderTests.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.StreamingTests.ControllableStreamProviderTests.<ControllableAdapterEchoTest>d__3.MoveNext() in D:\build\agent\_work\15\s\test\Tester\StreamingTests\ControllableStreamProviderTests.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by xiazen** [comment]
this can be fixed by #4343,  since it fails when some silo didn't join the cluster yet when test started.
