### ISSUE TITLE
Intermittent failure of  StressHandlingMultipleDelayedRequests test

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#4221]

**Comment by sergeybykov** [comment]
https://orleans.visualstudio.com/Orleans/_TestManagement/Runs?_a=resultSummary&runId=3989&resultId=100093
https://orleans.visualstudio.com/Orleans/_TestManagement/Runs#_a=resultSummary&runId=3987&resultId=100093

>Error message
System.TimeoutException : WithTimeout has timed out after 00:00:15
Stack trace
at Orleans.OrleansTaskExtentions.<WithTimeout>d__16.MoveNext() in D:\build\agent2\_work\8\s\src\Orleans.Core\Async\TaskExtensions.cs:line 225
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at DefaultCluster.Tests.ErrorGrainTest.<StressHandlingMultipleDelayedRequests>d__8.MoveNext() in D:\build\agent2\_work\8\s\test\DefaultCluster.Tests\ErrorGrainTest.cs:line 150
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by benjaminpetit** [comment]
I am running it for more than 15min now, and I don't reproduce this issue. I think the machine that executes the test should be overloaded at that time. I will relax the timeout a bit, and we will see if this test fails again

**Comment by sergeybykov** [comment]
Resolved (hopefully) via #4270.
