### ISSUE TITLE
Intermittent failures of ThreeClusterBattery test

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#4265]
https://orleans.visualstudio.com/Orleans/_TestManagement/Runs?_a=resultSummary&runId=4079&resultId=101380
>Error message
System.AggregateException : One or more errors occurred.\r\n---- Orleans.Runtime.OrleansMessageRejectionException : Forwarding failed: tried to forward message NewPlacement Request S127.0.0.1:21300:259343047*gcl/C/562f28b3+C@ef6312b6->S127.0.0.1:21301:259343061*grn/21E58844/4fe3f9d0@ca8917b6 #865358[ForwardCount=2]: for 2 times after Duplicate activation to invalid activation. Rejecting now. 
Stack trace
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at UnitTests.GeoClusterTests.MultiClusterRegistrationTests.ClientWrapper.GetRuntimeId(Int32 i) in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\MultiClusterRegistrationTests.cs:line 179
at UnitTests.GeoClusterTests.MultiClusterRegistrationTests.<Deact>d__17.MoveNext() in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\MultiClusterRegistrationTests.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Tests.GeoClusterTests.TestingClusterHost.<RunWithTimeout>d__6.MoveNext() in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\TestingClusterHost.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.GeoClusterTests.MultiClusterRegistrationTests.<ThreeClusterBattery>d__5.MoveNext() in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\MultiClusterRegistrationTests.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.OrleansTaskExtentions.<<ToTypedTask>g__ConvertAsync4_0>d`1.MoveNext() in D:\build\agent\_work\18\s\src\Orleans.Core\Async\TaskExtensions.cs:line 100

https://orleans.visualstudio.com/Orleans/_TestManagement/Runs?_a=resultSummary&runId=4069&resultId=101409
>Error message
System.AggregateException : One or more errors occurred.\r\n---- Orleans.Runtime.OrleansMessageRejectionException : Forwarding failed: tried to forward message NewPlacement Request S127.0.0.1:21300:259293372*gcl/C/697540ac+C@0aecc696->S127.0.0.1:21300:259293372*grn/21E58844/6f9bb666@aee927a3 #61674[ForwardCount=2]: for 2 times after Duplicate activation to invalid activation. Rejecting now. 
Stack trace
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at UnitTests.GeoClusterTests.MultiClusterRegistrationTests.ClientWrapper.GetRuntimeId(Int32 i) in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\MultiClusterRegistrationTests.cs:line 179
at UnitTests.GeoClusterTests.MultiClusterRegistrationTests.<Deact>d__17.MoveNext() in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\MultiClusterRegistrationTests.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Tests.GeoClusterTests.TestingClusterHost.<RunWithTimeout>d__6.MoveNext() in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\TestingClusterHost.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.GeoClusterTests.MultiClusterRegistrationTests.<ThreeClusterBattery>d__5.MoveNext() in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\MultiClusterRegistrationTests.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.OrleansTaskExtentions.<<ToTypedTask>g__ConvertAsync4_0>d`1.MoveNext() in D:\build\agent\_work\18\s\src\Orleans.Core\Async\TaskExtensions.cs:line 100

**Comment by ReubenBond** [comment]
Closing all test reliability issues. Test reliability has improved substantially. We can re-open for any test reliability issues which we still see.
