### ISSUE TITLE
Intermittent failure of GlobalSingleInstanceClusterTests.All_Small test

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#4281]
https://orleans.visualstudio.com/Orleans/_TestManagement/Runs?_a=resultSummary&runId=4113&resultId=101389
>Error message
Assert.True() Failure\r\nExpected: True\r\nActual: False
Stack trace
at Tests.GeoClusterTests.GlobalSingleInstanceClusterTests.<ConflictResolution>d__14.MoveNext() in D:\build\agent\_work\13\s\test\TesterInternal\GeoClusterTests\GlobalSingleInstanceClusterTests.cs:line 412
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Tests.GeoClusterTests.TestingClusterHost.<RunWithTimeout>d__6.MoveNext() in D:\build\agent\_work\13\s\test\TesterInternal\GeoClusterTests\TestingClusterHost.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Tests.GeoClusterTests.GlobalSingleInstanceClusterTests.<All_Small>d__1.MoveNext() in D:\build\agent\_work\13\s\test\TesterInternal\GeoClusterTests\GlobalSingleInstanceClusterTests.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by ReubenBond** [comment]
Closing all test reliability issues. Test reliability has improved substantially. We can re-open for any test reliability issues which we still see.
