### ISSUE TITLE
Fabric Service Rolling Upgrade

### ISSUE THREAD

**Issue by hanxinimm** [dotnet/orleans#4304]
No gateways available

**Comment by sergeybykov** [comment]
Could you share more information about your setup and logs? Client would temporarily see no gateways if no silo (with gateway enabled) is running.

**Comment by hanxinimm** [comment]
@sergeybykov 

```
异常信息 Response did not arrive on time in 00:00:30 for message: Request *cli/65da87bc@354b4780->S127.0.0.1:8741:0*grn/BC0CEC3B/00000000 #12: . Target History is: <S127.0.0.1:8741:0:*grn/BC0CEC3B/00000000:>.C:\ProgramData\SF\Staging-Server\Fabric\work\Applications\MGTAppType_App55\StatelessWebApiCommandServicePkg.Code.1.0.0\StatelessWebApiCommandService.dll 内部异常 C:\ProgramData\SF\Staging-Server\Fabric\work\Applications\MGTAppType_App55\StatelessWebApiCommandServicePkg.Code.1.0.0\StatelessWebApiCommandService.dll 异常来源 System.Private.CoreLibC:\ProgramData\SF\Staging-Server\Fabric\work\Applications\MGTAppType_App55\StatelessWebApiCommandServicePkg.Code.1.0.0\StatelessWebApiCommandService.dll 异常堆栈    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StatelessWebApiCommandService.CustomerController.<Add>d__0.MoveNext() in F:\LaborDispatch\MGTCenter\StatelessWebApiCommandService\Controllers\Customer\CustomerController.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```

Grain Server Restart

**Comment by sergeybykov** [comment]
How many silos are in the cluster? What provider are you using for cluster membership?
