### ISSUE TITLE
HelloWorld Sample Error for netcore 2.0

### ISSUE THREAD

**Issue by BenDerPan** [dotnet/orleans#4314]
I try to run the HelloWorld sample on my mac, I use .netcore 2.0, it throws the exception below:
System.ArgumentException: Cannot find an implementation class for grain interface: HelloWorld.Interfaces.IHello. Make sure the grain assembly was correctly deployed and loaded in the silo.
   at Orleans.GrainFactory.GetGrainClassData(Type interfaceType, String grainClassNamePrefix)
   at Orleans.GrainFactory.GetGrain[TGrainInterface](Int64 primaryKey, String grainClassNamePrefix)
   at OrleansClient.Program.<DoClientWork>d__3.MoveNext() in /Users/echo/Documents/Github/orleans/Samples/2.0/HelloWorld/src/OrleansClient/Program.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrleansClient.Program.<RunMainAsync>d__1.MoveNext() in /Users/echo/Documents/Github/orleans/Samples/2.0/HelloWorld/src/OrleansClient/Program.cs:line 29

**Comment by sergeybykov** [comment]
Resolved via #4387.

**Comment by sgf** [comment]
@sergeybykov 

```
static async void Run()
        {
            //define the cluster configuration
            var builder = new SiloHostBuilder()
                //configure the cluster with local host clustering
                .UseLocalhostClustering()
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = "dev";
                    options.ServiceId = "HelloWorldApp";
                })
                .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(HelloGrain).Assembly).WithReferences())
                //.ConfigureServices(services =>
                //{
                //    services.AddSingleton<IHello, HelloGrain>();
                //})
                .ConfigureLogging(logging => logging.AddConsole());
            //build the silo
            var host = builder.Build();
            //start the silo
            await host.StartAsync();
        }
```
Added in SiloHost

but given a New Error:

Orleans.Runtime.OrleansConfigurationException:“None of the assemblies added to ApplicationPartManager contain generated code. Ensure that code generation has been executed for grain interface and class assemblies.”

**Comment by sgf** [comment]
using Microsoft.Orleans.Server 2.0.3

**Comment by sgf** [comment]
@sergeybykov
{Orleans.Runtime.OrleansConfigurationException: None of the assemblies added to ApplicationPartManager contain generated code. Ensure that code generation has been executed for grain interface and class assemblies.
   at Orleans.Configuration.Validators.ApplicationPartValidator.ValidateConfiguration() in D:\build\agent\_work\18\s\src\Orleans.Core\Configuration\Validators\ApplicationPartValidator.cs:line 39
   at Orleans.Hosting.SiloHostBuilder.ValidateSystemConfiguration(IServiceProvider serviceProvider) in D:\build\agent\_work\18\s\src\Orleans.Runtime\Hosting\Generic\SiloHostBuilder.cs:line 159
   at Orleans.Hosting.SiloHostBuilder.Build() in D:\build\agent\_work\18\s\src\Orleans.Runtime\Hosting\Generic\SiloHostBuilder.cs:line 43
   at M3.Svr.Program.<Run>d__1.MoveNext() in G:\Src\Dev\Apps\Mir3Apps\M3.Svr\Program.cs:line 46}

**Comment by sgf** [comment]
Solved by https://github.com/dotnet/orleans/issues/1189#issuecomment-382035663
