### ISSUE TITLE
CustomStorage test is failing consistently

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#4316]
We should probably rename it to something less generic.

https://orleans.visualstudio.com/Orleans/_TestManagement/Runs?_a=resultSummary&runId=4144&resultId=101473
>Error message
System.InvalidOperationException : A suitable constructor for type 'Orleans.EventSourcing.CustomStorage.LogConsistencyProvider' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
Stack trace
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Tests.GeoClusterTests.BasicLogTestGrainTests.<>c__DisplayClass12_0.<<ThreeCheckers>b__0>d.MoveNext() in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\BasicLogTestGrainTests.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Tests.GeoClusterTests.BasicLogTestGrainTests.<ThreeCheckers>d__12.MoveNext() in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\BasicLogTestGrainTests.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Tests.GeoClusterTests.BasicLogTestGrainTests.<DoBasicLogTestGrainTest>d__11.MoveNext() in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\BasicLogTestGrainTests.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Tests.GeoClusterTests.BasicLogTestGrainTests.<CustomStorage>d__8.MoveNext() in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\BasicLogTestGrainTests.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by sergeybykov** [comment]
`TestBattery_MemoryStorageProvider` is another test that is failing consistently, and is possibly related.
https://orleans.visualstudio.com/Orleans/_build/index?buildId=9538&_a=summary&tab=ms.vss-test-web.test-result-details
>Error message
Orleans.Runtime.OrleansLifecycleCanceledException : Lifecycle start canceled due to errors at stage 4000\r\n---- System.ArgumentNullException : Value cannot be null.\r\nParameter name: type
Stack trace
at Orleans.LifecycleSubject.<OnStart>d__4.MoveNext() in D:\build\agent\_work\18\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.<Execute>d__8.MoveNext() in D:\build\agent\_work\18\s\src\Orleans.Runtime\Scheduler\ClosureWorkItem.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Silo.<StartAsync>d__64.MoveNext() in D:\build\agent\_work\18\s\src\Orleans.Runtime\Silo\Silo.cs:line 275
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.TestingHost.AppDomainSiloHost.Start() in D:\build\agent\_work\18\s\test\Orleans.TestingHost.AppDomain\AppDomainSiloHost.cs:line 37
at Orleans.TestingHost.AppDomainSiloHost.Start()
at Orleans.TestingHost.AppDomainSiloHandle.Create(String siloName, IList`1 configurationSources) in D:\build\agent\_work\18\s\test\Orleans.TestingHost.AppDomain\AppDomainSiloHandle.cs:line 75
at Orleans.TestingHost.TestCluster.StartOrleansSilo(Int32 instanceNumber, TestClusterOptions clusterOptions, IReadOnlyList`1 configurationOverrides, Boolean startSiloOnNewPort) in D:\build\agent\_work\18\s\src\Orleans.TestingHost\TestCluster.cs:line 482
at Orleans.TestingHost.TestCluster.<InitializeAsync>d__56.MoveNext() in D:\build\agent\_work\18\s\src\Orleans.TestingHost\TestCluster.cs:line 433
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.TestingHost.TestCluster.<DeployAsync>d__36.MoveNext() in D:\build\agent\_work\18\s\src\Orleans.TestingHost\TestCluster.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.TestingHost.TestCluster.Deploy() in D:\build\agent\_work\18\s\src\Orleans.TestingHost\TestCluster.cs:line 125
at Tests.GeoClusterTests.TestingClusterHost.NewCluster[TSiloBuilderConfigurator](Guid serviceId, String clusterId, Int16 numSilos, Action`1 customizer) in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\TestingClusterHost.cs:line 237
at Tests.GeoClusterTests.TestingClusterHost.NewGeoCluster[TSiloBuilderConfigurator](Guid globalServiceId, String clusterId, Int16 numSilos, Action`1 customizer) in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\TestingClusterHost.cs:line 166
at Tests.GeoClusterTests.LogConsistencyTestFixture.StartClustersIfNeeded(Int32 numclusters, ITestOutputHelper output) in D:\build\agent\_work\18\s\test\TesterInternal\GeoClusterTests\LogConsistencyTestFixture.cs:line 176
----- Inner Stack Trace -----
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
at Orleans.Providers.LegacyProviderConfigurator`1.<>c__DisplayClass3_0`1.<RegisterProvider>b__0(IServiceProvider s, String n) in D:\build\agent\_work\18\s\src\Orleans.Core\Providers\LegacyProviderConfigurator.cs:line 143
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at Orleans.Runtime.KeyedServiceCollection`2.GetService(IServiceProvider services, TKey k

**Comment by jason-bragg** [comment]
custom storage log consistency test fixed in #4323

**Comment by jason-bragg** [comment]
TestBattery_MemoryStorageProvider test failure is a test issue.  Should not block 2.0 release.

**Comment by ReubenBond** [comment]
Closing all test reliability issues. Test reliability has improved substantially. We can re-open for any test reliability issues which we still see.
