### ISSUE TITLE
Intermittent failures of PluggableQueueBalancerTest_ShouldUseInjectedQueueBalancerAndBalanceCorrectly test

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#4317]
Likely related to #3993.

https://orleans.visualstudio.com/Orleans/_TestManagement/Runs?_a=resultSummary&runId=4144&resultId=100678
>Error message
Assert.Equal() Failure\r\nExpected: 1\r\nActual: 2
Stack trace
at Tester.StreamingTests.PluggableQueueBalancerTestBase.<CheckLeases>d__4.MoveNext() in D:\build\agent\_work\18\s\test\Tester\StreamingTests\PlugableQueueBalancerTests\PluggableQueueBalancerTestBase.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.TestingHost.Utils.TestingUtils.<>c__DisplayClass4_0.<<WaitUntilAsync>b__0>d.MoveNext() in D:\build\agent\_work\18\s\src\Orleans.TestingHost\Utils\TestingUtils.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.TestingHost.Utils.TestingUtils.<WaitUntilAsync>d__4.MoveNext() in D:\build\agent\_work\18\s\src\Orleans.TestingHost\Utils\TestingUtils.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Tester.StreamingTests.PluggableQueueBalancerTestBase.<ShouldUseInjectedQueueBalancerAndBalanceCorrectly>d__2.MoveNext() in D:\build\agent\_work\18\s\test\Tester\StreamingTests\PlugableQueueBalancerTests\PluggableQueueBalancerTestBase.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by ReubenBond** [comment]
Closing all test reliability issues. Test reliability has improved substantially. We can re-open for any test reliability issues which we still see.
