### ISSUE TITLE
Intermittent failures of Rem_Grain_1J_MultiGrainMultiReminders test

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#4318]
https://orleans.visualstudio.com/Orleans/_TestManagement/Runs?_a=resultSummary&runId=4164&resultId=101330
>Error message
Orleans.Runtime.ReminderException : Could not unregister reminder <IOrleansReminder: GrainRef=GrainReference:*grn/549BB267/40733213fcc201daf462fc6a472e3e9403000000549bb267-0xB3D221CC ReminderName=REMINDER_1 ETag=bd94968a-6ff0-4986-9088-53bac5792d6d> from the reminder table, due to tag mismatch. You can retry.
Stack trace
Server stack trace: 
at Orleans.Runtime.ReminderService.LocalReminderService.<UnregisterReminder>d__19.MoveNext() in D:\build\agent\_work\15\s\src\Orleans.Runtime\ReminderService\LocalReminderService.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.OrleansCodeGenReminderServiceMethodInvoker.<Invoke>d__0.MoveNext() in D:\build\agent\_work\15\s\src\Orleans.Core\obj\Release\netstandard2.0\Orleans.Core.orleans.g.cs:line 947
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.GrainMethodInvoker.<Invoke>d__21.MoveNext() in D:\build\agent\_work\15\s\src\Orleans.Runtime\Core\GrainMethodInvoker.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.InsideRuntimeClient.<Invoke>d__64.MoveNext() in D:\build\agent\_work\15\s\src\Orleans.Runtime\Core\InsideRuntimeClient.cs:line 364
Exception rethrown at [0]: 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.Grains.ReminderTestGrain2.<StopReminder>d__14.MoveNext() in D:\build\agent\_work\15\s\test\TestInternalGrains\ReminderTestGrain2.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.GrainInterfaces.OrleansCodeGenReminderTestGrain2MethodInvoker.<Invoke>d__0.MoveNext() in D:\build\agent\_work\15\s\test\TestGrainInterfaces\obj\Release\netstandard2.0\win10-x64\TestGrainInterfaces.orleans.g.cs:line 26485
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.GrainMethodInvoker.<Invoke>d__21.MoveNext() in D:\build\agent\_work\15\s\src\Orleans.Runtime\Core\GrainMethodInvoker.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.InsideRuntimeClient.<Invoke>d__64.MoveNext() in D:\build\agent\_work\15\s\src\Orleans.Runtime\Core\InsideRuntimeClient.cs:line 364
Exception rethrown at [1]: 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.OrleansTaskExtentions.<WithTimeout>d__16.MoveNext() in D:\build\agent\_work\15\s\src\Orleans.Core\Async\TaskExtensions.cs:line 218
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.TimerTests.ReminderTests_Base.<ExecuteWithRetriesStop>d__29.MoveNext() in D:\build\agent\_work\15\s\test\TesterInternal\TimerTests\ReminderTests_Base.cs:line 420
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by benjaminpetit** [comment]
My guess is that we have a duplicate activation of the Grain based reminder.

**Comment by ReubenBond** [comment]
Closing all test reliability issues. Test reliability has improved substantially. We can re-open for any test reliability issues which we still see.

**Comment by ReubenBond** [comment]
Reopening for a current recurrence in the same multi-grain reminder test family:

- PR: #10587, head `728014b5b383e55ed6c89983f328e839fb95b310`
- Job: Microsoft SQL Server provider tests (SqlServer, net8.0), job 94835814186
- Test: `ReminderTests_AdoNet_SqlServer.Rem_Sql_1J_MultiGrainMultiReminders`
- Failure: expected tick count `1`, actual `2`, at `ReminderTestsBase.AdvanceRemindersByTicksAsync` line 486.

The branch already contains the ADO.NET asynchronous fixture initialization fix from #10560 (`c7f60d95a94c2aa2c1205018e9836e8941bd968c`). PR #10587 changes membership, placement, lifecycle, manifest/cache behavior and related tests, not reminder execution or the SQL Server provider. The PR has now been rebased onto current `main`; fresh CI is running at `ed790dfc5a575ba95b99069e6c4fdd6c97a7e072`.

**Comment by ReubenBond** [comment]
Additional framework evidence from the same rebased PR head:

- Microsoft SQL Server provider tests (SqlServer, net10.0), job 94850193560
- `Rem_Sql_1J_MultiGrainMultiReminders` timed out after approximately five minutes with `TaskCanceledException` in `AdvanceRemindersByTicksAsync` (`ReminderTestsBase.cs:426-428`); suite result 1 failed, 168 passed, 4 skipped.
- The corresponding SQL Server net8 job passed on this head.

This complements the prior net8 recurrence (expected one tick, observed two) and indicates the shared multi-reminder fake-time synchronization remains flaky across frameworks.

**Comment by ReubenBond** [comment]
Rerun result: the SQL Server net10.0 job passed on workflow attempt 3 (job 94852590887). SQL Server net8.0 also passed on the rebased head. The original net8 duplicate-tick and net10 timeout failures are therefore intermittent and remain tracked here.

**Comment by ReubenBond** [comment]
A sequential 10-run `.NET CI` `workflow_dispatch` audit against `main` at head `01fa5b5dda5ed0bfec2e8e4ff8cb9582b8a59157` reproduced the SQL Server reminder duplicate/missed-tick pattern in **7/10 workflow runs** and **8/20 SQL Server matrix jobs**. All 10 attempts completed; none were canceled.

`Rem_Sql_1J_MultiGrainMultiReminders` failed in 7 jobs across 6 workflow runs:

- net10.0: https://github.com/dotnet/orleans/actions/runs/31897990745/job/95044167861
- net8.0: https://github.com/dotnet/orleans/actions/runs/31898975270/job/95046539580
- net10.0: https://github.com/dotnet/orleans/actions/runs/31898975270/job/95046539496
- net8.0: https://github.com/dotnet/orleans/actions/runs/31900031672/job/95049212160
- net10.0: https://github.com/dotnet/orleans/actions/runs/31901975880/job/95054030901
- net10.0: https://github.com/dotnet/orleans/actions/runs/31903007862/job/95056530012
- net10.0: https://github.com/dotnet/orleans/actions/runs/31905145282/job/95061667029

Five occurrences observed a duplicate tick (`Expected: 1`, `Actual: 2`) in `AdvanceRemindersByTicksAsync` at lines 486/491. Two timed out in `GetReminderCounterWaitTask` at line 865 with the reminder counter one tick short and `Active owners: 1`.

The same duplicate-tick signature also affected `Rem_Sql_Basic_ListOps` once on net10.0: https://github.com/dotnet/orleans/actions/runs/31906351630/job/95064700587 (`Expected: 1`, `Actual: 2`, `AdvanceRemindersByTicksAsync` line 491). I am grouping it here rather than opening a duplicate because it has the same provider, fake-time advancement path, and duplicate-tick signature.

The combined recurrence rate is 70% of workflow runs and 40% of SQL Server matrix jobs.

**Comment by ReubenBond** [comment]
Investigation update:

- Searches across open and merged PRs for `#4318`, the exact grain/SQL test names, tag mismatch, ETag/race, duplicate/missed tick, and retry terms found no earlier fix tied directly to this issue. The exact historical test name only led to #4329 (the 2018 skip) and unrelated #4267.
- The 7/10 workflow recurrence at `01fa5b5` predates #10612 by three days. #10612 restored the single-owner invariant by preventing a stale owner from creating a local schedule after persisting a registration, then explicitly reconciles the current owner before fake time advances.
- #10666 re-enables the exact historical regression test and restores the shared fixture topology after its join phase. The exact test passed 50 consecutive runs across net8.0/net10.0; the complete shared fixture passed 20 consecutive runs across both frameworks.

#10666 includes `Fixes #4318`, so this issue can close when that PR merges.
