### ISSUE TITLE
Intermittent failures of  SMS_AllSilosRestart_UnsubscribeConsumer test

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#4322]
https://orleans.visualstudio.com/Orleans/_TestManagement/Runs?_a=resultSummary&runId=4155&resultId=101189
>Error message
Orleans.Runtime.OrleansMessageRejectionException : No gateways available
Stack trace
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.Streaming.Reliability.StreamReliabilityTests.<SMS_AllSilosRestart_UnsubscribeConsumer>d__40.MoveNext() in D:\build\agent\_work\15\s\test\TesterAzureUtils\Streaming\StreamReliabilityTests.cs:line 626
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by benjaminpetit** [comment]
Not a 2.0 blocker.

In the test we restart silos, and sometimes we try to make a call grom the client before it had a chance to refresh the list of gateway. Refreshing it more often + waiting a bit before making the final client call should fix this test.

**Comment by ReubenBond** [comment]
Closing all test reliability issues. Test reliability has improved substantially. We can re-open for any test reliability issues which we still see.
