### ISSUE TITLE
ClusterClient.Connect() retryFilter causes NullReferenceException

### ISSUE THREAD

**Issue by lmagyar** [dotnet/orleans#4427]
Introduced with #4161.

First bug (?): When client tries to connect, but fails in `OutsideRuntimeClient.StartInternal` inside the first `ExecuteWithRetries` it throws `OrleansException` instead of `SiloUnavailableException`.

Second bug: Later in this StartInternal, after another connection error, when the filter returns true, it retries, successfully, but at the first `GetGrain()` call it throws a `NullReferenceException` somewhere inside.

Based on this:
```
Orleans.Runtime.OrleansException: Not connected to a gateway
   at Orleans.Messaging.ClientMessageCenter.GetLiveGatewaySiloAddress()
   at Orleans.Messaging.ClientMessageCenter.GetImplicitStreamSubscriberTable(IInternalGrainFactory grainFactory)
   at Orleans.OutsideRuntimeClient.<StreamingInitialize>d__56.MoveNext()
```
It's some streaming reconnection error. It seems, when there is a streaming connection issue, it's still better to recreate the whole client. :(

See the repro at [lmagyar/ClientConnectRetryFilterBugRepro](https://github.com/lmagyar/ClientConnectRetryFilterBugRepro), it's basically a vanilla HelloWorld that uses runtime codegen to be slow enough. Start client manually, wait 2 seconds, start silo, you have to try it several times to be successful to repro. See output below.

```

Z:\Local\GitHub\lmagyar\ClientConnectRetryFilterBugRepro\src\Orleans.Activities.Samples.HelloWorld.DevClusterClient\bin\Debug>Orleans.Activities.Samples.HelloWorld.DevClusterClient.exe
info: Orleans.OutsideRuntimeClient[100313]
      ---------- Initializing OutsideRuntimeClient on XXX at XXX Client Id = *cli/53be99bc ----------
info: Orleans.OutsideRuntimeClient[100314]
      ---------- Starting OutsideRuntimeClient with runtime Version='2.0.0. Commit Hash: 89ebbe67d2266b24b34e704935fe70577d30408a (Release).' in AppDomain=<AppDomain.Id=1, AppDomain.FriendlyName=Orleans.Activities.Samples.HelloWorld.DevClusterClient.exe>
info: Orleans.Messaging.GatewayManager[101309]
      Found 1 knownGateways from Gateway listProvider [gwy.tcp://127.0.0.1:30000/0]
warn: Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0[100178]
      Unable to connect to gateway at address gwy.tcp://127.0.0.1:30000/0 on trial 0 (Exception: Could not connect to 127.0.0.1:30000: ConnectionRefused)
warn: Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0[100913]
      Marking gateway at address gwy.tcp://127.0.0.1:30000/0 as Disconnected
info: Orleans.Messaging.GatewayManager[101309]
      Refreshed the live Gateway list. Found 1 gateways from Gateway listProvider: [gwy.tcp://127.0.0.1:30000/0]. Picked only known live out of them. Now has 1 live Gateways: [gwy.tcp://127.0.0.1:30000/0]. Previous refresh time was = 04/08/2018 23:34:41
warn: Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0[100178]
      Unable to connect to gateway at address gwy.tcp://127.0.0.1:30000/0 on trial 1 (Exception: Could not connect to 127.0.0.1:30000: ConnectionRefused)
warn: Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0[100913]
      Marking gateway at address gwy.tcp://127.0.0.1:30000/0 as Disconnected
info: Orleans.Messaging.GatewayManager[101309]
      Refreshed the live Gateway list. Found 1 gateways from Gateway listProvider: [gwy.tcp://127.0.0.1:30000/0]. Picked only known live out of them. Now has 1 live Gateways: [gwy.tcp://127.0.0.1:30000/0]. Previous refresh time was = 04/08/2018 23:34:42
warn: Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0[100912]
      Marking gateway at address gwy.tcp://127.0.0.1:30000/0 as Dead in my client local gateway list.
warn: Orleans.Runtime.CallbackData[100157]
      The target silo became unavailable for message: Request *cli/53be99bc@43dd8d83->S127.0.0.1:30000:0*stg/17/00000011@S00000011 #2: . Target History is: <S127.0.0.1:30000:0:*stg/17/00000011:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help. About to break its promise.
warn: Orleans.OutsideRuntimeClient[100011]
      No callback for response message: Unrecoverable Rejection (info: Target silo S127.0.0.1:30000:0 is unavailable) Response S127.0.0.1:30000:0*stg/17/00000011@S00000011->*cli/53be99bc@43dd8d83 #2:
warn: Orleans.OutsideRuntimeClient[104202]
      Refresh the GrainTypeResolver failed. WIll be retried after
Orleans.Runtime.SiloUnavailableException: The target silo became unavailable for message: Request *cli/53be99bc@43dd8d83->S127.0.0.1:30000:0*stg/17/00000011@S00000011 #2: . Target History is: <S127.0.0.1:30000:0:*stg/17/00000011:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OutsideRuntimeClient.<RefreshGrainTypeResolver>d__59.MoveNext()


****************************************************************
Orleans.Runtime.OrleansException: Not connected to a gateway
   at Orleans.Messaging.ClientMessageCenter.GetLiveGatewaySiloAddress()
   at Orleans.Messaging.ClientMessageCenter.GetImplicitStreamSubscriberTable(IInternalGrainFactory grainFactory)
   at Orleans.OutsideRuntimeClient.<StreamingInitialize>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OutsideRuntimeClient.<<StartInternal>g__ExecuteWithRetries58_3>d.MoveNext()
****************************************************************


Attempt 1 of 5 failed to initialize the Orleans client.

warn: Orleans.Messaging.GatewayManager[101321]
      All gateways have previously been marked as dead. Clearing the list of dead gateways to expedite reconnection.
info: Orleans.Messaging.GatewayManager[101309]
      Refreshed the live Gateway list. Found 1 gateways from Gateway listProvider: [gwy.tcp://127.0.0.1:30000/0]. Picked only known live out of them. Now has 1 live Gateways: [gwy.tcp://127.0.0.1:30000/0]. Previous refresh time was = 04/08/2018 23:34:43
info: Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0[100908]
      Connected to gateway at address gwy.tcp://127.0.0.1:30000/0 on trial 0.
info: Messaging.GatewayClientReceiver/gwy.tcp://127.0.0.1:30000/0[0]
      Starting AsyncAgent Messaging.GatewayClientReceiver/gwy.tcp://127.0.0.1:30000/0 on managed thread 12
info: Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0[0]
      Starting AsyncAgent Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0 on managed thread 13
info: Orleans.OutsideRuntimeClient[100929]
      ---------- Started OutsideRuntimeClient with Global Client ID: CXXX:0:-260926481*cli/53be99bc@43dd8d83, client GUID ID: *cli/53be99bc
info: Orleans.ClientOptionsLogger[0]
      Configuration Orleans.Configuration.ClientMessagingOptions:
      ClientSenderBuckets: 8192
      PreferredFamily: InterNetwork
      NetworkInterfaceName:
      ResponseTimeout: 00:00:30
      ResponseTimeoutWithDebugger: 00:30:00
      MaxResendCount: 0
      ResendOnTimeout: False
      DropExpiredMessages: True
      BufferPoolBufferSize: 4096
      BufferPoolMaxSize: 10000
      BufferPoolPreallocationSize: 250
      PropagateActivityId: False

info: Orleans.ClientOptionsLogger[0]
      Configuration Orleans.Configuration.ClientStatisticsOptions:
      PerfCountersWriteInterval: -00:00:00.0010000
      LogWriteInterval: 00:05:00
      CollectionLevel: Info

info: Orleans.ClientOptionsLogger[0]
      Configuration Orleans.Configuration.ClusterOptions:
      ClusterId: dev
      ServiceId:

info: Orleans.ClientOptionsLogger[0]
      Configuration Orleans.Configuration.NetworkingOptions:
      OpenConnectionTimeout: 00:00:05
      MaxSocketAge: 10675199.02:48:05.4775807

info: Orleans.ClientOptionsLogger[0]
      Configuration Orleans.Configuration.StaticGatewayListProviderOptions:
      Gateways.0: gwy.tcp://127.0.0.1:30000/0

info: Orleans.LifecycleSubject[100452]
      Starting lifecycle stage -2147483648 took 22 Milliseconds
Client successfully connected to silo host.


****************************************************************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.GrainFactory.GetGrainClassData(Type interfaceType, String grainClassNamePrefix)
   at Orleans.GrainFactory.GetGrain[TGrainInterface](Guid primaryKey, String grainClassNamePrefix)
   at Orleans.ClusterClient.GetGrain[TGrainInterface](Guid primaryKey, String grainClassNamePrefix)
   at DevClusterClient.Program.<DoClientWorkAsync>d__6.MoveNext() in Z:\Local\GitHub\lmagyar\ClientConnectRetryFilterBugRepro\src\Orleans.Activities.Samples.HelloWorld.DevClusterClient\Program.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DevClusterClient.Program.<Main>d__1.MoveNext() in Z:\Local\GitHub\lmagyar\ClientConnectRetryFilterBugRepro\src\Orleans.Activities.Samples.HelloWorld.DevClusterClient\Program.cs:line 28
****************************************************************

Press Enter to terminate...
```

**Comment by ReubenBond** [comment]
I think I see the problem: `RefreshGrainTypeResolver` is swallowing all exceptions, so initialization is continuing despite any error.

**Comment by ReubenBond** [comment]
Thank you for taking the time to create a repro & report this, Laszlo - it's a great help

**Comment by lmagyar** [comment]
@ReubenBond I don't know whether the "first bug" is a bug, I just noticed it differs from other parts, but I don't know the internal logic, it's your decision. :)

**Comment by ReubenBond** [comment]
I changed the exception for when no gateways are available to `SiloUnavailableException` anyway, because it's nicer than `OrleansException` and I don't see a strong need for a more specific exception.
