### ISSUE TITLE
Cannot find an invoker for interface

### ISSUE THREAD

**Issue by justmara** [dotnet/orleans#4433]
Trying to migrate to 2.0.
First, adding application parts in host:

```
.ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(Workers.Auth.Grains.AuthCodeGrain).Assembly)
   .WithCodeGeneration())
```
(by the way, even if Interfaces/Workers libs contains reference to Microsoft.Orleans.OrleansCodeGenerator.Build, they're not added as application parts until I add WithCodeGeneration())
Then I see in host log that my grain code was scanned and registered:

```
Grain class Workers.HealthChecks.Grains.Workers.HealthChecks.Grains.HealthCheckGrain [1431208743 (0x554E8327)]
from Orleans.Workers.dll implementing interfaces: 
Interfaces.HealthChecks.Grains.IHealthCheckGrain [-1394029992 (0xACE8CA58)]
```
But when client tries to call it...
```
[Debug] About to call "[Activation: S10.35.27.174:1000:260979847*grn/554E8327/00000000@aed94880 #GrainType=Workers.HealthChecks.Grains.HealthCheckGrain Placement=RandomPlacement State=Activating]" grain's OnActivateAsync() method "Workers.HealthChecks.Grains.HealthCheckGrain"

[Information] Starting lifecycle stage 2000 took 0 Milliseconds

[Debug] Returned from calling "[Activation: S10.35.27.174:1000:260979847*grn/554E8327/00000000@aed94880 #GrainType=Workers.HealthChecks.Grains.HealthCheckGrain Placement=RandomPlacement State=Activating]" grain's OnActivateAsync() method "Workers.HealthChecks.Grains.HealthCheckGrain"

[Verbose] About to make timer callback for timer "GrainTimer.TransactionAgent. TimerCallbackHandler:[SystemTarget: S10.35.27.174:1000:260979847*stg/28/0000001c@S0000001c]->System.Threading.Tasks.Task ProcessRequests(System.Object)"

[Verbose] In table, Not in local, "<GrainRef=GrainReference:*grn/7022443F/9c1748a3 ReminderName=CourierArriverTimmer Period=00:01:00>"

[Verbose] Completed timer callback for timer "GrainTimer.TransactionAgent. TimerCallbackHandler:[SystemTarget: S10.35.27.174:1000:260979847*stg/28/0000001c@S0000001c]->System.Threading.Tasks.Task ProcessRequests(System.Object)"

[Warning] Exception during Grain method call of message: NewPlacement Request S10.35.27.174:1000:260979847*cli/f0dc71ba@ff343485->S10.35.27.174:1000:260979847*grn/554E8327/00000000@aed94880 #4: 
Orleans.Runtime.OrleansException: Cannot find an invoker for interface Interfaces.HealthChecks.Grains.IHealthCheckGrain (ID=-1394029992,0xACE8CA58).
   at Orleans.Runtime.GrainTypeManager.GetInvoker(Int32 interfaceId, String genericGrainType)
   at Orleans.Runtime.ActivationData.GetInvoker(GrainTypeManager typeManager, Int32 interfaceId, String genericGrainType)
   at Orleans.Runtime.InsideRuntimeClient.<Invoke>d__64.MoveNext()
```
How could that 'Cannot find an invoker' happen if we've seen it succesfully registered in host? With all the same id/hash values.

**Comment by justmara** [comment]
got it. `WithReferences()`. It fails because cannot find serializer for one of referenced types. But still error message is confusing
