### ISSUE TITLE
Exception: `TryToSuspectOrKill failed` with UseAdoNetClustering

### ISSUE THREAD

**Issue by DarkCow** [dotnet/orleans#4467]
Hey all, I am having a problem with one SiloHost randomly crashing, then the membership algorithm is having trouble kicking it out of the cluster. 

I am using Orleans 2.0.0 with `UseAdoNetClustering`

I have attached a log. You can see (near the bottom) at 2018-04-13T13:26:12.6526455Z is the exception, then scrolling up from there you can see what lead up to it.

[darkcow-errorlog.zip](https://github.com/dotnet/orleans/files/1907794/darkcow-errorlog.zip)

Here is the exception I am seeing.

```
System.AggregateException: One or more errors occurred. ---> System.AggregateException: An error occurred while writing to logger(s). ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Extensions.Logging.Internal.LogValuesFormatter.GetValue(Object[] values, Int32 index)
   at Microsoft.Extensions.Logging.Internal.FormattedLogValues.get_Item(Int32 index)
   at Microsoft.Extensions.Logging.Internal.FormattedLogValues.<GetEnumerator>d__14.MoveNext()
   at Serilog.Extensions.Logging.SerilogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogDebug(ILogger logger, String message, Object[] args)
   at Orleans.Runtime.MembershipService.MembershipOracle.<TryToSuspectOrKill>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__4`1.MoveNext()
   --- End of inner exception stack trace ---
   at Orleans.Runtime.MembershipService.MembershipOracle.<IncFailedProbes>b__67_1(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.AggregateException: An error occurred while writing to logger(s). ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Extensions.Logging.Internal.LogValuesFormatter.GetValue(Object[] values, Int32 index)
   at Microsoft.Extensions.Logging.Internal.FormattedLogValues.get_Item(Int32 index)
   at Microsoft.Extensions.Logging.Internal.FormattedLogValues.<GetEnumerator>d__14.MoveNext()
   at Serilog.Extensions.Logging.SerilogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogDebug(ILogger logger, String message, Object[] args)
   at Orleans.Runtime.MembershipService.MembershipOracle.<TryToSuspectOrKill>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__4`1.MoveNext()
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Extensions.Logging.Internal.LogValuesFormatter.GetValue(Object[] values, Int32 index)
   at Microsoft.Extensions.Logging.Internal.FormattedLogValues.get_Item(Int32 index)
   at Microsoft.Extensions.Logging.Internal.FormattedLogValues.<GetEnumerator>d__14.MoveNext()
   at Serilog.Extensions.Logging.SerilogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
<---
```

here is my initialization code

```
            var builder = new SiloHostBuilder( )
                .Configure<ClusterOptions>( options =>
                {
                    options.ClusterId = "mri";
                    options.ServiceId = Guid.Empty.ToString( );
                } )
                .Configure<SiloOptions>( options =>
                {
                    options.SiloName = "SiloHost";
                } )
                .UseAdoNetClustering( options =>
                {
                    options.Invariant = "System.Data.SqlClient";
                    options.ConnectionString = Mri.Pultt.Settings.ConnectionSettings.OrleansConnectionString;
                } )
                .AddAdoNetGrainStorage( "Default", options =>
                {
                    options.Invariant = "System.Data.SqlClient";
                    options.ConnectionString = Mri.Pultt.Settings.ConnectionSettings.OrleansConnectionString;
                } )
                .AddAdoNetGrainStorage( "PubSubStore", options =>
                {
                    options.Invariant = "System.Data.SqlClient";
                    options.ConnectionString = Mri.Pultt.Settings.ConnectionSettings.OrleansConnectionString;
                } )
                .UseAdoNetReminderService( options =>
                {
                    options.Invariant = "System.Data.SqlClient";
                    options.ConnectionString = Mri.Pultt.Settings.ConnectionSettings.OrleansConnectionString;
                } )
                // Workaround for bug in Orleans 2.0.0-rc2 https://github.com/dotnet/orleans/issues/4207
                .Configure<AdoNetReminderTableOptions>( options =>
                {
                    options.Invariant = "System.Data.SqlClient";
                    options.ConnectionString = Mri.Pultt.Settings.ConnectionSettings.OrleansConnectionString;
                } )
                .Configure<GrainCollectionOptions>( options =>
                {
                    options.ClassSpecificCollectionAge.Add( typeof( Mri.NOC.Actors.DisplayTermActor ).FullName, TimeSpan.FromMinutes( 5 ) );
                    options.ClassSpecificCollectionAge.Add( typeof( Mri.Pultt.Actors.SortedDisplayFilterActor ).FullName, TimeSpan.FromMinutes( 5 ) );
                } )
                .ConfigureApplicationParts( parts =>
                {
                    parts.AddApplicationPart( typeof( Mri.Interfaces.IAccountActor ).Assembly ).WithReferences( );
                    parts.AddApplicationPart( typeof( Mri.Pultt.Actors.AccountActor ).Assembly ).WithReferences( );
                    parts.AddApplicationPart( typeof( Mri.Pond.Actors.DisplayEventsActor ).Assembly ).WithReferences( );
                    parts.AddApplicationPart( typeof( Mri.NOC.Actors.DisplayHttpProxyActor ).Assembly ).WithReferences( );
                } )
                .ConfigureServices( Services.ConfigureServices )
                .AddStartupTask<OrleansStartupTask>( )
                .AddSimpleMessageStreamProvider( Events.SMS, options =>
                {
                    options.FireAndForgetDelivery = true;
                } )
                .AddIncomingGrainCallFilter<ExceptionConversionFilter>( )
                .AddPlacementDirector<RolePlacementStrategy, RolePlacementDirector>( )
                .AddPlacementDirector<NocPlacementStrategy, NocPlacementDirector>( )
                .ConfigureLogging( logging =>
                {
                    logging.AddSerilog( );
                } );
```

**Comment by DarkCow** [comment]
Hey, another SiloHost just crashed. Trying to figure out why, Here is the log for NOC-Silo04 which crashed at `2018-04-13T15:48:43.6150745Z` I then manually restarted it at `2018-04-13T16:49:46.2396923Z`

[darkcow-errorlog-silo_perspective.zip](https://github.com/dotnet/orleans/files/1908296/darkcow-errorlog-silo_perspective.zip)

A telling sign that a SiloHost is about to go down is I get these error messages popping up. 

`Worker pool thread Runtime.Scheduler.WorkerPoolThread/6 (ManagedThreadId=36) has been busy for long time: Executing Task Id=84725562 Status=Running for 05:18:05.1463325 on WorkItem=WorkItemGroup:Name=[Activation: S172.24.253.20:22222:261257415*grn/589B1051/00000000+PI00069@753f7dae #GrainType=Mri.Pond.Actors.DisplayEventsActor Placement=RolePlacementStrategy],WorkGroupStatus=Running Executing for 05:18:05.1463325. WorkItemGroup Details: WorkItemGroup:Name=[Activation: S172.24.253.20:22222:261257415*grn/589B1051/00000000+PI00069@753f7dae #GrainType=Mri.Pond.Actors.DisplayEventsActor Placement=RolePlacementStrategy],WorkGroupStatus=Running. Currently QueuedWorkItems=3; Total EnQueued=40; Total processed=36; Quantum expirations=0; TaskRunner=ActivationTaskScheduler-16043:Queued=3; Detailed SchedulingContext=<[Activation: S172.24.253.20:22222:261257415*grn/589B1051/0000000000000000000000000000000006000000589b1051+PI00069-0xBA813AAF@753f7dae #GrainType=Mri.Pond.Actors.DisplayEventsActor Placement=RolePlacementStrategy State=Valid NonReentrancyQueueSize=0 EnqueuedOnDispatcher=1 InFlightCount=1 NumRunning=1 IdlenessTimeSpan=06:18:11.5495242 CollectionAgeLimit=02:00:00 CurrentlyExecuting=Request S172.24.253.10:22222:261257466*grn/188574AB/00000000+PI00069@adf7c1b1->S172.24.253.20:22222:261257415*grn/589B1051/00000000+PI00069@753f7dae #3018323: ]>.`

I looked at CPU usage for those time stamps, and it ain't spiking as far as I can tell, and the code for that actor I just confirmed is 100% async/await with no blocking calls. (This code used to work on Orleans-2.0.0-rc2)

**Comment by sergeybykov** [comment]
The first log is very confusing. Is it from multiple silos and clients? Also, `Debug` level of logging is rather expensive and noisy. `Info` is usually enough.

In the second log, "Worker pool thread Runtime.Scheduler.WorkerPoolThread/6 (ManagedThreadId=36) has been busy for long" warnings point to grain logic blocking threads for a **VERY** long time. Something must be wrong there. Make sure any IO is done asynchronously there.

Blocked grain threads clog silos, and calls to their grains start to time out. I didn't see any indication of a silo crash. But I suspect blocking of threads eventually leads to that.

In the first log I see numerous exceptions thrown by grain methods:
>System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
Server stack trace: 
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Mri.Pond.Actors.DisplayEventsActor.<ApplyDisplayEventProfileAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mri.Pond.Actors.DisplayEventsActor.<CreateDisplayEventAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mri.Pond.Actors.DisplayEventsActor.<ClearDisplayEventAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Throwing an exception from inside a grain method is totally fine. But I wonder if there's some major issue with the grain code.

**Comment by DarkCow** [comment]
Yes it is from 17 Silos.. The logs are impossible to parse :sob:, I have the code currently deployed to my staging environment which has a lot less activity on it. If it occurs again I will try and parse some logs to be more readable.

I have also gone through and ruthlessly cut down on the exceptions that are occurring, I must confess that I have sinned and let them percolate up instead of handling them :)

I am however hoping to discover the reason why the `Orleans.Runtime.MembershipService.MembershipOracle` is throwing the `System.AggregateException: An error occurred while writing to logger(s). ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.` exception. And why it appears to be so tightly nit with my Serilog code... Below is some code that I have written (before and after) that I think might be the culprit... I won't know till ~48 hrs of runtime...

My question is the RequestContext immutable? I would argue that the new code is better irregardless

```
        {
            public LogContext( string name, string value )
            {
+               Dictionary<string, string> contexts;
+
                m_Name = name;
// Essentially what this code is doing is adding to the RequestContext a special key, that a serilog
// enricher can read from and add traceable log properties.
// Before I was altering the Orleans RequestContext dictionary, this appeared to work in Orleans 1.5x
// I have now changed it to a read/copy/modify/write
-               var contexts = RequestContext.Get( OrleansLogEnricher.SeriLogKey ) as Dictionary<string, string> ?? new Dictionary<string, string>( );
+               // If existing context, make a copy of the dictionary
+               if( RequestContext.Get( OrleansLogEnricher.SeriLogKey ) is Dictionary<string, string> existing ) contexts = new Dictionary<string, string>( existing );
                else contexts = new Dictionary<string, string>( );

                contexts[ m_Name ] = value;
                RequestContext.Set( OrleansLogEnricher.SeriLogKey, contexts );
            }
```

**Comment by DarkCow** [comment]
Welp, the service is still running, it appears that modifying the Request Context (which I think is immutable) can cause very bad things to happen over time...

But performing a read/copy/modify/write seems to work.

**Comment by sergeybykov** [comment]
Have you tried setting logging level to `Info` instead of `Debug`? This line wouldn't execute then at all. And as mentioned above, `Debug` is overkill in most cases anyway.

**Comment by DarkCow** [comment]
Setting my min log level to `Info` appears to fix the problem

**Comment by DarkCow** [comment]
@seralexeev Setting the min log level to `Info` fixes the problem. it appears to be a problem between Serilog and Microsoft.Extensions.Logging.

I will look into making an issue with Serilog. Thanks for the help.

**Comment by DarkCow** [comment]
#4507 appears to say Orleans plans on refactoring it's logging code to not use `System.Format` style, thus fixing Serilog incompatibility.

**Comment by benjaminpetit** [comment]
It's not an issue with Serilog: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x#log-message-template
