### ISSUE TITLE
DynamoDb null reference on read

### ISSUE THREAD

**Issue by stephenlautier** [dotnet/orleans#4482]
We are encountering a `NullReferenceException` on activation in special cases e.g. This seems to occur only when changing a type namespace.

This is the following error
```
Exc level 0: System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Storage.DynamoDBGrainStorage.ConvertFromStorageFormat(GrainStateRecord entity)
   at Orleans.Storage.DynamoDBGrainStorage.<ReadStateAsync>d__20.MoveNext()
```

### Additional info
We are using Orleans `2.0.0-rc2`

#### Dynamo Options
 - `config.UseJson = true;`
 ` config.TypeNameHandling` (unset)

Just reporting this maybe it gets handled better or more relevant exception

**Comment by sergeybykov** [comment]
>This seems to occur only when changing a type namespace.

Do you mean the identity of the type of the persisted object changes between when it is saved to storage and when it is later read back?

**Comment by stephenlautier** [comment]
@sergeybykov yes, for instance changing the namespace of the State class

e.g.

```cs
namespace Friend // rename to Enemy
{
    public class EntityState 
    {
          public string Name { get; set; }
    }
}
```

**Comment by galvesribeiro** [comment]
I believe this is not a supported scenario on any provider as the full type name (namespace + type) is used to reference the state... Specifically on DynamoDB, it is used as Range index and RowKey.

I would appreciate if you have a full stacktrace for me :)

**Comment by sergeybykov** [comment]
Yes, changing of the namespace changes the type identity, and without a special type forwarding logic of some sort, there is no way for any serializer to know that those type should be considered the same.

**Comment by stephenlautier** [comment]
@galvesribeiro maybe you missed my last point, I'm not expecting it to fetch the old data and work. I reported this because its throwing a `NullReferenceException` on activation; So what I'm suggesting is either somehow just returns `null` or throw a better/nicer exception. In my example I would rather have a null than an exception because then data would be refetched and everything would have worked

#### Exception

#### message
```
Error from storage provider DynamoDBGrainStorage.Odin.Gaming.Grains.GameInfo.GameInfoGrain during ReadState for grain Type=Odin.Gaming.Grains.GameInfo.GameInfoGrain Pk=*grn/5BAC51A8/00000000000000000000000000000000060000005bac51a8+loki/ORYX_HTML5_AER:DESKTOP:oryx:oryx-0x84E37497 Id=GrainReference:*grn/5BAC51A8/00000000+loki/ORYX_HTML5_AER:DESKTOP:oryx:oryx Error=
 
Exc level 0: System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Storage.DynamoDBGrainStorage.ConvertFromStorageFormat(GrainStateRecord entity)
   at Orleans.Storage.DynamoDBGrainStorage.<ReadStateAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Core.StateStorageBridge`1.<ReadStateAsync>d__11.MoveNext()
```

#### Stack
```
   at Orleans.Core.StateStorageBridge`1.<ReadStateAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Grain`1.<OnSetupState>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.LifecycleSubject.<WrapExecution>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.LifecycleSubject.<OnStart>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Orleans.Runtime.Catalog.<CallGrainActivate>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.<Execute>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<InitActivation>d__61.MoveNext()
```

I had took a glimpse at the code of the `DynamoDBGrainStorage.ConvertFromStorageFormat(GrainStateRecord entity)` to try and figure out why the null reference, and my guess its that the null reference is coming from the exception handling itself.
https://github.com/dotnet/orleans/blob/master/src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs#L322

See screenshot where i highlighted my assumption. 
![image](https://user-images.githubusercontent.com/3908723/39275705-789ed36a-48e6-11e8-8c46-4c131b519fb0.png)

**Assumption**
* We are using `UseJson`, so its using `StringState`
* Hence `BinaryState` is `null`
* An exception is thrown when its deserializing from JSON
* Goes into the catch
* An exception is thrown when checking `binaryData.length` because its `null`

Again its just assumption because i haven't debugged it, but from what i can see thats the only thing i can spot for null reference. Hope it helps!

**Comment by galvesribeiro** [comment]
Ok, now I understood your point and yes, that first `if` you highlighted on the `catch` should not throw NRE.

I'll submit a PR now to fix this, but even with that, deserialization exceptions should be thrown. I believe there is no "better" exception when it fail. Can you confirm that @sergeybykov ?

PR soon...

**Comment by galvesribeiro** [comment]
Fix on #4513

**Comment by stephenlautier** [comment]
@galvesribeiro cheers! i had opened one but i was too slow so closed mine 😄 

Yea after seeing the code i dont think there's a nice way of doing it.. other than try/catch return null, but i wouldnt do it.

**Comment by ReubenBond** [comment]
Should we consider this resolved now, after merging #4513? There will still be an exception, but it will be the intended exception instead of an NRE

**Comment by galvesribeiro** [comment]
@stephenlautier np, thanks for taking time to put the PR even if it wasn't merged. Too slow boy 😄 

The fix should go to the CI build/package on MyGet so you can experiment it before the next public release.

Please let us know if it worked for you.

**Comment by stephenlautier** [comment]
@ReubenBond yes i will close it as it should be resolved now, thanks!
