### ISSUE TITLE
ADO.Net Oracle storage provider:: InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by srinathgnath** [dotnet/orleans#4484]
Hello Team,
Am getting below error while registering ado.net oracle storage provider. Not sure if am missing something here. Any help would be appreciated.

Error Message:
InvalidOperationException: Sequence contains no matching element
Stack:
 at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Orleans.Storage.AdoNetGrainStorage.<Init>d__34.MoveNext() in D:\build\agent\_work\15\s\src\AdoNet\Orleans.Persistence.AdoNet\Storage\Provider\AdoNetGrainStorage.cs:line 409
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.<OnStart>d__9.MoveNext() in D:\build\agent\_work\15\s\src\Orleans.Runtime\Lifecycle\SiloLifecycleSubject.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.LifecycleSubject.<WrapExecution>d__8.MoveNext() in D:\build\agent\_work\15\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.LifecycleSubject.<OnStart>d__4.MoveNext() in D:\build\agent\_work\15\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 49

Thanks

**Comment by srinathgnath** [comment]
Working fine after adding Oracle.DataAccess assembly. So what I understood is that both Oracle.ManagedAccess & Oracle.DataAccess are required for ado.net oracle storage implementation. Host builder is throwing error if I remove reference to any one of those.

**Comment by srinathgnath** [comment]
Follow below steps for Oracle ADO.Net storage implementation:
1) Refer below assemblies.
                Orleans.Persistence.AdoNet
                Oracle.ManagedAccess
                Oracle.DataAccess
2) Call below silohost builder methods.

                .AddAdoNetGrainStorage("SampleDataStorage", options =>
                {
                    options.ConnectionString = "Enter your connection string";
                    options.Invariant = "Oracle.DataAccess.Client";
                    options.UseJsonFormat = true; // for JSON formatted data
                })
                .AddAdoNetGrainStorageAsDefault(options =>
               {
                   options.ConnectionString = "Enter your connection string";
                   options.Invariant = "Oracle.DataAccess.Client";
               })
3) Execute below sql scripts to create necessary database objects for orleans storage implementation.
      https://github.com/dotnet/orleans/blob/master/src/AdoNet/Shared/Oracle-Main.sql
      https://github.com/dotnet/orleans/blob/master/src/AdoNet/Orleans.Persistence.AdoNet/Oracle- 
        Persistence.sql
