### ISSUE TITLE
Exception when Adding UsePerfCounterEnvironmentStatistics() in a .NET Core 2.0 Service Fabric service 

### ISSUE THREAD

**Issue by jms69** [dotnet/orleans#4495]
Service Fabric .Net Core 2.0 Service hosting a silo.

Added builder.UsePerfCounterEnvironmentStatistics() cause the error below.
``
Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at Orleans.Statistics.PerfCounterEnvironmentStatistics.InitCpuMemoryCounters()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
``

This issue was not easy to find and only showed up for me when locally deployed only when deployed to the cloud cluster.

Solved by simply added the [System.Management](https://www.nuget.org/packages/System.Management/) nuget package.

Should we add this package to Orleans.TelemetryConsumers.Counter even though it is in preview to solve the reference problem?

**Comment by jms69** [comment]
Ignore this.  Post.  I just checked and saw that Orleans.TelemetryConsumers.Counter is .NET 4.6.1 only.
