### ISSUE TITLE
[2.0] TestCluster .Deploy() / SiloHost.StartAsync().Wait() never return.

### ISSUE THREAD

**Issue by Murodese** [dotnet/orleans#4498]
Using Orleans 2.0 with .NET Core 2.0, I have a TestCluster set up as an xunit collection fixture:

```
    [CollectionDefinition("Orleans TestCluster")]
    public class OrleansTestHelperCollection : ICollectionFixture<OrleansTestHelper> { }


    public class OrleansTestHelper : IDisposable
    {
        public TestCluster Cluster { get; set; }
        
        public OrleansTestHelper()
        {
            var builder = new TestClusterBuilder(1);
            this.Cluster = builder.Build();
            Cluster.Deploy();
        }

        public void Dispose()
        {
            Cluster.StopAllSilos();
        }
    }
```

When debugging or executing the unit test, the program will never move past Cluster.Deploy() - instead, hanging indefinitely. The silo is created with the following logs:

```
[2018-04-20 10:18:47.259 GMT 12	Information	0	Orleans.Runtime.Scheduler.OrleansTaskScheduler]	Starting OrleansTaskScheduler with 8 Max Active application Threads and 1 system thread.	
[2018-04-20 10:18:47.485 GMT 12	Information	100404	Orleans.Runtime.Silo]	Silo starting with GC settings: ServerGC=False GCLatencyMode=Interactive	
[2018-04-20 10:18:47.485 GMT 12	Warning	100405	Orleans.Runtime.Silo]	Note: Silo not running with ServerGC turned on - recommend checking app config : <configuration>-<runtime>-<gcServer enabled="true">	
[2018-04-20 10:18:47.485 GMT 12	Warning	100405	Orleans.Runtime.Silo]	Note: ServerGC only kicks in on multi-core systems (settings enabling ServerGC have no effect on single-core machines).	
[2018-04-20 10:18:47.485 GMT 12	Information	100403	Orleans.Runtime.Silo]	-------------- Initializing silo on host OptikaLap37 MachineName OPTIKALAP37 at 127.0.0.1:27112, gen 261915527 --------------	
[2018-04-20 10:18:47.485 GMT 12	Information	100415	Orleans.Runtime.Silo]	Starting silo Primary	
[2018-04-20 10:18:47.616 GMT 12	Information	101010	Orleans.Runtime.Messaging.IncomingMessageAcceptor]	Opened a listening socket at address 127.0.0.1:27112	
[2018-04-20 10:18:47.650 GMT 12	Information	101010	Orleans.Runtime.Messaging.IncomingMessageAcceptor]	Opened a listening socket at address 127.0.0.1:43228	
[2018-04-20 10:18:47.717 GMT 12	Information	0	Orleans.Runtime.ConsistentRing.VirtualBucketsRingProvider]	Starting VirtualBucketsRingProvider on silo S127.0.0.1:27112:261915527/x15AC0530.	
[2018-04-20 10:18:47.748 GMT 12	Information	103003	Orleans.Runtime.ConsistentRing.VirtualBucketsRingProvider]	Added Server S127.0.0.1:27112:261915527/x15AC0530. Current view: [S127.0.0.1:27112:261915527 -> <MultiRange: Size=x100000000, %Ring=100.000%>]	
[2018-04-20 10:18:47.749 GMT 12	Information	103005	Orleans.Runtime.ConsistentRing.VirtualBucketsRingProvider]	-NotifyLocalRangeSubscribers about old <(0 0], Size=x100000000, %Ring=100.000%> new <MultiRange: Size=x100000000, %Ring=100.000%> increased? True	
[2018-04-20 10:18:47.771 GMT 12	Information	0	Orleans.Runtime.Silo]	Skip multicluster oracle creation (no multicluster network configured)	
[2018-04-20 10:18:47.776 GMT 12	Information	100422	Orleans.Runtime.Silo]	-------------- Started silo S127.0.0.1:27112:261915527, ConsistentHashCode 15AC0530 --------------	
[2018-04-20 10:18:47.810 GMT 18	Information	0	Runtime.Scheduler.WorkerPoolThread/System.9]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/System.9 on managed thread 18	
[2018-04-20 10:18:47.810 GMT 20	Information	0	Runtime.Scheduler.WorkerPoolThread/1]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/1 on managed thread 20	
[2018-04-20 10:18:47.810 GMT 19	Information	0	Runtime.Scheduler.WorkerPoolThread/0]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/0 on managed thread 19	
[2018-04-20 10:18:47.810 GMT 22	Information	0	Runtime.Scheduler.WorkerPoolThread/3]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/3 on managed thread 22	
[2018-04-20 10:18:47.810 GMT 21	Information	0	Runtime.Scheduler.WorkerPoolThread/2]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/2 on managed thread 21	
[2018-04-20 10:18:47.812 GMT 23	Information	0	Runtime.Scheduler.WorkerPoolThread/4]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/4 on managed thread 23	
[2018-04-20 10:18:47.816 GMT 24	Information	0	Runtime.Scheduler.WorkerPoolThread/5]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/5 on managed thread 24	
[2018-04-20 10:18:47.817 GMT 12	Information	100452	Orleans.Runtime.Silo]	Start Scheduler took 25 Milliseconds to finish	
[2018-04-20 10:18:47.820 GMT 25	Information	0	Runtime.Scheduler.WorkerPoolThread/6]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/6 on managed thread 25	
[2018-04-20 10:18:47.823 GMT 26	Information	0	Runtime.Scheduler.WorkerPoolThread/7]	Starting AsyncAgent Runtime.Scheduler.WorkerPoolThread/7 on managed thread 26	
[2018-04-20 10:18:47.845 GMT 26	Information	100453	Orleans.Runtime.SiloLifecycleSubject]	Stage -2147483648: Orleans.Runtime.SiloOptionsLogger	
[2018-04-20 10:18:47.845 GMT 26	Information	100453	Orleans.Runtime.SiloLifecycleSubject]	Stage 2000: Orleans.Runtime.InsideRuntimeClient, Orleans.Runtime.Silo	
[2018-04-20 10:18:47.845 GMT 26	Information	100453	Orleans.Runtime.SiloLifecycleSubject]	Stage 4000: Orleans.Runtime.Silo	
[2018-04-20 10:18:47.845 GMT 26	Information	100453	Orleans.Runtime.SiloLifecycleSubject]	Stage 8000: Orleans.Runtime.Silo	
[2018-04-20 10:18:47.845 GMT 26	Information	100453	Orleans.Runtime.SiloLifecycleSubject]	Stage 10000: Orleans.Runtime.Versions.GrainVersionStore	
[2018-04-20 10:18:47.845 GMT 26	Information	100453	Orleans.Runtime.SiloLifecycleSubject]	Stage 19999: Orleans.Runtime.Silo	
[2018-04-20 10:18:47.845 GMT 26	Information	100453	Orleans.Runtime.SiloLifecycleSubject]	Stage 20000: Orleans.Runtime.Silo	
[2018-04-20 10:18:47.868 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.ActivationCountBasedPlacementOptions: 
ChooseOutOf: 2
	
[2018-04-20 10:18:47.870 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.ClusterMembershipOptions: 
NumMissedTableIAmAliveLimit: 2
LivenessEnabled: True
ProbeTimeout: 00:00:10
TableRefreshTimeout: 00:01:00
DeathVoteExpirationTimeout: 00:02:00
IAmAliveTablePublishTimeout: 00:05:00
MaxJoinAttemptTime: 00:05:00
ExpectedClusterSize: 20
ValidateInitialConnectivity: True
UseLivenessGossip: True
NumProbedSilos: 3
NumMissedProbesLimit: 3
NumVotesForDeathDeclaration: 2
IsRunningAsUnitTest: False
	
[2018-04-20 10:18:47.870 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.ConsistentRingOptions: 
NumVirtualBucketsConsistentRing: 30
UseVirtualBucketsConsistentRing: True
	
[2018-04-20 10:18:47.870 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.EndpointOptions: 
AdvertisedIPAddress: 127.0.0.1
SiloPort: 27112
GatewayPort: 43228
SiloListeningEndpoint: 
GatewayListeningEndpoint: 
	
[2018-04-20 10:18:47.872 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.GrainCollectionOptions: 
CollectionQuantum: 00:01:00
CollectionAge: 02:00:00
	
[2018-04-20 10:18:47.872 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.GrainDirectoryOptions: 
CachingStrategy: Adaptive
CacheSize: 1000000
InitialCacheTTL: 00:00:30
MaximumCacheTTL: 00:04:00
CacheTTLExtensionFactor: 2
LazyDeregistrationDelay: 00:01:00
	
[2018-04-20 10:18:47.872 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.GrainVersioningOptions: 
DefaultCompatibilityStrategy: BackwardCompatible
DefaultVersionSelectorStrategy: AllCompatibleVersions
	
[2018-04-20 10:18:47.873 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.LoadSheddingOptions: 
LoadSheddingEnabled: False
LoadSheddingLimit: 95
	
[2018-04-20 10:18:47.873 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.MultiClusterOptions: 
HasMultiClusterNetwork: False
MaxMultiClusterGateways: 10
BackgroundGossipInterval: 00:00:30
UseGlobalSingleInstanceByDefault: True
GlobalSingleInstanceNumberRetries: 10
GlobalSingleInstanceRetryInterval: 00:00:30
	
[2018-04-20 10:18:47.874 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.NetworkingOptions: 
OpenConnectionTimeout: 00:00:05
MaxSocketAge: 10675199.02:48:05.4775807
	
[2018-04-20 10:18:47.874 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.PerformanceTuningOptions: 
DefaultConnectionLimit: 200
Expect100Continue: False
UseNagleAlgorithm: False
MinDotNetThreadPoolSize: 200
	
[2018-04-20 10:18:47.874 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.ProcessExitHandlingOptions: 
FastKillOnProcessExit: True
	
[2018-04-20 10:18:47.875 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.SchedulingOptions: 
PerformDeadlockDetection: False
AllowCallChainReentrancy: True
MaxActiveThreads: 8
DelayWarningThreshold: 00:00:10
ActivationSchedulingQuantum: 00:00:00.1000000
TurnWarningLengthThreshold: 00:00:00.2000000
MaxPendingWorkItemsSoftLimit: 0
MaxPendingWorkItemsHardLimit: 0
EnableWorkerThreadInjection: False
	
[2018-04-20 10:18:47.875 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.SerializationProviderOptions: 
FallbackSerializationProvider: 
	
[2018-04-20 10:18:47.877 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.SiloMessagingOptions: 
SiloSenderQueues: 8
GatewaySenderQueues: 8
MaxForwardCount: 2
ClientDropTimeout: 00:01:00
ClientRegistrationRefresh: 00:05:00
MaxEnqueuedRequestsSoftLimit: 0
MaxEnqueuedRequestsHardLimit: 0
MaxEnqueuedRequestsSoftLimit_StatelessWorker: 0
MaxEnqueuedRequestsHardLimit_StatelessWorker: 0
MaxRequestProcessingTime: 02:00:00
AssumeHomogenousSilosForTesting: False
ResponseTimeout: 00:30:00
ResponseTimeoutWithDebugger: 00:30:00
MaxResendCount: 0
ResendOnTimeout: False
DropExpiredMessages: True
BufferPoolBufferSize: 4096
BufferPoolMaxSize: 10000
BufferPoolPreallocationSize: 250
PropagateActivityId: False
	
[2018-04-20 10:18:47.877 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.SiloOptions: 
SiloName: Primary
	
[2018-04-20 10:18:47.878 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.SiloStatisticsOptions: 
DeploymentLoadPublisherRefreshTime: 00:00:01
PerfCountersWriteInterval: 00:00:30
LogWriteInterval: 00:05:00
CollectionLevel: Info
	
[2018-04-20 10:18:47.878 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.TelemetryOptions: 
	
[2018-04-20 10:18:47.878 GMT 26	Information	0	Orleans.Runtime.SiloOptionsLogger]	Configuration Orleans.Configuration.TypeManagementOptions: 
TypeMapRefreshInterval: 00:01:00
	
[2018-04-20 10:18:47.878 GMT 26	Information	100452	Orleans.Runtime.SiloLifecycleSubject]	Lifecycle observer Orleans.Runtime.SiloOptionsLogger started in stage -2147483648 which took 23 Milliseconds.	
[2018-04-20 10:18:47.878 GMT 26	Information	100452	Orleans.LifecycleSubject]	Starting lifecycle stage -2147483648 took 27 Milliseconds	
[2018-04-20 10:18:47.881 GMT 8	Information	100401	Orleans.Runtime.Silo]	Silo Start()	
[2018-04-20 10:18:47.883 GMT 8	Information	100430	Orleans.Runtime.Silo]	Configured ThreadPool.SetMinThreads() to values: 200,200. Previous values are: 8,8.	
[2018-04-20 10:18:47.883 GMT 8	Information	100436	Orleans.Runtime.Silo]	Configured .NET ServicePointManager to Expect100Continue=False, DefaultConnectionLimit=200, UseNagleAlgorithm=False to improve Azure storage performance.	
[2018-04-20 10:18:47.883 GMT 8	Information	100452	Orleans.Runtime.Silo]	ConfigureThreadPoolAndServicePointSettings took 2 Milliseconds to finish	
[2018-04-20 10:18:47.887 GMT 26	Information	101711	Orleans.Runtime.GrainTypeManager]	Loaded grain type summary for 9 types: 
Grain class Orleans.Providers.Orleans.Providers.MemoryStreamQueueGrain [1359359215 (0x51062CEF)] from OrleansProviders.dll implementing interfaces: Orleans.Providers.IMemoryStreamQueueGrain [1158152105 (0x4507FFA9)]
Grain class Orleans.Runtime.Development.Orleans.Runtime.Development.DevelopmentLeaseProviderGrain [940524075 (0x380F422B)] from Orleans.Runtime.dll implementing interfaces: Orleans.Runtime.Development.IDevelopmentLeaseProviderGrain [-1234611069 (0xB6695483)]
Grain class Orleans.Runtime.Management.Orleans.Runtime.Management.ManagementGrain [1954798034 (0x7483D9D2)] from Orleans.Runtime.dll implementing interfaces: Orleans.Runtime.IManagementGrain [-1734666656 (0x989B1660)]
Grain class Orleans.Runtime.MembershipService.Orleans.Runtime.MembershipService.GrainBasedMembershipTableGrain [388921186 (0x172E7762)] from Orleans.Runtime.dll implementing interfaces: Orleans.IMembershipTableGrain [-1256503757 (0xB51B4633)]
Grain class Orleans.Runtime.ReminderService.Orleans.Runtime.ReminderService.GrainBasedReminderTable [-55315191 (0xFCB3F509)] from Orleans.Runtime.dll implementing interfaces: Orleans.IReminderTableGrain [-1135060418 (0xBC585A3E)]
Grain class Orleans.Runtime.Versions.Orleans.Runtime.Versions.VersionStoreGrain [331003096 (0x13BAB4D8)] from Orleans.Runtime.dll implementing interfaces: Orleans.Runtime.Versions.IVersionStoreGrain [-297600501 (0xEE42FA0B)], Orleans.IGrainWithStringKey [-1277021679 (0xB3E23211)]
Grain class Orleans.Storage.Orleans.Storage.MemoryStorageGrain [819348208 (0x30D642F0)] from OrleansProviders.dll implementing interfaces: Orleans.Storage.IMemoryStorageGrain [577125491 (0x22663C73)]
Grain class Orleans.Streams.Orleans.Streams.PubSubRendezvousGrain [1903070868 (0x716E8E94)] from Orleans.Runtime.dll implementing interfaces: Orleans.Streams.IPubSubRendezvousGrain [1746702088 (0x681C8F08)]
Grain class Orleans.TestingHost.Orleans.TestingHost.StorageFaultGrain [165808213 (0x9E20855)] from Orleans.TestingHost.dll implementing interfaces: Orleans.TestingHost.IStorageFaultGrain [-1063077025 (0xC0A2BB5F)], Orleans.IGrainWithStringKey [-1277021679 (0xB3E23211)]
	
[2018-04-20 10:18:47.891 GMT 26	Information	100452	Orleans.Runtime.InsideRuntimeClient]	Start InsideRuntimeClient took 8 Milliseconds	
[2018-04-20 10:18:47.891 GMT 26	Information	100452	Orleans.Runtime.SiloLifecycleSubject]	Lifecycle observer Orleans.Runtime.InsideRuntimeClient started in stage 2000 which took 9 Milliseconds.	
[2018-04-20 10:18:47.893 GMT 26	Information	100452	Orleans.Runtime.SiloLifecycleSubject]	Lifecycle observer Orleans.Runtime.Silo started in stage 2000 which took 14 Milliseconds.	
[2018-04-20 10:18:47.893 GMT 26	Information	100452	Orleans.LifecycleSubject]	Starting lifecycle stage 2000 took 14 Milliseconds	
[2018-04-20 10:18:47.900 GMT 27	Information	0	Orleans.Runtime.Messaging.IncomingMessageAcceptor]	Starting AsyncAgent Runtime.Messaging.IncomingMessageAcceptor on managed thread 27	
[2018-04-20 10:18:47.901 GMT 8	Information	100452	Orleans.Runtime.Silo]	Start Message center took 4 Milliseconds to finish	
[2018-04-20 10:18:47.904 GMT 28	Information	0	Runtime.Messaging.SiloMessageSender/PingSender]	Starting AsyncAgent Runtime.Messaging.SiloMessageSender/PingSender on managed thread 28	
[2018-04-20 10:18:47.907 GMT 29	Information	0	Runtime.Messaging.SiloMessageSender/SystemSender]	Starting AsyncAgent Runtime.Messaging.SiloMessageSender/SystemSender on managed thread 29	
[2018-04-20 10:18:47.909 GMT 8	Information	100452	Orleans.Runtime.Silo]	Start Incoming message agents took 6 Milliseconds to finish	
[2018-04-20 10:18:47.913 GMT 30	Information	0	Runtime.Messaging.IncomingMessageAgent/Ping]	Starting AsyncAgent Runtime.Messaging.IncomingMessageAgent/Ping on managed thread 30	
[2018-04-20 10:18:47.913 GMT 31	Information	0	Runtime.Messaging.IncomingMessageAgent/System]	Starting AsyncAgent Runtime.Messaging.IncomingMessageAgent/System on managed thread 31	
[2018-04-20 10:18:47.915 GMT 32	Information	0	Runtime.Messaging.IncomingMessageAgent/Application]	Starting AsyncAgent Runtime.Messaging.IncomingMessageAgent/Application on managed thread 32	
[2018-04-20 10:18:47.915 GMT 8	Information	0	Orleans.Runtime.GrainDirectory.LocalGrainDirectory]	Start	
[2018-04-20 10:18:47.916 GMT 27	Information	100328	Orleans.Runtime.Messaging.IncomingMessageAcceptor]	Stopping AsyncAgent Runtime.Messaging.IncomingMessageAcceptor that runs on managed thread 27	
[2018-04-20 10:18:47.917 GMT 8	Information	100452	Orleans.Runtime.Silo]	Start local grain directory took 7 Milliseconds to finish	
[2018-04-20 10:18:47.920 GMT 33	Information	0	Runtime.GrainDirectory.AdaptiveDirectoryCacheMaintainer`1]	Starting AsyncAgent Runtime.GrainDirectory.AdaptiveDirectoryCacheMaintainer`1 on managed thread 33	
[2018-04-20 10:18:47.922 GMT 34	Information	0	Runtime.GrainDirectory.GlobalSingleInstanceActivationMaintainer]	Starting AsyncAgent Runtime.GrainDirectory.GlobalSingleInstanceActivationMaintainer on managed thread 34	
[2018-04-20 10:18:47.931 GMT 8	Information	100452	Orleans.Runtime.Silo]	Init implicit stream subscribe table took 11 Milliseconds to finish	
[2018-04-20 10:18:47.931 GMT 34	Information	100328	Runtime.GrainDirectory.GlobalSingleInstanceActivationMaintainer]	Stopping AsyncAgent Runtime.GrainDirectory.GlobalSingleInstanceActivationMaintainer that runs on managed thread 34	
[2018-04-20 10:18:47.983 GMT 10	Information	100452	Orleans.Runtime.Silo]	Create system targets and inject dependencies took 46 Milliseconds to finish	
[2018-04-20 10:18:48.000 GMT 20	Information	100452	Orleans.Runtime.SiloLifecycleSubject]	Lifecycle observer Orleans.Runtime.Silo started in stage 4000 which took 107 Milliseconds.	
[2018-04-20 10:18:48.000 GMT 20	Information	100452	Orleans.LifecycleSubject]	Starting lifecycle stage 4000 took 107 Milliseconds	
[2018-04-20 10:18:48.012 GMT 13	Information	100452	Orleans.Runtime.Silo]	Init transaction agent took 4 Milliseconds to finish	
[2018-04-20 10:18:48.016 GMT 13	Information	100452	Orleans.Runtime.Silo]	Init grain services took 2 Milliseconds to finish	
[2018-04-20 10:18:48.017 GMT 18	Information	100507	Orleans.Runtime.Catalog]	Before collection#1: memory=12MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
[2018-04-20 10:18:48.020 GMT 18	Information	100508	Orleans.Runtime.Catalog]	After collection#1: memory=12MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0104148.	
[2018-04-20 10:18:48.022 GMT 22	Information	100603	Orleans.Runtime.MembershipService.MembershipOracleData]	MembershipOracle starting on host = OptikaLap37 address = S127.0.0.1:27112:261915527 at 2018-04-20 10:18:47.280 GMT, backOffMax = 00:00:20	
[2018-04-20 10:18:48.027 GMT 22	Information	100635	Orleans.Runtime.MembershipService.GrainBasedMembershipTable]	Creating membership table grain	
[2018-04-20 10:18:48.091 GMT 24	Information	100637	Orleans.Runtime.MembershipService.GrainBasedMembershipTableGrain]	GrainBasedMembershipTable Activated.	
[2018-04-20 10:18:48.091 GMT 24	Information	100452	Orleans.LifecycleSubject]	Starting lifecycle stage 2000 took 1 Milliseconds	
[2018-04-20 10:18:48.199 GMT 18	Information	100631	Orleans.Runtime.MembershipService.GrainBasedMembershipTable]	-Connected to membership table provider.	
[2018-04-20 10:18:52.788 GMT 18	Information	100652	Orleans.Runtime.MembershipService.MembershipOracleData]	-CleanupTable called on silo startup. Membership table 0 silos, 0 are Active, 0 are Dead, Version=<0, 0>. All silos: []	
[2018-04-20 10:18:52.862 GMT 18	Information	100660	Orleans.Runtime.MembershipService.MembershipOracleData]	Starting IAmAliveUpdateTimer.	
[2018-04-20 10:18:52.873 GMT 16	Information	100452	Orleans.Runtime.Silo]	Starting local silo status oracle took 4857 Milliseconds to finish	
[2018-04-20 10:18:52.883 GMT 25	Information	0	Orleans.Runtime.TypeManager]	OnRefreshClusterMapTimer: refresh start	
[2018-04-20 10:18:52.886 GMT 8	Information	100452	Orleans.Runtime.Silo]	Init type manager took 12 Milliseconds to finish	
[2018-04-20 10:18:52.887 GMT 8	Information	100702	Orleans.Runtime.CounterStatistic]	Starting Windows perf counter stats collection with frequency=00:00:30	
[2018-04-20 10:18:52.887 GMT 8	Information	100452	Orleans.Runtime.Silo]	Start silo statistics took 1 Milliseconds to finish	
[2018-04-20 10:18:52.893 GMT 18	Information	0	Orleans.Runtime.DeploymentLoadPublisher]	Starting DeploymentLoadPublisher.	
[2018-04-20 10:18:52.905 GMT 18	Information	0	Orleans.Runtime.DeploymentLoadPublisher]	Started DeploymentLoadPublisher.	
[2018-04-20 10:18:52.905 GMT 10	Information	100452	Orleans.Runtime.Silo]	Start deployment load collector took 18 Milliseconds to finish	
[2018-04-20 10:18:52.906 GMT 10	Information	0	Orleans.Runtime.Watchdog]	Starting Silo Watchdog.	
[2018-04-20 10:18:52.917 GMT 18	Information	100452	Orleans.Runtime.SiloLifecycleSubject]	Lifecycle observer Orleans.Runtime.Silo started in stage 8000 which took 4916 Milliseconds.	
[2018-04-20 10:18:52.917 GMT 18	Information	100452	Orleans.LifecycleSubject]	Starting lifecycle stage 8000 took 4917 Milliseconds	
[2018-04-20 10:18:52.920 GMT 35	Information	0	Runtime.Watchdog]	Starting AsyncAgent Runtime.Watchdog on managed thread 35	
[2018-04-20 10:18:52.920 GMT 18	Information	100452	Orleans.Runtime.SiloLifecycleSubject]	Lifecycle observer Orleans.Runtime.Versions.GrainVersionStore started in stage 10000 which took 2 Milliseconds.	
[2018-04-20 10:18:52.920 GMT 18	Information	100452	Orleans.LifecycleSubject]	Starting lifecycle stage 10000 took 2 Milliseconds	
[2018-04-20 10:18:52.928 GMT 14	Information	100452	Orleans.Runtime.Silo]	Start gateway took 5 Milliseconds to finish	
[2018-04-20 10:18:52.953 GMT 36	Information	0	Orleans.Runtime.Messaging.IncomingMessageAcceptor]	Starting AsyncAgent Runtime.Messaging.GatewayAcceptor on managed thread 36	
[2018-04-20 10:18:52.953 GMT 37	Information	0	Runtime.Messaging.GatewayClientCleanupAgent]	Starting AsyncAgent Runtime.Messaging.GatewayClientCleanupAgent on managed thread 37	
[2018-04-20 10:18:52.953 GMT 36	Information	100328	Orleans.Runtime.Messaging.IncomingMessageAcceptor]	Stopping AsyncAgent Runtime.Messaging.GatewayAcceptor that runs on managed thread 36	
[2018-04-20 10:18:52.965 GMT 18	Information	100604	Orleans.Runtime.MembershipService.MembershipOracleData]	-BecomeActive	
[2018-04-20 10:18:52.971 GMT 18	Information	100614	Orleans.Runtime.MembershipService.MembershipOracleData]	About to send pings to 0 nodes in order to validate communication in the Joining state. Pinged nodes = []	
[2018-04-20 10:18:52.981 GMT 18	Information	100634	Orleans.Runtime.MembershipService.MembershipOracleData]	-ReadAll (called from BecomeActive) Membership table 1 silos, 1 are Active, 0 are Dead, Version=<2, 5>. All silos: [SiloAddress=S127.0.0.1:27112:261915527 SiloName=Primary Status=Active]	
[2018-04-20 10:18:52.982 GMT 18	Information	100605	Orleans.Runtime.MembershipService.MembershipOracleData]	-Finished BecomeActive.	
[2018-04-20 10:18:52.983 GMT 8	Information	100452	Orleans.Runtime.Silo]	Starting local silo status oracle took 54 Milliseconds to finish	
[2018-04-20 10:18:52.983 GMT 25	Information	100452	Orleans.Runtime.SiloLifecycleSubject]	Lifecycle observer Orleans.Runtime.Silo started in stage 19999 which took 62 Milliseconds.	
[2018-04-20 10:18:52.983 GMT 25	Information	100452	Orleans.LifecycleSubject]	Starting lifecycle stage 19999 took 62 Milliseconds	
[2018-04-20 10:18:52.997 GMT 18	Information	100452	Orleans.Runtime.SiloLifecycleSubject]	Lifecycle observer Orleans.Runtime.Silo started in stage 20000 which took 14 Milliseconds.	
[2018-04-20 10:18:52.997 GMT 18	Information	100452	Orleans.LifecycleSubject]	Starting lifecycle stage 20000 took 14 Milliseconds	
[2018-04-20 10:19:48.025 GMT 18	Information	100507	Orleans.Runtime.Catalog]	Before collection#2: memory=12MB, #activations=1, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
[2018-04-20 10:19:48.027 GMT 18	Information	100508	Orleans.Runtime.Catalog]	After collection#2: memory=12MB, #activations=1, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0020846.	
[2018-04-20 10:19:52.885 GMT 18	Information	0	Orleans.Runtime.TypeManager]	OnRefreshClusterMapTimer: refresh start	
[2018-04-20 10:20:48.032 GMT 22	Information	100507	Orleans.Runtime.Catalog]	Before collection#3: memory=13MB, #activations=1, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
[2018-04-20 10:20:48.032 GMT 22	Information	100508	Orleans.Runtime.Catalog]	After collection#3: memory=13MB, #activations=1, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0004580.	
[2018-04-20 10:21:48.042 GMT 18	Information	100507	Orleans.Runtime.Catalog]	Before collection#4: memory=14MB, #activations=1, collector=<#Activations=0, #Buckets=0, buckets=[]>.	

```

I have tried:
- Using an ADONET provider for clustering (created tables and registered properly, but also did not progress)
- Manually setting BaseSilo/GatewayPort
- Moving the code out of the xunit fixture
- Moving the code out of the xunit fixture and using DeployAsync() instead
- Changing the number of silos initially created
- Probably a number of other things.

None of it worked - still hangs on Deploy(). I'm also unable to step into Deploy() to see where it's getting hung up, even though I have the pdbs loaded.

EDIT:

The same issue also occurs using the start SiloHost/Client functions:

```
var builder = new SiloHostBuilder();
            builder.UseLocalhostClustering();
            builder.ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(AkumenGrain).Assembly).WithCodeGeneration());
            builder.ConfigureLogging(logging => logging.SetMinimumLevel(LogLevel.Debug).AddDebug());
            SiloHost = builder.Build();

            // start the silo
            SiloHost.StartAsync().Wait();

            var clientBuilder = new ClientBuilder();
            clientBuilder.UseLocalhostClustering();
            clientBuilder.ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(AkumenGrain).Assembly).WithCodeGeneration());
            builder.ConfigureLogging(logging => logging.SetMinimumLevel(LogLevel.Debug).AddDebug());
            Client = clientBuilder.Build();

            // start the client
            Client.Connect().Wait();
```

As per @ReubenBond's suggestion, changing it to `Task.Run(() => SiloHost.StartAsync()).Wait();` allows it to continue successfully.

**Comment by Murodese** [comment]
The same is also required for a silo.StopAsync() / client.Close() call during Dispose(), else the tests will wait forever.

**Comment by benjaminpetit** [comment]
Not sure what is different between your environment and what we have in Orleans tests, but we use the synchronous method `Deploy()` in some ctor of test clasees?

**Comment by Murodese** [comment]
My test project is basically modeled off yours, so there's barely any difference - just some minor variations in cluster setup. I can try to make a minimal repro, but it'll take a few days - pretty busy at the moment.

**Comment by clegendre** [comment]
Hello,

Same issue here, but found why. 
Connections are refused on localhost, whether it is on netcoreapp2.0 or net461, when I specified "UseLocalhostClustering()" on client and server configurations:
`clientBuilder.UseLocalhostClustering()`
`hostBuilder.UseLocalhostClustering()`

When it is not specified (which I suspect is the default for the TestCluster), issue disapear and silos are deployed.

```[2018-04-24 08:14:32.026 GMT 33	Warning	101021	Runtime.Messaging.SiloMessageSender/SystemSender]	Exception getting a sending socket to endpoint S127.0.0.1:11111:0	
Exc level 0: Orleans.Runtime.OrleansException: Could not connect to 127.0.0.1:11111: ConnectionRefused
   at Orleans.Runtime.SocketManager.Connect(Socket s, IPEndPoint endPoint, TimeSpan connectionTimeout)
   at Orleans.Runtime.SocketManager.SendingSocketCreator(IPEndPoint target)
   at Orleans.Runtime.LRU`2.Get(TKey key)
   at Orleans.Runtime.Messaging.SiloMessageSender.GetSendingSocket(Message msg, Socket& socket, SiloAddress& targetSilo, String& error)
[2018-04-24 08:14:32.040 GMT 28	Error	100071	Orleans.Runtime.Dispatcher]	!!!!!!!!!! SelectTarget failed with Silo S127.0.0.1:28660:262253670 is rejecting message: Request S127.0.0.1:28660:262253670*stg/14/0000000e@S0000000e->S127.0.0.1:11111:0*stg/10/0000000a@S0000000a #3: . Reason = Exception getting a sending socket to endpoint S127.0.0.1:11111:0	
Exc level 0: Orleans.Runtime.OrleansMessageRejectionException: Silo S127.0.0.1:28660:262253670 is rejecting message: Request S127.0.0.1:28660:262253670*stg/14/0000000e@S0000000e->S127.0.0.1:11111:0*stg/10/0000000a@S0000000a #3: . Reason = Exception getting a sending socket to endpoint S127.0.0.1:11111:0```

**Comment by ReubenBond** [comment]
Closing due to inactivity. If this is still an issue, feel free to reopen 😊
