### ISSUE TITLE
[2.0] Build-time Code Generation fails when referencing a project that contains service references.

### ISSUE THREAD

**Issue by Murodese** [dotnet/orleans#4500]
As above. With a library targeting .NET Standard 2.0, a grain interface project references a project that contains a service reference, leading to the following build-time error:

```
13>Orleans-CodeGen - Generating file C:\<company>\<project>.ExecutionGrains.Interfaces\obj\Debug\netstandard2.0\<project>.ExecutionGrains.Interfaces.orleans.g.cs
13>warn: Orleans.CodeGenerator.RoslynCodeGenerator[101723]
13>      Exception loading types from assembly '<project>.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null':
13>      Exc level 0: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
13>         at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
13>         at System.Reflection.RuntimeAssembly.get_DefinedTypes()
13>         at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, ILogger logger) in D:\build\agent2\_work\8\s\src\Orleans.Core\CodeGeneration\TypeUtils.cs:line 561
13>      Exc level 1: System.BadImageFormatException: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
13>      Exc level 2: System.BadImageFormatException: Cannot load a reference assembly for execution.
13>      Exc level 1: System.BadImageFormatException: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
13>      Exc level 2: System.BadImageFormatException: Cannot load a reference assembly for execution.
13>      Exc level 1: System.BadImageFormatException: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
13>      Exc level 2: System.BadImageFormatException: Cannot load a reference assembly for execution.
13>      Exc level 1: System.BadImageFormatException: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
13>      Exc level 2: System.BadImageFormatException: Cannot load a reference assembly for execution.
13>      Exc level 1: System.BadImageFormatException: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
13>      Exc level 2: System.BadImageFormatException: Cannot load a reference assembly for execution.
13>      Exc level 1: System.BadImageFormatException: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
13>      Exc level 2: System.BadImageFormatException: Cannot load a reference assembly for execution.
13>      Exc level 1: System.BadImageFormatException: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
13>      Exc level 2: System.BadImageFormatException: Cannot load a reference assembly for execution.
13>      Exc level 1: System.BadImageFormatException: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
13>      Exc level 2: System.BadImageFormatException: Cannot load a reference assembly for execution..
13>System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
13>   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
13>   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
13>   at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, ILogger logger) in D:\build\agent2\_work\8\s\src\Orleans.Core\CodeGeneration\TypeUtils.cs:line 561
13>-- Code Generation FAILED --
13>
13>Exc level 0: System.ArgumentException: A BadImageFormatException has been thrown while parsing the signature. This is likely due to lack of a generic context. Ensure genericTypeArguments and genericMethodArguments are provided and contain enough context.
13>   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
13>   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
13>   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
13>   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
13>   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
13>   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
13>   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
13>   at Orleans.CodeGenerator.RoslynCodeGenerator.AddSerializationTypes(SerializationTypeDescriptions serializationTypes, Assembly targetAssembly, List`1 assemblies) in D:\build\agent2\_work\8\s\src\Orleans.CodeGeneration\RoslynCodeGenerator.cs:line 434
13>   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateCode(Assembly targetAssembly, List`1 assemblies) in D:\build\agent2\_work\8\s\src\Orleans.CodeGeneration\RoslynCodeGenerator.cs:line 327
13>   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateSourceForAssembly(Assembly input) in D:\build\agent2\_work\8\s\src\Orleans.CodeGeneration\RoslynCodeGenerator.cs:line 162
13>   at Orleans.CodeGeneration.CodeGenerator.GenerateSourceForAssembly(Assembly grainAssembly, LogLevel logLevel)
13>   at Orleans.CodeGeneration.CodeGenerator.GenerateCodeInternal(CodeGenOptions options)
13>   at Orleans.CodeGeneration.CodeGenerator.GenerateCode(CodeGenOptions options)
13>   at Orleans.CodeGeneration.Program.Main(String[] args)
13>Exc level 1: System.BadImageFormatException: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
13>   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
13>   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
13>   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
13>Exc level 2: System.BadImageFormatException: Cannot load a reference assembly for execution.
13>C:\Users\user\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.0.0\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets(76,5): error MSB3073: The command ""dotnet" "C:\Users\user\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.0.0\build\..\tasks\netcoreapp2.0\Orleans.CodeGeneration.Build.dll" "@obj\Debug\netstandard2.0\codegen\<project>.ExecutionGrains.Interfaces.orleans.g.args.txt"" exited with code 3.
13>Done building project "<project>.ExecutionGrains.Interfaces.csproj" -- FAILED.
```

**Comment by ReubenBond** [comment]
In the event that we are generating code for a .NET Standard library, we may have to first build the project as .NET Core in order to correctly resolve the referenced assemblies to loadable versions.

**Comment by apatenotre** [comment]
hi @ReubenBond , I am facing the same issue here. Any known workaround ?

**Comment by apatenotre** [comment]
> hi @ReubenBond , I am facing the same issue here. Any known workaround ?
Okay, I fixed it by moving grains (and therefore codegen package) out of the silo project, where the service reference is used (during DI configuration)
