### ISSUE TITLE
Running on dotnetcore on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by ppumkin** [dotnet/orleans#4522]
* Standard Ubuntu on Windows 10 **Windows Subsytem for Linux** (WSL )
* Installed dotnecore SDK as per 
* * https://www.microsoft.com/net/learn/get-started/linux/ubuntu16-04
* * Version 2.1.105
* Simple Hello world project compiled on the Ubuntu WSL using `dotnet restore` and `dotnet run`
* _Tested on Ubuntu 16.04 on Virtualbox and this does not happen. It is specific to WSL_

Project configuration for Silo which will not start

  ```
   var silo = new SiloHostBuilder()
               // Clustering information
               .Configure<ClusterOptions>(options =>
               {
                   options.ClusterId = "my-first-cluster";
                    options.ServiceId = "MyAwesomeOrleansService";
               })
               // Clustering provider
               .UseAzureStorageClustering(options => options.ConnectionString = azureTableConnectionString)
               // Endpoints
               .ConfigureEndpoints(siloPort: Int32.Parse(args[1]), gatewayPort: Int32.Parse(args[2]))
               //.ConfigureEndpoints(siloPort: 11111, gatewayPort: 30000)
               // Now create the silo!
               .ConfigureLogging(logging => logging.AddConsole())
               .Build();
```

Exception Aggregate 

> Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'
> Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'
> Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'
> Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'
> Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'
> Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'
> Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (An error was encountered while querying information from the operating system.) ---> System.Net.NetworkInformation.NetworkInformationException: An error was encountered while querying information from the operating system. ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'.) ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at Orleans.Runtime.Configuration.ConfigUtilities.<ResolveIPAddress>d__18.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Orleans.Hosting.EndpointOptionsExtensions.ConfigureEndpoints(ISiloHostBuilder builder, Int32 siloPort, Int32 gatewayPort, AddressFamily addressFamily, Boolean listenOnAnyHostAddress)
   at Kula1Orleans.SiloHost.Program.<Main>d__0.MoveNext() in /mnt/c/Users/piotr.kula/source/repos/Kula1Orleans/Kula1Orleans.SiloHost/Program.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kula1Orleans.SiloHost.Program.<Main>(String[] args)

```

There is a related issue on marked as BUG

https://github.com/dotnet/corefx/issues/22048

Any work around to get this working or should I not push my luck with WSL ?

**Comment by benjaminpetit** [comment]
You could try to specify manually the ip to use in the `EndpointOptions` but I would not be surprised if it doesn't work

**Comment by benjaminpetit** [comment]
Closing this one for inactivity. Let me know if you still have trouble running on WSL even with the workaround I provided

**Comment by ahadortiz** [comment]
I have the same issue
I try to install [neo-cli](https://github.com/neo-project/neo-cli) on subsystem, but I get the same issue.
I'm not sure which team I should report this issue

**Comment by ppumkin** [comment]
I never got this to work.. it was more of an experiment really. You should probably run it in a VM or docker instead. Don't use WSL it is quite limited on access to some resources..

**Comment by ahadortiz** [comment]
I see
I'll try to install neo-cli on windows and connect it from subsystem
Thanks anyway
