### ISSUE TITLE
Error during serialization of Entity Framework objects

### ISSUE THREAD

**Issue by ifle** [dotnet/orleans#4530]
If Lazy Load enabled in EF, the serialization process throws ArgumentException: Invalid token for impersonation - it cannot be duplicated error

```c#
var order = db.ORDERS.FirstOrDefault();
await GrainFactory.GetGrain<IOrderProcessor>().Execute(order);

```

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at Orleans.Serialization.BinaryFormatterSerializer.DeepCopy(Object source, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original, ICopyContext context)
   at Orleans.Serialization.ILBasedSerializer.DeepCopy(Object source, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original, ICopyContext context)
   at Orleans.Serialization.ILBasedSerializer.DeepCopy(Object source, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original, ICopyContext context)
   at Orleans.Serialization.ILBasedSerializer.DeepCopy(Object source, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original, ICopyContext context)
   at Orleans.Serialization.ILBasedSerializer.DeepCopy(Object source, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original, ICopyContext context)
   at Orleans.Serialization.ILBasedSerializer.DeepCopy(Object source, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original, ICopyContext context)
   at Orleans.Serialization.ILBasedSerializer.DeepCopy(Object source, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original, ICopyContext context)
   at Orleans.Serialization.BuiltInTypes.<>c__DisplayClass12_0`1.<DeepCopyList>b__0(T element)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Orleans.Serialization.BuiltInTypes.DeepCopyList[T](Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopy(Object original)
   at Orleans.Runtime.GrainReferenceRuntime.InvokeMethodAsync[T](GrainReference reference, Int32 methodId, Object[] arguments, InvokeMethodOptions options, SiloAddress silo)
   at PIfle.Server.Abstractions.OrleansCodeGenAssigmentPDGrainServiceReference.Run(List`1 newOrders)
 
Inner Exception 1:
ArgumentException: Invalid token for impersonation - it cannot be duplicated

```

**Comment by ReubenBond** [comment]
This exception is coming from `BinaryFormatter`. I would recommend not using Lazy Loading in an Orleans application. Lazy Loading requires blocking IO which can cause performance problems. Load the objects eagerly instead using async operations only.

**Comment by ReubenBond** [comment]
Closing due to inactivity
