### ISSUE TITLE
Using IoT Hub with streams

### ISSUE THREAD

**Issue by andrew-laughlin** [dotnet/orleans#4572]
My goal is to read events from an IoT Hub and process those events in grains. I wasn't able to find docs on this anywhere, but would be grateful if someone would point me in the right direction.

I've used the following code to configure the connection to the IoT Hub. I'm using the Event Hub compatible endpoint.

```
.AddEventHubStreams("EventHubProvider", shConfig =>
{
	shConfig.ConfigureEventHub(opts =>
	{
		opts.Configure(options =>
		{
			options.ConnectionString = "Endpoint=event hub compatible endpoint -- <SNIP> --";
			options.ConsumerGroup = "MyConsumerGroup";
			options.Path = "EventHubCompatibleName";
		});
	})
	.UseEventHubCheckpointer(opts => opts.Configure(options =>
	{
		options.ConnectionString = "DefaultEndpointsProtocol=https;AccountName= -- <SNIP> --"
	}));
});
```

I've created a simple grain and wired it to an implicit stream. However I'm not sure what namespace to use?

`[ImplicitStreamSubscription("WhatShouldThisBe?"]`

When I startup the Silo host, Orleans connects and begins reading messages:

```
info: Orleans.ServiceBus.Providers.EventHubAdapterReceiver.hub-myHub.20[0]
      Starting to read latest messages from EventHub partition hub-myHub-20 at offset 29716696
```

When a message is received, an exception is throw in the `EventHubDataAdapter` because partition key is null in the event data:

```
public virtual StreamPosition GetStreamPosition(EventData queueMessage)
        {
            Guid streamGuid =
            Guid.Parse(queueMessage.SystemProperties.PartitionKey); // PartitionKey is null
...
}

```

My intended design is to have a grain per device, and have those grains implicitly wired to a stream based on device ID. How should I setup the grain? What does the stream config look like (e.g. namespace and GUID)?

Best,
Andrew

**Comment by andrew-laughlin** [comment]
I think I figured this out. It required extending: `EventHubAdapterFactory, EventHubDataAdapter` and `EventHubQueueCacheFactory` with custom implementations, and implementing `IBatchContainer` to control stream creation.

At this point we're able to read events off an IoT Hub, put them on an implicit stream and have a subscribing grain ingest them.

**Comment by ejlevin1** [comment]
I've spent some time on trying to get the AddEventHubStreams to put from the IOT Hubs default endpoint, and I'm running into the same issues that @andrew-laughlin is reporting here... @jason-bragg I noticed that much of this code was written by you, so I'm hoping you can help as I may just be doing something wrong.  Here is what I've got -- and I'm hoping I am just doing something stupid and don't need to extend all the classes as Andrew did.

```
private static async Task<ISiloHost> StartSilo()
{
    // define the cluster configuration
    var builder = new SiloHostBuilder()
        .UseLocalhostClustering()
        .Configure<ClusterOptions>(options =>
        {
            options.ClusterId = "dev";
            options.ServiceId = "HelloWorldApp";
        })
        .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
        .AddMemoryGrainStorage("PubSubStore")
        .AddEventHubStreams("Source.AntEvents", (SiloEventHubStreamConfigurator c) => {
            c.ConfigureEventHub((opts) =>
            {
                opts.Configure(options =>
                {
                    options.ConnectionString = "Endpoint=sb://iothub-ns-**********.servicebus.windows.net/;SharedAccessKeyName=<owner>;SharedAccessKey=<key>;EntityPath=ao-iot-dev-1";
                    options.ConsumerGroup = "OrleansSiloHost";
                    options.Path = "ao-iot-dev-1";
                });
            })
            .UseEventHubCheckpointer(opts => opts.Configure(options =>
            {
                options.ConnectionString = <connection string>;
                options.TableName = "orleanspubsubtbl";
                options.PersistInterval = TimeSpan.FromSeconds(1);
            }))
            .ConfigureStreamPubSub(StreamPubSubType.ImplicitOnly);
        })
        .ConfigureLogging(logging => logging.AddConsole());

    var host = builder.Build();
    await host.StartAsync();
    return host;
}
```

Here is my Implicit Receiver Grain:
```
[ImplicitStreamSubscription("iothub-ns-**********")]
    public class EventHubSubscriber : Grain, IEventHubSubscriber, IAsyncObserver<string>
    {
        public async override Task OnActivateAsync()
        {
            var streamProvider = GetStreamProvider(SiloHostProviders.AntPlusStreamingProvider);
            var stream = streamProvider.GetStream<string>(this.GetPrimaryKey(), "iothub-ns-**********");
            await stream.SubscribeAsync(this);
        }

        public Task OnCompletedAsync()
        {
            Console.WriteLine("Completed.");
            return Task.CompletedTask;
        }

        public Task OnErrorAsync(Exception ex)
        {
            Console.WriteLine("ERROR: " + ex.Message);
            return Task.CompletedTask;
        }

        public Task OnNextAsync(string item, StreamSequenceToken token = null)
        {
            Console.WriteLine("Received: " + item);
            return Task.CompletedTask;
        }
    }
```

And here is the error output.  Line 252 is where it is trying to parse the partition ID; however, the partitions are showing in the logging as 0 and 1 which are hooked up to Queues.

```
info: Orleans.Streams.PersistentStreamPullingManager-Source.AntEvents[103502]
      Init.
info: Orleans.Streams.PersistentStreamPullingManager-Source.AntEvents[103503]
      Initialize: I am now responsible for 2 queues: [source.antevents-0, source.antevents-1].
info: Orleans.Streams.PersistentStreamPullingManager-Source.AntEvents[103517]
      Starting agents for 2 queues: [source.antevents-0, source.antevents-1]
info: Orleans.Streams.*stg/1515185665224622770/b07a42b2.Source.AntEvents[103301]
      Created PersistentStreamPullingAgent *stg/1515185665224622770/4e5cba2a2274a31c15070555b07a42b201000000000000ff-0x26156FA1 for Stream Provider Source.AntEvents on silo S127.0.0.1:11111:289281871 for Queue source.antevents-0-0x00000000.
info: Orleans.Streams.*stg/3261463326979622579/ac9586b3.Source.AntEvents[103301]
      Created PersistentStreamPullingAgent *stg/3261463326979622579/42fdbe1d2be353442d430b9dac9586b301000000000000ff-0xD22CAFD5 for Stream Provider Source.AntEvents on silo S127.0.0.1:11111:289281871 for Queue source.antevents-1-0x80000001.
info: Orleans.Streams.*stg/1515185665224622770/b07a42b2.Source.AntEvents[103302]
      Init of PersistentStreamPullingAgent *stg/1515185665224622770/4e5cba2a2274a31c15070555b07a42b201000000000000ff-0x26156FA1 on silo S127.0.0.1:11111:289281871 for queue source.antevents-0-0x00000000.
info: Orleans.Streams.*stg/3261463326979622579/ac9586b3.Source.AntEvents[103302]
      Init of PersistentStreamPullingAgent *stg/3261463326979622579/42fdbe1d2be353442d430b9dac9586b301000000000000ff-0xD22CAFD5 on silo S127.0.0.1:11111:289281871 for queue source.antevents-1-0x80000001.
info: Orleans.ServiceBus.Providers.EventHubAdapterReceiver.ao-iot-dev-1.0[0]
      Initializing EventHub partition ao-iot-dev-1-0.
info: Orleans.ServiceBus.Providers.EventHubAdapterReceiver.ao-iot-dev-1.1[0]
      Initializing EventHub partition ao-iot-dev-1-1.
info: Orleans.ServiceBus.Providers.EventHubCheckpointer[0]
      Creating EventHub checkpointer for partition 1 of stream provider Source.AntEvents with serviceId HelloWorldApp.
info: Orleans.ServiceBus.Providers.EventHubCheckpointer[0]
      Creating EventHub checkpointer for partition 0 of stream provider Source.AntEvents with serviceId HelloWorldApp.
info: Orleans.Streams.*stg/1515185665224622770/b07a42b2.Source.AntEvents[103304]
      Taking queue source.antevents-0-0x00000000 under my responsibility.
info: Orleans.Streams.*stg/3261463326979622579/ac9586b3.Source.AntEvents[103304]
      Taking queue source.antevents-1-0x80000001 under my responsibility.
info: Orleans.Streams.PersistentStreamPullingManager-Source.AntEvents[103508]
      Added 2 new queues: [source.antevents-0, source.antevents-1]. Now own total of 2 queues: [source.antevents-0, source.antevents-1]
info: Orleans.Streams.PersistentStreamPullingManager-Source.AntEvents[103519]
      Started agents.
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      Lifecycle observer Orleans.Providers.Streams.Common.PersistentStreamProvider-Source.AntEvents started in stage 20000 which took 156 Milliseconds.
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      Starting lifecycle stage 20000 took 156.4409 Milliseconds
info: Orleans.Streaming.EventHubs.AzureTableDataManager[100801]
      Attached to Azure storage table orleanspubsubtbl
info: Orleans.Streaming.EventHubs.AzureTableDataManager[100801]
      Attached to Azure storage table orleanspubsubtbl
info: Orleans.ServiceBus.Providers.EventHubAdapterReceiver.ao-iot-dev-1.0[0]
      Starting to read latest messages from EventHub partition ao-iot-dev-1-0 at offset -1
info: Orleans.ServiceBus.Providers.EventHubAdapterReceiver.ao-iot-dev-1.1[0]
      Starting to read latest messages from EventHub partition ao-iot-dev-1-1 at offset 105560
      ...........
      ...........
      ...........
info: Orleans.Runtime.Catalog[100507]
      Before collection#2: memory=9MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.
info: Orleans.Runtime.Catalog[100508]
      After collection#2: memory=9MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0019287.
warn: Orleans.Streams.*stg/3261463326979622579/ac9586b3.Source.AntEvents[103312]
      Exception while retrying the 0th time reading from queue source.antevents-1
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Guid.Parse(String input)
   at Orleans.ServiceBus.Providers.EventHubDataAdapter.GetStreamPosition(EventData queueMessage) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubDataAdapter.cs:line 252
   at Orleans.ServiceBus.Providers.EventHubDataAdapter.QueueMessageToCachedMessage(CachedEventHubMessage& cachedMessage, EventData queueMessage, DateTime dequeueTimeUtc) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubDataAdapter.cs:line 205
   at Orleans.Providers.Streams.Common.CachedMessageBlock`1.Add[TQueueMessage](TQueueMessage queueMessage, DateTime dequeueTimeUtc, ICacheDataAdapter`2 dataAdapter) in D:\build\agent\_work\24\s\src\OrleansProviders\Streams\Common\PooledCache\CachedMessageBlock.cs:line 118
   at Orleans.Providers.Streams.Common.CachedMessagePool`2.AllocateMessage(TQueueMessage queueMessage, DateTime dequeueTimeUtc, StreamPosition& streamPosition) in D:\build\agent\_work\24\s\src\OrleansProviders\Streams\Common\PooledCache\CachedMessagePool.cs:line 42
   at Orleans.Providers.Streams.Common.PooledQueueCache`2.Add(TQueueMessage message, DateTime dequeueTimeUtc) in D:\build\agent\_work\24\s\src\OrleansProviders\Streams\Common\PooledCache\PooledQueueCache.cs:line 330
   at Orleans.Providers.Streams.Common.PooledQueueCache`2.Add(List`1 messages, DateTime dequeueTime) in D:\build\agent\_work\24\s\src\OrleansProviders\Streams\Common\PooledCache\PooledQueueCache.cs:line 312
   at Orleans.ServiceBus.Providers.EventHubQueueCache`1.Add(List`1 messages, DateTime dequeueTimeUtc) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubQueueCache.cs:line 136
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.GetQueueMessagesAsync(Int32 maxCount) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubAdapterReceiver.cs:line 190
   at Orleans.Streams.PersistentStreamPullingAgent.ReadFromQueue(QueueId myQueueId, IQueueAdapterReceiver rcvr, Int32 maxCacheAddCount) in D:\build\agent\_work\24\s\src\Orleans.Runtime\Streams\PersistentStream\PersistentStreamPullingAgent.cs:line 435
   at Orleans.AsyncExecutorWithRetries.ExecuteWithRetriesHelper[T](Func`2 function, Int32 callCounter, Int32 maxNumSuccessTries, Int32 maxNumErrorTries, TimeSpan maxExecutionTime, DateTime startExecutionTime, Func`3 retryValueFilter, Func`3 retryExceptionFilter, IBackoffProvider onSuccessBackOff, IBackoffProvider onErrorBackOff) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\AsyncExecutorWithRetries.cs:line 143
```

**Comment by aloysiustany** [comment]
@andrew-laughlin any reason why you did not use AddEventHubStreams ?
