### ISSUE TITLE
Problem starting single silo cluster after ungraceful silo shutdown

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#4664]
The default cluster membership options will have it take 10 minutes of failing to contact another silo before it can be marked dead, but only 5 minutes for a new silo to attempt to join a cluster. This results in a 5 minute window where a new silo can't join the cluster if the previous silo(s) was ungracefully shutdown.
I can certainly change the timeouts in our application, but I'm a) not super familiar with their function and b) wondering if the defaults should prevent that situation.

The other problem is that the new silo continues to run after failing to join and doesn't seem to try again. Perhaps I am missing some configuration or a try/catch, but I would like to not leave a silo around in a broken state.

**Comment by benjaminpetit** [comment]
> This results in a 5 minute window where a new silo can't join the cluster if the previous silo(s) was ungracefully shutdown

I believe that silos can recognize an old entry of themselves (same ip/port but different generation number) and clean it up before trying to join the cluster. But it's not working for container since you always get a different ip address...

Yes you could change default timeout.

> The other problem is that the new silo continues to run after failing to join and doesn't seem to try again. Perhaps I am missing some configuration or a try/catch, but I would like to not leave a silo around in a broken state.

That's waird, could you post your init code?

**Comment by sergeybykov** [comment]
>The default cluster membership options will have it take 10 minutes of failing to contact another silo before it can be marked dead

Do you mean it takes 10 minutes to mark a silo dead in a cluster that went abruptly gone, like a 1-silo dev cluster that got killed? Because in a cluster it takes by default ~30 seconds for other silos to mark the missing one dead.

You can also turn off `ClusterMembershipOptions.ValidateInitialConnectivity` to allow silo to join cluster without trying to connect to other silos already listed in the cluster. This is not recommended for production, but may help in development scenarios. Although the easiest and cleanest way for development cases is to generate a new cluster ID for every run.

**Comment by jsteinich** [comment]
Thanks for the different suggestions.

Here is trimmed version of our init code:
```c#
private static ISiloHost silo;
private static readonly ManualResetEvent SiloStopped = new ManualResetEvent(false);

private static void Main()
{
	...
	ISiloHostBuilder builder = new SiloHostBuilder()
		.Configure<ClusterOptions>(options => options.ClusterId = environment)
		.ConfigureClustering()
		.ConfigureEndpoints(siloAddress, SiloPort, GatewayPort, true)
		...
		;

	silo = builder.Build();

	Task.Run(StartSilo);

	AssemblyLoadContext.Default.Unloading += context =>
	{
		logger.LogInformation("ProcessExit fired");
		Task.Run(StopSilo);
		SiloStopped.WaitOne();
	};

	SiloStopped.WaitOne();
}

private static ISiloHostBuilder ConfigureClustering(this ISiloHostBuilder builder)
{
	builder.UseDynamoDBClustering(options =>
	{
		options.Service = service;
	});
	return builder;
}

private static async Task StartSilo()
{
	await silo.StartAsync();
	logger.LogInformation("Silo started");
}

private static async Task StopSilo()
{
	await silo.StopAsync();
	logger.LogInformation("Silo stopped");
	SiloStopped.Set();
}
```

When the problem occurred I never saw "Silo started" log so it is possible an exception was thrown and just not logged, but I would have expected something to bubble up.

**Comment by benjaminpetit** [comment]
> You can also turn off ClusterMembershipOptions.ValidateInitialConnectivity to allow silo to join cluster without trying to connect to other silos already listed in the cluster.

Instead of having clear error at startup, you will have weird errors at runtime for a while... not sure if it is a good idea, even in dev

@jsteinich do you see the errors in the logs?

**Comment by jsteinich** [comment]
I see this sequence repeated a bunch:
```c#
[21:48:27 INF] About to send pings to 1 nodes in order to validate communication in the Joining state. Pinged nodes = [[SiloAddress=S<old silo>:265814527 SiloName=Silo_e4f19 Status=Active HostName=14a53fdcdd6e ProxyPort=40000 RoleName= UpdateZone=0 FaultZone=0 StartTime = 2018-06-04 13:22:08.081 GMT IAmAliveTime = 2018-06-06 21:47:19.782 GMT ]]
[21:48:30 WRN] Exception getting a sending socket to endpoint S<old silo>:265814527
Orleans.Runtime.OrleansException: Could not connect to <old silo>: HostUnreachable
at Orleans.Runtime.SocketManager.Connect(Socket s, IPEndPoint endPoint, TimeSpan connectionTimeout)
at Orleans.Runtime.SocketManager.SendingSocketCreator(IPEndPoint target)
at Orleans.Runtime.LRU`2.Get(TKey key)
at Orleans.Runtime.Messaging.SiloMessageSender.GetSendingSocket(Message msg, Socket& socket, SiloAddress& targetSilo, String& error)
[21:48:30 WRN] -Did not get ping response for ping #0 from S<old silo>:265814527. Reason = Original Exc Type: Orleans.Runtime.OrleansMessageRejectionException Message:Silo S<new silo>:266017691 is rejecting message: Request S<new silo>:266017691*stg/15/0000000f@S0000000f->S<old silo>:265814527*stg/15/0000000f@S0000000f #2: . Reason = Exception getting a sending socket to endpoint S<old silo>:265814527
[21:48:30 ERR] -Failed to get ping responses from all 1 silos that are currently listed as Active in the Membership table. Newly joining silos validate connectivity with all pre-existing silos that are listed as Active in the table and have written I Am Alive in the table in the last 00:10:00 period, before they are allowed to join the cluster. Active silos are: [[SiloAddress=S<old silo>:265814527 SiloName=Silo_e4f19 Status=Active HostName=14a53fdcdd6e ProxyPort=40000 RoleName= UpdateZone=0 FaultZone=0 StartTime = 2018-06-04 13:22:08.081 GMT IAmAliveTime = 2018-06-06 21:47:19.782 GMT ]]
```

Then when the timeout occurred I see this:
```c#
[21:53:26 WRN] Watchdog had 1 Health Check Failure(s) out of 2 Health Check Participants.
[21:53:27 ERR] Lifecycle observer Orleans.Runtime.Silo failed to start due to errors at stage 19999.
System.TimeoutException: MembershipOracle activating failed due to timeout 00:05:00
at Orleans.OrleansTaskExtentions.<WithTimeout>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Silo.<<OnBecomeActiveStart>g__BecomeActive72_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Silo.<StartAsyncTaskWithPerfAnalysis>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Silo.<OnBecomeActiveStart>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.<OnStart>d__9.MoveNext()
[21:53:27 ERR] Lifecycle start canceled due to errors at stage 19999
System.TimeoutException: MembershipOracle activating failed due to timeout 00:05:00
at Orleans.OrleansTaskExtentions.<WithTimeout>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Silo.<<OnBecomeActiveStart>g__BecomeActive72_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Silo.<StartAsyncTaskWithPerfAnalysis>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Silo.<OnBecomeActiveStart>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.<OnStart>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.LifecycleSubject.<WrapExecution>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.LifecycleSubject.<OnStart>d__4.MoveNext()
[21:53:27 ERR] Exception during Silo.Start
Orleans.Runtime.OrleansLifecycleCanceledException: Lifecycle start canceled due to errors at stage 19999 ---> System.TimeoutException: MembershipOracle activating failed due to timeout 00:05:00
at Orleans.OrleansTaskExtentions.<WithTimeout>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Silo.<<OnBecomeActiveStart>g__BecomeActive72_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Silo.<StartAsyncTaskWithPerfAnalysis>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Silo.<OnBecomeActiveStart>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.<OnStart>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.LifecycleSubject.<WrapExecution>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.LifecycleSubject.<OnStart>d__4.MoveNext()
--- End of inner exception stack trace ---
at Orleans.LifecycleSubject.<OnStart>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.<Execute>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.Silo.<StartAsync>d__64.MoveNext()
[21:53:35 ERR] -Silo S<new silo>:266017691 failed to update its status to Active in the table due to failures (socket failures or table read/write failures) after 25 attempts: One or more errors occurred. (Silo S<new silo>:266017691 is rejecting message: Request S<new silo>:266017691*stg/15/0000000f@S0000000f->S<old silo>:265814527*stg/15/0000000f@S0000000f #26:
[21:53:35 ERR] BecomeActive failed
Orleans.Runtime.OrleansException: -Silo S<new silo>:266017691 failed to update its status to Active in the table due to failures (socket failures or table read/write failures) after 25 attempts: One or more errors occurred. (Silo S<new silo>:266017691 is rejecting message: Request S<new silo>:266017691*stg/15/0000000f@S0000000f->S<old silo>:265814527*stg/15/0000
--- End of inner exception stack trace ---
at Orleans.Runtime.MembershipService.MembershipOracle.<>c__DisplayClass52_0.<GetJoiningPreconditionPromise>b__3(Task task)
at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.MembershipService.MembershipOracle.<GetJoiningPreconditionPromise>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.MembershipService.MembershipOracle.<TryUpdateMyStatusGlobalOnce>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.MembershipService.MembershipOracle.<>c__DisplayClass50_0.<<UpdateMyStatusGlobal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.MembershipService.MembershipOracle.<UpdateMyStatusGlobal>d__50.MoveNext()
--- End of inner exception stack trace ---
at Orleans.Runtime.MembershipService.MembershipOracle.<UpdateMyStatusGlobal>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.MembershipService.MembershipOracle.<BecomeActive>d__32.MoveNext()
```

**Comment by sergeybykov** [comment]
>About to send pings to 1 nodes in order to validate communication in the Joining state.

This is exactly the initial connectivity validation process that you can turn off via `ClusterMembershipOptions.ValidateInitialConnectivity` as @benjaminpetit mentioned above.

If you turn it off, the newly started silos will join the cluster. They will still try to connect to the older silos that are listed as `Active` while they are actually not. Eventually, that fact will be detected and they will be voted dead, assuming you'll have enough of new silos for the voting.
