### ISSUE TITLE
Impossible to restart Silohost after creating a reminder which will fire in 6 months time

### ISSUE THREAD

**Issue by Kimserey** [dotnet/orleans#471]
I created a reminder which is configured to fire in 6 months time.
After restarting the Silohost, the following error appears and it is then impossible to restart it.

Which is the largest value I can put? Is this related to the version I am using? I am using Orleans 1.0.5.

`Exc level 1: System.ArgumentOutOfRangeException: Time-out interval must be less than 2^32-2.
Parameter name: dueTime
   at System.Threading.Timer.Change(Int64 dueTime, Int64 period)
   at System.Threading.Timer.Change(TimeSpan dueTime, TimeSpan period)
   at Orleans.Runtime.SafeTimerBase.Start(TimeSpan due, TimeSpan period)
   at Orleans.Runtime.AsyncTaskSafeTimer.Start(TimeSpan dueTime, TimeSpan period)
   at Orleans.Runtime.GrainTimer.Start()
   at Orleans.Runtime.ReminderService.LocalReminderService.LocalReminderData.StartTimer(Func 2 asyncCallback, TraceLogger logger)
   at Orleans.Runtime.ReminderService.LocalReminderService.StartAndAddTimer(ReminderEntry entry)
   at Orleans.Runtime.ReminderService.LocalReminderService.<ReadTableAndStartTimers>d__2d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Runtime.ReminderService.LocalReminderService.<ReadAndUpdateReminders>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Runtime.ReminderService.LocalReminderService.<Start>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClassa.<<QueueTask>b__8>d__c.MoveNext()`

**Comment by sergeybykov** [comment]
Looks like a bug - we should be checking for the same limits that `Timer.Change()` imposes and throw from `RegisterOrUpdateReminder()` in case of a violation.

Are you running a 32 or 64-bit process? It appears that at least in the 32-bit case the limit is 2,147,483,647 milliseconds or ~25 days. The workaround would be to set the reminder for a shorter period, e.g. 1 day or 1 week, and update it until it's due.

**Comment by sergeybykov** [comment]
Just ran a test - the same limit is imposed in a 64-bit process. For now, I'd suggest the workaround I mentioned above.

We have some thoughts on redesigning reminders to make them more scalable. Such a redesign would address this limitation as well. If somebody is interested, we can share our initial thoughts.

**Comment by Kimserey** [comment]
Hi Sergey, thanks for the reply. The work around you proposed is what I am using at the moment.

**Comment by gabikliot** [comment]
The limit comes from System.Threading.Timer code:
http://referencesource.microsoft.com/#mscorlib/system/threading/timer.cs,c454f2afe745d4d3,references

Just added a check to reject reminder creation, so we don't say we created it but later cannot tick it: #472

**Comment by gabikliot** [comment]
Added validation at reminder creation time here: #472.
