### ISSUE TITLE
ServiceId_SiloRestart fails intermittently

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#4721]
Orleans.Runtime.OrleansLifecycleCanceledException : Lifecycle start canceled due to errors at stage 19999
2018-06-28T18:46:13.4380282Z       ---- System.TimeoutException : MembershipOracle activating failed due to timeout 00:05:00
2018-06-28T18:46:13.4390296Z       Stack Trace:
2018-06-28T18:46:13.4400270Z         D:\build\agent2\_work\13\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs(63,0): at Orleans.LifecycleSubject.<OnStart>d__5.MoveNext()
2018-06-28T18:46:13.4410272Z         --- End of stack trace from previous location where exception was thrown ---
2018-06-28T18:46:13.4420308Z            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-28T18:46:13.4430311Z            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-28T18:46:13.4440267Z         D:\build\agent2\_work\13\s\src\Orleans.Runtime\Scheduler\ClosureWorkItem.cs(67,0): at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.<Execute>d__8.MoveNext()
2018-06-28T18:46:13.4450349Z         --- End of stack trace from previous location where exception was thrown ---
2018-06-28T18:46:13.4460312Z            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-28T18:46:13.4470268Z            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-28T18:46:13.4480310Z         D:\build\agent2\_work\13\s\src\Orleans.Runtime\Silo\Silo.cs(272,0): at Orleans.Runtime.Silo.<StartAsync>d__64.MoveNext()
2018-06-28T18:46:13.4490358Z         --- End of stack trace from previous location where exception was thrown ---
2018-06-28T18:46:13.4500269Z            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-28T18:46:13.4520274Z            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-28T18:46:13.4530310Z         D:\build\agent2\_work\13\s\src\Orleans.TestingHost\InProcessSiloHandle.cs(36,0): at Orleans.TestingHost.InProcessSiloHandle.Create(String siloName, IList`1 configurationSources)
2018-06-28T18:46:13.4540301Z         D:\build\agent2\_work\13\s\src\Orleans.TestingHost\TestCluster.cs(523,0): at Orleans.TestingHost.TestCluster.StartOrleansSilo(Int32 instanceNumber, TestClusterOptions clusterOptions, IReadOnlyList`1 configurationOverrides, Boolean startSiloOnNewPort)
2018-06-28T18:46:13.4550314Z         D:\build\agent2\_work\13\s\src\Orleans.TestingHost\TestCluster.cs(419,0): at Orleans.TestingHost.TestCluster.RestartSilo(SiloHandle instance)
2018-06-28T18:46:13.4560208Z         D:\build\agent2\_work\13\s\test\TesterInternal\StreamProvidersTests.cs(90,0): at UnitTests.Streaming.StreamProvidersTests_ProviderConfigNotLoaded.<ServiceId_SiloRestart>d__9.MoveNext()
2018-06-28T18:46:13.4570308Z         --- End of stack trace from previous location where exception was thrown ---
2018-06-28T18:46:13.4580241Z            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-28T18:46:13.4590278Z            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-28T18:46:13.4600348Z         --- End of stack trace from previous location where exception was thrown ---
2018-06-28T18:46:13.4610265Z            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-28T18:46:13.4630367Z            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-28T18:46:13.4640374Z         --- End of stack trace from previous location where exception was thrown ---
2018-06-28T18:46:13.4650422Z            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-28T18:46:13.4660310Z            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-28T18:46:13.4670239Z         ----- Inner Stack Trace -----
2018-06-28T18:46:13.4680201Z         D:\build\agent2\_work\13\s\src\Orleans.Core\Async\TaskExtensions.cs(225,0): at Orleans.OrleansTaskExtentions.<WithTimeout>d__16.MoveNext()
2018-06-28T18:46:13.4690294Z         --- End of stack trace from previous location where exception was thrown ---
2018-06-28T18:46:13.4700308Z            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-28T18:46:13.4710156Z            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-28T18:46:13.4720307Z         D:\build\agent2\_work\13\s\src\Orleans.Runtime\Silo\Silo.cs(525,0): at Orleans.Runtime.Silo.<<OnBecomeActiveStart>g__BecomeActive|72_1>d.MoveNext()
2018-06-28T18:46:13.4730269Z         --- End of stack trace from previous location where exception was thrown ---
2018-06-28T18:46:13.4740231Z            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-28T18:46:13.4761713Z            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-28T18:46:13.4770267Z         D:\build\agent2\_work\13\s\src\Orleans.Runtime\Silo\Silo.cs(393,0): at Orleans.Runtime.Silo.<StartAsyncTaskWithPerfAnalysis>d__69.MoveNext()
2018-06-28T18:46:13.4780337Z         --- End of stack trace from previous location where exception was thrown ---
2018-06-28T18:46:13.4790334Z            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-28T18:46:13.4800336Z            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-28T18:46:13.4820323Z         D:\build\agent2\_work\13\s\src\Orleans.Runtime\Silo\Silo.cs(527,0): at Orleans.Runtime.Silo.<OnBecomeActiveStart>d__72.MoveNext()
2018-06-28T18:46:13.4830308Z         --- End of stack trace from previous location where exception was thrown ---
2018-06-28T18:46:13.4840265Z            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-28T18:46:13.4850267Z            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-28T18:46:13.4860281Z         D:\build\agent2\_work\13\s\src\Orleans.Runtime\Lifecycle\SiloLifecycleSubject.cs(82,0): at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.<OnStart>d__9.MoveNext()
2018-06-28T18:46:13.4870306Z         --- End of stack trace from previous location where exception was thrown ---
2018-06-28T18:46:13.4880348Z            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-28T18:46:13.4890265Z            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-28T18:46:13.4900353Z         D:\build\agent2\_work\13\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs(115,0): at Orleans.LifecycleSubject.<WrapExecution>d__10.MoveNext()
2018-06-28T18:46:13.4910389Z         --- End of stack trace from previous location where exception was thrown ---
2018-06-28T18:46:13.4920300Z            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-28T18:46:13.4930325Z            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-28T18:46:13.4940265Z         D:\build\agent2\_work\13\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs(55,0): at Orleans.LifecycleSubject.<OnStart>d__5.MoveNext()

**Comment by ReubenBond** [comment]
I think this may be related to https://github.com/dotnet/orleans/issues/4664

**Comment by ReubenBond** [comment]
I have not seen this fail in a long time
