### ISSUE TITLE
RollingUpdate fails on GetAllSubscriptions()

### ISSUE THREAD

**Issue by oreporan** [dotnet/orleans#4772]
Version:`Orleans 1.5.1`
StreamProvider: `SimpleStreamProvider`
Membership Table: `ServiceFabric Clustering `
While running a rolling update after a code change, we get flooded with exceptions that are happening in the `OnActivateAsync()` of our grain, specifically here:

```
System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request S10.0.0.11:20002:269521878*grn/A31B4281/f5ac76a1@88fe1ab0->S10.0.0.6:20002:269521702*grn/716E8E94/177ccc90+SimpleStreamProvider_SupportFeedItemEvents@6cdb1190 #4133: global::Orleans.Streams.IPubSubRendezvousGrain:GetAllSubscriptions(). Target History is: <S10.0.0.6:20002:269521702:*grn/716E8E94/177ccc90+SimpleStreamProvider_SupportFeedItemEvents:@6cdb1190>.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Streams.StreamPubSubImpl.<GetAllSubscriptions>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Streams.StreamConsumer`1.<GetAllSubscriptions>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 ...
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<CallGrainActivate>d__87.MoveNext()
```

Other errors have the same trace while the exception is:

```
Orleans.Runtime.SiloUnavailableException: The target silo became unavailable for message: Request S10.0.0.11:20002:269521878*grn/A31B4281/968c808d@5de1b4ab-
```

Or

```
Orleans.Runtime.OrleansMessageRejectionException: Silo stopping
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Streams.StreamPubSubImpl.<GetAllSubscriptions>d__9.MoveNext()
```

But all errors are from the same `GetAllSubscriptions` method 

**Current workaround:**
Restart each node in our cluster and then errors dissapear

**Comment by ReubenBond** [comment]
Closing due to no activity - I'm not sure this is an issue still, but it could have been a serialization problem.
