### ISSUE TITLE
Getting a lot of errors from azure queue stream provider

### ISSUE THREAD

**Issue by talarari** [dotnet/orleans#4798]
We're trying to move from simple message stream to azure queue streams.
Getting a lot of these errors:
```
Error doing DeleteMessage for Azure storage queue felix-azurequeuestreamprovider-4 
Exception = Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\HttpResponseParsers.Common.cs:line 50
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.<DeleteMessageImpl>b__39(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 2648
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 299
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AzureUtils.AzureQueueDataManager.<DeleteQueueMessage>d__21.MoveNext()
Request Information
RequestID:0b42e6b4-6003-0034-4232-24957a000000
RequestDate:Wed, 25 Jul 2018 16:14:51 GMT
StatusMessage:The specified message does not exist.
ErrorCode:MessageNotFound
ErrorMessage:The specified message does not exist.
RequestId:0b42e6b4-6003-0034-4232-24957a000000
Time:2018-07-25T16:14:52.1243047Z
```

all of these are for the same queue: queue felix-azurequeuestreamprovider-4 
when looking at that queue in azure storage explorer that was the only one that was full.
I deleted that queue and i think that stopped it.

any ideas?

**Comment by talarari** [comment]
happened again, deleting the queue definitely fixed it but that's not a real solution since it causes data loss.
I suspect this might be starting with a rolling upgrade and then stays broken until i delete the queue.

**Comment by talarari** [comment]
some more info, also seeing a lot of messages building up in felix-azurequeuestreamprovider-4, some have a high dequeue count (20+) but most have dequeue count 1

**Comment by jason-bragg** [comment]
An error on delete message should be benign.
You mentioned rolling upgrades..  Can you provide instructions on how to reproduce this?

**Comment by yevhen** [comment]
@talarari that's easy. During rolling upgrade, the pulling agent tries to send the message it got from the queue to the actor on the silo being restarted and it's getting back the `SiloUnavailableException` thus leading to numerous deque tries. It might be that pulling agents on different nodes deque the same message. Eventually, one succeeds and will remove the message from the queue, leaving the other one with 404.

Read full story #4757
