### ISSUE TITLE
Serializing Delegates not supported on this platform

### ISSUE THREAD

**Issue by sudsy** [dotnet/orleans#4832]
Hi There,

I am running the latest version of Orleans on a docker container based upon microsoft/dotnet:2.1-runtime on linux.

It's running at AWS in the ECS environment.

The problem seems to be related to Fallback serialization of exceptions. I make a call to an external library AmazonLambdaClient which is throwing a permissions exception. The permissions exception is a custom exception type and it seems that there is something wrong with serialization of this custom exception within docker on linux. 

For now, my workaround is to catch the exception and convert it to a regular System.Exception but I'm guessing this problem will rear it's head somewhere else.

The exception log is below:

`Hosting Environment is dockerprod
Using DynamoDB Clustering
[40m[1m[33mwarn[39m[22m[49m: Orleans.Runtime.NoOpHostEnvironmentStatistics[100708]
No implementation of IHostEnvironmentStatistics was found. Load shedding will not work yet
[40m[1m[33mwarn[39m[22m[49m: Orleans.Runtime.MembershipService.MembershipOracleData[100601]
Silo silo1 migrated from host ip-10-0-0-38 silo address S10.0.0.38:11111:271490656 to host ip-10-0-1-240 silo address S10.0.1.240:11111:271489317.
Orleans Silo Running
[40m[1m[33mwarn[39m[22m[49m: Orleans.Runtime.Messaging.IncomingMessageAcceptor[101036]
Exception on accepting socket during AcceptAsync
System.PlatformNotSupportedException: Accepting into an existing Socket is not supported on this platform.
at System.Net.Sockets.Socket.GetOrCreateAcceptSocket(Socket acceptSocket, Boolean unused, String propertyName, SafeCloseSocket& handle)
at System.Net.Sockets.Socket.AcceptAsync(SocketAsyncEventArgs e)
at Orleans.Runtime.Messaging.IncomingMessageAcceptor.StartAccept(SocketAsyncEventArgs acceptEventArg)
[40m[1m[33mwarn[39m[22m[49m: Orleans.Runtime.Messaging.IncomingMessageAcceptor[101036]
Exception on accepting socket during AcceptAsync
System.PlatformNotSupportedException: Accepting into an existing Socket is not supported on this platform.
at System.Net.Sockets.Socket.GetOrCreateAcceptSocket(Socket acceptSocket, Boolean unused, String propertyName, SafeCloseSocket& handle)
at System.Net.Sockets.Socket.AcceptAsync(SocketAsyncEventArgs e)
at Orleans.Runtime.Messaging.IncomingMessageAcceptor.StartAccept(SocketAsyncEventArgs acceptEventArg)
[40m[1m[33mwarn[39m[22m[49m: Orleans.Runtime.Scheduler.WorkItemGroup[101215]
Task [Id=1, Status=RanToCompletion] in WorkGroup [Activation: S10.0.0.38:11111:271490656*grn/F4D3640/46e1f291@744c36af #GrainType=PVL.Orl.Grains.SunSolveSystemJob Placement=RandomPlacement State=Valid] took elapsed time 0:00:00.4759661 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/3, ManagedThreadId=13, Executing Task Id=1 Status=RanToCompletion for 00:00:00.4787084 on WorkItem=WorkItemGroup:Name=[Activation: S10.0.0.38:11111:271490656*grn/F4D3640/46e1f291@744c36af #GrainType=PVL.Orl.Grains.SunSolveSystemJob Placement=RandomPlacement],WorkGroupStatus=Running Executing for 00:00:00.4792611. .>
[40m[1m[33mwarn[39m[22m[49m: Runtime.Messaging.SiloMessageSender/AppMsgsSender_0[101007]
Unexpected error sending message Response S10.0.0.38:11111:271490656*grn/F4D3640/46e1f291@744c36af->S10.0.1.240:11111:271490656*grn/37AC7DD4/99220d9c@36823a84 #180:
System.Runtime.Serialization.SerializationException: Serializing delegates is not supported on this platform.
at System.MulticastDelegate.GetObjectData(SerializationInfo info, StreamingContext context)
at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter, Boolean fCheck)
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Boolean check)
at Orleans.Serialization.BinaryFormatterSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at AcceptOperationSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at SocketAsyncContextSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.BuiltInTypes.SerializeDictionary[K,V](Object original, ISerializationContext context, Type expected)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at SocketAsyncEngineSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at SocketAsyncContextSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at SafeCloseSocketSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at SocketSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at HttpConnectionSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at CachedConnectionSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.BuiltInTypes.SerializeList[T](Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at HttpConnectionPoolSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.SerializationManager.SerializeArray(Array array, ISerializationContext context, Type expected, Type et)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TablesSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at HttpConnectionPoolManagerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at TimerQueueTimerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at HttpConnectionPoolManagerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at RedirectHandlerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at SocketsHttpHandlerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at DiagnosticsHandlerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at HttpClientHandlerSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at HttpClientSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at HttpResponseMessageBodySerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.ILBasedExceptionSerializer.Serialize(Object item, ISerializationContext outerContext, Type expectedType)
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at AmazonLambdaExceptionSerializer(Object , ISerializationContext , Type )
at Orleans.Serialization.ILBasedExceptionSerializer.Serialize(Object item, ISerializationContext outerContext, Type expectedType)
at Orleans.Serialization.ILBasedSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
at Orleans.Serialization.SerializationManager.Serialize(Object raw, IBinaryTokenStreamWriter stream)
at Orleans.Runtime.Message.Serialize(SerializationManager serializationManager, Int32& headerLengthOut, Int32& bodyLengthOut)
at Orleans.Messaging.OutgoingMessageSender.Process(Message msg)
[40m[1m[33mwarn[39m[22m[49m: Runtime.Messaging.SiloMessageSender/AppMsgsSender_0[101007]`

**Comment by ReubenBond** [comment]
I see that it's serializing `AmazonLambdaException` and that is for some reason holding on to an `HttpResponseMessageBody` which end up holding an `HttpClient` ... and it gets messier from there.

I think the only viable option is as you said, to wrap the exception in a generic type which doesn't include those fields.

Alternatively, it might be that the `ISerializable` implementation on those exceptions already avoids serializing those fields, in which case you might be able to switch to `BinaryFormatterSerializer` as your fallback and achieve better results.

**Comment by ReubenBond** [comment]
Closing due to inactivity - please reopen if this is still an issue for you

**Comment by artemiusgreat** [comment]
In my case, that was caused by `Timer`. 

**Model**

```
public class SomeModel
{
   Timer _clock = null;

   public void Start()
   {
      _clock = new Timer();
      _clock.Interval = 1000;
      _clock.Elapsed += new ElapsedEventHandler((object source, ElapsedEventArgs e) =>{ });
   }
}
```
**Grain**

```
public interface ISomeGrain : IGrainWithStringKey
{
  Task<SomeModel> Model();
  Task<SomeModel> SetModel(SomeModel model);
  Task<SomeModel> StartTimer();
}

public class SomeGrain : Grain, ISomeGrain
{
  SomeModel _model = null;

  Task<SomeModel> Model() => Task.FromResult(_model);
  Task<SomeModel> SetModel(SomeModel model) => Task.FromResult(_model = model);
  Task<SomeModel> StartTimer() 
  {
    _model.Start();                                 // Comment this and all is fine
    
    return Task.FromResult(_model);     // If timer is set, serialization exception is raised
  }
}
```
