### ISSUE TITLE
Orleans.Runtime.OrleansException: Not connected to a gateway when reconnecting to a local silo

### ISSUE THREAD

**Issue by skyflyer** [dotnet/orleans#4842]
I'm just playing with Orleans and one of the basics and I tried the 2.0 sample app.

I started the client before the silo (intentionally), just to see if the retry policy, outlined there would work. The client connected, but then immediately failed with the error I'm pasting below.

Steps to reproduce:

1. Use the [Hello world sample](https://github.com/dotnet/orleans/tree/master/Samples/2.0/HelloWorld)
1. Start the client
1. Start the silo (after the client has been started)
1. Observe the log output to see the exception

Expected behaviour:
I would expect the client to successfully reconnect and perform operations normally. Is this something that is supposed to work or am I expecting too much? Let me know if you need more details on the setup.

Log output:

<details>
  <summary>Expand log content</summary>

```
$ dotnet run --project src/OrleansClient/OrleansClient.csproj
info: Orleans.OutsideRuntimeClient[100313]
      ---------- Initializing OutsideRuntimeClient on Petarda.local at 172.16.1.50 Client Id = *cli/c3e0439a ----------
info: Orleans.OutsideRuntimeClient[100314]
      ---------- Starting OutsideRuntimeClient with runtime Version='2.0.3. Commit Hash: c5432c1809a37f12142fb1c489fb0a4f77ed3bda (Release).' in AppDomain=<AppDomain.Id=1, AppDomain.FriendlyName=OrleansClient>
info: Orleans.Messaging.GatewayManager[101309]
      Found 1 knownGateways from Gateway listProvider [gwy.tcp://127.0.0.1:30000/0]
warn: Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0[100178]
      Unable to connect to gateway at address gwy.tcp://127.0.0.1:30000/0 on trial 0 (Exception: Could not connect to 127.0.0.1:30000: ConnectionRefused)
warn: Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0[100913]
      Marking gateway at address gwy.tcp://127.0.0.1:30000/0 as Disconnected
info: Orleans.Messaging.GatewayManager[101309]
      Refreshed the live Gateway list. Found 1 gateways from Gateway listProvider: [gwy.tcp://127.0.0.1:30000/0]. Picked only known live out of them. Now has 1 live Gateways: [gwy.tcp://127.0.0.1:30000/0]. Previous refresh time was = 08/10/2018 22:41:30
warn: Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0[100178]
      Unable to connect to gateway at address gwy.tcp://127.0.0.1:30000/0 on trial 1 (Exception: Could not connect to 127.0.0.1:30000: ConnectionRefused)
warn: Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0[100913]
      Marking gateway at address gwy.tcp://127.0.0.1:30000/0 as Disconnected
info: Orleans.Messaging.GatewayManager[101309]
      Refreshed the live Gateway list. Found 1 gateways from Gateway listProvider: [gwy.tcp://127.0.0.1:30000/0]. Picked only known live out of them. Now has 1 live Gateways: [gwy.tcp://127.0.0.1:30000/0]. Previous refresh time was = 08/10/2018 22:41:30
warn: Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://127.0.0.1:30000/0[100912]
      Marking gateway at address gwy.tcp://127.0.0.1:30000/0 as Dead in my client local gateway list.
warn: Orleans.Runtime.CallbackData[100157]
      The target silo became unavailable for message: Request *cli/c3e0439a@28c5cba1->S127.0.0.1:30000:0*stg/17/00000011@S00000011 #2: . Target History is: <S127.0.0.1:30000:0:*stg/17/00000011:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help. About to break its promise.
warn: Orleans.OutsideRuntimeClient[100011]
      No callback for response message: Unrecoverable Rejection (info: Target silo S127.0.0.1:30000:0 is unavailable) Response S127.0.0.1:30000:0*stg/17/00000011@S00000011->*cli/c3e0439a@28c5cba1 #2:
Cluster client attempt 1 of 5 failed to connect to cluster.  Exception: Orleans.Runtime.SiloUnavailableException: The target silo became unavailable for message: Request *cli/c3e0439a@28c5cba1->S127.0.0.1:30000:0*stg/17/00000011@S00000011 #2: . Target History is: <S127.0.0.1:30000:0:*stg/17/00000011:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.
   at Orleans.OutsideRuntimeClient.<StartInternal>b__58_2()
   at Orleans.OutsideRuntimeClient.<StartInternal>g__ExecuteWithRetries58_3(Func`1 task, Func`2 shouldRetry)
Retrying ...
warn: Orleans.Messaging.GatewayManager[101321]
      All gateways have previously been marked as dead. Clearing the list of dead gateways to expedite reconnection.
info: Orleans.Messaging.GatewayManager[101309]
      Refreshed the live Gateway list. Found 1 gateways from Gateway listProvider: [gwy.tcp://127.0.0.1:30000/0]. Picked only known live out of them. Now has 1 live Gateways: [gwy.tcp://127.0.0.1:30000/0]. Previous refresh time was = 08/10/2018 22:41:30
Cluster client failed to connect to cluster with unexpected error.  Exception: Orleans.Runtime.OrleansException: Not connected to a gateway
   at Orleans.Messaging.ClientMessageCenter.GetLiveGatewaySiloAddress()
   at Orleans.Messaging.ClientMessageCenter.GetGrainTypeResolver(IInternalGrainFactory grainFactory)
   at Orleans.OutsideRuntimeClient.<StartInternal>b__58_2()
   at Orleans.OutsideRuntimeClient.<StartInternal>g__ExecuteWithRetries58_3(Func`1 task, Func`2 shouldRetry)
Exception: Orleans.Runtime.OrleansException: Not connected to a gateway
   at Orleans.Messaging.ClientMessageCenter.GetLiveGatewaySiloAddress()
   at Orleans.Messaging.ClientMessageCenter.GetGrainTypeResolver(IInternalGrainFactory grainFactory)
   at Orleans.OutsideRuntimeClient.<StartInternal>b__58_2()
   at Orleans.OutsideRuntimeClient.<StartInternal>g__ExecuteWithRetries58_3(Func`1 task, Func`2 shouldRetry)
   at Orleans.OutsideRuntimeClient.<StartInternal>g__ExecuteWithRetries58_3(Func`1 task, Func`2 shouldRetry)
   at Orleans.OutsideRuntimeClient.StartInternal(Func`2 retryFilter)
   at Orleans.OutsideRuntimeClient.Start(Func`2 retryFilter)
   at Orleans.ClusterClient.Connect(Func`2 retryFilter)
   at OrleansClient.Program.StartClientWithRetries() in /Users/miha/work/dev/Orleans-Docker/src/OrleansClient/Program.cs:line 59
   at OrleansClient.Program.RunMainAsync() in /Users/miha/work/dev/Orleans-Docker/src/OrleansClient/Program.cs:line 29
info: Orleans.Messaging.GatewayManager[101309]
      Refreshed the live Gateway list. Found 1 gateways from Gateway listProvider: [gwy.tcp://127.0.0.1:30000/0]. Picked only known live out of them. Now has 1 live Gateways: [gwy.tcp://127.0.0.1:30000/0]. Previous refresh time was = 08/10/2018 22:41:40
```
</details>

**Comment by benjaminpetit** [comment]
I think what you are experiencing right now is only because you are using a static gateway provider. If you use multiple silos with something like the azure storage gateway/membership providers, the retry mechanism will works as intended.

**Comment by benjaminpetit** [comment]
Closing for inactivity. If you need more help, feel free to reopen!

**Comment by skyflyer** [comment]
Hello @benjaminpetit! I am sorry for such a late response.

I configured the SQL Server clustering (aside: why are the SQL schema file missing from the docs?) and the client retry mechanism works when when connecting to the silo.

But if I shutdown the silo and bring it back on, ~~the client does not reconnect and just fails when trying to invoke a method on a grain~~. OK, so I tested this a bit more and I see if I allow more time for the client to repopulate gateway info, that it will eventually reconnect. I also found out that `GatewayListRefreshPeriod` controls how often the client refreshes the gateway list. I will try to test multiple silos next.

**Comment by benjaminpetit** [comment]
> aside: why are the SQL schema file missing from the docs?

Feel free to open an issue about this!

> OK, so I tested this a bit more and I see if I allow more time for the client to repopulate gateway info, that it will eventually reconnect. I also found out that GatewayListRefreshPeriod controls how often the client refreshes the gateway list. I will try to test multiple silos next.

Yes you can play with this value to update the list of gateway more often. It shouldn't add much load to your SQL server. We have a mechanism to expedite a refresh more quickly if the client has no "local" alive gateway, but since the refresh is in the background, you may have some failure until the refresh is complete
