### ISSUE TITLE
Could not find any gateway in Orleans.AzureUtils.AzureGatewayListProvider.

### ISSUE THREAD

**Issue by Kimserey** [dotnet/orleans#487]
I have deployed a Silohost in a Azure Worker role and it is not starting.
I am not sure where to start checking, I am getting the following error:

`Orleans.Runtime.OrleansException: Could not find any gateway in Orleans.AzureUtils.AzureGatewayListProvider. Orleans client cannot initialize.
   at Orleans.Messaging.GatewayManager..ctor(ClientConfiguration cfg, IGatewayListProvider gatewayListProvider)
   at Orleans.Messaging.ProxiedMessageCenter..ctor(ClientConfiguration config, IPAddress localAddress, Int32 gen, GrainId clientId, IGatewayListProvider gatewayListProvider)
   at Orleans.OutsideRuntimeClient..ctor(ClientConfiguration cfg, Boolean secondary)
   at Orleans.GrainClient.DoInternalInitialize(ClientConfiguration config, OutsideRuntimeClient runtimeClient)
   at Orleans.GrainClient.<>c__DisplayClass1.<InternalInitialize>b__0(Object state)`

**Comment by sergeybykov** [comment]
This is an error from GrainClient (usually web frontend) failing to connect to silos. How are you deploying silos? Have you tried deploying https://github.com/dotnet/orleans/tree/master/Samples/AzureWebSample first? Have you looked at http://dotnet.github.io/orleans/Orleans-Configuration-Guide/Typical-Configurations?

**Comment by Kimserey** [comment]
Thanks Sergey for the fast response, I already went through the samples but I might have missed something. I will go through it again.

**Comment by sergeybykov** [comment]
No problem. Let us know if you still run into problems.

**Comment by Kimserey** [comment]
It seems like it was related to Azure. I did not change any configuration and after an hour it succesfully restarted. It is now running properly as it was before. Thanks!

**Comment by sergeybykov** [comment]
Great!
