### ISSUE TITLE
FileNotFoundException when calling grain in another cluster

### ISSUE THREAD

**Issue by martinothamar** [dotnet/orleans#5005]
We have 2 clusters running on netcoreapp2.1 and the 2.1-rc1 Orleans release.
We use runtime codegen.

We're testing this locally using VS2017, running in debug mode.

Cluster B needs to call cluster A via an `IClusterClient`. We've setup the SMSProvider with `FireAndForget` and `OptimizeForImmutability`. The `IClusterClient` on B is connected during startup.
The initial symptom was that messages streamed via `OnNextAsync` on B.Grain never arrived on A.Grain (configured with ImplicitStreamSubscription).

When switching off `FireAndForget` we get the exception below:

```
Could not load file or assembly 'B.Grains, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask) in D:\build\agent\_work\23\s\src\Orleans.Core\Async\TaskExtensions.cs:line 100
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducerExtension.StreamConsumerExtensionCollection.DeliverToRemote(IStreamConsumerExtension remoteConsumer, StreamId streamId, GuidId subscriptionId, Object item, Boolean optimizeForImmutableData) in D:\build\agent\_work\23\s\src\Orleans.Core\Streams\SimpleMessageStream\SimpleMessageStreamProducerExtension.cs:line 222
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.OnNextAsync(T item, StreamSequenceToken token) in D:\build\agent\_work\23\s\src\Orleans.Core\Streams\SimpleMessageStream\SimpleMessageStreamProducer.cs:line 112
   at B.Grains.Grain.Delegate(Immutable`1 message) in C:\..Grain.cs:line 108
```

We tried switching from streaming to direct grain-calls via the `IClusterClient` but get a similar message.

**Comment by martinothamar** [comment]
Figured it out after a while... It was the receiving cluster that threw that exception, because the object being streamed was casted to a base class that A knew about, but was really an instance of a subclass that A _didn't_ know about.
