### ISSUE TITLE
Getting a SiloUnavailableException

### ISSUE THREAD

**Issue by sillyousu** [dotnet/orleans#5025]
Getting a  `SiloUnavailableException` after launching an orleans app which consist of both silo client and silo host. 

I had read [troubleshooting doc](https://dotnet.github.io/orleans/Documentation/deployment/troubleshooting_deployments.html#getting-a-silounavailableexception
) and I think my bootstrap process is good (or correct me if I'm wrong)

My program bootstrap like this :

```csharp
static void Main() {
    startSiloHost();
    startSiloClient();
    startGate();  
}

startSiloHost() {
    ISiloHostBuilder builder = new SiloHostBuilder(); 
    // a lot config stuff.
   var host = builder.Build()
   host.StartAsync().Wait();
}

startSiloClient() {
    ISiloHostBuilder builder = new SiloClientBuilder(); 
    // a lot config stuff.
   var client = builder.Build()
   client.StartAsync().Wait();
}

startGate() {
    // listen and serve real clients
}
```

```
2018-09-25 15:03:04.8621|INFO|Sims.Program|server start! "unknow"
2018-09-25 15:03:05.5019|WARN|Orleans.Runtime.Silo|Note: Silo not running with ServerGC turned on - recommend checking app config : <configuration>-<runtime>-<gcServer enabled="true">
2018-09-25 15:03:05.5019|WARN|Orleans.Runtime.Silo|Note: ServerGC only kicks in on multi-core systems (settings enabling ServerGC have no effect on single-core machines).
2018-09-25 15:03:05.5608|WARN|Orleans.Runtime.NoOpHostEnvironmentStatistics|No implementation of IHostEnvironmentStatistics was found. Load shedding will not work yet
2018-09-25 15:03:12.3743|INFO|Sims.Program|server start done!
2018-09-25 15:03:49.9147|WARN|Orleans.Runtime.MembershipService.MembershipOracleData|-Did not get ping response for ping #0 from S127.0.0.1:11111:275554985. Reason = Original Exc Type: Orleans.Runtime.OrleansMessageRejectionException Message:The target silo is no longer active: target was S127.0.0.1:11111:275554985, but this silo is S127.0.0.1:30000:275554985. The rejected ping message is Request S127.0.0.1:30000:275554985*stg/15/0000000f@S0000000f->S127.0.0.1:11111:275554985*stg/15/0000000f@S0000000f #34: .
2018-09-25 15:03:59.9196|WARN|Orleans.Runtime.MembershipService.MembershipOracleData|-Did not get ping response for ping #1 from S127.0.0.1:11111:275554985. Reason = Original Exc Type: Orleans.Runtime.OrleansMessageRejectionException Message:The target silo is no longer active: target was S127.0.0.1:11111:275554985, but this silo is S127.0.0.1:30000:275554985. The rejected ping message is Request S127.0.0.1:30000:275554985*stg/15/0000000f@S0000000f->S127.0.0.1:11111:275554985*stg/15/0000000f@S0000000f #35: .
2018-09-25 15:04:09.9346|WARN|Orleans.Runtime.MembershipService.MembershipOracleData|-Did not get ping response for ping #2 from S127.0.0.1:11111:275554985. Reason = Original Exc Type: Orleans.Runtime.OrleansMessageRejectionException Message:The target silo is no longer active: target was S127.0.0.1:11111:275554985, but this silo is S127.0.0.1:30000:275554985. The rejected ping message is Request S127.0.0.1:30000:275554985*stg/15/0000000f@S0000000f->S127.0.0.1:11111:275554985*stg/15/0000000f@S0000000f #36: .
2018-09-25 15:04:09.9863|WARN|Orleans.Runtime.CallbackData|The target silo became unavailable for message: Request S127.0.0.1:30000:275554985*stg/22/00000016@S00000016->S127.0.0.1:11111:275554985*stg/22/00000016@S00000016 #32: . Target History is: <S127.0.0.1:11111:275554985:*stg/22/00000016:@S00000016>. See https://aka.ms/orleans-troubleshooting for troubleshooting help. About to break its promise.
2018-09-25 15:04:10.0175|WARN|Orleans.Runtime.DeploymentLoadPublisher|An exception was thrown by PublishStatistics.UpdateRuntimeStatistics(). Ignoring. Orleans.Runtime.SiloUnavailableException: The target silo became unavailable for message: Request S127.0.0.1:30000:275554985*stg/22/00000016@S00000016->S127.0.0.1:11111:275554985*stg/22/00000016@S00000016 #32: . Target History is: <S127.0.0.1:11111:275554985:*stg/22/00000016:@S00000016>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.
   at Orleans.Runtime.DeploymentLoadPublisher.PublishStatistics(Object _) in D:\build\agent\_work\23\s\src\Orleans.Runtime\Placement\DeploymentLoadPublisher.cs:line 116
2018-09-25 15:04:12.2202|WARN|Orleans.Messaging.GatewayManager|All gateways have previously been marked as dead. Clearing the list of dead gateways to expedite reconnection.
2018-09-25 15:04:12.3790|WARN|Orleans.OutsideRuntimeClient|Refresh the GrainTypeResolver failed. WIll be retried after Orleans.Runtime.OrleansException: Not connected to a gateway
   at Orleans.Messaging.ClientMessageCenter.GetLiveGatewaySiloAddress() in D:\build\agent\_work\23\s\src\Orleans.Core\Messaging\ClientMessageCenter.cs:line 436
   at Orleans.Messaging.ClientMessageCenter.GetGrainTypeResolver(IInternalGrainFactory grainFactory) in D:\build\agent\_work\23\s\src\Orleans.Core\Messaging\ClientMessageCenter.cs:line 318
   at Orleans.OutsideRuntimeClient.RefreshGrainTypeResolver(Object _) in D:\build\agent\_work\23\s\src\Orleans.Core\Runtime\OutsideRuntimeClient.cs:line 293
2018-09-25 15:04:12.3790|WARN|Orleans.Messaging.GatewayManager|All gateways have previously been marked as dead. Clearing the list of dead gateways to expedite reconnection.
2018-09-25 15:05:12.2345|WARN|Orleans.Messaging.GatewayManager|All gateways have previously been marked as dead. Clearing the list of dead gateways to expedite reconnection.
2018-09-25 15:05:12.3886|WARN|Orleans.OutsideRuntimeClient|Refresh the GrainTypeResolver failed. WIll be retried after Orleans.Runtime.OrleansException: Not connected to a gateway
   at Orleans.Messaging.ClientMessageCenter.GetLiveGatewaySiloAddress() in D:\build\agent\_work\23\s\src\Orleans.Core\Messaging\ClientMessageCenter.cs:line 436
   at Orleans.Messaging.ClientMessageCenter.GetGrainTypeResolver(IInternalGrainFactory grainFactory) in D:\build\agent\_work\23\s\src\Orleans.Core\Messaging\ClientMessageCenter.cs:line 318
   at Orleans.OutsideRuntimeClient.RefreshGrainTypeResolver(Object _) in D:\build\agent\_work\23\s\src\Orleans.Core\Runtime\OutsideRuntimeClient.cs:line 293
2018-09-25 15:05:12.3886|WARN|Orleans.Messaging.GatewayManager|All gateways have previously been marked as dead. Clearing the list of dead gateways to expedite reconnection.
```

**Comment by sillyousu** [comment]
Sure. I'm working on a minimal reproduce.

**Comment by sillyousu** [comment]
@ReubenBond  https://github.com/sillyousu/OrleansHello  

You can take a look at  [this](https://github.com/sillyousu/OrleansHello/blob/master/DevApp/Program.cs) and [log](https://github.com/sillyousu/OrleansHello/blob/master/DevApp/stdout.txt#L417)

You also need run consul in dev mode ( `consul.exe agent -dev`) in the same machine

**Comment by sillyousu** [comment]
I'm not sure whether I can have both silo client and silo host same process?

**Comment by ReubenBond** [comment]
@sillyousu
> I'm not sure whether I can have both silo client and silo host same process?

Yes, you can 😄

**Comment by sillyousu** [comment]
trace log

[trace.zip](https://github.com/dotnet/orleans/files/2418045/trace.zip)

**Comment by sillyousu** [comment]
[trace.zip](https://github.com/dotnet/orleans/files/2418064/trace.zip)

```
cat trace.txt | grep "Forwarding message 51"|wc -l
```

It looks like message 51 in an endless forwarding loop.

**Comment by sillyousu** [comment]
I would like to look into this bug today. 
@ReubenBond could you provide some quick pointer/theory？

**Comment by ReubenBond** [comment]
@sillyousu, thank you for the repro.

The issue is in the Consul gateway provider here: https://github.com/dotnet/orleans/blob/7846ffe80134aaae2bba4d2b6aa573ec0fee83c0/src/Orleans.Clustering.Consul/ConsulGatewayListProvider.cs#L66

I'll submit a PR in a moment. The same issue is also in the Zookeeper provider.
