### ISSUE TITLE
Getting `System.InvalidOperationException: Grain directory is stopping` when shutting down 

### ISSUE THREAD

**Issue by sillyousu** [dotnet/orleans#5075]
setup:
* memory storage + local cluster
* co-host  1)API gate  2) cluster client 3) silo host in one process
* orleans version:  （almost) bb360159f695b008be701d7bafd581e410781001 
 ( https://github.com/sillyousu/orleans/tree/fix-4965)

When I shutdown the process, I got following warning:
```
2018-10-05 16:28:18.2058|INFO|Sims.Program|Recevie signal, shutting down
~\source\repos\OrleansLobby\Sims [master ≡ +0 ~9 -0 !]> 2018-10-05 16:28:18.3516|WARN|Orleans.Runtime.Catalog|UnregisterManyAsync 1 failed. System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 560
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterOrPutInForwardList(IEnumerable`1 addresses, UnregistrationCause cause, Int32 hopCount, Dictionary`2& forward, List`1 tasks, String context) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 721
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterManyAsync(List`1 addresses, UnregistrationCause cause, Int32 hopCount) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 768
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Scheduler\ClosureWorkItem.cs:line 63
   at Orleans.Runtime.Catalog.FinishDestroyActivations(List`1 list, Int32 number, MultiTaskCompletionSource tcs) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Catalog\Catalog.cs:line 1013
2018-10-05 16:28:18.4061|WARN|Orleans.Runtime.Dispatcher|Failed to un-register NonExistentActivation S127.0.0.1:11111:276424065*grn/716E8E94/00002767+ClientMessageService_ClientMessageService@466cef8e System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 560
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterAsync(ActivationAddress address, UnregistrationCause cause, Int32 hopCount) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 675
   at Orleans.Runtime.Dispatcher.<>c__DisplayClass18_1.<<ReceiveMessage>b__0>d.MoveNext() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Core\Dispatcher.cs:line 166
2018-10-05 16:28:18.4061|WARN|Orleans.Runtime.Dispatcher|Failed to un-register NonExistentActivation S127.0.0.1:11111:276424065*grn/716E8E94/00002767+ClientMessageService_ClientMessageService@466cef8e System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 560
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterAsync(ActivationAddress address, UnregistrationCause cause, Int32 hopCount) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 675
   at Orleans.Runtime.Dispatcher.<>c__DisplayClass18_1.<<ReceiveMessage>b__0>d.MoveNext() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Core\Dispatcher.cs:line 166
2018-10-05 16:28:18.4061|WARN|Orleans.Runtime.Dispatcher|Failed to un-register NonExistentActivation S127.0.0.1:11111:276424065*grn/716E8E94/00002767+ClientMessageService_ClientMessageService@466cef8e System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 560
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterAsync(ActivationAddress address, UnregistrationCause cause, Int32 hopCount) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 675
   at Orleans.Runtime.Dispatcher.<>c__DisplayClass18_1.<<ReceiveMessage>b__0>d.MoveNext() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Core\Dispatcher.cs:line 166
2018-10-05 16:28:18.4061|WARN|Orleans.Runtime.Dispatcher|Forwarding failed: tried to forward message Request S127.0.0.1:11111:276424065*grn/442EA8BA/00002767@9c66859e->S127.0.0.1:11111:276424065*grn/716E8E94/00002767+ClientMessageService_ClientMessageService@466cef8e #121[ForwardCount=2]:  for 2 times after Non-existent activation to invalid activation. Rejecting now.
2018-10-05 16:28:18.4061|WARN|Orleans.Runtime.Dispatcher|Failed to un-register NonExistentActivation S127.0.0.1:11111:276424065*grn/716E8E94/00002767+ClientMessageService_ClientMessageService@466cef8e System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 560
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterAsync(ActivationAddress address, UnregistrationCause cause, Int32 hopCount) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 675
   at Orleans.Runtime.Dispatcher.<>c__DisplayClass18_1.<<ReceiveMessage>b__0>d.MoveNext() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Core\Dispatcher.cs:line 166
2018-10-05 16:28:18.4219|WARN|Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1[[LobbyGrains.Core.Messages.ClientMessage, LobbyGrains, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]|Ignoring unhandled exception during PubSub.UnregisterProducer Orleans.Runtime.OrleansMessageRejectionException: Forwarding failed: tried to forward message Request S127.0.0.1:11111:276424065*grn/442EA8BA/00002767@9c66859e->S127.0.0.1:11111:276424065*grn/716E8E94/00002767+ClientMessageService_ClientMessageService@466cef8e #121[ForwardCount=2]:  for 2 times after Non-existent activation to invalid activation. Rejecting now.
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.Cleanup() in C:\Users\a\source\repos\orleans\src\Orleans.Core\Streams\SimpleMessageStream\SimpleMessageStreamProducer.cs:line 157
2018-10-05 16:28:18.4708|WARN|Orleans.Runtime.Dispatcher|Forwarding failed: tried to forward message Request S127.0.0.1:11111:276424065*grn/736BA21C/00002767@3e27ffa6->S127.0.0.1:11111:276424065*grn/716E8E94/00002767+ClientMessageService_ClientMessageService@466cef8e #123[ForwardCount=2]:  for 2 times after Non-existent activation to invalid activation. Rejecting now.
2018-10-05 16:28:18.4941|WARN|Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1[[LobbyGrains.Core.Messages.ClientMessage, LobbyGrains, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]|Ignoring unhandled exception during PubSub.UnregisterProducer Orleans.Runtime.OrleansMessageRejectionException: Forwarding failed: tried to forward message Request S127.0.0.1:11111:276424065*grn/736BA21C/00002767@3e27ffa6->S127.0.0.1:11111:276424065*grn/716E8E94/00002767+ClientMessageService_ClientMessageService@466cef8e #123[ForwardCount=2]:  for 2 times after Non-existent activation to invalid activation. Rejecting now.
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.Cleanup() in C:\Users\a\source\repos\orleans\src\Orleans.Core\Streams\SimpleMessageStream\SimpleMessageStreamProducer.cs:line 157
2018-10-05 16:28:18.4941|WARN|Orleans.Runtime.Catalog|UnregisterManyAsync 2 failed. System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 560
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterOrPutInForwardList(IEnumerable`1 addresses, UnregistrationCause cause, Int32 hopCount, Dictionary`2& forward, List`1 tasks, String context) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 721
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterManyAsync(List`1 addresses, UnregistrationCause cause, Int32 hopCount) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 768
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Scheduler\ClosureWorkItem.cs:line 63
   at Orleans.Runtime.Catalog.FinishDestroyActivations(List`1 list, Int32 number, MultiTaskCompletionSource tcs) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Catalog\Catalog.cs:line 1013
2018-10-05 16:28:18.5562|WARN|Orleans.Runtime.Dispatcher|Failed to un-register NonExistentActivation S127.0.0.1:11111:276424065*grn/716E8E94/00002766+ClientMessageService_ClientMessageService@28e00185 System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 560
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterAsync(ActivationAddress address, UnregistrationCause cause, Int32 hopCount) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 675
   at Orleans.Runtime.Dispatcher.<>c__DisplayClass18_1.<<ReceiveMessage>b__0>d.MoveNext() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Core\Dispatcher.cs:line 166
2018-10-05 16:28:18.6057|WARN|Orleans.Runtime.Dispatcher|Failed to un-register NonExistentActivation S127.0.0.1:11111:276424065*grn/716E8E94/00002766+ClientMessageService_ClientMessageService@28e00185 System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 560
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterAsync(ActivationAddress address, UnregistrationCause cause, Int32 hopCount) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 675
   at Orleans.Runtime.Dispatcher.<>c__DisplayClass18_1.<<ReceiveMessage>b__0>d.MoveNext() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Core\Dispatcher.cs:line 166
2018-10-05 16:28:18.6397|WARN|Orleans.Runtime.Dispatcher|Failed to un-register NonExistentActivation S127.0.0.1:11111:276424065*grn/716E8E94/00002766+ClientMessageService_ClientMessageService@28e00185 System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 560
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterAsync(ActivationAddress address, UnregistrationCause cause, Int32 hopCount) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 675
   at Orleans.Runtime.Dispatcher.<>c__DisplayClass18_1.<<ReceiveMessage>b__0>d.MoveNext() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Core\Dispatcher.cs:line 166
2018-10-05 16:28:18.6874|WARN|Orleans.Runtime.Dispatcher|Forwarding failed: tried to forward message Request S127.0.0.1:11111:276424065*grn/442EA8BA/00002766@234b9789->S127.0.0.1:11111:276424065*grn/716E8E94/00002766+ClientMessageService_ClientMessageService@28e00185 #122[ForwardCount=2]:  for 2 times after Non-existent activation to invalid activation. Rejecting now.
2018-10-05 16:28:18.7024|WARN|Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1[[LobbyGrains.Core.Messages.ClientMessage, LobbyGrains, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]|Ignoring unhandled exception during PubSub.UnregisterProducer Orleans.Runtime.OrleansMessageRejectionException: Forwarding failed: tried to forward message Request S127.0.0.1:11111:276424065*grn/442EA8BA/00002766@234b9789->S127.0.0.1:11111:276424065*grn/716E8E94/00002766+ClientMessageService_ClientMessageService@28e00185 #122[ForwardCount=2]:  for 2 times after Non-existent activation to invalid activation. Rejecting now.
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.Cleanup() in C:\Users\a\source\repos\orleans\src\Orleans.Core\Streams\SimpleMessageStream\SimpleMessageStreamProducer.cs:line 157
2018-10-05 16:28:18.7024|WARN|Orleans.Runtime.Dispatcher|Failed to un-register NonExistentActivation S127.0.0.1:11111:276424065*grn/716E8E94/00002766+ClientMessageService_ClientMessageService@28e00185 System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 560
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterAsync(ActivationAddress address, UnregistrationCause cause, Int32 hopCount) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 675
   at Orleans.Runtime.Dispatcher.<>c__DisplayClass18_1.<<ReceiveMessage>b__0>d.MoveNext() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Core\Dispatcher.cs:line 166
2018-10-05 16:28:18.7887|WARN|Orleans.Runtime.Dispatcher|Forwarding failed: tried to forward message Request S127.0.0.1:11111:276424065*grn/736BA21C/00002766@a66f81a1->S127.0.0.1:11111:276424065*grn/716E8E94/00002766+ClientMessageService_ClientMessageService@28e00185 #120[ForwardCount=2]:  for 2 times after Non-existent activation to invalid activation. Rejecting now.
2018-10-05 16:28:18.8041|WARN|Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1[[LobbyGrains.Core.Messages.ClientMessage, LobbyGrains, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]|Ignoring unhandled exception during PubSub.UnregisterProducer Orleans.Runtime.OrleansMessageRejectionException: Forwarding failed: tried to forward message Request S127.0.0.1:11111:276424065*grn/736BA21C/00002766@a66f81a1->S127.0.0.1:11111:276424065*grn/716E8E94/00002766+ClientMessageService_ClientMessageService@28e00185 #120[ForwardCount=2]:  for 2 times after Non-existent activation to invalid activation. Rejecting now.
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.Cleanup() in C:\Users\a\source\repos\orleans\src\Orleans.Core\Streams\SimpleMessageStream\SimpleMessageStreamProducer.cs:line 157
2018-10-05 16:28:18.8041|WARN|Orleans.Runtime.Catalog|UnregisterManyAsync 2 failed. System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 560
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterOrPutInForwardList(IEnumerable`1 addresses, UnregistrationCause cause, Int32 hopCount, Dictionary`2& forward, List`1 tasks, String context) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 721
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterManyAsync(List`1 addresses, UnregistrationCause cause, Int32 hopCount) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 768
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Scheduler\ClosureWorkItem.cs:line 63
   at Orleans.Runtime.Catalog.FinishDestroyActivations(List`1 list, Int32 number, MultiTaskCompletionSource tcs) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Catalog\Catalog.cs:line 1013
2018-10-05 16:28:18.8379|WARN|Orleans.Runtime.Catalog|UnregisterManyAsync 1 failed. System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 560
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterOrPutInForwardList(IEnumerable`1 addresses, UnregistrationCause cause, Int32 hopCount, Dictionary`2& forward, List`1 tasks, String context) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 721
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterManyAsync(List`1 addresses, UnregistrationCause cause, Int32 hopCount) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\GrainDirectory\LocalGrainDirectory.cs:line 768
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Scheduler\ClosureWorkItem.cs:line 63
   at Orleans.Runtime.Catalog.FinishDestroyActivations(List`1 list, Int32 number, MultiTaskCompletionSource tcs) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Catalog\Catalog.cs:line 1013
```

**Comment by sergeybykov** [comment]
This looks unpleasant but is soft of expected when you are shutting down a cluster of one silo which has no other silo to hand off the grain directory and forward requests to. We could treat this setup as a special case and add a bunch of code to suppress the normal behavior of a silo shutting down gracefully. But I personallt don't see much value in adding such complexity for the non-production case.

**Comment by sergeybykov** [comment]
>But what happens the last silo in a real cluster is shutting down?
Do I still get such warning?

Yes, you will get same warnings. The question is do you care about such warnings at that point? I wouldn't.

**Comment by sillyousu** [comment]
Shutting down a cluster happens very frequently in daily dev.
If such harmless warnings flood and hide valuable warnings/log, then it is a problem.

**Comment by sillyousu** [comment]
@sergeybykov just getting a 1.5KB log. I have to disable warnings from Orleans.

[log.txt](https://github.com/dotnet/orleans/files/2459798/log.txt)

**Comment by sergeybykov** [comment]
@sillyousu Are you shutting the silo down while clients continue sending requests to it?

**Comment by sillyousu** [comment]
>@sillyousu Are you shutting the silo down while clients continue sending requests to it?

I shutdown silo after IClusterClient is closed:

```csharp
void stop() {
    clusterClient.Close().Wait();
    siloHost.StopAsync().Wait();
}

```

**Comment by sillyousu** [comment]
I just found that I didn't tear down all client stream subscription before closing cluster client.

**Comment by sergeybykov** [comment]
That makes more sense - the warnings indicate that requests are still coming into the system, and they have nowhere to be forwarded to. What's the picture if you stop all traffic before shutting down the silo?

**Comment by sillyousu** [comment]
>What's the picture if you stop all traffic before shutting down the silo?

I just made sure all client stream is cleaned up, but still no luck.

**Comment by sillyousu** [comment]
> I just made sure all client stream is cleaned up, but still no luck.

can not reproduce anymore. closing.
