### ISSUE TITLE
TestCluster does not setup silo host correctly

### ISSUE THREAD

**Issue by patricksuo** [dotnet/orleans#5090]
Test cluster complains about `ClusterId` which is already had a valid value.

```
Result Message:	Orleans.Runtime.OrleansConfigurationException : Configuration for ClusterOptions is invalid. A non-empty value for ClusterId is required. See $https://aka.ms/orleans-troubleshooting for more information.
```

```csharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Orleans.TestingHost;
using Microsoft.Extensions.Configuration;


namespace LobbyGrainUnitTests
{
    public class PlayerGrainUnitTest
    {
        [Fact]
        public async Task LoginTest()
        {
            TestClusterOptions options = new TestClusterOptions();
            options.UseTestClusterMembership = true;
            options.ClusterId = "test_cluster";
            options.ServiceId = "test_service";
            options.BaseGatewayPort = 20000;
            options.BaseSiloPort = 20001;
            List<IConfigurationSource> configurationSources = new List<IConfigurationSource>();
            TestCluster cluster = new TestCluster(options, configurationSources);
            cluster.Deploy();
        }
    }
}

```

```
Test Name:	LobbyGrainUnitTests.PlayerGrainUnitTest.LoginTest
Test FullName:	LobbyGrainUnitTests.PlayerGrainUnitTest.LoginTest
Test Source:	C:\Users\a\source\repos\OrleansLobby\LobbyGrainUnitTests\PlayerGrainUnitTest.cs : line 16
Test Outcome:	Failed
Test Duration:	0:00:03.651

Result StackTrace:	
at Orleans.Configuration.ClusterOptionsValidator.ValidateConfiguration() in C:\Users\a\source\repos\orleans\src\Orleans.Core\Configuration\Options\ClusterOptions.cs:line 57
   at Orleans.Hosting.SiloHostBuilder.ValidateSystemConfiguration(IServiceProvider serviceProvider) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Hosting\Generic\SiloHostBuilder.cs:line 159
   at Orleans.Hosting.SiloHostBuilder.Build() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Hosting\Generic\SiloHostBuilder.cs:line 43
   at Orleans.TestingHost.TestClusterHostFactory.CreateSiloHost(String hostName, IEnumerable`1 configurationSources) in C:\Users\a\source\repos\orleans\src\Orleans.TestingHost\TestClusterHostFactory.cs:line 84
   at Orleans.TestingHost.InProcessSiloHandle.Create(String siloName, IList`1 configurationSources) in C:\Users\a\source\repos\orleans\src\Orleans.TestingHost\InProcessSiloHandle.cs:line 33
   at Orleans.TestingHost.TestCluster.StartOrleansSilo(Int32 instanceNumber, TestClusterOptions clusterOptions, IReadOnlyList`1 configurationOverrides, Boolean startSiloOnNewPort) in C:\Users\a\source\repos\orleans\src\Orleans.TestingHost\TestCluster.cs:line 516
   at Orleans.TestingHost.TestCluster.InitializeAsync() in C:\Users\a\source\repos\orleans\src\Orleans.TestingHost\TestCluster.cs:line 472
   at Orleans.TestingHost.TestCluster.DeployAsync() in C:\Users\a\source\repos\orleans\src\Orleans.TestingHost\TestCluster.cs:line 141
   at Orleans.TestingHost.TestCluster.Deploy() in C:\Users\a\source\repos\orleans\src\Orleans.TestingHost\TestCluster.cs:line 126
   at LobbyGrainUnitTests.PlayerGrainUnitTest.LoginTest() in C:\Users\a\source\repos\OrleansLobby\LobbyGrainUnitTests\PlayerGrainUnitTest.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
Result Message:	Orleans.Runtime.OrleansConfigurationException : Configuration for ClusterOptions is invalid. A non-empty value for ClusterId is required. See $https://aka.ms/orleans-troubleshooting for more information.
```

**Comment by sillyousu** [comment]
The test cluster builder work.
```csharp
            TestClusterBuilder builder = new TestClusterBuilder();
            var cluster = builder.Build();
            cluster.Deploy();
```

**Comment by xiazen** [comment]
Just used your code to reproduced the issue on my local machine. But I'm not sure it is 
- a bug in TestCluster, or 
- user aren't supposed to construct TestCluster directly, and we didn't make TestCluster internal to prevent that. In other words, user are supposed to use TestClusterBuilder. @ReubenBond for this, since I don't remember. 

either way I think it is a problem in our side, thanks for reporting ! For now please just use TestClusterBuilder if it isn't a problem for you.
