### ISSUE TITLE
GrainReference throwing `System.InvalidOperationException: Should be overridden by subclass` in GrainStorage.ReadStateAsync

### ISSUE THREAD

**Issue by sillyousu** [dotnet/orleans#5140]
```
Exc level 0: System.InvalidOperationException: Should be overridden by subclass
   at Orleans.Runtime.GrainReference.get_InterfaceName() in C:\Users\a\source\repos\orleans\src\Orleans.Core.Abstractions\Runtime\GrainReference.cs:line 305
   at Orleans.Persistence.RedisGrainStorage.GetKey(GrainReference grainReference) in C:\Users\supei\xd\sims\OrleansLobby\Orleans.Persistence.Redis\RedisGrainStorage.cs:line 213
   at Orleans.Persistence.RedisGrainStorage.ReadStateAsync(String grainType, GrainReference grainReference, IGrainState grainState) in C:\Users\supei\xd\sims\OrleansLobby\Orleans.Persistence.Redis\RedisGrainStorage.cs:line 128
   at Orleans.Core.StateStorageBridge`1.ReadStateAsync() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Storage\StateStorageBridge.cs:line 68 ---> System.InvalidOperationException: Should be overridden by subclass
   at Orleans.Runtime.GrainReference.get_InterfaceName() in C:\Users\a\source\repos\orleans\src\Orleans.Core.Abstractions\Runtime\GrainReference.cs:line 305
   at Orleans.Persistence.RedisGrainStorage.GetKey(GrainReference grainReference) in C:\Users\supei\xd\sims\OrleansLobby\Orleans.Persistence.Redis\RedisGrainStorage.cs:line 213
   at Orleans.Persistence.RedisGrainStorage.ReadStateAsync(String grainType, GrainReference grainReference, IGrainState grainState) in C:\Users\supei\xd\sims\OrleansLobby\Orleans.Persistence.Redis\RedisGrainStorage.cs:line 128
   at Orleans.Core.StateStorageBridge`1.ReadStateAsync() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Storage\StateStorageBridge.cs:line 68
   --- End of inner exception stack trace ---
   at Orleans.Core.StateStorageBridge`1.ReadStateAsync() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Storage\StateStorageBridge.cs:line 80
   at Orleans.LifecycleSubject.WrapExecution(CancellationToken ct, Func`2 action) in C:\Users\a\source\repos\orleans\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 115
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct) in C:\Users\a\source\repos\orleans\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 55
   at Orleans.Runtime.Catalog.CallGrainActivate(ActivationData activation, Dictionary`2 requestContextData) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Catalog\Catalog.cs:line 1170
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Scheduler\ClosureWorkItem.cs:line 63
   at Orleans.Runtime.Catalog.InitActivation(ActivationData activation, String grainType, String genericArguments, Dictionary`2 requestContextData) in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Catalog\Catalog.cs:line 556
   at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask) in C:\Users\a\source\repos\orleans\src\Orleans.Core\Async\TaskExtensions.cs:line 100
   at Sims.Gates.Modules.Players.PlayerService.Login(Session context, Login msg) in C:\Users\supei\xd\sims\OrleansLobby\Sims\Gates\Modules\Players\PlayerService.cs:line 79
   at Sims.Gates.Session.recvLoop() in C:\Users\supei\xd\sims\OrleansLobby\Sims\Gates\Session.cs:line 91
System.InvalidOperationException: Should be overridden by subclass
   at Orleans.Runtime.GrainReference.get_InterfaceName() in C:\Users\a\source\repos\orleans\src\Orleans.Core.Abstractions\Runtime\GrainReference.cs:line 305
   at Orleans.Persistence.RedisGrainStorage.GetKey(GrainReference grainReference) in C:\Users\supei\xd\sims\OrleansLobby\Orleans.Persistence.Redis\RedisGrainStorage.cs:line 213
   at Orleans.Persistence.RedisGrainStorage.ReadStateAsync(String grainType, GrainReference grainReference, IGrainState grainState) in C:\Users\supei\xd\sims\OrleansLobby\Orleans.Persistence.Redis\RedisGrainStorage.cs:line 128
   at Orleans.Core.StateStorageBridge`1.ReadStateAsync() in C:\Users\a\source\repos\orleans\src\Orleans.Runtime\Storage\StateStorageBridge.cs:line 68
```

**Comment by Dewaldf** [comment]
Hi, no expert here, would you be able to share some sample code ? It is really difficult to help when you only have the exception.

From the stack trace it looks like it is a virtual property that needs to be overwritten, if you navigate to the `GrainReference.cs`  file , line 305 

```
/// <summary>
/// Return the name of the interface for this GrainReference. 
/// Implemented in Orleans generated code.
/// </summary>
public virtual string InterfaceName
{
      get
      {
           throw new InvalidOperationException("Should be overridden by subclass");
      }
}
```
But also looks like the class that is suppose to overwrite this is generated by the Orleans Code gen. So to take a stab at answering, could you ensure the following
1. Your grain implementation is inheriting from the `Grain` class
2. Your grain interface inherits from one of the following `IGrainWithIntegerKey`,  `IGrainWithGuidKey`, `IGrainWithStringKey`

**Comment by sergeybykov** [comment]
Hard to tell without more details, but looks like the code is failing to load persisted state of a grain for some reason. Did you change something after the state was saved - codegen, grain class or interface?

**Comment by sillyousu** [comment]
@sergeybykov 

```
   at Orleans.Runtime.GrainReference.get_InterfaceName() in C:\Users\a\source\repos\orleans\src\Orleans.Core.Abstractions\Runtime\GrainReference.cs:line 305
```

In `GrainStorage.ReadStateAsync(string grainType, GrainReference grainReference, IGrainState grainState);`, accessing `grainReference.InterfaceName` throw a `InvalidOperationException`.

The type of param grainReference is `Orleans.Runtime.GrainReference `

https://github.com/dotnet/orleans/blob/6b802f6365e78d691430360a4101b1993eb7afee/src/Orleans.Core.Abstractions/Runtime/GrainReference.cs#L301-L307

I thought it is a derived `GrainReference` of some grain.

**Comment by sergeybykov** [comment]
Derived classes are generated by codegen. So everything should work automatically. That's why I'm wondering how this is used in the app code and what's changed.

**Comment by sillyousu** [comment]
@sergeybykov 

>That's why I'm wondering how this is used in the app code and what's changed.
I cleanup & rebuild the solution to make sure I don't change anything accidentally.
But I can see the same exception.

**Comment by sergeybykov** [comment]
Can you share how the grain interface and grain class are defined? What storage provider are you using? Did you also delete any grain state from the storage?

**Comment by sillyousu** [comment]
I suppect that runtime always passes  a base GrainReference instance to `StorageProvider.ReadStateAsync`

**Comment by sergeybykov** [comment]
>I suspect runtime always passes a base GrainReference instance to StorageProvider.ReadStateAsync

That's possible. Then this is a bug in the Redis provider to call `InterfaceName` on it. Providers included in the codebase don't do that.

**Comment by sillyousu** [comment]
@sergeybykov 
Feel free to close if it's intentionally.
