### ISSUE TITLE
Error: Extension not installed on grain attempting to invoke type OrleansCodeGenCancellationSourcesExtensionMethodInvoker

### ISSUE THREAD

**Issue by ifle** [dotnet/orleans#5142]
During calling to GrainCancellationTokenSource.Cancel I have following error.
I use GrainCancellationToken for aborting long running operation. 
What is missing? Thanks

```C#

Orleans.Runtime.GrainExtensionNotInstalledException
  HResult=0x80131500
  Message=Extension not installed on grain Server.Grains.ProgressWatcherGrain attempting to invoke type Orleans.Runtime.OrleansCodeGenCancellationSourcesExtensionMethodInvoker from invokable Orleans.Runtime.ActivationData
  Source=Orleans.Runtime
  StackTrace:
   at Orleans.Runtime.InsideRuntimeClient.<Invoke>d__62.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AsyncExecutorWithRetries.<>c__DisplayClass1_0.<<ExecuteWithRetries>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__4`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__4`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Server.Grains.ProjectGrain.<AbortProject>d__20.MoveNext()


```

**Comment by sergeybykov** [comment]
Do you have a repro project you could share?

**Comment by ifle** [comment]
Sorry, I don't have repro project for sharing

**Comment by sergeybykov** [comment]
@ifle Should we close it and reopen later if you get a repro?

The only thing I can think of is a version mismatch, but that's probably unlikely.

**Comment by jinfu-kooboo** [comment]
Hi @ifle, I'm runing into the same issue when GrainCancellationTokenSource.Cancel was called from the client. How did you finally fix it?

**Comment by ifle** [comment]
We no longer use it.
