### ISSUE TITLE
Failure to use stream providers with EventSequenceTokenV2

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#5172]
Hey folks!

After migrate some codebase that worked properly using SMS _streams_ to AWS SQS provider, I got this exception when trying to send/receive messages (both on client and silo):

```
[2018-11-08 19:22:54.095 UTC] hostid=XXXXXXXX env=dev shard=devtest proc=frontend level=WARN log=Orleans.InvokableObjectManager Exception during message body deserialization in LocalObjectMessagePumpAsync for message: Request S10.123.7.112:11111:279400800*stg/9856493027359806105/bae55299@Sbae55299->*cli/d9df2186@fab7c2bf77357389-7236-401d-b6a2-869be26fb1cf #1371: , Exception: System.Runtime.Serialization.SerializationException: Unsupported type 'Orleans.Providers.Streams.Common.EventSequenceTokenV2' encountered. Perhaps you need to mark it [Serializable] or define a custom serializer for it?
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at SQSBatchContainerDeserializer(Type , IDeserializationContext )
   at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeImmutable[T](Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeInvokeMethodRequest(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, IBinaryTokenStreamReader stream)
   at Orleans.Runtime.Message.DeserializeBody(SerializationManager serializationManager, List`1 bytes)
   at Orleans.Runtime.Message.GetDeserializedBody(SerializationManager serializationManager)
   at Orleans.InvokableObjectManager.<LocalObjectMessagePumpAsync>d__11.MoveNext()
```

The workaround as discussed with @sergeybykov was to add that type's assembly to the app parts list like this (both client and silo):

```
builder.AddApplicationPart(typeof(EventSequenceTokenV2 ).Assembly);
```

That unblocked us but it would be nice to get it fixed as it is an internal type from the runtime. I wonder if the codegen isn't generating code for it or if it does, the assembly isn't being loaded by it.

For reference, we are on Orleans 2.1.2 using the new source-to-source build time codegen.

Thanks!

**Comment by sergeybykov** [comment]
The odd thing here is that the additional `.AddApplicationPart()` call should be completely unnecessary if the previous `.AddApplicationPart()` calls have `.WithReferences()` after them.

**Comment by galvesribeiro** [comment]
For the record, we have several calls to `.AddApplicationPart()` and only the last one have `.WithReference()` as suggested by @ReubenBond on some chat we had months ago. Before that I was calling after every call of `.AddApplicationPart()` which seems unnecessary if I understood correctly.
