### ISSUE TITLE
AdoNetGrainStorage : Newtonsoft.Json.JsonSerializationException: Self referencing loop detected

### ISSUE THREAD

**Issue by ifle** [dotnet/orleans#5217]
We have json serialization error during WriteState for grain. We use the AdoNetGrainStorage .
Looks like the using of ReferenceLoopHandling json setting is missing.
```c#

Exc level 0: Newtonsoft.Json.JsonSerializationException: Self referencing loop detected with type 'Data.Item'. Path 'Items.$values[3].Orders.Item.$values'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Orleans.Storage.OrleansStorageDefaultJsonSerializer.Serialize(Object data)
   at Orleans.Storage.AdoNetGrainStorage.<>c__DisplayClass33_1.<WriteStateAsync>b__0(IDbCommand command)
   at Orleans.Persistence.AdoNet.Storage.RelationalStorage.<ExecuteAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Persistence.AdoNet.Storage.RelationalStorage.<ReadAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Storage.AdoNetGrainStorage.<WriteStateAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Core.StateStorageBridge`1.<WriteStateAsync>d__12.MoveNext()

```

**Comment by ReubenBond** [comment]
@ifle what is the best solution to this? I think ultimately it would be good if specific serialization options could be configured on a per-provider basis. Perhaps the solution would be to add a `JsonSerializerSettings` property to `AdoNetGrainStorageOptions` so that the user can customize it how they like. It would be configured to work with Orleans (grain reference serialization, etc) by default.

How does that sound? If it sounds like the right approach, would you be able to create a PR?

**Comment by ifle** [comment]
I don't have any special requirements for custom json serilization. I have simple grain state that has collection of items with parent\child  hierarchies. 
I think all orleans storage providers should save it out of box.
Take a look. 

Parent\Child classes
```csharp
public class Parent
{
	public string Id { get; set; }
	public List<Child> Children { get; set; } = new List<Child>();
}
public class Child
{
	public string Id { get; set; }
	public Parent Parent { get; set; }
}

````
Grain

```csharp
public class GrainState
{
    public List<Child> Children { get; set; }
}

public class ChildrenGrain : Grain<GrainState>, IChildrenGrain
{
     .....
}
```

Init state
```csharp
var parent = new Parent { Id = "parent-1" };
parent.Children.Add(new Child { Id = "child-1", Parent = parent });
parent.Children.Add(new Child { Id = "child-2", Parent = parent });
var state = new GrainState { Children =  parent.Children};
```
That is all. 
I think in OrleansJsonSerializer.GetDefaultSerializerSettings is missing ReferenceLoopHandling setting.
I also filed issue on Newtonsoft.Json repository about this strange behavior
https://github.com/JamesNK/Newtonsoft.Json/issues/1939

**Comment by JonPSmith** [comment]
Hi,

I added an issue on the [Newtonsoft.Json GitHub site](https://github.com/JamesNK/Newtonsoft.Json) about a "self-referencing loop detected" about two weeks ago, but no one has commented on it. I *think* my problem is related to this issue (throws "self-referencing loop detected" on serialization). I wonder if someone would mind looking at my issue.

I spent a day working out what was wrong, but the trigger turns out to bizarre - it fails if to properties have private setters! I'm happy to help if you can give me some pointers. I would really like to get this fixed if I can.

**Comment by ReubenBond** [comment]
Providers now expose a means for configuring `JsonSerializerSettings`. See the `AdoNetGrainStorageOptions.ConfigureJsonSerializerSettings` property. 

Hope that helps ☺
