### ISSUE TITLE
Microsoft.Orleans.OrleansCodeGenerator.Build dotnet core 2.2 support

### ISSUE THREAD

**Issue by RamanBut-Husaim** [dotnet/orleans#5245]
Hello,

Today I've tried to update my Orleans project to dotnet core 2.2 and faced the following issue. Seems that Microsoft.Orleans.OrleansCodeGenerator.Build package (https://www.nuget.org/packages/Microsoft.Orleans.OrleansCodeGenerator.Build/2.2.0-rc1) supports dotnet core 2.1 https://github.com/dotnet/orleans/blob/master/src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets and in latest RC-1 for orleans 2.2.0 there is no support for dotnet core 2.2 as well.

The error looks like this and it is expected due to the how *targets* file is implemented.
```
 Orleans-CodeGen - Generating file /home/rakkattakka/Development/reviewiteasy/ReviewItEasy.Webhooks/src/ReviewItEasy.Webhooks.Common/obj/Debug/netcoreapp2.2/ReviewItEasy.Webhooks.Common.orleans.g.cs
  -- Code Generation FAILED -- 
  
  Exc level 0: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  
     at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
     at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
     at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
     at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
     at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
     at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
     at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
     at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](Assembly element)
     at Orleans.ApplicationParts.AssemblyAttributeFeatureProvider`1.PopulateFeature(IEnumerable`1 parts, TFeature feature)
     at Orleans.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
     at Orleans.ApplicationPartManagerExtensions.CreateAndPopulateFeature[TFeature](IApplicationPartManager applicationPartManager)
     at Orleans.CodeGenerator.RoslynCodeGenerator..ctor(IApplicationPartManager partManager, ILoggerFactory loggerFactory)
     at Orleans.CodeGeneration.CodeGenerator.GenerateSourceForAssembly(Assembly grainAssembly, LogLevel logLevel)
     at Orleans.CodeGeneration.CodeGenerator.GenerateCodeInternal(CodeGenOptions options)
     at Orleans.CodeGeneration.CodeGenerator.GenerateCode(CodeGenOptions options)
     at Orleans.CodeGeneration.Program.Main(String[] args)
/home/rakkattakka/.nuget/packages/microsoft.orleans.orleanscodegenerator.build/2.1.2/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets(82,5): error MSB3073: The command ""/usr/share/dotnet/dotnet" "/home/rakkattakka/.nuget/packages/microsoft.orleans.orleanscodegenerator.build/2.1.2/build/../tasks/netcoreapp2.0/Orleans.CodeGeneration.Build.dll" "@obj/Debug/netcoreapp2.2/codegen/ReviewItEasy.Webhooks.Common.orleans.g.args.txt"" exited with code 3. [/home/rakkattakka/Development/reviewiteasy/ReviewItEasy.Webhooks/src/ReviewItEasy.Webhooks.Common/ReviewItEasy.Webhooks.Common.csproj]
```

I'm wondering whether there are plans to support netcore 2.2 with the release?

Thanks.

**Comment by ReubenBond** [comment]
@RamanBut-Husaim would the new codegen package work for you? `Microsoft.Orleans.CodeGenerator.MSBuild`

**Comment by RamanBut-Husaim** [comment]
Hello @ReubenBond ,
I've changed the code generation package for `Microsoft.Orleans.CodeGenerator.MSBuild` and it works fine now. At least all unit-tests and quick manual check looks good.

Thanks a lot for the tip.

However I have not found any information regarding this package in the docs. Is there any info available regarding this package so that the docs could be changed to include references or description for it?

I think that these two pieces should be updated:
+ https://dotnet.github.io/orleans/Documentation/core_concepts/code_generation.html
+ https://dotnet.github.io/orleans/Documentation/resources/Migration/Codegen.html

I could do this if I get more info on what are the principal differences.

Thanks.

**Comment by ReubenBond** [comment]
The principal difference between the two packages are that the new package uses Roslyn for code analysis as well as code generation. The old package only uses Roslyn for code generation and uses .NET Reflection for analysis.

The new package supports only build-time code generation (run-time code generation is possible in future).

Generally it supports .NET Core better than the old package because it does not need to load user assemblies for reflection.

**Comment by RamanBut-Husaim** [comment]
@ReubenBond hello.

Thanks a lot for the information. I found some additional notes from the release article - https://blogs.msdn.microsoft.com/orleans/2018/10/01/announcing-orleans-2-1/. 

I'm going to create a PR for docs during the week and after this will close this issue.

Thanks.

**Comment by RamanBut-Husaim** [comment]
@ReubenBond Hello. PR has been created - https://github.com/dotnet/orleans/pull/5257

**Comment by RamanBut-Husaim** [comment]
Closing this as PR has been merged.
