### ISSUE TITLE
Null reference in CallGrainActivate

### ISSUE THREAD

**Issue by darthkurak** [dotnet/orleans#5275]
Hi! I have really strange error and behavior. 
I'v created GranService which use EventProcessorHost and register appropriate EventHubProcessor.
EventHubProcessor get reference to OtherGrain and call on it method Process with grainId extracted from message. OtherGrain has state. There is a lot a different graindIds (around 10k). After running Silo on server, im getting following error:

```
Exc level 0: System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Providers.MongoDB.StorageProviders.MongoGrainStorage.GetCollection(String grainType)
   at Orleans.Providers.MongoDB.StorageProviders.MongoGrainStorage.<>c__DisplayClass16_0.<<ReadStateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.Providers.MongoDB.StorageProviders.MongoGrainStorage.<>c__DisplayClass20_0.<<DoAndLog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.Providers.MongoDB.StorageProviders.MongoGrainStorage.DoAndLog[T](String actionName, Func`1 action)
   at Orleans.Core.StateStorageBridge`1.ReadStateAsync() ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Providers.MongoDB.StorageProviders.MongoGrainStorage.GetCollection(String grainType)
   at Orleans.Providers.MongoDB.StorageProviders.MongoGrainStorage.<>c__DisplayClass16_0.<<ReadStateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.Providers.MongoDB.StorageProviders.MongoGrainStorage.<>c__DisplayClass20_0.<<DoAndLog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.Providers.MongoDB.StorageProviders.MongoGrainStorage.DoAndLog[T](String actionName, Func`1 action)
   at Orleans.Core.StateStorageBridge`1.ReadStateAsync()
   --- End of inner exception stack trace ---
   at Orleans.Core.StateStorageBridge`1.ReadStateAsync()
   at Orleans.LifecycleSubject.WrapExecution(CancellationToken ct, Func`2 action)
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
   --- End of inner exception stack trace ---
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
   at Orleans.Runtime.Catalog.CallGrainActivate(ActivationData activation, Dictionary`2 requestContextData)
```
- This error happen only on server, i can't reproduce it on my dev machine, and i see a correct documents in MongoDB
- This error happen also on AzureStorage provider:

```
Object reference not set to an instance of an object.
at Orleans.Storage.AzureBlobGrainStorage.ReadStateAsync(String grainType, GrainReference grainId, IGrainState grainState)
at Orleans.Core.StateStorageBridge1.ReadStateAsync() ---> System.NullReferenceException: Object reference not set to an instance of an object. at Orleans.Storage.AzureBlobGrainStorage.ReadStateAsync(String grainType, GrainReference grainId, IGrainState grainState) at Orleans.Core.StateStorageBridge1.ReadStateAsync()
--- End of inner exception stack trace ---
at Orleans.Core.StateStorageBridge1.ReadStateAsync() at Orleans.LifecycleSubject.WrapExecution(CancellationToken ct, Func2 action)
at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
--- End of inner exception stack trace ---
at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
at Orleans.Runtime.Catalog.CallGrainActivate(ActivationData activation, Dictionary`2 requestContextData)
```

**Comment by sergeybykov** [comment]
Do you get the same error if you call that grain directly, not from within your grain service?

**Comment by darthkurak** [comment]
I did the same logic with EventHubProcessorHost as OrleansClient and i get also Null Reference error, stacktrace:

```
   at Orleans.GrainFactory.GetGrainClassData(Type interfaceType, String grainClassNamePrefix) in D:\build\agent\_work\23\s\src\Orleans.Core\Core\GrainFactory.cs:line 188
   at Orleans.GrainFactory.GetGrain[TGrainInterface](Guid primaryKey, String grainClassNamePrefix) in D:\build\agent\_work\23\s\src\Orleans.Core\Core\GrainFactory.cs:line 61
   at Lingaro.OpenIoT.TelemetryReader.EventHubProcessor.Process(EventData message) in C:\src\lingaro-open-iot-platform\Lingaro.OpenIoT\Lingaro.OpenIoT.TelemetryReader\Class1.cs:line 104
   at Lingaro.OpenIoT.TelemetryReader.EventHubProcessor.<ProcessInParallel>b__9_0(EventData message) in C:\src\lingaro-open-iot-platform\Lingaro.OpenIoT\Lingaro.OpenIoT.TelemetryReader\Class1.cs:line 86
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Any ideas?

**Comment by ReubenBond** [comment]
Could you show the code you use to reproduce this, @darthkurak?

**Comment by darthkurak** [comment]
Ok, that null reference on grainTypeResolver was caused by missed client.Connect(); 
I managed to go further, and now, it seems that EventData from EventHubs is the problem, as Im getting:

"Unexpected token 'Error' introducing type specifier" error when calling grain method.

My grain interface:
```
   public interface IDeviceGrain2 : IGrainWithGuidKey
    {
        Task Process(EventData eventHubMessage);
    }
```

**Comment by ReubenBond** [comment]
Is `EventData` serializable, @darthkurak? It seems that it isn't. You may have to configure a serializer for it. See serialization docs https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/serialization.html

**Comment by ReubenBond** [comment]
Closing due to inactivity, can reopen if needed
