### ISSUE TITLE
Gettting a System.TypeAccessException: Unable to find a type named Microsoft.FSharp.Core.LanguagePrimitives

### ISSUE THREAD

**Issue by darting** [dotnet/orleans#5292]
Hi there, I am getting a `Gettting a System.TypeAccessException: Unable to find a type named Microsoft.FSharp.Core.LanguagePrimitives` when I try to work with a FSharp project.

Here is the source code: https://github.com/darting/OrleansTicTacToe

the exception details list as below:
```
System.TypeAccessException: Unable to find a type named Microsoft.FSharp.Core.LanguagePrimitives+-cctor@2255-2`1[[System.Tuple`2[[System.Int32],[System.Int32]]]],FSharp.Core
   at Orleans.Runtime.CachedTypeResolver.ResolveType(String name) in D:\build\agent\_work\23\s\src\Orleans.Core\AssemblyLoader\CachedTypeResolver.cs:line 19
   at Orleans.Serialization.TypeSerializer.GetTypeFromName(String assemblyQualifiedTypeName, Boolean throwOnError) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\TypeSerializer.cs:line 104
   at Orleans.Serialization.TypeSerializer.GetTypeFromTypeKey(TypeKey key, Boolean throwOnError) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\TypeSerializer.cs:line 75
   at Orleans.Serialization.ILBasedSerializer.ReadType(ILSerializerTypeToken token, IDeserializationContext context, Type expectedType) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\ILBasedSerializer.cs:line 148
   at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\ILBasedSerializer.cs:line 112
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1283
   at FSharpMap`2Deserializer(Type , IDeserializationContext )
   at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\ILBasedSerializer.cs:line 112
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1283
   at ModelDeserializer(Type , IDeserializationContext )
   at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\ILBasedSerializer.cs:line 112
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1283
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\BuiltInTypes.cs:line 2115
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1322
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, IBinaryTokenStreamReader stream) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1201
   at Orleans.Runtime.Message.GetDeserializedBody(SerializationManager serializationManager) in D:\build\agent\_work\23\s\src\Orleans.Core\Messaging\Message.cs:line 407
   at Orleans.Runtime.SharedCallbackData.ResponseCallback(Message message, TaskCompletionSource`1 context) in D:\build\agent\_work\23\s\src\Orleans.Core\Runtime\SharedCallbackData.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask) in D:\build\agent\_work\23\s\src\Orleans.Core\Async\TaskExtensions.cs:line 100
   at WebApi.Controllers.GameController.JoinGame(String token, String gameId) in C:\Users\Valor\github\valor\OrleansTicTacToe\WebApi\Controllers\GameController.cs:line 46
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
**version info:**
- .Net Core 2.2
- Orleans 2.2.0
- C# 7.3
- FSharp.Core 4.5.2

**Comment by darting** [comment]
Steps:
```sh
cd Silo
dotnet run
```
```sh
cd WebApi
dotnet run
```
After run Silo and WebApi project, you can access the url to get the exception:

`https://localhost:5001/api/game/joingame?token=mytoken&gameid=abc`

**Comment by veikkoeeva** [comment]
@darting Just by looking at the stack, the problem seem to be F# tuples which have been implemented differently from the C# ones (I'm not sure if they're aligned now that C# has anonymous tuples and destructuring too). Maybe it helps to refactor `int * int` instances to actual tuples, but this is just a guess. @ReubenBond is probably the most knowledgeable of this in case renaming doesn't help or some else problem isn't noticed.

**Comment by veikkoeeva** [comment]
@darting The same error? Records by default are also different when "on the C# side", for one they do not have setters but readonly properties. You could try decorating with `CLIMutable` and `DataContract` (and maybe with `KnownType`. I believe there is also a newer version of the F# Core library.

Apologies this is a bit of a hit-and-miss now, I'm in the middle of things here.

**Comment by darting** [comment]
hi @veikkoeeva , I try to add `CLIMutable` and `DataContract`, still got the same error, here is the error detail:

```
System.TypeAccessException: Unable to find a type named Microsoft.FSharp.Core.LanguagePrimitives+-cctor@2255-2`1[[TicTacToe.Pos,TicTacToe]],FSharp.Core
   at Orleans.Runtime.CachedTypeResolver.ResolveType(String name) in D:\build\agent\_work\23\s\src\Orleans.Core\AssemblyLoader\CachedTypeResolver.cs:line 19
   at Orleans.Serialization.TypeSerializer.GetTypeFromName(String assemblyQualifiedTypeName, Boolean throwOnError) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\TypeSerializer.cs:line 104
   at Orleans.Serialization.TypeSerializer.GetTypeFromTypeKey(TypeKey key, Boolean throwOnError) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\TypeSerializer.cs:line 75
   at Orleans.Serialization.ILBasedSerializer.ReadType(ILSerializerTypeToken token, IDeserializationContext context, Type expectedType) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\ILBasedSerializer.cs:line 148
   at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\ILBasedSerializer.cs:line 112
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1283
   at FSharpMap`2Deserializer(Type , IDeserializationContext )
   at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\ILBasedSerializer.cs:line 112
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1283
   at ModelDeserializer(Type , IDeserializationContext )
   at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\ILBasedSerializer.cs:line 112
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1283
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\BuiltInTypes.cs:line 2115
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1322
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, IBinaryTokenStreamReader stream) in D:\build\agent\_work\23\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1201
   at Orleans.Runtime.Message.GetDeserializedBody(SerializationManager serializationManager) in D:\build\agent\_work\23\s\src\Orleans.Core\Messaging\Message.cs:line 407
   at Orleans.Runtime.SharedCallbackData.ResponseCallback(Message message, TaskCompletionSource`1 context) in D:\build\agent\_work\23\s\src\Orleans.Core\Runtime\SharedCallbackData.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask) in D:\build\agent\_work\23\s\src\Orleans.Core\Async\TaskExtensions.cs:line 100
   at WebApi.Controllers.GameController.JoinGame(String token, String gameId) in C:\Users\Valor\github\valor\OrleansTicTacToe\WebApi\Controllers\GameController.cs:line 46
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by veikkoeeva** [comment]
@dartig Should probably soon take a look at the code, but would https://github.com/dotnet/orleans/issues/4188 help.

**Comment by darting** [comment]
hi @veikkoeeva, sorry for late reply,  I have tried but doesn't work.

**Comment by ReubenBond** [comment]
To help debug this, could you please build your project with `OrleansCodeGenLogLevel: Trace` and upload the build log? You can enable it in your fsproj using

``` xml
<PropertyGroup>
  <OrleansCodeGenLogLevel>Trace</OrleansCodeGenLogLevel>
</PropertyGroup>
```

I also opened #5298 for this, @darting.

**Comment by darting** [comment]
hi @ReubenBond , I dont have `Microsoft.Orleans.CodeGenerator.MSBuild` for my fsproject. But I have add `<OrleansCodeGenLogLevel>Trace</OrleansCodeGenLogLevel>` to my 3 projects (Grains, GrainInterfaces, TicTacToe -- the fsproject). Here is the log, thanks.

Silo logs:
[silo-log.txt](https://github.com/dotnet/orleans/files/2734986/silo-log.txt)

WebApi logs: (client project)
[webapi-log.txt](https://github.com/dotnet/orleans/files/2734987/webapi-log.txt)

**Comment by darting** [comment]
Its fixed by change FSharp `Map` to  `System.Collections.Generic.IDictionary`, thanks @ashtonkj 

https://github.com/darting/OrleansTicTacToe/blob/b3ef47ee90d802bf87e4c46cb201519ab49d9f42/TicTacToe/Library.fs#L29

https://github.com/darting/OrleansTicTacToe/blob/b3ef47ee90d802bf87e4c46cb201519ab49d9f42/TicTacToe/Library.fs#L45

**Comment by rafikiassumani-msft** [comment]
@darting I am closing this issue as it appears that the suggestion from @ashtonkj  worked for you.
