### ISSUE TITLE
Serialization Exception for ImmutableArray<int> 

### ISSUE THREAD

**Issue by b4barnett** [dotnet/orleans#5332]
Hi,

Using 1.5.0 (we can't yet upgrade to 2.0)

```
Orleans.Runtime.OrleansMessageRejectionException: System.Runtime.Serialization.SerializationException: Type 'System.Collections.Immutable.ImmutableArray`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' in Assembly 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at Orleans.Serialization.BinaryFormatterSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.BuiltInTypes.SerializeInvokeMethodRequest(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
   at Orleans.Serialization.SerializationManager.Serialize(Object raw, BinaryTokenStreamWriter stream)
   at Orleans.Runtime.Message.Serialize(SerializationManager serializationManager, Int32& headerLengthOut, Int32& bodyLengthOut)
   at Orleans.Messaging.OutgoingMessageSender.Process(Message msg)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Common.Domain.Subscriptions.SubscriptionGrain.<SubscribeToResults>d__22.MoveNext() in C:\BuildAgent\work\afca04fc01ce655a\Application\Common\Domain\Subscriptions\SubscriptionGrain.cs:line 215
```
In many other places we use `ImmutableArray` but with reference types and don't experience any issues, but we've found recently that for `ImmutableArray<int>`  the serialization fails (data structure below). I'm guessing other values types would fail but I've not tried this.
```
    [Serializable, Immutable]
    public abstract class GroupingSubscriberBase
    {
        protected ImmutableArray<int> AvailableSegements;
        protected ImmutableArray<SegmentDto> SegmentDtos;

        protected readonly bool DoesEmptyStatusNoneMeanActive;

        private Metrics _message;

        protected GroupingSubscriberBase( ImmutableArray<int> availableSegements, bool doesEmptyStatusNoneMeanActive, ImmutableArray<SegmentDto> segmentDtos )
        {
            AvailableSegements = availableSegements;
            DoesEmptyStatusNoneMeanActive = doesEmptyStatusNoneMeanActive;
            SegmentDtos = segmentDtos;
        }
    }

    [Serializable, Immutable]
    public class SpecificGroupingSubscriber : GroupingSubscriberBase
    {
        private IReceiveResults _resultsReceiver; //inherits IAddressable and is created as GrainReference

        public SpecificGroupingSubscriber( ImmutableArray<int> availableSegements,
            IReceiveResults receiver,
            bool doesEmptyStatusNoneMeanActive, ImmutableArray<SegmentDto> segmentDtos )
            : base( availableSegements, doesEmptyStatusNoneMeanActive, segmentDtos )
        {
            _resultsReceiver = receiver;
        }
    }
```
Thankfully not critical that we use `ImmutableArray` can just suffice with a normal array

**Comment by ReubenBond** [comment]
@b4barnett could you confirm that you have code generation enabled for the assembly in question? Could you show us the signature of the grain method being called?

**Comment by b4barnett** [comment]
@ReubenBond The assembly has build time code generation enabled for the assembly.

I'll try get the method signatures to you soon

**Comment by ReubenBond** [comment]
Closing for inactivity - we can re-open if needed
