### ISSUE TITLE
Unable to use Microsoft.Azure.EventHubs package greater than 1.0.3 with Microsoft.Orleans.OrleansServiceBus

### ISSUE THREAD

**Issue by alexmg** [dotnet/orleans#5369]
It is not possible to use a version of `Microsoft.Azure.EventHubs` greater than `1.0.3` in the same application as Orleans if the EventHubs stream provider is being used.

The `Microsoft.Orleans.OrleansServiceBus` package depends on version `1.0.3` of `Microsoft.Azure.EventHubs` (released Aug 23, 2017) and breaking changes have been made in later releases.

Even though it is not called out specifically in the release notes for `1.1.0` the `EventHubClient.CreateReceiver` method signature was changed to include an optional `ReceiverOptions` parameter.

https://github.com/Azure/azure-event-hubs-dotnet/releases/tag/1.1.0

A `MissingMethodException` is thrown when the `EventHubAdapterReceiver` attempts to create the `PartitionReceiver` due to the additional parameter that was added to the overload being used.

```
System.MissingMethodException: Method not found: 'Microsoft.Azure.EventHubs.PartitionReceiver Microsoft.Azure.EventHubs.EventHubClient.CreateReceiver(System.String, System.String, System.String, Boolean)'.
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.CreateReceiver(EventHubPartitionSettings partitionSettings, String offset, ILogger logger, ITelemetryProducer telemetryProducer)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.CreateReceiver(EventHubPartitionSettings partitionSettings, String offset, ILogger logger, ITelemetryProducer telemetryProducer)
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.Initialize()
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.GetQueueMessagesAsync(Int32 maxCount)
   at Orleans.Streams.PersistentStreamPullingAgent.ReadFromQueue(QueueId myQueueId, IQueueAdapterReceiver rcvr, Int32 maxCacheAddCount)
   at Orleans.AsyncExecutorWithRetries.ExecuteWithRetriesHelper[T](Func`2 function, Int32 callCounter, Int32 maxNumSuccessTries, Int32 maxNumErrorTries, TimeSpan maxExecutionTime, DateTime startExecutionTime, Func`3 retryValueFilter, Func`3 retryExceptionFilter, IBackoffProvider onSuccessBackOff, IBackoffProvider onErrorBackOff) 
```

A further breaking change was introduced to `Microsoft.Azure.EventHubs` in `2.0.0` and is mentioned in the release notes. Removal of the `Microsoft.Azure.EventHubs.PartitionReceiver.StartOfStream` property which is currently referenced by `Orleans.ServiceBus.Providers.EventHubConstants.StartOfStream` results in a `TypeInitializationException`.

https://github.com/Azure/azure-event-hubs-dotnet/releases/tag/v2.0.0

The inner `MissingFieldException` is a result of the property removal.

```
System.TypeInitializationException: The type initializer for 'Orleans.ServiceBus.Providers.EventHubConstants' threw an exception. ---> System.MissingFieldException: Field not found: 'Microsoft.Azure.EventHubs.PartitionReceiver.StartOfStream'.
   at Orleans.ServiceBus.Providers.EventHubConstants..cctor()
   --- End of inner exception stack trace ---
   at Orleans.ServiceBus.Providers.EventHubPartitionCheckpointEntity.Create(String streamProviderName, String serviceId, String partition) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubPartitionCheckpointEntity.cs:line 17
   at Orleans.ServiceBus.Providers.EventHubCheckpointer..ctor(AzureTableStreamCheckpointerOptions options, String streamProviderName, String partition, String serviceId, ILoggerFactory loggerFactory) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubCheckpointer.cs:line 92
   at Orleans.ServiceBus.Providers.EventHubCheckpointer.Create(AzureTableStreamCheckpointerOptions options, String streamProviderName, String partition, String serviceId, ILoggerFactory loggerFactory) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubCheckpointer.cs:line 70
   at Orleans.ServiceBus.Providers.EventHubCheckpointer..ctor(AzureTableStreamCheckpointerOptions options, String streamProviderName, String partition, String serviceId, ILoggerFactory loggerFactory) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubCheckpointer.cs:line 92
   at Orleans.ServiceBus.Providers.EventHubCheckpointer.Create(AzureTableStreamCheckpointerOptions options, String streamProviderName, String partition, String serviceId, ILoggerFactory loggerFactory) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubCheckpointer.cs:line 70
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.Initialize() in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubAdapterReceiver.cs:line 115
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.Initialize() in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubAdapterReceiver.cs:line 115
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.Initialize() in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubAdapterReceiver.cs:line 115
   at Orleans.OrleansTaskExtentions.SafeExecute(Func`1 action) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExtensions.cs:line 151
   at Orleans.OrleansTaskExtentions.SafeExecute(Func`1 action) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExtensions.cs:line 151
   at Orleans.OrleansTaskExtentions.SafeExecute(Func`1 action) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExtensions.cs:line 151
   at Orleans.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExtensions.cs:line 138
   at Orleans.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExtensions.cs:line 138
   at Orleans.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExtensions.cs:line 138
   at Orleans.Streams.PersistentStreamPullingAgent.AsyncTimerCallback(Object state) in D:\build\agent\_work\24\s\src\Orleans.Runtime\Streams\PersistentStream\PersistentStreamPullingAgent.cs:line 348
   at Orleans.Streams.PersistentStreamPullingAgent.AsyncTimerCallback(Object state) in D:\build\agent\_work\24\s\src\Orleans.Runtime\Streams\PersistentStream\PersistentStreamPullingAgent.cs:line 348
```

It appears that the constant value `"-1"` has been moved to an internal property of the `EventPosition` class.

https://github.com/Azure/azure-event-hubs-dotnet/blob/8aae6b6ec1af44de69326288854f5811985db539/src/Microsoft.Azure.EventHubs/EventPosition.cs#L21

I have investigated the changes required to upgrade `Microsoft.Azure.EventHubs` in a fork.

- Modify `Directory.Build.props` to update `Microsoft.Azure.EventHubs` package to `2.2.1` and `System.Net.Http` to `4.3.3` (to prevent downgrade in other projects).
- The `EventHubConstants.StartOfStream` property can be replaced with the constant `"-1"` leaving the value as a `string`.
- `EventPosition` is only required when creating the `PartitionReceiver` which is done inside the `EventHubAdapterReceiver.CreateReceiver` method where the offset (`string`) and inclusive flag (`bool`) are already available.
- Update reflection based code in `EventHubUtils` to cater for internal changes to `EventData`. Reflection is no longer required for setting the `Offset`, `SequenceNumber`, `EnqueuedTime` and `PartitionKey` properties, but is still required to initialize `SystemProperties` with a new `SystemPropertiesCollection` when `null`.

The unit tests are passing with the exception of `EHBatchedSubscriptionMultiplicityTests.EHBatchedMultipleLinearSubscriptionTest`. This fixture contains integration style tests that I had to point at my own EventHub and Storage Table to get working. I wasn't sure if this failure was related to the upgrade so I ran the same test without the upgrade and it still fails for me locally. I assume there is a difference between my setup and the one used in your build system.

I would be happy to put together a PR with these changes if you are interested.

**Comment by sergeybykov** [comment]
Yes, we are aware of this problem. We discussed the option of releasing a separate NuGet package for the latest version of Event Hub.

**Comment by sergeybykov** [comment]
Resolved via #5384.

**Comment by alexmg** [comment]
I just noticed that `3.0.0` has been released.

https://github.com/Azure/azure-event-hubs-dotnet/releases/tag/3.0.0

No further breaking changes mentioned in the release notes. The `SystemProperties` might be even easier to work with in tests though.

**Comment by alexmg** [comment]
I did some testing and it is possible to use `3.0.0` of the `Microsoft.Azure.EventHubs.Processor` package in the silo even though the Event Hubs stream provider has a dependency on `2.2.1` of `Microsoft.Azure.EventHubs`. The provider will end up using the `3.0.0` version of `Microsoft.Azure.EventHubs` but there does not appear to be any breaking changes.

**Comment by jason-bragg** [comment]
That's great news.  We should move to 3.x eventually and we'll resurrect this PR when we do, but your findings seem to indicate that we need not rush the update.
Much thanks!
