### ISSUE TITLE
System.Reflection.AmbiguousMatchException: 'Multiple custom attributes of the same type found.'

### ISSUE THREAD

**Issue by aletc1** [dotnet/orleans#5398]
Hi,

When I used the Dashboard v2.2.0 with Orleans.Server v2.2.4 the following exception throws:

```
Unhandled Exception: System.Reflection.AmbiguousMatchException: Multiple custom attributes of the same type found.
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
   at Orleans.CodeGenerator.RoslynCodeGenerator.ShouldGenerateCodeForAssembly(Assembly assembly) in D:\build\agent\_work\25\s\src\Orleans.CodeGeneration\RoslynCodeGenerator.cs:line 653
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssemblies(IEnumerable`1 assemblies) in D:\build\agent\_work\25\s\src\Orleans.CodeGeneration\RoslynCodeGenerator.cs:line 109
   at Orleans.Hosting.ApplicationPartManagerCodeGenExtensions.WithCodeGeneration(IApplicationPartManagerWithAssemblies manager, ILoggerFactory loggerFactory) in D:\build\agent\_work\25\s\src\Orleans.CodeGeneration\ApplicationPartManagerCodeGenExtensions.cs:line 46
   at Orleans.ServiceCollectionExtensions.<>c.<UseDashboard>b__0_0(IApplicationPartManager appParts)
   at Orleans.Hosting.SiloHostBuilderExtensions.ConfigureApplicationParts(ISiloHostBuilder builder, Action`1 configure) in D:\build\agent\_work\24\s\src\Orleans.Runtime.Abstractions\Hosting\Generic\SiloHostBuilderExtensions.cs:line 153
   at Orleans.ServiceCollectionExtensions.UseDashboard(ISiloHostBuilder builder, Action`1 configurator)
```
The workaround is to downgrade Microsoft.Orleans.Server to v2.2.0 and just worked again... but would be nice if latest verions can be used.

**Comment by alexmg** [comment]
I also get the same error using the latest `2.2.4` package on the CI feed. The issue has also been raised in the OrleansDashboard repository.

OrleansContrib/OrleansDashboard#213

**Comment by alexmg** [comment]
The `Orleans.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null` assembly in the `2.2.4` package is returning two `OrleansCodeGenerationTargetAttribute` attributes.

![orleanscodegenerationtargetattributes](https://user-images.githubusercontent.com/131293/53478948-b9197d80-3ac3-11e9-8b24-c89c2b3dd65a.PNG)

That is causing the `GetCustomAttribute` method to throw the `AmbiguousMatchException`.

**Comment by ReubenBond** [comment]
Are you able to provide a repro project, @alexmg? If you could attach it to this issue as a zip that would help me fix this in time for 2.3.0.

**Comment by alexmg** [comment]
@ReubenBond Sounds like multiple attributes is the expected behaviour. Do you still need that repro project?

**Comment by ReubenBond** [comment]
No, I don't - thank you :)
