### ISSUE TITLE
NPE on parsing the partition of an IOT Event Hub endpoint

### ISSUE THREAD

**Issue by ejlevin1** [dotnet/orleans#5418]
I've spent some time on trying to get the AddEventHubStreams to put from the IOT Hubs default endpoint, and I'm running into the same issues that @andrew-laughlin is reporting here (https://github.com/dotnet/orleans/issues/4572#issue-321329955) ... @jason-bragg I noticed that much of this code was written by you, so I'm hoping you can help as I may just be doing something wrong.  Here is what I've got -- and I'm hoping I am just doing something stupid and don't need to extend all the classes as Andrew did.

```
private static async Task<ISiloHost> StartSilo()
{
    // define the cluster configuration
    var builder = new SiloHostBuilder()
        .UseLocalhostClustering()
        .Configure<ClusterOptions>(options =>
        {
            options.ClusterId = "dev";
            options.ServiceId = "HelloWorldApp";
        })
        .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
        .AddMemoryGrainStorage("PubSubStore")
        .AddEventHubStreams("Source.AntEvents", (SiloEventHubStreamConfigurator c) => {
            c.ConfigureEventHub((opts) =>
            {
                opts.Configure(options =>
                {
                    options.ConnectionString = "Endpoint=sb://iothub-ns-**********.servicebus.windows.net/;SharedAccessKeyName=<owner>;SharedAccessKey=<key>;EntityPath=ao-iot-dev-1";
                    options.ConsumerGroup = "OrleansSiloHost";
                    options.Path = "ao-iot-dev-1";
                });
            })
            .UseEventHubCheckpointer(opts => opts.Configure(options =>
            {
                options.ConnectionString = <connection string>;
                options.TableName = "orleanspubsubtbl";
                options.PersistInterval = TimeSpan.FromSeconds(1);
            }))
            .ConfigureStreamPubSub(StreamPubSubType.ImplicitOnly);
        })
        .ConfigureLogging(logging => logging.AddConsole());

    var host = builder.Build();
    await host.StartAsync();
    return host;
}
```

Here is my Implicit Receiver Grain:
```
[ImplicitStreamSubscription("iothub-ns-**********")]
    public class EventHubSubscriber : Grain, IEventHubSubscriber, IAsyncObserver<string>
    {
        public async override Task OnActivateAsync()
        {
            var streamProvider = GetStreamProvider(SiloHostProviders.AntPlusStreamingProvider);
            var stream = streamProvider.GetStream<string>(this.GetPrimaryKey(), "iothub-ns-**********");
            await stream.SubscribeAsync(this);
        }

        public Task OnCompletedAsync()
        {
            Console.WriteLine("Completed.");
            return Task.CompletedTask;
        }

        public Task OnErrorAsync(Exception ex)
        {
            Console.WriteLine("ERROR: " + ex.Message);
            return Task.CompletedTask;
        }

        public Task OnNextAsync(string item, StreamSequenceToken token = null)
        {
            Console.WriteLine("Received: " + item);
            return Task.CompletedTask;
        }
    }
```

And here is the error output.  Line 252 is where it is trying to parse the partition ID; however, the partitions are showing in the logging as 0 and 1 which are hooked up to Queues.

```
info: Orleans.Streams.PersistentStreamPullingManager-Source.AntEvents[103502]
      Init.
info: Orleans.Streams.PersistentStreamPullingManager-Source.AntEvents[103503]
      Initialize: I am now responsible for 2 queues: [source.antevents-0, source.antevents-1].
info: Orleans.Streams.PersistentStreamPullingManager-Source.AntEvents[103517]
      Starting agents for 2 queues: [source.antevents-0, source.antevents-1]
info: Orleans.Streams.*stg/1515185665224622770/b07a42b2.Source.AntEvents[103301]
      Created PersistentStreamPullingAgent *stg/1515185665224622770/4e5cba2a2274a31c15070555b07a42b201000000000000ff-0x26156FA1 for Stream Provider Source.AntEvents on silo S127.0.0.1:11111:289281871 for Queue source.antevents-0-0x00000000.
info: Orleans.Streams.*stg/3261463326979622579/ac9586b3.Source.AntEvents[103301]
      Created PersistentStreamPullingAgent *stg/3261463326979622579/42fdbe1d2be353442d430b9dac9586b301000000000000ff-0xD22CAFD5 for Stream Provider Source.AntEvents on silo S127.0.0.1:11111:289281871 for Queue source.antevents-1-0x80000001.
info: Orleans.Streams.*stg/1515185665224622770/b07a42b2.Source.AntEvents[103302]
      Init of PersistentStreamPullingAgent *stg/1515185665224622770/4e5cba2a2274a31c15070555b07a42b201000000000000ff-0x26156FA1 on silo S127.0.0.1:11111:289281871 for queue source.antevents-0-0x00000000.
info: Orleans.Streams.*stg/3261463326979622579/ac9586b3.Source.AntEvents[103302]
      Init of PersistentStreamPullingAgent *stg/3261463326979622579/42fdbe1d2be353442d430b9dac9586b301000000000000ff-0xD22CAFD5 on silo S127.0.0.1:11111:289281871 for queue source.antevents-1-0x80000001.
info: Orleans.ServiceBus.Providers.EventHubAdapterReceiver.ao-iot-dev-1.0[0]
      Initializing EventHub partition ao-iot-dev-1-0.
info: Orleans.ServiceBus.Providers.EventHubAdapterReceiver.ao-iot-dev-1.1[0]
      Initializing EventHub partition ao-iot-dev-1-1.
info: Orleans.ServiceBus.Providers.EventHubCheckpointer[0]
      Creating EventHub checkpointer for partition 1 of stream provider Source.AntEvents with serviceId HelloWorldApp.
info: Orleans.ServiceBus.Providers.EventHubCheckpointer[0]
      Creating EventHub checkpointer for partition 0 of stream provider Source.AntEvents with serviceId HelloWorldApp.
info: Orleans.Streams.*stg/1515185665224622770/b07a42b2.Source.AntEvents[103304]
      Taking queue source.antevents-0-0x00000000 under my responsibility.
info: Orleans.Streams.*stg/3261463326979622579/ac9586b3.Source.AntEvents[103304]
      Taking queue source.antevents-1-0x80000001 under my responsibility.
info: Orleans.Streams.PersistentStreamPullingManager-Source.AntEvents[103508]
      Added 2 new queues: [source.antevents-0, source.antevents-1]. Now own total of 2 queues: [source.antevents-0, source.antevents-1]
info: Orleans.Streams.PersistentStreamPullingManager-Source.AntEvents[103519]
      Started agents.
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      Lifecycle observer Orleans.Providers.Streams.Common.PersistentStreamProvider-Source.AntEvents started in stage 20000 which took 156 Milliseconds.
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      Starting lifecycle stage 20000 took 156.4409 Milliseconds
info: Orleans.Streaming.EventHubs.AzureTableDataManager[100801]
      Attached to Azure storage table orleanspubsubtbl
info: Orleans.Streaming.EventHubs.AzureTableDataManager[100801]
      Attached to Azure storage table orleanspubsubtbl
info: Orleans.ServiceBus.Providers.EventHubAdapterReceiver.ao-iot-dev-1.0[0]
      Starting to read latest messages from EventHub partition ao-iot-dev-1-0 at offset -1
info: Orleans.ServiceBus.Providers.EventHubAdapterReceiver.ao-iot-dev-1.1[0]
      Starting to read latest messages from EventHub partition ao-iot-dev-1-1 at offset 105560
      ...........
      ...........
      ...........
info: Orleans.Runtime.Catalog[100507]
      Before collection#2: memory=9MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.
info: Orleans.Runtime.Catalog[100508]
      After collection#2: memory=9MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0019287.
warn: Orleans.Streams.*stg/3261463326979622579/ac9586b3.Source.AntEvents[103312]
      Exception while retrying the 0th time reading from queue source.antevents-1
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Guid.Parse(String input)
   at Orleans.ServiceBus.Providers.EventHubDataAdapter.GetStreamPosition(EventData queueMessage) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubDataAdapter.cs:line 252
   at Orleans.ServiceBus.Providers.EventHubDataAdapter.QueueMessageToCachedMessage(CachedEventHubMessage& cachedMessage, EventData queueMessage, DateTime dequeueTimeUtc) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubDataAdapter.cs:line 205
   at Orleans.Providers.Streams.Common.CachedMessageBlock`1.Add[TQueueMessage](TQueueMessage queueMessage, DateTime dequeueTimeUtc, ICacheDataAdapter`2 dataAdapter) in D:\build\agent\_work\24\s\src\OrleansProviders\Streams\Common\PooledCache\CachedMessageBlock.cs:line 118
   at Orleans.Providers.Streams.Common.CachedMessagePool`2.AllocateMessage(TQueueMessage queueMessage, DateTime dequeueTimeUtc, StreamPosition& streamPosition) in D:\build\agent\_work\24\s\src\OrleansProviders\Streams\Common\PooledCache\CachedMessagePool.cs:line 42
   at Orleans.Providers.Streams.Common.PooledQueueCache`2.Add(TQueueMessage message, DateTime dequeueTimeUtc) in D:\build\agent\_work\24\s\src\OrleansProviders\Streams\Common\PooledCache\PooledQueueCache.cs:line 330
   at Orleans.Providers.Streams.Common.PooledQueueCache`2.Add(List`1 messages, DateTime dequeueTime) in D:\build\agent\_work\24\s\src\OrleansProviders\Streams\Common\PooledCache\PooledQueueCache.cs:line 312
   at Orleans.ServiceBus.Providers.EventHubQueueCache`1.Add(List`1 messages, DateTime dequeueTimeUtc) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubQueueCache.cs:line 136
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.GetQueueMessagesAsync(Int32 maxCount) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubAdapterReceiver.cs:line 190
   at Orleans.Streams.PersistentStreamPullingAgent.ReadFromQueue(QueueId myQueueId, IQueueAdapterReceiver rcvr, Int32 maxCacheAddCount) in D:\build\agent\_work\24\s\src\Orleans.Runtime\Streams\PersistentStream\PersistentStreamPullingAgent.cs:line 435
   at Orleans.AsyncExecutorWithRetries.ExecuteWithRetriesHelper[T](Func`2 function, Int32 callCounter, Int32 maxNumSuccessTries, Int32 maxNumErrorTries, TimeSpan maxExecutionTime, DateTime startExecutionTime, Func`3 retryValueFilter, Func`3 retryExceptionFilter, IBackoffProvider onSuccessBackOff, IBackoffProvider onErrorBackOff) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\AsyncExecutorWithRetries.cs:line 143
```

**Comment by jason-bragg** [comment]
Was the data in the hub written by Orleans streams?

If not you'll, unfortunately, need to write a data adapter to get the streamId and deserialize the data in the hub.  At the moment this is far more painful than we'd like.

We've a work item to address this that also describes what users currently need do to conform their data to orleans (in way of an explanation of why we need address this).  https://github.com/dotnet/orleans/issues/4621

If the data was written to eventhub by Orleans streams, then I'm misunderstanding the issue, so please let me know if my assumptions are off.

**Comment by ejlevin1** [comment]
@jason-bragg -- yep, this was an IoT device writing to an event hub, and then I wanted orleans to pick it up and process (i.e. orleans isn't writing to it at all).  Appreciate the link to the other tracker -- your comment in there about EH consumption should help quite a bit.

**Comment by jason-bragg** [comment]
That issue is also linked to several other related discussions, many specific to using EHStreams with IoT.  As one would expect, there’s a fair amount of noise in those threads, but they are probably worth taking the time to at least skim through, as there has been a fair amount of thinking on this subject already.
