### ISSUE TITLE
Microsoft.Orleans.CodeGenerator.MSBuild - Issues with GrainState being of generic type

### ISSUE THREAD

**Issue by erikljung** [dotnet/orleans#5482]
Hi, we observed some differences between the `Microsoft.Orleans.OrleansCodeGenerator.Build` (works) and `Microsoft.Orleans.CodeGenerator.MSBuild` (fails) code generator.
Where we're having intermittent issues (while running the same test without rebuild) that produces the exception below.

We have a grain with a state of a generic type. This works fine with `Build` but fails with `MSBuild`. Changing the generic state to a concrete implementation solves the problem in the `MSBuild`-case.

```
public class MyGrain : Grain<StateHolder<SomeState>>, IMyGrain
```

```
Error Message:
 Orleans.Runtime.OrleansException : Error from storage provider MemoryGrainStorage.Project.Grains.Project.Grains.MyGrain during WriteState for grain Type=Project.Grains.Project.Grains.MyGrain Pk=*grn/D8F31C2F/0000000000000000000000000000000103ffffffd8f31c2f-0xD695DE71 Id=GrainReference:*grn/D8F31C2F/00000001 Error=

Exc level 0: System.TypeAccessException: Named type "Orleans.GrainState`1<Project.Grains.StateHolder`1<Project.Grains.SomeState>>" is invalid: Type string "Project.Grains.StateHolder`1'1" cannot be resolved.
   at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask) in D:\build\agent\_work\12\s\src\Orleans.Core\Async\TaskExtensions.cs:line 100
   at Orleans.Storage.MemoryGrainStorage.WriteStateAsync(String grainType, GrainReference grainReference, IGrainState grainState) in D:\build\agent\_work\12\s\src\OrleansProviders\Storage\MemoryStorage.cs:line 97
   at Orleans.Core.StateStorageBridge`1.WriteStateAsync() in D:\build\agent\_work\12\s\src\Orleans.Runtime\Storage\StateStorageBridge.cs:line 100
---- System.TypeAccessException : Named type "Orleans.GrainState`1<Project.Grains.StateHolder`1<Project.Grains.SomeState>>" is invalid: Type string "Project.Grains.StateHolder`1'1" cannot be resolved.
Stack Trace:
   at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask) in D:\build\agent\_work\12\s\src\Orleans.Core\Async\TaskExtensions.cs:line 100
   at Project.Tests.Can_get_grain() in ...\Tests.cs
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask) in D:\build\agent\_work\12\s\src\Orleans.Core\Async\TaskExtensions.cs:line 100
   at Orleans.Storage.MemoryGrainStorage.WriteStateAsync(String grainType, GrainReference grainReference, IGrainState grainState) in D:\build\agent\_work\12\s\src\OrleansProviders\Storage\MemoryStorage.cs:line 97
   at Orleans.Core.StateStorageBridge`1.WriteStateAsync() in D:\build\agent\_work\12\s\src\Orleans.Runtime\Storage\StateStorageBridge.cs:line 100
```

Codegen output:
```
// Microsoft.Orleans.CodeGenerator.MSBuild
feature.AddKnownType("Project.Grains.StateHolder`1,Project.Grains", "Project.Grains.StateHolder'1");

// Microsoft.Orleans.OrleansCodeGenerator.Build
feature.AddKnownType("Project.Grains.StateHolder`1,Project.Grains", "Project.Grains.StateHolder`'1");

```

At the moment we don't have time to do a repro. Hopefully this can help i some way.

**Comment by Alxandr** [comment]
I just ran into this issue. Been trying to figure out what's wrong for hours. Replacing the codegen fixed the issue.
