### ISSUE TITLE
"Failed to get a local IP address" on Linux with localhost clustering

### ISSUE THREAD

**Issue by bojidar-bg** [dotnet/orleans#5568]
**OS**: Arch Linux, updated 30.04.2019
**Linux kernel**: 5.0.10-arch1-1-ARCH
**Orleans version**: 2.2.0

**What happened**:
I am creating a cluster with UseLocalhostClustering, but I cannot connect from a client running on the same machine without having internet connection (or when on a tethered connection).
I suspect this is due to the loopback address having UNKNOWN state.

Related to #5097.

Stacktrace of the error:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Failed to get a local IP address.) ---> 
Orleans.Runtime.OrleansException: Failed to get a local IP address.
    at Orleans.Runtime.Configuration.ConfigUtilities.GetLocalIPAddress(AddressFamily family, String interfaceName)
    at Orleans.OutsideRuntimeClient.ConsumeServices(IServiceProvider services)
    at Orleans.ClientBuilder.Build()
    at … (non-orleans code)
```

`ip addr list` output (when on a tethered connection from an andorid phone):
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: wlp3s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 56:2f:10:d5:d9:f7 brd ff:ff:ff:ff:ff:ff
3: enp0s20u3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 8a:10:9e:df:40:22 brd ff:ff:ff:ff:ff:ff
    inet 192.168.42.135/24 brd 192.168.42.255 scope global dynamic noprefixroute enp0s20u3
       valid_lft 3511sec preferred_lft 3511sec
    inet6 …/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

`ip addr list` when not connected to the internet:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: wlp3s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 60:36:dd:8e:d7:f3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.43.228/24 brd 192.168.43.255 scope global dynamic noprefixroute wlp3s0
       valid_lft 2304sec preferred_lft 2304sec
    inet6 …/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

**Expected behaviour**:
I would expect Orleans to connect automagically, since this is a local (development) cluster. I shouldn't need a wifi or ethernet connection just to run something locally.

Alternatively, I would expect it to work when forcing the use of the `"lo"` network interface like this:
```csharp
new ClientBuilder()
…
.Configure<ClientMessagingOptions>(options =>
{
    options.NetworkInterfaceName = "lo";
})
…
```

Finally, it would be nice if there was an option for forcing a custom IP address and bypassing automatic IP address selection.

**Comment by mkjeff** [comment]
I have the same issue on Linux container with `macvlan`. 
`ConfigUtilities.GetLocalIPAddress` can't pick up an IP address since the network interface state is UNKNOWN.

**Comment by veikkoeeva** [comment]
@bojidar-bg and @mkjeff This subject has come up time-to-time, so I'll cross-reference https://github.com/dotnet/orleans/issues/2054. I think it makes sense to first do all the necessary work in https://github.com/dotnet/orleans/pull/5436 and elsewhere.

Maybe the larger subject is name/point things in Orleans, but it's a larger issue. :)

**Comment by benjaminpetit** [comment]
Thanks @veikkoeeva !

> Finally, it would be nice if there was an option for forcing a custom IP address and bypassing automatic IP address selection.

You can with `EndpointOptions` or with the helper `ConfigureEndpoints`:

``` csharp
builder.ConfigureEndpoints(IPAddress.Localhost, 22222, 30000, listenOnAnyHostAddress: true)
```

**Comment by bojidar-bg** [comment]
Uhm. The issue I reported is not on the silo, the silo binds itself to *:3000 just fine.
The issue is when connecting to the silo from another process running on the same machine.

On the cluster client, `OutsideRuntimeClient.ConsumeServices` [always calls](https://github.com/dotnet/orleans/blob/8971aa73ac04f53e34bc79b3ebe08a53654668b1/src/Orleans.Core/Runtime/OutsideRuntimeClient.cs#L156) `GetLocalIPAddress`, which has [no way](https://github.com/dotnet/orleans/blob/b279a53197a0de2926eb9fae312bc9e66cd117e1/src/Orleans.Core/Configuration/ConfigUtilities.cs#L439) of being configured to use a state=Unknown interface.

**Comment by mkjeff** [comment]
I have done a workaround for myself, not sure if any side effects.
https://github.com/mkjeff/orleans/commit/dd63231f7c1bba6543d451a03a2157864a01c671

**Comment by bojidar-bg** [comment]
An update from me:
Running Docker creates an additional interface with state UP, meaning that, 1) Orleans can actually be used without an internet connection by just running Docker alongside it, and 2) an Orleans client might potentially bind itself to the address given by the docker interface instead of using a wifi or ethernet interface, thus messing up the connection to a silo on the LAN.

Actually, since Docker's default interface gives an IP looking like `172.17.0.*`, it is going to [be picked](https://github.com/dotnet/orleans/blob/b279a53197a0de2926eb9fae312bc9e66cd117e1/src/Orleans.Core/Configuration/ConfigUtilities.cs#L415) instead of a common local network address looking like `192.168.*.*`.

Thinking about it, I think it would be better to use the routing table in order to decide which interface to bind the client to. Here is an example output from `ip route get`.
```bash
> ip route get 127.0.0.1
local 127.0.0.1 dev lo src 127.0.0.1 uid 1000 
    cache <local> 
> ip route get 8.8.8.8
8.8.8.8 via 192.168.1.1 dev enp4s0 src 192.168.1.… uid 1000 
    cache 
```
Seems like there are some answered [StackOverflow](https://stackoverflow.com/questions/15086863/c-sharp-know-with-which-ip-we-use-to-communicate-with-another-ip) [questions](https://stackoverflow.com/questions/15625023/ip-routing-table-lookup-in-net) related to querying the routing table, so it should be doable.

**Comment by zjsjmvn** [comment]
I have the same issue too = =!

**Comment by benc-uk** [comment]
Any update on this? I see the PR was closed, any way to configure the IP address of the client like we can the silo ?
I can certainly see some complexity & issues when running in containers and/or Kubernetes with the current approach

**Comment by benjaminpetit** [comment]
@benc-uk at the moment, no.

The previous PR was not merged because some of this logic should be implemented outside Orleans IMO. The solution pointed by @mkjeff seems better. It's more flexible that way

**Comment by mkjeff** [comment]
My PR is [here](#5838).
This approach had used in our docker environment for a while. I am really hoping that the issue can be solved via the official release. very appreciated.
