### ISSUE TITLE
 The given key 'ReminderService' was not present in the dictionary

### ISSUE THREAD

**Issue by qgxcry** [dotnet/orleans#5593]
1. Create  a  ReminderGrain 
public class ReminderGrain : GrainBase, IReminderGrain
    {
        public async Task<IGrainReminder> StartReminderAsync(string reminderName, TimeSpan dueTime, TimeSpan period)
        {
            return await RegisterOrUpdateReminder(reminderName, dueTime, period);
        }

        public Task ReceiveReminder(string reminderName, TickStatus status)
        {
            Console.WriteLine($"我是定时器{reminderName}，自动执行,首次执行时间：{status.FirstTickTime.ToString()}；当前执行时间{status.CurrentTickTime.ToString()}");
            return Task.CompletedTask;
        }
    }
2. Create a database by executing the MySQL-Reminders.sql file.
3. In Program UseAdoNetReminderService
 var builder = new SiloHostBuilder()
                // Membership
                .UseAdoNetClustering(options =>
                {
                    options.Invariant = configurationRoot["OrleansSetting:AdoNetClustering:Invariant"];
                    options.ConnectionString = configurationRoot["OrleansSetting:AdoNetClustering:ConnectionString"];
                })
                .UseAdoNetReminderService(options =>
                {
                    options.Invariant = configurationRoot["OrleansSetting:AdoNetReminderService:Invariant"];
                    options.ConnectionString = configurationRoot["OrleansSetting:AdoNetReminderService:ConnectionString"];
                })

3. Start SiloHost Throw Exception：
Exception during Silo.Start
Orleans.Runtime.OrleansLifecycleCanceledException: Lifecycle start canceled due to errors at stage 20000 ---> System.Collections.Generic.KeyNotFoundException: The given key 'ReminderService' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Orleans.Reminders.AdoNet.Storage.RelationalStorage..ctor(String invariantName, String connectionString) in D:\build\agent\_work\12\s\src\AdoNet\Shared\Storage\RelationalStorage.cs:line 208
   at Orleans.Reminders.AdoNet.Storage.RelationalStorage.CreateInstance(String invariantName, String connectionString) in D:\build\agent\_work\12\s\src\AdoNet\Shared\Storage\RelationalStorage.cs:line 98
   at Orleans.Reminders.AdoNet.Storage.RelationalOrleansQueries.CreateInstance(String invariantName, String connectionString, IGrainReferenceConverter grainReferenceConverter) in D:\build\agent\_work\12\s\src\AdoNet\Shared\Storage\RelationalOrleansQueries.cs:line 0
   at Orleans.Runtime.ReminderService.AdoNetReminderTable.Init() in D:\build\agent\_work\12\s\src\AdoNet\Orleans.Reminders.AdoNet\ReminderService\AdoNetReminderTable.cs:line 27
   at Orleans.OrleansTaskExtentions.WithTimeout(Task taskToComplete, TimeSpan timeout, String exceptionMessage) in D:\build\agent\_work\12\s\src\Orleans.Core\Async\TaskExtensions.cs:line 206
   at Orleans.Runtime.ReminderService.LocalReminderService.Start() in D:\build\agent\_work\12\s\src\Orleans.Runtime\ReminderService\LocalReminderService.cs:line 57
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute() in D:\build\agent\_work\12\s\src\Orleans.Runtime\Scheduler\ClosureWorkItem.cs:line 63
   at Orleans.OrleansTaskExtentions.WithTimeout(Task taskToComplete, TimeSpan timeout, String exceptionMessage) in D:\build\agent\_work\12\s\src\Orleans.Core\Async\TaskExtensions.cs:line 218
   at Orleans.Runtime.Silo.<OnActiveStart>g__StartReminderService|74_0() in D:\build\agent\_work\12\s\src\Orleans.Runtime\Silo\Silo.cs:line 541
   at Orleans.Runtime.Silo.StartAsyncTaskWithPerfAnalysis(String taskName, Func`1 task, Stopwatch stopWatch) in D:\build\agent\_work\12\s\src\Orleans.Runtime\Silo\Silo.cs:line 391
   at Orleans.Runtime.Silo.OnActiveStart(CancellationToken ct) in D:\build\agent\_work\12\s\src\Orleans.Runtime\Silo\Silo.cs:line 544
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in D:\build\agent\_work\12\s\src\Orleans.Runtime\Lifecycle\SiloLifecycleSubject.cs:line 75
   at Orleans.LifecycleSubject.WrapExecution(CancellationToken ct, Func`2 action) in D:\build\agent\_work\12\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 115
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct) in D:\build\agent\_work\12\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 55
   --- End of inner exception stack trace ---
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct) in D:\build\agent\_work\12\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 63
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute() in D:\build\agent\_work\12\s\src\Orleans.Runtime\Scheduler\ClosureWorkItem.cs:line 63
   at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken) in D:\build\agent\_work\12\s\src\Orleans.Runtime\Silo\Silo.cs:line 265
Orleans.Runtime.OrleansLifecycleCanceledException: Lifecycle start canceled due to errors at stage 20000 ---> System.Collections.Generic.KeyNotFoundException: The given key 'ReminderService' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Orleans.Reminders.AdoNet.Storage.RelationalStorage..ctor(String invariantName, String connectionString) in D:\build\agent\_work\12\s\src\AdoNet\Shared\Storage\RelationalStorage.cs:line 208
   at Orleans.Reminders.AdoNet.Storage.RelationalStorage.CreateInstance(String invariantName, String connectionString) in D:\build\agent\_work\12\s\src\AdoNet\Shared\Storage\RelationalStorage.cs:line 98
   at Orleans.Reminders.AdoNet.Storage.RelationalOrleansQueries.CreateInstance(String invariantName, String connectionString, IGrainReferenceConverter grainReferenceConverter) in D:\build\agent\_work\12\s\src\AdoNet\Shared\Storage\RelationalOrleansQueries.cs:line 0
   at Orleans.Runtime.ReminderService.AdoNetReminderTable.Init() in D:\build\agent\_work\12\s\src\AdoNet\Orleans.Reminders.AdoNet\ReminderService\AdoNetReminderTable.cs:line 27
   at Orleans.OrleansTaskExtentions.WithTimeout(Task taskToComplete, TimeSpan timeout, String exceptionMessage) in D:\build\agent\_work\12\s\src\Orleans.Core\Async\TaskExtensions.cs:line 206
   at Orleans.Runtime.ReminderService.LocalReminderService.Start() in D:\build\agent\_work\12\s\src\Orleans.Runtime\ReminderService\LocalReminderService.cs:line 57
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute() in D:\build\agent\_work\12\s\src\Orleans.Runtime\Scheduler\ClosureWorkItem.cs:line 63
   at Orleans.OrleansTaskExtentions.WithTimeout(Task taskToComplete, TimeSpan timeout, String exceptionMessage) in D:\build\agent\_work\12\s\src\Orleans.Core\Async\TaskExtensions.cs:line 218
   at Orleans.Runtime.Silo.<OnActiveStart>g__StartReminderService|74_0() in D:\build\agent\_work\12\s\src\Orleans.Runtime\Silo\Silo.cs:line 541
   at Orleans.Runtime.Silo.StartAsyncTaskWithPerfAnalysis(String taskName, Func`1 task, Stopwatch stopWatch) in D:\build\agent\_work\12\s\src\Orleans.Runtime\Silo\Silo.cs:line 391
   at Orleans.Runtime.Silo.OnActiveStart(CancellationToken ct) in D:\build\agent\_work\12\s\src\Orleans.Runtime\Silo\Silo.cs:line 544
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in D:\build\agent\_work\12\s\src\Orleans.Runtime\Lifecycle\SiloLifecycleSubject.cs:line 75
   at Orleans.LifecycleSubject.WrapExecution(CancellationToken ct, Func`2 action) in D:\build\agent\_work\12\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 115
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct) in D:\build\agent\_work\12\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 55
   --- End of inner exception stack trace ---
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct) in D:\build\agent\_work\12\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 63
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute() in D:\build\agent\_work\12\s\src\Orleans.Runtime\Scheduler\ClosureWorkItem.cs:line 63
   at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken) in D:\build\agent\_work\12\s\src\Orleans.Runtime\Silo\Silo.cs:line 265

**Comment by sergeybykov** [comment]
Do you see `OrleansRemindersTable` created in the database?

Also, did you create the clustering table as well?

**Comment by sergeybykov** [comment]
What's the value of `OrleansSetting:AdoNetClustering:Invariant`?

**Comment by qgxcry** [comment]
> What's the value of `OrleansSetting:AdoNetClustering:Invariant`?

![image](https://user-images.githubusercontent.com/13807716/57594754-33f71e00-7574-11e9-9f8b-3a46dc6962dc.png)

**Comment by qgxcry** [comment]
> Do you see `OrleansRemindersTable` created in the database?
> 
> Also, did you create the clustering table as well?



> Do you see `OrleansRemindersTable` created in the database?
> 
> Also, did you create the clustering table as well?
yes，I have created a table for Orleans, Reminders
![image](https://user-images.githubusercontent.com/13807716/57594787-60129f00-7574-11e9-9753-ce5514a2ea93.png)

**Comment by sergeybykov** [comment]
>Invariant: ReminderService

This is incorrect. Should be `Invariant: MySql.Data.MySqlClient` instead I believe.

**Comment by qgxcry** [comment]
@sergeybykov thank you！
