### ISSUE TITLE
GrainMethodInvoker.GetMethodEntry can throw InvalidOperationException

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#5627]
The dashboard uses a grain call filter which tries to grab the name of the method being invoked. It does this by calling `IIncomingGrainCallContext.ImplementationMethod` which concretely calls `GrainMethodInvoker.GetMethodEntry`. For certain grain calls that we have, this results in an `InvalidOperationException`.

I'm pretty sure this is the result of the particular grain structure we have...
The method being invoked is `IMessageHandler.HandleMessage(IMessage message ...)`
Hierarchy:
```csharp
interface IMessageHandler : IGrainWithIntegerKey
{
    HandleMessage(IMessage message ...)
}

interface IMessageHandler<in T> : IMessageHandler where T : IMessage
{
    HandleMessage(T message ...)
}

abstract class BaseMessageHandler<T> : Grain, IMessageHandler<T> where T : IMessage
{
    HandleMessage(IMessage message ...)
    {
        if (message is T typedMessage) return HandleMessage(typedMessage ...);
    }

    abstract HandleMessage(T message ...)
}

class AThingHandler : BaseMessageHandler<AThing>
{
    override HandleMessage(AThing message ...){...}
}

```

Partial trace
```csharp
System.InvalidOperationException: Type Server.Grains.Handlers.AThingHandler does not implement interface with id -1767514446 (96A5DEB2).
   at Orleans.InterfaceToImplementationMappingCache.GetOrCreate(Type implementationType, Int32 interfaceId) in D:\build\agent\_work\12\s\src\Orleans.Core\Core\InterfaceToImplementationMappingCache.cs:line 56
   at Orleans.Runtime.GrainMethodInvoker.GetMethodEntry() in D:\build\agent\_work\12\s\src\Orleans.Runtime\Core\GrainMethodInvoker.cs:line 124
   at Orleans.Runtime.GrainMethodInvoker.get_ImplementationMethod() in D:\build\agent\_work\12\s\src\Orleans.Runtime\Core\GrainMethodInvoker.cs:line 52
```

And from type mapping
```
Server.Grains.Handlers.BaseMessageHandler<T> [-1425476372 (0xAB08F4EC)] from ServerGrains.dll implementing interfaces: Server.Grains.IMessageHandler<T> [-1767514446 (0x96A5DEB2)], Server.Grains.IMessageHandler [896328416 (0x356CE2E0)]

Grain class Server.Grains.Handlers.Server.Grains.Handlers.AThingHandler [175942383 (0xA7CAAEF)] from ServerGrains.dll implementing interfaces: Server.Grains.IMessageHandler<AThing> [
354762693 (0x15253FC5)], Server.Grains.IMessageHandler [896328416 (0x356CE2E0)]
```

**Comment by ReubenBond** [comment]
I believe this is fixed by #6004
