### ISSUE TITLE
Catalog and Directory Grains failing to communicate - Select Activation Timeouts

### ISSUE THREAD

**Issue by peter-maude** [dotnet/orleans#5631]
Hi,

We are having issues in our cluster with select activation timeouts between the catalog and directory grains - Issue below.

`System.TimeoutException: Response did not arrive on time in 00:01:00 for message: Request S10.210.0.191:11111:296756057*stg/14/0000000e@S0000000e->S10.210.1.70:11111:296756073*stg/10/0000000a@S0000000a #14780: . Target History is: <S10.210.1.70:11111:296756073:*stg/10/0000000a:@S0000000a>.
   at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.LookupAsync(GrainId grainId, Int32 hopCount)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem`1.Execute()
   at Orleans.Runtime.Placement.RandomPlacementDirector.OnSelectActivation(PlacementStrategy strategy, GrainId target, IPlacementRuntime context)
   at Orleans.Runtime.Placement.PlacementDirectorsManager.SelectOrAddActivation(ActivationAddress sendingAddress, PlacementTarget targetGrain, IPlacementRuntime context, PlacementStrategy strategy)
   at Orleans.Runtime.Dispatcher.AddressMessageAsync(Message message, PlacementTarget target, PlacementStrategy strategy, ActivationAddress targetAddress)
   at Orleans.Runtime.Dispatcher.<>c__DisplayClass37_0.<<AsyncSendMessage>b__1>d.MoveNext()`

Once this error starts, it never recovers, and that source silo seems to stop doing much useful work.  We have struggled to nail down when it happens.

Is it possible to move those system grains, away from silos that run our grains, so we can rule out our interaction with the silo, which I am sure it is what we are doing on there

Can you effectively segment the cluster, to allow system grains on one half, and custom grains on the other ?

Thanks

**Comment by sergeybykov** [comment]
When you see these errors, is silo 10.210.1.70:11111 actually up?

**Comment by robindjohnson** [comment]
Yes, boxes are definitely up and the process is running when the error occurs. We have implemented our own stream provider and queue cache which pulls from multiple gcp pubsub queues and forwards on to the grains.  Could we be "clogging" up the orleans schedulers somehow?

**Comment by sergeybykov** [comment]
>Is it possible to move those system grains, away from silos that run our grains, so we can rule out our interaction with the silo, which I am sure it is what we are doing on there

These are core silo runtime components, and cannot be moved anywhere. Catalog (stg/14) of 10.210.0.191:11111 is calling Directory partition (stg/10) on 10.210.1.70:11111, and that call is timing out in a minute. Something really terrible must happen to 10.210.1.70:11111 for this to be possible because system targets (stg/*) have a dedicated thread to execute that grains don't get scheduled on. So, even if you flood the system with tons of stream events, Catalog and Directory should continue to respond.

Can you share full logs? What version is this? If you could take a memory dump of 10.210.1.70:11111 in this state, that would very likely help shed some light on what's going on there.

**Comment by robindjohnson** [comment]
Thank you for your helpful response. I am also working on the same project as the original poster.

We have have implemented our own stream providers which are used by the persistent pulling agent.  As the persistent pulling agents are system targets, would they be running on the same dedicated threads and therefore possibly causing the threads to be "clogged" by something we are doing in our stream provider?

**Comment by peter-maude** [comment]
Hi Sergey,

Thanks for getting back, I have been away from office.  We are going to start stripping away our code, to see if we can isolate, it may be better for use to get some more informed observations around that

I had wanted to check that there was no obvious things first

What I can tell you, is that these issues happen between pairs of servers.

In my current example
10 Servers
10 Pulling Agents
Server A, and Server B are having the select activation errors between them like above.

But both A and B are handling grain traffic from other servers without issue. Having a high number of pulling agents, does somewhat mitigate this issue, as there are more agents around that do not have the issue.  Over time more pairs of server can get into this persistent state, and eventually performance of the cluster suffers badly.

We will come back when we have some better information around stripping away components.

Thanks

**Comment by sergeybykov** [comment]
>As the persistent pulling agents are system targets, would they be running on the same dedicated threads and therefore possibly causing the threads to be "clogged" by something we are doing in our stream provider?

Pulling agents are low priority system targets, and they execute on grain threads, specifically so that they wouldn't clog the high priority (silo runtime) system targets. So, this shouldn't be the reason.

>But both A and B are handling grain traffic from other servers without issue. Having a high number of pulling agents, does somewhat mitigate this issue, as there are more agents around that do not have the issue. Over time more pairs of server can get into this persistent state, and eventually performance of the cluster suffers badly.

This sounds very strange. Logs would help up see the whole picture, if you can share them. What version is this? What is the queuing system that the stream provider is for?

**Comment by sergeybykov** [comment]
Closing due to inactivity. Will reopen if there's new information.
