### ISSUE TITLE
BatchSendBatchConsume test failing intermittently

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#5632]
>Error message
Assert.Equal() Failure\r\nExpected: 30\r\nActual: 20
Stack trace
at UnitTests.StreamingTests.StreamBatchingTestRunner.<CheckCounters>d__7.MoveNext() in D:\build\agent\_work\23\s\test\Tester\StreamingTests\StreamBatchingTestRunner.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.TestingHost.Utils.TestingUtils.<>c__DisplayClass4_0.<<WaitUntilAsync>b__0>d.MoveNext() in D:\build\agent\_work\23\s\src\Orleans.TestingHost\Utils\TestingUtils.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.TestingHost.Utils.TestingUtils.<WaitUntilAsync>d__4.MoveNext() in D:\build\agent\_work\23\s\src\Orleans.TestingHost\Utils\TestingUtils.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.StreamingTests.StreamBatchingTestRunner.<BatchSendBatchConsume>d__6.MoveNext() in D:\build\agent\_work\23\s\test\Tester\StreamingTests\StreamBatchingTestRunner.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by ReubenBond** [comment]
Closing all test reliability issues. Test reliability has improved substantially. We can re-open for any test reliability issues which we still see.
