### ISSUE TITLE
EHStreamConsumerOnDroppedClientTest failing intermittently

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#5634]
>Error message
Assert.Equal() Failure\r\nExpected: 1\r\nActual: 0
Stack trace
at Tester.StreamingTests.ClientStreamTestRunner.<CheckCounters>d__9.MoveNext() in D:\build\agent\_work\23\s\test\Tester\StreamingTests\ClientStreamTestRunner.cs:line 150
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.TestingHost.Utils.TestingUtils.<>c__DisplayClass4_0.<<WaitUntilAsync>b__0>d.MoveNext() in D:\build\agent\_work\23\s\src\Orleans.TestingHost\Utils\TestingUtils.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.TestingHost.Utils.TestingUtils.<WaitUntilAsync>d__4.MoveNext() in D:\build\agent\_work\23\s\src\Orleans.TestingHost\Utils\TestingUtils.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Tester.StreamingTests.ClientStreamTestRunner.<StreamConsumerOnDroppedClientTest>d__5.MoveNext() in D:\build\agent\_work\23\s\test\Tester\StreamingTests\ClientStreamTestRunner.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at ServiceBus.Tests.StreamingTests.EHClientStreamTests.<EHStreamConsumerOnDroppedClientTest>d__11.MoveNext() in D:\build\agent\_work\23\s\test\Extensions\ServiceBus.Tests\Streaming\EHClientStreamTests.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by ReubenBond** [comment]
Closing all test reliability issues. Test reliability has improved substantially. We can re-open for any test reliability issues which we still see.
