### ISSUE TITLE
Code generator fails on empty projects

### ISSUE THREAD

**Issue by Alxandr** [dotnet/orleans#5678]
```
-- Code Generation FAILED --

Exc level 0: System.InvalidOperationException: Compilation has no syntax trees.
   at Orleans.CodeGenerator.CodeGenerator..ctor(Compilation compilation, ILogger log) in D:\build\agent\_work\7\s\src\Orleans.CodeGenerator\CodeGenerator.cs:line 37
   at Orleans.CodeGenerator.MSBuild.CodeGeneratorCommand.Execute(CancellationToken cancellationToken) in D:\build\agent\_work\7\s\src\Orleans.CodeGenerator.MSBuild\CodeGeneratorCommand.cs:line 129
   at Microsoft.Orleans.CodeGenerator.MSBuild.Program.SourceToSource(String[] args) in D:\build\agent\_work\7\s\src\Orleans.CodeGenerator.MSBuild\Program.cs:line 126
   at Microsoft.Orleans.CodeGenerator.MSBuild.Program.Main(String[] args) in D:\build\agent\_work\7\s\src\Orleans.CodeGenerator.MSBuild\Program.cs:line 16
```

This should probably be handled, as you don't want the compilation of solutions to fail if you just added a new project that you've yet to add anything to.

**Comment by ReubenBond** [comment]
That's a fair point. Are you able to submit a PR?

**Comment by Alxandr** [comment]
Not sure. Not in the next few days at least. I'll put it on my list and can hopefully get to it next weekend.

**Comment by ReubenBond** [comment]
Opened #5689 with a fix
