### ISSUE TITLE
Nulleble enum not serialized/deserialized (default serializer)

### ISSUE THREAD

**Issue by grendizeras** [dotnet/orleans#5829]
When contract, which is returned from other silo has any nullable enum property, deserialization fails in calling silo grain.

We have property 
`public BetSlipEditTypes? BetSlipEditTypeId { get; set; } `

```
Exception stack trace:
 Orleans.Runtime.Messaging.IncomingMessageAcceptor[101017]
      Exception trying to process 4519 bytes from endpoint ****
System.TypeAccessException: Named type "BL.Domain.Enum.BetSlipEditTypes" is invalid: Type string "BL.Domain.Enum.BetSlipEditTypes" cannot be resolved.
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadSpecifiedTypeHeader[TReader](TReader this, SerializationManager serializationManager) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\BinaryTokenStreamReader.cs:line 423
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1270
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1218
   at Orleans.Serialization.DeserializationContext.DeserializeInner(Type expected) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\DeserializationContext.cs:line 77
   at OrleansGeneratedCode73FC44B9.OrleansCodeGenBL_Domain_Billing_BetSlipContractMinSerializer.Deserializer(Type expected, IDeserializationContext context) in C:\TFS_New\BL.Sport\src\Grains\BL.Billing.Grains.BLL\obj\Debug\BL.Billing.Grains.BLL.orleans.g.cs:line 1521
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1318
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1218
   at Orleans.Serialization.BuiltInTypes.DeserializeKeyValuePair[K,V](Type expected, IDeserializationContext context) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\BuiltInTypes.cs:line 1725
   at Orleans.Serialization.BuiltInTypes.DeserializeGenericKeyValuePair(Type expected, IDeserializationContext context) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\BuiltInTypes.cs:line 1706
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1318
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1218
   at Orleans.Serialization.BuiltInTypes.DeserializeList[T](Type expected, IDeserializationContext context) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\BuiltInTypes.cs:line 134
   at Orleans.Serialization.BuiltInTypes.DeserializeGenericList(Type expected, IDeserializationContext context) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\BuiltInTypes.cs:line 104
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1318
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1218
   at Orleans.Serialization.DeserializationContext.DeserializeInner(Type expected) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\DeserializationContext.cs:line 77
   at OrleansGeneratedCode73FC44B9.OrleansCodeGenBL_Domain_Billing_PlaceBetSlipsResultContractSerializer.Deserializer(Type expected, IDeserializationContext context) in C:\TFS_New\BL.Sport\src\Grains\BL.Billing.Grains.BLL\obj\Debug\BL.Billing.Grains.BLL.orleans.g.cs:line 1299
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1318
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1218
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\BuiltInTypes.cs:line 2128
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1318
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1218
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, IBinaryTokenStreamReader stream) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1188
   at Orleans.Serialization.SerializationManager.Deserialize(IBinaryTokenStreamReader stream) in D:\build\agent\_work\25\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1155
   at Orleans.Runtime.Message.DeserializeBody(SerializationManager serializationManager, List`1 bytes) in D:\build\agent\_work\25\s\src\Orleans.Core\Messaging\Message.cs:line 434
   at Orleans.Runtime.Message.DeserializeBodyObject(SerializationManager serializationManager, List`1 body) in D:\build\agent\_work\25\s\src\Orleans.Core\Messaging\Message.cs:line 462
   at Orleans.Runtime.IncomingMessageBuffer.TryDecodeMessage(Message& msg) in D:\build\agent\_work\25\s\src\Orleans.Core\Messaging\IncomingMessageBuffer.cs:line 192
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor.ReceiveCallbackContext.ProcessReceived(SocketAsyncEventArgs e) in D:\build\agent\_work\25\s\src\Orleans.Runtime\Messaging\IncomingMessageAcceptor.cs:line 677
fail: Orleans.Runtime.Messaging.IncomingMessageAcceptor[101027]
```

What I found out, in **BinaryTokenStreamReaderExtensinons** class, method **ReadSpecifiedTypeHeader** does not have specified cast for nullable enum.

Orleans version 2.3.6.

**Comment by ReubenBond** [comment]
Hi @grendizeras, does the assembly containing `BL.Domain.Enum.BetSlipEditTypes` contain code generation? Which code generator package + version are you using?

The issue is likely not directly related to `Nullable<T>`, it seems instead that the silo is not aware of this enum type itself. One way to ensure that it is is to have the an assembly level attribute to force it to be aware, eg: `[assembly: KnownType(typeof(BetSlipEditTypes))]`. That attribute would usually go in your grain interfaces assembly.

When you configure your silo, do you use `builder.ConfigureApplicationParts(...)` at all? If yes, it may be that not all assemblies are being added. If no, this is likely not the problem.

**Comment by grendizeras** [comment]
> Hi @grendizeras, does the assembly containing `BL.Domain.Enum.BetSlipEditTypes` contain code generation? Which code generator package + version are you using?
> 
> The issue is likely not directly related to `Nullable<T>`, it seems instead that the silo is not aware of this enum type itself. One way to ensure that it is is to have the an assembly level attribute to force it to be aware, eg: `[assembly: KnownType(typeof(BetSlipEditTypes))]`. That attribute would usually go in your grain interfaces assembly.
> 
> When you configure your silo, do you use `builder.ConfigureApplicationParts(...)` at all? If yes, it may be that not all assemblies are being added. If no, this is likely not the problem.

Our code generator package : Microsoft.Orleans.OrleansCodeGenerator.Build 2.3.6 
We use builder.ConfigureApplicationParts(...);  assembly, containing mentioned type is included in list. 
Silo is aware of type, when we make enum property not nullable, also there is no problem, when nullable type property value is null. This exception only occurs when nullable type value  is set with enum value.

**Comment by ReubenBond** [comment]
@grendizeras does the assembly containing that type also have the code generator package installed on it?

**Comment by grendizeras** [comment]
> @grendizeras does the assembly containing that type also have the code generator package installed on it?

@ReubenBond Sure! It is installed. The problem involves only enum nullable types, other nullable types works fine. Temporary fix was to change nullable enum types to nullable int types, but it is just temporary solution. Big problem also is, exception is not bubbled up, so we struggled to identify the problem with serialization. **IncomingMessageAcceptor.ProcessReceive(SocketAsyncEventArgs e)** has try catch, that isn't rethrowing, and closes connection. After that grain freezes.

**Comment by ReubenBond** [comment]
The request should currently timeout when this happens.

Did you try the `KnownType` attribute in your grain interfaces assembly?

**Comment by grendizeras** [comment]
Not yet. Will try.

**Comment by grendizeras** [comment]
Will investigate farther and let you know, `KnownType` Attribute didn't work.

**Comment by ReubenBond** [comment]
Hi @grendizeras did you manage to fix this or find out more information?

**Comment by ReubenBond** [comment]
Closing due to inactivity - please comment here or open another issue if this is still  a problem
