### ISSUE TITLE
Could not find silo entry for silo ... in the table

### ISSUE THREAD

**Issue by dingsongjie** [dotnet/orleans#5868]
Orleans version: 2.2
Errors
```log

fail: Orleans.Runtime.MembershipService.MembershipOracleData[100623]


      -Could not find silo entry for silo S10.0.2.125:11111:300894698 in the table.


fail: Orleans.Runtime.MembershipService.MembershipOracleData[100623]


      -Could not find silo entry for silo S10.0.2.125:11111:300894698 in the table.


fail: Orleans.Runtime.MembershipService.MembershipOracleData[100651]


      TryToSuspectOrKill failed


System.AggregateException: One or more errors occurred. (-Could not find silo entry for silo S10.0.2.125:11111:300894698 in the table.) ---> System.Collections.Generic.KeyNotFoundException: -Could not find silo entry for silo S10.0.2.125:11111:300894698 in the table.


   at Orleans.Runtime.MembershipService.MembershipOracle.TryToSuspectOrKill(SiloAddress silo)


   at Orleans.AsyncExecutorWithRetries.ExecuteWithRetriesHelper[T](Func`2 function, Int32 callCounter, Int32 maxNumSuccessTries, Int32 maxNumErrorTries, TimeSpan maxExecutionTime, DateTime startExecutionTime, Func`3 retryValueFilter, Func`3 retryExceptionFilter, IBackoffProvider onSuccessBackOff, IBackoffProvider onErrorBackOff)


   at Orleans.AsyncExecutorWithRetries.ExecuteWithRetriesHelper[T](Func`2 function, Int32 callCounter, Int32 maxNumSuccessTries, Int32 maxNumErrorTries, TimeSpan maxExecutionTime, DateTime startExecutionTime, Func`3 retryValueFilter, Func`3 retryExceptionFilter, IBackoffProvider onSuccessBackOff, IBackoffProvider onErrorBackOff)


   --- End of inner exception stack trace ---


---> (Inner Exception #0) System.Collections.Generic.KeyNotFoundException: -Could not find silo entry for silo S10.0.2.125:11111:300894698 in the table.


   at Orleans.Runtime.MembershipService.MembershipOracle.TryToSuspectOrKill(SiloAddress silo)


   at Orleans.AsyncExecutorWithRetries.ExecuteWithRetriesHelper[T](Func`2 function, Int32 callCounter, Int32 maxNumSuccessTries, Int32 maxNumErrorTries, TimeSpan maxExecutionTime, DateTime startExecutionTime, Func`3 retryValueFilter, Func`3 retryExceptionFilter, IBackoffProvider onSuccessBackOff, IBackoffProvider onErrorBackOff)


   at Orleans.AsyncExecutorWithRetries.ExecuteWithRetriesHelper[T](Func`2 function, Int32 callCounter, Int32 maxNumSuccessTries, Int32 maxNumErrorTries, TimeSpan maxExecutionTime, DateTime startExecutionTime, Func`3 retryValueFilter, Func`3 retryExceptionFilter, IBackoffProvider onSuccessBackOff, IBackoffProvider onErrorBackOff)<---




fail: Orleans.Runtime.MembershipService.MembershipOracleData[100623]


      -Could not find silo entry for silo S10.0.2.125:11111:300894698 in the table.


fail: Orleans.Runtime.MembershipService.MembershipOracleData[100623]


      -Could not find silo entry for silo S10.0.2.125:11111:300894698 in the table.


fail: Orleans.Runtime.MembershipService.MembershipOracleData[100623]


      -Could not find silo entry for silo S10.0.2.125:11111:300894698 in the table.
```
Some code in source
```cs
            if (!table.Contains(silo))
            {
                // this should not happen ...
                var str = String.Format("-Could not find silo entry for silo {0} in the table.", silo.ToLongString());
                logger.Error(ErrorCode.MembershipFailedToReadSilo, str);
                throw new KeyNotFoundException(str);
            }
```
It seems the silo hoped to delete is already deleted in my membershipTableProvider.
Why soli don't update it's probedSilos？
I checked the source code , the  already deleted (in membershipTableProvider) probedSilo will be dead only after delete in membershipTableProvider ,But I am not sure,I will check the higher version

**Comment by dingsongjie** [comment]
In version 2.4.1  
I  checked the source code ，MembershipTableSnapshot is always from membershipTableProvider,and MonitoredSilos is updated from MembershipTableSnapshot  by task. It can fix my problem . Am I right?

**Comment by sergeybykov** [comment]
Silo entries don't get deleted from the table (other than for automatic cleanup of old entries). What clustering provider are you using here?

**Comment by dingsongjie** [comment]
I use  [redis ](https://github.com/arleyschrock/Orleans.Clustering.Redis) clustering provider

**Comment by dingsongjie** [comment]
> Silo entries don't get deleted from the table (other than for automatic cleanup of old entries). What clustering provider are you using here?

I use [redis ](https://github.com/arleyschrock/Orleans.Clustering.Redis) clustering provider

**Comment by dingsongjie** [comment]
I know the reason, because the dead soli entity in redis was deleted by redis cluster provider when ReadAll.

**Comment by sergeybykov** [comment]
Entries for dead silos are supposed to stay in the table, so that other silos (and in some cases the silo that was declared dead) can learn about that. Does the Redis provider actually *delete* the entry in the table?

For a comparison, I'd suggest to try the Azure Table provider. It can be used with the Azure Storage emulator. That provider does behave correctly.
