### ISSUE TITLE
Handling very specific exceptions on the client

### ISSUE THREAD

**Issue by vyshkant** [dotnet/orleans#5871]
Hello to all! Thanks for the great job! I have the following question:

What is the best way to handle this situation: one of the grains throws a very specific exception (for example, related to the database driver). Further, this exception "flies" and reaches the client, where it cannot be deserialized (because the client does not know anything about working with the database, all of these libraries are not loaded in the client).

What is the best way to solve such problems?

Here is an example of this kind of deserialization error:

```
Could not load file or assembly 'MongoDB.Driver, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

 at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
 at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
 at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
 at Orleans.Runtime.CachedTypeResolver.<>c__DisplayClass7_0.<TryPerformUncachedTypeResolution>g__ResolveAssembly|0(AssemblyName assemblyName)
 at System.TypeNameParser.ResolveAssembly(String asmName, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
 at System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
 at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
 at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
 at Orleans.Runtime.CachedTypeResolver.TryPerformUncachedTypeResolution(String fullName, Type& type, Assembly[] assemblies)
 at Orleans.Runtime.CachedTypeResolver.TryPerformUncachedTypeResolution(String name, Type& type)
 at Orleans.Runtime.CachedTypeResolver.TryResolveType(String name, Type& type)
 at Orleans.Serialization.TypeSerializer.GetTypeFromName(String assemblyQualifiedTypeName, Boolean throwOnError)
 at Orleans.Serialization.TypeSerializer.GetTypeFromTypeKey(TypeKey key, Boolean throwOnError)
 at Orleans.Serialization.ILBasedExceptionSerializer.Deserialize(Type expectedType, IDeserializationContext outerContext)
 at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
 at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
 at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context)
 at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
 at Orleans.Serialization.SerializationManager.Deserialize(Type t, IBinaryTokenStreamReader stream)
 at Orleans.Runtime.Message.GetDeserializedBody(SerializationManager serializationManager)
 at Orleans.Runtime.SharedCallbackData.ResponseCallback(Message message, TaskCompletionSource`1 context) --- End of stack trace from previous location where exception was thrown ---
 at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
 at Path.To.The.Place.Where.Cluster.Client.Is.Calling.The.Grain.Method() in /path/to/my/File.cs:line 42
```

**Comment by ReubenBond** [comment]
Hi @vyshkant, in cases like this I would recommend converting the exception into something which the client is able to deserialize. If the exception is one which you have created then you can convert the MongoDB types into a deserializable representation (eg, a string with the stack trace) & avoid storing it as the `InnerException` (for example).

Does that help?

**Comment by vyshkant** [comment]
@ReubenBond thank a lot! But there is a problem with this solution: I have `n` grains with `m` methods, should I wrap alle these methods with try/catch to convert all possible exceptions? This sounds bad.

Is there some place on the silo, where I can "proxy" requests from the client (and convert all "non-mine" exceptions to "mine ones")?

**Comment by ReubenBond** [comment]
Grain call filters should be able to help you out, @vyshkant: http://dotnet.github.io/orleans/Documentation/grains/interceptors.html

**Comment by bddckr** [comment]
I believe this exact issue is documented on that page in particular!
https://dotnet.github.io/orleans/Documentation/grains/interceptors.html?q=exception#exception-conversion

**Comment by vyshkant** [comment]
@bddckr @ReubenBond Thank you very much, this is exactly what I need!

But could you plese help me again: is there everything OK the syntax in that examples? What is a "RequestContext"?

**Comment by bddckr** [comment]
It's a `static` class holding some info for the current request:
https://dotnet.github.io/orleans/Documentation/grains/request_context.html

https://github.com/dotnet/orleans/blob/e56ad4d4798f3f758037a06e75972b65535eccbc/src/Orleans.Core.Abstractions/Runtime/RequestContext.cs#L7-L22

**Comment by vyshkant** [comment]
Thanks a lot!
