### ISSUE TITLE
EventHubs NullReferenceException

### ISSUE THREAD

**Issue by JorgeCandeias** [dotnet/orleans#5900]
This is my setup code:

```csharp
builder.AddEventHubStreams(
    StreamProviderNames.ResultIngress,
    options =>
    {
        options.ConnectionString = context.Configuration.GetConnectionString("Orleans:Streams:EventHub:Ingress:Results");
        options.Path = context.Configuration.GetValue("Orleans:Streams:EventHub:Ingress:Results:Path", "orleans-local");
        options.ConsumerGroup = context.Configuration.GetValue("Orleans:Streams:EventHub:Ingress:Results:ConsumerGroup", "$Default");
    },
    options =>
    {
        options.ConnectionString = context.Configuration.GetConnectionString("Orleans:Streams:EventHub:Checkpointer:Ingress:Results");
        options.TableName = context.Configuration.GetValue("Orleans:Streams:EventHub:Checkpointer:TableName", "eventhub-checkpoints");
        options.PersistInterval = TimeSpan.FromSeconds(10);
    });
```

This is what I get - a lot of these, in fact.

```
fail: Orleans.Streams.*stg/5407470843411388598/02d158b6.result-ingress-stream-provider[103312]
      Giving up reading from queue result-ingress-stream-provider-0 after retry attempts 6
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.GetMaxAddCount() in D:\build\agent\_work\12\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubAdapterReceiver.cs:line 66
   at Orleans.Streams.PersistentStreamPullingAgent.AsyncTimerCallback(Object state) in D:\build\agent\_work\12\s\src\Orleans.Runtime\Streams\PersistentStream\PersistentStreamPullingAgent.cs:line 356
```

This is the line that appears to fail in [EventHubAdapterReceiver.cs](https://github.com/dotnet/orleans/blob/master/src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubAdapterReceiver.cs)

```csharp
        public int GetMaxAddCount()
        {
            return this.flowController.GetMaxAddCount();
        }
```

While this issue is similar to #4431, the code also has:

```csharp
builder.Configure<ClusterOptions>(options =>
{
    options.ClusterId = context.Configuration.GetValue("Orleans:ClusterId", "local");
    options.ServiceId = context.Configuration.GetValue("Orleans:ServiceId", "application");
});
```

What am I missing?

**Comment by JorgeCandeias** [comment]
Never mind. I found the problem and it was between the keyboard and the chair.

`"eventhub-checkpoints"` is, of course, not a valid table name.
