### ISSUE TITLE
Exception when deserializing an empty array.

### ISSUE THREAD

**Issue by krasin-ga** [dotnet/orleans#5918]
I think that the problem is in the **TryCheckLengthFast** method of the **BinaryTokenStreamReader** class, which can return null if argument passed to parameter **n** is 0.

Log message:
```
Exception trying to process 972 bytes from endpoint 10.0.0.16:57786
ExceptionMessage: Value cannot be null. Parameter name: src
```
Stack trace:
```
 at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Orleans.Serialization.BinaryTokenStreamReader.ReadBlockInto(Array array, Int32 n)
   at Orleans.Serialization.SerializationManager.DeserializeArray(Type resultType, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, IBinaryTokenStreamReader stream)
   at Orleans.Runtime.IncomingMessageBuffer.TryDecodeMessage(Message& msg)
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor.ReceiveCallbackContext.ProcessReceived(SocketAsyncEventArgs e)
```

Orleans version: 2.4.1

**Comment by ReubenBond** [comment]
I am fairly confident that this was fixed by #5920. Closing for now until we get repro.
