### ISSUE TITLE
Roslyn code generator fails when Azure Cosmos DB SDK 3.0 is references by a grain

### ISSUE THREAD

**Issue by jkonecki** [dotnet/orleans#5926]
When using Azure Cosmos DB SDK 3.0 inside a grain (even without adding Cosmos SDK types to method declaration) the build fails with error: 

```
2>      Exc level 1: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.Cosmos.Direct, Version=3.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..
2>System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
2>   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2>   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
2>   at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, ILogger logger) in D:\build\agent\_work\23\s\src\Orleans.Core\CodeGeneration\TypeUtils.cs:line 528
2>-- Code Generation FAILED --
2>
2>Exc level 0: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.Cosmos.Direct, Version=3.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
2>   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
2>   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
2>   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
2>   at System.RuntimeType.get_Namespace()
2>   at Orleans.Utilities.RuntimeTypeNameFormatter.AddNamespace(StringBuilder builder, Type type) in D:\build\agent\_work\23\s\src\Orleans.Core\Utils\RuntimeTypeNameFormatter.cs:line 72
2>   at Orleans.Utilities.RuntimeTypeNameFormatter.Format(StringBuilder builder, Type type, Boolean isElementType) in D:\build\agent\_work\23\s\src\Orleans.Core\Utils\RuntimeTypeNameFormatter.cs:line 61
2>   at Orleans.Utilities.RuntimeTypeNameFormatter.<>c.<Format>g__FormatType|3_0(Type t) in D:\build\agent\_work\23\s\src\Orleans.Core\Utils\RuntimeTypeNameFormatter.cs:line 36
2>   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2>   at Orleans.Utilities.CachedReadConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) in D:\build\agent\_work\23\s\src\Orleans.Core\Utils\CachedReadConcurrentDictionary.cs:line 152
2>   at Orleans.Utilities.RuntimeTypeNameFormatter.Format(Type type) in D:\build\agent\_work\23\s\src\Orleans.Core\Utils\RuntimeTypeNameFormatter.cs:line 28
2>   at Orleans.CodeGenerator.RoslynCodeGenerator.AddSerializationTypes(SerializationTypeDescriptions serializationTypes, Assembly targetAssembly, List`1 assemblies) in D:\build\agent\_work\23\s\src\Orleans.CodeGeneration\RoslynCodeGenerator.cs:line 459
2>   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateCode(Assembly targetAssembly, List`1 assemblies) in D:\build\agent\_work\23\s\src\Orleans.CodeGeneration\RoslynCodeGenerator.cs:line 345
2>   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateSourceForAssembly(Assembly input) in D:\build\agent\_work\23\s\src\Orleans.CodeGeneration\RoslynCodeGenerator.cs:line 162
2>   at Orleans.CodeGeneration.CodeGenerator.GenerateSourceForAssembly(Assembly grainAssembly, LogLevel logLevel)
2>   at Orleans.CodeGeneration.CodeGenerator.GenerateCodeInternal(CodeGenOptions options)
2>   at Orleans.CodeGeneration.CodeGenerator.GenerateCode(CodeGenOptions options)
2>   at Orleans.CodeGeneration.Program.Main(String[] args)
```

I believe the issue is caused by Roslyn code generator trying to load all references assemblies, and Microsoft.Azure.Cosmos.Direct package is somehow optional for Cosmos SDK and not always present.

I think Azure Cosmos SDK 3.0 has an issue with async (tasks are hanging when calling SDK from with in a grain - I saw a similar problem in SDK 2.0) and I'm trying to prepare a repro for Cosmos DB Team.

Attached is the repro project.
[Repro.zip](https://github.com/dotnet/orleans/files/3563394/Repro.zip)

cc: @ReubenBond

**Comment by ReubenBond** [comment]
@jkonecki 

As a workaround, can you use the newer code generator package instead? i.e, change:

``` xml
<PackageReference
  Include="Microsoft.Orleans.OrleansCodeGenerator.Build"
  Version="2.4.2"
  PrivateAssets="all">
```

to

``` xml
<PackageReference
  Include="Microsoft.Orleans.CodeGenerator.MSBuild"
  Version="2.4.2"
  PrivateAssets="all">
```

> I think Azure Cosmos SDK 3.0 has an issue with async (tasks are hanging when calling SDK from with in a grain - I saw a similar problem in SDK 2.0) and I'm trying to prepare a repro for Cosmos DB Team.

That seems like a separate (but important) issue. If you get a repro and can send a memory dump, I'll take a look & try to root-cause it

**Comment by jkonecki** [comment]
Thanks Reuben, the new code gen packaged worked!

I have a memory dump - zip file is 30MB, how can I get it over to you?

**Comment by ReubenBond** [comment]
rebond / microsoft.com

**Comment by ReubenBond** [comment]
That dump file looks like it was taken from a client - I see `OutsideRuntimeClient` in the stack traces. Is that the right process?

**Comment by jkonecki** [comment]
@ReubenBond would you like to keep this issue open wrt the old code generator, or should I close it as the new generator is working fine?
