### ISSUE TITLE
MSBuild code generator exception (v3.0)

### ISSUE THREAD

**Issue by MV10** [dotnet/orleans#6155]
I've been playing around with `JournaledGrain`. I have a relatively simple setup with a `Customer` POCO domain model, a few simple domain events derived from a `DomainEventBase` class, the `JournaledGrain` itself is called `CustomerManager` and `CustomerState` derives from `Customer` to add the `Apply` overloads.

One thing I haven't liked about `JournaledGrain` is that `State` and the various `RaiseEvent` methods are protected. I suppose the grain/actor philosophy is that the grain is self-sufficient, but ES is a natural counterpart to CQRS and commands should be issuing events to "document" the results of command-processing, so the grain has to expose a way to accept events, and I also need to access the state to implement certain commands. I decided to try standardizing this with an interface:

```csharp
public interface IEventSourcedGrain<TDomainModel, TEventBase>
    where TDomainModel : class
    where TEventBase : class
{
    TDomainModel ManagedState { get; }
    void RaiseEvent<TEvent>(TEvent @event) where TEvent : TEventBase;
    void RaiseEvents<TEvent>(IEnumerable<TEvent> events) where TEvent : TEventBase;
    Task<bool> RaiseConditionalEvent<TEvent>(TEvent @event) where TEvent : TEventBase;
    Task<bool> RaiseConditionalEvents<TEvent>(IEnumerable<TEvent> events) where TEvent : TEventBase;
    Task ConfirmEvents();
}
```

This is added to my `ICustomerManager` interface:

```csharp
public interface ICustomerManager 
    : IGrainWithStringKey
    , IEventSourcedGrain<Customer, DomainEventBase>
    , ICustomStorageInterface<CustomerState, DomainEventBase>
{ }
```

Then in the grain class the interface is implemented along these lines:

```csharp
public Customer ManagedState
{
    // State is CustomerState which derives from Customer
    get => State;
}

public new void RaiseEvent<TEvent>(TEvent @event)
    where TEvent : DomainEventBase
    => base.RaiseEvent(@event);
```

The exception is caused by the property `TDomainModel ManagedState { get; }`. If I comment that out of the interface, the project builds fine. But with that in the interface I get an error saying my `Customer` domain model doesn't have a `GetAwaiter` method. I'm not sure where or why it's trying to await a Task or how to troubleshoot this further.

The full build output is:

```
1>------ Build started: Project: ServiceCustomerManager, Configuration: Debug Any CPU ------
1>Orleans.CodeGenerator - command-line = SourceToSource C:\Source\OrleansEventStreamLog\ServiceCustomerManager\obj\Debug\netstandard2.1\ServiceCustomerManager.orleans.g.args.txt
1>-- Code Generation FAILED --
1>
1>Exc level 0: System.Collections.Generic.KeyNotFoundException: Type DomainModel.Customer does not have a member of kind Microsoft.CodeAnalysis.IMethodSymbol named GetAwaiter
1>   at Orleans.CodeGenerator.Utilities.SymbolExtensions.Member[TSymbol](ITypeSymbol type, String name, Func`2 predicate) in D:\build\agent\_work\17\s\src\Orleans.CodeGenerator\Utilities\SymbolExtensions.cs:line 241
1>   at Orleans.CodeGenerator.Generators.GrainMethodInvokerGenerator.GenerateInvokeForMethod(WellKnownTypes wellKnownTypes, ExpressionSyntax castGrain, IMethodSymbol method, ExpressionSyntax arguments, Dictionary`2 genericInvokerFields) in D:\build\agent\_work\17\s\src\Orleans.CodeGenerator\Generators\GrainMethodInvokerGenerator.cs:line 275
1>   at Orleans.CodeGenerator.Generators.GrainMethodInvokerGenerator.<>c__DisplayClass8_0.<GenerateInvokeMethod>b__1(IMethodSymbol methodType) in D:\build\agent\_work\17\s\src\Orleans.CodeGenerator\Generators\GrainMethodInvokerGenerator.cs:line 204
1>   at Orleans.CodeGenerator.Generators.GrainInterfaceCommon.GenerateGrainInterfaceAndMethodSwitch(WellKnownTypes types, INamedTypeSymbol grainType, ExpressionSyntax methodIdArgument, Func`2 generateMethodHandler, Func`3 composeInterfaceBlock) in D:\build\agent\_work\17\s\src\Orleans.CodeGenerator\Generators\GrainInterfaceCommon.cs:line 62
1>   at Orleans.CodeGenerator.Generators.GrainMethodInvokerGenerator.GenerateInvokeMethod(WellKnownTypes wellKnownTypes, INamedTypeSymbol grainType, IMethodSymbol invokeMethod, Dictionary`2 genericInvokerFields) in D:\build\agent\_work\17\s\src\Orleans.CodeGenerator\Generators\GrainMethodInvokerGenerator.cs:line 200
1>   at Orleans.CodeGenerator.Generators.GrainMethodInvokerGenerator.GenerateInvokeMethod(WellKnownTypes wellKnownTypes, INamedTypeSymbol grainType, Dictionary`2 genericInvokerFields) in D:\build\agent\_work\17\s\src\Orleans.CodeGenerator\Generators\GrainMethodInvokerGenerator.cs:line 111
1>   at Orleans.CodeGenerator.Generators.GrainMethodInvokerGenerator.GenerateClass(GrainInterfaceDescription description) in D:\build\agent\_work\17\s\src\Orleans.CodeGenerator\Generators\GrainMethodInvokerGenerator.cs:line 65
1>   at Orleans.CodeGenerator.CodeGenerator.GenerateSyntax(AggregatedModel model) in D:\build\agent\_work\17\s\src\Orleans.CodeGenerator\CodeGenerator.cs:line 145
1>   at Orleans.CodeGenerator.CodeGenerator.GenerateCode(CancellationToken cancellationToken) in D:\build\agent\_work\17\s\src\Orleans.CodeGenerator\CodeGenerator.cs:line 59
1>   at Orleans.CodeGenerator.MSBuild.CodeGeneratorCommand.Execute(CancellationToken cancellationToken) in D:\build\agent\_work\17\s\src\Orleans.CodeGenerator.MSBuild\CodeGeneratorCommand.cs:line 143
1>   at Microsoft.Orleans.CodeGenerator.MSBuild.Program.SourceToSource(String[] args) in D:\build\agent\_work\17\s\src\Orleans.CodeGenerator.MSBuild\Program.cs:line 136
1>   at Microsoft.Orleans.CodeGenerator.MSBuild.Program.Main(String[] args) in D:\build\agent\_work\17\s\src\Orleans.CodeGenerator.MSBuild\Program.cs:line 26
1>C:\Users\Jon\.nuget\packages\microsoft.orleans.codegenerator.msbuild\3.0.0\build\Microsoft.Orleans.CodeGenerator.MSBuild.targets(123,5): error MSB3073: The command ""dotnet" "C:\Users\Jon\.nuget\packages\microsoft.orleans.codegenerator.msbuild\3.0.0\build\..\tasks\netcoreapp3.0\Orleans.CodeGenerator.MSBuild.dll" SourceToSource "C:\Source\OrleansEventStreamLog\ServiceCustomerManager\obj\Debug\netstandard2.1\ServiceCustomerManager.orleans.g.args.txt"" exited with code 3.
1>Done building project "ServiceCustomerManager.csproj" -- FAILED.
```

**Comment by MV10** [comment]
Rookie mistake ... everything invoked via proxy must be wrapped in a Task. This can be closed.

```csharp
public interface IEventSourcedGrain<TDomainModel, TEventBase>
    where TDomainModel : class
    where TEventBase : class
{
    Task<TDomainModel> GetManagedState();
    Task RaiseEvent<TEvent>(TEvent @event) where TEvent : TEventBase;
    Task RaiseEvents<TEvent>(IEnumerable<TEvent> events) where TEvent : TEventBase;
    Task<bool> RaiseConditionalEvent<TEvent>(TEvent @event) where TEvent : TEventBase;
    Task<bool> RaiseConditionalEvents<TEvent>(IEnumerable<TEvent> events) where TEvent : TEventBase;
    Task ConfirmEvents();
}
```
