### ISSUE TITLE
[Azure Queue based Stream] Exception: Attempt to read past the end of the input stream

### ISSUE THREAD

**Issue by govenkat-ms** [dotnet/orleans#6160]
In our infra, we have 2 grain types, one a stream grain A that publishes the messages using Azure Queue as its PersistentStreamProvider and another grain type B that **implicitly** subscribes to type A. There are many instances where the consumer grain fails to get activated due to the error message shown below. Any help would be appreciated.

**Configuration**

_Orleans version for all packages_: 2.4.3
_PersistentStreamProvider type_: Azure Queue

**Exception message:** 
```

Exc level 0: System.Runtime.Serialization.SerializationException: Attempt to read past the end of the input stream: CurrentPosition=1648, n=1702062945, totalLength=3244
        at Orleans.Serialization.BinaryTokenStreamReader.CheckLength(Int32 n, Int32& offset, Boolean& safeToUse)
        at Orleans.Serialization.BinaryTokenStreamReader.CheckLength(Int32 n, Int32& offset)
        at Orleans.Serialization.BinaryTokenStreamReader.ReadString()
        at ComputeInputDeserializer(Type , IDeserializationContext )
        at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
        at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
        at OrleansGeneratedCode85767590.OrleansCodeGenMicrosoft_MachineLearning_Common_AsyncOperationsFramework_AsyncOperationStateSerializer.Deserializer(Type expected, IDeserializationContext context)
        at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
        at OrleansGeneratedCode85767590.OrleansCodeGenMicrosoft_MachineLearning_Common_AsyncOperationsFramework_ManagerGrainStateSerializer.Deserializer(Type expected, IDeserializationContext context)
        at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
        at Orleans.Serialization.SerializationManager.DeserializeInner[T](IDeserializationContext context)
        at Orleans.Storage.AzureBlobGrainStorage.ConvertFromStorageFormat(Byte[] contents)
        at Orleans.Storage.AzureBlobGrainStorage.ReadStateAsync(String grainType, GrainReference grainId, IGrainState grainState)
        at Orleans.Core.StateStorageBridge`1.ReadStateAsync() System.Runtime.Serialization.SerializationException: Attempt to read past the end of the input stream: CurrentPosition=1648, n=1702062945, totalLength=3244
        at Orleans.Serialization.BinaryTokenStreamReader.CheckLength(Int32 n, Int32& offset, Boolean& safeToUse)
        at Orleans.Serialization.BinaryTokenStreamReader.CheckLength(Int32 n, Int32& offset)
        at Orleans.Serialization.BinaryTokenStreamReader.ReadString()
        at ComputeInputDeserializer(Type , IDeserializationContext )
        at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
        at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
        at OrleansGeneratedCode85767590.OrleansCodeGenMicrosoft_MachineLearning_Common_AsyncOperationsFramework_AsyncOperationStateSerializer.Deserializer(Type expected, IDeserializationContext context)
        at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
        at OrleansGeneratedCode85767590.OrleansCodeGenMicrosoft_MachineLearning_Common_AsyncOperationsFramework_ManagerGrainStateSerializer.Deserializer(Type expected, IDeserializationContext context)
        at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
        at Orleans.Serialization.SerializationManager.DeserializeInner[T](IDeserializationContext context)
        at Orleans.Storage.AzureBlobGrainStorage.ConvertFromStorageFormat(Byte[] contents)
        at Orleans.Storage.AzureBlobGrainStorage.ReadStateAsync(String grainType, GrainReference grainId, IGrainState grainState)
        at Orleans.Core.StateStorageBridge`1.ReadStateAsync()
```

**Comment by sergeybykov** [comment]
Looks like deserialization failures. I wonder why `ILBasedSerializer` kicks in here.

**Comment by ReubenBond** [comment]
Did a type (eg, `ComputeInput`) change between persisting some state and trying to load it? i.e, does the code differ between versions such that deserialization breaks?

This looks like Azure Blob Grain Storage, from the stack trace, not Azure Queue streams - is that right?

Seeing that `ILBasedSerializer` is being called upon here, that indicates that `ComputeInput` was probably not marked as `[Serializable]`.

It's also possible that a type was marked as `[Immutable]` when it is not actually immutable, but I don't think that's what's going on here.

**Comment by govenkat-ms** [comment]
This error only arose after introducing the streaming aspect of the Grain design. If the useJson property is set to true for GrainBlobStorage properties then I assumed that the Serializable attribute was not needed to be set correct?

**Comment by ReubenBond** [comment]
It looks like it's either reading data which was already stored in a binary format, or UseJson is not set to true

**Comment by ReubenBond** [comment]
I would advise you always mark classes you intend to serializers as [Serializable]

**Comment by ReubenBond** [comment]
Closing due to inactivity - we can reopen if this is still an issue
