### ISSUE TITLE
Microsoft.Orleans.OrleansCodeGenerator.Build not working with .NET Standard 2.1

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#6166]
A have a library project targetting `netstandard2.0` that holds the grain interfaces. I'm using Orleans version 2.4.4, and the code generator is `Microsoft.Orleans.OrleansCodeGenerator.Build`. Everything works fine.

After I updated my project to `netstandard2.1`, code generation fails:

```text
Exc level 0: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](Assembly element)
   at Orleans.ApplicationParts.AssemblyAttributeFeatureProvider`1.PopulateFeature(IEnumerable`1 parts, TFeature feature) in D:\build\agent\_work\25\s\src\Orleans.Core\ApplicationParts\AssemblyAttributeFeatureProvider.cs:line 41
   at Orleans.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature) in D:\build\agent\_work\25\s\src\Orleans.Core\ApplicationParts\ApplicationPartManager.cs:line 49
   at Orleans.ApplicationPartManagerExtensions.CreateAndPopulateFeature[TFeature](IApplicationPartManager applicationPartManager) in D:\build\agent\_work\25\s\src\Orleans.Core\ApplicationParts\ApplicationPartManagerExtensions.cs:line 67
   at Orleans.CodeGenerator.RoslynCodeGenerator..ctor(IApplicationPartManager partManager, ILoggerFactory loggerFactory) in D:\build\agent\_work\25\s\src\Orleans.CodeGeneration\RoslynCodeGenerator.cs:line 43
   at Orleans.CodeGeneration.CodeGenerator.GenerateSourceForAssembly(Assembly grainAssembly, LogLevel logLevel)
   at Orleans.CodeGeneration.CodeGenerator.GenerateCodeInternal(CodeGenOptions options)
   at Orleans.CodeGeneration.CodeGenerator.GenerateCode(CodeGenOptions options)
   at Orleans.CodeGeneration.Program.Main(String[] args)
D:\NuGetPackages\microsoft.orleans.orleanscodegenerator.build\2.4.4\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets(83,5): error MSB3073: The command ""dotnet" "D:\NuGetPackages\microsoft.orleans.orleanscodegenerator.build\2.4.4\build\..\tasks\netcoreapp2.1\Orleans.CodeGeneration.Build.dll" "@obj\Debug\netstandard2.1\codegen\Demo.Microservices.GrainInterfaces.orleans.g.args.txt"" exited with code 3.
Done building project "Demo.Microservices.GrainInterfaces.csproj" -- FAILED.`
```

When trying to compile the project that holds the grain implementations, the same error occurs.

I'm using Visual Studio 2019 Version 16.5.0. Preview 1.0.

**Comment by windperson** [comment]
For targeting .NET Standard 2.1 or .NET Core 3.0, 3.1 project, you need to use the version 3.0.x  nuget packages of Orleans. The [Microsoft.Orleans.CodeGenerator.MSBuild/](https://www.nuget.org/packages/Microsoft.Orleans.CodeGenerator.MSBuild/) package has the same situation.

**Comment by ReubenBond** [comment]
Do you see this issue when using the `Microsoft.Orleans.CodeGenerator.MSBuild` package, too, @peter-perot?

**Comment by peter-perot** [comment]
@ReubenBond Nope. When using the _MSBuild_ variant, compilation works okay. It just seemed to me that the _Build_ variant is more stable because I saw one or two open issues with the _MSBuild_ variant.

BTW I have a question: does mixing code generator variants work? Say I have one assembly compiled with _MSBuild_ code generator and packed into a NuGet package (sort of a common business logic library), and another assembly (sort of an application using the library) compiled with _Build_ code generator – does this work?

**Comment by ReubenBond** [comment]
Mixing the code generators ought to work just fine, as long as they're on different assemblies, but I don't generally recommend it anyway.

Are there any issues with the MSBuild package which affect you? I hope not. I see 2 open issues, but none of them should be impacting

**Comment by peter-perot** [comment]
Thank you, @ReubenBond! You are right, the two open issues are of minor impact and don't affect me.

In the meantime I upgraded our template solution to Orleans 3.0.1 with no friction – compiled it without any code changes.

You can close this issue if you think that we shouldn't track the original issue with netstandard2.1 and the Orleans 2.x _CodeGenerstor.Build_.

**Comment by ReubenBond** [comment]
Glad it worked out for you :)
