### ISSUE TITLE
[macOS] Failure on calling more than 20 grains simultaneously

### ISSUE THREAD

**Issue by vmikhailov** [dotnet/orleans#6174]
Code to reproduce the problem is here https://github.com/vmikhailov/OrleansBugRepro

There is an issue with simultaneous calls to different simple grains. Transport layer seems to corrupt inbound data stream.

**Comment by ReubenBond** [comment]
What am I supposed to see when running this, @vmikhailov? On my machine I see this:

```
********** StartAsync **************.
Press enter to start

Request of 100 instances took: 00:00:00.0099373. 10063.0956094714 per ms
Calling a method of 100 instances took: 00:00:00.5589815. 178.896797121193 per second
Calling a method of 100 instances took: 00:00:00.0203094. 4923.82837503816 per second
Sequentially calculating of totals (100) took: 00:00:00.0744108. 1343.89094056239 per second
```

I'm running on Windows, though, so maybe you can share your output from macOS High Sierra?

**Comment by vmikhailov** [comment]
Processing buffer 1632
Processing buffer 1428
Processing buffer 1224
Processing buffer 1020
Processing buffer 816
Processing buffer 612
Processing buffer 408
Processing buffer 204
Processing buffer 0
Processing buffer 231840
Processing buffer 231636
Processing buffer 231432
Processing buffer 231228
Processing buffer 231024
Processing buffer 230820
Processing buffer 230616
Processing buffer 230412
Processing buffer 230208
Processing buffer 230004
Processing buffer 229800
Processing buffer 229596
Processing buffer 229392
Processing buffer 229188
Processing buffer 228984
Processing buffer 228780
Processing buffer 228576
Processing buffer 228372
Processing buffer 228168
Processing buffer 227964
Processing buffer 227760
Processing buffer 227556
Processing buffer 227352
Processing buffer 227148
Processing buffer 226944
Processing buffer 226740
Processing buffer 226536
Processing buffer 226332
Processing buffer 226128
Processing buffer 225924
Processing buffer 225720
Processing buffer 225516
Processing buffer 225312
Reading 1688365753 bytes in Orleans.Serialization.BinaryTokenStreamReader2
warn: Microsoft.Orleans.Networking[0]
      Exception reading message (null) from remote endpoint 127.0.0.1:30000 to local endpoint 127.0.0.1:55555: System.InvalidOperationException: Insufficient data present in buffer.
         at Orleans.Serialization.BinaryTokenStreamReader2.ThrowInsufficientData() in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 197
         at Orleans.Serialization.BinaryTokenStreamReader2.MoveNext() in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 99
         at Orleans.Serialization.BinaryTokenStreamReader2.<ReadBytes>g__CopySlower|31_0(Span`1& d) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 256
         at Orleans.Serialization.BinaryTokenStreamReader2.ReadBytes(Span`1& destination) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 242
         at Orleans.Serialization.BinaryTokenStreamReader2.ReadBytes(UInt32 count) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 228
         at Orleans.Serialization.BinaryTokenStreamReader2.ReadString() in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 320
         at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadUniqueKey[TReader](TReader this) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader.cs:line 41
         at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadActivationId[TReader](TReader this) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader.cs:line 32
         at Orleans.Runtime.Message.HeadersContainer.Deserializer(Type expected, IDeserializationContext context) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Messaging/Message.cs:line 1201
         at Orleans.Runtime.Messaging.MessageSerializer.HeadersSerializer.Deserialize(ReadOnlySequence`1 input, HeadersContainer& value) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Messaging/MessageSerializer.cs:line 205
         at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Messaging/MessageSerializer.cs:line 67
         at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Networking/Connection.cs:line 215
warn: Microsoft.Orleans.Networking[0]
      Exception while processing messages from remote endpoint 127.0.0.1:30000: System.InvalidOperationException: Insufficient data present in buffer.
         at Orleans.Serialization.BinaryTokenStreamReader2.ThrowInsufficientData() in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 197
         at Orleans.Serialization.BinaryTokenStreamReader2.MoveNext() in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 99
         at Orleans.Serialization.BinaryTokenStreamReader2.<ReadBytes>g__CopySlower|31_0(Span`1& d) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 256
         at Orleans.Serialization.BinaryTokenStreamReader2.ReadBytes(Span`1& destination) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 242
         at Orleans.Serialization.BinaryTokenStreamReader2.ReadBytes(UInt32 count) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 228
         at Orleans.Serialization.BinaryTokenStreamReader2.ReadString() in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 320
         at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadUniqueKey[TReader](TReader this) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader.cs:line 41
         at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadActivationId[TReader](TReader this) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader.cs:line 32
         at Orleans.Runtime.Message.HeadersContainer.Deserializer(Type expected, IDeserializationContext context) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Messaging/Message.cs:line 1201
         at Orleans.Runtime.Messaging.MessageSerializer.HeadersSerializer.Deserialize(ReadOnlySequence`1 input, HeadersContainer& value) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Messaging/MessageSerializer.cs:line 205
         at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Messaging/MessageSerializer.cs:line 67
         at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Networking/Connection.cs:line 215
System.InvalidOperationException: Insufficient data present in buffer.
   at Orleans.Serialization.BinaryTokenStreamReader2.ThrowInsufficientData() in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 197
   at Orleans.Serialization.BinaryTokenStreamReader2.MoveNext() in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 99
   at Orleans.Serialization.BinaryTokenStreamReader2.<ReadBytes>g__CopySlower|31_0(Span`1& d) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 256
   at Orleans.Serialization.BinaryTokenStreamReader2.ReadBytes(Span`1& destination) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 242
   at Orleans.Serialization.BinaryTokenStreamReader2.ReadBytes(UInt32 count) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 228
   at Orleans.Serialization.BinaryTokenStreamReader2.ReadString() in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 320
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadUniqueKey[TReader](TReader this) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader.cs:line 41
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadActivationId[TReader](TReader this) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Serialization/BinaryTokenStreamReader.cs:line 32
   at Orleans.Runtime.Message.HeadersContainer.Deserializer(Type expected, IDeserializationContext context) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Messaging/Message.cs:line 1201
   at Orleans.Runtime.Messaging.MessageSerializer.HeadersSerializer.Deserialize(ReadOnlySequence`1 input, HeadersContainer& value) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Messaging/MessageSerializer.cs:line 205
   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message) in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Messaging/MessageSerializer.cs:line 67
   at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in /Users/vmikhailov/Projects/Github/Orleans/src/Orleans.Core/Networking/Connection.cs:line 215
info: Microsoft.Orleans.Networking[0]
      Completed processing messages from remote endpoint 127.0.0.1:30000
info: Microsoft.Orleans.Networking[0]
      Closing connection with remote endpoint 127.0.0.1:30000
info: Microsoft.Orleans.Networking[0]
      Completed processing messages to remote endpoint 127.0.0.1:30000

**Comment by vmikhailov** [comment]
Console.WriteLine($"Processing buffer {buffer.Length}"); 
added to Connection class at line 213 (right before "int headerLength, bodyLength;")

**Comment by vmikhailov** [comment]
And yes, you need MacOs to reproduce.

**Comment by vmikhailov** [comment]
@ReubenBond, can help with the issue somehow?

**Comment by ReubenBond** [comment]
I'm not sure how to debug this without getting my hands on a macbook yet.

Which version of .NET Core are you running on? The project specifies netcoreapp2.1. There was a JIT bug which bit us in the past on earlier versions of .NET Core 2.1 & 2.2: https://github.com/dotnet/coreclr/issues/20040

If you upgrade to .NET Core 3.1, is this still present?

**Comment by vmikhailov** [comment]
Yes, i'm on 3.1 
Probably i could dump buffers which are going to/from pipes on both sides? Will it help?
Btw, right before getting buffer corrupted i start getting 
warn: Orleans.OutsideRuntimeClient[100011]
      No callback for response message: Response S127.0.0.1:30000:0*grn/2E3C90AF/0000271c@5d5d5d9c->*cli/dc27fca1@04ee4ab3 #247:

**Comment by vmikhailov** [comment]
Reproducible on fresh Catalina and another mac hardware. .NET Core 3.0.100

**Comment by sergeybykov** [comment]
I suspect some kind of a .NET Core on Mac bug because we aren't seeing this behavior on Windows or Linux. Hence, the question - is there a small repro to share with the .NET team?

**Comment by vmikhailov** [comment]
There is a link up there. Test is tiny but requires full Orleans codebase. I think the root cause is somewhere near PipeWriter/PipeReader but i do not understand detailed data exchange between a silo and a client therefore it is difficult to reproduce w/o Orleans.

**Comment by sergeybykov** [comment]
Yeah, I saw it. It would require them to run the whole Orleans stack, which is akin to looking for a needle in a haystack. I was wondering if the repro could be slimmed down somehow to make investigation easier.

**Comment by vmikhailov** [comment]
I will try to draft some simple data exchange test based on the Pipe mechanism used inside Orleans. I hope it will help.

**Comment by sergeybykov** [comment]
That would be ideal. Otherwise, it is only natural to suspect that "the bug is probably somewhere in that Orleans stack above our code."

**Comment by ReubenBond** [comment]
I'm the process of multi-targeting our tests so that we can run them on macOS & Linux. That ought to help us see this issue on the Azure DevOps build agents (which support macOS), so we may be able to make progress.

**Comment by vmikhailov** [comment]
Guys, I've checked it with the latest master and 3.1.101 fw. Looks like problem is gone.

**Comment by ReubenBond** [comment]
That's great! Let's close this, then. Hopefully, it does not need re-opening down the line
