### ISSUE TITLE
 No default storage provider found loading grain type HelloWorld.Grains.HelloArchiveGrain.

### ISSUE THREAD

**Issue by neozhu** [dotnet/orleans#6191]
Orleans.Storage.BadGrainStorageConfigException: No default storage provider found loading grain type HelloWorld.Grains.HelloArchiveGrain.
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at OrleansClient.Program.Main(String[] args) in D:\sample\orleans-3.0.2\orleans-3.0.2\Samples\3.0\TransportLayerSecurity\src\OrleansClient\Program.cs:line 40``

> ``
 await client.Connect(CreateRetryFilter());
                Console.WriteLine("Client successfully connect to silo host");
                var msg =   client.GetGrain<IHelloArchive>(0);
                var res = await msg.SayHello("hello");
                Console.WriteLine(res);
                var list = await msg.GetGreetings();
                Console.WriteLine(list);

**Comment by neozhu** [comment]
````
I am add 

> .AddMemoryGrainStorage("OrleansStorage")
    .AddMemoryGrainStorageAsDefault()

private static async Task<ISiloHost> StartSilo()
        {
            //var config = ClusterConfiguration.LocalhostPrimarySilo();
            //config.Globals.ClusterId = "Test";
            //config.AddMemoryStorageProvider();

            var builder = new SiloHostBuilder()
                .UseLocalhostClustering()
                .AddMemoryGrainStorage("OrleansStorage")
                .AddMemoryGrainStorageAsDefault()
                .ConfigureApplicationParts(parts =>
                    parts.AddApplicationPart(typeof(IInventoryItemGrain).Assembly).WithReferences())
                .ConfigureLogging(logging => logging.AddConsole())

                ;

            var host = builder.Build();
            await host.StartAsync();
            return host;
        }

execute get http://localhost:60430/bank/account/e2ad8864-4548-44e8-b35d-7f9e45d38f57  error
An unhandled exception occurred while processing the request.
SerializationException: Unexpected token 'Error' introducing type specifier
Orleans.Serialization.SerializationManager.DeserializeInner<TContext, TReader>(SerializationManager sm, Type expected, TContext context, TReader reader)

> System.Runtime.Serialization.SerializationException: Unexpected token 'Error' introducing type specifier
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at ConnectionClosedExceptionDeserializer(Type , IDeserializationContext )
   at Orleans.Serialization.ILBasedExceptionSerializer.Deserialize(Type expectedType, IDeserializationContext outerContext)
   at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value)
   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message)
   at Orleans.Runtime.Messaging.Connection.ProcessIncoming()
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Web.BankAccountModule.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext() in D:\sample\PracticalOrleans-master\src\Web\BankAccountModule.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at Botwin.BotwinExtensions.<>c__DisplayClass1_0.<<CreateRouteHandler>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
