### ISSUE TITLE
Orleans Membership using SQLServer fails in .Net Core

### ISSUE THREAD

**Issue by ALEXR92** [dotnet/orleans#6203]
Hi,
I am trying to migrate our silo project into a .Net Core one but I am facing a new exception that I didn't have when using Framework 4.7.2. The exception is raised creating the membership using SQL Server and says:

_The keyword 'asynchronous processing' is not supported on this platform.
at System.Data.SqlClient.SqlConnectionString.ThrowUnsupportedIfKeywordSet(String keyword)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Orleans.Clustering.AdoNet.Storage.DbConnectionFactory.CreateConnection(String invariantName, String connectionString)
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage.ExecuteAsync[TResult](String query, Action`1 parameterProvider, Func`5 executor, Func`4 selector, CancellationToken cancellationToken, CommandBehavior commandBehavior)
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage.ReadAsync[TResult](String query, Action`1 parameterProvider, Func`4 selector, CancellationToken cancellationToken, CommandBehavior commandBehavior)
   at Orleans.Clustering.AdoNet.Storage.RelationalOrleansQueries.CreateInstance(String invariantName, String connectionString, IGrainReferenceConverter grainReferenceConverter)
   at Orleans.Runtime.MembershipService.AdoNetClusteringTable.InitializeMembershipTable(Boolean tryInitTableVersion)
   at Orleans.Runtime.MembershipService.MembershipTableManager.Start()
   at Orleans.Runtime.MembershipService.MembershipTableManager.<>c__DisplayClass53_0.<<Orleans-ILifecycleParticipant<Orleans-Runtime-ISiloLifecycle>-Participate>g__OnRuntimeGrainServicesStart|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct)
   at Orleans.LifecycleSubject.<OnStart>g__CallOnStart|7_0(Int32 stage, OrderedObserver observer, CancellationToken cancellationToken)
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute()
   at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken)
   at Orleans.Hosting.SiloWrapper.StartAsync(CancellationToken cancellationToken)
   at SiloWorkerService.SiloWorker.StartAsync(CancellationToken cancellation) in D:\Dev\Alex\DevNew\PRICING\LFService\Developement\SiloWorkerService\SiloWorker.cs:line 126
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)

I already tried updating Orleans nuget packages to the latest version (3.0.2) and also system.data.SqlClient (4.8.0) but doesn't seem to fix it.
Does anyone have an idea ?

**Comment by sergeybykov** [comment]
Tagging @veikkoeeva in the new year. 🙂

**Comment by veikkoeeva** [comment]
As per the exception, it looks like the problem is parameter `asynchronous processing` in the connection string, some more information at https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/asynchronous-programming. This parameter was ignored after .NET 4.5 update, I think, and it appears removed altogether in .NET Core.

**Comment by ALEXR92** [comment]
That's it!! Removed `Asynchronous Processing=True;` from the connection string and now it works perfectly.
Thank you
