### ISSUE TITLE
Unit Testing Streams and UnsubscribeAsync

### ISSUE THREAD

**Issue by pawanrao** [dotnet/orleans#6371]
hey folks,
I'm having a problem testing streams with OrleansTestKit and perhaps someone here could throw some light on why that is happening
My sample code is up here:
https://gist.github.com/pawanrao/6c0c682e490b625a2db7d08098712b3c

The problem I'm facing is that when I try to assert that the stream subscriber for `OnNextAsync` is called correctly, the unsubscribe seems to happen before the test has executed and I run into the following error:
```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute

System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)

   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult() in D:\a\1\s\src\NUnitFramework\framework\Internal\TaskAwaitAdapter.cs:line 99
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke) in D:\a\1\s\src\NUnitFramework\framework\Internal\AsyncToSyncAdapter.cs:line 60
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 64
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork() in D:\a\1\s\src\NUnitFramework\framework\Internal\Execution\SimpleWorkItem.cs:line 58
```

I'm a little confused if this is a limitation of OrleansTestKit or if I'm unsubscribing to the stream at the wrong place
Any help would be appreciated!

**Comment by ReubenBond** [comment]
Looking at the test, I think this belongs on the [OrleansTestKit repo](https://github.com/OrleansContrib/OrleansTestKit), which I am not very familiar with the inner workings of.

The code is creating a grain outside the context of Orleans and it doesn't look as though there is any scheduler there, which *might* explain why the test fails.

Does the code work using a real silo?

**Comment by pawanrao** [comment]
@ReubenBond code does work correctly in a real silo. 
I'll try posting this on the OrleansTestKit repo

**Comment by pawanrao** [comment]
This was an issue with testkit and a fix was released.
