### ISSUE TITLE
Issue getting stream in Singleton using the ClusterClient

### ISSUE THREAD

**Issue by hero-joel** [dotnet/orleans#6398]
When getting a stream in a Singleton using the ClusterClient orleans it throws an System.InvalidOperationException saying "Attempting to GetCurrentActivationData when not in an activation scope".

`  this._streamProvider = this._clusterClient.GetStreamProvider(HostConstants.STREAM_PROVIDER);
            this._serverStream = this._streamProvider.GetStream<ClientMessage>(HostConstants.ALL_STREAM_ID, HostConstants.STREAM_NAMESPACE);`

> System.InvalidOperationException: Attempting to GetCurrentActivationData when not in an activation scope
>    at Orleans.Runtime.InsideRuntimeClient.<GetCurrentGrainContext>g__ThrowInvalidOperationException|87_0()
>    at Orleans.Runtime.InsideRuntimeClient.GetCurrentGrainContext(ISchedulingContext context)
>    at Orleans.Runtime.InsideRuntimeClient.GetStreamDirectory()
>    at Orleans.Runtime.Providers.SiloProviderRuntime.GetStreamDirectory()
>    at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProvider.GetStream[T](Guid id, String streamNamespace)
>    at Test.Silo.Services.CustomHubLifetimeManager`1.SetupStreams() in C:\git\tmp\orleansingletonstreamissue\CustomHubLifetimeManager.cs:line 60

This worked before upgrading to orleans 3+ and is essentially the same way that OrleansContrib/SignalR.Orleans packages does it. 
i tried setting up the streams after boot as well and get the same result.

please see https://github.com/hero-joel/orleansingletonstreamissue  for a somewhat minimal  recreation.

**Comment by hero-joel** [comment]
After updating to 3.1.2 of orleans the error changed;

> [13:54:01.147 ERR] QueueWorkItem was called on a non-null context [SystemTarget: S127.0.0.1:11111:321800040*stg/14/0000000e@S0000000e] but there is no valid WorkItemGroup for it.
[13:54:01.157 ERR] Failed to address message Request S127.0.0.1:11111:321800040*cli/8c61d592@148c138b->*grn/716E8E94/71558182+ORLEANS_SIGNALR_STREAM_PROVIDER_SERVERS_STREAM #2: 
 from activation null
Orleans.Runtime.InvalidSchedulingContextException: QueueWorkItem was called on a non-null context [SystemTarget: S127.0.0.1:11111:321800040*stg/14/0000000e@S0000000e] but there 
is no valid WorkItemGroup for it.
   at Orleans.Runtime.Scheduler.OrleansTaskScheduler.ThrowNoWorkItemGroup(ISchedulingContext context)
   at Orleans.Runtime.Scheduler.OrleansTaskScheduler.QueueWorkItem(IWorkItem workItem, ISchedulingContext context)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.QueueTask[T](OrleansTaskScheduler scheduler, Func`1 taskFunc, ISchedulingContext targetContext)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.RunOrQueueTask[T](OrleansTaskScheduler scheduler, Func`1 taskFunc, ISchedulingContext targetContext)
   at Orleans.Runtime.Catalog.FullLookup(GrainId grain)
   at Orleans.Runtime.Placement.RandomPlacementDirector.OnSelectActivation(PlacementStrategy strategy, GrainId target, IPlacementRuntime context)
   at Orleans.Runtime.Placement.PlacementDirectorsManager.SelectOrAddActivation(ActivationAddress sendingAddress, PlacementTarget targetGrain, IPlacementRuntime context, PlacementStrategy strategy)
   at Orleans.Runtime.Dispatcher.AddressMessageAsync(Message message, PlacementTarget target, PlacementStrategy strategy, ActivationAddress targetAddress)
   at Orleans.Runtime.Dispatcher.<>c__DisplayClass36_0.<<AsyncSendMessage>g__TransportMessageAferSending|0>d.MoveNext()

**Comment by hero-joel** [comment]
After banging my head on this most of the weekend i got a working solution, i consider it a work around however based on various comments i found on other issues that you are supposed to do stream setup on startup #5444 . 

After realizing that the original error did not really make sense and seeing there was 3.1.2 release of orleans i updated to that, as mentioned above i now got a different error message. I then removed the EnsureStreamSetup() form the constructor of the CustomHubLifetimeManager ( the singleton) and instead only call it and setup the streams on the first time it's used (first time a connection is made to signalr in my case) and it works.

please close the issue if my understanding that it should be possible to setup streams on startup is wrong.

**Comment by ReubenBond** [comment]
Apologies for the slow reply. I think this should work. Where is the code being called?

**Comment by hero-joel** [comment]
The stream subs are setup in 
https://github.com/hero-joel/orleansingletonstreamissue/blob/master/CustomHubLifetimeManager.cs
this singleton is instansiated
in the startup, https://github.com/hero-joel/orleansingletonstreamissue/blob/master/API/Startup.cs

**Comment by ReubenBond** [comment]
This lock is not released in all cases: https://github.com/hero-joel/orleansingletonstreamissue/blob/b8a351f3f30b3a6835e099dc374db76009ef4683/CustomHubLifetimeManager.cs#L37

I think what's happening here is that the hub setup code is being called too early, before the silo has initialized, so things may not be fully setup when it gets called.
