### ISSUE TITLE
Silos Periodically Shutdown After Upgrade from 2.4.2 to 3.1.4

### ISSUE THREAD

**Issue by SebFerraro** [dotnet/orleans#6470]
We are finding that our silos in both our production and UAT areas are, seemingly randomly, dying/shutting down since the upgrade from 2.4.2 to 3.1.4. There are no critical errors I can find in the silo logs. Neither are there any event log messages. Due to this, the windows service manager doesn't try and restart the service. At the moment we have a task scheduler task in place that continually checks and starts the silos if required.

The below is a log from our one of our production silos.

https://gist.github.com/SebFerraro/1f0fa283bd2cff3e1be24d4ef7e1c979

Our setup is as such:

Azure North Europe
9 x D4s v3 (with 3 vms inside each of the 3 availability zones)
Windows 2019 datacentre
Silos running as windows service

Our average Orleans Dashboard stats don't seem to have changed. We are still seeing roughly 100ms/req and throughput of ~250-300req/s at peak.

**Comment by ReubenBond** [comment]
The first thing I notice is this line: `An established connection was aborted by the software in your host machine`

Orleans silos will not shut themselves down un-prompted. There are a few general ways for a silo to stop:

* A crash/termination of the process (.NET runtime crashes or something forcibly kills the process)
* The silo host (IHost/ISiloHost) receives SIGINT
* The silo is declared dead, in which case it logs a `Critical`-level message and calls `Environment.FastExit()`. You should see a message containing `FATAL EXCEPTION from`, in the console, or `Fatal error from` in the logs. Typically, that would be coupled with a preceding message starting with `I have been told I am dead, so this silo will stop!`

I don't see any of those in the logs you posted.

I do see some very long pauses (>11 seconds) in your process, though. Is there some synchronous pausing occurring or some very heavy GC load? Long pauses (typically, >15s) with result in the 3rd reason above for termination, as other silos will vote the silo dead, since it hasn't responded.

Regarding those pauses, I see no logs during that pause time, which indicates whole-process pause, which indicates GC.

The next step would be to record some performance traces. Maoni Stephens posted a description of her workflow here: https://devblogs.microsoft.com/dotnet/work-flow-of-diagnosing-memory-performance-issues-part-0/

If memory issues are causing a problem, then dumps (either `procdump`/`dotnet dump` or `dotnet gcdump`, which doesn't include the full heap, just a summary) can also be useful to analyze.

I typically also take CPU samples for, eg, 30 seconds: `.\PerfView.exe /acceptEULA /noGui /threadTime /zip /maxCollectSec:30 /dataFile:1.etl collect`

**Comment by KevinCathcart** [comment]
Some slightly more detailed analysis from the log that may or may not be helpful, plus a few questions that might help narrow things down. (Beyond just what performance traces or memory dumps might tell you).

**Important question: Is the silo service process actually stopping?** That would almost certainly require one of those three cases Reuben mentioned. If the service is still running, but is non-responsive (which is how the first gitter message sounded to me), that suggests other possibilities. I'm assuming the latter in the following analysis.

From a detailed look at the one log, it looks like the connection with 172.30.72.22:22222 got aborted, causing it to be closed and reopened. Then about 2 seconds later many (all?) of the other outbound connections die (also aborted), and get reopened. At that point the doomed silo has successful reopened connections back to the other silos, so things _should_ be working again. Instead we see: `OrleansMessageRejectionException`s stemming from terminated connections, grain calls getting aborted due to response not arriving in 30 seconds, and a bunch of responses to other silos eventually timing out without having gotten sent. 

Aside: The Connection aborts are interesting because those most commonly happen when a network is way too congested, or the target machine has suddenly crashed or powered off (and thus, cannot send an RST packet back) or a firewall or other network security program or appliance starts silently dropping the packets. Unsure the cause of these aborts in this case, but Orleans definitely is intended to be able to recover from that.

Assuming the process continues to run, it looks to me like something is causing messages to not properly flow over the re-opened connections. I also have to wonder why the unresponsive silo is not getting voted dead, then stopping itself. If all Orleans task scheduler threads were blocked with synchronous IO, or stuck in an infinite loop, or something, that might explain things.

**Do the other logs show any signs of the non-responding silos getting voted dead, prior to you restarting them?** If not, then I think we need to conclude that the non-responsive silos are still responding to ping messages, despite normal messages not working. That is actually plausible, as the ping messages have special short circuit handling on the receiving silo side, bypassing a lot of the machinery that normal messages travel through. If that is the case, it is still unclear though how processing of other messages could break as some sort of side effect of the abort (or perhaps break due to some unknown cause that is also responsible for the connection aborts.)

It is worth noting that a networking code re-write was a significant change between 2.x and 3.x, so it is not possible that you are encountering a bug in the new code. Of course, this does raise the question as to why other people are not encountering this same issue. (I mention this because the one thing you mention changing is upgrading to 3.1.4.) **Are you running against the .NET Framework, or core, and which version specifically?** An uncommon answer to that question might possibly explain why you are seeing something that others are not.

Hope this proves useful in some way.

**Comment by NoMercy82** [comment]
Hi there guys. To respond to some of the questions:

Yes the process is indeed stopping. And it is doing so in a non-critical way such that the recovery options set on the windows service do not realise they need to restart it.

We are running against .NET Framework 4.7.2, we decided to wait until .NET 5 was released and supported rather than migrate to Core first.

**Comment by KevinCathcart** [comment]
Hmm... The service stopping cleanly, such that Windows' Service Manager's restart policies don't kick in sounds really odd. 

As Reuben explained, the main reason for a silo to stop itself (other than receiving a shutdown signal for the appropriate hosting type, like SIGINT/SIGTERM for console apps, or the service stop command for windows services) is fatal membership errors, the most prominent of which is a silo finding itself declared dead.

That case uses `IFatalErrorHandler`, and the default implementation of which calls `Environment.FailFast()`. If that happened, I'm pretty sure windows would see this as the service crashing. Of course, in the unlikely event you replaced the default `IFatalErrorHandler`, your replacement could do anything.


The only other case in which Orleans itself would directly exit the process is if the logger `.Fail(...)` extension method is called, possibly via the logger `.Assert(...)` extension method. However, neither of those is actually used in real code paths inside Orleans. And even if it were called, it does `Process.Exit(128)`, which I would expect to be treated as a service failing. 


Other than that, the only way for the process to end are the normal .NET ways, like user code calling one of those methods, an unhandled exception taking down the process (which would get logged in the event log), or reaching the end of the main function.

**Comment by NoMercy82** [comment]
Hi guys - I have to apologise. Upon initial inspection the event viewer did not initially appear to show any logs.

However, I have now picked up the following:

`Application: Silohost.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: FATAL EXCEPTION from Orleans.Runtime.MembershipService.MembershipTableManager. Context: I have been told I am dead, so this silo will stop! I should be Dead according to membership table (in CleanupTableEntries): entry = [SiloAddress=S172.30.88.25:22222:324120169 SiloName=Silo_2961d Status=Dead HostName=VerUatBifrost05 ProxyPort=40000 RoleName= UpdateZone=0 FaultZone=0 StartTime = 2020-04-09 09:22:50.200 GMT IAmAliveTime = 2020-04-10 06:22:57.203 GMT Suspecters = [S172.30.88.22:22222:324106191, S172.30.88.21:22222:324148547] SuspectTimes = [2020-04-09 16:01:24.647 GMT, 2020-04-10 06:24:55.579 GMT]].. Exception: null.
Current stack:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Orleans.Runtime.FatalErrorHandler.OnFatalException(Object sender, String context, Exception exception)
   at Orleans.Runtime.MembershipService.MembershipTableManager.KillMyselfLocally(String reason)
   at Orleans.Runtime.MembershipService.MembershipTableManager.<CleanupMyTableEntries>d__47.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Orleans.Runtime.MembershipService.MembershipTableManager.CleanupMyTableEntries(MembershipTableData table)
   at Orleans.Runtime.MembershipService.MembershipTableManager.<RefreshInternal>d__34.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Orleans.Runtime.MembershipService.AdoNetClusteringTable.<ReadAll>d__8.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Orleans.Clustering.AdoNet.Storage.RelationalOrleansQueries.<ReadAsync>d__7`2.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage.<ReadAsync>d__10`1.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage.<ExecuteAsync>d__15`1.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage.<ExecuteReaderAsync>d__14`1.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage.<SelectAsync>d__13`1.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.TaskCompletionSource`1.TrySetResult(TResult result)
   at System.Data.SqlClient.SqlDataReader.CompleteRetryable[T](Task`1 task, TaskCompletionSource`1 source, IDisposable objectToDispose)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Orleans.Runtime.FatalErrorHandler.OnFatalException(System.Object, System.String, System.Exception)
   at Orleans.Runtime.MembershipService.MembershipTableManager.KillMyselfLocally(System.String)
   at Orleans.Runtime.MembershipService.MembershipTableManager+<CleanupMyTableEntries>d__47.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Orleans.Runtime.MembershipService.MembershipTableManager+<CleanupMyTableEntries>d__47, Orleans.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]](<CleanupMyTableEntries>d__47 ByRef)
   at Orleans.Runtime.MembershipService.MembershipTableManager.CleanupMyTableEntries(Orleans.MembershipTableData)
   at Orleans.Runtime.MembershipService.MembershipTableManager+<RefreshInternal>d__34.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Orleans.Runtime.MembershipService.AdoNetClusteringTable+<ReadAll>d__8.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Orleans.Clustering.AdoNet.Storage.RelationalOrleansQueries+<ReadAsync>d__7`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage+<ReadAsync>d__10`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage+<ExecuteAsync>d__15`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage+<ExecuteReaderAsync>d__14`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage+<SelectAsync>d__13`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(Boolean)
   at System.Threading.Tasks.TaskCompletionSource`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(Boolean)
   at System.Data.SqlClient.SqlDataReader.CompleteRetryable[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Threading.Tasks.Task`1<Boolean>, System.Threading.Tasks.TaskCompletionSource`1<Boolean>, System.IDisposable)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
`

**Comment by KevinCathcart** [comment]
Ok. So at least we now understand what is killing the silo. What is left is figuring out what is causing the the long pauses that result in the other silos thinking this one has died. Then there is also the open question of why the failfast is not triggering the services restart on failure policy.

**Comment by SebFerraro** [comment]
Whilst I would love to say why our Orleans instance kept crashing due to this, I unfortunately can't. But I removed the [Reentrant] setting on a single grain and since doing so, our Orleans cluster has not had a single silo restart. This was only 2 days ago now, but I willa continue to monitor and will close the issue if I don't see it happen again within a 7 day period if that's ok.

I don't know this was causing the silos to die and drop out, but something was evidently not happy with it!

**Comment by SebFerraro** [comment]
Since removing a reentrant flag from a grain, this has no longer caused us any issues. I will close for now.
