### ISSUE TITLE
OrleansLifecycleCanceledException using ASP.NET Core Co-Hosting

### ISSUE THREAD

**Issue by ryoshi87** [dotnet/orleans#6534]
Hi,

i've tried to integrate the Orleans silo into our main ASP.NET Core API as a co-hosting component.
I've followed the sample from https://github.com/dotnet/orleans/tree/master/Samples/3.0/AspNetCoreCohosting.

When the server is starting up i've get an Orleans.Runtime.OrleansLifecycleCanceledException, which states:

> Orleans.Runtime.Silo: Error: Exception during Silo.Start
> 
> Orleans.Runtime.OrleansLifecycleCanceledException: Lifecycle start canceled by request
>    at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
>    at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute()
>    at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken)

There seems to be no more info in the output, that relates to the error.
I can't find the cause and looking at the https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Lifecycle/LifecycleSubject.cs I don't know who's requesting the cancel.

Any ideas on how to debug or find the issue?

Greetings
Daniel

**Comment by ryoshi87** [comment]
Hi,

I've found my error and sometimes the most obvious things are overlooked.
So just for documentation purpose or if someone else does make this bonehead mistake:

While converting the old app to the generic web host, I've changed to
`CreateWebHostBuilder(args).RunConsoleAsync();`
but forgot to change the Main method signiture to
`public static Task Main(string[] args)`
having a void as return type caused the Orleans service to stop, while the rest of the API was still working.

Greetings Daniel
