### ISSUE TITLE
Restarting the server after Streams Subscribe does not work

### ISSUE THREAD

**Issue by GaLeGayGay** [dotnet/orleans#6550]
Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProvider[0]
      Initialized SimpleMessageStreamProvider with name SMSProvider and with property FireAndForgetDelivery: False, OptimizeForImmutableData: True and PubSubType: ExplicitGrainBasedAndImplicit
fail: Orleans.LifecycleSubject[100450]
      Lifecycle start canceled due to errors at stage 2000: System.NullReferenceException: Object reference not set to an instance of an object.
         at Orleans.Streams.PubSubRendezvousGrain.<>c__DisplayClass23_0.<GetAllSubscriptions>b__0(PubSubSubscriptionState c)
         at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at Orleans.Streams.PubSubRendezvousGrain.GetAllSubscriptions(StreamId streamId, IStreamConsumerExtension streamConsumer)
         at Orleans.Streams.OrleansCodeGenPubSubRendezvousGrainMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request)
         at Orleans.Runtime.GrainMethodInvoker.Invoke()
         at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message)
         at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
         at Orleans.Streams.StreamPubSubImpl.GetAllSubscriptions(StreamId streamId, IStreamConsumerExtension streamConsumer)
         at Orleans.Streams.StreamConsumer`1.GetAllSubscriptions()
         at OrleansHttp.Host.HelloGrain.OnActivateAsync() in D:\Project\Other\ConsoleApp1\ConsoleApp1\HelloGrain.cs:line 24
         at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
fail: Orleans.Runtime.Catalog[100513]
      Error calling grain's OnActivateAsync() method - Grain type = OrleansHttp.Host.HelloGrain Activation = [Activation: S127.0.0.1:11111:328183974*grn/416BFC04/00000000@d99a39bd #GrainType=OrleansHttp.Host
.HelloGrain Placement=RandomPlacement State=Activating]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Streams.PubSubRendezvousGrain.<>c__DisplayClass23_0.<GetAllSubscriptions>b__0(PubSubSubscriptionState c)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Orleans.Streams.PubSubRendezvousGrain.GetAllSubscriptions(StreamId streamId, IStreamConsumerExtension streamConsumer)
   at Orleans.Streams.OrleansCodeGenPubSubRendezvousGrainMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request)
   at Orleans.Runtime.GrainMethodInvoker.Invoke()
   at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message)
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Orleans.Streams.StreamPubSubImpl.GetAllSubscriptions(StreamId streamId, IStreamConsumerExtension streamConsumer)
   at Orleans.Streams.StreamConsumer`1.GetAllSubscriptions()
   at OrleansHttp.Host.HelloGrain.OnActivateAsync() in D:\Project\Other\ConsoleApp1\ConsoleApp1\HelloGrain.cs:line 24
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
   at Orleans.Runtime.Catalog.CallGrainActivate(ActivationData activation, Dictionary`2 requestContextData)
warn: Orleans.Runtime.Catalog[100534]
      Failed to InvokeActivate for [Activation: S127.0.0.1:11111:328183974*grn/416BFC04/00000000@d99a39bd #GrainType=OrleansHttp.Host.HelloGrain Placement=RandomPlacement State=FailedToActivate].
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Streams.PubSubRendezvousGrain.<>c__DisplayClass23_0.<GetAllSubscriptions>b__0(PubSubSubscriptionState c)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Orleans.Streams.PubSubRendezvousGrain.GetAllSubscriptions(StreamId streamId, IStreamConsumerExtension streamConsumer)
   at Orleans.Streams.OrleansCodeGenPubSubRendezvousGrainMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request)
   at Orleans.Runtime.GrainMethodInvoker.Invoke()
   at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message)
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Orleans.Streams.StreamPubSubImpl.GetAllSubscriptions(StreamId streamId, IStreamConsumerExtension streamConsumer)
   at Orleans.Streams.StreamConsumer`1.GetAllSubscriptions()
   at OrleansHttp.Host.HelloGrain.OnActivateAsync() in D:\Project\Other\ConsoleApp1\ConsoleApp1\HelloGrain.cs:line 24
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
   at Orleans.Runtime.Catalog.CallGrainActivate(ActivationData activation, Dictionary`2 requestContextData)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute()
   at Orleans.Runtime.Catalog.InitActivation(ActivationData activation, Dictionary`2 requestContextData)
info: Orleans.Messaging[101033]
      Forwarding 1 requests destined for address S127.0.0.1:11111:328183974*grn/416BFC04/00000000@d99a39bd to address (null) after OnActivateAsync failed
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Streams.PubSubRendezvousGrain.<>c__DisplayClass23_0.<GetAllSubscriptions>b__0(PubSubSubscriptionState c)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Orleans.Streams.PubSubRendezvousGrain.GetAllSubscriptions(StreamId streamId, IStreamConsumerExtension streamConsumer)
   at Orleans.Streams.OrleansCodeGenPubSubRendezvousGrainMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request)
   at Orleans.Runtime.GrainMethodInvoker.Invoke()
   at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message)
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Orleans.Streams.StreamPubSubImpl.GetAllSubscriptions(StreamId streamId, IStreamConsumerExtension streamConsumer)
   at Orleans.Streams.StreamConsumer`1.GetAllSubscriptions()
   at OrleansHttp.Host.HelloGrain.OnActivateAsync() in D:\Project\Other\ConsoleApp1\ConsoleApp1\HelloGrain.cs:line 24
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
   at Orleans.Runtime.Catalog.CallGrainActivate(ActivationData activation, Dictionary`2 requestContextData)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute()
   at Orleans.Runtime.Catalog.InitActivation(ActivationData activation, Dictionary`2 requestContextData)

**Comment by GaLeGayGay** [comment]
![QQ图片20200526181447](https://user-images.githubusercontent.com/8246779/82889151-e5e56a80-9f7c-11ea-9c5e-24ea04b686fe.png)
![QQ图片20200526181510](https://user-images.githubusercontent.com/8246779/82889155-e7169780-9f7c-11ea-8cf4-bd2c62a711cb.png)

**Comment by GaLeGayGay** [comment]
![image](https://user-images.githubusercontent.com/8246779/82964760-d99ef300-9ff8-11ea-9333-da14d0c1feb0.png)

**Comment by GaLeGayGay** [comment]
If I delete the Cosmos table, it will work

**Comment by GaLeGayGay** [comment]
![image](https://user-images.githubusercontent.com/8246779/82965494-df95d380-9ffa-11ea-8480-a9823f41f612.png)
After adding this Attribute work fine
