### ISSUE TITLE
[Error] Silo Stop There's a problem

### ISSUE THREAD

**Issue by Cloud33** [dotnet/orleans#6568]
This error will occur when Silo shuts down normally, what did I do?
I have a usage reminder，

Orleans 3.1.17
```
fail: Orleans.Runtime.ClientObserverRegistrar[101317]
      Directory.RegisterAsync S127.0.0.1:11111:328687643*cli/60e6dda6@e8765d68 failed.
System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.RegisterAsync(ActivationAddress address, Boolean singleActivation, Int32 hopCount)
   at Orleans.Internal.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message)
fail: Orleans.Runtime.ClientObserverRegistrar[101317]
      Directory.RegisterAsync S127.0.0.1:11111:328687643*cli/f73678b9@51168991 failed.
System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.RegisterAsync(ActivationAddress address, Boolean singleActivation, Int32 hopCount)
   at Orleans.Internal.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message)
fail: Orleans.Runtime.ClientObserverRegistrar[101319]
      OnClientRefreshTimer has thrown an exceptions.
System.InvalidOperationException: Grain directory is stopping
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.RegisterAsync(ActivationAddress address, Boolean singleActivation, Int32 hopCount)
   at Orleans.Internal.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message)
   at Orleans.Runtime.ClientObserverRegistrar.OnRefreshClients()
```

**Comment by sergeybykov** [comment]
In this case, do you have a single silo in the cluster?

**Comment by Cloud33** [comment]
yes，configure
```
var builder = new SiloHostBuilder()
                     .UseLocalhostClustering()
```

**Comment by sergeybykov** [comment]
A single silo cannot cleanly shut down because it doesn't have other silos to forward messages to. So I would treat this behavior as by design, even it is unclean.

**Comment by Cloud33** [comment]
Can I understand it as no effect? Thank you for your reply

**Comment by sergeybykov** [comment]
It a normal behavior of the last silo shutting down in a cluster.

**Comment by Cloud33** [comment]
Thank you for your answer. Solved my problem.
