### ISSUE TITLE
ConnectionString is not valid. Error trying to connect to blob storage 

### ISSUE THREAD

**Issue by Serhii-Boiko-Dev** [dotnet/orleans#6576]
When the silo starts, I get an error connecting to the blob storage

> Orleans.Runtime.OrleansConfigurationException: 'Configuration for AzureTableStorageProvider Default is invalid. ConnectionString is not valid.

program.cs from SiloHost project, added a method TestConnectionBlobStorage, that checks the connection, method returns a positive result

```
namespace SiloHost
{
    public class Program
    {
        public static Task Main(string[] args)
        {
            bool TestConnectionBlobStorage(string connectionString, string containerName)
            {
                try
                {

                    BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
                    BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);

                    return containerClient.Exists();

                }
                catch (Exception)
                {
                    return false;
                }
            }

            if (TestConnectionBlobStorage(AppSettingsProvider.AzureStorageConnectionString, "state-store"))
                Console.WriteLine("Blob Connection passed");

            return new HostBuilder()
                .UseOrleans(builder =>
                {
                    builder
                        .UseLocalhostClustering()
                        .AddAzureBlobGrainStorage("state-store",
                                options =>
                                {
                                    // Use JSON for serializing the state in storage
                                    options.UseJson = true;

                                    // Configure the storage connection key
                                    options.ConnectionString = AppSettingsProvider.AzureStorageConnectionString;
                                    options.ContainerName = "state-store";
                                })

                        .AddAzureTableGrainStorageAsDefault()
                        .Configure<ClusterOptions>(options =>
                        {
                            options.ClusterId = "dev";
                            options.ServiceId = "UserProvider";
                        })
                        //.ConfigureEndpoints(siloPort: 30001, gatewayPort: 30002, listenOnAnyHostAddress: true)
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(UserCollectionGrain).Assembly).WithReferences())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(UserGrain).Assembly).WithReferences());
                })
                .ConfigureServices(services =>
                {
                    services.Configure<ConsoleLifetimeOptions>(options =>
                    {
                        options.SuppressStatusMessages = true;
                    });
                })
                .ConfigureLogging(builder =>
                {
                    builder.AddConsole();
                })
                .RunConsoleAsync();
        }
    }
}
```
and code snippet from grain project
```    [StorageProvider(ProviderName = "state-store")]
    public class UserGrain : Grain<UserState>, IUserGrain
    {

        private readonly ILogger<UserGrain> logger;
        private readonly IPersistentState<UserState> state;
        private Guid OwnerKey;

        private Guid GrainKey => this.GetPrimaryKey();

        public UserGrain(ILogger<UserGrain> logger, [PersistentState("UserModel")] IPersistentState<UserState> state)
        {
            this.state = state;
            this.logger = logger;
        }
``` 
full error log
```
      -------------- Started silo S127.0.0.1:11111:328962475, ConsistentHashCode C62B56DE --------------
fail: Orleans.Runtime.Scheduler.OrleansTaskScheduler[101231]
      QueueWorkItem was called on a non-null context [SystemTarget: S127.0.0.1:11111:328962475*stg/13/0000000d@S0000000d] but there is no valid WorkItemGroup for it.
Unhandled exception. Orleans.Runtime.OrleansConfigurationException: Configuration for AzureTableStorageProvider Default is invalid. ConnectionString is not valid.
   at Orleans.Configuration.AzureTableGrainStorageOptionsValidator.ValidateConfiguration()
   at Orleans.Hosting.SiloHostedService.ValidateSystemConfiguration(IEnumerable`1 configurationValidators)
   at Orleans.Hosting.SiloHostedService..ctor(ISiloHost siloHost, IEnumerable`1 configurationValidators, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at SiloHost.Program.<Main>(String[] args)

**Comment by Serhii-Boiko-Dev** [comment]
If I disable .AddAzureTableGrainStorageAsDefault()
when I try to access the grain, I get an error

```
[15:17:38 ERR] An unhandled exception has occurred while executing the request.
Orleans.Runtime.OrleansException: Error creating activation for Grains.UserGrain. Message NewPlacement Request S127.0.0.1: 11111: 328968994 * cli / e9a8fe94 @ 817de99a-> S127.0.0.1: 11111: 328968994 * grn / ACAC55BE / 0127c6a8 @ 218bd3bc # 4:
  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
  ---> Orleans.Storage.BadGrainStorageConfigException: No default storage provider found loading grain type Grains.UserGrain.
```

**Comment by sergeybykov** [comment]
In the first code snippet I see that you configured options, including `options.ConnectionString`, for `AddAzureBlobGrainStorage`, but not for `AddAzureTableGrainStorageAsDefault()`.

**Comment by Serhii-Boiko-Dev** [comment]
Previously, I tried AzureTableGrainStorage and AzureBlobGrainStorage, due to inattention, I incorrectly assembled the code.
I tried in both configurations, now the code looks like this
```
public class Program
    {
        public static Task Main(string[] args)
        {
            bool TestConnectionBlobStorage(string connectionString, string containerName)
            {
                try
                {

                    BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
                    BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);

                    return containerClient.Exists();

                }
                catch (Exception)
                {
                    return false;
                }
            }

            if (TestConnectionBlobStorage(AppSettingsProvider.AzureStorageConnectionString, "state-store"))
                Console.WriteLine("Blob Connection passed");

            return new HostBuilder()
                .UseOrleans(builder =>
                {
                    builder
                        .UseLocalhostClustering()
                        .AddAzureBlobGrainStorage("state-store",
                                options =>
                                {
                                    options.UseJson = true;

                                    options.ConnectionString = AppSettingsProvider.AzureStorageConnectionString;
                                    options.ContainerName = "state-store";
                                })

                        .AddAzureBlobGrainStorageAsDefault()
                        .Configure<ClusterOptions>(options =>
                        {
                            options.ClusterId = "dev";
                            options.ServiceId = "UserProvider";
                        })
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(UserCollectionGrain).Assembly).WithReferences())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(UserGrain).Assembly).WithReferences());
                })
                .ConfigureServices(services =>
                {
                    services.Configure<ConsoleLifetimeOptions>(options =>
                    {
                        options.SuppressStatusMessages = true;
                    });
                })
                .ConfigureLogging(builder =>
                {
                    builder.AddConsole();
                })
                .RunConsoleAsync();
        }
    }
}

```
But I still get the error.

```
      -------------- Started silo S127.0.0.1:11111:329421552, ConsistentHashCode F1C8921C --------------
fail: Orleans.Runtime.Scheduler.OrleansTaskScheduler[101231]
      QueueWorkItem was called on a non-null context [SystemTarget: S127.0.0.1:11111:329421552*stg/13/0000000d@S0000000d] but there is no valid WorkItemGroup for it.
Unhandled exception. Orleans.Runtime.OrleansConfigurationException: Configuration for AzureBlobStorageOptions Default is invalid. ConnectionString is not valid.
   at Orleans.Configuration.AzureBlobStorageOptionsValidator.ValidateConfiguration()

```

**Comment by ReubenBond** [comment]
If you set a breakpoint where you set the ConnectionString, is the value for `AppSettingsProvider.AzureStorageConnectionString` correct?

**Comment by Serhii-Boiko-Dev** [comment]
To check the correctness of the connection string, I added a method _TestConnectionBlobStorage(string connectionString, string containerName)_, which is called before HostBuilder, and it returns the result - true.

Connection string value
`DefaultEndpointsProtocol=https;AccountName=dev;AccountKey=NwsDgmLsijGxAh2II3NRD3jNQp7XXXXXXXXXXXXXXXXXXXXXXXXXXXX=;EndpointSuffix=core.windows.net`

**Comment by sergeybykov** [comment]
How do you test that the connection string is set for both providers: "state-store" and the default one? I thought the issue was that the code wasn't configuring it for the default provider.
