### ISSUE TITLE
Error with generic grains

### ISSUE THREAD

**Issue by nathan5580** [dotnet/orleans#6604]
Hello everyone.

I'm trying to use a grain with "Object" as a parameter.
But when calling this grain, I get the error below :

`Could not load file or assembly 'Core.Gateway, Culture=neutral, PublicKeyToken=null'.`

Code example :
- Grain interface 
`Task<string> DoSomething(object o);`
- Grain implementation 
```
public Task<string> DoSomething(object o)
        {
            return Task.FromResult("Test result");
        }
```
- Grain call
```
var grain = _orleansClient.GetGrain<IMailGrain>(new Guid());

await grain.DoSomething(new { Name = "test" });
```

Everything works fine in this grain, but when implementing a generic object, an error is thrown.

Thank you in advance for your help.

**Comment by ReubenBond** [comment]
Is your assembly present on the caller and callee side?

**Comment by nathan5580** [comment]
Core.Gateway is my API and yes it implements the grain interface.

**Comment by ReubenBond** [comment]
Could you include the entire stack trace as well as your csproj?

**Comment by nathan5580** [comment]
Here's the stacktrace : 
```
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Core.Gateway.Controllers.Test.Testt() in C:\Users\NathanWilcké\source\repos\Orleans\core\Core.Gateway\Controllers\Test.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

And my API csproj :
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <UserSecretsId>XXXXX</UserSecretsId>
    <ApplicationInsightsResourceId>XXXXX</ApplicationInsightsResourceId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>Orkestramm.Gateway.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>Orkestramm.Gateway.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\SharedSettings.Development.json" Link="SharedSettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\SharedSettings.json" Link="SharedSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="9.0.0" />
    <PackageReference Include="ClosedXML" Version="0.95.3" />
    <PackageReference Include="ClosedXML.Extensions.WebApi" Version="0.2.1" />
    <PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="3.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="3.2.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="5.5.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core.GrainInterfaces\Core.GrainInterfaces.csproj" />
    <ProjectReference Include="..\..\core\Core.Grains\Core.Grains.csproj" />
    <ProjectReference Include="..\..\Core\Core.Mappers\Core.Mappers.csproj" />
    <ProjectReference Include="..\..\Shared\Orleans.Resources\Orleans.Resources.csproj" />
    <ProjectReference Include="..\..\Shared\Orleans.Utils\Orleans.UtilsStandard.csproj" />
    <ProjectReference Include="..\..\Shared\UtilsCommon\Orleans.UtilsCore.csproj" />
    <ProjectReference Include="..\Orkestramm.Database\Orkestramm.Database.csproj" />
    <ProjectReference Include="..\Orkestramm.GrainInterfaces\Orkestramm.GrainInterfaces.csproj" />
    <ProjectReference Include="..\Orkestramm.Grains\Orkestramm.Grains.csproj" />
    <ProjectReference Include="..\Orkestramm.Mappers\Orkestramm.Mappers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Properties\launchSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="Orkestramm.Gateway.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>


</Project>
```

csproj of my grain implementation if that can help :
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentEmail.Core" Version="2.8.0" />
    <PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="3.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="morelinq" Version="3.3.2" />
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="3.0.51" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core.GrainInterfaces\Core.GrainInterfaces.csproj" />
    <ProjectReference Include="..\..\Shared\Orleans.Utils\Orleans.UtilsStandard.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.GrainInterfaces\Shared.GrainInterfaces.csproj" />
    <ProjectReference Include="..\Orkestramm.Database\Orkestramm.Database.csproj" />
    <ProjectReference Include="..\Orkestramm.GrainInterfaces\Orkestramm.GrainInterfaces.csproj" />
    <ProjectReference Include="..\Orkestramm.Resources\Orkestramm.Resources.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Orkestramm.GrainInterfaces">
      <HintPath>..\Orkestramm.GrainInterfaces\bin\Debug\netstandard2.1\Orkestramm.GrainInterfaces.dll</HintPath>
    </Reference>
    <Reference Include="Orleans.UtilsStandard">
      <HintPath>..\..\Shared\Orleans.Utils\bin\Debug\netstandard2.1\Orleans.UtilsStandard.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
```

**Comment by ReubenBond** [comment]
I don't see Core.Gateway being referenced in either project

**Comment by nathan5580** [comment]
That's why I don't understand the problem either, Core.Gateway is my API and only needs to reference the grain interface.

The problem only appears when I call a grain method with an "`object`" as parameter

**Comment by ReubenBond** [comment]
What is the value that's being passed in as the `object`? Does it reference something from that assembly?

**Comment by nathan5580** [comment]
I passed a new object like this one ` new { Name = "test" }`, it does not reference anything

**Comment by ReubenBond** [comment]
C# translates that declaration into a class which lives in your client assembly, so it cannot be deserialized on the remote side (the silo). Object works, but anonymous objects like that cannot work. You should define your types in some shared assembly.

**Comment by nathan5580** [comment]
ah I thought anonymous objects worked.
I just tested and indeed it works fine with a shared object.
Thanks for your help

**Comment by ReubenBond** [comment]
The issue comes down to .NET using a nominal type system, rather than purely structural types. I think this kind of thing would be doable, but if you want dynamic objects like that, perhaps JSON types are your best bet, or some other semi-structured format
