### ISSUE TITLE
OrleansJsonSerializer failing with Reminders

### ISSUE THREAD

**Issue by awshrubsall** [dotnet/orleans#6628]
I am attempting to add OrleansJsonSerializer as our Serialization Provider, primarily for version-tolerant interface object models to be used alongside grain versioning, but whenever we use `Task<IGrainReminder> RegisterOrUpdateReminder(string reminderName, TimeSpan dueTime, TimeSpan period)` the Serializer throws an Exception:

<pre>Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type Orleans.ReminderData. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'GrainRef', line 1, position 67.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Orleans.Serialization.OrleansJsonSerializer.Deserialize(Type expectedType, IDeserializationContext context)
   at Orleans.Serialization.OrleansJsonSerializer.DeepCopy(Object source, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original, ICopyContext context)
   at Orleans.Serialization.SerializationManager.DeepCopy(Object original)
...</pre>

<pre>{
    "$id": "1",
    "$type": "Orleans.ReminderData, Orleans.Core",
    "GrainRef": {
        "$type": "Orleans.Runtime.GrainReference, Orleans.Core.Abstractions",
        "GrainId": "0000000000000000000000000000000103ffffff95b8b5b5",
        "GenericArguments": ""
    },
    "ReminderName": "TestReminder",
    "ETag": "W/"datetime'2020-07-02T02%3A24%3A08.757Z'""
}</pre>

We are using Orleans v3.0.2 but the same error also occurs when everything is upgraded to v3.2.0. This is happening with the AzureTableReminderService and InMemoryReminderService. Looking at our Azure table I see the reminder has been successfully saved, and ReceiveReminder triggers after the dueTime so I am not sure it is ever necessary to serialize this reminder as Json. 
Is there anything we can do to resolve this error?

As we really only wanted to use the OrleansJsonSerializer for user-defined classes in the first place without the added work required implementing Bond or Protobuf, is there a way to limit the supported types to within our business namespace or attribute?

**Comment by SebastianStehle** [comment]
You can inherit from the serializer and overwrite this method: https://github.com/dotnet/orleans/blob/00fac09a241526dbcad2e298ded71481578dc20b/src/Orleans.Core/Serialization/OrleansJsonSerializer.cs#L98

**Comment by awshrubsall** [comment]
Thanks that does work, I didn't think it was the intended use as IsSupportedType is not marked virtual, but we can hide it with the 'new' keyword. Is the OrleansJsonSerializer not meant to work out-of-the-box with Orleans.Runtime types?

**Comment by sergeybykov** [comment]
`IsSupportedType` is defined as part of `IExternalSerializer`. Can't you simply implement `IExternalSerializer` in your serializer class and return `true` for the types you want it to handle?
