### ISSUE TITLE
If grain maps to a valid silo, why not reset it?

### ISSUE THREAD

**Issue by Roytin** [dotnet/orleans#6649]
S10.42.2.237:21111:332152160 is already closed, but the application still visit it again and again.  
> Orleans.Runtime.OrleansException: Current directory at S10.42.4.104:21111:332319353 is not stable to perform the lookup for grainId *grn/24C7E6CB/00000000 (it maps to S10.42.2.237:21111:332152160, which is not a valid silo). Retry later.
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.LookupAsync(GrainId grainId, Int32 hopCount)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem`1.Execute()
   at Orleans.Runtime.Placement.RandomPlacementDirector.OnSelectActivation(PlacementStrategy strategy, GrainId target, IPlacementRuntime context)
   at Orleans.Runtime.Placement.PlacementDirectorsManager.SelectOrAddActivation(ActivationAddress sendingAddress, PlacementTarget targetGrain, IPlacementRuntime context, PlacementStrategy strategy)
   at Orleans.Runtime.Dispatcher.AddressMessageAsync(Message message, PlacementTarget target, PlacementStrategy strategy, ActivationAddress targetAddress)
   at Orleans.Runtime.Dispatcher.<>c__DisplayClass36_0.<<AsyncSendMessage>g__TransportMessageAferSending|0>d.MoveNext()

**Comment by sergeybykov** [comment]
What version of Orleans is this? Is the cluster is a stable state when this happens?

**Comment by Roytin** [comment]
The version of Orleans is 3.1.7. 
After I update my services on k8s with rolling-update, some grains map to the silo which is closed. There are two silos in my cluster, not all of them were wrong, I still can get the right result with 1/2 chance. When I restart the bad silo which is printing the error log, everything is back to OK.

**Comment by sergeybykov** [comment]
What clustering provider are you using?

Just a wild guess. I wonder if the rolling upgrade is actually happening properly with two silos when, presumably, each silo gets a new IP:Port identity upon upgrade. Do you see the silos actually immediately marking their old records in the membership table as `Dead` as part of their shutdown? If you can share the logs, that could shed some light on what's going on.

**Comment by Roytin** [comment]
I'm using Orleans.Providers.MongoDB. I lost the exception message when closing the old silo. It hasn't happened yet, I added logs and wait for it to happen.
