### ISSUE TITLE
GatewayConnectionListener taking long to shutdown in 3.2.1+

### ISSUE THREAD

**Issue by xontab** [dotnet/orleans#6654]
In 3.2.1, the `GatewayConnectionListener` is taking more than 5 sec to stop during a graceful shutdown and causing the host to timeout.

```
[08:35:16 INF] GatewayConnectionListener stopped in stage Active (20000) in 5017.0019 Milliseconds.
[08:35:16 INF] Stopping lifecycle stage Active (20000) took 5034.7544 Milliseconds
...
[08:35:16 INF] Orleans Silo stopped.
Unhandled exception. System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at KafkaPingPong.Orleans.Program.Main(String[] args) in /home/shaun/Dev/wasteland/KafkaPingPong/KafkaPingPong.Orleans/Program.cs:line 11
```

After some debugging, I noticed that there is a `Task.Delay` which is causing this delay during the shutdown process.

https://github.com/dotnet/orleans/blob/a1ea24789375a71244a6ba6ee3fb395fa65e2799/src/Orleans.Runtime/Networking/GatewayConnectionListener.cs#L111

Is the delay necessary? If so what do you suggest? Should we extend the `ShutdownTimeout` by 5 sec or is there another way to avoid it?

**Comment by veikkoeeva** [comment]
@xontab Good points. I wonder why is this five seconds there and depending on the reason if it ought to be made configurable (with logging). Also it may take time to close connections, so would it be useful to close them in parallel?

**Comment by benjaminpetit** [comment]
I think we should make it configurable. But you should also probably extend your `ShutdownTimeout` value. Is there any practical reason you don't set a value like 30 or even 60 seconds?

**Comment by xontab** [comment]
Yes, we can extend `ShutdownTimeout` but my main concern was that we didn't know if this behaviour is by design or not since this issue happens using the default `HostOptions` configuration and at first I thought it was a bug in the shutdown process.

Thanks for making it configurable.

**Comment by jdahl** [comment]
Is this only for client connections so silo to silo connections wont use this? 
As such if you have a system that only use inter silo communication (including inbedded clients) with no external client this delay isn't needed at all.

If that is the case adding a check if any call was done to StopSendingToGateway and only then apply the delay would be a good option to not delay shutdowns when there is no need.
