### ISSUE TITLE
Configuration for `DynamoDBStorageOptions` should support injectable AWSOptions and IAmazonDynamoDB

### ISSUE THREAD

**Issue by passuied** [dotnet/orleans#6671]
I'm an AWS user and thinking about using Orleans for one of our Production applications. 
I dug into the code of `Microsoft.Orleans.Persistence.DynamoDB` and was surprised to see that it only supports credentials through passing `AccessKey` and `SecretId`.
It doesn't support the abstraction provided by AWS: https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html which allows to configure and inject credentials and services...

The current implementation doesn't appear to be usable using credentials stored in a profile.

The implementation should be updated to be more usable.

Thanks in advance,

**Comment by jsteinich** [comment]
Injectable pieces could open up some new options for configuration, but it is already possible to use credentials other than `AccessKey` + `SecretId`.

The standard credential resolution flow applies if you don't pass either one of those.
https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html (Credential and Profile Resolution section)

I haven't tried using a profile, so you may have to fall back to setting an environment variable if DI config isn't working.

**Comment by passuied** [comment]
As far as I can tell there's no way to pass the profile name through DI so
I would assume the only way is via Environment variables...

Will give it a shot.

Any plans to have better injection or would you accept contributions in
this regard?

**Comment by jsteinich** [comment]
I don't believe there are any plans to alter how DynamoDB (or other AWS extensions) is configured.
Support for AWS is primarily community driven, so contributions are generally accepted.
While a 4.0 version is in progress, I imagine the team would prefer non-breaking changes.

**Comment by sergeybykov** [comment]
Contributions are very welcome!
>While a 4.0 version is in progress, I imagine the team would prefer non-breaking changes.

I'm not sure I understand what would be a breaking change here.

**Comment by jsteinich** [comment]
> I'm not sure I understand what would be a breaking change here.

Apologizes. What I really meant was that I think it would be good to make sure any changes made are done as optional configuration and that all current ways of configuring continue to work. I could see longer term maybe wanting to remove credentials / service specification from the current options classes and instead rely on more typical AWS configuration. However, there is a balance between making configuration of different backing services all very similar vs making them more tailored to how those services would typically be configured without Orleans.

**Comment by passuied** [comment]
Agreed!

Let me play a bit more with Orleans and I'll probably send a PR in a few
weeks ideally.

**Comment by passuied** [comment]
Passing the profile through environment variables doesn't seem to work.
I'm working in docker. I'm setting the environment as follows:
```
- "AWS_PROFILE=sandbox"
- "AWS_DEFAULT_REGION=us-west-2"
```

I have validated that I have access to AWS through my profile from AWS cli.

However when I start the silo, I get the following error:
```
Unhandled exception. Amazon.DynamoDBv2.AmazonDynamoDBException: The security token included in the request is invalid.
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Orleans.Clustering.DynamoDB.DynamoDBStorage.GetTableDescription(String tableName)
   at Orleans.Clustering.DynamoDB.DynamoDBStorage.InitializeTable(String tableName, List`1 keys, List`1 attributes, List`1 secondaryIndexes, String ttlAttributeName)
   at Orleans.Clustering.DynamoDB.DynamoDBMembershipTable.InitializeMembershipTable(Boolean tryInitTableVersion)
   at Orleans.Runtime.MembershipService.MembershipTableManager.Start()
   at Orleans.Runtime.MembershipService.MembershipTableManager.<>c__DisplayClass53_0.<<Orleans-ILifecycleParticipant<Orleans-Runtime-ISiloLifecycle>-Participate>g__OnRuntimeGrainServicesStart|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct)
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute()
   at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken)
   at Orleans.Hosting.SiloWrapper.StartAsync(CancellationToken cancellationToken)
   at Orleans.Hosting.SiloHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at OrleansPoc.SiloHost.Program.<Main>(String[] args)
```

I'm configuring  my silo as follows:
```
.UseOrleans(builder =>
                {
                    builder
                        .Configure<ClusterOptions>(options =>
                        {
                            options.ClusterId = "dev";
                            options.ServiceId = "OrleansPoc";
                        })
                        .UseDynamoDBClustering(options =>
                        {
                            options.Service = "https://dynamodb.us-west-2.amazonaws.com";
                            options.TableName = Constants.DynamoDBClusteringTableName;
                        })
                        .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(CompProcessorGrain).Assembly).WithReferences())
                        .AddMemoryGrainStorage(name: "UserStateStorage");
                })
```

Is it really supported?

**Comment by passuied** [comment]
Nevermind after reverse engineering the code, I saw you needed to set it up to the region name (e.g. us-west-2).
This is not really intuitive :(

**Comment by ReubenBond** [comment]
@passuied do you believe a PR could make it more intuitive?

**Comment by passuied** [comment]
Providing ability to inject `IAmazonDynamoDB` would help. 

The property name `Service` is misleading because it is sometimes used to pass the local dynamoDB, sometimes the region name...

It would be challenging to make it more intuitive without a breaking change tbh...

**Comment by jsteinich** [comment]
I'm not certain if this would work or not, but I was thinking we could maybe change things so that `IAmazonDynamoDB` is always injected. The `UseDynamo...` extensions methods could take care of an injecting an instance configured based on the current options class. That would be skipped if a user provided value was already present and a later provided user value would override it. One tricky area could be how to use a different config for storage, reminders, etc.

**Comment by jsteinich** [comment]
This would be a nice change.
