### ISSUE TITLE
Silo sometimes hangs on shutting down

### ISSUE THREAD

**Issue by krasin-ga** [dotnet/orleans#6674]
It continues to write these logs and does not shut down:

**[Warning] Waiting for 1 connections to terminate**

**[Info] Message was queued for sending after outbound queue was stopped: Request S10.0.0.68:11111:334221442*stg/13/0000000d@S0000000d->S10.0.0.67:11111:334222314*stg/10/0000000a@S0000000a 4817**

**[Error] OnClientRefreshTimer has thrown an exceptions. Message was queued for sending after outbound queue was stopped**

```
  at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at ***.Library.Retries.Orleans.RetryOutgoingGrainCallFilter.Invoke(IOutgoingGrainCallContext context) in /lvm0/teamcityagent/work/17306128d401e2b3/***.Library.Retries.Orleans/RetryOutgoingGrainCallFilter.cs:line 76
   at ***.Library.Retries.Orleans.RetryOutgoingGrainCallFilter.Invoke(IOutgoingGrainCallContext context) in /lvm0/teamcityagent/work/17306128d401e2b3/***.Library.Retries.Orleans/RetryOutgoingGrainCallFilter.cs:line 76
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.GrainReferenceRuntime.InvokeWithFilters(GrainReference reference, InvokeMethodRequest request, InvokeMethodOptions options)
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.RegisterAsync(ActivationAddress address, Boolean singleActivation, Int32 hopCount)
   at Orleans.Internal.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message)
```

**[Error] Directory.RegisterAsync S10.0.0.68:11111:334221442*cli/086b1b85@8bec91af failed.**

```
 at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at ***.Library.Retries.Orleans.RetryOutgoingGrainCallFilter.Invoke(IOutgoingGrainCallContext context) in /lvm0/teamcityagent/work/17306128d401e2b3/***.Library.Retries.Orleans/RetryOutgoingGrainCallFilter.cs:line 76
   at ***.Library.Retries.Orleans.RetryOutgoingGrainCallFilter.Invoke(IOutgoingGrainCallContext context) in /lvm0/teamcityagent/work/17306128d401e2b3/***.Library.Retries.Orleans/RetryOutgoingGrainCallFilter.cs:line 76
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.GrainReferenceRuntime.InvokeWithFilters(GrainReference reference, InvokeMethodRequest request, InvokeMethodOptions options)
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.RegisterAsync(ActivationAddress address, Boolean singleActivation, Int32 hopCount)
   at Orleans.Internal.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message)

```

**[Error] Message was queued for sending after outbound queue was stopped: Unrecoverable Rejection**
```
Message was queued for sending after outbound queue was stopped: Unrecoverable Rejection (info:  Orleans.Runtime.OrleansMessageRejectionException: Message was queued for sending after outbound queue was stopped
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at ***.Library.Retries.Orleans.RetryOutgoingGrainCallFilter.Invoke(IOutgoingGrainCallContext context) in /lvm0/teamcityagent/work/17306128d401e2b3/***.Library.Retries.Orleans/RetryOutgoingGrainCallFilter.cs:line 76
   at ***.Library.Retries.Orleans.RetryOutgoingGrainCallFilter.Invoke(IOutgoingGrainCallContext context) in /lvm0/teamcityagent/work/17306128d401e2b3/***.Library.Retries.Orleans/RetryOutgoingGrainCallFilter.cs:line 76
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.GrainReferenceRuntime.InvokeWithFilters(GrainReference reference, InvokeMethodRequest request, InvokeMethodOptions options)
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.LookupAsync(GrainId grainId, Int32 hopCount)
   at Orleans.Runtime.GrainDirectory.DhtGrainLocator.Lookup(GrainId grainId)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem`1.Execute()
   at Orleans.Runtime.Placement.RandomPlacementDirector.OnSelectActivation(PlacementStrategy strategy, GrainId target, IPlacementRuntime context)
   at Orleans.Runtime.Placement.PlacementDirectorsManager.SelectOrAddActivation(ActivationAddress sendingAddress, PlacementTarget targetGrain, IPlacementRuntime context, PlacementStrategy strategy)
   at Orleans.Runtime.Dispatcher.AddressMessageAsync(Message message, PlacementTarget target, PlacementStrategy strategy, ActivationAddress targetAddress)
   at Orleans.Runtime.Dispatcher.<>c__DisplayClass38_0.<<AsyncSendMessage>g__TransportMessageAferSending|0>d.MoveNext()) Response S10.0.0.68:11111:334221442*grn/RefreshmentGrain/0000188d->S10.0.0.68:11111:334221442*cli/6585b086@074390b6 #48140
```
![image](https://user-images.githubusercontent.com/11534678/89270293-d1d87c00-d643-11ea-961c-6f0e60a41557.png)

![image](https://user-images.githubusercontent.com/11534678/89270254-c2f1c980-d643-11ea-9a8a-103cfe8dceb0.png)

Configuration: cluster of two nodes, Orleans version: 3.2.2

**Comment by sergeybykov** [comment]
>***.Library.Retries.Orleans.RetryOutgoingGrainCallFilter.Invoke

Is this something like Polly that keeps retrying? I wonder if that's the culprit.

**Comment by krasin-ga** [comment]
Yes, [it's like Polly](
https://gist.github.com/krasin-ga/41a676bca04f009e2a5e40ee87b293e8). On silo it uses the IHostApplicationLifetime.ApplicationStopping CancelationToken to stop retrying on exceptions when silo is shutting down, so it just calls Invoke() on IOutgoingGrainCallContext. 

I don't know if it's a coincidence or not, but after setting GatewayListRefreshPeriod  (we are using ADO.NET clustering) to 1 second i wasn't able to reproduce this issue.

I'll check it again next week.

**Comment by OracPrime** [comment]
We're seeing something very similar, but in a unit test environment.  We haven't got any retrying going on, but we're finding some times the Cluster.StopAllSilos call doesn't complete in any sensible time frame.  When it does this, it *seems* to reliably time out somewhere around 5 minutes.  This is using TestHostCluster.

**Comment by krasin-ga** [comment]
With default value of GatewayListRefreshPeriod I still can't reproduce the issue. Since only this parameter has been changed, I have no idea why the issue is not reproducing anymore.

**Comment by ReubenBond** [comment]
@OracPrime could you share a memory dump when that happens? I can help debug it.
