### ISSUE TITLE
InvalidOperationException: "Insufficient data present in buffer"

### ISSUE THREAD

**Issue by krasin-ga** [dotnet/orleans#6702]
Exception was thrown after restart of silo.
Orleans version: 3.2.2
``` 
Exception reading message NewPlacement Request S10.10.0.162:11111:335124933*grn/xxx/0000014b@6aa88fbc->S10.10.0.161:11111:335545517*grn/yyy/a1699f83@f43ad78c #118356673 from remote endpoint 10.10.0.162:11111 to local endpoint 10.10.0.161:53217: System.InvalidOperationException: Insufficient data present in buffer.
   at Orleans.Serialization.BinaryTokenStreamReader2.ThrowInsufficientData()
   at Orleans.Serialization.BinaryTokenStreamReader2.<ReadUInt32>g__ReadSlower|23_0()
   at Orleans.Serialization.BinaryTokenStreamReader2.ReadString()
   at BeePublicationSupplyDeserializer(Type , IDeserializationContext )
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Serialization.BuiltInTypes.DeserializeInvokeMethodRequest(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value)
   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message)
   at Orleans.Runtime.Messaging.Connection.ProcessIncoming()
```

**Comment by SebastianStehle** [comment]
I had this problem with a custom serializer.

**Comment by ReubenBond** [comment]
Yes, this is most likely due to a change in the `BeePublicationSupply` type that is not backwards compatible

**Comment by krasin-ga** [comment]
Thanks! Indeed, there was a change in this class. 
But should adding a property break backward compatibility?

![image](https://user-images.githubusercontent.com/11534678/90863555-eb91f700-e397-11ea-8f12-21252725d3ba.png)
