### ISSUE TITLE
Client freezes when catching an exception the type of which is not known on the client-side

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#6729]
Used version is Orleans 3.2.2.

The problem: When I **throw an exception from a grain**, and the **type of this exception is not known on the client-side** (since the exception type is defined in the grain implementation assembly), the **client freezes under certain circumstances**.

It is a known problem that the client throws a `SerializationException` since it cannot deserialize the exception - that's okay so far.

But after that, further grain calls are freezing and do not return - **but only if the stack trace exceeds a specific length**.

How to reproduce this issue? First, download the [Hello World](https://github.com/dotnet/orleans/tree/master/Samples/3.0/HelloWorld) project. Then update to version 3.2.2 since I cannot say if this issue also exists in older versions.

Modify the following two source files:

`HelloGrain.cs`

```csharp
using HelloWorld.Interfaces;
using Microsoft.Extensions.Logging;
using Orleans;
using System;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace HelloWorld.Grains
{
  /// <summary>
  ///   Orleans grain implementation class HelloGrain.
  /// </summary>
  public class HelloGrain : Grain, IHello
  {
    private readonly ILogger logger;

    public HelloGrain(ILogger<HelloGrain> logger)
    {
      this.logger = logger;
    }

    public Task<string> SayHello(string greeting)
    {
      if (greeting?.EndsWith("!", StringComparison.Ordinal) ?? false)
      {
        Recurse();
      }

      this.logger.LogInformation($"SayHello message received: greeting = '{greeting}'");
      return Task.FromResult($"You said: '{greeting}', I say: Hello!");
    }

    private static void Recurse(int i = 0)
    {
      if (i < 100)
      {
        Recurse(i + 1);
      }

      throw new PrivateException("OMG!");
    }
  }

  [Serializable]
  public class PrivateException : Exception
  {
    public PrivateException()
    {
    }

    public PrivateException(string message) : base(message)
    {
    }

    public PrivateException(string message, Exception inner) : base(message, inner)
    {
    }

    protected PrivateException(SerializationInfo info, StreamingContext context) : base(info, context)
    {
    }
  }
}
```

***

`HelloWorldClientHostedService.cs`

```csharp
using HelloWorld.Interfaces;
using Microsoft.Extensions.Hosting;
using Orleans;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace OrleansClient
{
  public class HelloWorldClientHostedService : IHostedService
  {
    private readonly IClusterClient client;

    public HelloWorldClientHostedService(IClusterClient client)
    {
      this.client = client;
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
      // example of calling grains from the initialized client
      var friend = this.client.GetGrain<IHello>(0);

      string response;

      try
      {
        response = await friend.SayHello("Good morning, my friend!");
        Console.WriteLine($"{response}");
      }
      catch (Exception exc)
      {
        Console.WriteLine(exc);
      }

      response = await friend.SayHello("How are you?");
      Console.WriteLine($"{response}");

      Console.WriteLine();
      Console.WriteLine("Bye!");
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
  }
}
```

When you run the project the client outputs the following:

```
warn: Orleans.Networking[0]
      Exception reading message Response S127.0.0.1:30000:0*grn/F057335D/00000000@c6014e99->*cli/9ca77f85@65a001be #4 from remote endpoint 127.0.0.1:30000 to lo
cal endpoint 127.0.0.1:49254: System.Runtime.Serialization.SerializationException: Unable to find assembly 'HelloWorld.Grains, Version=1.0.0.0, Culture=neutral,
 PublicKeyToken=null'.
         at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
         at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
         at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] t
ypeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
         at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
         at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
         at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
         at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
         at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
         at Orleans.Serialization.BinaryFormatterSerializer.Deserialize(Type expectedType, IDeserializationContext context) in D:\build\agent\_work\24\s\src\Orl
eans.Core\Serialization\BinaryFormatterSerializer.cs:line 88
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader read
er) in D:\build\agent\_work\24\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1296
         at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\24\s\src\Orleans
.Core\Serialization\SerializationManager.cs:line 1233
         at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context) in D:\build\agent\_work\24\s\src\Orlea
ns.Core\Serialization\BuiltInTypes.cs:line 2135
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader read
er) in D:\build\agent\_work\24\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1334
         at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value) in D:\build\agent\_work\24\s\src\Orl
eans.Core\Messaging\MessageSerializer.cs:line 151
         at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message) in D:\build\agent\_work\24\s\src\Orleans.Core\Messa
ging\MessageSerializer.cs:line 77
         at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in D:\build\agent\_work\24\s\src\Orleans.Core\Networking\Connection.cs:line 259
System.Runtime.Serialization.SerializationException: Unable to find assembly 'HelloWorld.Grains, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInf
ormationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at Orleans.Serialization.BinaryFormatterSerializer.Deserialize(Type expectedType, IDeserializationContext context) in D:\build\agent\_work\24\s\src\Orleans.C
ore\Serialization\BinaryFormatterSerializer.cs:line 88
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in
 D:\build\agent\_work\24\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1296
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\24\s\src\Orleans.Core\
Serialization\SerializationManager.cs:line 1233
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context) in D:\build\agent\_work\24\s\src\Orleans.Cor
e\Serialization\BuiltInTypes.cs:line 2135
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in
 D:\build\agent\_work\24\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1334
   at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value) in D:\build\agent\_work\24\s\src\Orleans.C
ore\Messaging\MessageSerializer.cs:line 151
   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message) in D:\build\agent\_work\24\s\src\Orleans.Core\Messaging\M
essageSerializer.cs:line 77
   at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in D:\build\agent\_work\24\s\src\Orleans.Core\Networking\Connection.cs:line 259
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExten
sions.cs:line 101
   at OrleansClient.HelloWorldClientHostedService.StartAsync(CancellationToken cancellationToken) in D:\IcoDevSandbox\temp\OrleansNonSerializableExceptionBug\sr
c\OrleansClient\HelloWorldClientHostedService.cs:line 28
```

The client gets stuck and is not executing the line `Console.WriteLine("Bye!");`.

Now things get esoteric: just change one line in the method `HelloGrain.Recurse` from

```chsarp
if (i < 100)
```

to

```chsarp
if (i < 1)
```

Now everythings works fine and the client's output looks like this:

```
warn: Orleans.Networking[0]
      Exception reading message Response S127.0.0.1:30000:0*grn/F057335D/00000000@23ef52a2->*cli/0a35b993@dcc4bab7 #4 from remote endpoint 127.0.0.1:30000 to lo
cal endpoint 127.0.0.1:49764: System.Runtime.Serialization.SerializationException: Unable to find assembly 'HelloWorld.Grains, Version=1.0.0.0, Culture=neutral,
 PublicKeyToken=null'.
         at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
         at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
         at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] t
ypeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
         at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
         at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
         at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
         at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
         at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
         at Orleans.Serialization.BinaryFormatterSerializer.Deserialize(Type expectedType, IDeserializationContext context) in D:\build\agent\_work\24\s\src\Orl
eans.Core\Serialization\BinaryFormatterSerializer.cs:line 88
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader read
er) in D:\build\agent\_work\24\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1296
         at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\24\s\src\Orleans
.Core\Serialization\SerializationManager.cs:line 1233
         at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context) in D:\build\agent\_work\24\s\src\Orlea
ns.Core\Serialization\BuiltInTypes.cs:line 2135
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader read
er) in D:\build\agent\_work\24\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1334
         at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value) in D:\build\agent\_work\24\s\src\Orl
eans.Core\Messaging\MessageSerializer.cs:line 151
         at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message) in D:\build\agent\_work\24\s\src\Orleans.Core\Messa
ging\MessageSerializer.cs:line 77
         at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in D:\build\agent\_work\24\s\src\Orleans.Core\Networking\Connection.cs:line 259
System.Runtime.Serialization.SerializationException: Unable to find assembly 'HelloWorld.Grains, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInf
ormationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at Orleans.Serialization.BinaryFormatterSerializer.Deserialize(Type expectedType, IDeserializationContext context) in D:\build\agent\_work\24\s\src\Orleans.C
ore\Serialization\BinaryFormatterSerializer.cs:line 88
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in
 D:\build\agent\_work\24\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1296
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\build\agent\_work\24\s\src\Orleans.Core\
Serialization\SerializationManager.cs:line 1233
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context) in D:\build\agent\_work\24\s\src\Orleans.Cor
e\Serialization\BuiltInTypes.cs:line 2135
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in
 D:\build\agent\_work\24\s\src\Orleans.Core\Serialization\SerializationManager.cs:line 1334
   at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value) in D:\build\agent\_work\24\s\src\Orleans.C
ore\Messaging\MessageSerializer.cs:line 151
   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message) in D:\build\agent\_work\24\s\src\Orleans.Core\Messaging\M
essageSerializer.cs:line 77
   at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in D:\build\agent\_work\24\s\src\Orleans.Core\Networking\Connection.cs:line 259
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExten
sions.cs:line 101
   at OrleansClient.HelloWorldClientHostedService.StartAsync(CancellationToken cancellationToken) in D:\IcoDevSandbox\temp\OrleansNonSerializableExceptionBug\sr
c\OrleansClient\HelloWorldClientHostedService.cs:line 28
You said: 'How are you?', I say: Hello!

Bye!
```

Any idea where this behavior comes from?

Currently I work around this issue by wrapping the message of exceptions that are unknown to the client into a plain .NET `Exception`. But this bug caused me some headache since it took me a while to figure out the circumstances to reproduce it.

**Comment by peter-perot** [comment]
To make things easier:

[OrleansNonDeserializableExceptionFreezeBug.zip](https://github.com/dotnet/orleans/files/5169325/OrleansNonDeserializableExceptionFreezeBug.zip)

**Comment by peter-perot** [comment]
@ReubenBond Any idea what causes this issue? Maybe a race condition? And why does it only occur at a certain size of the exception call stack?

**Comment by peter-perot** [comment]
Issue is still existing.

**Comment by SebastianStehle** [comment]
Sounds urgent to me, please do not close, dear bot ;)
