### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#6734]
I just got a super weird error and I want to report it before I forget it:

My application is running in kubernetes. I made a new deployment and got the following exception:

```

"Lifecycle start canceled due to errors at stage 1999: Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Orleans.Networking.Shared.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Orleans.Networking.Shared.SocketConnectionListener.Bind()
   at Orleans.Networking.Shared.SocketConnectionListenerFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Orleans.Runtime.Messaging.ConnectionListener.BindAsync(CancellationToken cancellationToken)
   at Orleans.Runtime.Messaging.GatewayConnectionListener.OnRuntimeInitializeStart(CancellationToken cancellationToken)
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct)
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)"
```

It is the first time that this happened and after 4 restart it has been solved automatically but it is weird. I assume that somehow the previous socket was hanging on the host or so. No idea what exactly happened but it is strange.

**Comment by ReubenBond** [comment]
Interesting, which version of Orleans is this? I assume it's pre-3.2.2, in which we took a slight change to allow address reuse: https://github.com/dotnet/orleans/releases/tag/v3.2.2

It happens because of some quirks of TCP, where the OS will block rebinding to recently closed sockets for a short period (typically 1 or 2 minutes) to reduce the likelihood of receiving packets intended for the previously bound socket. The PR linked from the release notes explains some more.

**Comment by SebastianStehle** [comment]
Yes, it is 3.2.0....I have not changed anything except a UI fix in my code. But I thought this cannot happen in Docker.
