### ISSUE TITLE
Forbidden to access K8s cluster info

### ISSUE THREAD

**Issue by freever** [dotnet/orleans#6759]
Hi guys

I am trying to use Microsoft.Orleans.Hosting.Kubernetes Version=3.3.0-rc2 to help manage my deployments on k8s, but when the silo pods start up they are throwing the following exception:

```
> fail: Orleans.Runtime.SiloLifecycleSubject[100450]
      Lifecycle start canceled due to errors at stage 8100: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Forbidden'
         at k8s.Kubernetes.ListNamespacedPodWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
         at k8s.KubernetesExtensions.ListNamespacedPodAsync(IKubernetes operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, CancellationToken cancellationToken)
         at Orleans.Hosting.Kubernetes.KubernetesClusterAgent.OnRuntimeInitializeStart(CancellationToken cancellation)
         at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct)
         at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
fail: Orleans.Runtime.Silo[100439]
      Exception during Silo.Start
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Forbidden'
   at k8s.Kubernetes.ListNamespacedPodWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ListNamespacedPodAsync(IKubernetes operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, CancellationToken cancellationToken)
   at Orleans.Hosting.Kubernetes.KubernetesClusterAgent.OnRuntimeInitializeStart(CancellationToken cancellation)
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct)
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute()
   at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken)
```

If I comment out the `siloBuilder.UseKubernetesHosting();` part of my setup then my cluster functions perfectly with multiple nodes connecting up and clients in the same deployment able to connect. 

I believe I have followed all the instructions here: https://github.com/dotnet/orleans/pull/6707

I have set up the template labels:
```yaml
  template:
    metadata:
      labels:
        serviceId: moonbase-service 
        clusterId: moonbase-cluster
```

and ENV variables
```yaml
        - name: ORLEANS_SERVICE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['serviceId']
        - name: ORLEANS_CLUSTER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['clusterId']
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

I thought it might be a namespace thing, but all my k8s resources are in the default namespace. 

Any ideas?

**Comment by ReubenBond** [comment]
My first thought would be that you need a role binding, as described in this comment: https://github.com/dotnet/orleans/pull/6707#issuecomment-688893171

**Comment by SebastianStehle** [comment]
Can this extension run optionally? I don't know how my app is deployed and I would like to enable it by default and if it works good, otherwise it just logs the errors and continues.

**Comment by freever** [comment]
@ReubenBond thanks that seems to have done the business - didn't know I needed it, but I needed it.

Now I am getting a different problem with connections dropping all the time forcing my pds to restart 

```Exception while processing messages from remote endpoint 10.2.1.169:37956: Microsoft.AspNetCore.Connections.ConnectionResetException: Connection reset by peer```

I'll close this issues since the RBAC solved it, and post a new one if I have more enlightening information to share.

**Comment by LiamMorrow** [comment]
@SebastianStehle I have something like this where I configure my siloHost:
```
            if (configuration.GetValue("OrleansEnvironment", "k8s") == "k8s")
            {
                builder.UseKubernetesHosting();
            }
```
where configuration is the dotnet core IConfiguration that is injected.  Let's me set where it is running.  Alternatively you could check for an environment variable

**Comment by ReubenBond** [comment]
You can also call `k8s.KubernetesClientConfiguration.IsInCluster()` to check. See: https://github.com/kubernetes-client/csharp/blob/e38525c13bae1c2e40feac6906ba326ff6cd1e2c/src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs#L19
