### ISSUE TITLE
AWS SQS Stream - Object not set error

### ISSUE THREAD

**Issue by sjbthfc2** [dotnet/orleans#6781]
Hi,

I am tryng oi use the Microsoft.Orleans.Streaming.SQS but I am getting an 'Object not set' exception when calling OnNextAsync(message) from my Web API Controller as it tries to put a message in the Stream. I am using SQS on AWS and setting up the provider like so:

`                    .AddSqsStreams("OrleansStream", options =>
                    {
                        options.ConnectionString = "<queueurl>/OrleansStream";
                    })
`

I get the Stream in my Controller like so:

`            var streamProvider = GetStreamProvider("OrleansStream");
            //Get the reference to a stream
            var stream = streamProvider.GetStream<Group>(id, "GroupSettings");`

Then try and send the message:

`await stream.OnNextAsync(message);`

And the object not set exception is throw at:

```
   at OrleansAWSUtils.Storage.SQSStorage.CreateClient()
   at OrleansAWSUtils.Storage.SQSStorage..ctor(ILoggerFactory loggerFactory, String queueName, String connectionString, String serviceId)
   at OrleansAWSUtils.Streams.SQSAdapter.<QueueMessageBatchAsync>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

The SQS queue is working fine from the AWS console, am I not setting this up correctly, there isn't any documentation on doing for this for SQS so took a best guess from the SMS sample and looking at the SQS Orleans code.

Thanks

**Comment by sjbthfc2** [comment]
Also see the exception during Silo build:

`fail: Orleans.Streams.OrleansStream[103302]
      Exception while calling IQueueAdapter.CreateNewReceiver.
System.NullReferenceException: Object reference not set to an instance of an object.
   at OrleansAWSUtils.Storage.SQSStorage.CreateClient()
   at OrleansAWSUtils.Storage.SQSStorage..ctor(ILoggerFactory loggerFactory, String queueName, String connectionString, String serviceId)
   at OrleansAWSUtils.Streams.SQSAdapterReceiver.Create(SerializationManager serializationManager, ILoggerFactory loggerFactory, QueueId queueId, String dataConnectionString, String serviceId)
   at OrleansAWSUtils.Streams.SQSAdapter.CreateReceiver(QueueId queueId)
   at Orleans.Streams.PersistentStreamPullingAgent.InitializeInternal(IQueueAdapter qAdapter, IQueueAdapterCache queueAdapterCache, IStreamFailureHandler failureHandler)`

**Comment by sjbthfc2** [comment]
Is it just the URL to the queue? that is all you seem to get to connect to a SQS queue and seems to be OK, just copied it from the AWS Console.

**Comment by sjbthfc2** [comment]
I just put `<queueurl>` above to redact the real URL.

**Comment by benjaminpetit** [comment]
I never used SQS so I am not 100% sure on how the connection string looks like, but our code expects something like this: ``Service=<some_url>;SecretKey=<some_key>;AccessKey=<some_access_key>``. The `SecretKey` and `AccessKey` part may be optional if you use implicit auth.

**Comment by sjbthfc2** [comment]
Hi @benjaminpetit, thanks for your help on this. I have added the AWS keys to the connection string but now I am getting an "Object reference not set" error when I try and call `GetStream()` on the StreamProvider.

My builder code builds the stream provider as below:

`
.AddSqsStreams("SMSProvider", options =>`
`{`
         `options.ConnectionString = "Service=https://sqs.us-east-2.amazonaws.com/<aws-sqs-queue>;SecretKey=xxxxxxxxxxxxxxxxxxx;AccessKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxx";`
                    `})`
       `.AddDynamoDBGrainStorage(name: "PubSubStore",`
                    `options =>`
                    `{`
                     `   SiloHelper.CreateDynamoDbStorageOption(options, "PubSubStore");`
                    `})`

Then when I try and retrieve a Stream:

`var stream = streamProvider.GetStream<Group>(Guid.Parse(allowedDevice), "GroupSettings");`

I get the object not set error thrown with the the following stack trace:

   at Orleans.Providers.Streams.Common.PersistentStreamProvider.get_IsRewindable()
   at Orleans.Providers.Streams.Common.PersistentStreamProvider.<>c__DisplayClass22_0`1.<GetStream>b__0()
   at Orleans.Streams.StreamDirectory.<>c__DisplayClass2_0`1.<GetOrAddStream>b__0(StreamId _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orleans.Streams.StreamDirectory.GetOrAddStream[T](StreamId streamId, Func`1 streamCreator)
   at Orleans.Providers.Streams.Common.PersistentStreamProvider.GetStream[T](Guid id, String streamNamespace)

**Comment by wilbit** [comment]
> I never used SQS so I am not 100% sure on how the connection string looks like, but our code expects something like this: `Service=<some_url>;SecretKey=<some_key>;AccessKey=<some_access_key>`. The `SecretKey` and `AccessKey` part may be optional if you use implicit auth.

`<some_url>` is AWS region, like `us-east-2`.
`SecretKey` and `AccessKey` are not required, permissions must be set by IAM policies and roles.
Currently, SQS provider does not support FIFO queues, which is a road block for our company's project. I guess I have to fix it if nobody did it last year. I see, actually, that nobody touched SQS provider for years, that's sad 😞...

**Comment by benjaminpetit** [comment]
If you could do a PR with that, we would be happy to review it!
