### ISSUE TITLE
"Forwarding failed" on concurrent invocation of stateless worker grain

### ISSUE THREAD

**Issue by EdeMeijer** [dotnet/orleans#6795]
We encountered an error in our production application where a grain call failed because: `Cannot enqueue message to invalid activation`. It was a grain call to a stateless worker grain with max activations = 1, and marked as [Reentrant]. It basically serves as a silo-local cache grain for some data. I was under the assumption that a call like this should never fail. The logs tell that it tried to forward the request to a new activation twice, which all failed.

```
17:22:52.009 | WARN | T694 | Orleans.Runtime.ActivationData | Cannot enqueue message to invalid activation [Activation: S10.100.10.188:657:340639501*grn/1F80D60C/4bed8207b3facb162eada762a8ad2983030000001f80d60c-0xCA924F6B@06d72e8f #GrainType=Netwerkplek.Cloud.Orleans.Flow.FlowRouting.FlowRoutingGrain Placement=StatelessWorkerPlacement State=Invalid NonReentrancyQueueSize=0 EnqueuedOnDispatcher=0 InFlightCount=0 NumRunning=0 IdlenessTimeSpan=737715.17:22:52.0089780 CollectionAgeLimit=01:00:00] : NewPlacement Request S10.100.10.188:657:340639501*grn/FF3499E2/00000000@9a7ae8b8->S10.100.10.188:657:340639501*grn/1F80D60C/a8ad2983@06d72e8f #1273118
17:22:52.009 | WARN | T306 | Orleans.Runtime.ActivationData | Cannot enqueue message to invalid activation [Activation: S10.100.10.188:657:340639501*grn/1F80D60C/4bed8207b3facb162eada762a8ad2983030000001f80d60c-0xCA924F6B@ef135f9e #GrainType=Netwerkplek.Cloud.Orleans.Flow.FlowRouting.FlowRoutingGrain Placement=StatelessWorkerPlacement State=Invalid NonReentrancyQueueSize=0 EnqueuedOnDispatcher=0 InFlightCount=0 NumRunning=0 IdlenessTimeSpan=737715.17:22:52.0089862 CollectionAgeLimit=01:00:00] : NewPlacement Request S10.100.10.188:657:340639501*grn/FF3499E2/00000000@9a7ae8b8->S10.100.10.188:657:340639501*grn/1F80D60C/a8ad2983@ef135f9e #1273117
17:22:52.009 | WARN | T694 | Orleans.Runtime.ActivationData | Cannot enqueue message to invalid activation [Activation: S10.100.10.188:657:340639501*grn/1F80D60C/4bed8207b3facb162eada762a8ad2983030000001f80d60c-0xCA924F6B@5d8b86b4 #GrainType=Netwerkplek.Cloud.Orleans.Flow.FlowRouting.FlowRoutingGrain Placement=StatelessWorkerPlacement State=Invalid NonReentrancyQueueSize=0 EnqueuedOnDispatcher=0 InFlightCount=0 NumRunning=0 IdlenessTimeSpan=737715.17:22:52.0096354 CollectionAgeLimit=01:00:00] : NewPlacement Request S10.100.10.188:657:340639501*grn/FF3499E2/00000000@9a7ae8b8->S10.100.10.188:657:340639501*grn/1F80D60C/a8ad2983@5d8b86b4 #1273118[ForwardCount=2]
17:22:52.009 | WARN | T694 | Orleans.Messaging | Failed to forward message NewPlacement Request S10.100.10.188:657:340639501*grn/FF3499E2/00000000@9a7ae8b8->S10.100.10.188:657:340639501*grn/1F80D60C/a8ad2983@5d8b86b4 #1273118[ForwardCount=2] from S10.100.10.188:657:340639501*grn/1F80D60C/a8ad2983@5d8b86b4 to S10.100.10.188:657:340639501*grn/1F80D60C/a8ad2983@5d8b86b4 after EnqueueRequest. Attempt 2
17:22:52.016 | EROR | T690 | Netwerkplek.Cloud.Orleans.Flow.Executor.FlowExecutorGrain | Error while executing flow node Orleans.Runtime.OrleansMessageRejectionException: Forwarding failed: tried to forward message NewPlacement Request S10.100.10.188:657:340639501*grn/FF3499E2/00000000@9a7ae8b8->S10.100.10.188:657:340639501*grn/1F80D60C/a8ad2983@5d8b86b4 #1273118[ForwardCount=2] for 2 times after EnqueueRequest to invalid activation. Rejecting now.
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Netwerkplek.Cloud.Tools.Async.Tasks.When[A,B,C](Task`1 Ta, Task`1 Tb, Task`1 Tc) in /app/Cloud/Tools/Async/Tasks.cs:line 23
   at Netwerkplek.Cloud.Orleans.Flow.Executor.Commands.MacroCommand.ExecuteAsync(NodeCommandContext Ctx) in /app/Cloud/Orleans/Flow/Executor/Commands/MacroCommand.cs:line 67
   at Netwerkplek.Cloud.Orleans.Flow.Executor.FlowExecutorGrain.ExecuteAsync(BoundFlowNode BoundNode, FlowEvent EventData) in /app/Cloud/Orleans/Flow/Executor/FlowExecutorGrain.cs
```

**Comment by EdeMeijer** [comment]
I found the problem and will submit a PR in a minute
