### ISSUE TITLE
Failed to refresh membership table, will retry shortly: Orleans.Runtime.OrleansException: Failed to read Azure storage table OrleansSiloInstances: The operation was canceled

### ISSUE THREAD

**Issue by clement128** [dotnet/orleans#6828]
Hi there,

I am running orleans on google cloud kubernetes. somehow I saw this error (not always happen but randomly):

```log
[04:19:06 ERR] Failed to refresh membership table, will retry shortly: Orleans.Runtime.OrleansException: Failed to read Azure storage table OrleansSiloInstances: The operation was canceled.
...
at Orleans.Internal.AsyncExecutorWithRetries.ExecuteWithRetriesHelper[T](Func`2 function, Int32 callCounter, Int32 maxNumSuccessTries, Int32 maxNumErrorTries, TimeSpan maxExecutionTime, DateTime startExecutionTime, Func`3 retryValueFilter, Func`3 retryExceptionFilter, IBackoffProvider onSuccessBackOff, IBackoffProvider onErrorBackOff
at Orleans.Internal.AsyncExecutorWithRetries.ExecuteWithRetriesHelper[T](Func`2 function, Int32 callCounter, Int32 maxNumSuccessTries, Int32 maxNumErrorTries, TimeSpan maxExecutionTime, DateTime startExecutionTime, Func`3 retryValueFilter, Func`3 retryExceptionFilter, IBackoffProvider onSuccessBackOff, IBackoffProvider onErrorBackOff)
  at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.ReadTableEntriesAndEtagsAsync(String filter)
Request Information
RequestID:
RequestDate:
StatusMessage:
ErrorCode:
--- End of inner exception stack trace ---
at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.ReadTableEntriesAndEtagsAsync(String filter)
at Orleans.AzureUtils.OrleansSiloInstanceManager.FindAllSiloEntries()
at Orleans.Runtime.MembershipService.AzureBasedMembershipTable.ReadAll()
at Orleans.Runtime.MembershipService.MembershipTableManager.RefreshInternal(Boolean requireCleanup)
at Orleans.Runtime.MembershipService.MembershipTableManager.Refresh()
at Orleans.Runtime.MembershipService.MembershipTableManager.PeriodicallyRefreshMembershipTable()
```

I don't have any  special configuration just follow the documents, this error is it normal?

thanks

env:

- Microsoft.Orleans.Clustering.AzureStorage: 3.3.0
- Microsoft.Orleans.Persistence.AzureStorage: 3.3.0
- Microsoft.Orleans.Server: 3.3.0
- Microsoft.Orleans.Hosting.Kubernetes: 3.3.0-rc2
- dotnet core 3.1
- GKE: 1.17.13-gke.1400
- node image: Container-Optimized OS (cos)

**Comment by sergeybykov** [comment]
If it only happens infrequently, then it's likely just a transient error talking to Azure Table (across clouds?).
