### ISSUE TITLE
Exception when shutdown silo gracefully

### ISSUE THREAD

**Issue by lpyvvvvvv** [dotnet/orleans#6871]
I using Orleans 3.3.0.
there are 12 silos online.
shutdown all silo gracefully with `await _silHost.StopAsync(cancellationToken);`
and Exception occured.
`System.NullReferenceException: Object reference not set to an instance of an object.
at Orleans.Runtime.Messaging.IncomingMessageHandler.ReceiveMessage(Message msg)
at Orleans.Runtime.Messaging.MessageCenter.SendRejection(Message msg, RejectionTypes rejectionType, String reason)
at Orleans.Runtime.Messaging.OutboundMessageQueue.SendMessage(Message msg)
at Orleans.Runtime.Messaging.GatewayInboundConnection.RetryMessage(Message msg, Exception ex)
at Orleans.Runtime.Messaging.Connection.b__62_0(Object msg)
at System.Threading.ThreadPoolWorkQueue.Dispatch()`

**Comment by rikbosch** [comment]
I can confirm we're seeing this exception also in some of our test runs

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Runtime.Messaging.IncomingMessageHandler.ReceiveMessage(Message msg)
   at Orleans.Runtime.Messaging.MessageCenter.OnReceivedMessage(Message message)
   at Orleans.Runtime.Messaging.MessageCenter.SendRejection(Message msg, RejectionTypes rejectionType, String reason)
   at Orleans.Runtime.Messaging.OutboundMessageQueue.SendMessage(Message msg)
   at Orleans.Runtime.Messaging.MessageCenter.SendMessage(Message msg)
   at Orleans.Runtime.Messaging.GatewayInboundConnection.RetryMessage(Message msg, Exception ex)
   at Orleans.Runtime.Messaging.Connection.<RerouteMessage>b__62_0(Object msg)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
   ```

we're using Orleans 3.2.2

**Comment by benjaminpetit** [comment]
Do you repro this issue with > 3.4.1. I think we fixed it recently

**Comment by ReubenBond** [comment]
Closed due to inactivity and we believe this is fixed. Please open a new issue if this is still occurring on the most recent release
