### ISSUE TITLE
Error reported when registering Stream

### ISSUE THREAD

**Issue by Difficulty-in-naming** [dotnet/orleans#6888]
The server has been configured with PubSubStore

```
ISiloHostBuilder builder = new SiloHostBuilder()
                .AddCosmosDBGrainStorage("Profile",options =>
                {
                    options.Client = DatabaseClient.Core;
                })
                .AddCosmosDBGrainStorage("PubSubStore",options =>
                {
                    options.Client = DatabaseClient.Core;
                })

```
 When the client calls 
`await guildChanged.SubscribeAsync((msg, token) => GuildChangedCallback(msg, info.id,db, token));`

After that, the following error occurs

```
fail: Orleans.Streams.PubSubRendezvousGrain[103412]
      Failed to register a stream consumer.  Stream: HalloWorld-00000000-0000-0000-0000-000000000000-GuildInfo, SubscriptionId 2677df3d-9791-48d8-83b9-636d8834c159, Consumer: ObserverId:*cli/e8b96d80/53cb2e68-acc7-4192-8c1f-309032a3d3fc
      Orleans.Runtime.OrleansException: Error from storage provider CosmosDBGrainStorage.Orleans.Streams.PubSubRendezvousGrain during WriteState for grain Type=Orleans.Streams.PubSubRendezvousGrain Pk=*grn/Orleans.Streams.PubSubRendezvousGrain/0+GuildInfo_HalloWorld-0xA39B81
59 Id=GrainReference:*grn/Orleans.Streams.PubSubRendezvousGrain/0+GuildInfo_HalloWorld Error=

      Exc level 0: System.AggregateException: One or more errors occurred. (Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: c5a97512-86ed-4125-aece-2ba87ca2a324; Reason: (Message: {"Errors":["Resource Not Found"]}
      ActivityId: c5a97512-86ed-4125-aece-2ba87ca2a324, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats:
      RequestStartTime: 2021-01-13T09:51:53.6426154Z, RequestEndTime: 2021-01-13T09:51:53.6436132Z,  Number of regions attempted:1
      ResponseTime: 2021-01-13T09:51:53.6436132Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10000/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 644, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: Tr
ue, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#644, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
      ResponseTime: 2021-01-13T09:51:53.6436132Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10000/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 644, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: Tr
ue, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#644, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
      , SDK: Microsoft.Azure.Documents.Common/2.9.2, Please see CosmosDiagnostics, Windows/10.0.18363 cosmos-netstandard-sdk/3.15.2);)
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
         at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
         at System.Threading.Tasks.Task`1.get_Result()
         at Microsoft.Azure.Cosmos.ContainerCore.<>c.<GetPartitionKeyDefinitionAsync>b__40_0(Task`1 containerPropertiesTask)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.Azure.Cosmos.ContainerCore.ExtractPartitionKeyAndProcessItemStreamAsync[T](Nullable`1 partitionKey, String itemId, T item, OperationType operationType, ItemRequestOptions requestOptions, CosmosDiagnosticsContext diagnosticsContext, CancellationToken can
cellationToken)
         at Microsoft.Azure.Cosmos.ContainerCore.CreateItemAsync[T](CosmosDiagnosticsContext diagnosticsContext, T item, Nullable`1 partitionKey, ItemRequestOptions requestOptions, CancellationToken cancellationToken)
         at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](CosmosDiagnosticsContext diagnosticsContext, Func`2 task)
         at Orleans.Persistence.CosmosDB.CosmosDBGrainStorage.ExecuteWithRetries[TResult](Func`1 clientFunc)
         at Orleans.Persistence.CosmosDB.CosmosDBGrainStorage.WriteStateAsync(String grainType, GrainReference grainReference, IGrainState grainState)
         at Orleans.Core.StateStorageBridge`1.WriteStateAsync()
      Exc level 1: Microsoft.Azure.Cosmos.CosmosException: Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: c5a97512-86ed-4125-aece-2ba87ca2a324; Reason: (Message: {"Errors":["Resource Not Found"]}
      ActivityId: c5a97512-86ed-4125-aece-2ba87ca2a324, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats:
      RequestStartTime: 2021-01-13T09:51:53.6426154Z, RequestEndTime: 2021-01-13T09:51:53.6436132Z,  Number of regions attempted:1
      ResponseTime: 2021-01-13T09:51:53.6436132Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10000/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 644, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: Tr
ue, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#644, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
      ResponseTime: 2021-01-13T09:51:53.6436132Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10000/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 644, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: Tr
ue, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#644, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
      , SDK: Microsoft.Azure.Documents.Common/2.9.2, Please see CosmosDiagnostics, Windows/10.0.18363 cosmos-netstandard-sdk/3.15.2);
         at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)
         at Microsoft.Azure.Cosmos.GatewayStoreClient.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, Uri physicalAddress, CancellationToken cancellationToken)
         at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
         at Microsoft.Azure.Cosmos.Routing.ClientCollectionCache.ReadCollectionAsync(String collectionLink, CancellationToken cancellationToken, IDocumentClientRetryPolicy retryPolicyInstance)
         at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
         at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
         at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
         at Microsoft.Azure.Cosmos.Common.CollectionCache.<>c__DisplayClass10_0.<<ResolveByNameAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.Azure.Cosmos.Common.AsyncCache`2.GetAsync(TKey key, TValue obsoleteValue, Func`1 singleValueInitFunc, CancellationToken cancellationToken, Boolean forceRefresh)
         at Microsoft.Azure.Cosmos.Common.CollectionCache.ResolveByNameAsync(String apiVersion, String resourceAddress, CancellationToken cancellationToken)
         at Microsoft.Azure.Cosmos.ContainerCore.GetCachedContainerPropertiesAsync(CancellationToken cancellationToken)
       ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: c5a97512-86ed-4125-aece-2ba87ca2a324; Reason: (Message: {"Errors":["Resource Not Found"]}
      ActivityId: c5a97512-86ed-4125-aece-2ba87ca2a324, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats:
      RequestStartTime: 2021-01-13T09:51:53.6426154Z, RequestEndTime: 2021-01-13T09:51:53.6436132Z,  Number of regions attempted:1
      ResponseTime: 2021-01-13T09:51:53.6436132Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10000/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 644, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: Tr
ue, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#644, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
      ResponseTime: 2021-01-13T09:51:53.6436132Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10000/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 644, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: Tr
ue, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#644, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
      , SDK: Microsoft.Azure.Documents.Common/2.9.2, Please see CosmosDiagnostics, Windows/10.0.18363 cosmos-netstandard-sdk/3.15.2);)
       ---> Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: c5a97512-86ed-4125-aece-2ba87ca2a324; Reason: (Message: {"Errors":["Resource Not Found"]}
      ActivityId: c5a97512-86ed-4125-aece-2ba87ca2a324, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats:
      RequestStartTime: 2021-01-13T09:51:53.6426154Z, RequestEndTime: 2021-01-13T09:51:53.6436132Z,  Number of regions attempted:1
      ResponseTime: 2021-01-13T09:51:53.6436132Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10000/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 644, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: Tr
ue, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#644, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
      ResponseTime: 2021-01-13T09:51:53.6436132Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10000/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 644, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: Tr
ue, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#644, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
      , SDK: Microsoft.Azure.Documents.Common/2.9.2, Please see CosmosDiagnostics, Windows/10.0.18363 cosmos-netstandard-sdk/3.15.2);
         at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)
         at Microsoft.Azure.Cosmos.GatewayStoreClient.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, Uri physicalAddress, CancellationToken cancellationToken)
         at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
         at Microsoft.Azure.Cosmos.Routing.ClientCollectionCache.ReadCollectionAsync(String collectionLink, CancellationToken cancellationToken, IDocumentClientRetryPolicy retryPolicyInstance)
         at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
         at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
         at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
         at Microsoft.Azure.Cosmos.Common.CollectionCache.<>c__DisplayClass10_0.<<ResolveByNameAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.Azure.Cosmos.Common.AsyncCache`2.GetAsync(TKey key, TValue obsoleteValue, Func`1 singleValueInitFunc, CancellationToken cancellationToken, Boolean forceRefresh)
         at Microsoft.Azure.Cosmos.Common.CollectionCache.ResolveByNameAsync(String apiVersion, String resourceAddress, CancellationToken cancellationToken)
         at Microsoft.Azure.Cosmos.ContainerCore.GetCachedContainerPropertiesAsync(CancellationToken cancellationToken)
      --- Cosmos Diagnostics ---{"DiagnosticVersion":"2","Summary":{"StartUtc":"2021-01-13T09:51:53.6557926Z","RunningElapsedTimeInMs":16.4915,"UserAgent":"cosmos-netstandard-sdk/3.15.1|3.15.2|03|X64|Microsoft Windows 10.0.18363|.NET 5.0.1-servicing.20575.16|","TotalRequestC
ount":0,"FailedRequestCount":0,"Operation":"CosmosDiagnosticsContextCore"},"Context":[]}
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
         at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
         at System.Threading.Tasks.Task`1.get_Result()
         at Microsoft.Azure.Cosmos.ContainerCore.<>c.<GetPartitionKeyDefinitionAsync>b__40_0(Task`1 containerPropertiesTask)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.Azure.Cosmos.ContainerCore.ExtractPartitionKeyAndProcessItemStreamAsync[T](Nullable`1 partitionKey, String itemId, T item, OperationType operationType, ItemRequestOptions requestOptions, CosmosDiagnosticsContext diagnosticsContext, CancellationToken can
cellationToken)
         at Microsoft.Azure.Cosmos.ContainerCore.CreateItemAsync[T](CosmosDiagnosticsContext diagnosticsContext, T item, Nullable`1 partitionKey, ItemRequestOptions requestOptions, CancellationToken cancellationToken)
         at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](CosmosDiagnosticsContext diagnosticsContext, Func`2 task)
         at Orleans.Persistence.CosmosDB.CosmosDBGrainStorage.ExecuteWithRetries[TResult](Func`1 clientFunc)
         at Orleans.Persistence.CosmosDB.CosmosDBGrainStorage.WriteStateAsync(String grainType, GrainReference grainReference, IGrainState grainState)
         at Orleans.Core.StateStorageBridge`1.WriteStateAsync()
         --- End of inner exception stack trace ---
         at Orleans.Core.StateStorageBridge`1.WriteStateAsync()
         at Orleans.Streams.PubSubRendezvousGrain.RegisterConsumer(GuidId subscriptionId, StreamId streamId, IStreamConsumerExtension streamConsumer, IStreamFilterPredicateWrapper filter)
info: Orleans.Runtime.Catalog[100540]
      DeactivateActivationOnIdle: [Activation: S127.0.0.1:11111:348227503*grn/Orleans.Streams.PubSubRendezvousGrain/0+GuildInfo_HalloWorld@3a2d6da4 #GrainType=Orleans.Streams.PubSubRendezvousGrain Placement=RandomPlacement State=Deactivating] later when become idle.
```

**Comment by maryammadzadeh** [comment]
It looks like this isn't an issue with Orleans, but one of your resources are not configured correctly and could not be found. Either the document you are looking for is not there.

Exc level 0: System.AggregateException: One or more errors occurred. (Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: c5a97512-86ed-4125-aece-2ba87ca2a324; **Reason: (Message: {"Errors":["Resource Not Found"]}
      ActivityId: c5a97512-86ed-4125-aece-2ba87ca2a324, Request URI: **/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p**/**, RequestStats:
      RequestStartTime: 2021-01-13T09:51:53.6426154Z, RequestEndTime: 2021-01-13T09:51:53.6436132Z,  Number of regions attempted:1
      
Stack trace shows it application level and not an orleans issue. Did you see if the resource you were looking for exists?

**Comment by ReubenBond** [comment]
If you want the CosmosDB storage provider to create resources for you, then you need to specify `CanCreateResources = true` in the configuration
