### ISSUE TITLE
StateStorageBridge<TState> requires empty constructor for TState

### ISSUE THREAD

**Issue by fdbeirao** [dotnet/orleans#6913]
Hello,

I am trying to use a c# 9.0 record as my grain state representation:

```csharp
[Serializable]
public sealed record SupportAccountPoolGrainStateV1(
    ImmutableHashSet<(SupportAccountDataStateV1, Guid)> SupportAccountsInUse,
    ImmutableHashSet<SupportAccountDataStateV1> AvailableSupportAccounts);
```

I am running into an issue when activating this Grain: 

```csharp
public sealed class SupportAccountPoolGrain : Grain, ISupportAccountPoolService, IRemindable
{
    private ILogger Logger { get; }

    private readonly IPersistentState<SupportAccountPoolGrainStateV1> _stateV1;

    public SupportAccountPoolGrain(
        [PersistentState(nameof(SupportAccountPoolGrainStateV1), GrainInterfaces.Consts.PostgresAdoGrainStorage)]
        IPersistentState<SupportAccountPoolGrainStateV1> stateV1,
        ILogger<SupportAccountPoolGrain> logger) =>
            (_stateV1, Logger) =
            (@stateV1, logger);
}
```

This is the exception: 
```text
System.MissingMethodException: No parameterless constructor defined for type 'Grains.SupportAccountPool.SupportAccountPoolGrainStateV1'.
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at Orleans.Core.StateStorageBridge`1..ctor(String name, GrainReference grainRef, IGrainStorage store, ILoggerFactory loggerFactory)
   at Orleans.Runtime.PersistentStateFactory.PersistentStateBridge`1.OnSetupState(CancellationToken ct)
   at Orleans.LifecycleExtensions.Observer.OnStart(CancellationToken ct)
   at Orleans.LifecycleSubject.<OnStart>g__CallOnStart|7_0(OrderedObserver observer, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
```

The issue seems to be coming from [this line](https://github.com/dotnet/orleans/blob/769729dbcb714c5542626b37aca3a13a6d1d2382/src/Orleans.Runtime/Storage/StateStorageBridge.cs#L49).

I am using the most recent version of Orleans at the time of this post (`3.4.0`) and that code snipped could be found on `master` branch.

My question is: If we know beforehand that we will use `Activator.CreateInstance<TState>()` could we not give a hint to the compiler that TState requires `new()` capability?

So changing the class definition line to

```csharp
public class StateStorageBridge<TState> : IStorage<TState> where TState : new()
```
(this of course would need to bubble up to many other type definitions, so that it would make it to the developer's code)

Or is there something I am missing?

Either that, or allowing the State to be nullable? Since later we will overwrite ([ado](https://github.com/dotnet/orleans/blob/cafbbe4b2526f86e44f0e431b1070b0554617807/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs#L320) and in other projects too) it anyway..?

It still keeps tripping me up that I only see these issues at runtime, specially since I have enabled all the Roslyn analysers + the new c# 9 nullability features.

Kind regards and thanks for the awesome work on Orleans.

**Comment by fdbeirao** [comment]
For now, as a workaround, I will change my record definition to

```csharp
[Serializable]
public sealed record SupportAccountPoolGrainStateV1 
{
    public ImmutableHashSet<(SupportAccountDataStateV1, Guid)> SupportAccountsInUse { get; init; } = ImmutableHashSet<(SupportAccountDataStateV1, Guid)>.Empty;

    public ImmutableHashSet<SupportAccountDataStateV1> AvailableSupportAccounts { get; init; } = ImmutableHashSet<SupportAccountDataStateV1>.Empty;
}
```

But it would still be very nice if this was a compile-time warning/error rather than a runtime one.
