### ISSUE TITLE
System.Runtime.Serialization.SerializationException: Unexpected token '7' introducing type specifier

### ISSUE THREAD

**Issue by DaweiCai** [dotnet/orleans#6915]
exception: System.Runtime.Serialization.SerializationException: Unexpected token '7' introducing type specifier
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.GrainReferenceRuntime.InvokeWithFilters(GrainReference reference, InvokeMethodRequest request, InvokeMethodOptions options)

**Comment by DaweiCai** [comment]
Any one know this issue?

**Comment by DaweiCai** [comment]
@sergeybykov

**Comment by ReubenBond** [comment]
@DaweiCai this usually means that you're trying to upgrade a cluster from one version of your code to another, but you have changed the definition for a type which is sent between grains (eg, adding or removing fields/properties, or changing a field's type).
