### ISSUE TITLE
Using roslyn analyzer creates generated classes that are not picked up by orleans codegen

### ISSUE THREAD

**Issue by ajvwray** [dotnet/orleans#7002]
So I've been trying to explore Orleans by creating some building blocks similarly to how I've worked before which involved creating models using roslyn. 

I do get a message from orleans codegen:

`3>Orleans.CodeGenerator - command-line = SourceToSource C:\projects\TradingHub\TradingHub.Domain\obj\Debug\net5.0\TradingHub.Domain.orleans.g.args.txt
3>EXEC : warning : attempted to get TypeSyntax for unknown (error) type, "CustomerQueryModel". Possible reason: None. Possible candidates:
3>TradingHub.Domain -> C:\projects\TradingHub\TradingHub.Domain\bin\Debug\net5.0\TradingHub.Domain.dll`

but it builds and runs and even grains that return the base type "CustomerQueryModel" work but if I use this in a List it throws an exception: 

`Exception thrown: 'System.TypeAccessException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.TypeAccessException: Named type "TradingHub.Domain.Customer.Queries.CustomerQueryModel" is invalid: Type string "TradingHub.Domain.Customer.Queries.CustomerQueryModel" cannot be resolved.
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadSpecifiedTypeHeader[TReader](TReader this, SerializationManager serializationManager)
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadFullTypeHeader[TReader](TReader this, SerializationManager serializationManager, Type expected)
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadGenericArguments(IBinaryTokenStreamReader this, SerializationManager serializationManager, Int32 n)
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadSpecifiedTypeHeader[TReader](TReader this, SerializationManager serializationManager)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value)
   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message)
   at Orleans.Runtime.Messaging.Connection.ProcessIncoming()
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at TradingHub.GraphQl.ValuesController.Get(Guid customerId) in C:\projects\TradingHub\TradingHub\ValuesController.cs:line 35
   at lambda_method4(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

Is this something thats supported? I guess the exception is because despite some resolution the actual generated model isnt mapped in the orleans codegen?

**Comment by ReubenBond** [comment]
I'd say that's not supported. I don't know of any way to specify an order for Roslyn Analyzers (or Source Generators) to run in.

If there was a way to define such an order, then it could potentially be supported.

**Comment by ajvwray** [comment]
I can output files instead but then as you've said the order isn't guaranteed and you'd need to build it twice (I actually tried this but it was a little too hacky). 

I'm not a 100% sure if that's why it doesn't get picked up as I guess the Orleans codegen looks for files in the project? or is lookups to referenced assemblies? Would another project acting as a façade for the Orleans codegen to force the order help?

**Comment by ReubenBond** [comment]
Using a separate project may help, you can include an attribute such as `[assembly: KnownAssembly(typeof(MyGeneratedType)]` to tell Orleans to inspect your other assembly.

**Comment by ajvwray** [comment]
Should you be able to reference grain interfaces from another assembly that way?

**Comment by ReubenBond** [comment]
Yes, if you are generating grain interfaces in another assembly, then the solution I provided above ought to work, since any given assembly must be built before any assembly which references it is built.
