### ISSUE TITLE
Could not find a membership entry for this silo

### ISSUE THREAD

**Issue by qzwzqty** [dotnet/orleans#7027]
Hello. I need help. thx！

Run client and silo in the same program, and use redis Cluster，and after a few seconds, log an error

````
[ERR Orleans.Runtime.MembershipService.LocalSiloHealthMonitor] Could not find a membership entry for this silo
[WRN Orleans.Runtime.MembershipService.LocalSiloHealthMonitor] Self-monitoring determined that local health is degraded. Degradation score is 8/8 (lower is better). Complaints: Could not find a membership entry for this silo
````
and after a period of time，log an error

````
[ERR Orleans.Runtime.MembershipService.MembershipAgent] Failed to update table entry for this silo, will retry shortly: Orleans.Clustering.Redis.RedisClusteringException: Could not find a value for the key S172.17.48.1:30000:353557710
   at Orleans.Clustering.Redis.RedisMembershipTable.UpdateIAmAlive(MembershipEntry entry)
   at Orleans.Runtime.MembershipService.MembershipTableManager.UpdateIAmAlive()
   at Orleans.Runtime.MembershipService.MembershipAgent.UpdateIAmAlive()
````
I debugged the orleans source code and found that line 169 ```` if 
 (membershipSnapshot.Entries.TryGetValue(_localSiloDetails.SiloAddress, out var membershipEntry))```` of ```` class LocalSiloHealthMonitor```` always returns false

No such problem with UseLocalhostClustering. 
Thank you!

**Comment by qzwzqty** [comment]
````
public class Program
    {
        static async Task<int> Main(string[] args)
        {
            // 启动服务
            try
            {
                var host = await StartSilo();
                Console.WriteLine("Silo is ready!");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                Console.ReadLine();
                return 1;
            }

            // 启动客户端
            try
            {
                var client = await StartClientWithRetries();
                await DoClientWork(client);

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return 1;
            }

            Console.ReadKey();
            return 0;
        }

        private static async Task<ISiloHost> StartSilo()
        {
            var builder = new SiloHostBuilder()
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = "testcluster";
                    options.ServiceId = "testcluster";
                })
                .ConfigureEndpoints(IPAddress.Loopback, 22222, 33333,listenOnAnyHostAddress: true)
                .UseRedisClustering(opt =>
                {
                    opt.ConnectionString = "192.168.103.113:6379,password=Qbkj@2020";
                    opt.Database = 13;
                })
                .AddMemoryGrainStorageAsDefault()
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(HelloGrain).Assembly).WithReferences())
                .ConfigureLogging(logging => logging.AddConsole());

            var host = builder.Build();
            await host.StartAsync();
            return host;
        }

        private static async Task<IClusterClient> StartClientWithRetries(int initializeAttemptsBeforeFailing = 5)
        {
            int attempt = 0;
            IClusterClient client;
            while (true)
            {
                try
                {
                    client = new ClientBuilder()
                        .Configure<ClusterOptions>(options =>
                        {
                            options.ClusterId = "testcluster";
                            options.ServiceId = "testcluster";
                        })
                        .UseRedisClustering(opt =>
                        {
                            opt.ConnectionString = "192.168.103.113:6379,password=Qbkj@2020";
                            opt.Database = 13;
                        })
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IHello).Assembly).WithReferences())
                        .ConfigureLogging(logging => logging.AddConsole())
                        .Build();

                    await client.Connect();
                    Console.WriteLine("Client successfully connect to silo host");
                    break;
                }
                catch (SiloUnavailableException)
                {
                    attempt++;
                    Console.WriteLine($"Attempt {attempt} of {initializeAttemptsBeforeFailing} failed to initialize the Orleans client.");
                    if (attempt > initializeAttemptsBeforeFailing)
                    {
                        throw;
                    }
                    await Task.Delay(TimeSpan.FromSeconds(4));
                }
            }

            return client;
        }

        private static async Task DoClientWork(IClusterClient client)
        {
            var friend = client.GetGrain<IHello>(0);
            for (int i = 0; i < 10; i++)
            {
                var response = await friend.SayHello("Good morning, my friend!");
                Console.WriteLine("\n\n{0}\n\n", response);
            }
        }
    }
````

**Comment by qzwzqty** [comment]
I Solved the problem, but I don't know why

**Comment by qzwzqty** [comment]
No Solved, still have the problem

**Comment by qzwzqty** [comment]
It should be a problem with redis cluster, ado cluster does not have this problem. sorry
