### ISSUE TITLE
GetGrainId has been called on an unexpected type

### ISSUE THREAD

**Issue by mchandler-manticore** [dotnet/orleans#7055]
On silo shutdown it looks like the logging code is triggering an exception to be thrown and then failing silo shutdown:

Exception Callstack:
```
 System.ArgumentException: GetGrainId has been called on an unexpected type: OrleansStatusApiService. (Parameter 'grain')
   at Orleans.GrainExtensions.GetGrainId(IAddressable grain)
   at Orleans.Runtime.Silo.OnActiveStop(CancellationToken ct)
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStop(CancellationToken ct)
```

Grain Service:
```
    public interface IOrleansStatusApiService : IGrainService
    {
    }

    public class OrleansStatusApiService : GrainService, IOrleansStatusApiService
    {
	   ...
    }
```

What i think is causing the error:
```
Silo.cs:789

	if (this.logger.IsEnabled(LogLevel.Debug))
	{
		logger.Debug(
			"{GrainServiceType} Grain Service with Id {GrainServiceId} stopped successfully.", 
			grainService.GetType().FullName, 
			grainService.**GetPrimaryKeyLong**(out string ignored));
	}
```

**Comment by ReubenBond** [comment]
I'm not so sure about this use case, but I don't see a compelling reason why we should *not* support this scenario, so I've opened #7259 with the fix.
