### ISSUE TITLE
Reminder not working in Kubernetes

### ISSUE THREAD

**Issue by gabrielfreire** [dotnet/orleans#7078]
Hi Guys, i'm having Reminder problems in kubernetes.

Orleans version 3.4.2

**It works fine locally**, but when i deploy to my kubernetes silo cluster, i get the error below.
```
Orleans.Runtime.OrleansMessageRejectionException: SystemTarget *stg/0/00000000 not active on this silo. Msg=Request S10.42.104.46:11113:357845393*grn/Grains.NotificationReminderManager/0+sp_core_reminders_repository@4003479c->S10.42.166.190:11111:357038348*stg/0/00000000@S00000000 InvokeMethodRequest Orleans.IReminderService:RegisterOrUpdateReminder #239
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Grains.NotificationReminderManager.StartOrUpdateReminderAsync(CoreReminder coreReminder, TimeSpan dueTimeInSeconds) in /src/Grains/NotificationReminderManager.cs:line 153
```

I don't think the reminder is not registered in the silo as i'm waiting around 3 minutes after the service has started and the Silo has been active before calling the API,

I was using AdoNet Reminder adapter but changed to InMemory to check if the database was causing problems, but no success, got the same error.

Registering 
```csharp
.ConfigureApplicationParts(parts =>
 {
    parts.AddApplicationPart(typeof(NotificationReminderManager).Assembly).WithReferences();
})
```

grain
```csharp
public interface INotificationReminderManager : IGrainWithStringKey
    {
        Task StartAllSavedRemindersAsync();
        Task<CoreReminder> StartOrUpdateReminderAsync(CoreReminder coreReminder, TimeSpan dueTimeInSeconds);
        Task StopReminderAsync(string reminderId);
        Task<List<CoreReminder>> ListAllRemindersAsync();
        Task<CoreReminder> GetReminderByIdAsync(string reminderId);
    }
```
```csharp
public class NotificationReminderManager : Grain, INotificationReminderManager, IRemindable
{
...
      public async Task<CoreReminder> StartOrUpdateReminderAsync(CoreReminder coreReminder, TimeSpan dueTimeInSeconds)
        {
            ...
            try
            {
                   ....
                    await base.RegisterOrUpdateReminder(coreReminder.ReminderName, dueTimeInSeconds, coreReminder.PeriodInMinutes);
                    return coreReminder;
                
            }
            catch (Exception ex)
            {
                
                throw;
            }
        }
...
}
```

**Comment by gabrielfreire** [comment]
My bad, I'll close this issue as i didn't know i need to register `.UseAdoNetReminderService` for each silo in the cluster.

It works now
