### ISSUE TITLE
exception: Activation access violation. A non-activation thread attempted to access activation services.

### ISSUE THREAD

**Issue by AnakinCN** [dotnet/orleans#7086]
Hi,

I'm using a loop within grains, in which the grain can interact with others according to :https://stackoverflow.com/questions/7472013/how-to-create-a-thread-task-with-a-continuous-loop

But,  the loop violates the original therads, and when calling GrainFactory.GetGrain, it says: 
`System.InvalidOperationException
  HResult=0x80131509
  Message=Activation access violation. A non-activation thread attempted to access activation services.
  Source=Orleans.Runtime
  StackTrace:
   at Orleans.Runtime.GrainRuntime.<CheckRuntimeContext>g__ThrowMissingContext|27_0()
   at Orleans.Runtime.GrainRuntime.CheckRuntimeContext()
   at Orleans.Runtime.GrainRuntime.get_GrainFactory()
   at Orleans.Grain.get_GrainFactory()
   at ActorSim.Grains.ZoneGrain.PassCar(ZoneGrain thiszone) in D:\SUTPC-repo\ActorSim\ZoneGrain\ZoneGrain.cs:line 70
   at ActorSim.Grains.ZoneGrain.<ProcessZone>b__7_0(Task t) in D:\SUTPC-repo\ActorSim\ZoneGrain\ZoneGrain.cs:line 55
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
`

the project is attached:
[ActorSim.zip](https://github.com/dotnet/orleans/files/6508350/ActorSim.zip)

Any thoughts? Thank you in advance.

**Comment by AnakinCN** [comment]
never mind, nailed it using a static IGrainFactory.
