### ISSUE TITLE
Code generator failed on net5.0 library

### ISSUE THREAD

**Issue by lukapor** [dotnet/orleans#7307]
I am using lastest 3.5.0 version of orleans.

My project are build in net5.0 framework (app & library). I added orleans into my project. Problem occours when building grain project - code generation. Bellow is build error stack trace. Do I doing something wrong or orleans do not support net5.0?

I also try nights build but same error.

`  -- Code Generation FAILED --

  Exc level 0: System.ArgumentException: A BadImageFormatException has been thrown while parsing the signature. This is likely due to lack of a generic context. Ensure genericTypeArguments and genericMethodArguments are provided and contain enough context.
     at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
     at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
     at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
     at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
     at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
     at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](Assembly element)
     at Orleans.ApplicationParts.AssemblyAttributeFeatureProvider`1.PopulateFeature(IEnumerable`1 parts, TFeature feature) in D:\build\agent\_work\31\s\src\Orleans.Core\ApplicationParts\AssemblyAttributeFeatureProvider.cs:line 41
     at Orleans.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature) in D:\build\agent\_work\31\s\src\Orleans.Core\ApplicationParts\ApplicationPartManager.cs:line 49
     at Orleans.ApplicationPartManagerExtensions.CreateAndPopulateFeature[TFeature](IApplicationPartManager applicationPartManager) in D:\build\agent\_work\31\s\src\Orleans.Core\ApplicationParts\ApplicationPartManagerExtensions.cs:line 66
     at Orleans.CodeGenerator.RoslynCodeGenerator..ctor(IApplicationPartManager partManager, ILoggerFactory loggerFactory) in D:\build\agent\_work\31\s\src\Orleans.CodeGeneration\RoslynCodeGenerator.cs:line 43
     at Orleans.CodeGeneration.CodeGenerator.GenerateSourceForAssembly(Assembly grainAssembly, LogLevel logLevel) in D:\build\agent\_work\31\s\src\Orleans.CodeGeneration.Build\CodeGenerator.cs:line 81
     at Orleans.CodeGeneration.CodeGenerator.GenerateCodeInternal(CodeGenOptions options) in D:\build\agent\_work\31\s\src\Orleans.CodeGeneration.Build\CodeGenerator.cs:line 165
     at Orleans.CodeGeneration.CodeGenerator.GenerateCodeInCurrentAppDomain(CodeGenOptions options)
     at Orleans.CodeGeneration.CodeGenerator.GenerateCodeInAppDomain(CodeGenOptions options) in D:\build\agent\_work\31\s\src\Orleans.CodeGeneration.Build\CodeGenerator.cs:line 111
     at Orleans.CodeGeneration.CodeGenerator.GenerateCode(CodeGenOptions options) in D:\build\agent\_work\31\s\src\Orleans.CodeGeneration.Build\CodeGenerator.cs:line 49
     at Orleans.CodeGeneration.Program.Main(String[] args) in D:\build\agent\_work\31\s\src\Orleans.CodeGeneration.Build\Program.cs:line 139
  Exc level 1: System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
     at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
     at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
     at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
  Exc level 2: System.BadImageFormatException: Cannot load a reference assembly for execution.

C:\Users\Luka\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\3.5.0\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets(83,5): error MSB3073: The command ""C:\Users\Luka\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\3.5.0\build\..\tasks\net461\Orleans.CodeGeneration.Build.exe" "@obj\Debug\net5.0\codegen\Shared.Grain.orleans.g.args.txt"" exited with code 3. [C:\Nito\4O_Backend\src\Lib.Shared\Grain\Shared.Grain.csproj]`

**Comment by lukapor** [comment]
I replace package Microsoft.Orleans.OrleansCodeGenerator.Build with Microsoft.Orleans.CodeGenerator.MSBuild. Now works. Sorry - my mistake
