### ISSUE TITLE
Orleans fails to perform JsonPatchDocument operations

### ISSUE THREAD

**Issue by Aashish93-stack** [dotnet/orleans#7328]
We are in the process of upgrading our projects to orleans 3.5.0 and donet 5.0 and we observed that all of our JsonPatchDocument requests started to fail with the following 
`Unhandled exception. System.Runtime.Serialization.SerializationException: Reference with no referred object
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task1 asyncTask)`

While trying to reproduce the same Issue on a the HelloWorld Sample project. On reproducing the issue, we noticed some interesting logs related to deserialization on the SiloHost and we believe we are seeing the same in our internal projects.

```
         System.Runtime.Serialization.SerializationException: Reference with no referred object
         at Orleans.Serialization.DeserializationContext.FetchReferencedObject(Int32 offset)
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
         at Orleans.Serialization.SerializationManager.DeserializeArray(Type resultType, IDeserializationContext context)
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
         at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
         at TablesDeserializer(Type , IDeserializationContext )
         at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
         at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
         at ConcurrentDictionary`2Deserializer(Type , IDeserializationContext )
         at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
         at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
         at ThreadSafeStore`2Deserializer(Type , IDeserializationContext )
         at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
         at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
         at DefaultContractResolverDeserializer(Type , IDeserializationContext )
         at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
         at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
         at JsonPatchDocumentDeserializer(Type , IDeserializationContext )
         at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
         at Orleans.Serialization.BuiltInTypes.DeserializeInvokeMethodRequest(Type expected, IDeserializationContext context)
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
         at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value)
         at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message)
         at Orleans.Runtime.Messaging.Connection.ProcessIncoming()
```
Versions used in the project 

```
donet sdk version: 5.0.401
Target Framework: net5.0
Orleans Version: 3.5.0
Microsoft.AspNetCore.JsonPatch Version: 5.0.10
```

I have uploaded the zip file for the reproducer. Instructions for running are in the readme file
[HelloWorld.zip](https://github.com/dotnet/orleans/files/7306202/HelloWorld.zip)

**Comment by Aashish93-stack** [comment]
Thanks for the update @ReubenBond

**Comment by britaincarter** [comment]
Updating the example HelloWorld app to orleans 3.5.1 did not resolve the serialization error. Is there another work around needed or a working example?
