### ISSUE TITLE
InconsistentStateException: Blob storage condition not Satisfied. 

### ISSUE THREAD

**Issue by pascalwinters** [dotnet/orleans#7375]
Running Orleans 3.5.0 in an AKS cluster on Azure
StorageProvider: Azure Blobstorage

```
InconsistentStateException: Blob storage condition not Satisfied.  BlobName: <grainname>.json, Container: grainstate, CurrentETag: 0x8D99F816B2C315F Expected Etag=Unknown Received Etag=0x8D99F816B2C315F Azure.RequestFailedException: The condition specified using HTTP conditional header(s) is not met.
RequestId:4e15eb7a-301e-00b0-4777-d17984000000
Time:2021-11-04T12:31:02.6616999Z
Status: 412 (The condition specified using HTTP conditional header(s) is not met.)
ErrorCode: ConditionNotMet

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 4e15eb7a-301e-00b0-4777-d17984000000
x-ms-client-request-id: 0da73d9d-1124-40e8-9463-7a8f38ffaba8
x-ms-version: 2019-07-07
x-ms-error-code: ConditionNotMet
Date: Thu, 04 Nov 2021 12:31:02 GMT
Content-Length: 252
Content-Type: application/xml

   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, Stream body, Int64 contentLength, String version, Nullable`1 timeout, Byte[] transactionalContentHash, String blobContentType, String blobContentEncoding, String blobContentLanguage, Byte[] blobContentHash, String blobCacheControl, IDictionary`2 metadata, String leaseId, String blobContentDisposition, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, Nullable`1 tier, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadInternal(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, Nullable`1 accessTier, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.PartitionedUploader.UploadAsync(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, IProgress`1 progressHandler, Nullable`1 accessTier, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobClient.StagedUploadAsync(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, IProgress`1 progressHandler, Nullable`1 accessTier, StorageTransferOptions transferOptions, Boolean async, CancellationToken cancellationToken)
   at Orleans.Storage.AzureBlobGrainStorage.DoOptimisticUpdate[TResult](Func`1 updateOperation, BlobClient blob, String currentETag)
```

**Comment by pepelu0** [comment]
Any update on this? I see this error in Orleans a lot

**Comment by benjaminpetit** [comment]
It should indicate that the blob was modified between the moment the grain read its state from storage, and the moment it's trying to write to it.

Do you have an external process that do that?

**Comment by pepelu0** [comment]
I don't think so. In my case, the blob is only used by grain

**Comment by benjaminpetit** [comment]
Do you have a repro? Could you check the etag value manually when you see one if this error to check if it is indeed an etag issue?

**Comment by remcoros** [comment]
Is this a reentrant grain and doing a lot of writes?

When writing to storage within busy and reentrant grain, the storage calls could arrive out of order on the actual storage server (azure blobs), hence the ETag validation will fail.

One solution is to serialize and batch those writes. The chirper example has a pattern on how to do this: https://github.com/dotnet/orleans/blob/main/samples/Chirper/Chirper.Grains/ChirperAccount.cs#L243
