### ISSUE TITLE
IGrainReferenceActivatorProvider added as Singleton rather than added to enumerable

### ISSUE THREAD

**Issue by fuocor** [dotnet/orleans#7376]
```csharp
services.AddSingleton<IGrainReferenceActivatorProvider, GrainReferenceActivatorProvider>();
services.AddSingleton<IGrainReferenceActivatorProvider, UntypedGrainReferenceActivatorProvider>();
```

I believe that the above in both `src\Orleans.Core\Core\DefaultClientServices.cs` and `src\Orleans.Runtime\Hosting\DefaultSiloServices.cs` results in the latter overriding the prior which causes downstream failures activating grains in `GrainReferenceActivator` when providers cannot be located.

resulting in exceptions like the following:
```
     GetOwnerContextAsync, Id: 10dc185c-d635-4997-b39c-d7bf17e6dd77 Faulted with System.InvalidOperationException: Unable to find an IGrainReferenceActivatorProvider for grain type sys.client
         at Orleans.GrainReferences.GrainReferenceActivator.CreateReference(GrainId grainId, GrainInterfaceType interfaceType) in D:\build\agent\_work\22\s\src\Orleans.Core\GrainReferences\GrainReferenceActivator.cs:line 41
         at Orleans.Runtime.GrainReferenceRuntime.Cast(IAddressable grain, Type grainInterface) in D:\build\agent\_work\22\s\src\Orleans.Core\Runtime\GrainReferenceRuntime.cs:line 113
         at Orleans.GrainFactory.Cast(IAddressable grain, Type interfaceType) in D:\build\agent\_work\22\s\src\Orleans.Core\Core\GrainFactory.cs:line 126
         at Orleans.GrainFactory.CreateObjectReference(Type interfaceType, IAddressable obj) in D:\build\agent\_work\22\s\src\Orleans.Core\Core\GrainFactory.cs:line 247
         at Orleans.GrainFactory.CreateObjectReference[TGrainObserverInterface](IAddressable obj) in D:\build\agent\_work\22\s\src\Orleans.Core\Core\GrainFactory.cs:line 103
         at Orleans.Runtime.HostedClient.GetOrSetExtension[TExtension,TExtensionInterface](Func`1 newExtensionFunc) in D:\build\agent\_work\22\s\src\Orleans.Runtime\Core\HostedClient.cs:line 276
         at Orleans.Runtime.Providers.SiloStreamProviderRuntime.BindExtension[TExtension,TExtensionInterface](Func`1 newExtensionFunc) in D:\build\agent\_work\22\s\src\Orleans.Streaming\Providers\SiloProviderRuntime.cs:line 138
         at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.RegisterProducer() in D:\build\agent\_work\22\s\src\Orleans.Streaming\SimpleMessageStream\SimpleMessageStreamProducer.cs:line 68
         at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.ConnectToRendezvous() in D:\build\agent\_work\22\s\src\Orleans.Streaming\SimpleMessageStream\SimpleMessageStreamProducer.cs:line 87
         at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.OnNextAsync(T item, StreamSequenceToken token) in D:\build\agent\_work\22\s\src\Orleans.Streaming\SimpleMessageStream\SimpleMessageStreamProducer.cs:line 111
```

**Comment by fuocor** [comment]
The problem remains, but the source lies elsewhere.

**Comment by irit1** [comment]
I'm upgrading from orleans 3 on .net 6 to orleans 7 on .net8 and face a similar error:
```
System.InvalidOperationException: Unable to find an IGrainReferenceActivatorProvider for grain type visitor
   at Orleans.GrainReferences.GrainReferenceActivator.CreateActivator(GrainType grainType, GrainInterfaceType interfaceType) in /_/src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs:line 85
   at Orleans.GrainReferences.GrainReferenceActivator.CreateReference(GrainId grainId, GrainInterfaceType interfaceType) in /_/src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs:line 54
   at Orleans.GrainFactory.GetGrain(Type interfaceType, IdSpan grainKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 217
   at Orleans.GrainFactory.GetGrain[TGrainInterface](String primaryKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 59
```
any idea what's causing it and how to fix it?

**Comment by Joshhua5** [comment]
I was running into this problem when a grain has a single parameter of type "object", swapping that for anything else worked.
