### ISSUE TITLE
Error using ProtobufSerializer as SerializationProvider in 3.5.1

### ISSUE THREAD

**Issue by jmairena-s3d** [dotnet/orleans#7387]
Hello!

We were using ProtobufSerializer as SerializationProvider for grain states (ISiloBuilder) and for Orleans clients communication (IClientBuilder) in 3.5.0 without problems.
But we are facing some problems with this while trying to upgrade project to Orleans 3.5.1.

In 3.5.0 it was enough for us to add ProtobufSerializer as a SerializationProvider, on ISiloBuilder and IClientBuilder:
`SerializationProviders.Add(typeof(Orleans.Serialization.ProtobufSerializer))`

When updating to Orleans 3.5.1 grains states writes and reads and communication with orleans clients fails (see exception below).

Adding ProtobufSerializer also as the FallbackSerializationProvider seems to fix grain states writes and communication with orleans clients, but grain states reads are still throwing same exception.
`FallbackSerializationProvider = typeof(Orleans.Serialization.ProtobufSerializer)`

Adding ProtobufSerializer as the FallbackSerializationProvider should not be necessary in our project, but we are trying to find the source of the problem.

Are we missing something that needs to be done in this new Orleans version?
Is there any new known bug related to this?

Thanks!

Exception thrown: 

```
System.Runtime.Serialization.SerializationException: End of Stream encountered before parsing was completed.
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at Orleans.Serialization.BinaryFormatterSerializer.Deserialize(Type expectedType, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.FallbackDeserializer(IDeserializationContext context, Type expectedType)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeImmutable[T](Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeGenericImmutable(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value)
   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message)
   at Orleans.Runtime.Messaging.Connection.ProcessIncoming()
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
```

**Comment by benjaminpetit** [comment]
I wonder if you had some type that were not really serialized with protobuf, but with the ILBasedSerializer... that is now deactivated in 3.5.1?

**Comment by jmairena-s3d** [comment]
Ok, my bad.
I was trying to deserialize already existing data from data base that was serialized using a different serializer 🤦‍♂️ 

Using ProtobufSerializer everywhere works perfectly with Orleans 3.5.1 😃 
Thanks!
