### ISSUE TITLE
Unhandled exception. System.ArgumentException: Could not find exact match for generic method in version 3.5.1

### ISSUE THREAD

**Issue by amcorch** [dotnet/orleans#7388]
Hello, after updating to 3.5.1 I am getting the following error.

```
Unhandled exception. System.ArgumentException: Could not find exact match for generic method Grains.IModelStore.Get<TestEntity,String>(String,CancellationToken).
   at Orleans.CodeGeneration.GenericMethodInvoker.GetMethod(Type declaringType, String methodName, Type[] typeParameters, Type[] parameterTypes)
   at Orleans.CodeGeneration.GenericMethodInvoker.CreateInvoker(Object[] arguments)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orleans.CodeGeneration.GenericMethodInvoker.Invoke(IAddressable grain, Object[] arguments)
   at Grains.OrleansCodeGenModelStoreGrainMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request) in C:\Users\acorch\source\repos\ConsoleApp4\Grains\obj\Debug\net6.0\Grains.orleans.g.cs:line 34
   at Orleans.Runtime.GrainMethodInvoker.Invoke()
   at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message)   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Grains.DataStore.Get(String id, CancellationToken cancellationToken) in C:\Users\acorch\source\repos\ConsoleApp4\Grains\DataStore.cs:line 18
   at Program.<Main>$(String[] args) in C:\Users\acorch\source\repos\ConsoleApp4\Client\Program.cs:line 16
   at Program.<Main>(String[] args)
```

I have attached a sample project to reproduce the error.

[OrleansSample.zip](https://github.com/dotnet/orleans/files/7529361/OrleansSample.zip)

**Comment by rafikiassumani-msft** [comment]
@amcorch We think this has been fixed by #7400 . Will be released in 3.6.0
