### ISSUE TITLE
Orleans can not generate code for application part

### ISSUE THREAD

**Issue by sanzor** [dotnet/orleans#7398]
I have an ASP NET Core application where i am using an orleans silo.

I have tried adding a class derived from `JournaledGrain` as an application part and i keep getting the exception :

**Exception message**
`None of the assemblies added to ApplicationPartManager contain generated code. Ensure that code generation has been executed for grain interface and class assemblies`

**Console Output**
```
info: Orleans.Runtime.Silo[100415]
      Starting silo Silo_8a3d8
warn: Orleans.Runtime.NoOpHostEnvironmentStatistics[100708]
      No implementation of IHostEnvironmentStatistics was found. Load shedding will not work yet
info: Orleans.Runtime.ConsistentRing.VirtualBucketsRingProvider[0]
      Starting VirtualBucketsRingProvider on silo S127.0.0.1:11111:374943811/xC62F3E64.
info: Orleans.Runtime.ConsistentRing.VirtualBucketsRingProvider[103003]
      Added Server S127.0.0.1:11111:374943811/xC62F3E64. Current view: [S127.0.0.1:11111:374943811 -> <MultiRange: Size=x100000000, %Ring=100.000%>]
info: Orleans.Runtime.ConsistentRing.VirtualBucketsRingProvider[103005]
      -NotifyLocalRangeSubscribers about old <(0 0], Size=x100000000, %Ring=100.000%> new <MultiRange: Size=x100000000, %Ring=100.000%> increased? True
info: Orleans.Runtime.Silo[100422]
      -------------- Started silo S127.0.0.1:11111:374943811, ConsistentHashCode C62F3E64 --------------
fail: Orleans.Runtime.Scheduler.OrleansTaskScheduler[101231]
      QueueWorkItem was called on a non-null context [SystemTarget: S127.0.0.1:11111:374943811*stg/13/0000000d@S0000000d] but there is no valid WorkItemGroup for it.
```

My grain was first located in a separate DLL which was refrenced by the one containing the Silo.
Upon this error i have moved the Grain class in the Silo dll to no avail.

Full post with code and error can be found on my post :
https://stackoverflow.com/questions/70022281/orleans-can-not-generate-code-for-application-part

P.S I have already checked [this issue](https://github.com/dotnet/orleans/issues/4633) and added Orleans CodeGeneration Build  dll to no avail.

**Comment by sanzor** [comment]
**Update**
So it seemed i was installing Microsoft.Orleans.CodeGenerator.Build instead of MSBuild.
After i have installed on the dll containing the grain the MSBuild dll , i get the following error as output:

```
3>Orleans.CodeGenerator - command-line = SourceToSource C:\WOkr\NotifService\NotificationSolution\Notification\Notification.Application\obj\Debug\netcoreapp3.1\Notification.Application.orleans.g.args.txt
3>-- Code Generation FAILED --
3>
3>Exc level 0: System.Collections.Generic.KeyNotFoundException: Type LanguageExt.EitherAsync<LanguageExt.Common.Error, LanguageExt.Unit> does not have a member of kind Microsoft.CodeAnalysis.IMethodSymbol named GetAwaiter
3>   at Orleans.CodeGenerator.Utilities.SymbolExtensions.Member[TSymbol](ITypeSymbol type, String name, Func`2 predicate) in D:\build\agent\_work\31\s\src\Orleans.CodeGenerator\Utilities\SymbolExtensions.cs:line 243
3>   at Orleans.CodeGenerator.Generators.GrainMethodInvokerGenerator.GenerateInvokeForMethod(WellKnownTypes wellKnownTypes, ExpressionSyntax castGrain, IMethodSymbol method, ExpressionSyntax arguments, Dictionary`2 genericInvokerFields) in D:\build\agent\_work\31\s\src\Orleans.CodeGenerator\Generators\GrainMethodInvokerGenerator.cs:line 275
3>   at Orleans.CodeGenerator.Generators.GrainMethodInvokerGenerator.<>c__DisplayClass8_0.<GenerateInvokeMethod>b__1(IMethodSymbol methodType) in D:\build\agent\_work\31\s\src\Orleans.CodeGenerator\Generators\GrainMethodInvokerGenerator.cs:line 204
3>   at Orleans.CodeGenerator.Generators.GrainInterfaceCommon.GenerateGrainInterfaceAndMethodSwitch(WellKnownTypes types, INamedTypeSymbol grainType, ExpressionSyntax methodIdArgument, Func`2 generateMethodHandler, Func`3 composeInterfaceBlock) in D:\build\agent\_work\31\s\src\Orleans.CodeGenerator\Generators\GrainInterfaceCommon.cs:line 62
3>   at Orleans.CodeGenerator.Generators.GrainMethodInvokerGenerator.GenerateInvokeMethod(WellKnownTypes wellKnownTypes, INamedTypeSymbol grainType, IMethodSymbol invokeMethod, Dictionary`2 genericInvokerFields) in D:\build\agent\_work\31\s\src\Orleans.CodeGenerator\Generators\GrainMethodInvokerGenerator.cs:line 200
3>   at Orleans.CodeGenerator.Generators.GrainMethodInvokerGenerator.GenerateInvokeMethod(WellKnownTypes wellKnownTypes, INamedTypeSymbol grainType, Dictionary`2 genericInvokerFields) in D:\build\agent\_work\31\s\src\Orleans.CodeGenerator\Generators\GrainMethodInvokerGenerator.cs:line 111
3>   at Orleans.CodeGenerator.Generators.GrainMethodInvokerGenerator.GenerateClass(GrainInterfaceDescription description) in D:\build\agent\_work\31\s\src\Orleans.CodeGenerator\Generators\GrainMethodInvokerGenerator.cs:line 65
3>   at Orleans.CodeGenerator.CodeGenerator.GenerateSyntax(AggregatedModel model) in D:\build\agent\_work\31\s\src\Orleans.CodeGenerator\CodeGenerator.cs:line 145
3>   at Orleans.CodeGenerator.CodeGenerator.GenerateCode(CancellationToken cancellationToken) in D:\build\agent\_work\31\s\src\Orleans.CodeGenerator\CodeGenerator.cs:line 59
3>   at Orleans.CodeGenerator.MSBuild.CodeGeneratorCommand.Execute(CancellationToken cancellationToken) in D:\build\agent\_work\31\s\src\Orleans.CodeGenerator.MSBuild\CodeGeneratorCommand.cs:line 143
3>   at Microsoft.Orleans.CodeGenerator.MSBuild.Program.SourceToSource(String[] args) in D:\build\agent\_work\31\s\src\Orleans.CodeGenerator.MSBuild\Program.cs:line 138
3>   at Microsoft.Orleans.CodeGenerator.MSBuild.Program.Main(String[] args) in D:\build\agent\_work\31\s\src\Orleans.CodeGenerator.MSBuild\Program.cs:line 26
3>C:\Users\adrian.bercovici\.nuget\packages\microsoft.orleans.codegenerator.msbuild\3.5.0\build\Microsoft.Orleans.CodeGenerator.MSBuild.targets(125,5): error MSB3073: The command ""dotnet" "C:\Users\adrian.bercovici\.nuget\packages\microsoft.orleans.codegenerator.msbuild\3.5.0\build\..\tasks\netcoreapp3.1\Orleans.CodeGenerator.MSBuild.dll" SourceToSource "C:\WOkr\NotifService\NotificationSolution\Notification\Notification.Application\obj\Debug\netcoreapp3.1\Notification.Application.orleans.g.args.txt"" exited with code 3.
3>Done building project "Notification.Application.csproj" -- FAILED.
```

**Comment by sanzor** [comment]
It seems that i had a dll problem. It works now using MSBuild. Issue can be closed !
