### ISSUE TITLE
MissingMethodException CreateNamespacedCustomObjectAsync in Orleans.Clustering.Kubernetes

### ISSUE THREAD

**Issue by chillitom** [dotnet/orleans#7406]
After upgrading to net6 and Orleans 3.5.1 we get the following exception when running on x64 Linux Kubernetes.

It looks like the _KubernetesClient_ library dependency was upgraded from 2.0.29 to 6.0.19 between version 3.5.0 and 3.5.1.

http://fuget.org/packages/Microsoft.Orleans.Hosting.Kubernetes/3.5.1
http://fuget.org/packages/Microsoft.Orleans.Hosting.Kubernetes/3.5.0

```
fail: Orleans.Runtime.SiloLifecycleSubject[100450]
      Lifecycle start canceled due to errors at stage 8000: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Object> k8s.KubernetesExtensions.CreateNamespacedCustomObjectAsync(k8s.IKubernetes, System.Object, System.String, System.String, System.String, System.String, System.String, System.Threading.CancellationToken)'.
         at Orleans.Clustering.Kubernetes.KubeMembershipTable.TryInitClusterVersion()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Orleans.Clustering.Kubernetes.KubeMembershipTable.TryInitClusterVersion()
         at Orleans.Clustering.Kubernetes.KubeMembershipTable.InitializeMembershipTable(Boolean tryInitTableVersion)
         at Orleans.Runtime.MembershipService.MembershipTableManager.Start()
         at Orleans.Runtime.MembershipService.MembershipTableManager.<>c__DisplayClass54_0.<<Orleans-ILifecycleParticipant<Orleans-Runtime-ISiloLifecycle>-Participate>g__OnRuntimeGrainServicesStart|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct)
         at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
fail: Orleans.Runtime.Silo[100439]
      Exception during Silo.Start
      System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Object> k8s.KubernetesExtensions.CreateNamespacedCustomObjectAsync(k8s.IKubernetes, System.Object, System.String, System.String, System.String, System.String, System.String, System.Threading.CancellationToken)'.
         at Orleans.Clustering.Kubernetes.KubeMembershipTable.TryInitClusterVersion()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Orleans.Clustering.Kubernetes.KubeMembershipTable.TryInitClusterVersion()
         at Orleans.Clustering.Kubernetes.KubeMembershipTable.InitializeMembershipTable(Boolean tryInitTableVersion)
         at Orleans.Runtime.MembershipService.MembershipTableManager.Start()
         at Orleans.Runtime.MembershipService.MembershipTableManager.<>c__DisplayClass54_0.<<Orleans-ILifecycleParticipant<Orleans-Runtime-ISiloLifecycle>-Participate>g__OnRuntimeGrainServicesStart|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct)
         at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
         at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute()
         at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken)
info: Orleans.Runtime.HostedClient[0]
      HostedClient completed processing all messages. Shutting down.
Unhandled exception. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Object> k8s.KubernetesExtensions.CreateNamespacedCustomObjectAsync(k8s.IKubernetes, System.Object, System.String, System.String, System.String, System.String, System.String, System.Threading.CancellationToken)'.
   at Orleans.Clustering.Kubernetes.KubeMembershipTable.TryInitClusterVersion()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Orleans.Clustering.Kubernetes.KubeMembershipTable.TryInitClusterVersion()
   at Orleans.Clustering.Kubernetes.KubeMembershipTable.InitializeMembershipTable(Boolean tryInitTableVersion)
   at Orleans.Runtime.MembershipService.MembershipTableManager.Start()
   at Orleans.Runtime.MembershipService.MembershipTableManager.<>c__DisplayClass54_0.<<Orleans-ILifecycleParticipant<Orleans-Runtime-ISiloLifecycle>-Participate>g__OnRuntimeGrainServicesStart|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct)
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute()
   at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken)
   at Orleans.Hosting.SiloHost.StartAsync(CancellationToken cancellationToken)
   at Orleans.Hosting.SiloHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args) in /workspace/Program.cs:line 36
   at Program.<Main>(String[] args)

```

**Comment by highlyunavailable** [comment]
Orleans.Clustering.Kubernetes became incompatible because of this, but the fix is to get this merged and a release cut: https://github.com/OrleansContrib/Orleans.Clustering.Kubernetes/pull/56

Honestly, the Clustering implementation needs to be moved out of the OrleansContrib repo into Orleans itself, since it's such a core part of using Kube with Orleans, and using the super old 2.x libraries caused this problem with _other_ libraries being integrated, hence the upgrade.

Unfortunately the only workaround currently is to clone a copy of the Orleans.Clustering.Kubernetes repo, manually update the version of Kubeclient, and integrate that into your project as a reference if you want to use 3.5.1. There's no need to make any code changes, but the underlying signatures have changed to include a bunch of optional params, which is why you're getting `MissingMethodException`.
