### ISSUE TITLE
Unable to rolling update from Orleans 3.1.7

### ISSUE THREAD

**Issue by pawanrao** [dotnet/orleans#7408]
We are currently running Orleans 3.1.7 and would preferably like to upgrade to the latest version 3.5.0

However, during a rolling upgrade we consistently see the following exception:

```
Exception when trying to get GrainInterfaceMap for silos
Unable to cast object of type 'System.String' to type 'Orleans.Runtime.GrainClassData'.
at Orleans.Serialization.BuiltInTypes.DeserializeDictionary[K,V](Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Runtime.OrleansCodeGenOrleans_Runtime_GrainInterfaceMapSerializer.Deserializer(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value)
   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message)
   at Orleans.Runtime.Messaging.Connection.ProcessIncoming()
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem`1.Execute()
   at Orleans.Runtime.TypeManager.GetTargetSiloGrainInterfaceMap(SiloAddress siloAddress)

```
We've tried upgrading to all the versions starting from 3.2.0 but still, the same issue persists across versions. 
Could someone please take a look as to what could be the possible cause of the exceptions?

**Comment by benjaminpetit** [comment]
Are you using multi cluster?

**Comment by pawanrao** [comment]
> Are you using multi cluster?

@benjaminpetit no, we are not using multi-cluster

**Comment by pawanrao** [comment]
@benjaminpetit any update here?

**Comment by benjaminpetit** [comment]
No update from me, and unfortunately 3.1.7 is quite old, which makes things costly to investigate.

Do you see these errors on client or on silos? Do you see other errors in the logs (requests to grain failing, etc.)?

**Comment by benjaminpetit** [comment]
We had a small back compat issue around 3.1.x or 3.2.x time. It is possible that's the same issue, although I am not 100% sure.

Either way, the error you are seeing should not make grain calls to fail. Old silos will not be able to place new activations on new silos, and vice-versa, but they still should be able to send request to existing activation.

I will close this issue, but don't hesitate to ping again if you have more questions
