### ISSUE TITLE
[Question] Is there any reserved character for string grain identity?

### ISSUE THREAD

**Issue by zeinali0** [dotnet/orleans#7462]
Hi 
Is there any character limitation for string grain identity?

I used redis-persistance but it cannot activate grains with following error:
```
Exc level 0: Orleans.Persistence.Redis.RedisStorageException: Failed to read grain state for MyTest.Orleans.UpdateAuthKeyClientProxyGrain,MyTest.Grains.AuthState grain with id GrainReference:*grn/MyTest.Orleans.UpdateAuthKeyClientProxyGrain/0+authkey-6227792029253167109 and storage key GrainReference=0000000000000000000000000000000006ffffff998d29cd+authkey-6227792029253167109|json.
         at Orleans.Persistence.RedisGrainStorage.ReadStateAsync(String grainType, GrainReference grainReference, IGrainState grainState)
         at Orleans.Core.StateStorageBridge`1.ReadStateAsync()
      Exc level 1: System.ArgumentException: Provided grain must be a GrainReference. (Parameter 'grain')
         at Orleans.GrainFactory.BindGrainReference(IAddressable grain)
         at Orleans.Serialization.GrainReferenceConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Orleans.Persistence.RedisGrainStorage.ReadStateAsync(String grainType, GrainReference grainReference, IGrainState grainState)
```

**Comment by zeinali0** [comment]
The problem was one of my class in State was implementing IAddresable interface while it doesn't had any reference
