### ISSUE TITLE
Follow-Up to issue #7436: Solution

### ISSUE THREAD

**Issue by SeppPenner** [dotnet/orleans#7510]
Just a small follow-up to issue https://github.com/dotnet/orleans/issues/7436. I have now fixed the issue with a custom logic (For the future, I will use more silo hosts and the ADO.net provider). The `solution` / changes can be found under https://github.com/SeppPenner/OrleansReconnection/tree/master/src_resolved and https://github.com/SeppPenner/OrleansReconnection/commit/f1cde7ba230b4ed7692b8d0024e1aaef86b4e97b.

If someone can reactivate https://github.com/dotnet/orleans/issues/7436, I would post the result there. Currently, the task is locked for comments.

**Comment by ReubenBond** [comment]
I think there's some confusion here.

* Orleans clients reconnect automatically. They proactively refresh the list of gateways from the source and maintain a connection to the cluster.
* The `IClusterClient.Connect` method accepts a retry delegate where you can perform backoff and retry logic.
* You should use something more robust than a static list for anything which isn't a test environment. Eg, use the ADO.NET provider or Azure Storage clustering: each of those have a corresponding gateway list provider for your client to use.

**Comment by SeppPenner** [comment]
> Orleans clients reconnect automatically. They proactively refresh the list of gateways from the source and maintain a connection to the cluster.

I can't confirm that in our scenario. The client loses connection and can't reconnect within hours even if the Silo is only down for like 2 minutes (At least with static clustering and only one silo).

> The IClusterClient.Connect method accepts a retry delegate where you can perform backoff and retry logic.

Good to know, I didn't see the option to be honest...

> You should use something more robust than a static list for anything which isn't a test environment. Eg, use the ADO.NET provider or Azure Storage clustering: each of those have a corresponding gateway list provider for your client to use

That's planned for the future as well as running three silos, not only one. Right now, the workaround is ok for me.

**Comment by SeppPenner** [comment]
> Please don't use the static gateway list if you want resiliency.

Okay.

> Still, can you share logs for what you're seeing when you do, from silo & client?

I will try to reproduce the issue and come back to you.

**Comment by SeppPenner** [comment]
Reopen, I will add details soon :)

**Comment by SeppPenner** [comment]
Some more details from my side: When I run the code from https://github.com/SeppPenner/OrleansReconnection/tree/master/src and
1. Start the SiloHost without debugger.
2. Start the service with debugger.
3. Kill the SiloHost.
4. Start the SiloHost again without debugger.
5. The log that comes (client side):

```log
21.02.22 18:59:56.491   [WRN]                   Connection attempt to endpoint "S127.0.0.1:30000:0" failed
Orleans.Networking.Shared.SocketConnectionException: Unable to connect to 127.0.0.1:30000. Error: ConnectionRefused
   at Orleans.Networking.Shared.SocketConnectionFactory.ConnectAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Orleans.Runtime.Messaging.ConnectionFactory.ConnectAsync(SiloAddress address, CancellationToken cancellationToken)
   at Orleans.Internal.OrleansTaskExtentions.MakeCancellable[T](Task`1 task, CancellationToken cancellationToken)
   at Orleans.Runtime.Messaging.ConnectionManager.ConnectAsync(SiloAddress address)
21.02.22 19:00:23.190   [WRN]                   All gateways have previously been marked as dead. Clearing the list of dead gateways to expedite reconnection.
21.02.22 19:00:23.717   [INF]                   Refreshed the live gateway list. Found 1 gateways from gateway list provider: "[S127.0.0.1:30000:0]". Picked only known live out of them. Now has 1 live gateways: "[S127.0.0.1:30000:0]". Previous refresh time was = 02/21/2022 17:59:51
21.02.22 19:00:24.407   [INF]                   Refreshed the live gateway list. Found 1 gateways from gateway list provider: "[S127.0.0.1:30000:0]". Picked only known live out of them. Now has 1 live gateways: "[S127.0.0.1:30000:0]". Previous refresh time was = 02/21/2022 18:00:23
21.02.22 19:00:24.939   [INF]                   Establishing connection to endpoint "S127.0.0.1:30000:0"
21.02.22 19:00:24.953   [ERR]   ExampleService          The connection to the Silo failed
21.02.22 19:00:24.954   [INF]                   Connected to endpoint "S127.0.0.1:30000:0"
21.02.22 19:00:25.830   [ERR]   ExampleService          Reconnect to silo failed
21.02.22 19:00:25.830   [INF]                   Connection "[Local: 127.0.0.1:61024, Remote: 127.0.0.1:30000, ConnectionId: 0HMFLCFG3HTGK]" established with "S127.0.0.1:30000:0"
21.02.22 19:00:25.832   [INF]   ExampleService          Heartbeat for service "ExampleService": Total "17,470", heap size: "0,000", memory load: "0,000".
```

After some short time, the following error occurs:

System.InvalidOperationException: "Client is already initialized." in https://github.com/SeppPenner/OrleansReconnection/blob/638d513e7b736cf27a2a190070933f197c06c41d/src/ExampleService/ExampleService.cs#L145

--> This is alrigth, I guess. In my workaround, I circumvent this by disposing the old client (Which works properly).

I will check my first version now, too and provide the results here.

**Comment by ReubenBond** [comment]
The client isn't meant to be used this way:
https://github.com/SeppPenner/OrleansReconnection/blob/master/src/ExampleService/ExampleService.cs

If it connects, it *will* reconnect by itself and does not need prompting. Calling `Close` followed by `Connect` is not valid (which is why you're seeing that exception).

**Comment by SeppPenner** [comment]
For my first version under https://github.com/SeppPenner/OrleansReconnection/tree/master/src_firsttry (No custom reconnection), the same scenario:

1. Start the SiloHost without debugger.
2. Start the service with debugger.
3. Kill the SiloHost.
4. Start the SiloHost again without debugger.
5. The log that comes (client side):

```log
21.02.22 19:11:37.566   [WRN]                   Exception while processing messages from remote endpoint "127.0.0.1:30000"
Microsoft.AspNetCore.Connections.ConnectionResetException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
 ---> System.Net.Sockets.SocketException (10054): Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.GetResult()
   at Orleans.Networking.Shared.SocketConnection.ProcessReceives()
   at Orleans.Networking.Shared.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Orleans.Runtime.Messaging.Connection.ProcessIncoming()
21.02.22 19:11:37.606   [INF]                   Closing connection "[Local: 127.0.0.1:61185, Remote: 127.0.0.1:30000, ConnectionId: 0HMFLCMA1PIPK]"
21.02.22 19:11:37.622   [INF]                   Establishing connection to endpoint "S127.0.0.1:30000:0"
21.02.22 19:11:42.463   [WRN]                   Connection attempt to endpoint "S127.0.0.1:30000:0" failed
Orleans.Networking.Shared.SocketConnectionException: Unable to connect to 127.0.0.1:30000. Error: ConnectionRefused
   at Orleans.Networking.Shared.SocketConnectionFactory.ConnectAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Orleans.Runtime.Messaging.ConnectionFactory.ConnectAsync(SiloAddress address, CancellationToken cancellationToken)
   at Orleans.Internal.OrleansTaskExtentions.MakeCancellable[T](Task`1 task, CancellationToken cancellationToken)
   at Orleans.Runtime.Messaging.ConnectionManager.ConnectAsync(SiloAddress address)
21.02.22 19:12:07.289   [WRN]                   All known gateways have been marked dead locally. Expediting gateway refresh and resetting all gateways to live status.
21.02.22 19:12:07.296   [INF]                   Establishing connection to endpoint "S127.0.0.1:30000:0"
21.02.22 19:12:07.299   [INF]                   Connected to endpoint "S127.0.0.1:30000:0"
21.02.22 19:12:07.299   [INF]                   Connection "[Local: 127.0.0.1:61219, Remote: 127.0.0.1:30000, ConnectionId: 0HMFLCMA1PIPL]" established with "S127.0.0.1:30000:0"
21.02.22 19:12:07.302   [WRN]                   All gateways have previously been marked as dead. Clearing the list of dead gateways to expedite reconnection.
21.02.22 19:12:07.318   [INF]                   Refreshed the live gateway list. Found 1 gateways from gateway list provider: "[S127.0.0.1:30000:0]". Picked only known live out of them. Now has 1 live gateways: "[S127.0.0.1:30000:0]". Previous refresh time was = 02/21/2022 18:11:27
21.02.22 19:12:07.359   [INF]   ExampleService          Heartbeat for service "ExampleService": Total "17,409", heap size: "0,000", memory load: "0,000".
21.02.22 19:12:17.365   [INF]   ExampleService          Heartbeat for service "ExampleService": Total "17,494", heap size: "0,000", memory load: "0,000".
```

--> This works now in the example project... I'm not sure what I did differently than in production... What I can tell for sure is that we sometimes got the error from my issue under https://github.com/dotnet/orleans/issues/6629 and therefore implemented the workaround with reconnection (As initially described https://github.com/dotnet/orleans/issues/7510#issue-1113618934).

Another thought (This is something a colleague realised): If you have base classes like a `BaseService`:

```csharp
public class BaseService
{
    protected ISomethingGrain grain;

    public BaseService (IClusterClient clusterClient)
    {
        this.grain = clusterClient.GetGrain<IExampleGrain>("Grain1");
    }
}
```

if you now use the grain reference from an implementing class, you might get an error if the client reconnects (The grain reference is attached to the old client and after reconnection the grain reference is invalid). I assume, that this also not the recommended way on how to handle grain calls... Maybe that was the reason it didn't work in my case with the first version times ago.

I guess, the issue can kept closed now :)

**Comment by SeppPenner** [comment]
> The client isn't meant to be used this way: https://github.com/SeppPenner/OrleansReconnection/blob/master/src/ExampleService/ExampleService.cs
> 
> If it connects, it _will_ reconnect by itself and does not need prompting. Calling `Close` followed by `Connect` is not valid (which is why you're seeing that exception).

Yeah, I know. That was the second step of my progress on trying to get my service to work properly again.

**Comment by ReubenBond** [comment]
> The grain reference is attached to the old client and after reconnection the grain reference is invalid
This occurs because the client is being disposed and recreated - it's one of the reasons why that shouldn't be done

Thanks for your patience. Hopefully everything is working well now. If you do run into another issue, please let us know.

**Comment by SeppPenner** [comment]
> Thanks for your patience. Hopefully everything is working well now. If you do run into another issue, please let us know.

Nothing to complain about at the moment, it works now as expected :)
