### ISSUE TITLE
Orleans.TestingHost.TestClusterBuilder.Build() fails with PlatformNotSupportedException on Linux

### ISSUE THREAD

**Issue by wangjia184** [dotnet/orleans#7548]
NuGet Package :  https://www.nuget.org/packages/Microsoft.Orleans.TestingHost/
Version : v3.6.0

Test cases works well on Windows.  while when it is running in docker container by CI. it fails.
Docker image is [docker:19.03.12](https://hub.docker.com/layers/docker/library/docker/19.03.12/images/sha256-5ed3b31d3b1e5ac2f06187bb3e1aadcb6b9b9cb5ddb18f1dc25c80ce1047acb7?context=explore)

```
 System.PlatformNotSupportedException : The information requested is unavailable on the current platform.
  Stack Trace:
   at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveTcpListenersFromFiles(String tcp4ConnectionsFile, String tcp6ConnectionsFile)
   at System.Net.NetworkInformation.LinuxIPGlobalProperties.GetActiveTcpListeners()
   at Orleans.TestingHost.TestClusterPortAllocator.AllocateConsecutivePortPairs(Int32 numPorts) in /_/src/Orleans.TestingHost/TestClusterPortAllocator.cs:line 22
   at Orleans.TestingHost.TestClusterBuilder.ConfigureDefaultPorts() in /_/src/Orleans.TestingHost/TestClusterBuilder.cs:line 153
   at Orleans.TestingHost.TestClusterBuilder.Build() in /_/src/Orleans.TestingHost/TestClusterBuilder.cs:line 119
```

**Comment by wangjia184** [comment]
The container runs on overlay network with internal k9s addresses without ipv6. Most likely it is because IPv6 is not available

https://github.com/dotnet/runtime/blob/dfd618dc648ba9b11dd0f8034f78113d69f223cd/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Connections.cs#L34

Have no idea how to fix this ussye

**Comment by benjaminpetit** [comment]
I guess it's more on issue on the Runtime then?

To work around the issue, you could implement your own `ITestClusterPortAllocator` and set it on `TestClusterBuilder.PortAllocator`
