### ISSUE TITLE
PubSubRendezvousGrain.RegisterConsumer failure

### ISSUE THREAD

**Issue by mradovcic** [dotnet/orleans#7567]
Hi all,
had anyone else encountered this issue

```
"ClassName":"System.InvalidOperationException",
"Message":"Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.",
"Data":null,
"InnerException":null,
"HelpURL":null,
"StackTraceString":"   at Orleans.Streams.PubSubRendezvousGrain.RegisterConsumer(GuidId subscriptionId, StreamId streamId, IStreamConsumerExtension streamConsumer, IStreamFilterPredicateWrapper filter)
   at Orleans.Streams.OrleansCodeGenPubSubRendezvousGrainMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request)
   at Orleans.Runtime.GrainMethodInvoker.Invoke()
   at OrleansDashboard.Metrics.GrainProfilerFilter.Invoke(IIncomingGrainCallContext context)
   at Orleans.Runtime.GrainMethodInvoker.Invoke()
   at <MyGrainInvoke>",
"RemoteStackTraceString":null,
"RemoteStackIndex":0,
"ExceptionMethod":null,
"HResult":-2146233079,
"Source":"Orleans.Runtime",
"WatsonBuckets":null

```
It occurs during consumer grain subscription to stream. One consumer grain opens more than one subscription (to different streams) and there is only one producer per stream.

Orleans version 3.5.1 is used on net5.0 framework.

**Comment by benjaminpetit** [comment]
I don't recall seeing this issue. Can you repro it reliably?

**Comment by mradovcic** [comment]
I've tried but unfortunately no.

**Comment by rafikiassumani-msft** [comment]
@mradovcic as @benjaminpetit  suggested we will need a repro for this.
