### ISSUE TITLE
System.InvalidOperationException: Collection was modified in SimpleMessageStreamProducerExtension

### ISSUE THREAD

**Issue by dbratus** [dotnet/orleans#7620]
Hello,

Getting exception from the simple message stream provider. The callstack is
```
(Orleans.Streams.PubSubRendezvousGrain) []  Failed to unregister a stream consumer.  Stream: GroupEventsStream-68771922-43d6-4c6a-b4cb-6daabf652ae6-Default, SubscriptionId abee7080-e8a9-45f1-8751-0c4f2562927c
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducerExtension.RemoveSubscriber(GuidId subscriptionId, StreamId streamId)
   at Orleans.Streams.OrleansCodeGenStreamProducerExtensionMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request)
   at Orleans.InvokableObjectManager.LocalObjectMessagePumpAsync(LocalObjectData objectData)
   at Orleans.Streams.PubSubRendezvousGrain.ExecuteProducerTask(PubSubPublisherState producer, Task producerTask)
   at Orleans.Streams.PubSubRendezvousGrain.NotifyProducersOfRemovedSubscription(GuidId subscriptionId, StreamId streamId)
   at Orleans.Streams.PubSubRendezvousGrain.UnregisterConsumer(GuidId subscriptionId, StreamId streamId)
```

Orleans v3.5.0

It seems that it occurs only in high concurrency environment, when multiple grain subscribe/unsubscribe simultaneously to the same stream (we found it during stresstesting).

Looked into SimpleMessageStreamProducerExtension and found that it contains a ConcurrentDictionary within a simple Dictionary. It seems suspicious, as if the class was meant to be thread safe but not completely.

**Comment by benjaminpetit** [comment]
Are you calling `OnNextAsync` without awaiting it in your producer grain?

**Comment by dbratus** [comment]
I've found that this particular event is published from within Task.Run. So, yes, it is not in the grain's async chain.
```
Task.Run(async () =>
    await groupEventsPublisher.Value.Publish(groupEvent));
```
(Here `Publish` simply wraps `OnNextAsync`)

I think this is done to prevent deadlocks.

**Comment by benjaminpetit** [comment]
I think it's possible your race condition comes from here. Using SMS, the first call to `OnNextAsync` modify the dictionary. My guess is that you have several call in parallel that trigger this race condition.

**Comment by dbratus** [comment]
OK, calling `OnNextAsync` from the grain's async context solves the problem. Thank you!
