### ISSUE TITLE
InvalidOperationException occurs in IGrainFactory.GetGrain in Orleans v4.0 preview1

### ISSUE THREAD

**Issue by wangjia184** [dotnet/orleans#7621]
```
new HostBuilder()
.UseOrleans((ISiloBuilder siloBuilder) => {
    siloBuilder.UseLocalhostClustering()
    .Configure<ClusterOptions>(options =>
    {
        options.ClusterId = appSettings.Orleans.ClusterID;
        options.ServiceId = appSettings.Orleans.ServiceID;
    })
    .ConfigureServices(services =>
    {
        InstallServices(services);
    })
    .ConfigureApplicationParts(parts => parts.AddFromApplicationBaseDirectory())
    .ConfigureLogging(logging => logging.AddConsole())
// ...
    ;
}).Build();
```

The above code works well in Orleans v.3.6.0.  But after upgrade to v4.0 preview-1,  `ConfigureApplicationParts` is undefined.

> CS1061	'ISiloBuilder' does not contain a definition for 'ConfigureApplicationParts' and no accessible extension method 'ConfigureApplicationParts' accepting a first argument of type 'ISiloBuilder' could be found (are you missing a using directive or an assembly reference?)

`ConfigureApplicationParts` is removed from v4.0.

And I am encountering the following exception when calling `IGrainFactory.GetGrain<IMyAgentGrain>`

I never saw this type of error when using v3.6.0.  The grain interfaces seems not allowed?
```
System.AggregateException: One or more errors occurred. (Type "BE.MyAgent.Actor.IMyAgentGrain" from assembly "BE.MyAgent.Abstraction" is not allowed. To allow it, add it to TypeManifestOptions.AllowedTypes or register an ITypeFilter instance which allows it.)
       ---> System.InvalidOperationException: Type "BE.MyAgent.Actor.IMyAgentGrain" from assembly "BE.MyAgent.Abstraction" is not allowed. To allow it, add it to TypeManifestOptions.AllowedTypes or register an ITypeFilter instance which allows it.
         at Orleans.Serialization.TypeSystem.TypeConverter.ThrowTypeNotAllowed(QualifiedType& value) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 337
         at Orleans.Serialization.TypeSystem.TypeConverter.ConvertToDisplayName(QualifiedType& input) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 293
         at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.HandleNamedType(NamedTypeSpec type, String assemblyName, Rewriter replaceTypeName) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 75
         at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.ApplyInner(TypeSpec input, String assemblyName, Rewriter replaceFunc) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 32
         at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.HandleAssembly(AssemblyQualifiedTypeSpec type, String assemblyName, Rewriter replaceTypeName) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 115
         at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.ApplyInner(TypeSpec input, String assemblyName, Rewriter replaceFunc) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 33
         at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.Rewrite(TypeSpec input, Rewriter rewriter) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 17
         at Orleans.Serialization.TypeSystem.TypeConverter.FormatInternal(Type type, Func`2 rewriter) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 214
         at Orleans.Serialization.TypeSystem.TypeConverter.Format(Type type, Func`2 rewriter) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 169
         at Orleans.Metadata.GrainInterfaceTypeResolver.GetGrainInterfaceTypeByConvention(Type type) in /_/src/Orleans.Core/Manifest/GrainInterfaceTypeResolver.cs:line 56
         at Orleans.Metadata.GrainInterfaceTypeResolver.GetGrainInterfaceType(Type type) in /_/src/Orleans.Core/Manifest/GrainInterfaceTypeResolver.cs:line 41
         at Orleans.GrainFactory.GetGrain(Type interfaceType, IdSpan grainKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 206
         at Orleans.GrainFactory.GetGrain[TGrainInterface](String primaryKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 60
         --- End of inner exception stack trace ---
```

**Comment by ElanHasson** [comment]
Correct, it's no longer required.

**Comment by wangjia184** [comment]
Thanks @ElanHasson ,  how to tell Orleans to load grains from a specific assembly if I am running multiple services in the same cluster?
