### ISSUE TITLE
InvalidOperationException occurs in IGrainFactory.GetGrain in Orleans v4.0 preview1

### ISSUE THREAD

**Issue by wangjia184** [dotnet/orleans#7623]
A simple grain interface

```
public interface IMyAgentGrain : IGrainWithStringKey
    {
        public Task EnsureActivated();
    }
```

`IGrainFactory.GetGrain<IMyAgentGrain>` raises an exception.

```
System.AggregateException: One or more errors occurred. (Type "BE.MyAgent.Actor.IMyAgentGrain" from assembly "BE.MyAgent.Abstraction" is not allowed. To allow it, add it to TypeManifestOptions.AllowedTypes or register an ITypeFilter instance which allows it.)
       ---> System.InvalidOperationException: Type "BE.MyAgent.Actor.IMyAgentGrain" from assembly "BE.MyAgent.Abstraction" is not allowed. To allow it, add it to TypeManifestOptions.AllowedTypes or register an ITypeFilter instance which allows it.
         at Orleans.Serialization.TypeSystem.TypeConverter.ThrowTypeNotAllowed(QualifiedType& value) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 337
         at Orleans.Serialization.TypeSystem.TypeConverter.ConvertToDisplayName(QualifiedType& input) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 293
         at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.HandleNamedType(NamedTypeSpec type, String assemblyName, Rewriter replaceTypeName) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 75
         at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.ApplyInner(TypeSpec input, String assemblyName, Rewriter replaceFunc) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 32
         at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.HandleAssembly(AssemblyQualifiedTypeSpec type, String assemblyName, Rewriter replaceTypeName) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 115
         at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.ApplyInner(TypeSpec input, String assemblyName, Rewriter replaceFunc) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 33
         at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.Rewrite(TypeSpec input, Rewriter rewriter) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 17
         at Orleans.Serialization.TypeSystem.TypeConverter.FormatInternal(Type type, Func`2 rewriter) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 214
         at Orleans.Serialization.TypeSystem.TypeConverter.Format(Type type, Func`2 rewriter) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 169
         at Orleans.Metadata.GrainInterfaceTypeResolver.GetGrainInterfaceTypeByConvention(Type type) in /_/src/Orleans.Core/Manifest/GrainInterfaceTypeResolver.cs:line 56
         at Orleans.Metadata.GrainInterfaceTypeResolver.GetGrainInterfaceType(Type type) in /_/src/Orleans.Core/Manifest/GrainInterfaceTypeResolver.cs:line 41
         at Orleans.GrainFactory.GetGrain(Type interfaceType, IdSpan grainKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 206
         at Orleans.GrainFactory.GetGrain[TGrainInterface](String primaryKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 60
         --- End of inner exception stack trace ---
```

Never saw this error in v3.6.0.   First time see it in v4.0 preview1.

P.S. `ConfigureApplicationParts` is removed in v4.0,  could that be the reason?

**Comment by ReubenBond** [comment]
You need to ensure that the `Microsoft.Orleans.Sdk` package is installed on all projects (eg client, server, grains, grain interfaces, and data contract projects). You can replace the `Microsoft.Orleans.CodeGenerator.MSBuild` package with the SDK package. This is different from 3.x, where code generator was not installed on the client/server projects.
