### ISSUE TITLE
Clusterin.AdoNet MembershipTableManager and Lifecycle start errors

### ISSUE THREAD

**Issue by cernuto** [dotnet/orleans#7629]
Orleans logs look as usual other than the following errors:

MembershipTableManager failed to start due to errors at stage RuntimeGrainServices (8000): Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
 ---> System.ComponentModel.Win32Exception (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage.ExecuteAsync[TResult](String query, Action`1 parameterProvider, Func`5 executor, Func`4 selector, CancellationToken cancellationToken, CommandBehavior commandBehavior) in /_/src/AdoNet/Shared/Storage/RelationalStorage.cs:line 265
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage.ReadAsync[TResult](String query, Action`1 parameterProvider, Func`4 selector, CancellationToken cancellationToken, CommandBehavior commandBehavior) in /_/src/AdoNet/Shared/Storage/RelationalStorage.cs:line 164
   at Orleans.Clustering.AdoNet.Storage.RelationalOrleansQueries.CreateInstance(String invariantName, String connectionString, IGrainReferenceConverter grainReferenceConverter) in /_/src/AdoNet/Shared/Storage/RelationalOrleansQueries.cs:line 72
   at Orleans.Runtime.MembershipService.AdoNetClusteringTable.InitializeMembershipTable(Boolean tryInitTableVersion) in /_/src/AdoNet/Orleans.Clustering.AdoNet/Messaging/AdoNetClusteringTable.cs:line 36
   at Orleans.Runtime.MembershipService.MembershipTableManager.Start() in /_/src/Orleans.Runtime/MembershipService/MembershipTableManager.cs:line 164
   at Orleans.Runtime.MembershipService.MembershipTableManager.<>c__DisplayClass54_0.<<Orleans-ILifecycleParticipant<Orleans-Runtime-ISiloLifecycle>-Participate>g__OnRuntimeGrainServicesStart|0>d.MoveNext() in /_/src/Orleans.Runtime/MembershipService/MembershipTableManager.cs:line 859
--- End of stack trace from previous location ---
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in /_/src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs:line 135
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:10060,State:0,Class:20

-- and --

Lifecycle start canceled due to errors at stage 8000: Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
 ---> System.ComponentModel.Win32Exception (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage.ExecuteAsync[TResult](String query, Action`1 parameterProvider, Func`5 executor, Func`4 selector, CancellationToken cancellationToken, CommandBehavior commandBehavior) in /_/src/AdoNet/Shared/Storage/RelationalStorage.cs:line 265
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage.ReadAsync[TResult](String query, Action`1 parameterProvider, Func`4 selector, CancellationToken cancellationToken, CommandBehavior commandBehavior) in /_/src/AdoNet/Shared/Storage/RelationalStorage.cs:line 164
   at Orleans.Clustering.AdoNet.Storage.RelationalOrleansQueries.CreateInstance(String invariantName, String connectionString, IGrainReferenceConverter grainReferenceConverter) in /_/src/AdoNet/Shared/Storage/RelationalOrleansQueries.cs:line 72
   at Orleans.Runtime.MembershipService.AdoNetClusteringTable.InitializeMembershipTable(Boolean tryInitTableVersion) in /_/src/AdoNet/Orleans.Clustering.AdoNet/Messaging/AdoNetClusteringTable.cs:line 36
   at Orleans.Runtime.MembershipService.MembershipTableManager.Start() in /_/src/Orleans.Runtime/MembershipService/MembershipTableManager.cs:line 164
   at Orleans.Runtime.MembershipService.MembershipTableManager.<>c__DisplayClass54_0.<<Orleans-ILifecycleParticipant<Orleans-Runtime-ISiloLifecycle>-Participate>g__OnRuntimeGrainServicesStart|0>d.MoveNext() in /_/src/Orleans.Runtime/MembershipService/MembershipTableManager.cs:line 859
--- End of stack trace from previous location ---
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in /_/src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs:line 135
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct) in /_/src/Orleans.Core/Lifecycle/LifecycleSubject.cs:line 97
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:10060,State:0,Class:20

Possibly the reason old entries never get cleared out of OrleansMembershipTable?

**Comment by pmorelli92** [comment]
Did you check your table? Did it have registries of non available instances with a status different than 6? When your silo stops executing, are you calling the Stop and Stopped methods?

**Comment by cernuto** [comment]
Yes, they're all status 6 in the dev environment:
![image](https://user-images.githubusercontent.com/37497959/158071763-32c33e0a-6a91-488b-ba78-697b06315fe3.png)

So, I added a stop/stopped graceful shutdown implementation. I haven't figured out a way to test it yet in service fabric as it's dependent upon service fabric's OnCloseAsync() which doesn't get called when you stop the debugger. Perhaps there's a way in PS to gracefully stop a SF node.

It's still not clear to me how this is causing a SQL connection error?

**Comment by pmorelli92** [comment]
> It's still not clear to me how this is causing a SQL connection error?

Yeah for sure that should not have to do with what entries are or are not on the membership table.

> Yes, they're all status 6 in the dev environment

As long as the old entries are 6 it is not a problem with the silo trying to communicate with other "dead" silos. So I believe this has nothing to do with that.

Can you add a ping SQL statement before the silo gets started to see if that triggers the SQL error as well? If a ping fails then this is not Orleans related and more SQL connection related such as an IP restriction or something not allowing the program to connect to the SQL server.

**Comment by cernuto** [comment]
Let me clarify - when these exceptions are logged the silos do still connect to SQL server and insert OrleansMembershipTable entries. The silos even comm. with one another including the clients. 

The exceptions are something particular to MembershipTableManager?
