### ISSUE TITLE
EventHub Stream Provider doesn't refresh cursor on new data

### ISSUE THREAD

**Issue by davidvanchu** [dotnet/orleans#7686]
I noticed 2 different (bad) behaviors depending on the configured `StreamInactivityPeriod` and `StreamCacheEvictionOptions`, one of which results in lost messages and the other results in duplicate events being delivered.

Note in these scenarios, events A, B, C, D refer to events intended for this specific `streamId`, although other events may come in between events A and B for other `streamId`s, handled by the same PersistentStreamPullingAgent. I believe this is necessary to evict event A from the cache before event B arrives.

1. If `StreamInactivityPeriod` is greater than the time an event is likely to be in the cache, let's say `StreamInactivityPeriod` = 60 minutes events are cached for 30 mins before being evicted:
* An event A comes in, is successfully processed. Cursor state is now Idle.
* Event A is evicted from the cache after 30 minutes.
* Events B, C, D, E come in after 45 minutes. `PersistentStreamPullingAgent` will call `StartInactiveCursors()` on the existing `streamData` it gets from the `pubSubCache`.
* `consumerData.Cursor?.Refresh(startToken)` is called. Currently this is a no-op with the EventHub provider.
* Cursor tries to resume at event A. (Instead of event B as one might expect?)
* `QueueCacheMissException` occurs.
* It tries to recover by setting the cursor to the newest message in the cache. It will start at event E, losing event B, C, and D.

2. If `StreamInactivityPeriod` = 30 mins, events cached for 60 minutes:
* An event A comes in, is successfully processed. Cursor state is now Idle.
* Events B, C, D, E come in after 10 minutes. `PersistentStreamPullingAgent` will call `StartInactiveCursors()` on the existing `streamData` it gets from the `pubSubCache`.
* `consumerData.Cusor?.Refresh(startToken)` is called. Currently this is a no-op with the EventHub provider.
* Cursor tries to resume at event A. (Instead of event B as one might expect?)
* Event A is still in the cache, duplicate occurs.

My thought is that scenarios 1 and 2 would behave more as expected if RefreshCursor was implemented properly on the `Cursor` inside `EventHubAdapterReceiver`. Does that make sense to anyone more familiar with this code?

IQueueCacheCusor Refresh():
https://github.com/dotnet/orleans/blob/main/src/Orleans.Streaming/QueueAdapters/IQueueCacheCursor.cs#L31
SimpleQueueCacheCursor implementation:
https://github.com/dotnet/orleans/blob/main/src/Orleans.Streaming/Common/SimpleCache/SimpleQueueCacheCursor.cs#L102
Cursor inside EventHubAdapterReceiver implementation:
https://github.com/dotnet/orleans/blob/main/src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubAdapterReceiver.cs#L341

**Comment by benjaminpetit** [comment]
Is it a behavior that you see in real life, or is it just observation from the code?

> Cursor tries to resume at event A. (Instead of event B as one might expect?)

Because the implementation of the cursor always points to the latest event processed. If you look in the code, before calling `cursor.GetCurrent()` we do a call to `cursor.MoveNext()`. If `MoveNext` returned false, that mean that we could not advance the cursor, so in this case it will still point to event `A`.

For scenario 1: 
We actually track the last purged element on a per stream basis to avoid if possible a unecessary `QueueCacheMissException`: see the logic [here](https://github.com/dotnet/orleans/blob/f9299762e433ed2b426f7a6e676776d224f13f52/src/Orleans.Streaming/Common/PooledCache/PooledQueueCache.cs#L210). By default we keep track of the last purged element for a stream for 10 min (`StreamCacheEvictionOptions.DefaultMetadataMinTimeInCache`)
But we will throw a `QueueCacheMissException` if we cannot be 100% sure that nothing was missed. Orleans will set the cursor to the last element in the cache to avoid infinite cache miss exception, if your consumer is too slow for example. You can configure a `IStreamFailureHandler` to fault the subscription and not deliver element to that consumer anymore. The consumer has been notified via `OnError`, so it could resubscribre with a different token for example.

For scenario 2:
Not sure to understand, since like I said earlier, we always try to call `cursor.MoveNext()` before calling `cursor.GetCurrent()`.

Maybe we should remove this `consumerData.Cursor?.Refresh(startToken)` call and move the logic of `SimpleQueueCacheCursor` in `MoveNext()` like other cursor implementations.

**Comment by davidvanchu** [comment]
This is behavior I see in real usage. 

> Because the implementation of the cursor always points to the latest event processed. If you look in the code, before calling cursor.GetCurrent() we do a call to cursor.MoveNext(). If MoveNext returned false, that mean that we could not advance the cursor, so in this case it will still point to event A.

The QueueCacheMissException in this case occurs during the call to `cursor.MoveNext()`:

```
Exception:
Message:Item not found in cache.  Requested: EventHubSequenceToken(EventHubOffset: , SequenceNumber: 2702051, EventIndex: 0), Low: EventHubSequenceToken(EventHubOffset: , SequenceNumber: 2703091, EventIndex: 0), High: EventHubSequenceToken(EventHubOffset: , SequenceNumber: 2703352, EventIndex: 0)
StackTrace:   at Orleans.Providers.Streams.Common.PooledQueueCache.SetCursor(Cursor cursor, StreamSequenceToken sequenceToken)
   at Orleans.Providers.Streams.Common.PooledQueueCache.TryGetNextMessage(Object cursorObj, IBatchContainer& message)
   at Orleans.ServiceBus.Providers.EventHubQueueCache.TryGetNextMessage(Object cursorObj, IBatchContainer& message)
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.Cursor.MoveNext()
   at Orleans.Streams.PersistentStreamPullingAgent.GetBatchForConsumer(IQueueCacheCursor cursor, IStreamFilterPredicateWrapper filterWrapper, StreamId streamId)
   at Orleans.Streams.PersistentStreamPullingAgent.RunConsumerCursor(StreamConsumerData consumerData, IStreamFilterPredicateWrapper filterWrapper)
Type:Orleans.Streams.QueueCacheMissException
```

In `PooledQueueCache.TryGetNextMessage`, it calls `cursor.SetCursor(cursor, cursor.SequenceToken)`,  where `cursor.SequenceToken` is latest event processed event A.
If event A is no longer in the cache, it throws the `QueueCacheMissException`, and then following the stack trace back up to `RunConsumerCursor()`, where it catches the exception and it recovers by starting at newest item in the cache instead of event B. (`consumerData.Cursor = queueCache.GetCacheCursor(consumerData.StreamId, null);`)

**Comment by benjaminpetit** [comment]
> In PooledQueueCache.TryGetNextMessage, it calls cursor.SetCursor(cursor, cursor.SequenceToken), where cursor.SequenceToken is latest event processed event A.
If event A is no longer in the cache, it throws the QueueCacheMissException, and then following the stack trace back up to RunConsumerCursor(), where it catches the exception and it recovers by starting at newest item in the cache instead of event B. (consumerData.Cursor = queueCache.GetCacheCursor(consumerData.StreamId, null);)

Yep, like I said earlier, that's the intended behavior: in this case we cannot guarantee that we didn't miss anything, so you will get a cache miss exception. If the `lastPurgedToken` check was not successful, we cannot be 100% sure that there was no event between A and B. That's why we point to A, to be able to start processing starting from this event.

If you hit a `QueueCacheMissException`, we will then skip to the freshest entry in the cache. We want to avoid a case where a slow consumer is triggering multiple exception in a row.

Scenario 2 shouldn't happen. If the token isn't in the pubsub cache anymore, the pulling agent will ask directly the consumer the token value of the latest element sent.
My guess is that your consumer was deactivated, its entry in the pubsub cache removed. Once reactivated because of stream activity, I assume you resumed/subscribed with a null token? Subscribing with a null token ask to start from the oldest element in the stream., in this case element A.

**Comment by davidvanchu** [comment]
Thanks for the explanations!

> Scenario 2 shouldn't happen. If the token isn't in the pubsub cache anymore, the pulling agent will ask directly the consumer the token value of the latest element sent.
My guess is that your consumer was deactivated, its entry in the pubsub cache removed. Once reactivated because of stream activity, I assume you resumed/subscribed with a null token? Subscribing with a null token ask to start from the oldest element in the stream., in this case element A.

Can you point me to the code that starts from oldest element in the stream (is this the same as oldest message in the cache?) if subscribing with null token? I wasn't able to find this.

Yes, we are resuming with null token. When resuming a deactivated consumer with null token, we are seeing `QueueCacheMissException`s here too, if both:

1. Consumer is deactivated, no longer in the `pubSubCache`, such that the next element that reactivates the stream causes the pullingAgent to go through `DoHandshakeWithConsumer()`, and
2. the last element processed `A` was also evicted from the cache.

This is the stack trace for when we resume, passing in no token:

```
Exception:
Message:Item not found in cache.  Requested: EventHubSequenceToken(EventHubOffset: 811755415544, SequenceNumber: 2905478, EventIndex: 0), Low: EventHubSequenceToken(EventHubOffset: , SequenceNumber: 2906038, EventIndex: 0), High: EventHubSequenceToken(EventHubOffset: , SequenceNumber: 2906529, EventIndex: 0)
StackTrace:   at Orleans.Providers.Streams.Common.PooledQueueCache.SetCursor(Cursor cursor, StreamSequenceToken sequenceToken)
   at Orleans.ServiceBus.Providers.EventHubQueueCache.GetCursor(IStreamIdentity streamIdentity, StreamSequenceToken sequenceToken)
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.GetCacheCursor(IStreamIdentity streamIdentity, StreamSequenceToken token)
   at Orleans.Streams.PersistentStreamPullingAgent.DoHandshakeWithConsumer(StreamConsumerData consumerData, StreamSequenceToken cacheToken)
Type:Orleans.Streams.QueueCacheMissException
```

How could this happen if resuming with null token starts at oldest message in the cache?

It seems like this recovers by then resuming at element `B` (the element that reactivates the stream) in this case, which would be okay. Is that true, that it resumes at element `B`? 

I am referencing this: https://github.com/dotnet/orleans/blob/main/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L279-L319

See: `catch` the `QueueCacheMissException` on line 302, and then set cursor using element B's `cacheToken` (since it is what reactivated the stream) on line 319?

**Comment by davidvanchu** [comment]
Do you have any general recommendations on configuration of:

StreamInactivityPeriod
DataMinTimeInCache
DataMaxAgeInCache
MetadataMinTimeInCache

By default, MaxAgeInCache and StreamInactivityPeriod are both = 30 minutes. Should these be kept in sync?
Is it a bad idea (resource-wise) to increase MetadataMinTimeInCache beyond 10 minutes? Say, 30 minutes, or multiple hours?

From our experimentation it seemed like having a long StreamInactivityPeriod compared to cache time is bad (leads to those QueueCacheMissExceptions that recover by starting at newest message). Are there other bad configurations, such has having a much shorter StreamInactivityPeriod compared to cache time?

**Comment by benjaminpetit** [comment]
> Can you point me to the code that starts from oldest element in the stream (is this the same as oldest message in the cache?) if subscribing with null token? I wasn't able to find this.

Sorry I was wrong earlier let me try to explain:
- if a consumer subscribe to a stream with a null token, and this stream is still in the pubsub cache of the pulling agent, you will not get the event in the event cache, you will only get event that will come after your call to subscribe
- if a consumer is woke up by a stream item, and the consumer resume with a null token, the first item you will get is the item that triggered the reactivation. This logic is in the [pulling agent code](https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L482)

In your case, if the consumer is not activated anymore, resubscribe with a null token AND there is no reference to the stream in the pubsub cache, then I don't see how the pulling agent would try to start from A, since there is no reference of A anywhere. Are you 100% that the stream was no longer in the pubsub cache? It's possible to have a race condition here if the pubsub cache wasn't cleared.

For what values I would use:
- `DataMinTimeInCache`: application dependant
- `DataMaxAgeInCache`: application dependant. How much stream traffic do you see, how big are your expected events, how much memory can you spare?
- `StreamInactivityPeriod`: the default value is 30 min, like the default value of DataMaxAgeInCache, but I would use something lower than the configured DataMaxAgeInCache value, to avoid a possible race condition (that should be avoided with the help of `MetadataMinTimeInCache`). It should never be more than `DataMaxAgeInCache`.
- `MetadataMinTimeInCache`: application dependant. The default is 10 min. It's basically how much time will you get a reference to the last purged token for a given stream. The biggest value the better, but it consumer a lot of memory if you have a lot of different streams. But remember that's an in memory cache, it's not written to storage.

And these values are correlated to the configured `CollectionAge` for consumer. As long as the consumer isn't deactivate/reactivated and call subscribe again, the token used will always point to the latest processed element.

For example (by keeping the default configured values), let's say your consumer X received element A from stream 123, then nothing for 45 min. Stream 123 will be purged from the pubsub cache and from the metadata cache. Element A will be removed from the steam cache too.

Now element B for stream 123 arrives. The pulling agent doesn't have a reference to that stream in its cache, so it will get the list of subscribers. When adding a new consumer, the pulling agent will do a handshake with X, to ask which element was last processed.

From the handshake, consumer X returns the token pointing to element A... that is no longer in the cache. So you will get a cache miss exception.

**Comment by davidvanchu** [comment]
I am no longer sure why I am seeing duplicate events delivered, I will have to look at this further, but for now we can forget this.

I did not take into account the CollectionAge of the consumer, you're right that the consumer is still active. I was confusing this with the StreamInactivityPeriod.

So in this situation (no longer Scenario 2, I just wanted to clarify recovery behavior outlined in your example at the bottom of your most recent reply):
* consumer is active
* stream is inactive
* last item processed `A` is no longer in cache
* metadata with information on last purged token is also no longer in cache
* message `B` (and `C`, `D`) comes in, stream wakes up and during Handshake, asks for consumer's last processed item `A` (just to see if it should throw QueueCacheMiss or not, it won't actually deliver item `A` again)
* QueueCacheMissException occurs
* start at `B`

Is this right? The difference here, is if stream is _active_, it starts at newest = `D` instead of `B`.

Stream is active it does this: https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L560

Stream is inactive, it does this: https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L319

Our use case:
We have many devices, each represented by a grain.

This grain is implicitly subscribed (using it's device guid, to only receive messages intended for that specific device grain) to an Event Hub stream. The stream is a single EH stream which services all (300k+, not all active at the same time) devices, but split into 32 partitions. The contents of which are message traffic generated by the physical device.

An individual device may send traffic often, say dozens (more likely) to hundreds (less likely) of messages an hour, or go somewhat inactive and send 1 message every hour, or be off, in which case it sends no messages, depending on the user. Some are power users and use it every day throughout the day, others use it on the weekends, and others use it only a few times a year.

It sounds like we can increase MetadataMinTimeInCache since it is only 1 stream (or 32 streams, one per partition? depending on your definition) and won't take up too much memory. From my understanding, this is a dictionary per partition which is <StreamIdentity, (DateTime, Token)> where StreamIddentity is per device in this case?

Min/MaxTimeInCache we are less inclined to increase due to memory constraints. We get about 24k events per hour.

So far we have decided on:
StreamInactivityPeriod = 20 mins
DataMinTimeInCache = 15 mins
DataMaxAgeInCache = 20 mins
MetadataMinTimeInCache = 30 mins

Perhaps all we should change is set StreamInactivityPeriod to 19 minutes to avoid the race condition you mentioned.

**Comment by davidvanchu** [comment]
I think I was able to figure out the duplicates I am seeing. I hope you can verify the behavior.

Conditions:
1. Consumer(grain) is active
2. Stream is inactive
3. Last item processed by grain is in cache.
---
1. Since the Stream is inactive, the Pulling Agent goes through the `DoHandshakeWithConsumer` function: 
https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L270-L272
2. Since the consumer (the grain) is still active, it will return the last token it processed as the `requestedHandshakeToken`:
https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L281-L287
3. Use it to set Cursor:
https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L292
https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/Common/PooledCache/PooledQueueCache.cs#L242-L264
It then sets `cursor.Index` to the sequence token from step 2 (this is important later!). Note that `cursor.State` is not equal to `CursorStates.Idle` (it is `Unset`), so it skips moving to the next message here, and sets `cursor.SequenceToken` and `cursor.State` = `CursorStates.Set`.
4. Handshake complete.
5. `RunConsumerCursor` is called:
https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L266
6. Then `GetBatchForContainer` from there: https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L550
7. `cursor.MoveNext`
https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L622
https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubAdapterReceiver.cs#L329-L337
8. `TryGetNextMessage`. Note: This will `out IBatchContainer message` as `out next` above, and sets `this.current` = `next`. This is important: https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/Common/PooledCache/PooledQueueCache.cs#L273
9. `cursor.State` is `Set` (from step 3), skips the `if` here:
https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/Common/PooledCache/PooledQueueCache.cs#L288-L295
10. Sets the `currentMessage`, which is eventually used to `out message`, equal to `cursor.Message`. This is the message at the `CurrentBlock.Value[Index]`, which is the last one processed, per step 3:
https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/Common/PooledCache/PooledQueueCache.cs#L311
11. Sets the `cursor.Index` to the next message and `cursor.SequenceToken` using that `cursor.Index`. and returns true:
https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/Common/PooledCache/PooledQueueCache.cs#L331-L339
12. `GetBatchForConsumer` returns what is in `cursor.current`, which is the last one processed, as set in step 7. It is then processed again:
https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L627
https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L574-L580

**Comment by benjaminpetit** [comment]
> Is this right? The difference here, is if stream is active, it starts at newest = D instead of B.

Correct

> It sounds like we can increase MetadataMinTimeInCache since it is only 1 stream (or 32 streams, one per partition? depending on your definition) and won't take up too much memory. From my understanding, this is a dictionary per partition which is <StreamIdentity, (DateTime, Token)> where StreamIddentity is per device in this case?

No, in your case you have one stream per device? Unless I am not understanding correctly.

The values you chose seems fine to me, but what's the value for `CollectionAge`. You also could handle the cache miss exception if you know you didn't received any event for X minutes for example.

---

I was able to repro the issue with duplicate events like in your last scenario. EventHub is considered "deliver at least once" , but I think it's still a bug since we could avoid it.

I will need some time to work on a potential fix

**Comment by benjaminpetit** [comment]
That means 1 stream per device.

If you didn't change `CollectionAge` you might get unwanted cache exception. But you could choose to ignore them if you see that we didn't receive any stream event for X minutes.

The workaround is pretty simple in your case, you can just ignore stream token equals or older than the latest received token.

Thank you so much for the investigation, it's greatly appreciated. I am not sure since when we do have this issue, I don't recall any recent change that could have introduced this.

**Comment by ReubenBond** [comment]
Both paths reported here are addressed in main. Idle Event Hubs cursors refresh to the first new event (#10266), delivery cache misses recover inclusively from retained data (#9711/#9714), and acknowledged-token recovery skips the acknowledged item while preserving the first newer batch (#10936/#11149). Together these cover the idle-cursor loss and duplicate-on-reactivation cases in the discussion. Closing as completed.
