### ISSUE TITLE
Silo continues to run when asp.net hosted service crashed

### ISSUE THREAD

**Issue by christallire** [dotnet/orleans#7711]
Hi guys,

There's some edge case I've observed during the failure of asp.net hosted service StartAsync.

It immediately prints
```
[03:44:52 INF] HostedClient completed processing all messages. Shutting down.
```

And then start logging below.

```
[03:44:53 INF] Message was queued for sending after outbound queue was stopped: Response S10.0.28.149:11111:389245486*stg/DeploymentLoadPublisher/00000016@S00000016->S10.0.11.48:11111:389245108*stg/DeploymentLoadPublisher/00000016@S00000016 #2362
[03:44:53 WRN] Did not get response for probe #1 to silo S10.0.8.126:11111:389245346 after 00:00:00.0001218. Current number of consecutive failed probes is 1
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Orleans.Runtime.MembershipService.RemoteSiloProber.Probe(SiloAddress remoteSilo, Int32 probeNumber) in /_/src/Orleans.Runtime/MembershipService/RemoteSiloProber.cs:line 20
   at Orleans.Runtime.MembershipService.SiloHealthMonitor.ProbeDirectly(CancellationToken cancellation) in /_/src/Orleans.Runtime/MembershipService/SiloHealthMonitor.cs:line 240
```

The problem is silo keeps running, even though the host is stopped. and SiloHealthMonitor doesn't handle ObjectDisposedException and keeps probing, which leads to voting every other silo as a dead silo. this is critical especially when we're horizontally scaling, so many replicas fail at the same time, which puts the entire cluster to fail almost immediately.

My suggestion is:
1) Implement IDisposable at
https://github.com/dotnet/orleans/blob/7333134d339d13a61c0bd8de4b695ae7c439395f/src/Orleans.Runtime/Hosting/SiloHostedService.cs#L11
or register handler at IApplicationLifetimeService because StopAsync is not always called as per asp.net doc
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio#stopasync

2) Don't make SiloHealthMonitor swallow all exception and retry

I've tried to fix 1) but there's no clear way to await end of silo's execution and stop other than `void Stop()` method and I don't like it.

(Related issue: https://github.com/dotnet/orleans/issues/7505)

**Comment by ReubenBond** [comment]
Do you know the root cause for the failure?

**Comment by christallire** [comment]
see my analysis

2022년 5월 6일 (금) 오후 11:05, Reuben Bond ***@***.***>님이 작성:

**Comment by ReubenBond** [comment]
It's not clear to me why the very first thing you describe happens (`HostedClient completed processing all messages. Shutting down.`). Could you show what your Program.cs looks like?

**Comment by christallire** [comment]
It's a bit complicated to show you since it's part of the internal framework and all start-up logic is split into several classes.

but basically, I added problematic service via `serviceCollection.AddHostedService<T>()` and 
Orleans is configured via `hostBuilder.UseOrleans(...);`

and from the log `HostedClient completed processing all messages. Shutting down.` is telling me that the silo is starting or started already.

**Comment by ReubenBond** [comment]
Could you show me the actual hosting code? I.e, the thing which creates and starts the host and calls UseOrleans?

**Comment by abbottdev** [comment]
@ReubenBond I actually stumbled across this myself but I have a longer log message with hopefully some additional context.

When I've experienced this issue, has been when I have a bad/dead silo in my membership store. When I run my Orleans service, it starts, then tries to clean the dead silos, and then an exception occurs (hard to see/figure what it is in the depths of the logs).

Looks like the Watchdog class does some additional writing to objects as they're being disposed of on shutdown from the DI container? Obviously I'm seeing EventLogInternal as that's a windows thing, but I assume the same would hold true for other IDisposable log targets. 

Hopefully this helps - I'll attach a full output from the stack on startup below.
[log.txt](https://github.com/dotnet/orleans/files/12458490/log.txt)

Orleans setup:
```

builder.Host.UseOrleans((ctx, siloBuilder) =>
{
    siloBuilder
        .ConfigureServices(
            services => services.AddMongoDBMembershipTable((MongoDBMembershipTableOptions o) => configuration.Bind("MongoDB:Clustering", o))
        )
        .AddMemoryStreams(Constants.StreamProvider)
        .UseMongoDBClient(configuration.GetValue<string>("MongoDB:ConnectionString"))
        .UseMongoDBReminders((MongoDBRemindersOptions c) => configuration.Bind("MongoDB:Reminders", c))
        .AddMongoDBGrainStorage("Default", (MongoDBGrainStorageOptions o) => configuration.Bind("MongoDB:GrainStorage:Default", o))
        .AddStartupTask<App.Api.Tasks.EnsureMovements>()
        .AddStartupTask<App.Api.Tasks.EnsureTags>()
        .AddStartupTask<App.Api.Tasks.EnsureSampleGyms>();

    if (ctx.HostingEnvironment.IsDevelopment())
    {
        siloBuilder.UseMongoDBClustering((MongoDBMembershipTableOptions options) => configuration.Bind("MongoDB:Clustering", options));
    }
    else
    {
        siloBuilder.UseKubernetesHosting();
    }
});
```

Exerpt from Logs:
```
[S172.20.80.1:11111:52264297 sys.svc.load-publisher/172.20.80.1:11111@52264297] Orleans.Runtime.IDeploymentLoadPublisherOrleans.Runtime.IDeploymentLoadPublisher.UpdateRuntimeStatistics(S172.20.80.1:11111:52264297, SiloRuntimeStatistics: ActivationCount=19 RecentlyUsedActivationCount=0 CpuUsage=<unset> AvailableMemory= MemoryUsage=16388080 IsOverloaded=False ClientCount=0 TotalPhysicalMemory= DateTime=28/08/2023 21:51:51) #91
warn: Orleans.Runtime.MembershipService.SiloHealthMonitor[100613]
      Did not get response for probe #3 to silo S172.20.0.1:11111:47430909 after 00:00:00.0001149. Current number of consecutive failed probes is 3
      System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'IServiceProvider'.
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Orleans.Runtime.MembershipService.RemoteSiloProber.Probe(SiloAddress remoteSilo, Int32 probeNumber) in /_/src/Orleans.Runtime/MembershipService/RemoteSiloProber.cs:line 20
         at Orleans.Runtime.MembershipService.SiloHealthMonitor.ProbeDirectly(CancellationToken cancellation) in /_/src/Orleans.Runtime/MembershipService/SiloHealthMonitor.cs:line 242
fail: Orleans.Runtime.Watchdog[102602]
      Watchdog encountered an internal error
      System.AggregateException: An error occurred while writing to logger(s). (Cannot access a disposed object.
      Object name: 'EventLogInternal'.)
       ---> System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'EventLogInternal'.
         at System.Diagnostics.EventLogInternal.OpenForWrite(String currentMachineName)
         at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName)
         at System.Diagnostics.EventLogInternal.WriteEvent(EventInstance instance, Byte[] data, Object[] values)
         at Microsoft.Extensions.Logging.EventLog.WindowsEventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category)
         at Microsoft.Extensions.Logging.EventLog.EventLogLogger.WriteMessage(String message, EventLogEntryType eventLogEntryType, Int32 eventId)
         at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|13_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
         --- End of inner exception stack trace ---
         at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
         at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
         at Microsoft.Extensions.Logging.LoggerExtensions.LogWarning(ILogger logger, EventId eventId, String message, Object[] args)
         at Orleans.Runtime.Watchdog.CheckYourOwnHealth(DateTime lastCheckt, ILogger logger) in /_/src/Orleans.Runtime/Silo/Watchdog.cs:line 124
         at Orleans.Runtime.Watchdog.WatchdogHeartbeatTick() in /_/src/Orleans.Runtime/Silo/Watchdog.cs:line 71
         at Orleans.Runtime.Watchdog.Run() in /_/src/Orleans.Runtime/Silo/Watchdog.cs:line 53
info: Orleans.Runtime.Messaging.MessageCenter[100115]
      Message was queued for sending after outbound queue was stopped: Request [S172.20.80.1:11111:52264297 sys.svc.load-publisher/172.20.80.1:11111@52264297]->[S172.20.0.1:11111:47430909 sys.svc.load-publisher/172.20.0.1:11111@47430909] Orleans.Runtime.IDeploymentLoadPublisherOrleans.Runtime.IDeploymentLoadPublisher.UpdateRuntimeStatistics(S172.20.80.1:11111:52264297, SiloRuntimeStatistics: ActivationCount=19 RecentlyUsedActivationCount=0 CpuUsage=<unset> AvailableMemory= MemoryUsage=16388080 IsOverloaded=False ClientCount=0 TotalPhysicalMemory= DateTime=28/08/2023 21:51:51) #92
fail: Orleans.Runtime.MembershipService.SiloHealthMonitor[0]
      Exception monitoring silo S172.20.0.1:11111:47430909
      System.AggregateException: An error occurred while writing to logger(s). (Cannot access a disposed object.
      Object name: 'EventLogInternal'.)
       ---> System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'EventLogInternal'.
         at System.Diagnostics.EventLogInternal.OpenForWrite(String currentMachineName)
         at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName)
         at System.Diagnostics.EventLogInternal.WriteEvent(EventInstance instance, Byte[] data, Object[] values)
         at Microsoft.Extensions.Logging.EventLog.WindowsEventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category)
         at Microsoft.Extensions.Logging.EventLog.EventLogLogger.WUnhandled exception. riteMessage(String message, EventLogEntryType eventLogEntryType, Int32 eventId)
         at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|13_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
         --- End of inner exception stack trace ---
```
