### ISSUE TITLE
Flaky test: `ManyConcurrentInvocationsOnActivationLimitedStatelessWorkerDoesNotFail`

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#7730]
Eg, on a pr-build machine `System.TimeoutException : Response did not arrive on time in 00:00:30 for message:  Request [ sys.client/c8f709f53d0142aeadafb83f3dfa5ed6 @008f25806dd54c90b67b4da669f0e502]->[S127.0.0.1:44811:0 statelessworker/41 @00000000000000000000000000000000] UnitTests.GrainInterfaces.IStatelessWorkerGrainUnitTests.GrainInterfaces.IStatelessWorkerGrain.DummyCall() #2100. Target History is: S127.0.0.1:44811:0:statelessworker/41:.`

Stack:
`   at Orleans.Serialization.Invocation.ResponseCompletionSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 107
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at DefaultCluster.Tests.General.StatelessWorkerTests.ManyConcurrentInvocationsOnActivationLimitedStatelessWorkerDoesNotFail() in C:\agent\_work\4\s\test\DefaultCluster.Tests\StatelessWorkerTests.cs:line 108
--- End of stack trace from previous location ---`

https://orleans.visualstudio.com/GitHub%20-%20PR%20Builds/_build/results?buildId=52336&view=ms.vss-test-web.build-test-results-tab&runId=1056476&resultId=100003&paneView=debug

**Comment by ReubenBond** [comment]
This is not flaky anymore
