### ISSUE TITLE
JournaledGrain activating grain first calling state was return null 

### ISSUE THREAD

**Issue by onurcanyilmaz** [dotnet/orleans#7734]
Hello,

I have null reference exception when Journaled grain activate.

.NET 6
ASP.NET CORE

This is my program.cs silosettings
```cs
 siloBuilder.UseLocalhostClustering();

 siloBuilder.AddMemoryGrainStorage("MYKEY")
               .AddMemoryGrainStorageAsDefault();

 siloBuilder.Configure<EndpointOptions>(options =>
    {
        options.AdvertisedIPAddress = IPAddress.Loopback;
        options.GatewayListeningEndpoint = new IPEndPoint(IPAddress.Any, EndpointOptions.DEFAULT_GATEWAY_PORT);
        options.SiloListeningEndpoint = new IPEndPoint(IPAddress.Any, EndpointOptions.DEFAULT_SILO_PORT);
    });

  siloBuilder.Configure<ClusterOptions>(options =>
    {
        options.ClusterId = "my-x-cluster";
        options.ServiceId = "my-x-service";
    });

  siloBuilder.Configure<GrainCollectionOptions>(options =>
    {
        options.CollectionAge = TimeSpan.FromSeconds(61);
    });
```
This is my JournaledGrain

OnActivateAsync:

```cs
  public async override Task OnActivateAsync()
        {
            grainStream = $"KEY({this.GetPrimaryKeyString()})";

            _logger.LogInformation("OnActivateAsync--{grainStream}", grainStream);
        }
```

When I triggered that method, the RaiseEvent update the grain state. OK

```cs
public async Task NewItem(NewItemDto newItem)
{
           await RaiseEvent(new NewItemAddedEvent());
}
```

This is my State class
```cs
public LinkedList<string> Actions { get; set; }

public ActionState Apply(NewItemAddedEvent evnt)
{
        if (Actions is null)
                Actions = new LinkedList<string>();

            Actions.AddLast("The new item");
            return this;
}
```

After when grain is activate, I call that method and I successfully getting my state. OK.

```cs
public async Task<List<string>> GetActions() => await Task.FromResult(State.Actions.ToList());
```

But when grain is deactivate, I call GetActions method, i m getting exception on State properties(Actions). Actually, grain does not update state.
But second calls successfully getting actions

```cs
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

In this situation what can I do something.

Thanks.

**Comment by onurcanyilmaz** [comment]
Hello again,
I have a solution about that situation 

When I override OnActivateAsync, I forgot to call base.OnActivateAsync(); 
Currently, states runs succesfully.

if you have a question mark in your mind, you can evaluate that otherwise issue can close

Thanks.

**Comment by ReubenBond** [comment]
Thank you for investigating and fixing the issue, @onurcanyilmaz! Apologies for not responding sooner
