### ISSUE TITLE
Flaky test: `ClusterHealthMonitorTests.ClusterHealthMonitor_NoIndirectProbes`

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#7743]
Looks like a race condition surrounding creation of new silo monitors, but needs investigation
```
Assert.NotEmpty() Failure

   at NonSilo.Tests.Membership.ClusterHealthMonitorTests.ClusterHealthMonitor_BasicScenario_Runner(Boolean enableIndirectProbes, Nullable`1 numVotesForDeathDeclaration) in C:\agent\_work\7\s\test\NonSilo.Tests\Membership\ClusterHealthMonitorTests.cs:line 219
   at NonSilo.Tests.Membership.ClusterHealthMonitorTests.ClusterHealthMonitor_NoIndirectProbes() in C:\agent\_work\7\s\test\NonSilo.Tests\Membership\ClusterHealthMonitorTests.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by ReubenBond** [comment]
Hopefully fixed by #7754
