### ISSUE TITLE
Reminder Unregister Null exception when high load

### ISSUE THREAD

**Issue by sanzor** [dotnet/orleans#7744]
IMPORTANT ! 
The below behaviour does happen only when i load test the application ! In non heavy load scenario the behaviour does not reproduce 
!!!!!!!!!!!!!!!!!!!!

I am using Reminders in my Orleans application, and i have a `JournaledGrain` that does implement the `IRemindable` interface. At the end of the flow i make sure i use `UnregisterAsync`. The reminder gets registered with the grain's identity.The `IReminder` is not saved in the state but is retrieved by using the `GetReminder `method of the grain.

The problem: Even though i do a null check and then unregister the reminder i still get an ArgumentNullException when calling the `UnregisterAsync` method.

Original issue on [Stackoverflow](https://stackoverflow.com/questions/72283347/argumentnullexception-when-unregistering-reminder-despite-null-check)

**Grain**
```
public PaymentGrain: JournaledGrain<Something, SomethingElse>,IRemindable,IGrainWithGuidKey
{
     public async Task RegisterAsync()
     {
             var reminder = await this.RegisterOrUpdateReminder(
                this.GetPrimaryKey().ToString(),
                TimeSpan.FromHours(3),
                TimeSpan.FromMinutes(10));
     }

    //the place where the reminder is unregistering...
    public async Task NotifyMerchant_PaymentNotificationSuccededAsync()
    {
         var reminder = await this.GetReminder(this.GetPrimaryKey().ToString());
         if (reminder != null) {           
          await this.UnregisterReminder(reminder); //this throws with argument null
         }                              //in the error the line 328 with thee error is here
    }
}
```

**The exception:**

```
>     warn: Orleans.Grain.InvokeException[100322]
>           Exception during Grain method call of message: OneWay S10.244.0.14:11111:390542859*grn/Notification.Grains.PaymentMerchantGrain/16528479710843@d70ef3b0->S10.244.0.14:11111:390542859*grn/Notification.Grains.PaymentGrain/16528479710843@df8bf09b
> InvokeMethodRequest
> Notification.Grains.IPaymentGrain:NotifyMerchant_PaymentNotificationSuccededAsync
> #1580601:
>           Exc level 0: System.ArgumentNullException: Value cannot be null. (Parameter 'reminder')
>              at Orleans.Grain.UnregisterReminder(IGrainReminder reminder) in /_/src/Orleans.Core.Abstractions/Core/Grain.cs:line 152
>              at Notification.Grains.PaymentGrain.NotifyMerchant_PaymentNotificationSuccededAsync(PaymentNotification_ToMerchant_SucceededMessage
> paymentSuccededDTO) in
> /src/Notification/Notification.Grains/Grain/Payment/Grains/PaymentGrain/PaymentGrain.cs:line
> 328                <--------------------------------------------!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>              at Notification.Grains.OrleansCodeGenPaymentGrainMethodInvoker.Invoke(IAddressable
> grain, InvokeMethodRequest request) in
> /src/Notification/Notification.Grains/obj/Release/net6.0/Notification.Grains.orleans.g.cs:line
> 240 
>              at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Runtime/Core/GrainMethodInvoker.cs:line 104
>              at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target,
> IInvokable invokable, Message message) 
>     in /_/src/Orleans.Runtime/Core/InsideRuntimeClient.cs:line 469
>           System.ArgumentNullException: Value cannot be null. (Parameter 'reminder')
>              at Orleans.Grain.UnregisterReminder(IGrainReminder reminder) in /_/src/Orleans.Core.Abstractions/Core/Grain.cs:line 152
>              at Notification.Grains.PaymentGrain.NotifyMerchant_PaymentNotificationSuccededAsync(PaymentNotification_ToMerchant_SucceededMessage
> paymentSuccededDTO) in
> /src/Notification/Notification.Grains/Grain/Payment/Grains/PaymentGrain/PaymentGrain.cs:line
> 328
>              at Notification.Grains.OrleansCodeGenPaymentGrainMethodInvoker.Invoke(IAddressable
> grain, InvokeMethodRequest request) in
> /src/Notification/Notification.Grains/obj/Release/net6.0/Notification.Grains.orleans.g.cs:line
> 240 
>              at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Runtime/Core/GrainMethodInvoker.cs:line 104
>              at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target,
> IInvokable invokable, Message message) 
>     in /_/src/Orleans.Runtime/Core/InsideRuntimeClient.cs:line 469
>      04:26: 12[WRN] {EventId={Id=100322}, SourceContext="Orleans.Grain.InvokeException",
> ActionId="8fe38a88-4767-42ea-925c-31cdcf5338f4",
> ActionName="Notification.WebApi.PaymentController.PaymentNotificationAsync
> (Notification.WebApi)", RequestId="0HMHOGFQS74L4:00000266",
> RequestPath="/payment/", ConnectionId="0HMHOGFQS74L4",
> corellationId="fe11cbbe-d9f4-48a5-9760-1a962311f40e"} Exception during
> Grain method call of message: OneWay
> S10.244.0.14:11111:390542859*grn/Notification.Grains.PaymentMerchantGrain/16528479710843@d70ef3b0->S10.244.0.14:11111:390542859*grn/Notification.Grains.PaymentGrain/16528479710843@df8bf09b
> InvokeMethodRequest
> Notification.Grains.IPaymentGrain:NotifyMerchant_PaymentNotificationSuccededAsync
> #1580601:
>     Exc level 0: System.ArgumentNullException: Value cannot be null. (Parameter 'reminder')
>        at Orleans.Grain.UnregisterReminder(IGrainReminder reminder) in /_/src/Orleans.Core.Abstractions/Core/Grain.cs:line 152
>        at Notification.Grains.PaymentGrain.NotifyMerchant_PaymentNotificationSuccededAsync(PaymentNotification_ToMerchant_SucceededMessage
> paymentSuccededDTO) in
> /src/Notification/Notification.Grains/Grain/Payment/Grains/PaymentGrain/PaymentGrain.cs:line
> 328
>        at Notification.Grains.OrleansCodeGenPaymentGrainMethodInvoker.Invoke(IAddressable
> grain, InvokeMethodRequest request) in
> /src/Notification/Notification.Grains/obj/Release/net6.0/Notification.Grains.orleans.g.cs:line
> 240       
>        at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Runtime/Core/GrainMethodInvoker.cs:line 104    
>        at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message) in
> /_/src/Orleans.Runtime/Core/InsideRuntimeClient.cs:line 469
>     System.ArgumentNullException: Value cannot be null. (Parameter 'reminder')
>        at Orleans.Grain.UnregisterReminder(IGrainReminder reminder) in /_/src/Orleans.Core.Abstractions/Core/Grain.cs:line 152
>        at Notification.Grains.PaymentGrain.NotifyMerchant_PaymentNotificationSuccededAsync(PaymentNotification_ToMerchant_SucceededMessage
> paymentSuccededDTO) in
> /src/Notification/Notification.Grains/Grain/Payment/Grains/PaymentGrain/PaymentGrain.cs:line
> 328
>        at Notification.Grains.OrleansCodeGenPaymentGrainMethodInvoker.Invoke(IAddressable
> grain, InvokeMethodRequest request) in
> /src/Notification/Notification.Grains/obj/Release/net6.0/Notification.Grains.orleans.g.cs:line
> 240       
>        at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Runtime/Core/GrainMethodInvoker.cs:line 104    
>        at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message) in
> /_/src/Orleans.Runtime/Core/InsideRuntimeClient.cs:line 469
>      04:26: 12[INF] {corellationId="9edd7d8c-2770-4a13-b67f-57b52e91d6d0",
> ActionId="8fe38a88-4767-42ea-925c-31cdcf5338f4",
> ActionName="Notification.WebApi.PaymentController.PaymentNotificationAsync
> (Notification.WebApi)", RequestId="0HMHOGFQS74L2:00000279",
> RequestPath="/payment/", ConnectionId="0HMHOGFQS74L2"}
> ApplyUpdatesToStorage: etag 0 special-case write Initialized event
>      04:26: 12[WRN] {EventId={Id=100322}, SourceContext="Orleans.Grain.InvokeException",
> ActionId="8fe38a88-4767-42ea-925c-31cdcf5338f4",
> ActionName="Notification.WebApi.PaymentController.PaymentNotificationAsync
> (Notification.WebApi)", RequestId="0HMHOGFQS74L4:00000266",
> RequestPath="/payment/", ConnectionId="0HMHOGFQS74L4",
> corellationId="fe11cbbe-d9f4-48a5-9760-1a962311f40e"} Exception during
> Grain method call of message: OneWay
> S10.244.0.14:11111:390542859*grn/Notification.Grains.PaymentMerchantGrain/16528479710843@d70ef3b0->S10.244.0.14:11111:390542859*grn/Notification.Grains.PaymentGrain/16528479710843@df8bf09b
> InvokeMethodRequest
> Notification.Grains.IPaymentGrain:NotifyMerchant_PaymentNotificationSuccededAsync
> #1580601:
>     Exc level 0: System.ArgumentNullException: Value cannot be null. (Parameter 'reminder')
>        at Orleans.Grain.UnregisterReminder(IGrainReminder reminder) in /_/src/Orleans.Core.Abstractions/Core/Grain.cs:line 152
>        at Notification.Grains.PaymentGrain.NotifyMerchant_PaymentNotificationSuccededAsync(PaymentNotification_ToMerchant_SucceededMessage
> paymentSuccededDTO) in
> /src/Notification/Notification.Grains/Grain/Payment/Grains/PaymentGrain/PaymentGrain.cs:line
> 328
>        at Notification.Grains.OrleansCodeGenPaymentGrainMethodInvoker.Invoke(IAddressable
> grain, InvokeMethodRequest request) in
> /src/Notification/Notification.Grains/obj/Release/net6.0/Notification.Grains.orleans.g.cs:line
> 240       
>        at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Runtime/Core/GrainMethodInvoker.cs:line 104    
>        at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message) in
> /_/src/Orleans.Runtime/Core/InsideRuntimeClient.cs:line 469
>     System.ArgumentNullException: Value cannot be null. (Parameter 'reminder')
>        at Orleans.Grain.UnregisterReminder(IGrainReminder reminder) in /_/src/Orleans.Core.Abstractions/Core/Grain.cs:line 152
>        at Notification.Grains.PaymentGrain.NotifyMerchant_PaymentNotificationSuccededAsync(PaymentNotification_ToMerchant_SucceededMessage
> paymentSuccededDTO) in
> /src/Notification/Notification.Grains/Grain/Payment/Grains/PaymentGrain/PaymentGrain.cs:line
> 328
>        at Notification.Grains.OrleansCodeGenPaymentGrainMethodInvoker.Invoke(IAddressable
> grain, InvokeMethodRequest request) in
> /src/Notification/Notification.Grains/obj/Release/net6.0/Notification.Grains.orleans.g.cs:line
> 240       
>        at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Runtime/Core/GrainMethodInvoker.cs:line 104    
>        at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message) in
> /_/src/Orleans.Runtime/Core/InsideRuntimeClient.cs:line 469
>      04:26: 12[INF] {corellationId="c3beb36f-699f-4644-9468-2d1b7fec05fa",
> ActionId="8fe38a88-4767-42ea-925c-31cdcf5338f4",
> ActionName="Notification.WebApi.PaymentController.PaymentNotificationAsync
> (Notification.WebApi)", RequestId="0HMHOGFQS743R:00000033",
> RequestPath="/payment/", ConnectionId="0HMHOGFQS743R"}
> ApplyUpdatesToStorage: etag 0 special-case write Initialized event
```

**Comment by ReubenBond** [comment]
Everything looks fine in that code, but it looks like the code you included as your example is pseudocode, not the real code, and that's likely where the issue is. As for the null check, the code is a straightforward check: https://github.com/dotnet/orleans/blob/7333134d339d13a61c0bd8de4b695ae7c439395f/src/Orleans.Core.Abstractions/Core/Grain.cs#L152

**Comment by sanzor** [comment]
The code for registering the reminder as well as the unregistering is exactly the one i posted.

**Comment by ReubenBond** [comment]
It's not valid C#: you're using `await` in a non-async method

**Comment by sanzor** [comment]
That

> It's not valid C#: you're using `await` in a non-async method

My bad that was a typo. So this error seems to be happening only when i am load testing. In a normal scenario the error is not present.

**Comment by ReubenBond** [comment]
As with #7746, is this still an issue?

**Comment by sanzor** [comment]
The error did not reproduce again. Probably issue was unrelated.
