### ISSUE TITLE
UpdateIAmAlive retries indefinitely even though it won't be able to succeed

### ISSUE THREAD

**Issue by oleggolovkov** [dotnet/orleans#7784]
I had this issue with Redis clustering but I believe it may be more generic

**Steps to reproduce**:
1. Spin up a typical cluster with **non**-localhost clustering and let it operate for some time
2. Make an entry for one of the silos disappear from clustering storage without touching the cluster itself. One possibility to do so is to DELETE a row from the table if ADO.NET clustering is used. The other possibility (which happens in my case) is to have Redis clustering with **no** 'Redis persistence' and simply reboot this Redis instance
3. Observe exceptions like this happening every few seconds till the end of times
`Failed to update table entry for this silo, will retry shortly: "Orleans.Clustering.Redis.RedisClusteringException: Could not find a value for the key S10.0.1.101:8952:392386255
   at Orleans.Clustering.Redis.RedisMembershipTable.UpdateIAmAlive(MembershipEntry entry)
   at Orleans.Runtime.MembershipService.MembershipTableManager.UpdateIAmAlive() in /_/src/Orleans.Runtime/MembershipService/MembershipTableManager.cs:line 201
   at Orleans.Runtime.MembershipService.MembershipAgent.UpdateIAmAlive() in /_/src/Orleans.Runtime/MembershipService/MembershipAgent.cs:line 72"`

**Actual result**:
`Orleans.Runtime.MembershipService.MembershipAgent` enters a loop which it can't resolve itself

**Expected result**:
`Orleans.Runtime.MembershipService.MembershipAgent` is able to understand permanent failures (in my example the error message contains `Could not find a value for the key`) and does not retry those (in my example it explicitly states that it will: `will retry shortly`) but instead does something else like trying to reconfigure the whole cluster or consider itself a newly joining silo

**Comment by ReubenBond** [comment]
How should we address this? Generally speaking, there's no way to know which errors are transient and which are permanent/fatal.

**Comment by ReubenBond** [comment]
@oleggolovkov would that be a filter specific to each clustering provider or specific for `IAmAlive` or would it be a global filter?

**Comment by oleggolovkov** [comment]
The main idea is that sometimes the cluster can get into a (somewhat failed) state which it is unable to recover automatically from, like in this case the only solution I was able to find is rebooting the silos. If the only place in the system where infinite retries are happening is this case with updating `IAmAlive` then we could have a specific filter for that; if there are other places - would be nice to have either a global filter or specific filters for those places as well.

**Comment by ReubenBond** [comment]
@ArminShoeibi did Redis restart and was no persistence configured? I recommend using Azure Storage for clustering instead

**Comment by ArminShoeibi** [comment]
> @ArminShoeibi did Redis restart and was no persistence configured? I recommend using Azure Storage for clustering instead

Yes @ReubenBond , only one of our pods crashed twice due to being OOM Killed. We've implemented Redis sentinel with three sentinels and two slaves, and our Redis instance is set up to save data to disk, serving as our primary database, which has proven to be quite stable.

I should note that after enabling Redis grain directory, I encountered the mentioned error.

**Comment by shuizhugeju** [comment]
@ReubenBond 
I am using Azure Redis at the basic level （it does not have data persistence）. In my situation, the key does not exist, which may be caused by the Redis instance being restarted.
Can we check the Redis key before updating the silo key, or should we try to add the key after encountering this exception?

**Comment by rkargMsft** [comment]
Another recovery option could be for the Silo to consider itself dead if it tries to update IAmAlive time and there isn't a membership entry found (perhaps after X attempts). That approach is that it should be able to be implemented in the Orleans core. This would have a new Silo entry added when the silo restarts and ensure that there is nothing else out of sync that needs to be potentially cleaned up.

**Comment by akovac35** [comment]
> [@ReubenBond](https://github.com/ReubenBond) I am using Azure Redis at the basic level （it does not have data persistence）. In my situation, the key does not exist, which may be caused by the Redis instance being restarted. Can we check the Redis key before updating the silo key, or should we try to add the key after encountering this exception?

Just encountered this scenario during architecture design. I restarted a Redis instance (without persistence) and after it came back online, Orleans stopped working with all silos reporting the following error:

<pre>
warn: Orleans.Runtime.MembershipService.MembershipAgent[100659]
      Failed to update table entry for this silo, will retry shortly
      Orleans.Clustering.Redis.RedisClusteringException: Could not find a value for the key S172.27.144.1:52803:109597275
         at Orleans.Clustering.Redis.RedisMembershipTable.UpdateIAmAlive(MembershipEntry entry) in /_/src/Redis/Orleans.Clustering.Redis/Storage/RedisMembershipTable.cs:line 180
         at Orleans.Runtime.MembershipService.MembershipTableManager.UpdateIAmAlive() in /_/src/Orleans.Runtime/MembershipService/MembershipTableManager.cs:line 198
         at Orleans.Runtime.MembershipService.MembershipAgent.UpdateIAmAlive() in /_/src/Orleans.Runtime/MembershipService/MembershipAgent.cs:line 71
</pre>

I note here that Orleans worked just fine while the Redis instance was down for the duration of the test (there were no changes to silo cluster membership in this time), only when the Redis instance came back online did Orleans completely crash due to the above error.

What is the reason that a full upsert is not created here?

https://github.com/dotnet/orleans/blob/3f67c95d732d0873761d407f987de7a22e8d03a2/src/Redis/Orleans.Clustering.Redis/Storage/RedisMembershipTable.cs#L165-L180

**Comment by akovac35** [comment]
> The membership table getting dropped is not a valid scenario. It's critical infrastructure.
> 
> One solution is to enable persistence in redis or use another provider which has persistence. Otherwise, if membership is dropped you will need to restart your cluster.
> 
> It would be complex and highly nuanced to support this scenario correctly - it requires implementing consensus (Paxos, etc), for example. I rather we don't add partial solutions which give the illusion that it's supported.
> 
> If you feel otherwise, please help me to understand.

Thanks for the explanation; I don't think any changes are needed, except maybe an emphasis in the documentation regarding the durable table requirements. I will check if anything can be improved on the following page:

https://learn.microsoft.com/en-us/dotnet/orleans/implementation/cluster-management

My use case was such that I wanted to have an ephemeral clustering provider, for simplicity. The system must support Azure, but also on premises when isolated.
