### ISSUE TITLE
Unneeded exception in AzureBlobStorage when Clearing state

### ISSUE THREAD

**Issue by marcelk-workstreampeople-com** [dotnet/orleans#7791]
Hi,

When I try to unsubscribe the last subscriber form a stream where no publishers are stored and log level is set to Trace, the call to `GetPropertiesAsync` will result in an exception.

![image](https://user-images.githubusercontent.com/72133017/173583303-44848add-b868-446b-9b27-209a5908f2c2.png)

---
Part of exception:

Exc level 0: Azure.RequestFailedException: Service request failed.
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound

Headers:
Transfer-Encoding: chunked
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 4ee5dbb8-a01e-0006-25eb-7f4e75000000
x-ms-client-request-id: d6866991-9bcc-4b1a-9035-54a47ffffa0a
x-ms-version: 2019-07-07
x-ms-error-code: BlobNotFound
Date: Tue, 14 Jun 2022 12:38:59 GMT

   at Azure.Storage.Blobs.BlobRestClient.Blob.GetPropertiesAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Blob.GetPropertiesAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, String snapshot, Nullable`1 timeout, String leaseId, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.GetPropertiesInternal(BlobRequestConditions conditions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.GetPropertiesAsync(BlobRequestConditions conditions, CancellationToken cancellationToken)
   at Orleans.Storage.AzureBlobGrainStorage.ClearStateAsync(String grainType, GrainReference grainId, IGrainState grainState)
   at Orleans.Core.StateStorageBridge`1.ClearStateAsync()

**Comment by ReubenBond** [comment]
Hi @marcelk-workstreampeople-com, thanks for reporting. You're right, this is essentially a no-op.
If you're willing, a PR to remedy this would be most appreciated.
