### ISSUE TITLE
Trouble with Declarative Persistence tutorial

### ISSUE THREAD

**Issue by valeri-ilyin** [dotnet/orleans#786]
Hi everybody,

I'm using the Declarative Persistence tutorial to test a simple Azure Table storage persistence
http://dotnet.github.io/orleans/Step-by-step-Tutorials/

I got an issue with the tutorial. My Host crashes on the starting step (siloHost.StartOrleansSilo();

Exception details:
```c#
ERROR starting Orleans silo name=rufrw-vil Exception=
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo()
Exc level 1: Orleans.Runtime.OrleansException: Provider of type Orleans.Storage.AzureTableStorage name TestStore was not loaded.
   at Orleans.Providers.ProviderLoader`1.ValidateProviders()
   at Orleans.Providers.ProviderLoader`1.LoadProviders(IDictionary`2 configs, IProviderManager providerManager)
   at Orleans.Runtime.Storage.StorageProviderManager.LoadStorageProviders(IDictionary`2 configs)
   at Orleans.Runtime.Silo.<DoStart>b__11()
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClassa.<<QueueTask>b__8>d__c.MoveNext()
```

Host starting code
```c#
            siloHost = new SiloHost(System.Net.Dns.GetHostName());
            siloHost.ConfigFileName = "OrleansConfiguration.xml";
            siloHost.InitializeOrleansSilo();
            var startedok = siloHost.StartOrleansSilo(); // Orleans crashes  here.
```
Here is my Hosts Orleans config file (Azure credentials were replaced with placeholders )
DataConnectionString is correct - I tested it in another application 
OrleansConfiguration.xml
```xml
  <Globals>
    <StorageProviders>
      <Provider Type="Orleans.Storage.AzureTableStorage" Name="TestStore"
                DataConnectionString="DefaultEndpointsProtocol=https;AccountName=[AccountName];AccountKey=[AccountKey]" />
    </StorageProviders>
    <SeedNode Address="localhost" Port="11111" />
  </Globals>
```
--------------------------------------------------------
Sorry if my question is obvious.  I'm a newbie with Orleans. I just do tutorials one by one.

**Comment by valeri-ilyin** [comment]
Forgot to add Exception details:
```c#
ERROR starting Orleans silo name=rufrw-vil Exception=
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo()
Exc level 1: Orleans.Runtime.OrleansException: Provider of type Orleans.Storage.AzureTableStorage name TestStore was not loaded.
   at Orleans.Providers.ProviderLoader`1.ValidateProviders()
   at Orleans.Providers.ProviderLoader`1.LoadProviders(IDictionary`2 configs, IProviderManager providerManager)
   at Orleans.Runtime.Storage.StorageProviderManager.LoadStorageProviders(IDictionary`2 configs)
   at Orleans.Runtime.Silo.<DoStart>b__11()
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClassa.<<QueueTask>b__8>d__c.MoveNext()
```

**Comment by gabikliot** [comment]
@valeri-ilyin , in the config file you need to specify the provider name: http://dotnet.github.io/orleans/Step-by-step-Tutorials/Declarative-Persistence
```c# 
<StorageProviders>
      <Provider Type="Orleans.Storage.AzureTableStorage"
                      Name="AzureStore" 
                      DataConnectionString="UseDevelopmentStorage=true" />
     </StorageProviders>
```

**Comment by valeri-ilyin** [comment]
Sorry, Gabriel, I've posted corrupted XML first time. My config looks like your sample, but I'm getting exceptions

```xml
  <Globals>
    <StorageProviders>
      <Provider Type="Orleans.Storage.AzureTableStorage" Name="TestStore"
                DataConnectionString="DefaultEndpointsProtocol=https;AccountName=[AccountName];AccountKey=[AccountKey]" />
    </StorageProviders>
    <SeedNode Address="localhost" Port="11111" />
  </Globals>
```

**Comment by gabikliot** [comment]
Ok, in such a case you need to make sure that `OrleansAzureUtils.dll` is copied and present in your execution folder.

**Comment by sergeybykov** [comment]
Are you missing OrleansAzureUtils.dll by chance?

**Comment by valeri-ilyin** [comment]
Yes!! I've added OrleansAzureUtils.dll and it works now.
Thank you guys. Thank you very much. I've spent about 3 days trying to understand what's wrong with such simple configuration.

**Comment by sergeybykov** [comment]
Maybe we should extend the error message to be more explicit. With something like "Check that you deployed the assembly in which the provider class is defined."

**Comment by gabikliot** [comment]
Added more helpful error msg in https://github.com/dotnet/orleans/pull/792.
