### ISSUE TITLE
No codec found for OrleansAWSUtils.Streams.SQSBatchContainer

### ISSUE THREAD

**Issue by tanordheim** [dotnet/orleans#7941]
When trying to add SQS streaming to an Orleans 4.0 preview 2 project I get the following error on startup:

```
Orleans.Providers.Streams.Common.PersistentStreamProvider-test-stream failed to start due to errors at stage ApplicationServices (10000)
      Orleans.Serialization.CodecNotFoundException: Could not find a codec for type OrleansAWSUtils.Streams.SQSBatchContainer.
         at Orleans.Serialization.Serializers.CodecProvider.ThrowCodecNotFound[TField](Type fieldType) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 913
         at Orleans.Serialization.Serializers.CodecProvider.GetCodec[TField]() in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 167
         at Orleans.Serialization.Serializer`1..ctor(ICodecProvider codecProvider, SerializerSessionPool sessionPool) in /_/src/Orleans.Serialization/Serializer.cs:line 497
         at Orleans.Serialization.Serializer.GetSerializer[T]() in /_/src/Orleans.Serialization/Serializer.cs:line 38
         at OrleansAWSUtils.Streams.SQSAdapterFactory..ctor(String name, SqsOptions sqsOptions, HashRingStreamQueueMapperOptions queueMapperOptions, SimpleQueueCacheOptions cacheOptions, IOptions`1 clusterOptions, Serializer serializer, ILoggerFactory loggerFactory) in /_/src/AWS/Orleans.Streaming.SQS/Streams/SQSAdapterFactory.cs:line 43
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
         at OrleansAWSUtils.Streams.SQSAdapterFactory.Create(IServiceProvider services, String name) in /_/src/AWS/Orleans.Streaming.SQS/Streams/SQSAdapterFactory.cs:line 95
         at Orleans.Runtime.KeyedSingletonService`2.<>c__DisplayClass4_0.<.ctor>b__0() in /_/src/Orleans.Core/Utils/KeyedService.cs:line 83
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at System.Lazy`1.get_Value()
         at Orleans.Runtime.KeyedSingletonService`2.GetService(IServiceProvider services) in /_/src/Orleans.Core/Utils/KeyedService.cs:line 87
         at Orleans.Runtime.KeyedServiceCollection`2.GetService(IServiceProvider services, TKey key)
         at Orleans.Runtime.KeyedServiceCollectionExtensions.GetServiceByKey[TKey,TService](IServiceProvider services, TKey key) in /_/src/Orleans.Core.Abstractions/Utils/IKeyedServiceCollection.cs:line 78
         at Orleans.Runtime.KeyedServiceCollectionExtensions.GetRequiredServiceByKey[TKey,TService](IServiceProvider services, TKey key) in /_/src/Orleans.Core.Abstractions/Utils/IKeyedServiceCollection.cs:line 100
         at Orleans.Runtime.KeyedServiceCollectionExtensions.GetRequiredServiceByName[TService](IServiceProvider services, String name) in /_/src/Orleans.Core.Abstractions/Utils/IKeyedServiceCollection.cs:line 138
         at Orleans.Providers.Streams.Common.PersistentStreamProvider.Init(CancellationToken token) in /_/src/Orleans.Streaming/PersistentStreams/PersistentStreamProvider.cs:line 106
         at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in /_/src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs:line 134
```

This can easily be reproduced by this code:

```csharp
var app = Host.CreateDefaultBuilder(args)
    .UseOrleans((_, siloBuilder) =>
    {
        siloBuilder
            .UseLocalhostClustering()
            .AddMemoryGrainStorage("PubSubStore")
            .AddSqsStreams("test-stream", options =>
            {
                options.ConnectionString = "Service=http://localhost:9324/orleansstream";
            })
            .Configure<ClusterOptions>(options =>
            {
                options.ClusterId = "test-cluster";
                options.ServiceId = "test-service";
            })
            .Configure<EndpointOptions>(options =>
            {
                var ipAddress = Dns.GetHostEntry(Dns.GetHostName())
                    .AddressList
                    .FirstOrDefault(a => a.AddressFamily == AddressFamily.InterNetwork);
                if (ipAddress is null)
                    throw new Exception("unable to find public ipv4 address");
                options.AdvertisedIPAddress = ipAddress;
                options.SiloPort = 11111;
                options.GatewayPort = 30000;
            });
    })
    .Build();

await app.RunAsync();
```

Is something missing from the Microsoft.Orleans.Streaming.SQS NuGet package for this release?

**Comment by captainsafia** [comment]
Triage: @benjaminpetit thinks that we might need to produce a serializer for SQSBatchContainer to resolve this issue.

**Comment by benjaminpetit** [comment]
Thanks for the bug report @tanordheim 

We don't have automated tests for SQS, it would be great to be able to test it against a docker container in PR.
