### ISSUE TITLE
Exception throws when using MemoryStream with PrometheusTelemetryConsumer.

### ISSUE THREAD

**Issue by vrecluse** [dotnet/orleans#7990]
```
System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Orleans.TelemetryConsumers.Prometheus.PrometheusTelemetryConsumer.GetCategoryFromMetricName(String name)
   at Orleans.TelemetryConsumers.Prometheus.PrometheusTelemetryConsumer.TrackMetric(String name, Double value, IDictionary`2 properties)
   at Orleans.Runtime.TelemetryManager.TrackMetric(String name, Double value, IDictionary`2 properties) in /_/src/Orleans.Core/Telemetry/TelemetryManager.cs:line 52
   at Orleans.Providers.Streams.Common.DefaultQueueAdapterReceiverMonitor.TrackInitialization(Boolean success, TimeSpan callTime, Exception exception) in /_/src/OrleansProviders/Streams/Common/Monitors/DefaultQueueAdapterReceiverMonitor.cs:line 39
   at Orleans.Providers.MemoryAdapterReceiver`1.Initialize(TimeSpan timeout) in /_/src/OrleansProviders/Streams/Memory/MemoryAdapterReceiver.cs:line 32
   at Orleans.Streams.PersistentStreamPullingAgent.<InitializeInternal>b__28_0() in /_/src/Orleans.Runtime/Streams/PersistentStream/PersistentStreamPullingAgent.cs:line 133
   at Orleans.Internal.OrleansTaskExtentions.SafeExecute(Func`1 action) in /_/src/Orleans.Core/Async/TaskExtensions.cs:line 178
   at Orleans.Internal.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message) in /_/src/Orleans.Core/Async/TaskExtensions.cs:line 166
```
It seems the names passed to TrackMetric do not include '.'
```csharp
        public void TrackInitialization(bool success, TimeSpan callTime, Exception exception)
        {
            this.TelemetryProducer.TrackMetric("InitializationFailure", success ? 0 : 1, this.LogProperties);
            this.TelemetryProducer.TrackMetric("InitializationCallTime", callTime, this.LogProperties);
            this.TelemetryProducer.TrackMetric("InitializationException", exception == null ? 0 : 1, this.LogProperties);
        }

```

**Comment by ReubenBond** [comment]
Hi @vrecluse, this looks like an issue with the Prometheus package which you're using, which I assume is from here: https://github.com/zh6335901/Orleans.TelemetryConsumers.Prometheus
