### ISSUE TITLE
Event hub streams, weird error in 7.0.0 Unable to find an IGrainReferenceActivatorProvider

### ISSUE THREAD

**Issue by RbsTechOnline** [dotnet/orleans#8111]
Firstly, great work! 7.0.0 ! Orleans is really becoming part of the family

However, I've just rolled over from preview 2, to 7.0.0 and found a curious exception with streaming, I'm not sure if i have missed something in the PR's that is relivent here, or I am just missing something simple. 

**Setup**

```
private static ISiloBuilder ConfigureEventHub(this ISiloBuilder siloBuilder, string streamNamespace, IHostEnvironment environment, IConfiguration configuration, TokenCredential tokenCredential)
{
    return siloBuilder.AddEventHubStreams(streamNamespace, configurator =>
    {
        var clientOption = configuration.GetSectionInstance<EventHubClientOption>();

        configurator.ConfigureEventHub(builder => 
            builder.Configure(hubOptions => 
                hubOptions.ConfigureEventHubConnection(clientOption.FullyQualifiedNamespace, clientOption.EventHubName, clientOption.ConsumerGroup, tokenCredential)));

        configurator.ConfigureStreamPubSub(StreamPubSubType.ImplicitOnly);
        configurator.UseDataAdapter((provider, s) 
            => ActivatorUtilities.CreateInstance<CustomDataAdapter>(provider));

        configurator.UseCosmosCheckPoint(ob => ob.Configure(options =>
        {
            options.StorageSettings.Database = environment.EnvironmentName.FirstCharToUpper();
        }));

    });
}
```

**Adapter**

```
public class CustomDataAdapter : EventHubDataAdapter
{
    public CustomDataAdapter(Serializer serialisationManager) : base(serialisationManager) {}

    protected override IBatchContainer GetBatchContainer(EventHubMessage eventHubMessage) => new CustomBatchContainer(eventHubMessage);
}
```

**BatchContainer**

```
public class CustomBatchContainer : IBatchContainer
{
    private readonly byte[] _payload;

    public CustomBatchContainer(EventHubMessage eventHubMessage)
    {
        StreamId = eventHubMessage.StreamId;
        SequenceToken = new EventHubSequenceTokenV2(eventHubMessage.Offset, eventHubMessage.SequenceNumber, 0);
        _payload = eventHubMessage.Payload;
    }

    public StreamSequenceToken SequenceToken { get; }

    public bool ImportRequestContext() => false;

    public StreamId StreamId { get; }

    public IEnumerable<Tuple<T, StreamSequenceToken>> GetEvents<T>()
    {
        var evt = JsonSerializer.Deserialize<T>(_payload);

        return new[]
        {
            Tuple.Create(evt!, SequenceToken)
        };
    }
}
```

Exception

```
System.InvalidOperationException: Unable to find an IGrainReferenceActivatorProvider for grain type sys.svc.stream.agent-mgr
   at Orleans.GrainReferences.GrainReferenceActivator.CreateActivator(GrainType grainType, GrainInterfaceType interfaceType) in /_/src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs:line 85
   at Orleans.GrainReferences.GrainReferenceActivator.CreateReference(GrainId grainId, GrainInterfaceType interfaceType) in /_/src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs:line 54
   at Orleans.Runtime.GrainReferenceRuntime.Cast(IAddressable grain, Type grainInterface) in /_/src/Orleans.Core/Runtime/GrainReferenceRuntime.cs:line 94
   at Orleans.GrainExtensions.AsReference[TGrainInterface](IAddressable grain) in /_/src/Orleans.Core.Abstractions/Core/GrainExtensions.cs:line 64
   at Orleans.Runtime.Providers.SiloStreamProviderRuntime.InitializePullingAgents(String streamProviderName, IQueueAdapterFactory adapterFactory, IQueueAdapter queueAdapter) in /_/src/Orleans.Streaming/Providers/SiloStreamProviderRuntime.cs:line 89
   at Orleans.Providers.Streams.Common.PersistentStreamProvider.Start(CancellationToken token) in /_/src/Orleans.Streaming/PersistentStreams/PersistentStreamProvider.cs:line 127
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in /_/src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs:line 134
   at Orleans.LifecycleSubject.OnStart(CancellationToken cancellationToken) in /_/src/Orleans.Core/Lifecycle/LifecycleSubject.cs:line 118
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute() in /_/src/Orleans.Runtime/Scheduler/ClosureWorkItem.cs:line 34
   at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken) in /_/src/Orleans.Runtime/Silo/Silo.cs:line 213
   at Orleans.Hosting.SiloHostedService.StartAsync(CancellationToken cancellationToken) in /_/src/Orleans.Runtime/Hosting/SiloHostedService.cs:line 28
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
```

**Comment by RbsTechOnline** [comment]
Update, this is likely related to https://github.com/dotnet/orleans/issues/8112 I'll do some more testing on this soon
