### ISSUE TITLE
GenerateSerializer code fix documentation issue

### ISSUE THREAD

**Issue by christallire** [dotnet/orleans#8161]
Well, I don't know If this only happened to me but I personally had a hard time figuring out how to use the analyzer built-in code fix in VS + Resharper environment during the migration.

![154169861-7c5547d0-e489-4af9-8aba-1e2f71c50211](https://user-images.githubusercontent.com/1384630/202375406-16ea4897-3454-4996-be15-c1eb60183f25.gif)

The problem with the above image is, 
In order to get the code fix bulb you'll have to move your cursor to dotted underline.. took so much time to figure it out.

![idk](https://user-images.githubusercontent.com/1384630/202377760-a92ffcab-0edd-4ba7-8f98-373972c2dd28.gif)
(Look at the position of the cursor)

I'm not sure if it needs to be documented since it's IDE's problem but I personally had a hard time figuring it out so I just want to share the experience.

On a side note, One thing that contributed to having a hard time figuring it out is the analyzer is not always run.

I've noticed that it runs when you change the currently opened tab but when you add [GenerateSerializer] attribute, sometimes it does not just run. 
It happens a lot to me especially when you have so many serializable classes in a file.
Usually cut and paste the snippet works but sometimes not. so I had to create a file and move the class there and decorate the attribute then save the file, and then move back to the original file to get the analyzer fix up.
Oh, And reshaper sometimes complains that the analyzer spews some error so it won't just gonna show its code completion sometimes.

**Comment by ReubenBond** [comment]
Thanks for the request, @christallire! We could raise the level from *Hint* to *Warning*, which will result in the entire attribute being underlined. I think that we should.
As for the ReSharper issue, I'm not sure, but I'll see if I can reproduce it.

**Comment by christallire** [comment]
@ReubenBond hope this helps regarding error code, this error is spewed from VS, not resharper

```System.InvalidOperationException : The item specified is not the element of a list.
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.NodeListEditor.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.InsertNodesInListCore(SyntaxNode nodeInList,IEnumerable`1 nodesToInsert,Boolean insertBefore)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.InsertNodesBefore[TRoot](TRoot root,SyntaxNode nodeInList,IEnumerable`1 newNodes)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.InsertNodesBeforeInternal(SyntaxNode root,SyntaxNode declaration,IEnumerable`1 newDeclarations)
   at Microsoft.CodeAnalysis.Editing.SyntaxGenerator.PreserveTrivia[TNode](TNode node,Func`2 nodeChanger)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.InsertNodesBefore(SyntaxNode root,SyntaxNode declaration,IEnumerable`1 newDeclarations)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Orleans.Analyzers.GenerateOrleansSerializationAttributesCodeFix.AddNonSerializedAttributes(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)```

**Comment by ReubenBond** [comment]
@christallire that is interesting. Could you show me the code you executed that CodeFix on?

**Comment by dferretti** [comment]
This happens to me as well - in a class library project with only 1 package reference to `Microsoft.Orleans.Sdk` version `7.2.1`

A simple class like
```c#
[GenerateSerializer]
public class TestClass
{
    public int X { get; set; }
}
```

With the cursor on `GenerateSerializer`, I can `ctrl + .` to bring up intellisense. By default it highlights the first suggestion, and everything is working fine:
![image](https://github.com/dotnet/orleans/assets/24608502/e4466875-d9eb-45df-b868-2f7d7f7590d1)

But as soon as I press down to highlight the second option, the generator throws an exception that VS reports:
![image](https://github.com/dotnet/orleans/assets/24608502/1ef6244f-0103-4f6e-b64c-32fa01147e00)

Stack trace looks to be the same as reported above:

<details>
<summary>stack trace</summary>

```
System.InvalidOperationException : The item specified is not the element of a list.
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.NodeListEditor.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.InsertNodesInListCore(SyntaxNode nodeInList,IEnumerable`1 nodesToInsert,Boolean insertBefore)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.InsertNodesBefore[TRoot](TRoot root,SyntaxNode nodeInList,IEnumerable`1 newNodes)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.InsertNodesBeforeInternal(SyntaxNode root,SyntaxNode declaration,IEnumerable`1 newDeclarations)
   at Microsoft.CodeAnalysis.Editing.SyntaxGenerator.PreserveTrivia[TNode](TNode node,Func`2 nodeChanger)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.InsertNodesBefore(SyntaxNode root,SyntaxNode declaration,IEnumerable`1 newDeclarations)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Orleans.Analyzers.GenerateOrleansSerializationAttributesCodeFix.AddNonSerializedAttributes(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

</details>

**Comment by ReubenBond** [comment]
Thanks for the details, @dferretti, I see the issue. I will try to get a fix PR opened soon

**Comment by ReubenBond** [comment]
I opened #8557 with the fix. There is still the minor nuisance of it adding a `using` directive when you are using C#'s `global using` feature, but at least it works.
