### ISSUE TITLE
Call to RegisterOrUpdateReminder throws exception: "No service for type 'Orleans.Timers.IReminderRegistry' has been registered."

### ISSUE THREAD

**Issue by htxryan** [dotnet/orleans#8177]
Hello!

I'm facing an issue when upgrading from 3.x to 7.

Calls to `RegisterOrUpdateReminder()` from grains that implement `IRemindable` throw exceptions: "No service for type 'Orleans.Timers.IReminderRegistry' has been registered."

As noted [here](https://learn.microsoft.com/en-us/dotnet/orleans/whats-new-in-orleans#packaging-changes), a reference to `Microsoft.Orleans.Reminders` has been added.

I'm using the [MongoDB reminder provider](https://github.com/OrleansContrib/Orleans.Providers.MongoDB).

**NOTE**: Changing from the MongoDB provider to the in-memory reminder service **DOES** make this issue go away. So this might be an issue with that library. If someone reading this believes that to be the case, please let me know. I'm going to open this same issue there just in case (https://github.com/OrleansContrib/Orleans.Providers.MongoDB/issues/115).

Stack trace:
```
System.InvalidOperationException: No service for type 'Orleans.Timers.IReminderRegistry' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Orleans.GrainReminderExtensions.GetReminderRegistry(IGrainContext grainContext) in /_/src/Orleans.Reminders/GrainReminderExtensions.cs:line 125
   at Orleans.GrainReminderExtensions.RegisterOrUpdateReminder(Boolean remindable, IGrainContext grainContext, String reminderName, TimeSpan dueTime, TimeSpan period) in /_/src/Orleans.Reminders/GrainReminderExtensions.cs:line 52
   at Orleans.GrainReminderExtensions.RegisterOrUpdateReminder(Grain grain, String reminderName, TimeSpan dueTime, TimeSpan period) in /_/src/Orleans.Reminders/GrainReminderExtensions.cs:line 29
   at [ grain function]...
```

**Comment by ReubenBond** [comment]
Hi @htxryan, could you show us how you are configuring your silo?

**Comment by htxryan** [comment]
@ReubenBond Actually just figured this out -- I was missing the `AddReminders()` call (which was apparently not required in 3.x, as reminders were working for me before the upgrade). I didn't see this mentioned anywhere in the upgrade docs, so it may need to be added there (though I could very well have missed it).

Where I got the nudge to make this change that fixed it for me: https://github.com/OrleansContrib/Orleans.Providers.MongoDB/issues/115

**Comment by ReubenBond** [comment]
@htxryan I was going to check. We should add `AddReminders` to the `Orleans.Providers.MongoDB` provider so that you don't need to call it manually.  Would you be willing to submit a PR to that repo?

**Comment by htxryan** [comment]
@ReubenBond Yep, I'll look into that now. Thanks!

**Comment by htxryan** [comment]
For posterity, here's the PR: https://github.com/OrleansContrib/Orleans.Providers.MongoDB/pull/116
