### ISSUE TITLE
Silo initialization error with Kubernetes 1.25

### ISSUE THREAD

**Issue by EPinci** [dotnet/orleans#8193]
When trying to run a 7.0.0 silo in kubernetes, the pod fails with:
```
[ERR] Lifecycle start canceled due to errors at stage 8100
System.TypeLoadException: Could not load type 'k8s.Models.V1PodList' from assembly 'KubernetesClient, Version=7.2.0.0, Culture=neutral, PublicKeyToken=null'.
   at Orleans.Hosting.Kubernetes.KubernetesClusterAgent.OnRuntimeInitializeStart(CancellationToken cancellation)
   at Orleans.LifecycleExtensions.Observer.OnStart(CancellationToken ct) in /_/src/Orleans.Core.Abstractions/Lifecycle/LifecycleExtensions.cs:line 123
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in /_/src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs:line 134
   at Orleans.LifecycleSubject.OnStart(CancellationToken cancellationToken) in /_/src/Orleans.Core/Lifecycle/LifecycleSubject.cs:line 118
```

Running on Kubernetes 1.25.
The KubernetesClient dependency of `Microsoft.Orleans.Hosting.Kubernetes` seems outdated.
Silo is using AzureTableStorage as clustering storage. Init log for it show success.

Silo code and container packaging are faily basic. Can provide the source if needed.

Thank you.

**Comment by EPinci** [comment]
Closed by #8199
