### ISSUE TITLE
TypeLoadException: Unable to resolve type alias "("inv",[Orleans.Runtime.GrainReference]

### ISSUE THREAD

**Issue by christallire** [dotnet/orleans#8200]
Hey guys, is there some reason I can't use same method name again?

For example, Let's say I have following grain

```
public interface ISomeGrain : IGrainWithIntegerKey
{
    Task Method();
}
```

and I've accidentally getting `TypeLoadException: Unable to resolve type alias "("inv",[Orleans.Runtime.GrainReference]` exception by changing signature like:

```
public interface ISomeGrain : IGrainWithIntegerKey
{
    Task Method(int accidentParameter);
}
```

so I hot-fixed the grain by adding a new signature like:

```
[Version(1)]
public interface ISomeGrain : IGrainWithIntegerKey
{
    Task Method();
    Task NewMethod(int accidentParameter);
}
```

and everything went okay. (this was a painful experience tho..)

The problem is I cannot use the same method name again and wonder why is that so. I've completely deployed version 1 grain and trying to reclaim the method name back but Orleans kept throwing `TypeLoadException` again like interface below:

```
[Version(2)]
public interface ISomeGrain : IGrainWithIntegerKey
{
    Task Method(int accidentParameter);
}
```

Here's my question:
1) Why am I not allowed to use the method name of the previous version?
2) Why am I not allowed to accept consequences (having side effects, being not backward compatible) and getting runtime errors instead of making silent signature changes?

**Comment by ReubenBond** [comment]
Hi @christallire, could you please clarify what triggers this issue for you? From your description, it sounds like defining this grain interface is enough:
```C#
public interface ISomeGrain : IGrainWithIntegerKey
{
    Task Method();
}
```

Is that correct?

**Comment by christallire** [comment]
from
```
public interface ISomeGrain : IGrainWithIntegerKey
{
    Task Method();
}
```
to
```
public interface ISomeGrain : IGrainWithIntegerKey
{
    Task Method(int accidentParameter);
}
```

this is re: question 2

**Comment by ReubenBond** [comment]
Ok, so you've got a heterogeneous setup where you're modifying a grain interface and the problem is that it's no longer the same method, so Orleans doesn't know what to do with it. You can tell Orleans to treat them as the same method by giving the method an alias using `[Alias("My method")]` on the grain interface method. In that case maybe it will work. We should improve the error message either way.

**Comment by christallire** [comment]
But isn't that okay as long as agreed between both parties that are no longer the same method and both are aware of it?
I was scratching my head because that doesn't just work.

Silo 1 knows: ISomeGrain Version 0 (just referencing defined assembly, not using the interface)
Silo 2 knows: ISomeGrain Version 0 (just referencing defined assembly, not using the interface)
Silo 3 knows: ISomeGrain Version 0 (just referencing defined assembly, not using the interface)
Silo 4 knows: ISomeGrain Version 0 (just referencing defined assembly, not using the interface)
Silo 5 knows: ISomeGrain Version 2 (the client)
Silo 6 knows: ISomeGrain Version 2 (grain is activated here)

Here's my question:

Why am I not allowed to use the method name of the previous version?
Why am I not allowed to accept consequences (having side effects, being not backward compatible) but getting runtime errors instead of making silent signature changes?

**Comment by ReubenBond** [comment]
You should be allowed to use a method name which was also defined in a previous version. Could you upload a repro? I'd like to investigate.

**Comment by YAJeff** [comment]
I'm running into this issue too. But only on 1 of the 3 replicas that my silo container is deployed to. Is there some kind of cache or short-term memory that is hanging onto these type definitions which can be deleted before a redeploy? This makes it challenging while just trying to develop a first release of an application.

**Comment by JCKortlang** [comment]
I am observing the same behavior in a non heterogeneous setup after changing a grain interface.

Interface:

```
//From
public interface IAssertionGrain : IGrainWithStringKey, IUpdateResourceNotifier
{
    Task<Assertion> Register(Assertion assertion);
    Task Delete();
    Task<Assertion?> GetDetails();
    Task<AssertionStatistics> QueryHistory(DateTimeOffset start, DateTimeOffset end);
}

//To
public interface IAssertionGrain : IGrainWithStringKey, IUpdateResourceNotifier
{
    Task<Assertion> Register(Assertion assertion);
    Task Delete();
    Task<Assertion?> GetDetails();
    Task<AssertionStatistics> QueryHistory(DateTimeOffset start, DateTimeOffset end, string gameRegion, string gameStage, string gameVersion = Metrics.Dimensions.DefaultValue);
}
```

Stack Trace:
```
An unhandled exception has occurred while executing the request.

System.TypeLoadException: Unable to resolve type alias "("inv",[Orleans.Runtime.GrainReference],[Insights.Telemetry.Grains.Interfaces.IAssertionGrain,Insights.Telemetry.Grains.Interfaces],"1AC7528E")".

   at Orleans.Serialization.TypeSystem.TypeConverter.ResolveCompoundAliasType[TState](TupleTypeSpec input, TState& state) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 545

   at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.TypeRewriter`1.HandleCompoundType(TupleTypeSpec type, String assemblyName) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 223

   at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.TypeRewriter`1.ApplyInner(TypeSpec input, String assemblyName) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 77

   at Orleans.Serialization.TypeSystem.TypeConverter.ParseInternal(TypeSpec parsed, Type& type) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 345

   at Orleans.Serialization.TypeSystem.TypeCodec.TryRead[TInput](Reader`1& reader) in /_/src/Orleans.Serialization/TypeSystem/TypeCodec.cs:line 72

   at Orleans.Serialization.Codecs.FieldHeaderCodec.ReadType[TInput](Reader`1& reader, SchemaType schemaType) in /_/src/Orleans.Serialization/Codecs/FieldHeaderCodec.cs:line 219

   at Orleans.Serialization.Codecs.FieldHeaderCodec.ReadExtendedFieldHeader[TInput](Reader`1& reader, Field& field) in /_/src/Orleans.Serialization/Codecs/FieldHeaderCodec.cs:line 201

   at Orleans.Runtime.Messaging.MessageSerializer.ReadBodyObject[TInput](Message message, Reader`1& reader) in /_/src/Orleans.Core/Messaging/MessageSerializer.cs:line 129

   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message) in /_/src/Orleans.Core/Messaging/MessageSerializer.cs:line 125

   at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in /_/src/Orleans.Core/Networking/Connection.cs:line 347

--- End of stack trace from previous location ---

   at Orleans.Serialization.Invocation.ResponseCompletionSource.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 90

   at Orleans.Runtime.OutgoingCallInvoker`1.Invoke() in /_/src/Orleans.Core/Runtime/OutgoingCallInvoker.cs:line 117

   at Orleans.Runtime.ActivityPropagationGrainCallFilter.Process(IGrainCallContext context, Activity activity) in /_/src/Orleans.Core/Diagnostics/ActivityPropagationGrainCallFilter.cs:line 75

   at Orleans.Runtime.OutgoingCallInvoker`1.Invoke() in /_/src/Orleans.Core/Runtime/OutgoingCallInvoker.cs:line 88

   at Orleans.Runtime.GrainReferenceRuntime.InvokeMethodWithFiltersAsync[TResult](GrainReference reference, IInvokable request, InvokeMethodOptions options) in /_/src/Orleans.Core/Runtime/GrainReferenceRuntime.cs:line 74

   at Insights.Telemetry.SiloExtensions.TelemetrySiloExtensions.<>c.<<MapTelemetryRoutes>b__3_7>d.MoveNext() in /app/src/Telemetry/Insights.Telemetry.SiloExtensions/TelemetrySiloExtensions.cs:line 250

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)

   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by ReubenBond** [comment]
Is the grain interface available on all hosts, @JCKortlang? That is a requirement today but it is a restriction which we are working on lifting, so that these kinds of errors will not occur in future.

**Comment by JCKortlang** [comment]
@ReubenBond it "should" be. We are deploying the latest container image across [1..n] containers. 

Based on the AWS ECS logs, the most recent version of the image was deployed across all containers prior to the error. The issue was not reproducible when running the silo locally.

Note that I re-deployed the same code without changes and was unable to reproduce.

**Comment by ReubenBond** [comment]
Sorry, this is my fault for misreading. You are performing a rolling upgrade and are also modifying a grain interface method, which has changed is identity. If the method is still compatible, i.e, old versions of the code can ignore the new parameters, then you can specify the method id explicitly by applying the `[Alias("MyMethodName")]` attribute to it as I mentioned previously in [this comment](https://github.com/dotnet/orleans/issues/8200#issuecomment-1333074364). I would recommend applying that to methods before you add arguments to them.

If the new method is not semantically equivalent to the old one (the new arguments cannot be safely ignored during the upgrade), then you should use Grain interface versioning to denote a breaking change.
In this case, and in the case where you are adding a new method to the interface, you can use a two-phase upgrade: add the interface method in one deployment without using it anywhere, and then start using the method in a subsequent deployment.

I hope that helps to clarify things. We are still looking to improve the experience here for the next release.

**Comment by christallire** [comment]
I haven't had time to look this up for myself but:


> I'm running into this issue too. But only on 1 of the 3 replicas that my silo container is deployed to. Is there some kind of cache or short-term memory that is hanging onto these type definitions which can be deleted before a redeploy? This makes it challenging while just trying to develop a first release of an application.

There's also an issue that Orleans doesn't allow breaking changes even with Versions like the quote above, especially with rolling updates, it just throws an exception if any of those signatures mismatches. 

Preventing devs from making mistakes is a great idea, yet we really have to do something with this kind of runtime exception since we can't test it until it goes into production.

**Comment by sc-starman** [comment]
migration from 7.2.3 to 8.0.0-rc2
I got the same exception:
```
 Exception reading message Request [ sys.client/adf9fef2141c4881b1d4b8d5970cb3cb]->[S10.0.8.184:30000:0 sys.svc.manifest/10.0.8.184:30000@0] #302529 from remote endpoint 10.0.8.222:35278 to local endpoint 10.0.8.184:30000
System.TypeLoadException: Unable to resolve type alias "("inv",[Orleans.Runtime.GrainReference],[Orleans.Runtime.IClusterManifestSystemTarget,Orleans.Core],"4EFCA109")".
   at Orleans.Serialization.TypeSystem.TypeConverter.ResolveCompoundAliasType[TState](TupleTypeSpec input, TState& state) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 545
   at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.TypeRewriter`1.HandleCompoundType(TupleTypeSpec type, String assemblyName) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 223
   at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.TypeRewriter`1.ApplyInner(TypeSpec input, String assemblyName) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 77
   at Orleans.Serialization.TypeSystem.TypeConverter.ParseInternal(TypeSpec parsed, Type& type) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 345
   at Orleans.Serialization.TypeSystem.TypeCodec.TryRead[TInput](Reader`1& reader) in /_/src/Orleans.Serialization/TypeSystem/TypeCodec.cs:line 72
   at Orleans.Serialization.Codecs.FieldHeaderCodec.ReadType[TInput](Reader`1& reader, SchemaType schemaType) in /_/src/Orleans.Serialization/Codecs/FieldHeaderCodec.cs:line 187
   at Orleans.Serialization.Codecs.FieldHeaderCodec.ReadExtendedFieldHeader[TInput](Reader`1& reader, Field& field) in /_/src/Orleans.Serialization/Codecs/FieldHeaderCodec.cs:line 169
   at Orleans.Runtime.Messaging.MessageSerializer.ReadBodyObject[TInput](Message message, Reader`1& reader) in /_/src/Orleans.Core/Messaging/MessageSerializer.cs:line 130
   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message) in /_/src/Orleans.Core/Messaging/MessageSerializer.cs:line 126
   at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in /_/src/Orleans.Core/Networking/Connection.cs:line 349
```

**Comment by sc-starman** [comment]
> migration from 7.2.3 to 8.0.0-rc2 I got the same exception:
> 
> ```
>  Exception reading message Request [ sys.client/adf9fef2141c4881b1d4b8d5970cb3cb]->[S10.0.8.184:30000:0 sys.svc.manifest/10.0.8.184:30000@0] #302529 from remote endpoint 10.0.8.222:35278 to local endpoint 10.0.8.184:30000
> System.TypeLoadException: Unable to resolve type alias "("inv",[Orleans.Runtime.GrainReference],[Orleans.Runtime.IClusterManifestSystemTarget,Orleans.Core],"4EFCA109")".
>    at Orleans.Serialization.TypeSystem.TypeConverter.ResolveCompoundAliasType[TState](TupleTypeSpec input, TState& state) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 545
>    at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.TypeRewriter`1.HandleCompoundType(TupleTypeSpec type, String assemblyName) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 223
>    at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.TypeRewriter`1.ApplyInner(TypeSpec input, String assemblyName) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 77
>    at Orleans.Serialization.TypeSystem.TypeConverter.ParseInternal(TypeSpec parsed, Type& type) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 345
>    at Orleans.Serialization.TypeSystem.TypeCodec.TryRead[TInput](Reader`1& reader) in /_/src/Orleans.Serialization/TypeSystem/TypeCodec.cs:line 72
>    at Orleans.Serialization.Codecs.FieldHeaderCodec.ReadType[TInput](Reader`1& reader, SchemaType schemaType) in /_/src/Orleans.Serialization/Codecs/FieldHeaderCodec.cs:line 187
>    at Orleans.Serialization.Codecs.FieldHeaderCodec.ReadExtendedFieldHeader[TInput](Reader`1& reader, Field& field) in /_/src/Orleans.Serialization/Codecs/FieldHeaderCodec.cs:line 169
>    at Orleans.Runtime.Messaging.MessageSerializer.ReadBodyObject[TInput](Message message, Reader`1& reader) in /_/src/Orleans.Core/Messaging/MessageSerializer.cs:line 130
>    at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message) in /_/src/Orleans.Core/Messaging/MessageSerializer.cs:line 126
>    at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in /_/src/Orleans.Core/Networking/Connection.cs:line 349
> ```

It was my mistake that I didn't update the client to  8.0.0-rc2, after update everything seems to be fine again.

**Comment by ReubenBond** [comment]
Thank you for confirming, @sc-starman

**Comment by turowicz** [comment]
@ReubenBond I get this after upgrading to 8.2.0 which is simillar to @sc-starman 

```
[06:29:17 WRN] Failed to fetch cluster manifest update from GrainReference:sys.svc.manifest/10.42.2.68:30000@0:Orleans.Runtime.IClusterManifestSystemTarget.
System.TypeLoadException: Unable to resolve type alias "("inv",[Orleans.Runtime.GrainReference],[Orleans.Runtime.IClusterManifestSystemTarget,Orleans.Core],"4EFCA109")".
   at Orleans.Serialization.TypeSystem.TypeConverter.ResolveCompoundAliasType[TState](TupleTypeSpec input, TState& state) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 545
   at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.TypeRewriter`1.HandleCompoundType(TupleTypeSpec type, String assemblyName) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 223
   at Orleans.Serialization.TypeSystem.TypeConverter.ParseInternal(TypeSpec parsed, Type& type) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 316
   at Orleans.Serialization.TypeSystem.TypeCodec.TryRead[TInput](Reader`1& reader) in /_/src/Orleans.Serialization/TypeSystem/TypeCodec.cs:line 83
   at Orleans.Serialization.Codecs.FieldHeaderCodec.ReadType[TInput](Reader`1& reader, SchemaType schemaType) in /_/src/Orleans.Serialization/Codecs/FieldHeaderCodec.cs:line 178
   at Orleans.Serialization.Codecs.FieldHeaderCodec.ReadExtendedFieldHeader[TInput](Reader`1& reader, Field& field) in /_/src/Orleans.Serialization/Codecs/FieldHeaderCodec.cs:line 152
   at Orleans.Runtime.Messaging.MessageSerializer.ReadBodyObject[TInput](Message message, Reader`1& reader) in /_/src/Orleans.Core/Messaging/MessageSerializer.cs:line 144
   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message) in /_/src/Orleans.Core/Messaging/MessageSerializer.cs:line 126
   at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in /_/src/Orleans.Core/Networking/Connection.cs:line 349
```

Could it be due to one of the packages that I am using still being on 8.0.0? Details:
https://github.com/OrleansContrib/Orleans.Clustering.Kubernetes/blob/master/src/Orleans.Clustering.Kubernetes/Orleans.Clustering.Kubernetes.csproj
https://github.com/OrleansContrib/Orleans.Clustering.Kubernetes/issues/76

Everything else is on 8.2.0

**Comment by alexf2017** [comment]
Same for me, upgrading from v7 to v8, all packages on v8.2.0

`System.TypeLoadException: Unable to resolve type alias \"(\"inv\",[Orleans.Runtime.GrainReference],[Orleans.Streams.IStreamConsumerExtension,Orleans.Streaming],\"B9CFF2C9\")\".\n at Orleans.Serialization.TypeSystem.TypeConverter.ResolveCompoundAliasType[TState](TupleTypeSpec input, TState& state) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 574\n at Orleans.Serialization.TypeSystem.RuntimeTypeNameRewriter.TypeRewriter`1.HandleCompoundType(TupleTypeSpec type, String assemblyName) in /_/src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs:line 233\n at Orleans.Serialization.TypeSystem.TypeConverter.ParseInternal(TypeSpec parsed, Type& type) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 316\n at Orleans.Serialization.TypeSystem.TypeCodec.TryRead[TInput](Reader`1& reader) in /_/src/Orleans.Serialization/TypeSystem/TypeCodec.cs:line 112\n at Orleans.Serialization.Codecs.FieldHeaderCodec.ReadType[TInput](Reader`1& reader, SchemaType schemaType) in /_/src/Orleans.Serialization/Buffers/Writer.FieldHeader.cs:line 180\n at Orleans.Serialization.Codecs.FieldHeaderCodec.ReadExtendedFieldHeader[TInput](Reader`1& reader, Field& field) in /_/src/Orleans.Serialization/Buffers/Writer.FieldHeader.cs:line 163\n at Orleans.Runtime.Messaging.MessageSerializer.ReadBodyObject[TInput](Message message, Reader`1& reader) in /_/src/Orleans.Core/Messaging/MessageSerializer.cs:line 130\n at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message) in /_/src/Orleans.Core/Messaging/MessageSerializer.cs:line 110\n at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in /_/src/Orleans.Core/Networking/Connection.cs:line 299`

**Comment by alexf2017** [comment]
> [@alexf2017](https://github.com/alexf2017) is that during a rolling upgrade or are you deploying blue/green or fresh?

Fresh as replacing old .net6 upgraded .net to v8 together with orleans packages

**Comment by prfi01** [comment]
sorry, I may have been a bit unclear, this is an update from older version of orleans which we're replacing, meaning at the time of switch there will be messages created by v7 left for processing by v8

**Comment by elarrieux** [comment]
@ReubenBond we just saw this error today while doing a rolling upgrade from Orleans 8 to Orleans 9.

**Comment by elarrieux** [comment]
> > [@ReubenBond](https://github.com/ReubenBond) we just saw this error today while doing a rolling upgrade from Orleans 8 to Orleans 9.
> 
> 8.0.0 or a later version, and did you change anything else during the upgrade?

thanks for the quick reply, the upgrade was from 8.2.0 to 9.0.1, but I just realized I updated an existing interface which was the actual reason of the errors.

**Comment by turowicz** [comment]
It seems that these errors appeared only initially after migrating from v7 to v8, after 10-15mins it stops.

**Comment by dmitrig89** [comment]
> [@prfi01](https://github.com/prfi01) there was a break in wire compatibility (my mistake, it was required to fix a rare bug). This won't be an issue for messages stored in streams, but it prevents some messages from being compatible between 7.x hosts and 8.x hosts. If you shutdown the 7.x cluster and deploy an 8.x cluster it won't be an issue.
> 
> Please accept my apologies for the trouble caused

@ReubenBond Thanks for letting us know of this change.
We have a live cluster running v7 with multiple clients sending messages via grain invocations and host to host communications, we don't use streams. 
We can't really allow for a shutdown\brand new deployment because we are set up to always be running and only deploying via rolling restarts. 
What would you suggest may be the best approach to updating such a deployment?


Thanks
