### ISSUE TITLE
CleanupDefunctSiloEntries key insert is missing in sql files

### ISSUE THREAD

**Issue by ka4ep** [dotnet/orleans#8216]
I've created a new fresh Sql Server database, have run all the `System.Data.SqlClient` invariant queries for that database from the manual page https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/adonet-configuration. Program is configured to use it for storage, clustering and reminders; all the nuget packages are 7.0.0.
During silo start all of a sudden I've caught an exception:
```
System.ArgumentException: Not all required queries found. Missing are: CleanupDefunctSiloEntriesKey
   at Orleans.Clustering.AdoNet.Storage.DbStoredQueries..ctor(Dictionary`2 queries) in /_/src/AdoNet/Shared/Storage/DbStoredQueries.cs:line 39
   at Orleans.Clustering.AdoNet.Storage.RelationalOrleansQueries.CreateInstance(String invariantName, String connectionString) in /_/src/AdoNet/Shared/Storage/RelationalOrleansQueries.cs:line 71
   at Orleans.Runtime.MembershipService.AdoNetClusteringTable.InitializeMembershipTable(Boolean tryInitTableVersion) in /_/src/AdoNet/Orleans.Clustering.AdoNet/Messaging/AdoNetClusteringTable.cs:line 37
   at Orleans.Runtime.MembershipService.MembershipTableManager.Start() in /_/src/Orleans.Runtime/MembershipService/MembershipTableManager.cs:line 170
   at Orleans.Runtime.MembershipService.MembershipTableManager.<>c__DisplayClass59_0.<<Orleans-ILifecycleParticipant<Orleans-Runtime-ISiloLifecycle>-Participate>g__OnRuntimeGrainServicesStart|0>d.MoveNext() in /_/src/Orleans.Runtime/MembershipService/MembershipTableManager.cs:line 877
--- End of stack trace from previous location ---
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in /_/src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs:line 134
   at Orleans.LifecycleSubject.OnStart(CancellationToken cancellationToken) in /_/src/Orleans.Core/Lifecycle/LifecycleSubject.cs:line 118
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute() in /_/src/Orleans.Runtime/Scheduler/ClosureWorkItem.cs:line 34
   at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken) in /_/src/Orleans.Runtime/Silo/Silo.cs:line 213
```
Indeed, OrleansQuery table does not have `CleanupDefunctSiloEntries` query key:
![image](https://user-images.githubusercontent.com/5640372/206186544-e6b14a54-5068-4b26-bb4f-68d9e663ce97.png)
Then I've double-checked https://github.com/dotnet/orleans/tree/main/src/AdoNet and... there's no corresponding insert in any of .sql files.
What should be the QueryText for `CleanupDefunctSiloEntries`?

**Comment by ElanHasson** [comment]
Hi @ka4ep,

I think you may have uncovered a gap in our documentation.

You have to run all of the script migrations, in version order for each of the providers you're using.

See:

https://github.com/dotnet/orleans/tree/main/src%2FAdoNet%2FOrleans.Clustering.AdoNet%2FMigrations

**Comment by ElanHasson** [comment]
I'm not aware of any plans for auto-running the scripts as every single shop has a different way to manage DB schema changes and the tooling is different everywhere.

v3.7.0 hasn't yet been released (I believe it is in progress), but that is the "earliest version" where these changes would appear.

If you'd like automation, I have it here some here using `dotnet ef package` https://github.com/web-scheduler/web-scheduler/tree/main/Source/WebScheduler.DataMigrations, feel free to take that and make it your own ❤️. 


cc: @ReubenBond @benjaminpetit

**Comment by bnowlin** [comment]
It does not make sense to me for fresh 7.0 project to need to run migrations.

**Comment by ElanHasson** [comment]
Hi @bnowlin, 

Orleans does not have a mechanism to deploy the scripts.  The definition of "migration" here is to "apply all DB schema changes".

7.0 builds upon all DB schema changes since the beginning and therefore requires you to run all incrimental SQL scripts ("migrations") to bring you to correct state for 7.0.

**Comment by bnowlin** [comment]
Yes, I was able to get it working with the migrations before I posted. (My first comment may have been venting)

> I think you may have uncovered a gap in our documentation.

It is here that I am agreeing with. If you are starting 7.0 and going through the documentation then you will eventually hit https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/adonet-configuration for setting up database. As far as I am aware, this is the ONLY documentation on database schema. However, if you run all scripts found there and try to start a 7.0 project it will bomb with the CleanupDefunctSiloEntriesKey as first posted.

**Comment by olejorgenhauge** [comment]
There seems to be a typo in the Oracle migration script to 3.7.0. 'CleanupDefunctSiloEntriesKey' has been named 'DeleteMembershipTableEntriesKey' instead. Changing it to 'CleanupDefunctSiloEntriesKey' fixes the problem

**Comment by ElanHasson** [comment]
Thanks for calling this out @olejorgenhauge , because of licensing, we're unable to test the Oracle scripts in CI.

Can you please send a pull request with the verified fix?

Thanks!

**Comment by Neftedollar** [comment]
Same problem for Postgres

**Comment by wz172** [comment]
How does silo fit together？ I want to delete long dead silo

**Comment by ReubenBond** [comment]
Resolved for the SQL Server setup reported here by #8811. The base clustering script now registers CleanupDefunctSiloEntriesKey. #9125 and #8896 provide the corresponding PostgreSQL and MySQL registrations discussed above. The separate Oracle migration-key typo remains tracked in #8937. Closing this issue as completed for the corrected SQL Server/PostgreSQL/MySQL setup scripts.
