### ISSUE TITLE
[Error Orleans 7]: Cannot resolve scoped service 'Orleans.Streams.StreamDirectory' from root provider.

### ISSUE THREAD

**Issue by doctorcode-org** [dotnet/orleans#8219]
Hi
The exception is thrown when we create a singleton service and implement ILifecycleParticipant<ISiloLifecycle> and then call GetStream from IStreamProvider:
```
async Task ILifecycleObserver.OnStart(CancellationToken cancellationToken)
{
    Logger.LogInitializing(_logger, _hubName, _serverId);
    _streamProvider = _clusterClient.GetStreamProvider(PusherStream.StreamProvider);
    _serverStream = _streamProvider.GetStream<ClientMessage>(_serverId, PusherStream.ServerStream);
}
```
The participant state is ServiceLifecycleStage.Active.
The error detail:
```
2022-12-09 11:02:21    [Error-11:02:21.050 +03:30] Exception during Silo.Start System.InvalidOperationException: Cannot resolve scoped service 'Orleans.Streams.StreamDirectory' from root provider.
2022-12-09 11:02:21    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
2022-12-09 11:02:21    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2022-12-09 11:02:21    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2022-12-09 11:02:21    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2022-12-09 11:02:21    at Orleans.Runtime.Providers.SiloStreamProviderRuntime.GetStreamDirectory() in /_/src/Orleans.Streaming/Providers/SiloStreamProviderRuntime.cs:line 127
2022-12-09 11:02:21    at Orleans.Providers.Streams.Common.PersistentStreamProvider.GetStream[T](StreamId streamId) in /_/src/Orleans.Streaming/PersistentStreams/PersistentStreamProvider.cs:line 158
2022-12-09 11:02:21    at Orleans.Streams.StreamProviderExtensions.GetStream[T](IStreamProvider streamProvider, String ns, String id) in /_/src/Orleans.Streaming/Providers/IStreamProvider.cs:line 73
2022-12-09 11:02:21    at DoctorCode.Oms.Pusher.Sockets.OrleansHubLifetimeManager`1.Orleans.ILifecycleObserver.OnStart(CancellationToken cancellationToken) in D:\Projects\oms\pusher\DoctorCode.Oms.Pusher\Sockets\OrleansHubLifetimeManager.cs:line 68
```

**Comment by ReubenBond** [comment]
I am unsure about this one. Is it possible that you could provide more context on how your silo is configured?
How are streams being configured in your host?
This shouldn't happen, should it, @benjaminpetit?

**Comment by doctorcode-org** [comment]
Thank you @ReubenBond 
I will give an example of a very simple project with minimal configs.
The **Program.cs** code:
```
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Orleans;
using Orleans.Hosting;
using Orleans.Runtime;
using Orleans7Test;

var builder = WebApplication.CreateBuilder(args);

builder.Host.UseOrleans(siloBuilder =>
{
    siloBuilder.UseLocalhostClustering();
    siloBuilder.AddMemoryStreams("test");
    siloBuilder.Services.AddTransient(sp => (ILifecycleParticipant<ISiloLifecycle>)sp.GetRequiredService<SingletonService>());
});
builder.Services.AddSingleton<SingletonService>();


var app = builder.Build();
app.UseHttpsRedirection();

app.UseRouting();
app.MapGet("/", () => "Ready!");

app.Run();

```
The SingletonService.cs code:
```
using Orleans;
using Orleans.Runtime;
using Orleans.Streams;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Orleans7Test
{
    public class SingletonService : ILifecycleParticipant<ISiloLifecycle>, ILifecycleObserver
    {
        private readonly IClusterClient _clusterClient;

        public SingletonService(IClusterClient clusterClient)
        {
            _clusterClient = clusterClient;
        }

        public Task OnStart(CancellationToken cancellationToken = default)
        {
            _clusterClient
                        .GetStreamProvider("test")
                        .GetStream<string>("test-message")
                        .SubscribeAsync((data, token) =>
                        {
                            Console.WriteLine(data);
                            return Task.CompletedTask;
                        });
            return Task.CompletedTask;
        }

        public Task OnStop(CancellationToken cancellationToken = default)
        {
            return Task.CompletedTask;
        }

        public void Participate(ISiloLifecycle observer)
        {
            observer.Subscribe(
                nameof(SingletonService),
                ServiceLifecycleStage.Active,
                this);
        }
    }
}
```

**Comment by fwaris** [comment]
just ran into this issue - trying to access streaming from within a service start does not seem to work

**Comment by fwaris** [comment]
one workaround is to use lazy evaluation - delay stream provider access till after the start is done

**Comment by benjaminpetit** [comment]
Not sure to understand why it shouldn't work... Can you try to change the stage from `ServiceLifecycleStage.Active` to `ServiceLifecycleStage.Active + 1` and see if it works?

**Comment by doctorcode-org** [comment]
I changed the stage to **ServiceLifecycleStage.Active + 1**  but the exception didn't fix.
If I create an IHostedService and call the StreamProvider in its StartAsync method, no exception is thrown and it works correctly.

**Comment by galvesribeiro** [comment]
> just ran into this issue - trying to access streaming from within a service start does not seem to work

My error was precisely that.

After speaking with @ReubenBond we got it to work by wrapping the `OnStart` method with `Task.Run()` and await it.

```csharp
public void Participate(ISiloLifecycle lifecycle)
    {
        lifecycle.Subscribe(
           observerName: nameof(OrleansHubLifetimeManager<THub>),
           stage: ServiceLifecycleStage.Active,
           onStart: async ct => await Task.Run(EnsureStreamSetup, ct));
    }
```

That did the trick.

This is indeed a behavior that changed on v7 since that code used to work on 3.x.

I hope it help others.
