### ISSUE TITLE
Nodatime serialization 

### ISSUE THREAD

**Issue by SalimiHabib** [dotnet/orleans#8224]
After adding objects of nodatime as property to my types  , an error raised complaining about serialization of that property , there is a serialize package  for nodatime   but  how can it be introduced to silo to use  for that property  ?

[NodaTime.Serialization](https://www.nuget.org/packages/NodaTime.Serialization.JsonNet)

thank yo

**Comment by ReubenBond** [comment]
Hi @SalimiHabib, you could use the package you linked in conjunction with Newtonsoft.Json serialization support in Orleans: https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/serialization-configuration?pivots=orleans-7-0#configure-orleans-to-use-newtonsoftjson

Something like this should work:
```
siloBuilder.Services.AddSerializer(serializerBuilder =>
{
    serializerBuilder.AddNewtonsoftJsonSerializer(
        isSupported: type => type.Namespace is { } ns && ns.StartsWith("NodaTime"));
});
```

**Comment by ReubenBond** [comment]
This would be a good candidate for an OrleanContrib repository and several packages, Orleans.Serialization.X where X = NodaTime, etc

**Comment by SalimiHabib** [comment]
Above setting as you suggested is fine and work correctly ,  but service only find in first object initialization and next object rise an error because codec  not available in service collection   
constructor of generated code is as below(error raised on _codec1  parameter ):
```
public Codec_PSB(global::Orleans.Serialization.Activators.IActivator<global::aco.trs.com.poco.PSB> _activator, global::Orleans.Serialization.Serializers.ICodecProvider codecProvider)
        {
            this._activator = OrleansGeneratedCodeHelper.UnwrapService(this, _activator);
            _codec1 = OrleansGeneratedCodeHelper.GetService<global::Orleans.Serialization.Codecs.IFieldCodec<global::NodaTime.Instant>>(this, codecProvider);
            _codec4 = OrleansGeneratedCodeHelper.GetService<OrleansCodeGen.aco.trs.com.poco.Codec_LocationOfPSB>(this, codecProvider);
            _codec6 = OrleansGeneratedCodeHelper.GetService<global::Orleans.Serialization.Codecs.IFieldCodec<global::aco.trs.com.poco.TagStatus>>(this, codecProvider);
            _codec7 = OrleansGeneratedCodeHelper.GetService<OrleansCodeGen.aco.trs.com.poco.Codec_UsageAndLimitation>(this, codecProvider);
        }
```


first time it find as untyped codec wrapper , but next object initialization it is not exist in service collection 
`{Orleans.Serialization.Codecs.UntypedCodecWrapper<NodaTime.Instant>}`

error is as below 

```
Orleans.Serialization.CodecNotFoundException
  HResult=0x80131500
  Message=Could not find a codec for type NodaTime.Instant.
  Source=Orleans.Serialization
  StackTrace:
   at Orleans.Serialization.Serializers.CodecProvider.ThrowCodecNotFound(Type fieldType)
   at Orleans.Serialization.Serializers.CodecProvider.GetCodec[TField]()
   at Orleans.Serialization.ServiceCollectionExtensions.FieldCodecHolder`1.get_Value()
   at Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.GetService[TService](Object caller, ICodecProvider codecProvider)
   at OrleansCodeGen.aco.trs.com.poco.Codec_PSB..ctor(IActivator`1 _activator, ICodecProvider codecProvider) in E:\Users\hab\source\repos\aco.transport\be\aco.trs.com\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\aco.trs.com.orleans.g.cs:line 8976
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Orleans.Serialization.Serializers.CodecProvider.GetServiceOrCreateInstance(Type type, Object[] constructorArguments)
   at Orleans.Serialization.Serializers.CodecProvider.CreateCodecInstance(Type fieldType, Type searchType)
   at Orleans.Serialization.Serializers.CodecProvider.TryCreateCodec(Type fieldType)
   at Orleans.Serialization.Serializers.CodecProvider.TryGetCodec(Type fieldType)
   at Orleans.Serialization.SerializerConfigurationAnalyzer.<AnalyzeSerializerAvailability>g__VisitType|0_0(Type type, MethodInfo methodInfo, <>c__DisplayClass0_0& )
   at Orleans.Serialization.SerializerConfigurationAnalyzer.AnalyzeSerializerAvailability(ICodecProvider codecProvider, TypeManifestOptions options)
   at Orleans.SerializerConfigurationValidator.Orleans.IConfigurationValidator.ValidateConfiguration()
   at Orleans.ClusterClient.<.ctor>g__ValidateSystemConfiguration|3_1(IServiceProvider serviceProvider)
   at Orleans.ClusterClient..ctor(IServiceProvider serviceProvider, OutsideRuntimeClient runtimeClient, ILoggerFactory loggerFactory, IOptions`1 clientMessagingOptions)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Orleans.Configuration.Internal.ServiceCollectionExtensions.<>c__DisplayClass1_0.<AddFromExisting>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()

```


and setting in silo builder is :
```

JsonSerializerSettings jsonSerializerSettings = new JsonSerializerSettings();
jsonSerializerSettings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
siloBuilder.Services.AddSerializer(serializerBuilder =>
{
    serializerBuilder
    .AddNewtonsoftJsonSerializer(
        isSupported: type => type.Namespace is { } ns && ns.StartsWith("NodaTime"),
        jsonSerializerSettings);
});

```

**Comment by ReubenBond** [comment]
Interesting. I think that should work. Could you put together a small test case?

**Comment by SalimiHabib** [comment]
hi @ReubenBond ( this issue is continue of #8224)

Setting as you suggested is fine and work correctly ,  but service only find in first object initialization and next object rise an error because codec  not available in service collection   

and setting in silo builder is :
```

JsonSerializerSettings jsonSerializerSettings = new JsonSerializerSettings();
jsonSerializerSettings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
siloBuilder.Services.AddSerializer(serializerBuilder =>
{
    serializerBuilder
    .AddNewtonsoftJsonSerializer(
        isSupported: type => type.Namespace is { } ns && ns.StartsWith("NodaTime"),
        jsonSerializerSettings);
});

```


constructor of generated code is as below(error raised on _codec1  parameter ):
```
public Codec_PSB(global::Orleans.Serialization.Activators.IActivator<global::aco.trs.com.poco.PSB> _activator, global::Orleans.Serialization.Serializers.ICodecProvider codecProvider)
        {
            this._activator = OrleansGeneratedCodeHelper.UnwrapService(this, _activator);
            _codec1 = OrleansGeneratedCodeHelper.GetService<global::Orleans.Serialization.Codecs.IFieldCodec<global::NodaTime.Instant>>(this, codecProvider);
            _codec4 = OrleansGeneratedCodeHelper.GetService<OrleansCodeGen.aco.trs.com.poco.Codec_LocationOfPSB>(this, codecProvider);
            _codec6 = OrleansGeneratedCodeHelper.GetService<global::Orleans.Serialization.Codecs.IFieldCodec<global::aco.trs.com.poco.TagStatus>>(this, codecProvider);
            _codec7 = OrleansGeneratedCodeHelper.GetService<OrleansCodeGen.aco.trs.com.poco.Codec_UsageAndLimitation>(this, codecProvider);
        }
```


first time it find as untyped codec wrapper , but next object initialization it is not exist in service collection 
`{Orleans.Serialization.Codecs.UntypedCodecWrapper<NodaTime.Instant>}`

error is as below 

```
Orleans.Serialization.CodecNotFoundException
  HResult=0x80131500
  Message=Could not find a codec for type NodaTime.Instant.
  Source=Orleans.Serialization
  StackTrace:
   at Orleans.Serialization.Serializers.CodecProvider.ThrowCodecNotFound(Type fieldType)
   at Orleans.Serialization.Serializers.CodecProvider.GetCodec[TField]()
   at Orleans.Serialization.ServiceCollectionExtensions.FieldCodecHolder`1.get_Value()
   at Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.GetService[TService](Object caller, ICodecProvider codecProvider)
   at OrleansCodeGen.aco.trs.com.poco.Codec_PSB..ctor(IActivator`1 _activator, ICodecProvider codecProvider) in E:\Users\hab\source\repos\aco.transport\be\aco.trs.com\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\aco.trs.com.orleans.g.cs:line 8976
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Orleans.Serialization.Serializers.CodecProvider.GetServiceOrCreateInstance(Type type, Object[] constructorArguments)
   at Orleans.Serialization.Serializers.CodecProvider.CreateCodecInstance(Type fieldType, Type searchType)
   at Orleans.Serialization.Serializers.CodecProvider.TryCreateCodec(Type fieldType)
   at Orleans.Serialization.Serializers.CodecProvider.TryGetCodec(Type fieldType)
   at Orleans.Serialization.SerializerConfigurationAnalyzer.<AnalyzeSerializerAvailability>g__VisitType|0_0(Type type, MethodInfo methodInfo, <>c__DisplayClass0_0& )
   at Orleans.Serialization.SerializerConfigurationAnalyzer.AnalyzeSerializerAvailability(ICodecProvider codecProvider, TypeManifestOptions options)
   at Orleans.SerializerConfigurationValidator.Orleans.IConfigurationValidator.ValidateConfiguration()
   at Orleans.ClusterClient.<.ctor>g__ValidateSystemConfiguration|3_1(IServiceProvider serviceProvider)
   at Orleans.ClusterClient..ctor(IServiceProvider serviceProvider, OutsideRuntimeClient runtimeClient, ILoggerFactory loggerFactory, IOptions`1 clientMessagingOptions)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Orleans.Configuration.Internal.ServiceCollectionExtensions.<>c__DisplayClass1_0.<AddFromExisting>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()

```

**Comment by SalimiHabib** [comment]
of course 
I will create an send you test project .

**Comment by SalimiHabib** [comment]
projects as attached file contains:
1- ConsoleApp3 Orleans project ,grain and its interface 
2 - test project using Orleans test cluster 

behavior is same as original project and error raised  in second request  from container ( below constructor in generated code  )

```
public Codec_nodetestClass(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider)
{
    _codec0 = OrleansGeneratedCodeHelper.GetService<global::Orleans.Serialization.Codecs.IFieldCodec<global::NodaTime.Instant>>(this, codecProvider);
}
```


 

[ConsoleApp3.zip](https://github.com/dotnet/orleans/files/10289153/ConsoleApp3.zip)
[TestProject1.zip](https://github.com/dotnet/orleans/files/10289159/TestProject1.zip)

**Comment by SalimiHabib** [comment]
Is it possible to having conflict by  more than one container in silo configuration  ?

**Comment by ReubenBond** [comment]
You need to configure the serialization on the *client* as well as the silo.

**Comment by SalimiHabib** [comment]
It works now .

Thank you
