### ISSUE TITLE
F# host: Could not find an implementation for interface OrleansDashboard.IDashboardGrain - C# host ok

### ISSUE THREAD

**Issue by fwaris** [dotnet/orleans#8235]
Unable to host silo in F# console project. C# console project works fine. Please see attached minimal repo.

[FsGrains (2).zip](https://github.com/dotnet/orleans/files/10267813/FsGrains.2.zip)

Need to host in F# due to other F# frameworks (e.g. for web dev) required for the application.

Issue is with the 7.x version. This was not an issue with the 3.x.x version of Orleans. 

F# hosting works if 'UseDashboard' is commented out.

Error seen:
```
fail: Orleans.Runtime.SiloLifecycleSubject[100450]
      Orleans.Hosting.SiloBuilderStartupExtensions+StartupTask failed to start due to errors at stage Active (20000)
      System.ArgumentException: Could not find an implementation for interface OrleansDashboard.IDashboardGrain
         at Orleans.GrainInterfaceTypeToGrainTypeResolver.GetGrainType(GrainInterfaceType interfaceType) in /_/src/Orleans.Core/Core/GrainInterfaceTypeToGrainTypeResolver.cs:line 149
         at Orleans.GrainFactory.GetGrain(Type interfaceType, IdSpan grainKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 214
         at Orleans.GrainFactory.GetGrain[TGrainInterface](Int64 primaryKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 52
         at OrleansDashboard.Dashboard.ActivateDashboardGrainAsync()
         at OrleansDashboard.Dashboard.Execute(CancellationToken cancellationToken)
         at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in /_/src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs:line 134
f
```

**Comment by fwaris** [comment]
Update: I set ```<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>``` in the C# host project and found that there are 'generated' files for Dashboard grain serialization. 

No source is generated for F# so maybe that's the reason for the error. However, not sure what is the solution other than maybe support for F# code generation.

**Comment by fwaris** [comment]
After a little more digging, I found that adding parts of C# generated code - namely assembly attributes - to F# host, fixed this issue. 'Program.fs' is now as follows:

```F#
open Microsoft.Extensions.Hosting
open Orleans
open Orleans.Hosting

Host.CreateDefaultBuilder()
    .UseOrleans(fun siloBuilder -> 
        siloBuilder
          .UseDashboard()
          .UseLocalhostClustering() 
          .AddMemoryGrainStorage("store") |> ignore)
    .RunConsoleAsync()
|> Async.AwaitTask
|> Async.RunSynchronously

module Load =

    //[<assembly: Orleans.ApplicationPartAttribute("SiloCS")>]
    [<assembly: Orleans.ApplicationPartAttribute("GrainsCodeGen")>]
    [<assembly: Orleans.ApplicationPartAttribute("Orleans.Core.Abstractions")>]
    [<assembly: Orleans.ApplicationPartAttribute("Orleans.Serialization")>]
    [<assembly: Orleans.ApplicationPartAttribute("Orleans.Core")>]
    [<assembly: Orleans.ApplicationPartAttribute("Orleans.Persistence.Memory")>]
    [<assembly: Orleans.ApplicationPartAttribute("Orleans.Runtime")>]
    [<assembly: Orleans.ApplicationPartAttribute("Orleans.Reminders")>]
    [<assembly: Orleans.ApplicationPartAttribute("OrleansDashboard.Core")>]
    [<assembly: Orleans.ApplicationPartAttribute("OrleansDashboard")>]
    //[<assembly: global::Orleans.Serialization.Configuration.TypeManifestProviderAttribute(typeof(OrleansCodeGen.SiloCS.Metadata_SiloCS))]
    ()
```

I will use this as a workaround while waiting for the 'official' fix or recommendation.

Also not sure what the ```TypeManifestProvider``` attribute does and will a lack of it cause issues later on?

**Comment by fwaris** [comment]
linking reminders issue #8125. The workaround solution will likely work for the reminder table issue

**Comment by WesleySkeen** [comment]
Thanks legend. Nice one for this

**Comment by DejanMilicic** [comment]
I spent past three days looking for even a trivial end-to-end F#-only example of how to use Orleans with F#, and I am hitting several issues including this one.
Seems like F# is low priority for Orleans. What would be recommended solution - shall I set up mixed C# / F# project, with host written in C#? @fwaris what are your experiences?

**Comment by fwaris** [comment]
I had to put a minimal C# library in the solution for the code gen to work.

Below is a sample (prob. now out-of-date) that might help.

https://github.com/[fwaris/OrleansKafkaSample](https://github.com/fwaris/OrleansKafkaSample)

**Comment by DejanMilicic** [comment]
Thanx @fwaris !
I took some time to clean up your project and to strip it down to something that would be basic sample project for people who would like to use Orleans with F#. If you have a minute or two, I would be grateful if you could glance over the code to verify I am not making anything stupid - I am yet starting with Orleans.

@ReubenBond if you can glance over the code and verify this is the correct / best-practices way of setting up Orleans, that would be awesome.

Thanx!

https://github.com/DejanMilicic/OrleansFsharp

**Comment by fwaris** [comment]
@DejanMilicic sure I can take a quick look at it

**Comment by DejanMilicic** [comment]
@fwaris I am now proceeding further (in my private repo) and refactoring code to be more F# style.
As part of that refactoring, I am introducing messages in the form of discriminated union.
Call to grain succeeds, but received message is null. Clearly, it is a serialization problem.
I tried various things in past few days, but I did not manage to fix it.

Can you point me to a working example where F# type is successfully serialized and deserialized in the context of Orleans?
Thanx!

**Comment by fwaris** [comment]
in my prod app I think I side-stepped the problem by not using discriminated unions, as I was running into serialization issues also. 

(This seriously affects F# programming style!)

@ReubenBond hopefully we can get F# discriminated unions working again see https://github.com/dotnet/orleans/issues/9258

**Comment by fwaris** [comment]
thanks @ReubenBond, I was not aware of this.
@DejanMilicic can you please try the fix and let us know

**Comment by 64J0** [comment]
Hello everyone, is there any documentation that explains this C# code generation process? And were there any updates regarding F# support?
