### ISSUE TITLE
I am getting an error when persisting a state property of type ICollection<T>/Collection<T>.

### ISSUE THREAD

**Issue by dgeller-OUHSC** [dotnet/orleans#8237]
surfaced as a bug [on the orleans discord channel](https://discord.com/channels/333727978460676096/922945034427432980/1054815581032960030)

example of state class:

```
[GenerateSerializer]
public class RefreshGameResponse
{
	[Id(0)]
	public ICollection<int> Icol { get; private set; }
}
```

error when writing the state:
```
  Message: 
Orleans.Runtime.OrleansException : Error from storage provider MemoryGrainStorage.Default during WriteState for grain Type=ballcaller Id=1 Error=
 
Exc level 0: Orleans.Serialization.CodecNotFoundException: Could not find a copier for type System.Collections.ObjectModel.Collection`1[System.Int32].
   at Orleans.Serialization.Serializers.CodecProvider.ThrowCopierNotFound(Type type) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 657
   at Orleans.Serialization.Serializers.CodecProvider.GetDeepCopier(Type fieldType) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 326
   at Orleans.Serialization.Cloning.CopyContext.DeepCopy[T](T value) in /_/src/Orleans.Serialization/Cloning/IDeepCopier.cs:line 263
   at Orleans.Serialization.Codecs.ObjectCopier.Orleans.Serialization.Cloning.IDeepCopier.DeepCopy(Object input, CopyContext context) in /_/src/Orleans.Serialization/Codecs/ObjectCodec.cs:line 124
   at Orleans.Serialization.Cloning.UntypedCopierWrapper`1.DeepCopy(T original, CopyContext context) in /_/src/Orleans.Serialization/Cloning/IDeepCopier.cs:line 360
   at Orleans.Serialization.Cloning.IDeepCopier`1.Orleans.Serialization.Cloning.IDeepCopier.DeepCopy(Object input, CopyContext context) in /_/src/Orleans.Serialization/Cloning/IDeepCopier.cs:line 123
   at Orleans.Serialization.Cloning.CopyContext.DeepCopy[T](T value) in /_/src/Orleans.Serialization/Cloning/IDeepCopier.cs:line 263
   at OrleansCodeGen.Orleans.Storage.Proxy_IMemoryStorageGrain.global::Orleans.Storage.IMemoryStorageGrain.WriteStateAsync[T](String arg0, IGrainState`1 arg1) in /_/src/Orleans.Core/Orleans.CodeGenerator/Orleans.CodeGenerator.OrleansSerializationSourceGenerator/Orleans.Core.orleans.g.cs:line 5243
   at Orleans.Storage.MemoryGrainStorage.WriteStateAsync[T](String grainType, GrainId grainId, IGrainState`1 grainState)
   at Orleans.Core.StateStorageBridge`1.WriteStateAsync() in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 93
---- Orleans.Serialization.CodecNotFoundException : Could not find a copier for type System.Collections.ObjectModel.Collection`1[System.Int32].

  Stack Trace: 
StateStorageBridge`1.WriteStateAsync() line 104
BallCallerGrain.Join(Int32 playerId) line 36
TaskRequest.CompleteInvokeAsync(Task resultTask) line 707
--- End of stack trace from previous location ---
IValueTaskSource.GetResult(Int16 token) line 98
<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
BallCallerTest.JoinGame() line 23
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
CodecProvider.ThrowCopierNotFound(Type type) line 657
CodecProvider.GetDeepCopier(Type fieldType) line 326
CopyContext.DeepCopy[T](T value) line 263
IDeepCopier.DeepCopy(Object input, CopyContext context) line 124
UntypedCopierWrapper`1.DeepCopy(T original, CopyContext context) line 360
IDeepCopier.DeepCopy(Object input, CopyContext context) line 123
CopyContext.DeepCopy[T](T value) line 263
IMemoryStorageGrain.WriteStateAsync[T](String arg0, IGrainState`1 arg1) line 5243
MemoryGrainStorage.WriteStateAsync[T](String grainType, GrainId grainId, IGrainState`1 grainState)
StateStorageBridge`1.WriteStateAsync() line 93
--- End of stack trace from previous location ---

```

**Comment by ReubenBond** [comment]
Thank you for reporting, @dgeller-OUHSC. I have opened #8238 with a fix

**Comment by dgeller-OUHSC** [comment]
Thank you for the absurdly quick response!
