### ISSUE TITLE
[Proposal] Allow silos to publish multiple endpoints to membership

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#8268]
Currently, silos are identified by their IP address (`EndpointOptions.AdvertisedIPAddress`) which is also how other silos connect to them.

This presents problems in some cases. The one which people run into most frequently is where a host has multiple network adaptors. For example, when building locally and running in a docker container.

Another related problem is when the host has no ethernet connectivity: we currently fail to pick an IP address at all. Instead, we should pick a loopback adaptor, which is otherwise filtered out. We should not filter out loopback adaptors. Instead, we should sort them to the end of the candidate list (see https://github.com/dotnet/orleans/blob/bcc52fda1b5501dc4c27be37a3b6c4db2dcf8a1a/src/Orleans.Core/Configuration/ConfigUtilities.cs#L55).

Upon connection, we are exchanging identities and so we can verify that the connector has established a connection to the party they intended to. This would not be a security measure, of course, just a way to reduce the scope for misconfiguration. We must implement a validation if we are going to enable publishing loopback adaptors. We could also publish DnsHostName and use that to ensure that we do not connect to a loopback adaptor for a host on a different machine.

We should also consider listening on UnixDomainSockets by default and publishing those endpoints. We should consider allowing these endpoints to include some metadata, such as certificate thumbprints and protocol identifiers.

**Comment by amccool** [comment]
adding a little color.  scenario: 
* windows
* using ado.net on mssql.    membership table is populated with 172.27.96.1 (the docker adapter).  
* Single silo is listening on 0.0.0.0

```
PS C:\Users\amccool> netstat -ano | findstr 30000
  TCP    0.0.0.0:30000          0.0.0.0:0              LISTENING       24624
  TCP    172.27.96.1:14036      172.27.96.1:30000      ESTABLISHED     18164
  TCP    172.27.96.1:30000      172.27.96.1:14036      ESTABLISHED     24624
```
I have several local clients running 3.4.2 attempting to make a connection.  Upon manually modifying the membership table to 192.168.3.119 (a good local network address) I see the following.

```
Orleans.Networking | Establishing connection to endpoint S192.168.3.119:30000:0
Orleans.Networking | Connected to endpoint S192.168.3.119:30000:0
Orleans.Networking | Connection [Local: 192.168.3.119:18710, Remote: 192.168.3.119:30000, ConnectionId: 0HMO3RKQHVA9G] established with S192.168.3.119:30000:0
Orleans.Networking | Error processing connection [Local: 192.168.3.119:30000, Remote: 192.168.3.119:18710, ConnectionId: 0HMO3RKQHVA9H]

System.InvalidOperationException
Unexpected direct silo connection on proxy endpoint from S172.27.96.1:11111:412901279
at Orleans.Runtime.Messaging.GatewayInboundConnection.ProcessConnection() in /_/src/Orleans.Runtime/Networking/GatewayInboundConnection.cs:line 121    
at Orleans.Runtime.Messaging.Connection.Run() in /_/src/Orleans.Core/Networking/Connection.cs:line 185
```

two clients are still trying to connect.
one client has gotten a connection (?!?)

```
PS C:\Users\amccool> netstat -ano | findstr 30000
  TCP    0.0.0.0:30000          0.0.0.0:0              LISTENING       24624
  TCP    192.168.3.119:18008    192.168.3.119:30000    ESTABLISHED     18164
  TCP    192.168.3.119:18038    192.168.3.119:30000    ESTABLISHED     22876
  TCP    192.168.3.119:18086    192.168.3.119:30000    ESTABLISHED     24772
  TCP    192.168.3.119:30000    192.168.3.119:18008    ESTABLISHED     24624
  TCP    192.168.3.119:30000    192.168.3.119:18038    ESTABLISHED     24624
  TCP    192.168.3.119:30000    192.168.3.119:18086    ESTABLISHED     24624
  TCP    192.168.3.119:30000    192.168.3.119:19355    TIME_WAIT       0
  TCP    192.168.3.119:30000    192.168.3.119:19366    TIME_WAIT       0
```
```
PS C:\Users\amccool> netstat -ano | findstr 11111
  TCP    0.0.0.0:11111          0.0.0.0:0              LISTENING       24624
```

pid
24624 - silo
18164 - client one .....connected no idea how
22876 - client two  .... reporting not connected
24776 - client three ... reporting not connected

**Comment by amccool** [comment]
is this a bug?
```
Orleans.Networking | Error processing connection [Local: 192.168.3.119:30000, Remote: 192.168.3.119:18710, ConnectionId: 0HMO3RKQHVA9H]

System.InvalidOperationException
Unexpected direct silo connection on proxy endpoint from S172.27.96.1:11111:412901279
at Orleans.Runtime.Messaging.GatewayInboundConnection.ProcessConnection() in /_/src/Orleans.Runtime/Networking/GatewayInboundConnection.cs:line 121    
at Orleans.Runtime.Messaging.Connection.Run() in /_/src/Orleans.Core/Networking/Connection.cs:line 185
```

why is a 300000 port connection being proxied as a 11111 connection?
