### ISSUE TITLE
Error removing reminder from DynamoDb reminder provider

### ISSUE THREAD

**Issue by ADringer** [dotnet/orleans#8280]
Hi,

I've got the following error when trying to remove all reminders on a grain:

`Query condition missed key schema element: GrainReference 
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Orleans.Reminders.DynamoDB.DynamoDBStorage.QueryAsync[TResult](String tableName, Dictionary`2 keys, String keyConditionExpression, Func`2 resolver, String indexName, Boolean scanIndexForward, Dictionary`2 lastEvaluatedKey, Boolean consistentRead) in /_/src/AWS/Shared/Storage/DynamoDBStorage.cs:line 683
   at Orleans.Reminders.DynamoDB.DynamoDBStorage.QueryAllAsync[TResult](String tableName, Dictionary`2 keys, String keyConditionExpression, Func`2 resolver, String indexName, Boolean scanIndexForward, Boolean consistentRead)
   at Orleans.Reminders.DynamoDB.DynamoDBReminderTable.ReadRows(GrainReference grainRef) in /_/src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDBReminderTable.cs:line 148
   at Orleans.Runtime.ReminderService.LocalReminderService.GetReminders(GrainReference grainRef) in /_/src/Orleans.Runtime/ReminderService/LocalReminderService.cs:line 165`

This doesn't happen with all grains, only just noticed it today on a couple. I'm not sure why GrainReference would not be provided, as it's ran from the grain so should have an id?

The code that runs is:

```
public virtual async Task Deactivate()
        {
            if (Persistence.RecordExists)
                await Persistence.ClearStateAsync();

            var reminders = await GetReminders();
            reminders.ForEach(x => UnregisterReminder(x));
            
            DeactivateOnIdle();
        }
```

Is there anything obvious as to why I would get this error? Can't work out what could be causing it myself.

Thanks

**Comment by ADringer** [comment]
Spotted the obvious error - I was awaiting the `UnregisterReminder` method! I'll close this now
