### ISSUE TITLE
Failed to register activation in grain directory

### ISSUE THREAD

**Issue by aurokk** [dotnet/orleans#8350]
Hi!

I encountered a problem with my orleans cluster. When some grain is killed and created again in some other silo then the other silos emit such log `Failed to register activation in grain directory.` on every call to this restarted grain. It happens when a silo is being restarted, during a deployment for example.

### Case 1
I have a _long-running grain_, such grain that has a Task inside and it is supposed to be running for 5-10 minutes. This grain manages a payment, I have thousands of such grains active simultaneously and when I deploy the app it emits tens of thousands of such logs. When the payment is completed, the grain deactivates and the runtime stops producing the logs.

### Case 2
I have a  _long-running grain_, which is supposed to be active forever, it has a Task inside. This grain is a sharded data processor and each activation processes some shard. I make the grain active forever by polling each activation every N seconds. So this grain is active forever and when this problem happens with such a grain the runtime emits the logs _forever_ (actually, I'm not sure). 

### Question
Is it by design or is it a bug?

Currently, I muted such logs, but it looks bad :-)

### Repro
To reproduce the issue you need:
1. a cluster with 1+ silos
2. a grain with the random placement strategy
3. ping this grain each second for example
4. deactivate the grain periodically to trigger its activation in another silo

### Code
I created a small repro, it is not fully automated, but it can be used to reproduce the problem
https://github.com/aurokk/orleans-bug-repro-20-03-2023
```
1. docker-compose up -d
2. apply script.sql to the database
3. docker restart app-0
```

There is a full log from the prod app
```
Failed to register grain "[Activation: S10.0.87.96:11111:37973701/parallelizedjobcommandrunner/EventsToPaymentCommands:1:8@c2aa76bfb38248fe94f3f4d7f2371c67#Placement=RandomPlacement State=Invalid]" in grain directory

Failed to forward message "Request [S10.0.87.96:11111:37973701 sys.client/hosted-10.0.87.96:11111@37973701]->[S10.0.87.96:11111:37973701 parallelizedjobcommandrunner/EventsToPaymentCommands:7:8] Dodo.PaymentGateway.App.ParallelizedJobs.IParallelizedJobCommandRunnerDodo.PaymentGateway.App.ParallelizedJobs.IParallelizedJobCommandRunner.Ping() #45083[ForwardCount=3]" from "[GrainAddress GrainId parallelizedjobcommandrunner/EventsToPaymentCommands:7:8, ActivationId: @77a5f421aadb49eb8b96eac8d1a5c140, SiloAddress: S10.0.87.96:11111:37973701]" to "[GrainAddress GrainId parallelizedjobcommandrunner/EventsToPaymentCommands:7:8, ActivationId: @96b0bc91a59548a18fbc61a0fca8f120, SiloAddress: S10.0.87.96:11111:37973701]" after "Failed to register activation in grain directory.". Attempt 3
```

**Comment by jamescarter-le** [comment]
I also have this, a Grain that separate worker services poll from outside the cluster every second for a new batch of work.
I do a rolling deployment with 2/3 silo's Healthy during the deployment, and this error appears along with a forwarding request issue.

`[Warning] Orleans.Grain: Failed to register grain [Activation: S10.0.2.209:11111:40919026/<GRAINTYPE>/0@84a9b6865f6a44d1a43271864c08c7ed#Placement=RandomPlacement State=Invalid] in grain directory`

`[Information] Orleans.Messaging: Forwarding 1 requests destined for address [GrainAddress GrainId <GRAINTYPE>/0, ActivationId: @6d978dffe2454926a71fc7d6869859dc, SiloAddress: S10.0.2.209:11111:40919026] to address [GrainAddress GrainId <GRAINTYPE>/0, ActivationId: @16943d412e16411fa5b744ae82c479ee, SiloAddress: S10.0.3.13:11111:40918856] after Failed to register activation in grain directory.`

**Comment by sheng-jie** [comment]
Hi @ReubenBond Could you help to look at this issue? Thanks.

I encountered the same problem, and the debugging log information is as follows, which includes the call stack, but does not print the real exception message. Therefore, it is difficult to determine the specific exception that caused the registration failure. It is recommended to log the exception message in [MessageFactory.CreateRejectionResponse()](https://github.com/dotnet/orleans/blob/main/src/Orleans.Core/Messaging/MessageFactory.cs#L62) method for analysis and troubleshooting.


```
2023-09-28 17:52:32.8889|DEBUG|Orleans.Runtime.MessageFactory|machine: cluster-be-7ff8dd78d9-cbgrw
Creating Transient rejection with info 'Forwarding failed: tried to forward message Request [S10.4.6.10:11111:54801936 pod/51fe592f0000ff000000000000000000+47.13.21.81]->[S10.4.6.9:11111:54801861 cloud/36d53cac28654d3a86e1673fb1d4753d] PCloud.IPodGrain.GetState() #38660402[ForwardCount=2] for 2 times after "Failed to register activation in grain directory." to invalid activation. Rejecting now. ' at:
   at Orleans.Runtime.MessageFactory.CreateRejectionResponse(Message request, RejectionTypes type, String info, Exception ex)
   at Orleans.Runtime.Messaging.MessageCenter.RejectMessage(Message message, RejectionTypes rejectionType, Exception exc, String rejectInfo)
   at Orleans.Runtime.Messaging.MessageCenter.TryForwardRequest(Message message, GrainAddress oldAddress, SiloAddress forwardingAddress, String failedOperation, Exception exc)
   at Orleans.Runtime.Messaging.MessageCenter.ProcessRequestsToInvalidActivation(List`1 messages, GrainAddress oldAddress, SiloAddress forwardingAddress, String failedOperation, Exception exc, Boolean rejectMessages)
   at Orleans.Runtime.ActivationData.RerouteAllQueuedMessages()
   at Orleans.Runtime.ActivationData.<RunMessageLoop>g__ProcessRequestsToInvalidActivation|126_2()
   at Orleans.Runtime.ActivationData.<RunMessageLoop>g__ProcessPendingRequests|126_0()
   at Orleans.Runtime.ActivationData.RunMessageLoop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<>c.<Run>b__2_0(Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run(Task ignored, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at Orleans.Runtime.ActivationData.<RunMessageLoop>g__ProcessOperationsAsync|126_4(List`1 operations)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<>c.<Run>b__2_0(Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run(Task ignored, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at Orleans.Runtime.ActivationData.ActivateAsync(Dictionary`2 requestContextData, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<>c.<Run>b__2_0(Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run(Task ignored, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at Orleans.Runtime.ActivationData.RegisterActivationInGrainDirectoryAndValidate()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<>c.<Run>b__2_0(Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run(Task ignored, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at Orleans.Runtime.GrainDirectory.DhtGrainLocator.Register(GrainAddress address, GrainAddress previousAddress)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<>c.<Run>b__2_0(Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run(Task ignored, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.RegisterAsync(GrainAddress address, GrainAddress previousAddress, Int32 hopCount)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<>c.<Run>b__2_0(Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.RunTask(Task task)
   at Orleans.Runtime.Scheduler.WorkItemGroup.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by ReubenBond** [comment]
Hi @sheng-jie, was this during a rolling deployment?

**Comment by sheng-jie** [comment]
Hi @ReubenBond , it wasn't during a rolling deployment.

**Comment by ReubenBond** [comment]
I've opened https://github.com/dotnet/orleans/pull/8696 & https://github.com/dotnet/orleans/pull/8704 to fix this issue. We will create a release shortly.

**Comment by ReubenBond** [comment]
The v7.2.3 release which aims to fix this is now available, so I will close this but please open a new issue and reference this if you still encounter this issue: https://github.com/dotnet/orleans/releases/tag/v7.2.3
