### ISSUE TITLE
Missing messages, not delivered, MemoryStream

### ISSUE THREAD

**Issue by jamescarter-le** [dotnet/orleans#8399]
I am using MemoryStream, and whilst I know it is not a Guaranteed Delivery mechanism, I have a low frequency of messages (maybe 1 per 5 minutes currently) and would not expect to loose a lot (any) of messages when operating inside a VPC, over TCP.

I notice that I can sometimes get this Error log, and can usually it is one particular stream that seems to die, but it is not reliable, sometimes it does come back. I get no exceptions calling OnNextBack on the producer.

```
Message: An error occurred on the stream

Orleans.Streams.QueueCacheMissException: Item not found in cache.  Requested: [EventSequenceToken: SeqNum=638174475994405873, EventIndex=0], Low: [EventSequenceToken: SeqNum=638174475994405875, EventIndex=0], High: [EventSequenceToken: SeqNum=638174475994405875, EventIndex=0]
   at Orleans.Providers.Streams.Common.PooledQueueCache.SetCursor(Cursor cursor, StreamSequenceToken sequenceToken) in /_/src/Orleans.Streaming/Common/PooledCache/PooledQueueCache.cs:line 215
   ........
   at Orleans.Streams.PersistentStreamPullingAgent.DoHandshakeWithConsumer(StreamConsumerData consumerData, StreamSequenceToken cacheToken) in /_/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs:line 305
```

The grain subscribed is a long running grain, (it has it's own scoped Websocket to a client API), so it resubscribed on cluster start, or if a silo is restarted due to rolling upgrade.

Any idea's where to start debugging this? The message is a simple POCO `struct`, and contains strings and value types, with 1 enum.
Decorated with `GenerateSerializer` and the `Id(n)` attributes.

**Comment by jamescarter-le** [comment]
It looks like I was mistaken about `OnErrorAsync` not being invoked, it is indeed where I am catching the above exception and logging it.

I found this ticket: https://github.com/dotnet/orleans/issues/850 which appears to go over this, which seems to mention it has been resolved, but I'm not sure how to handle this in my own scenario, without loosing messages.

I am not providing a SequenceToken on resume (as I am using a MemoryStream anyway).

Unsure if this is a bug in the MemoryStream, or if it is state that has gone bad somehow in my Grains?  The SeqNum mentioned above `638174475994405873` it excessively large if this is a sequential id of the last message on the Stream, this number should be in the region of 2000 or so if it starts from Zero on a new stream.

**Comment by jamescarter-le** [comment]
On the Producer the Stream I am publishing too it cached once it is first created. Maybe this is an issue when I perform a rolling upgrade and the Queue moves Silo?
```
            if (_stream is null)
            {
                var streamId = StreamId.Create(StreamNamespace_BinanceLeaderboardPositionEvents,
                    _state.State.Identifier);
                _stream = this.GetStreamProvider(StreamProvider_BinanceLeaderboardPositionEvents)
                    .GetStream<BinanceLeaderboardPositionEvent>(streamId);
            }
            ```

**Comment by jamescarter-le** [comment]
Does anyone have any information on this issue?
What should I be doing with my Consumers if this error occurs?
Whenever I do a Cluster upgrade, it is likely this error will occur and I lose messages on streams:

![image](https://user-images.githubusercontent.com/1643692/235145051-e2506519-8e1e-4f39-a826-430f60202aa4.png)

**Comment by jamescarter-le** [comment]
I believe the silo is being shutdown correctly, as I see my Consumers logging they are being deactivated before the silo count reduces in the Dashboard. But I get these messages coming up, just wondering if something is wrong with cluster health and that could be why this issue is happening?


```
[Warning] Orleans.Grain: Failed to register grain [Activation: S10.0.2.16:11111:41886690/<GRAINID>#Placement=RandomPlacement State=Invalid] in grain directory
[Information] Orleans.Messaging: Trying to forward Request [S10.0.2.16:11111:41886690 sys.client/44f96651316a4235b196861b937ad370]->[S10.0.2.16:11111:41886690 <GRAINID>] GrainType.SubmitPerpData() #2030598 from [GrainAddress GrainId <GRAINID>, ActivationId: @d268d5afb2c2412386451534556041a3, SiloAddress: S10.0.2.16:11111:41886690] to [GrainAddress GrainId <GRAINID>, ActivationId: @22ed7f20597d4fb6bf9d45839e9c3381, SiloAddress: S10.0.3.210:11111:41886870] after Failed to register activation in grain directory.. Attempt 0
```

I get many hundreds of these errors, my understanding was I should be able to replace the silos without the clients/cluster having these kind of issues?

Maybe it's something I'm doing wrong in my configuration? I am adding `UseDynamoDBClustering` on both Silo and Client hosts.

I have just done a rolling upgrade to see if one of my Streams comes back, one of my two Consumers (I only have 2 for this testing) was no longer receiving OnNextAsync from it's explicit stream. It was not blocked.
Subscribing to this same Stream from a second Consumer, (without restarting the cluster) was able to receive these messages.

This is why I just did a rolling upgrade. Can you confirm this approach is acceptable?

Before Refresh Silos:
![before_update_cluster](https://user-images.githubusercontent.com/1643692/235372649-3e75feda-8cc3-4f15-b44e-677654e50d92.png)


During Refresh Silos:
![6_silos_total](https://user-images.githubusercontent.com/1643692/235372653-3cd1f17e-a0ba-4867-8dad-9160d804127c.png)


After Refresh Silos:
![fully_replaced](https://user-images.githubusercontent.com/1643692/235372661-918faeae-29ad-42be-bdf7-102b51aa71be.png)

**Comment by jamescarter-le** [comment]
OK after the Silo restarted, I was able to repo it straight away.
My Consumers did ResumeAsync, my Producers started to emit messages, and nothing turns up on the Consumers.

I'm not passing a SequenceToken on the Producers, as it is a memory stream and Optional on the interface, could this be the issue? Because the silo is not actually shutdown, and the streams live on, could the sequence be totally out? And why I got ~200k `QueueCacheMissExceptions` originally?

**Comment by jamescarter-le** [comment]
Just done another rolling upgrade as part of development, this time it generated ~560K `QueueCacheMissException` in 30 minutes.

I do not know if the streams are still alive or not.

Any thoughts from the team would be greatly appreciate.

![image](https://user-images.githubusercontent.com/1643692/235698885-a4686ba1-5c66-44bd-aaeb-1bebb65b009f.png)

**Comment by jamescarter-le** [comment]
Is there a specific Type and LogLevel I should enable to help me debug this? Looks like PersistentStreamPullingAgent is not emitting no errors or warnings. 

Anything else I should be looking for?
To me it feels like something is Blocked or stuck in some unrecoverable state but there is nothing output in the logs to say what.

**Comment by benjaminpetit** [comment]
Sorry I haven't had the time to look at your issue yet.

Are you 100% sure that your silos are shutting down gracefully on rolling upgrade? Do you see warning/errors about silos failing to respond to probe messages?

**Comment by jamescarter-le** [comment]
Thanks @benjaminpetit I'm just trying to gather as much information as I can.

I think maybe I have a rough location, indicated by the fact that the application emits these errors for ~30 mins (which is the same as the default Queue purge time?).

https://github.com/dotnet/orleans/blob/01475f531c27c1c1fa7bc6f20827ffc8a50e5636/src/Orleans.Streaming/Common/PooledCache/PooledQueueCache.cs#L201


Here is the data from the actual QueueCacheMissExceptions:

```
Req:  [EventSequenceToken: SeqNum=638186329955314832, EventIndex=0],
Low:  [EventSequenceToken: SeqNum=638186308533223378, EventIndex=0],
High: [EventSequenceToken: SeqNum=638186329955314832, EventIndex=0]
```

It looks like the Requested message is greater than what it believes is the Oldest Message, but the lastPurgedToken has not yet been set? In this case it throws QueueCacheMissException, doesn't change the Cursor, and it will just continue this loop?

I do not get any errors from silos about probe messages, and am logging the `Silo shutdown` messages in my logs.

**Comment by jamescarter-le** [comment]
I tried another mechanism for rolling update of bringing down 1 silo, then replacing it when it was shutdown. Instead of creating 3 new silos, and dropping the older 3 when the new 3 joined, as I thought if ALL the old silos shutdown at the same time it could create this issue.

No joy, after it had finished recycling all silos. The streams ended up unresponsive again.

Infact, it generated so many `QueueCacheMissException` at a rate that my AWS Logger buffer ran out of space.

**Comment by benjaminpetit** [comment]
When using `MemoryStream`, the `SequenceNumber` starts from the `DateTime.UtcNow.Ticks` value when the `MemoryStreamQueueGrain` was first activated, so it's expected that's not 0 or a low number. `SequenceNumber` is then incremented for each message enqueued.

It is somewhat expected to see `QueueCacheMissException` when doing a rolling upgrade when using `MemoryStream`: the stream queue (with this provider only) are stored in grains, that are deactivated from silos shutting down.

When this grain queue is reactivated somewhere else, the `SequenceNumber` starts again from `DateTime.UtcNow.Ticks`.

`LastPurgedToken` is not helping in your case either, because it's also a silo local value, that is lost when a silo shuts down.

> I do not get any errors from silos about probe messages, and am logging the Silo shutdown messages in my logs.

But the log line 

> [Warning] Orleans.Streams.PubSubRendezvousGrain: Producer PubSubPublisherState:StreamId=<StreamNamespace&Type>/538E78E33A3B0363FC37E393EB334103,Producer=sys.svc.stream.agent/10.0.3.250:11111@42038429+EventType_5_eventtype-1-0x20000001. on stream <StreamNamespace&Type>/538E78E33A3B0363FC37E393EB334103 is no longer active - permanently removing producer.

really looks like a silo did not had enough time to shut down properly.

Do you see the new silos starting new pulling agents?

If you could send me the full silos log it could be very helpful.

**Comment by jamescarter-le** [comment]
@benjaminpetit 

Do you have a secure way for me to send the log files to you directly?

![image](https://github.com/dotnet/orleans/assets/1643692/defce82e-fbd8-4909-8c57-57f12b598010)

![image](https://github.com/dotnet/orleans/assets/1643692/bb3dea26-91c7-4279-b2ac-bb6d227fdbb3)

**Comment by luckyycode** [comment]
Anything new about this issue?
