### ISSUE TITLE
Grain with attribute [GrainType] can't create grain with generic type

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/orleans#8448]
I have this deffinition for garain
``` cs
[Reentrant]
[GrainType($"ManagedCode.${nameof(SignalRInvocationGrain<THub>)}")]
public class SignalRInvocationGrain<THub> : Grain, ISignalRInvocationGrain<THub>
{
    private readonly ILogger<SignalRInvocationGrain<THub>> _logger;
    private readonly IPersistentState<InvocationInfo> _stateStorage;
    private readonly IOptions<OrleansSignalROptions> _options;
    
    public SignalRInvocationGrain(ILogger<SignalRInvocationGrain<THub>> logger,  
        [PersistentState(nameof(SignalRInvocationGrain<THub>), OrleansSignalROptions.OrleansSignalRStorage)] IPersistentState<InvocationInfo> stateStorage,
        IOptions<OrleansSignalROptions> options)
    {
        _logger = logger;
        _stateStorage = stateStorage;
        _options = options;
    }
...
```

When I try to call method I recive this error

```Type Microsoft.Extensions.Logging.ILogger`1[ManagedCode.Orleans.SignalR.Server.SignalRInvocationGrain`1[THub]] contains generic parameters (Parameter 'type')```

```
   at System.Dynamic.Utils.TypeUtils.ValidateType(Type type, String paramName, Int32 index)
   at System.Dynamic.Utils.TypeUtils.ValidateType(Type type, String paramName, Boolean allowByRef, Boolean allowPointer)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.BuildFactoryExpression(ConstructorInfo constructor, Nullable`1[] parameterMap, Expression serviceProvider, Expression factoryArgumentArray)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(Type instanceType, Type[] argumentTypes)
   at Orleans.Runtime.ConfigureDefaultGrainActivator.Configure(GrainType grainType, GrainProperties properties, GrainTypeSharedContext shared) in /_/src/Orleans.Runtime/Activation/IGrainContextActivator.cs:line 406
   at Orleans.Runtime.GrainTypeSharedContextResolver.Create(GrainType grainType) in /_/src/Orleans.Runtime/Activation/IGrainContextActivator.cs:line 250
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orleans.Runtime.GrainTypeSharedContextResolver.GetComponents(GrainType grainType) in /_/src/Orleans.Runtime/Activation/IGrainContextActivator.cs:line 233
   at Orleans.Runtime.ActivationDataActivatorProvider.TryGet(GrainType grainType, IGrainContextActivator& activator) in /_/src/Orleans.Runtime/Activation/ActivationDataActivatorProvider.cs:line 54
   at Orleans.Runtime.GrainContextActivator.CreateActivator(GrainType grainType) in /_/src/Orleans.Runtime/Activation/IGrainContextActivator.cs:line 78
   at Orleans.Runtime.GrainContextActivator.CreateInstance(GrainAddress address) in /_/src/Orleans.Runtime/Activation/IGrainContextActivator.cs:line 59
   at Orleans.Runtime.Catalog.GetOrCreateActivation(GrainId& grainId, Dictionary`2 requestContextData) in /_/src/Orleans.Runtime/Catalog/Catalog.cs:line 273
   at Orleans.Runtime.Messaging.MessageCenter.ReceiveMessage(Message msg) in /_/src/Orleans.Runtime/Messaging/MessageCenter.cs:line 486
--- End of stack trace from previous location ---
   at Orleans.Serialization.Invocation.ResponseCompletionSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 98
   at ManagedCode.Orleans.SignalR.Core.SignalR.OrleansHubLifetimeManager`1.InvokeConnectionAsync[T](String connectionId, String methodName, Object[] args, CancellationToken cancellationToken) in /Users/ksemenenko/Developer/Orleans.SignalR/ManagedCode.Orleans.SignalR.Core/SignalR/OrleansHubLifetimeManager.cs:line 220
```

**Comment by KSemenenko** [comment]
option with name "[GrainType("randomname")] throw the same error

**Comment by KSemenenko** [comment]
without ILogger exeption is:
```
Type ManagedCode.Orleans.SignalR.Server.SignalRInvocationGrain`1[THub] is a generic type definition (Parameter 'constructor')
```

**Comment by KSemenenko** [comment]
Also when I removed all parameters from contrcutory anyway grain is throw the same error

**Comment by ReubenBond** [comment]
You need to put the generic arity on the grain type name, eg, hub`1

**Comment by KSemenenko** [comment]
thanks!
