### ISSUE TITLE
Help with System.AccessViolationException

### ISSUE THREAD

**Issue by fernandozago** [dotnet/orleans#8513]
Hello Guys, 

Im receiving this exception. 
And none of this exception stack is related with my code...

I can't find the problem...

Edit:
I cant get a consistent problem. But I noticed that the problem occurs when i have the dashboard open on "Activations by Type" page....

by the looks of things, i should add this ticket on https://github.com/OrleansContrib/OrleansDashboard issues.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryGetValueInternal(System.__Canon, Int32, System.__Canon ByRef)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddOrUpdate(System.__Canon, System.Func`2<System.__Canon,System.__Canon>, System.Func`3<System.__Canon,System.__Canon,System.__Canon>)
   at OrleansDashboard.Metrics.GrainProfiler.Track(Double, System.Type, System.String, Boolean)
   at OrleansDashboard.Implementation.GrainProfilerFilter.Track(Orleans.IIncomingGrainCallContext, System.Diagnostics.Stopwatch, Boolean)
   at OrleansDashboard.Implementation.GrainProfilerFilter+<Invoke>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[OrleansDashboard.Implementation.GrainProfilerFilter+<Invoke>d__7, OrleansDashboard, Version=7.2.1.0, Culture=neutral, PublicKeyToken=null]](<Invoke>d__7 ByRef)
   at OrleansDashboard.Implementation.GrainProfilerFilter.Invoke(Orleans.IIncomingGrainCallContext)
   at Orleans.Runtime.GrainMethodInvoker+<Invoke>d__35.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Orleans.Runtime.GrainMethodInvoker+<Invoke>d__35, Orleans.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]](<Invoke>d__35 ByRef)
   at Orleans.Runtime.GrainMethodInvoker.Invoke()
   at Orleans.Runtime.InsideRuntimeClient+<Invoke>d__48.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Orleans.Runtime.InsideRuntimeClient+<Invoke>d__48, Orleans.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]](<Invoke>d__48 ByRef)
   at Orleans.Runtime.InsideRuntimeClient.Invoke(Orleans.Runtime.IGrainContext, Orleans.Runtime.Message)
   at Orleans.Runtime.ActivationData.InvokeIncomingRequest(Orleans.Runtime.Message)
   at Orleans.Runtime.ActivationData.<RunMessageLoop>g__ProcessPendingRequests|122_0()
   at Orleans.Runtime.ActivationData+<RunMessageLoop>d__122.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Orleans.Runtime.ActivationData+<RunMessageLoop>d__122, Orleans.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.RunTask(System.Threading.Tasks.Task)
   at Orleans.Runtime.Scheduler.WorkItemGroup.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

**Comment by ReubenBond** [comment]
That's scary. Can you reproduce it? It may be an issue with ConcurrentDictionary

**Comment by fernandozago** [comment]
Hi @ReubenBond ,

I'm trying to create something to reproduce more reliable. Because it's being very intermittent. 

But it happens more often than not.
Im not doing anything weird.

I have 4 main components:
(HostedService) KafkaConsumer (Responsible for Connecting to Kafka and Consume the messages - 200 partitions)
KafkaPartitionGrain (int pk) - Receive messages from its partition
UserGrain (int pk) - Called by KafkaPartitionGrain for updating the state
MemoryStream - Called by the UserGrain

```
KafkaConsumer -> KafkaPartitionGrain -> UserGrain -> MemoryStream
```

I'm not using any of the OneWay or Reentrancy on any of those steps.

I dont need realy much of troughtput. we are processing +- 12K messages per second from kafka

**Comment by ReubenBond** [comment]
It doesn't look like a scenario issue, unless the Kafka library is corrupting random memory.

Regular C# code should never produce this error.

**Comment by fernandozago** [comment]
I dont think that is the kafka lib, i splitted the consumer to another app, and used the orleans client to send messages to KafkaPartitionGrain, and it still happens (on the orleans cluster app)...

I think that i have a bad memory problem or is something on OS.

I tried different machines, and the problem does not occur.

Sorry about that! I think we can close this out.

Thank you @ReubenBond
