### ISSUE TITLE
Dashboards do not work on v7.2.0

### ISSUE THREAD

**Issue by tomhreb** [dotnet/orleans#8536]
Hi,
I have registration of dashboards as below.

```csharp
builder.UseDashboard(_ => { });
```

After updating to v7.2.0, it give me only following error on silo start:

```
fail: Orleans.Runtime.SiloLifecycleSubject[100450]
      Lifecycle start canceled due to errors at stage 20000
      System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask Orleans.Runtime.GrainReference.InvokeAsync(Orleans.Serialization.Invocation.IInvokable)'.
         at OrleansCodeGen.OrleansDashboard.Proxy_IDashboardGrain.global::OrleansDashboard.IDashboardGrain.Init()
         at OrleansDashboard.Dashboard.ActivateDashboardGrainAsync()
         at OrleansDashboard.Dashboard.Execute(CancellationToken cancellationToken)
         at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in /_/src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs:line 134
         at Orleans.LifecycleSubject.OnStart(CancellationToken cancellationToken) in /_/src/Orleans.Core/Lifecycle/LifecycleSubject.cs:line 118
```

**Comment by ReubenBond** [comment]
Dashboard issues should be opened on the dashboard repo. There is an existing issue opened for this and it was fixed: https://github.com/OrleansContrib/OrleansDashboard/issues/402 and hopefully a new version of the dashboard will be released soon

**Comment by tomhreb** [comment]
Sorry, I forgot there are multiple packages. Thanks!
