### ISSUE TITLE
exception: Activation access violation. A non-activation thread attempted to access activation services

### ISSUE THREAD

**Issue by nikhilvc** [dotnet/orleans#8567]
Some times i am getting an error like this in my grain 

System.InvalidOperationException
  HResult=0x80131509
  Message=Activation access violation. A non-activation thread attempted to access activation services.
  Source=Orleans.Runtime

  StackTrace:
   at Orleans.Runtime.GrainRuntime.<CheckRuntimeContext>g__ThrowMissingContext|20_0()
   at Orleans.Runtime.GrainRuntime.CheckRuntimeContext(IGrainContext context)
   at Orleans.Core.StateStorageBridge`1.get_State()
   at Orleans.Runtime.PersistentStateFactory.PersistentStateBridge`1.get_State()

Any thoughts? Thank you in advance.

**Comment by ReubenBond** [comment]
This is likely caused by a ConfigureAwait(false) or similar in your grain code. Alternatively, something else which is causing your code to execute off the grain's scheduler
