### ISSUE TITLE
Deserializing state with Redis persistence can fail in certain scenarios when using the Orleans binary serializer

### ISSUE THREAD

**Issue by tanordheim** [dotnet/orleans#8624]
I've been triaging a curious issue today where we silently lost state in some of our grains using Redis persistence after grains restarted (and state was re-read from Redis). I have tracked this down to a specific scenario where:

1. Redis is being used for persistence.
2. Redis persistence is configured using the Orleans binary serializer.
3. The type being persisted has a reference to another serialized type that lives in another assembly.

Without 3) this seems to work just fine. It also works fine if using the JSON serializer. The issue is not reproducible with for example the DynamoDB persistence provider while also using Orleans binary serialization.

I have created a reproducible demo here: [tanordheim/orleans-redis-serialization-bug](https://github.com/tanordheim/orleans-redis-serialization-bug/tree/main). The readme contains info on how to reproduce, and allows you to test the state of a grain before/after reactivation with either DynamoDB or Redis storage, and either JSON or Orleans binary serialization. All combinations of there work just fine apart from Redis and Orleans binary serialization.

This affects the latest Orleans 7.2.1 release. I have not tested it on older releases.

**Comment by ReubenBond** [comment]
What should happen in this case?

**Comment by tanordheim** [comment]
Sure thing, the Redis + Orleans binary serialization produces this stack trace:

```
Orleans.Persistence.Redis.RedisStorageException: Failed to read grain state for MyState with ID stateful/ff0055a8d0ce46089b30b260951e61b2 and storage key default/state/stateful/ff0055a8d0ce46089b30b260951e61b2/MyState. System.InvalidOperationException: Insufficient data present in buffer.
    at Orleans.Persistence.RedisGrainStorage.ReadStateAsync[T](String grainType, GrainId grainId, IGrainState`1 grainState) in /_/src/Redis/Orleans.Persistence.Redis/Storage/RedisGrainStorage.cs:line 142
    at Orleans.Core.StateStorageBridge`1.ReadStateAsync() in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 72
  ---> Orleans.Persistence.Redis.RedisStorageException: Failed to read grain state for MyState with ID stateful/ff0055a8d0ce46089b30b260951e61b2 and storage key default/state/stateful/ff0055a8d0ce46089b30b260951e61b2/MyState. System.InvalidOperationException: Insufficient data present in buffer.
    at Orleans.Persistence.RedisGrainStorage.ReadStateAsync[T](String grainType, GrainId grainId, IGrainState`1 grainState) in /_/src/Redis/Orleans.Persistence.Redis/Storage/RedisGrainStorage.cs:line 142
    at Orleans.Core.StateStorageBridge`1.ReadStateAsync() in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 72
    --- End of inner exception stack trace ---
    at Orleans.Core.StateStorageBridge`1.OnError(Exception exception, ErrorCode id, String operation) in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 168
    at Orleans.Core.StateStorageBridge`1.ReadStateAsync() in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 78
    at Orleans.LifecycleSubject.OnStart(CancellationToken cancellationToken) in /_/src/Orleans.Core/Lifecycle/LifecycleSubject.cs:line 118
```

Its also worth noting I have seen other errors from the same error scenario when trying to triage this in the failing service internally today, for example:

```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Orleans.Persistence.RedisGrainStorage.ReadStateAsync[T](String grainType, GrainId grainId, IGrainState`1 grainState) in /_/src/Redis/Orleans.Persistence.Redis/Storage/RedisGrainStorage.cs:line 142
   at Orleans.Core.StateStorageBridge`1.ReadStateAsync() in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 72
   at Orleans.Core.StateStorageBridge`1.OnError(Exception exception, ErrorCode id, String operation) in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 168
   at Orleans.Core.StateStorageBridge`1.ReadStateAsync() in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 78
   at Orleans.LifecycleSubject.OnStart(CancellationToken cancellationToken) in /_/src/Orleans.Core/Lifecycle/LifecycleSubject.cs:line 118
   at Orleans.Internal.OrleansTaskExtentions.MakeCancellable(Task task, CancellationToken cancellationToken) in /_/src/Orleans.Core/Async/TaskExtensions.cs:line 188
   at Orleans.Internal.OrleansTaskExtentions.WithCancellation(Task taskToComplete, String message, CancellationToken cancellationToken) in /_/src/Orleans.Core/Async/TaskExtensions.cs:line 145
   at Orleans.Runtime.ActivationData.<ActivateAsync>g__CallActivateAsync|139_0(Dictionary`2 requestContextData, CancellationToken cancellationToken) in /_/src/Orleans.Runtime/Catalog/ActivationData.cs:line 1400
--- End of stack trace from previous location ---
```

This exception seemed to be thrown by the codec of the type referenced in that external assembly when deserializing that field of the state model. It did not throw this error when using DynamoDB persistence with the otherwise same code path. I wasn't able to reproduce that in the example project.

Even more concerning; the service I was triaging this on internally today threw no exception at all, and logged no errors, when failing to deserialize the persisted state. Grains were just activated with an empty grain state, and previously stored data was lost the next time the grain wrote its state back to Redis.

**Comment by tanordheim** [comment]
I'm not sure it has any relation but maybe still worth pointing out; I reported #8310 a while back with some issues with serialized data no longer being readable after an Orleans minor version upgrade (7.0 -> 7.1). That also failed silently, just returning an empty object when deserialization failed instead of throwing an exception - which made it really tricky to figure out what was going on in the affected services. Just throwing it out there in case it gives you some ideas of what the issue might be 🙂

**Comment by bangfalse** [comment]
It looks like the fix might already be in, it just hasn't made a release yet? https://github.com/dotnet/orleans/pull/8538

**Comment by tanordheim** [comment]
Closing this, as #8538 solved this
