### ISSUE TITLE
Question: Drai

### ISSUE THREAD

**Issue by erikljung** [dotnet/orleans#8658]

**Comment by erikljung** [comment]
Found a solution to increase the time in OnDeactivateAsync:
```
siloBuilder.Configure<GrainCollectionOptions>( x =>
	x.DeactivationTimeout = TimeSpan.FromMinutes( 5 ) );

siloBuilder.Configure<HostOptions>( x =>
	x.ShutdownTimeout = TimeSpan.FromMinutes( 5 ) );
```

This does however not answer all my questsions.

**Comment by erikljung** [comment]
After some testing I found some issues that I would like to get explained. The testing setup is quite simple. I'm using ADO net clustering through Postgres. I've got 1 database and 1 silo running, I start a long running task on a grain A which spawns in silo 1. I start another silo (2) and making a request trying to retrieve data from grain A, this will timeout since it's occupied processing the long running task, so far so good. I now gracefully stop silo 1, the long running task will proceed to do what it's doing on silo 1. I now try to access grain A again which will succeed, grain A will now spawn on silo 2 even though it's still processing the long running task on silo 1. The long running task in grain A succeeds, _OnDeactivateAsync_  is triggered and silo 1 is shut down.

The main issue with this result is that I at some point have 2 grains with the same identity active, one in silo 1 executing a long running task which might update the state, and one in silo 2 (during silo 1 shutdown) with a possible stale state. I even observed receiving the _OnDeactivateAsync_ invocation in silo 1 twice. First during the ongoing task processing (interleaving) were it seemed like grain state that was set in the same method which started the long running task was lost, even though this occurred seconds later. And a second time when the task was finished.

I wrote an assumption on how I thought this would work, hopefully someone can explain why the assumption doesn't correlate with my observed results: 
Once a silo received a stop signal it won't activate new grains or process new requests. Pending requests will be rerouted to 
 other silos. _OnDeactivateAsync_ won't be initiated before the grain finishes its current work (because interleaving 
semantics should be respected). Until the _OnDeactivateAsync_ have been invoked on a grain it shouldn't be possible for that unique grain to be activated on another silo. By increasing the host shutdown timeout there should be leeway for finishing long running processes. Other dependent bits (grains, streams etc) of such a process may have been deactivated on an old silo, these will be reactivated and requests forwarded to the new silos.

**Comment by benjaminpetit** [comment]
What you are hitting here is a limitation of the built-in directory system: once a silo is shutting down, all of his activations are considered dead (I simplified a bit, it's not totally true but there is a time window where it does happen). So if you have an activation that is running for a very long time and is delaying the deactivation process, then Orleans might create a duplicate activation if a new request comes.

It's a trade-off, between availability and consistency.

To get back at your first post, what you are proposing is possible using a custom placement strategy (that would be aware of the deployment) to stop placing new activations on a silo that will be shut down.  You could then use https://github.com/dotnet/orleans/issues/7692 to migrate grains to another silo.

**Comment by christallire** [comment]
Please don't do rolling deployment with Orleans. I did it with Orleans with k8s. The cluster became unavailable due to all the internal messaging especially when you have lots of (I had 20+ "microservice" silo) silos and two or more replicas each with a heterogeneous silo.

**Comment by benjaminpetit** [comment]
@christallire we do test rolling scenarios, and we do manage 0 errors during our tests. But it really depends on the app.

So yes, you can do rolling update. But you need to be careful and make sure that your silos are shutting down gracefully.

**Comment by erikljung** [comment]
Thanks @benjaminpetit for the clarification, it helps a lot. It sounds to me that the relying on the shutdown, even if it's graceful, is too risky. When I read "once a silo is shutting down, all of his activations are considered dead" it seems impossible to guarantee a smooth ride even when a grain takes a second or two to finish its work. However, as long as I know the limitations. 

From what I understand it would be possible with versioned grain interfaces to force new activations to a newly deployed cluster? In that case one solution could be to just run Silo A and B alongside until all grains are naturally moved, it would however take quite a while I guess. Would that be a valid solution?

I will have a look at the placement strategy next week, and hopefully understand a bit more about how this works. Do you know if there is any material or implementations to guide me, besides the official documentation?

**Comment by benjaminpetit** [comment]
When I say "once a silo is shutting down, all of his activations are considered dead", it's really an over-simplification. It's just that there is a small window of time where you _could_ have two concurrent activations at the same time. That's why we strongly recommend to not write to storage on `OnDeactivateAsync`: it will slow down considerably the shutting down phase, and if you have 1000's of activation on the silo, it will make a lot of storage calls...

> From what I understand it would be possible with versioned grain interfaces to force new activations to a newly deployed silo? In that case one solution could be to just run Silo A and B alongside until all grains have naturally moved, it would however take quite a while I guess. Would that be a valid solution? One issue would be hot grains which never gets deactivated, I guess thats were dehydration comes in to place.

Yes it's possible: if the client do a request targetting a Vnext version of the grain, the Vprev activation will me deactivated, and a new one will be created on the newer silo. That way there is no issue with "hot grains" never beeing deactivated.

> I've also read that there is a redis-backed grain directory that should be more robust, would that help in this case?
The redis directory might not help you in this case.

> I will have a look at the placement strategy next week, and hopefully understand a bit more about how this works. Do you know if there is any material or implementations to guide me, besides the official documentation?

Not really, but that would be a welcome addition :)

**Comment by erikljung** [comment]
> When I say "once a silo is shutting down, all of his activations are considered dead", it's really an over-simplification. It's just that there is a small window of time where you _could_ have two concurrent activations at the same time. That's why we strongly recommend to not write to storage on `OnDeactivateAsync`: it will slow down considerably the shutting down phase, and if you have 1000's of activation on the silo, it will make a lot of storage calls...
> 
To be as clear as I can. I'm not actually writing anything to state **on** `OnDeactivateAsync`, the writing is done in the long running task which happens to still be active when the grain is deactivating. The call to `OnDeactivateAsync` seems (for the most time) to arrive after that task has finished. So what I initially  assumed was that the grain activation is not considered dead until the `OnDeactivateAsync` has finished.

> Yes it's possible: if the client do a request targetting a Vnext version of the grain, the Vprev activation will me deactivated, and a new one will be created on the newer silo. That way there is no issue with "hot grains" never beeing deactivated.
> 
Alright, that's good news!

> Not really, but that would be a welcome addition :)
I will try to update this issue with my solution (if any), hopefully it can help someone.

**Comment by erikljung** [comment]
I made some new tests with grain interface versioning.

The grain versioning options I run was:
```
DefaultCompatibilityStrategy = "BackwardCompatible"
DefaultVersionSelectorStrategy = "LatestVersion"
```

Since I own both the clients and silos, I will refer to them as App.

1. _Silo A_  starts processing long running task on _Grain A_
2. Makes 10 simultaneous requests with V2 client towards _Grain A_
3. Requests needs to wait because _Grain A_ is still processing
4. _Grain A_ finishes the long running task and gets deactivated
5. _Silo B_ retrieves the 10 requests on a new activation of _Grain A_
6. No errors observed

So this seems like a good start, having no silo shutdown deactivations in the mix. Does this look like a good solution in all cases (which I cannot foresee yet, need to do more tests). One thing I observed is that versioned grains which is implicit stream subscriptions won't switch silo but rather keep receiving messages on the old silo. Is there any  differences on how implicit streams and regular grains are handled here?

**Comment by erikljung** [comment]
Nothing lasts forever.. Attempted the same test with a bit more fuzz in the cluster and got the following errors which seems to be related to streams (I'm running in memory stream). I'm not sure how to interpret these or what I should do to fix them. The implicit stream grain interface is also versioned.

_Silo A_
```
09:52:24 [WRN] Orleans.Grain - Failed to register grain [Activation: S172.28.0.3:11111:56541057/pubsubrendezvous/DefaultStreamProvider/Domain.Grains.Models.Diagnostics.Auditing.ChangeEvent/84d05f9ceea653d39d479cf76dfe6773@10473e577e2a4fa4a4257d95a012198c#Placement=RandomPlacement State=Invalid] in grain directory {"EventId":{"Id":100064},"MerchantId":null,"TraceId":""} 
09:52:24 [WRN] Orleans.Messaging - Failed to forward message Request [S172.28.0.5:11111:56541085 sys.svc.stream.agent/172.28.0.5:11111@56541085+DefaultStreamProvider_5_defaultstreamprovider-6-0xC0000006]->[S172.28.0.3:11111:56541057 pubsubrendezvous/DefaultStreamProvider/Domain.Grains.Models.Diagnostics.Auditing.ChangeEvent/84d05f9ceea653d39d479cf76dfe6773] Orleans.Streams.IPubSubRendezvousGrainOrleans.Streams.IPubSubRendezvousGrain.RegisterProducer(DefaultStreamProvider/Domain.Grains.Models.Diagnostics.Auditing.ChangeEvent/84d05f9ceea653d39d479cf76dfe6773, sys.svc.stream.agent/172.28.0.5:11111@56541085+DefaultStreamProvider_5_defaultstreamprovider-6-0xC0000006) #4371[ForwardCount=2] from [GrainAddress GrainId pubsubrendezvous/DefaultStreamProvider/Domain.Grains.Models.Diagnostics.Auditing.ChangeEvent/84d05f9ceea653d39d479cf76dfe6773, ActivationId: @10473e577e2a4fa4a4257d95a012198c, SiloAddress: S172.28.0.3:11111:56541057] to [GrainAddress GrainId pubsubrendezvous/DefaultStreamProvider/Domain.Grains.Models.Diagnostics.Auditing.ChangeEvent/84d05f9ceea653d39d479cf76dfe6773, ActivationId: @3d73d54a4e5643edbcfdeca58458ab5a, SiloAddress: S172.28.0.3:11111:56541057] after Failed to register activation in grain directory.. Attempt 2 {"EventId":{"Id":101032,"Name":"Orleans.Messaging.Dispatcher.ForwardingFailed"},"MerchantId":null,"TraceId":""} 

```

_Silo B_
```
09:52:24 [ERR] Orleans.Streams.DefaultStreamProvider - RegisterAsStreamProducer failed {"EventId":{"Id":103317},"MerchantId":null,"TraceId":""} Orleans.Runtime.OrleansMessageRejectionException: Forwarding failed: tried to forward message Request [S172.28.0.5:11111:56541085 sys.svc.stream.agent/172.28.0.5:11111@56541085+DefaultStreamProvider_5_defaultstreamprovider-6-0xC0000006]->[S172.28.0.3:11111:56541057 pubsubrendezvous/DefaultStreamProvider/Domain.Grains.Models.Diagnostics.Auditing.ChangeEvent/84d05f9ceea653d39d479cf76dfe6773] Orleans.Streams.IPubSubRendezvousGrainOrleans.Streams.IPubSubRendezvousGrain.RegisterProducer(DefaultStreamProvider/Domain.Grains.Models.Diagnostics.Auditing.ChangeEvent/84d05f9ceea653d39d479cf76dfe6773, sys.svc.stream.agent/172.28.0.5:11111@56541085+DefaultStreamProvider_5_defaultstreamprovider-6-0xC0000006) #4371[ForwardCount=2] for 2 times after "Failed to register activation in grain directory." to invalid activation. Rejecting now. 
   at Orleans.Serialization.Invocation.ResponseCompletionSource`1.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 239
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Orleans.Streams.StreamPubSubImpl.RegisterProducer(QualifiedStreamId streamId, GrainId streamProducer) in /_/src/Orleans.Streaming/PubSub/StreamPubSubImpl.cs:line 33
   at Orleans.Streams.PersistentStreamPullingAgent.PubsubRegisterProducer(IStreamPubSub pubSub, QualifiedStreamId streamId, GrainId meAsStreamProducer, ILogger logger) in /_/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs:line 819
```

**Comment by erikljung** [comment]
I took a guess that the grain directory (in some way) was the root to this issue, so I changed to the Redis directory and these issues disappeared.  Can someone confirm that this was likeley to happen and that the Redis solution is a good choice?

For reference.
```
siloBuilder.UseRedisGrainDirectoryAsDefault( x =>
	x.ConfigurationOptions = new ConfigurationOptions
		{
			EndPoints = { new DnsEndPoint( RedisHost, RedisPort ) }
		} );
```

**Comment by benjaminpetit** [comment]
> One thing I observed is that versioned grains which is implicit stream subscriptions won't switch silo but rather keep receiving messages on the old silo. Is there any differences on how implicit streams and regular grains are handled here?

The silo that is responsible for the pulling agent for this stream will dictate the min version to use for the request. So, if the silo has a reference to the Vprev interface, and a Vprev activation exists, it will be handled by the existing activation. If the silo hosting the pulling agent is referencing Vnext, then it will be forwarded to a new Vnext activation.

> These errors just seem to get logged for over an hour now. What is it that I'm seeing here exactly?

It seems the entry in the directory is poisoned... we did some fixes related to that in the last versions, which version are you running currently?

**Comment by erikljung** [comment]
> The silo that is responsible for the pulling agent for this stream will dictate the min version to use for the request. So, if the silo has a reference to the Vprev interface, and a Vprev activation exists, it will be handled by the existing activation. If the silo hosting the pulling agent is referencing Vnext, then it will be forwarded to a new Vnext activation.

In my current setup (still trying to determine if it's a good setup), Silo A (un deploy) will be V1 and Silo B (deploy) will be V2. If I understand you right if a pulling agent is started and has an activation on Silo A, it will remain there. Is there any way of force a move to Silo B here?

> It seems the entry in the directory is poisoned... we did some fixes related to that in the last versions, which version are you running currently?
I'm running 7.2.2. As mentioned above, I don't seem to get these issues with the Redis directory, so I guess that would be an indicator that something is still not working 100%.
