### ISSUE TITLE
TestCluster has problems registering other Serializers

### ISSUE THREAD

**Issue by itsChekki** [dotnet/orleans#8665]
Hi, I am currently migrating a project to Orleans 7 and I have a problem with the TestCluster and NewtonsoftJson/SystemJson serializer. Some of the grains have an external Result class from the nuget package `CSharpFunctionalExtensions` as return type which needs an external Serializer. 

A simple grain which causes the problem:

```csharp
public class HelloWorldGrain : Grain, IHelloWorldGrain
{
    public Task<Result<string>> Hello()
    {
        return Task.FromResult(Result.Success("Hello World"));
    }
}
```

The silo setup looks like this: 

```csharp
IHostBuilder builder = Host.CreateDefaultBuilder(args)
    .UseOrleans(silo =>
    {
        silo.UseLocalhostClustering()
            .ConfigureLogging(logging => logging.AddConsole());

        silo.Services
            .AddAdditionalSerializers();
    })
    .UseConsoleLifetime();
```

The serializer for the `CSharpFunctionalExtensions` namespace is added via an extensions method for `IServiceCollection` which looks like this:
```csharp
    public static IServiceCollection AddAdditionalSerializers(this IServiceCollection serviceCollection)
    {
        serviceCollection
            .AddSerializer(serilzerBuilder =>
                serilzerBuilder.AddNewtonsoftJsonSerializer(isSupported: type =>
                    type.Namespace!.StartsWith("CSharpFunctional")));

        return serviceCollection;
    }
```

It works without a problem when you start the application as a console application but it does not work when starting a `TestCluster` for unittesting. When deploying the TestCluster an `Orleans.Runtime.OrleansConfigurationException` is thrown.

## Sample unit test
```csharp
public class UnitTest1
{
    [Fact]
    public async Task Test1()
    {
        var builder = new TestClusterBuilder();
        builder.AddSiloBuilderConfigurator<TestSiloConfigurations>();
        var cluster = builder.Build();
        await cluster.DeployAsync();

        var factory = cluster.GrainFactory;
        var grain = factory.GetGrain<IHelloWorldGrain>("Grain");

        var result = await grain.Hello();
        result.IsSuccess.Should().BeTrue();
    }
}

public class TestSiloConfigurations : ISiloConfigurator
{
    public void Configure(ISiloBuilder siloBuilder)
    {
        siloBuilder.ConfigureServices(services =>
        {
            services.AddAdditionalSerializers();
        });
    }
}
```

Stacktrace: 

```
Found unserializable or uncopyable types which are being referenced in grain interface signatures:
Type: CSharpFunctionalExtensions.Result`1[System.String] has no serializer and was referenced by the following:
	* Orleans.Example.IHelloWorldGrain,Orleans.Example methods: System.Threading.Tasks.Task`1[CSharpFunctionalExtensions.Result`1[System.String]] Test()
Ensure that all types which are used in grain interfaces have serializers available for them.
Applying the [GenerateSerializer] attribute to your type and adding [Id(x)] attributes to serializable properties and fields is the simplest way to accomplish this.
Alternatively, for types which are outside of your control, serializers may have to be manually crafted, potentially using surrogate types.

   at Orleans.SerializerConfigurationValidator.Orleans.IConfigurationValidator.ValidateConfiguration() in /_/src/Orleans.Core/Configuration/Validators/SerializerConfigurationValidator.cs:line 94
   at Orleans.ClusterClient.<.ctor>g__ValidateSystemConfiguration|3_1(IServiceProvider serviceProvider) in /_/src/Orleans.Core/Core/ClusterClient.cs:line 59
   at Orleans.ClusterClient..ctor(IServiceProvider serviceProvider, OutsideRuntimeClient runtimeClient, ILoggerFactory loggerFactory, IOptions`1 clientMessagingOptions) in /_/src/Orleans.Core/Core/ClusterClient.cs:line 33
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Orleans.Configuration.Internal.ServiceCollectionExtensions.<>c__DisplayClass1_0.<AddFromExisting>b__0(IServiceProvider sp) in /_/src/Orleans.Core/Configuration/ServiceCollectionExtensions.cs:line 48
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Orleans.TestingHost.TestCluster.InitializeClientAsync() in /_/src/Orleans.TestingHost/TestCluster.cs:line 597
   at Orleans.TestingHost.TestCluster.InitializeAsync() in /_/src/Orleans.TestingHost/TestCluster.cs:line 625
   at Orleans.TestingHost.TestCluster.DeployAsync() in /_/src/Orleans.TestingHost/TestCluster.cs:line 166
   at Orleans.TestingHost.TestCluster.DeployAsync() in /_/src/Orleans.TestingHost/TestCluster.cs:line 201
   at Orleans.Example.Tests.UnitTest1.Test1() in D:\Projects\Orlenas.Example\Orleans.Example.Tests\UnitTest1.cs:line 16
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
```

**Comment by zeus82** [comment]
What version of Orleans are you running?  We had a similar issue with 7.2.1, but upgrading to 7.2.2 seemed to fix it for us.

**Comment by ReubenBond** [comment]
In the example code, the issue is that the custom serializer is added to the silos but not the client. You need to add a configurator for your client, similar to the one you have for your silo.

I discerned this based on this line in the stack trace:

```csharp
   at Orleans.TestingHost.TestCluster.InitializeClientAsync() in /_/src/Orleans.TestingHost/TestCluster.cs:line 597
```
