### ISSUE TITLE
Silo has activated grains but these are not processing any messages

### ISSUE THREAD

**Issue by tiasmt** [dotnet/orleans#8667]
We are trying to migrate to Orleans 7 from 3.x. We are using kubernetes while using consul for clustering on a Linux container.
When performing a rolling deploy we are noticing that silos / pods are being deployed successfully but the last created pods are not processing any messages / requests (even though there are grain activations). 

Just a side note, when killing / restarting a random pod, the newly created pod tries to join the cluster but we are having the same result (the pod is not processing any messages even though there are activations). 

Any idea what may be happening (this is working correctly on 3.x)?

![image](https://github.com/dotnet/orleans/assets/20759400/7da1b4ef-416f-4238-b25d-54f84cecb450)

![image](https://github.com/dotnet/orleans/assets/20759400/2fc571fd-b01d-4691-ac07-36e7da580ab4)

**Comment by ReubenBond** [comment]
Where are the requests for this system originating from? It's interesting that the grains are being activated at all if there are no requests being sent their way, since grains are only activated by requests. Do you have logs from those silos and other silos which would be making requests? Do you have custom placement?

**Comment by ReubenBond** [comment]
Does this repro on 7.2.1? Do you have a custom directory?

**Comment by tiasmt** [comment]
Hi Reuben, 

We are not using custom placement / custom directory, the requests are originating from a GrainService. What we are finding interesting is that even the ManagementGrain is showing the same issue:

![image](https://github.com/dotnet/orleans/assets/20759400/ad912aae-0a93-45f3-8d63-7f48ebe2911a)

In terms of errors this is the one that seems most relevant:
Error processing cluster membership updates

```
exceptions.Message: Argument must have a previous version to the current instance. Expected <= -9223372036854775808, encountered 12 (Parameter 'previous')

exception.StackTraceString: at Orleans.Runtime.ClusterMembershipSnapshot.CreateUpdate(ClusterMembershipSnapshot previous) in /_/src/Orleans.Runtime/MembershipService/ClusterMembershipSnapshot.cs:line 76
   at Orleans.Runtime.ActivationMigrationManager.ProcessMembershipUpdates() in /_/src/Orleans.Runtime/Catalog/ActivationMigrationManager.cs:line 164
```

**Comment by ReubenBond** [comment]
Oh, are you attempting to perform a rolling upgrade from 3.x to 7.x? That is not supported - the two versions are not wire compatible

**Comment by tiasmt** [comment]
No it is not a rolling upgrade in that sense - we have cleaned any old states / data

**Comment by tiasmt** [comment]
I removed all silos and re deployed (basically ensuring that it is completely clean), the deployment succeeded and there were activations across all silos and they were all partially processing (as they are not succeeding all the time) we are encountering the following error:

```
Forwarding failed: tried to forward message Request [S10.150.26.104:11111:56646254 sys.svc.user.9D282C6F/10.150.26.104:11111@56646254]->[S10.150.36.246:11111:56646254 consumer/odinKafkaConsumer/prod-kronos-user_email_notification-v1/21] Odin.Messaging.Kafka.Consuming.IConsumerGrain.ConsumeAndPublish() #198152[ForwardCount=2] for 2 times after "This grain is active on another host (S10.150.36.246:11111:56646254)." to invalid activation. Rejecting now.
```
seems to be related to this issue: 
https://github.com/dotnet/orleans/issues/8658#issuecomment-1766080837

**Comment by ReubenBond** [comment]
Does that error only occur during rolling deployment, @tiasmt, i.e., is the error resolved after deployment completes?

This is expected, to a degree, while the grain directory is in flux (i.e, during cluster membership changes, such as a rolling deployment). You can use an external directory (like Redis) to avoid this kind of issue.

@benjaminpetit we should consider further mitigations for these conditions until we can rectify it entirely (eg using a storage backed directory), such as potentially inserting a delay, waiting for directory/membership stability, or increasing the allowed number of hops. Currently, it's 2, configured via `SiloMessagingOptions.MaxForwardCount`. You could try increasing that to 4 or 5 to alleviate the majority of these issues, @tiasmt.

**Comment by erikljung** [comment]
> Does that error only occur during rolling deployment, @tiasmt, i.e., is the error resolved after deployment completes?

I observed this during a rolling deploy with `DefaultVersionSelectorStrategy = "LatestVersion"`. The two errors (https://github.com/dotnet/orleans/issues/8658#issuecomment-1766080837) seemed to persist for at least one hour (before I shut it down). After changing to the Redis grain directory I haven't been able to reproduce this state, but I have some further testing to do before I would say it's 100% solid.

**Comment by tiasmt** [comment]
> > Does that error only occur during rolling deployment, @tiasmt, i.e., is the error resolved after deployment completes?
> 
> I observed this during a rolling deploy with `DefaultVersionSelectorStrategy = "LatestVersion"`. The two errors ([#8658 (comment)](https://github.com/dotnet/orleans/issues/8658#issuecomment-1766080837)) seemed to persist for at least one hour (before I shut it down). After changing to the Redis grain directory I haven't been able to reproduce this state, but I have some further testing to do before I would say it's 100% solid.

I am observing the same thing on my end (the error persisted for around 3 hours with the latest deployment). 

I will try and change the `SiloMessagingOptions.MaxForwardCount` to see if it has any effect

**Comment by ReubenBond** [comment]
Do you have a custom serializer?

**Comment by tiasmt** [comment]
Yes, we are using a custom serializer (but this is only for specific types as per https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/serialization-configuration?pivots=orleans-7-0). 

Could this be impacting the membership in some way? I will try and remove the custom serializer later today (where possible) and see if it fixes the issue

**Comment by ReubenBond** [comment]
Do you still have the same exception message as [above](https://github.com/dotnet/orleans/issues/8667#issuecomment-1768328260)? i.e:

```
Error processing cluster membership updates
exceptions.Message: Argument must have a previous version to the current instance. Expected <= -9223372036854775808, encountered 12 (Parameter 'previous')

exception.StackTraceString: at Orleans.Runtime.ClusterMembershipSnapshot.CreateUpdate(ClusterMembershipSnapshot previous) in /_/src/Orleans.Runtime/MembershipService/ClusterMembershipSnapshot.cs:line 76
   at Orleans.Runtime.ActivationMigrationManager.ProcessMembershipUpdates() in /_/src/Orleans.Runtime/Catalog/ActivationMigrationManager.cs:line 164
```

If so, when you removed the JSON serializer, did you perform a clean deployment?

**Comment by tiasmt** [comment]
Hi, the error is not present anymore but the issue is still occurring. 
What we have noticed is that when the silos are up and running within a couple of seconds, everything seems to work fine but when there is a delay for some silos to initialize these do not process any messages.

We  also managed to replicate the issue by performing a deployment and killing some random silos (when restarting these are not processing any messages).

This was replicated on a dummy application (having bare minimal code from our side) and we were observing the problem on the management grain.

**Comment by ReubenBond** [comment]
Are you able to share logs? If you prefer not to upload them here, we could share them via email instead

**Comment by tiasmt** [comment]
Trying to gather logs from my end and will share them once available

**Comment by tanordheim** [comment]
We are seeing "This grain is active on another host" a lot too, I havent managed to dig into it yet but we are using the Redis grain directory and what I noticed at first glance was:

- Grain was active in some silo that crashed
- New silo came up, tried to activate the grain, got a RedisTimeoutException

After this no grain calls to this grain succeeds, always the same error as above. Max forward count is set to 5.

Does this feel like the same issue at all @ReubenBond? If so I can collect some logs and the current registration in Redis and add here too for some additional context.

**Comment by ReubenBond** [comment]
@tanordheim this looks like a different issue to me - the Redis timeout is the likely cause. It may be worth opening a new issue with details

**Comment by tiasmt** [comment]
> Are you able to share logs? If you prefer not to upload them here, we could share them via email instead

I've given you access to a repository with the logs.

The logs are part of the dummy application I mentioned previously (without the JSON serializer).
I started 6 silos and these were functioning as expected, I then killed 3 random silos when these restarted they never processed any messages. 

Let me know if I can provide any more details / information

**Comment by ReubenBond** [comment]
It looks like your cluster is still being affected by this issue: https://github.com/dotnet/orleans/issues/8667, since cluster membership is failing to update. Can you show me how you're configuring your system?

**Comment by tiasmt** [comment]
Updated the logs to show the `Exception`

Configuration is as follows:
 
``` csharp
.UseOrleans((ctx, builder) =>
			{
				var siloOptions = new SiloConfigBuilder()
					.FromConfig(ctx.Configuration);
				microSvcBuilder.ConfigureOrleansDelegate?.Invoke(context, siloOptions, builder);

				if (siloOptions.SiloPort == 0)
					siloOptions.SiloPort = hostBuilder.GetAvailablePort(11111, 12000);
				
				builder
					.Configure<ClusterOptions>(
						opts =>
						{
							opts.ClusterId = context.AppInfo.ClusterId;
							opts.ServiceId = context.AppInfo.ServiceId;
						}
					)
					.AddMemoryGrainStorage(OrleansStoreNames.GrainMemory)
					.AddIncomingGrainCallFilter<UnknownErrorIncomingCallFilter>()
					.AddOutgoingGrainCallFilter<UnknownErrorOutgoingCallFilter>()
					.AddIncomingGrainCallFilter<LoggingIncomingCallFilter>()
					.AddOutgoingGrainCallFilter<LoggingOutgoingCallFilter>()
					;

				builder.Configure<ClusterMembershipOptions>(
					options =>
					{
						options.ExtendProbeTimeoutDuringDegradation = siloOptions.ClusterConfig.ExtendProbeTimeout;
						options.EnableIndirectProbes = siloOptions.ClusterConfig.EnableIndirectProbes;
						options.LocalHealthDegradationMonitoringPeriod =
							TimeSpan.FromSeconds(siloOptions.ClusterConfig.LocalHealthDegradationMonitoringPeriod);
					}
				);

				if (siloOptions.OrleansDashboardConfig.IsEnabled)
					builder.UseDashboard(
						options =>
						{
							options.Username = siloOptions.OrleansDashboardConfig.Username;
							options.Password = siloOptions.OrleansDashboardConfig.Password;
							options.Port = siloOptions.OrleansDashboardConfig.Port;
							options.CounterUpdateIntervalMs = siloOptions.OrleansDashboardConfig.CounterUpdateIntervalMs;
						}
					);
				
				// Consul
				builder
					.ConfigureEndpoints(
						siloOptions.SiloPort,
						siloOptions.GatewayPort,
						listenOnAnyHostAddress: true
					)
					.UseConsulSiloClustering(opts =>
					{
						opts.KvRootFolder = siloOptions.ConsulConfig.KvRootFolder;
						var address = new Uri(siloOptions.ConsulConfig.Uri);
						opts.ConfigureConsulClient(address);
					});
```

**Comment by ReubenBond** [comment]
@tiasmt am I understanding correctly that this issue does not occur when using the AdoNet clustering provider, only when using both Consul & JSON.NET?

**Comment by tiasmt** [comment]
> @tiasmt am I understanding correctly that this issue does not occur when using the AdoNet clustering provider, only when using both Consul & JSON.NET?

Yes, the `Error processing cluster membership updates` only occurs when using Consul and the JSON serializer (I was using System.Text.Json). 

When using `AdoNet` this issue does not occur.

**Comment by zeus82** [comment]
Orleans 7.2.2 has been running for about 24 hours for us without any issues, but now we are seeing what @tanordheim was seeing, but were not using redis.  We are running Kubernetes and using the Kubernetes Clustering lib
```
Orleans.Runtime.OrleansMessageRejectionException: Forwarding failed: tried to forward message Request [S10.12.58.12:11111:58467741 sys.client/hosted-10.12.58.12:11111@58467741]->[S10.12.58.9:11111:58466489 deviceconnect/212C6D43] TestApp.Orleans.Interface.IDeviceConnectGrain.UpdateConnectAsync(11/09/2023 23:39:12) #33404136[ForwardCount=2] for 2 times after "This grain is active on another host (S10.12.58.9:11111:58466489)." to invalid activation. Rejecting now. 
    at Orleans.Serialization.Invocation.ResponseCompletionSource.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 90
    at Orleans.Runtime.OutgoingCallInvoker`1.Invoke() in /_/src/Orleans.Core/Runtime/OutgoingCallInvoker.cs:line 129
    at Orleans.Runtime.ActivityPropagationGrainCallFilter.Process(IGrainCallContext context, Activity activity) in /_/src/Orleans.Core/Diagnostics/ActivityPropagationGrainCallFilter.cs:line 75
    at Orleans.Runtime.OutgoingCallInvoker`1.Invoke() in /_/src/Orleans.Core/Runtime/OutgoingCallInvoker.cs:line 129
    at Orleans.Runtime.GrainReferenceRuntime.InvokeMethodWithFiltersAsync[TResult](GrainReference reference, IInvokable request, InvokeMethodOptions options) in /_/src/Orleans.Core/Runtime/GrainReferenceRuntime.cs:line 92
    at TestApp.OrleansDeviceController.UpdateLastConnectAsync(IEnumerable`1 request, CancellationToken cancellationToken) 
```

**Comment by shykln** [comment]
Hi @ReubenBond ,

I recently upgrade my orleans project from 3.6 to 8.2. 
I'm also facing the issue that when my ci/cd tool did the rolling upgrade of code, in a big change that several grains in the new silos stop processing messages. I tried to go with both memory grain directory (default) and redis grain directory, the issue persists. 

My question is that will #9103 and `DistributedGrainDirectory hosting` fix this issue?

Thank you!

**Comment by shykln** [comment]
> [@shykln](https://github.com/shykln) it's difficult to say without knowing more. Are you also using Consul for clustering?

I use ado.net clustring with a sql server
