### ISSUE TITLE
grain duplicate activation in same address.and forward message is not work.

### ISSUE THREAD

**Issue by PengYuee** [dotnet/orleans#8688]
![1698197254173](https://github.com/dotnet/orleans/assets/43264125/4a395b9a-a30b-4e9e-a5a5-8dce28213226)
![image](https://github.com/dotnet/orleans/assets/43264125/37192660-933a-4afa-a60e-9abc1498d0a6)

**Comment by ReubenBond** [comment]
Hi @PengYuee, thank you for opening this issue. This ought to be fixed in [v7.2.3](https://github.com/dotnet/orleans/releases/tag/v7.2.3). Please update to that version and let us know if you still encounter this problem by opening a new issue.

**Comment by PengYuee** [comment]
Hi @ReubenBond,thank you for fixed this problem,I will update the version immediately。

**Comment by ReubenBond** [comment]
Thank you, please tell us about your experience.

**Comment by PengYuee** [comment]
umm，it happend in production environment,and i discovered this information by checking the logs.i suspect it's caused by  network problem.

**Comment by ReubenBond** [comment]
Does it resolve itself quickly or does it seem to get stuck in a bad state? Some forwarding from activations which failed to register is expected based on calling patterns

**Comment by PengYuee** [comment]
it can not resolve itself,it will fall into a loop like active->forward->active.At least it was like this all day, and then I chose to restart 
the silo. about calling patterns,i don’t follow :)

**Comment by ReubenBond** [comment]
Could you share some logs?

**Comment by PengYuee** [comment]
This is the log after the request was received,what other logs do you want?
**this is debug logs**
```
#2023-10-24 05:07:50 Created ActivationTaskScheduler-65403:Queued=0 with GrainContext=[Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@38949cd99be34ef09e36be555fc83ab8#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Create]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Tried to create a duplicate activation [GrainAddress GrainId friend/7067977412356828226, ActivationId: @38949cd99be34ef09e36be555fc83ab8, SiloAddress: S10.255.8.32:9001:56873595], but we'll use S10.255.8.32:9001:56873595 instead. GrainInstance Type is GameServerPlus.GrainImpl.FriendGrain. Primary Directory partition for this grain is S10.255.3.43:9001:56873583. Full activation address is [GrainAddress GrainId friend/7067977412356828226, ActivationId: @38949cd99be34ef09e36be555fc83ab8, SiloAddress: S10.255.8.32:9001:56873595, MembershipVersion: -9223372036854775808]. We have 1 messages to forward.
---------------------------------------------------------------------
#2023-10-24 05:07:50 Rerouting 1 messages from invalid grain activation [Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@38949cd99be34ef09e36be555fc83ab8#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Invalid]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Forwarding 1 requests destined for address [GrainAddress GrainId friend/7067977412356828226, ActivationId: @38949cd99be34ef09e36be555fc83ab8, SiloAddress: S10.255.8.32:9001:56873595] to address S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.
---------------------------------------------------------------------
#2023-10-24 05:07:50 Trying to forward Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.GetFriendList() #11243698 from [GrainAddress GrainId friend/7067977412356828226, ActivationId: @38949cd99be34ef09e36be555fc83ab8, SiloAddress: S10.255.8.32:9001:56873595] to S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.. Attempt 0
---------------------------------------------------------------------
#2023-10-24 05:07:50 Resend Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.GetFriendList() #11243698[ForwardCount=1]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Created ActivationTaskScheduler-65404:Queued=0 with GrainContext=[Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@93f2beecfebb4c1bb480828cf9cd1df3#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Create]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Tried to create a duplicate activation [GrainAddress GrainId friend/7067977412356828226, ActivationId: @93f2beecfebb4c1bb480828cf9cd1df3, SiloAddress: S10.255.8.32:9001:56873595], but we'll use S10.255.8.32:9001:56873595 instead. GrainInstance Type is GameServerPlus.GrainImpl.FriendGrain. Primary Directory partition for this grain is S10.255.3.43:9001:56873583. Full activation address is [GrainAddress GrainId friend/7067977412356828226, ActivationId: @93f2beecfebb4c1bb480828cf9cd1df3, SiloAddress: S10.255.8.32:9001:56873595, MembershipVersion: -9223372036854775808]. We have 1 messages to forward.
---------------------------------------------------------------------
#2023-10-24 05:07:50 Rerouting 1 messages from invalid grain activation [Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@93f2beecfebb4c1bb480828cf9cd1df3#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Invalid]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Forwarding 1 requests destined for address [GrainAddress GrainId friend/7067977412356828226, ActivationId: @93f2beecfebb4c1bb480828cf9cd1df3, SiloAddress: S10.255.8.32:9001:56873595] to address S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.
---------------------------------------------------------------------
#2023-10-24 05:07:50 Trying to forward Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.GetFriendList() #11243698[ForwardCount=1] from [GrainAddress GrainId friend/7067977412356828226, ActivationId: @93f2beecfebb4c1bb480828cf9cd1df3, SiloAddress: S10.255.8.32:9001:56873595] to S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.. Attempt 1
---------------------------------------------------------------------
#2023-10-24 05:07:50 Resend Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.GetFriendList() #11243698[ForwardCount=2]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Created ActivationTaskScheduler-65405:Queued=0 with GrainContext=[Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@1312b2af4218440d977e66bc0e9714bd#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Create]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Tried to create a duplicate activation [GrainAddress GrainId friend/7067977412356828226, ActivationId: @1312b2af4218440d977e66bc0e9714bd, SiloAddress: S10.255.8.32:9001:56873595], but we'll use S10.255.8.32:9001:56873595 instead. GrainInstance Type is GameServerPlus.GrainImpl.FriendGrain. Primary Directory partition for this grain is S10.255.3.43:9001:56873583. Full activation address is [GrainAddress GrainId friend/7067977412356828226, ActivationId: @1312b2af4218440d977e66bc0e9714bd, SiloAddress: S10.255.8.32:9001:56873595, MembershipVersion: -9223372036854775808]. We have 1 messages to forward.
---------------------------------------------------------------------
#2023-10-24 05:07:50 Rerouting 1 messages from invalid grain activation [Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@1312b2af4218440d977e66bc0e9714bd#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Invalid]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Forwarding 1 requests destined for address [GrainAddress GrainId friend/7067977412356828226, ActivationId: @1312b2af4218440d977e66bc0e9714bd, SiloAddress: S10.255.8.32:9001:56873595] to address S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.
---------------------------------------------------------------------
#2023-10-24 05:07:50 Trying to forward Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.GetFriendList() #11243698[ForwardCount=2] from [GrainAddress GrainId friend/7067977412356828226, ActivationId: @1312b2af4218440d977e66bc0e9714bd, SiloAddress: S10.255.8.32:9001:56873595] to S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.. Attempt 2
---------------------------------------------------------------------
#2023-10-24 05:07:50 Rejected message Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.GetFriendList() #11243698[ForwardCount=2] with reason 'Forwarding failed: tried to forward message Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.GetFriendList() #11243698[ForwardCount=2] for 2 times after "Failed to register activation in grain directory." to invalid activation. Rejecting now.' (Transient)
---------------------------------------------------------------------
#2023-10-24 05:07:50 Creating Transient rejection with info 'Forwarding failed: tried to forward message Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.GetFriendList() #11243698[ForwardCount=2] for 2 times after "Failed to register activation in grain directory." to invalid activation. Rejecting now. ' at:
   at Orleans.Runtime.MessageFactory.CreateRejectionResponse(Message request, RejectionTypes type, String info, Exception ex)
   at Orleans.Runtime.Messaging.MessageCenter.RejectMessage(Message message, RejectionTypes rejectionType, Exception exc, String rejectInfo)
   at Orleans.Runtime.Messaging.MessageCenter.TryForwardRequest(Message message, GrainAddress oldAddress, SiloAddress forwardingAddress, String failedOperation, Exception exc)
   at Orleans.Runtime.Messaging.MessageCenter.ProcessRequestsToInvalidActivation(List`1 messages, GrainAddress oldAddress, SiloAddress forwardingAddress, String failedOperation, Exception exc, Boolean rejectMessages)
   at Orleans.Runtime.ActivationData.RerouteAllQueuedMessages()
   at Orleans.Runtime.ActivationData.<RunMessageLoop>g__ProcessRequestsToInvalidActivation|126_2()
   at Orleans.Runtime.ActivationData.<RunMessageLoop>g__ProcessPendingRequests|126_0()
   at Orleans.Runtime.ActivationData.RunMessageLoop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<>c.<Run>b__2_0(Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run(Task ignored, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at Orleans.Runtime.ActivationData.<RunMessageLoop>g__ProcessOperationsAsync|126_4(List`1 operations)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<>c.<Run>b__2_0(Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run(Task ignored, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at Orleans.Runtime.ActivationData.ActivateAsync(Dictionary`2 requestContextData, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<>c.<Run>b__2_0(Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run(Task ignored, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at Orleans.Runtime.ActivationData.RegisterActivationInGrainDirectoryAndValidate()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<>c.<Run>b__2_0(Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run(Task ignored, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at Orleans.Runtime.GrainDirectory.DhtGrainLocator.Register(GrainAddress address, GrainAddress previousAddress)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<>c.<Run>b__2_0(Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run(Task ignored, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.RegisterAsync(GrainAddress address, GrainAddress previousAddress, Int32 hopCount)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.<>c.<Run>b__2_0(Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at Orleans.Runtime.Scheduler.ActivationTaskScheduler.RunTask(Task task)
   at Orleans.Runtime.Scheduler.WorkItemGroup.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

---------------------------------------------------------------------
#2023-10-24 05:07:50 Created ActivationTaskScheduler-65406:Queued=0 with GrainContext=[Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@2daa09f89e33489983832b71cec1eeab#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Create]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Tried to create a duplicate activation [GrainAddress GrainId friend/7067977412356828226, ActivationId: @2daa09f89e33489983832b71cec1eeab, SiloAddress: S10.255.8.32:9001:56873595], but we'll use S10.255.8.32:9001:56873595 instead. GrainInstance Type is GameServerPlus.GrainImpl.FriendGrain. Primary Directory partition for this grain is S10.255.3.43:9001:56873583. Full activation address is [GrainAddress GrainId friend/7067977412356828226, ActivationId: @2daa09f89e33489983832b71cec1eeab, SiloAddress: S10.255.8.32:9001:56873595, MembershipVersion: -9223372036854775808]. We have 1 messages to forward.
---------------------------------------------------------------------
#2023-10-24 05:07:50 Rerouting 1 messages from invalid grain activation [Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@2daa09f89e33489983832b71cec1eeab#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Invalid]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Forwarding 1 requests destined for address [GrainAddress GrainId friend/7067977412356828226, ActivationId: @2daa09f89e33489983832b71cec1eeab, SiloAddress: S10.255.8.32:9001:56873595] to address S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.
---------------------------------------------------------------------
#2023-10-24 05:07:50 Trying to forward Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.FriendCalcReddot() #11243699 from [GrainAddress GrainId friend/7067977412356828226, ActivationId: @2daa09f89e33489983832b71cec1eeab, SiloAddress: S10.255.8.32:9001:56873595] to S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.. Attempt 0
---------------------------------------------------------------------
#2023-10-24 05:07:50 Resend Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.FriendCalcReddot() #11243699[ForwardCount=1]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Created ActivationTaskScheduler-65407:Queued=0 with GrainContext=[Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@d6f4a883a3f4489bac93c74a2b7f1c5f#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Create]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Tried to create a duplicate activation [GrainAddress GrainId friend/7067977412356828226, ActivationId: @d6f4a883a3f4489bac93c74a2b7f1c5f, SiloAddress: S10.255.8.32:9001:56873595], but we'll use S10.255.8.32:9001:56873595 instead. GrainInstance Type is GameServerPlus.GrainImpl.FriendGrain. Primary Directory partition for this grain is S10.255.3.43:9001:56873583. Full activation address is [GrainAddress GrainId friend/7067977412356828226, ActivationId: @d6f4a883a3f4489bac93c74a2b7f1c5f, SiloAddress: S10.255.8.32:9001:56873595, MembershipVersion: -9223372036854775808]. We have 1 messages to forward.
---------------------------------------------------------------------
#2023-10-24 05:07:50 Rerouting 1 messages from invalid grain activation [Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@d6f4a883a3f4489bac93c74a2b7f1c5f#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Invalid]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Forwarding 1 requests destined for address [GrainAddress GrainId friend/7067977412356828226, ActivationId: @d6f4a883a3f4489bac93c74a2b7f1c5f, SiloAddress: S10.255.8.32:9001:56873595] to address S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.
---------------------------------------------------------------------
#2023-10-24 05:07:50 Trying to forward Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.FriendCalcReddot() #11243699[ForwardCount=1] from [GrainAddress GrainId friend/7067977412356828226, ActivationId: @d6f4a883a3f4489bac93c74a2b7f1c5f, SiloAddress: S10.255.8.32:9001:56873595] to S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.. Attempt 1
---------------------------------------------------------------------
#2023-10-24 05:07:50 Resend Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.FriendCalcReddot() #11243699[ForwardCount=2]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Created ActivationTaskScheduler-65408:Queued=0 with GrainContext=[Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@4c32173851064530bbae5e69e2c3c928#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Create]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Tried to create a duplicate activation [GrainAddress GrainId friend/7067977412356828226, ActivationId: @4c32173851064530bbae5e69e2c3c928, SiloAddress: S10.255.8.32:9001:56873595], but we'll use S10.255.8.32:9001:56873595 instead. GrainInstance Type is GameServerPlus.GrainImpl.FriendGrain. Primary Directory partition for this grain is S10.255.3.43:9001:56873583. Full activation address is [GrainAddress GrainId friend/7067977412356828226, ActivationId: @4c32173851064530bbae5e69e2c3c928, SiloAddress: S10.255.8.32:9001:56873595, MembershipVersion: -9223372036854775808]. We have 1 messages to forward.
---------------------------------------------------------------------
#2023-10-24 05:07:50 Rerouting 1 messages from invalid grain activation [Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@4c32173851064530bbae5e69e2c3c928#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Invalid]
---------------------------------------------------------------------
#2023-10-24 05:07:50 Forwarding 1 requests destined for address [GrainAddress GrainId friend/7067977412356828226, ActivationId: @4c32173851064530bbae5e69e2c3c928, SiloAddress: S10.255.8.32:9001:56873595] to address S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.
---------------------------------------------------------------------
#2023-10-24 05:07:50 Trying to forward Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.FriendCalcReddot() #11243699[ForwardCount=2] from [GrainAddress GrainId friend/7067977412356828226, ActivationId: @4c32173851064530bbae5e69e2c3c928, SiloAddress: S10.255.8.32:9001:56873595] to S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.. Attempt 2
---------------------------------------------------------------------
#2023-10-24 05:07:50 Rejected message Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.FriendCalcReddot() #11243699[ForwardCount=2] with reason 'Forwarding failed: tried to forward message Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.FriendCalcReddot() #11243699[ForwardCount=2] for 2 times after "Failed to register activation in grain directory." to invalid activation. Rejecting now.' (Transient)
---------------------------------------------------------------------
#2023-10-24 05:07:50 Creating Transient rejection with info 'Forwarding failed: tried to forward message Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.FriendCalcReddot() #11243699[ForwardCount=2] for 2 times after "Failed to register activation in grain directory." to invalid activation. Rejecting now. ' at:
   at Orleans.Runtime.MessageFactory.CreateRejectionResponse(Message request, RejectionTypes type, String info, Exception ex)
   at Orleans.Runtime.Messaging.MessageCenter.RejectMessage(Message message, RejectionTypes rejectionType, Exception exc, String rejectInfo)
   at Orleans.Runtime.Messaging.MessageCenter.TryForwardRequest(Message message, GrainAddress oldAddress, 
```
**this is warn logs**
```
#2023-10-24 05:07:50 Failed to register grain [Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@38949cd99be34ef09e36be555fc83ab8#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Invalid] in grain directory
---------------------------------------------------------------------
#2023-10-24 05:07:50 Failed to register grain [Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@93f2beecfebb4c1bb480828cf9cd1df3#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Invalid] in grain directory
---------------------------------------------------------------------
#2023-10-24 05:07:50 Failed to register grain [Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@1312b2af4218440d977e66bc0e9714bd#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Invalid] in grain directory
---------------------------------------------------------------------
#2023-10-24 05:07:50 Failed to forward message Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.GetFriendList() #11243698[ForwardCount=2] from [GrainAddress GrainId friend/7067977412356828226, ActivationId: @1312b2af4218440d977e66bc0e9714bd, SiloAddress: S10.255.8.32:9001:56873595] to S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.. Attempt 2
---------------------------------------------------------------------
#2023-10-24 05:07:50 Failed to register grain [Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@2daa09f89e33489983832b71cec1eeab#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Invalid] in grain directory
---------------------------------------------------------------------
#2023-10-24 05:07:50 Failed to register grain [Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@d6f4a883a3f4489bac93c74a2b7f1c5f#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Invalid] in grain directory
---------------------------------------------------------------------
#2023-10-24 05:07:50 Failed to register grain [Activation: S10.255.8.32:9001:56873595/friend/7067977412356828226@4c32173851064530bbae5e69e2c3c928#GrainType=GameServerPlus.GrainImpl.FriendGrain,GameServerPlus.GameServerPlus.GrainImpl Placement=RandomPlacement State=Invalid] in grain directory
---------------------------------------------------------------------
#2023-10-24 05:07:50 Failed to forward message Request [S10.255.88.33:9003:56873595 sys.client/ba1e5db2cc484e17ad21d88d8b865c50]->[S10.255.8.32:9001:56873595 friend/7067977412356828226] GameServerPlus.GrainInterface.IFriend.FriendCalcReddot() #11243699[ForwardCount=2] from [GrainAddress GrainId friend/7067977412356828226, ActivationId: @4c32173851064530bbae5e69e2c3c928, SiloAddress: S10.255.8.32:9001:56873595] to S10.255.8.32:9001:56873595 after Failed to register activation in grain directory.. Attempt 2
```

**Comment by ReubenBond** [comment]
Could you please check again to make sure that you have upgraded all of your silos to v7.2.3? The log lines your seeing seem to indicate you are using a different version. I might be mistaken, but I except you to see a line starting with "The grain directory has an existing entry pointing to a different activation of this grain on this silo"

**Comment by PengYuee** [comment]
Very sorry,these logs are from before the updated version,I thought you wanted to know about the previous experience that caused the problem,after upgraded my silo to v7.2.3,this problem has not yet arisen

**Comment by ReubenBond** [comment]
Ok, that's great. I will close this issue

**Comment by PengYuee** [comment]
Ok，Thank you very much.
