### ISSUE TITLE
Can't start orleans client on Linux server

### ISSUE THREAD

**Issue by FranKieSator** [dotnet/orleans#8695]
I'm trying to deploy my web api to the linux server, web api is used as Orleans client (version 7.1.2), however, whenever I start api, it fails with an exception.
 
I checked that appsettings is set correctly (i tried to e.g. make conn string empty and it correctly says that conn string is missing). I also checked source code of DBConnecitonFactory line 112, unfortunately with no success what and why is null. Any ideas or same experiences?

the full exception:

 Starting Orleans client with runtime version "7.1.2. Commit Hash: 01475f531c27c1c1fa7bc6f20827ffc8a50e5636+01475f531c27c1c1fa7bc6f20827ffc8a50e5636 (Release).", local address 192.168.12.11 and client id sys.client/220e81513647478889f836b9935c18d0
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Clustering.AdoNet.Storage.DbConnectionFactory.CreateConnection(String invariantName, String connectionString) in //src/AdoNet/Shared/Storage/DbConnectionFactory.cs:line 112
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage.ExecuteAsync[TResult](String query, Action1 parameterProvider, Func5 executor, Func`4 selector, CancellationToken cancellationToken, CommandBehavior commandBehavior) in //src/AdoNet/Shared/Storage/RelationalStorage.cs:line 263

**Comment by FranKieSator** [comment]
ok, found the issue. In csproj, I had correctly set runtime to linux-x64 but in our build pipeline, runtime settings was missing (I assume it took probably just linux by default instead of the one from csproj). Because of that, the used libraries were different and the issue was happening - dunno why exactly but setting linux-64 to build pipeline fixed the issue
