### ISSUE TITLE
Cant get grain from IClusterClient: InvalidOperationException: Unable to find an IGrainReferenceActivatorProvider for grain type solar

### ISSUE THREAD

**Issue by Hickori** [dotnet/orleans#8729]
Hi!

I am trying to learn an use Microsoft Orleans, and have never used anything like it. But now I am just trying to setup a simple test grain and silo in my projects to then start adding more to the backend part. But when I try to get a grain from the cluster client I get the exception: 
```Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Unable to find an IGrainReferenceActivatorProvider for grain type solar
         at Orleans.GrainReferences.GrainReferenceActivator.CreateActivator(GrainType grainType, GrainInterfaceType interfaceType) in /_/src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs:line 85
         at Orleans.GrainReferences.GrainReferenceActivator.CreateReference(GrainId grainId, GrainInterfaceType interfaceType) in /_/src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs:line 54
         at Orleans.GrainFactory.GetGrain(Type interfaceType, IdSpan grainKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 217
         at Orleans.GrainFactory.GetGrain[TGrainInterface](Guid primaryKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 44
         at Orleans.ClusterClient.GetGrain[TGrainInterface](Guid primaryKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/ClusterClient.cs:line 95
         at Program.<>c.<<<Main>$>b__0_5>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
Here is my client:

```builder.Host
    .UseOrleansClient(client =>
    {
        client.UseLocalhostClustering();

        client.Configure<ClusterOptions>(options =>
        {
            options.ClusterId = "dev";
            options.ServiceId = "dev";
        });
    })
    .ConfigureLogging(logging => logging.AddConsole());

app.MapGet("/test", async (IServiceProvider sp) =>
{
    var grainFactory = sp.GetRequiredService<IClusterClient>();
    var solarGrain = grainFactory.GetGrain<ISolarGrain>(Guid.NewGuid());
    var a = await solarGrain.GetSolarHistoriesAsync();
});
```
Here is my silo:
```builder.Host.UseOrleans(silo =>
               {
                   silo.UseLocalhostClustering();

                   silo.Configure<ClusterOptions>(options =>
                       {
                           options.ClusterId = "dev";
                           options.ServiceId = "dev";
                       })
                       .ConfigureLogging(logging => logging.AddConsole());

                   silo.ConfigureEndpoints(
                        advertisedIP: IPAddress.Loopback,
                        siloPort: 11111,
                        listenOnAnyHostAddress: true,
                        gatewayPort: 30000
                    );
               });
```

Do you need more information about the grains to be able to figure out what possibly can be the error? :) 

Thank you so much in advance!
Best regards Max

**Comment by Hickori** [comment]
Was only missing some nuget packages! Worked when I added all required nuget packages!
