### ISSUE TITLE
Custom placement strategy from doc does not work any more after upgrading to version 8

### ISSUE THREAD

**Issue by wangjia184** [dotnet/orleans#8830]
* Orleans Version: `8.0.0`
* Dotnet core version: 8
* Example from Orleans(v7) [doc](https://learn.microsoft.com/en-us/dotnet/orleans/grains/grain-placement#sample-custom-placement-strategy)

The following code works well in Orleans v7.
```csharp
        public static void Install(IServiceCollection services)
        {
            services.AddSingletonNamedService<PlacementStrategy, ExplicitPlacementStrategy>(nameof(ExplicitPlacementStrategy));
            services.AddSingletonKeyedService<Type, IPlacementDirector, ExplicitPlacementDirector>(typeof(ExplicitPlacementStrategy));
        }
```

While after upgrading to Orleans v8, `AddSingletonNamedService` & `AddSingletonKeyedService` do not exist any more.  Hence I updated the code to following:
```csharp
        public static void Install(IServiceCollection services)
        {
            services.AddKeyedSingleton<PlacementStrategy, ExplicitPlacementStrategy>(nameof(ExplicitPlacementStrategy));
            services.AddKeyedSingleton<IPlacementDirector, ExplicitPlacementDirector>(nameof(ExplicitPlacementDirector));
        }
```

Unfortunately it stopped working and application raises exception as below. The other codes remain unchanged.
```
      Unable to activate SubscriptionGrain
      System.Collections.Generic.KeyNotFoundException: Could not resolve placement strategy ExplicitPlacementStrategy for grain type subscription
         at Orleans.Runtime.Placement.PlacementStrategyResolver.TryGetNonDefaultPlacementStrategy(GrainType grainType, PlacementStrategy& strategy) in /_/src/Orleans.Runtime/Placement/PlacementStrategyResolver.cs:line 78
         at Orleans.Runtime.Placement.PlacementStrategyResolver.GetPlacementStrategyInternal(GrainType grainType) in /_/src/Orleans.Runtime/Placement/PlacementStrategyResolver.cs:line 88
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Orleans.Runtime.Placement.PlacementService.PlacementWorker.GetOrPlaceActivationAsync(Message firstMessage) in /_/src/Orleans.Runtime/Placement/PlacementService.cs:line 370
         at Orleans.Runtime.Messaging.MessageCenter.<AddressAndSendMessage>g__SendMessageAsync|39_0(Task addressMessageTask, Message m) in /_/src/Orleans.Runtime/Messaging/MessageCenter.cs:line 471
         at Orleans.Serialization.Invocation.ResponseCompletionSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 98
         at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
```

This exception is raised from [this line](https://github.com/dotnet/orleans/blob/v8.0.0/src/Orleans.Runtime/Placement/PlacementStrategyResolver.cs#L78).

**Comment by wangjia184** [comment]
```csharp
public static void Install(IServiceCollection services)
{
    //services.AddSingletonNamedService<PlacementStrategy, ExplicitPlacementStrategy>(nameof(ExplicitPlacementStrategy));
    //services.AddSingletonKeyedService<Type, IPlacementDirector, ExplicitPlacementDirector>(typeof(ExplicitPlacementStrategy));
    services.AddPlacementDirector<ExplicitPlacementStrategy, ExplicitPlacementDirector>();
}
```

Issue is solved by reading source code

**Comment by HermesNew** [comment]
你升级到orleans8之后，是否有个节点内存使用量比别的节点高很多？有没有观察过？

**Comment by wangjia184** [comment]
> After upgrading to orleans8, is there a node with significantly higher memory usage than other nodes? Have you ever observed it?

so far so good.  we are still testing on stage environment and not deploy to production yet.
