### ISSUE TITLE
Orleans 7.0 About Memory stream usage help

### ISSUE THREAD

**Issue by wz172** [dotnet/orleans#8840]
Dear friends, I am using the example in the project to add the built-in memory stream of Orleans7.0 as Grain's message acceptance. In the test, I found that if a message is not sent for more than half an hour and the stream information is sent later, Grain cannot receive the stream information. I use the display mode to subscribe the stream information.What is the reason for this problem, is there any other related configuration when adding the memory stream?

**Comment by wz172** [comment]
Here is catching exception information


Orleans.Streams.QueueCacheMissException: Item not found in cache.  Requested: [EventSequenceToken: SeqNum=638427006424614893, EventIndex=0], Low: [EventSequenceToken: SeqNum=638427006424623717, EventIndex=0], High: [EventSequenceToken: SeqNum=638427006424631869, EventIndex=0]
   at Orleans.Providers.Streams.Common.PooledQueueCache.SetCursor(Cursor cursor, StreamSequenceToken sequenceToken) in /_/src/Orleans.Streaming/Common/PooledCache/PooledQueueCache.cs:line 215
   at Orleans.Providers.Streams.Common.PooledQueueCache.TryGetNextMessage(Object cursorObj, IBatchContainer& message) in /_/src/Orleans.Streaming/Common/PooledCache/PooledQueueCache.cs:line 283
   at Orleans.Streams.PersistentStreamPullingAgent.RunConsumerCursor(StreamConsumerData consumerData)

**Comment by tchelidze** [comment]
experiencing the similar issue, any update on this ?

**Comment by ReubenBond** [comment]
Fixed on main by #9711 and #11149, with the recovery behavior preserved by #9714. The delivery-time cache-miss path shown in the supplied RunConsumerCursor stack trace now resumes inclusively from retained data. Recovery also preserves the first newer batch after an acknowledged message has been purged. These changes address the inactivity-related memory-stream delivery failure reported here. Closing as completed.
