### ISSUE TITLE
"Activation access violation" with grain timers in Orleans 8

### ISSUE THREAD

**Issue by EdeMeijer** [dotnet/orleans#8854]
We're in the process of migrating from Orleans 3.x to 8.0. One last issue is that we were frequently seeing the error `System.InvalidOperationException: Activation access violation. A non-activation thread attempted to access activation services.`.

I was able to boil the issue down to a small repro. It seems to occur when the grain calls (a reference to) itself with a grain timer concurrently with an external client calling it, and when accessing grain state is involved. The state storage bridge performs some check on the thread static grain context, which sometimes is missing. I had a quick look at the Orleans source to see if I could find the cause, but the whole scheduling stuff is a bit dense.

Anyway, here's a single file repro of the issue. It only depends on `Microsoft.Orleans.Server` 8.0.0 and uses .NET 8.0.

Program.cs
```C#
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Orleans.Runtime;

var hostBuilder = new HostBuilder();

hostBuilder.ConfigureLogging(loggingBuilder =>
    loggingBuilder.AddSimpleConsole(options =>
    {
        options.SingleLine = true;
        options.TimestampFormat = "HH:mm:ss.ffff ";
    })
);

hostBuilder.UseOrleans(siloBuilder =>
{
    siloBuilder.UseLocalhostClustering();
    siloBuilder.AddMemoryGrainStorageAsDefault();
});

hostBuilder.ConfigureServices(Services =>
{
    Services.AddSingleton<ExternalCallerService>();
    Services.AddHostedService(Sp => Sp.GetRequiredService<ExternalCallerService>());
});

using var app = hostBuilder.Build();
await app.RunAsync();


public class ExternalCallerService(IGrainFactory grainFactory, ILogger<ExternalCallerService> logger) : IHostedService
{
    private readonly CancellationTokenSource _cts = new();

    public Task StartAsync(CancellationToken cancellationToken)
    {
        var grain = grainFactory.GetGrain<ITestGrain>("test");

        Task.Run(async () =>
        {
            for (;;)
            {
                await Task.Delay(20, _cts.Token);
                try
                {
                    await grain.CallThatAccessesStateAsync();
                }
                catch (Exception Ex)
                {
                    logger.LogWarning(Ex, "Error during grain call");
                }
            }
        }, _cts.Token);

        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return _cts.CancelAsync();
    }
}

public interface ITestGrain : IGrainWithStringKey
{
    Task CallThatAccessesStateAsync();
}

public class TestGrainGrain : Grain, ITestGrain
{
    private readonly IPersistentState<TestGrainState> _state;

    public TestGrainGrain(
        [PersistentState("test")] IPersistentState<TestGrainState> state
    )
    {
        _state = state;
    }

    public override Task OnActivateAsync(CancellationToken CancelToken)
    {
        var thisRef = this.AsReference<ITestGrain>();

        RegisterTimer(
            _ => thisRef.CallThatAccessesStateAsync(),
            null,
            TimeSpan.FromSeconds(0.05),
            TimeSpan.FromSeconds(0.05)
        );

        return Task.CompletedTask;
    }

    public async Task CallThatAccessesStateAsync()
    {
        // Just access the state is enough
        _ = _state.State.Value;
    }
}

public sealed class TestGrainState
{
    public int Value { get; set; } = 0;
}

```  
Output:

```
10:02:18.3558 info: Orleans.Runtime.Silo[100404] Silo starting with GC settings: ServerGC=False GCLatencyMode=Interactive
10:02:18.3960 warn: Orleans.Runtime.Silo[100405] Note: Silo not running with ServerGC turned on - recommend checking app config : <configuration>-<runtime>-<gcServer enabled="true">
10:02:18.3961 warn: Orleans.Runtime.Silo[100405] Note: ServerGC only kicks in on multi-core systems (settings enabling ServerGC have no effect on single-core machines).
10:02:18.4040 info: Orleans.Runtime.Silo[100403] -------------- Initializing silo on host ede-laptop MachineName ede-laptop at 127.0.0.1:11111, gen 66992538 --------------
10:02:18.4041 info: Orleans.Runtime.Silo[100415] Starting silo Silo_08ae5
10:02:18.8936 info: Orleans.Runtime.Silo[100422] -------------- Started silo S127.0.0.1:11111:66992538, ConsistentHashCode 469E3776 --------------
10:02:18.9101 info: Orleans.Hosting.SiloHostedService[0] Starting Orleans Silo.
10:02:18.9436 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.ActivationCountBasedPlacementOptions:  ChooseOutOf: 2 
10:02:18.9458 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.ClusterMembershipOptions:  NumMissedTableIAmAliveLimit: 2 LivenessEnabled: True ProbeTimeout: 00:00:05 TableRefreshTimeout: 00:01:00 DeathVoteExpirationTimeout: 00:02:00 IAmAliveTablePublishTimeout: 00:05:00 MaxJoinAttemptTime: 00:05:00 UseLivenessGossip: True NumProbedSilos: 3 NumMissedProbesLimit: 3 NumVotesForDeathDeclaration: 2 DefunctSiloExpiration: 7.00:00:00 DefunctSiloCleanupPeriod: 01:00:00 LocalHealthDegradationMonitoringPeriod: 00:00:10 ExtendProbeTimeoutDuringDegradation: True EnableIndirectProbes: True 
10:02:18.9461 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.ClusterOptions:  ClusterId: default ServiceId: default 
10:02:18.9473 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.ConnectionOptions:  ProtocolVersion: Version1 ConnectionsPerEndpoint: 1 ConnectionRetryDelay: 00:00:01 OpenConnectionTimeout: 00:00:05 
10:02:18.9475 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.ConsistentRingOptions:  NumVirtualBucketsConsistentRing: 30 UseVirtualBucketsConsistentRing: True 
10:02:18.9478 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.DevelopmentClusterMembershipOptions:  PrimarySiloEndpoint: 127.0.0.1:11111 
10:02:18.9480 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.EndpointOptions:  AdvertisedIPAddress: 127.0.0.1 SiloPort: 11111 GatewayPort: 30000 SiloListeningEndpoint:  GatewayListeningEndpoint:  
10:02:18.9485 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.GrainCollectionOptions:  CollectionQuantum: 00:01:00 CollectionAge: 00:15:00 ActivationTimeout: 00:00:30 DeactivationTimeout: 00:00:30 
10:02:18.9535 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.GrainDirectoryOptions:  CachingStrategy: Adaptive CacheSize: 1000000 InitialCacheTTL: 00:00:30 MaximumCacheTTL: 00:04:00 CacheTTLExtensionFactor: 2 LazyDeregistrationDelay: 00:01:00 
10:02:18.9537 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.GrainVersioningOptions:  DefaultCompatibilityStrategy: BackwardCompatible DefaultVersionSelectorStrategy: AllCompatibleVersions 
10:02:18.9539 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.LoadSheddingOptions:  LoadSheddingEnabled: False LoadSheddingLimit: 95 
10:02:18.9542 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.MemoryGrainStorageOptions-Default:  NumStorageGrains: 10 InitStage: 10000 GrainStorageSerializer: Orleans.Storage.JsonGrainStorageSerializer 
10:02:18.9546 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.SchedulingOptions:  DelayWarningThreshold: 00:00:10 ActivationSchedulingQuantum: 00:00:00.1000000 TurnWarningLengthThreshold: 00:00:01 MaxPendingWorkItemsSoftLimit: 0 StoppedActivationWarningInterval: 00:01:00 
10:02:18.9562 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.SiloMessagingOptions:  SiloSenderQueues: 0 GatewaySenderQueues: 0 MaxForwardCount: 2 ClientDropTimeout: 00:01:00 ClientRegistrationRefresh: 00:05:00 ClientGatewayShutdownNotificationTimeout: 00:00:05 MaxEnqueuedRequestsSoftLimit: 0 MaxEnqueuedRequestsHardLimit: 0 MaxEnqueuedRequestsSoftLimit_StatelessWorker: 0 MaxEnqueuedRequestsHardLimit_StatelessWorker: 0 MaxRequestProcessingTime: 02:00:00 AssumeHomogenousSilosForTesting: False ShutdownRerouteTimeout: 00:00:10 SystemResponseTimeout: 00:00:30 GrainWorkloadAnalysisPeriod: 00:00:05 RequestProcessingWarningTime: 00:00:05 RequestQueueDelayWarningTime: 00:00:10 WaitForMessageToBeQueuedForOutboundTime: 00:00:02 ResponseTimeout: 00:00:30 ResponseTimeoutWithDebugger: 00:30:00 DropExpiredMessages: True MaxMessageHeaderSize: 10485760 MaxMessageBodySize: 104857600 
10:02:18.9565 info: Orleans.Runtime.SiloOptionsLogger[0] Configuration Orleans.Configuration.SiloOptions:  SiloName: Silo_08ae5 
10:02:18.9779 info: Orleans.Runtime.Silo[100401] Silo Start()
10:02:18.9940 info: Orleans.Runtime.Silo[100452] Start local grain directory took 1 milliseconds to finish
10:02:19.0085 info: Orleans.Runtime.MembershipService.MembershipTableManager[100603] MembershipOracle starting on host ede-laptop with SiloAddress S127.0.0.1:11111:66992538 at 2024-02-15 09:02:18.660 GMT
10:02:19.0104 info: Orleans.Runtime.MembershipService.SystemTargetBasedMembershipTable[100635] Creating in-memory membership table
10:02:19.0105 info: Orleans.Runtime.Silo[100452] Init grain services took 1 milliseconds to finish
10:02:19.0115 info: Orleans.Runtime.MembershipService.MembershipTableSystemTarget[100637] GrainBasedMembershipTable Activated.
10:02:19.0246 info: Orleans.Runtime.Silo[100452] Start deployment load collector took 14 milliseconds to finish
10:02:19.0717 info: Orleans.Runtime.MembershipService.SystemTargetBasedMembershipTable[100631] Connected to membership table provider.
10:02:19.0892 info: Orleans.Runtime.MembershipService.MembershipAgent[100663] Joining
10:02:19.1158 info: Orleans.Runtime.MembershipService.MembershipAgent[100604] -BecomeActive
10:02:19.1291 info: Orleans.Runtime.MembershipService.MembershipAgent[100605] -Finished BecomeActive.
10:02:19.1330 info: Orleans.Hosting.SiloHostedService[0] Orleans Silo started.
10:02:19.1460 info: Microsoft.Hosting.Lifetime[0] Application started. Press Ctrl+C to shut down.
10:02:19.1462 info: Microsoft.Hosting.Lifetime[0] Hosting environment: Production
10:02:19.1462 info: Microsoft.Hosting.Lifetime[0] Content root path: /home/ede/repos/OrleansBugRepro/bin/Debug/net8.0/
10:02:23.0090 warn: ExternalCallerService[0] Error during grain call System.InvalidOperationException: Activation access violation. A non-activation thread attempted to access activation services.    at Orleans.Runtime.GrainRuntime.<CheckRuntimeContext>g__ThrowMissingContext|21_0() in /_/src/Orleans.Runtime/Core/GrainRuntime.cs:line 97    at Orleans.Runtime.GrainRuntime.CheckRuntimeContext(IGrainContext context) in /_/src/Orleans.Runtime/Core/GrainRuntime.cs:line 96    at Orleans.Core.StateStorageBridge`1.get_State() in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 34    at TestGrainGrain.CallThatAccessesStateAsync() in /home/ede/repos/OrleansBugRepro/Program.cs:line 98    at Orleans.Runtime.TaskRequest.Invoke() in /_/src/Orleans.Core.Abstractions/Runtime/GrainReference.cs:line 734 --- End of stack trace from previous location ---    at Orleans.Serialization.Invocation.ResponseCompletionSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 98    at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) --- End of stack trace from previous location ---    at ExternalCallerService.<>c__DisplayClass4_0.<<StartAsync>b__0>d.MoveNext() in /home/ede/repos/OrleansBugRepro/Program.cs:line 47
10:02:23.1118 warn: ExternalCallerService[0] Error during grain call System.InvalidOperationException: Activation access violation. A non-activation thread attempted to access activation services.    at Orleans.Runtime.GrainRuntime.<CheckRuntimeContext>g__ThrowMissingContext|21_0() in /_/src/Orleans.Runtime/Core/GrainRuntime.cs:line 97    at Orleans.Runtime.GrainRuntime.CheckRuntimeContext(IGrainContext context) in /_/src/Orleans.Runtime/Core/GrainRuntime.cs:line 96    at Orleans.Core.StateStorageBridge`1.get_State() in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 34    at TestGrainGrain.CallThatAccessesStateAsync() in /home/ede/repos/OrleansBugRepro/Program.cs:line 98    at Orleans.Runtime.TaskRequest.Invoke() in /_/src/Orleans.Core.Abstractions/Runtime/GrainReference.cs:line 734 --- End of stack trace from previous location ---    at Orleans.Serialization.Invocation.ResponseCompletionSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 98    at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) --- End of stack trace from previous location ---    at ExternalCallerService.<>c__DisplayClass4_0.<<StartAsync>b__0>d.MoveNext() in /home/ede/repos/OrleansBugRepro/Program.cs:line 47
10:02:23.8929 warn: ExternalCallerService[0] Error during grain call System.InvalidOperationException: Activation access violation. A non-activation thread attempted to access activation services.    at Orleans.Runtime.GrainRuntime.<CheckRuntimeContext>g__ThrowMissingContext|21_0() in /_/src/Orleans.Runtime/Core/GrainRuntime.cs:line 97    at Orleans.Runtime.GrainRuntime.CheckRuntimeContext(IGrainContext context) in /_/src/Orleans.Runtime/Core/GrainRuntime.cs:line 96    at Orleans.Core.StateStorageBridge`1.get_State() in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 34    at TestGrainGrain.CallThatAccessesStateAsync() in /home/ede/repos/OrleansBugRepro/Program.cs:line 98    at Orleans.Runtime.TaskRequest.Invoke() in /_/src/Orleans.Core.Abstractions/Runtime/GrainReference.cs:line 734 --- End of stack trace from previous location ---    at Orleans.Serialization.Invocation.ResponseCompletionSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 98    at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) --- End of stack trace from previous location ---    at ExternalCallerService.<>c__DisplayClass4_0.<<StartAsync>b__0>d.MoveNext() in /home/ede/repos/OrleansBugRepro/Program.cs:line 47
10:02:24.4112 warn: ExternalCallerService[0] Error during grain call System.InvalidOperationException: Activation access violation. A non-activation thread attempted to access activation services.    at Orleans.Runtime.GrainRuntime.<CheckRuntimeContext>g__ThrowMissingContext|21_0() in /_/src/Orleans.Runtime/Core/GrainRuntime.cs:line 97    at Orleans.Runtime.GrainRuntime.CheckRuntimeContext(IGrainContext context) in /_/src/Orleans.Runtime/Core/GrainRuntime.cs:line 96    at Orleans.Core.StateStorageBridge`1.get_State() in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 34    at TestGrainGrain.CallThatAccessesStateAsync() in /home/ede/repos/OrleansBugRepro/Program.cs:line 98    at Orleans.Runtime.TaskRequest.Invoke() in /_/src/Orleans.Core.Abstractions/Runtime/GrainReference.cs:line 734 --- End of stack trace from previous location ---    at Orleans.Serialization.Invocation.ResponseCompletionSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 98    at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) --- End of stack trace from previous location ---    at ExternalCallerService.<>c__DisplayClass4_0.<<StartAsync>b__0>d.MoveNext() in /home/ede/repos/OrleansBugRepro/Program.cs:line 47
...
```

The timers involved run on a quite high rates to be able to trigger the condition frequently. There seems to be some kind of race condition involved as it only happens relatively infrequently, but it happens nonetheless.

Please let me know if more info is required.

**Comment by spingee** [comment]
Try Task.Run(thisRef.CallThatAccessesStateAsync)

**Comment by EdeMeijer** [comment]
Tried that already, same thing happens. Also, it shouldn't matter. The grain call through a reference should be schedul

**Comment by ReubenBond** [comment]
Thanks for reporting, this does look like a bug. I'm taking a look now.

**Comment by HermesNew** [comment]
This issue also present in 3.x.
