### ISSUE TITLE
Receiving events from Azure Queue Stream Provider multiple times

### ISSUE THREAD

**Issue by BenjaminGibbs** [dotnet/orleans#890]
I appear to have an issue which I have been chasing for a few weeks now, where when I push messages down a stream the consumer/handler is not receiving them.

I have this issue in my main solution which has 23 projects, but managed to replicate it in a simple solution as well.

I'll take some time to explain the set up I have: 

I have three grain types: Red, Blue and Green.

The Red grain has one function which takes a string and posts it as a byte array down into two separate streams, both with an id of `guid.empty`

The Blue and Green grains have an `ImplicitStreamSubscription` to `TestStream` and `TestStream2` respectively.

To start with, everything works as expected, the Red grain sends the events down `TestStream` and `TestStream2` and the handlers in both the Blue and Green grains receive the events, but within a few minutes (I appear unable to work out 'why') the handlers stop receiving the events, even though they appear to be submitted.

When trying to replicate the issue, just having one stream, it didn't appear to cause any issues and firing at streams with different id's for each request didn't have an issue either. It only appeared to be an issue if firing off to a stream which had already had data sent to it. 

However, after reading #884 it could be the cause of the issue, as I am getting a log full of `QueueCacheMissExceptions` - if it is will reverting back to an older version of Orleans be a workaround until the next release?

```
[2015-10-08 22:44:48.073 GMT    17	ERROR  	103315	PullingAgentSystemTarget/FF/821b63b5-QueueStore	127.0.0.1:11111]	!!!!!!!!!! Ignored RunConsumerCursor Error	
Exc level 0: Orleans.Streams.QueueCacheMissException: Item not found in cache.  Requested: [EventSequenceToken: SeqNum=31, EventIndex=0], Low: [EventSequenceToken: SeqNum=190, EventIndex=0], High: [EventSequenceToken: SeqNum=191, EventIndex=0]
   at Orleans.Providers.Streams.Common.SimpleQueueCache.InitializeCursor(SimpleQueueCacheCursor cursor, StreamSequenceToken sequenceToken)
   at Orleans.Providers.Streams.Common.SimpleQueueCache.TryGetNextMessage(SimpleQueueCacheCursor cursor, IBatchContainer& batch)
   at Orleans.Providers.Streams.Common.SimpleQueueCacheCursor.MoveNext()
   at Orleans.Streams.PersistentStreamPullingAgent.<RunConsumerCursor>d__46.MoveNext()
```

**Comment by gabikliot** [comment]
@BenjaminGibbs , you are using Azure queue stream provider, right?

If you try the latest version from master, including #884, does it work? There indeed have been a number of fixes around those issues lately (multiple streams, some cache miss exceptions), and unfortunately you need all of them for things to work properly.

**Comment by BenjaminGibbs** [comment]
Sorry yes I am using the Azure Queue, sorry I should have mentioned that.

**Comment by gabikliot** [comment]
Yes, try the master. There is a good chance it will fix the issue.

**Comment by BenjaminGibbs** [comment]
On the surface the issues appear to be fixed when using the master. I am going to do a bit more testing this evening and see if anything else pops up.

**Comment by sergeybykov** [comment]
Sounds encouraging. Please keep us posted.

**Comment by BenjaminGibbs** [comment]
So it works fine on the surface, when I push a similar workload to before it works like a dream, however when I push the workload so the streams get a backlog I start losing items and they don't get delivered. This is looking like a different error to before.

From the log: I am using the AzureQueueStreamProvider with the default settings, queue count and cache size.

```
[2015-10-13 00:20:52.053 GMT    19	ERROR  	103211	AzureQueueDataManager	127.0.0.1:11111]	!!!!!!!!!! Error doing DeleteMessage for Azure storage queue beta-queuestore-3 
Exception = Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\HttpResponseParsers.Common.cs:line 50
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.<DeleteMessageImpl>b__3a(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 2676
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 299
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AzureUtils.AzureQueueDataManager.<DeleteQueueMessage>d__20.MoveNext()
Request Information
RequestID:a09f9118-0003-0044-0f4c-052ccc000000
RequestDate:Tue, 13 Oct 2015 00:20:34 GMT
StatusMessage:The specified message does not exist.
ErrorCode:MessageNotFound
	
Exc level 0: Microsoft.WindowsAzure.Storage.StorageException: Message = The remote server returned an error: (404) Not Found., HttpStatusCode = 404, HttpStatusMessage = The specified message does not exist., ExtendedErrorInformation.ErrorCode = MessageNotFound, ExtendedErrorInformation.ErrorMessage = The specified message does not exist.
RequestId:a09f9118-0003-0044-0f4c-052ccc000000
Time:2015-10-13T00:20:35.0431917Z.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AzureUtils.AzureQueueDataManager.<DeleteQueueMessage>d__20.MoveNext()
Exc level 1: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\HttpResponseParsers.Common.cs:line 50
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.<DeleteMessageImpl>b__3a(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 2676
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 299
[2015-10-13 00:20:52.061 GMT    19	ERROR  	103211	AzureQueueDataManager	127.0.0.1:11111]	!!!!!!!!!! Error doing DeleteMessage for Azure storage queue beta-queuestore-3 
Exception = Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\HttpResponseParsers.Common.cs:line 50
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.<DeleteMessageImpl>b__3a(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 2676
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 299
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AzureUtils.AzureQueueDataManager.<DeleteQueueMessage>d__20.MoveNext()
Request Information
RequestID:c7b6bad1-0003-002f-364c-05719a000000
RequestDate:Tue, 13 Oct 2015 00:20:34 GMT
StatusMessage:The specified message does not exist.
ErrorCode:MessageNotFound
```

**Comment by gabikliot** [comment]
This indeed looks a different issue.
My guess is that we try to delete twice from the queue and second time it fails, naturally.
Jason, I would check how we handle failed deletes. What happened for example if first delete succeeded but response timed out, would we retry and how. It can explain this log error.

It does looks though as a benign issue, if we failed to delete (maybe second time) its not a problem.
Benjamin, is there any application visible problem? If not, it may be the 2nd delete case, and there is no problem

**Comment by jason-bragg** [comment]
I'll review the error handling logic.  We set a retry policy on the storage account, which would make this a natural error to receive any time the azure client library retries due to timeouts.  Our error handling should catch, log, and ignore this error when deleting messages.  If it does not, this is a bug.

**Comment by gabikliot** [comment]
Thanks Jason. Agree with what you wrote. Of course, it could also be, in theory,  a different bug where we somehow try to delete a wrong msg that was never in the queue,,but I doubt.

The most important thing I think is to make sure that if the above error happens, we do ignore it and keep processing as nothing happened. If the msg was not deleted, it will re appear and we will re deliver, later on, in accordance with azure queue at least once semantics.

**Comment by jason-bragg** [comment]
We don't ignore this error.  It is logged and re-thrown, which will cause the main reader loop in the agent to exit until the next timer.  In general, this is not good, but should not cause data loss.

To mitigate this some, until we get a fix, you can set "GetQueueMessagesTimerPeriod" to TimeSpan.FromMilliseconds(10) in the provider configuration.  This will reduce the effect of this exception.

"When I push the workload so the streams get a backlog I start losing items and they don't get delivered"
The posted exceptions 'should' not be causing data loss.  Can you log any OnErrorAsync calls to your grains?  If the stream infrastructure is having difficulties delivering events, it will attempt to notify the grain of these errors via the OnErrorAsync handler.

**Comment by BenjaminGibbs** [comment]
So after somewhat alot more testing in the last 12 hours, I am not losing message they are being delivery multiple times - my mistake.

I am now sending Random GUID's down 4 different streams with the aim that at the end of each run they state should be the same - And it is; 

However I am also counting how many times we try to add an item which is already in the state and it fails, ie it is a re submission. - This is not triggering onErrorAsync.

If I push 10,000 items at once it gets backloged but in the end it all the states match, however the reprocess count is up to 10 times that of the times in the list, each stream has a different reprocess count. 

But if I drop the cache size to a low value like 10 this doesn't happen. It should be noted I an intentionally creating a backlog on the grain at the moment, to see how it would handle a spike in traffic.

A possible explanation could be that the the stream cache could be holding the items longer than the time out which means the AzureQueue is making the items reappear which then get re-added to the Stream Cache so in effect an never ending loop as in items are getting processed multiple times.

I was able to replicate this theory by adding a delay to the processing of the grain that consumes the message, I could push in 100 items in to the streams and when I had the delay it re-processed in excess of 1700 extra messages, on top of the items. - If I repeated I get the same number of excess if I increase the delay it goes up, reduce the delay it goes down.

On error is not being fired.

**Comment by jason-bragg** [comment]
"This is not triggering onErrorAsync"
That is correct.  It should not.  Azure queues allow multiple delivery, so this is not an error.  If you see data loss, you should see OnErrorAsync calls.

"the AzureQueue is making the items reappear"
This can happen.  When using azure queue's it's important to keep event processing time lower than azure queues re-add time.

Setting the GetQueueMessagesTimerPeriod as mentioned before should help some with this, but in general, you'll need to perform some load tests and capacity planning to ensure that you've enough processing power for your load.
Tuning queue count and cache size can also help.

**Comment by jason-bragg** [comment]
Depending on how much effort you want to put into this, a custom queue cache could be developed, based off of SimpleQueueCache, which tracks how long messages have been in the cache and adjusts back pressure with this info.  Basically, if the time in the cache starts to approach the (configured) redelivery time, the cache could trigger the reader to back off, thereby reducing load.

This is more work of course, but it would be a more robust solution for azure queues with unbounded load.

**Comment by BenjaminGibbs** [comment]
Thanks Jason for clarification.

I am pleased the original Issue I posted is fixed, I think extending the SimpleQueueCache would be a useful thing to do to in long run so I will look at doing that, currently I can control this with cache size and timer period.

**Comment by veikkoeeva** [comment]
@BenjaminGibbs, @jason-bragg A very enlightening exchange of thoughts and conclusion. :+1:

**Comment by jason-bragg** [comment]
@BenjaminGibbs The SimpleQueueCache, as its name probably indicates, is a general all-purpose queue cache.  It is not queue specific.  If you do decide to make a custom adapter cache that is more tuned to azure queues, I could see that being useful to others in the community.  I fully expect that you're primary focus will be to build out the tech you need, but If you find the time, I'd be interested in seeing a issue opened regarding contributing your azure queue adapter cache to Orleans to be maintained as an alternative implementation of IQueueCache.

**Comment by jason-bragg** [comment]
@BenjaminGibbs A question in issue "Talk about the stream (Feedback on the stream and QueueCacheMissException) #850" reminded me of a cache behavior that may explain why you see more redeliveries with larger cache sizes. 

Events are removed from the queue (via the MessagesDeliveredAsync call) once they are purged from the cache.  In general they are purged from the cache when all consumers have delivered the event, however the SimpleQueueCache purges events in bulk, not on an individual event by event basis.  It has buckets of events and does not purge a bucket until all of the events in the bucket have been deliver.  If the cache size is increased the bucket size will increase increased, increasing the number of events that must be delivered before all events in the bucket can be released.

**Comment by gabikliot** [comment]
We can also allow to configure the number of buckets.

**Comment by gabikliot** [comment]
Can we please rename this issue to better represent what it is about: Something along the lines of: receiving events from azure queue stream provider multiple times.

**Comment by gabikliot** [comment]
@benjamingibbs, did you manage to solve it, by playing with cache size and number of buckets?

**Comment by sergeybykov** [comment]
@BenjaminGibbs Feel free to reopen if you are still experiencing this issue.
