### ISSUE TITLE
Expetion thrown on Subcribtion to MemoryStream.

### ISSUE THREAD

**Issue by IvansPhoto** [dotnet/orleans#8920]
### Looking for advice on how to properly use an explicit subscription.
I have an issue with subscriptions to a memory stream. To try to find a reason why an exception was thrown and determine how to use memory streams, I prepared a simple project. It uses LocalhostClustering, MemoryStreams, and a MemoryGrainStorage; contains only two Grain.
[Sample project](https://github.com/IvansPhoto/MsOrleans.Steams)

### Step to reproduce on the sample project.
1. Run the project.
2. Run any call in TestRequests.http (This file works in Rider). 

The endpoint "http://localhost:5287/test-1" uses a code chain when a Consumer Grain tries to subscribe to a stream.
The endpoint "http://localhost:5287/test-2" uses a code chain when a subscription is attempted in the minimal-api method.

### Exception
The exception is thrown in the generated code: 

> System.InvalidOperationException: No service for type 'Orleans.Storage.IGrainStorage' has been registered.

It happens after execution line 54 [var subscriptionHandles = await _stream.GetAllSubscriptionHandles();](https://github.com/IvansPhoto/MsOrleans.Steams/blob/master/MsOrleans.Steams.Main/Consumer.cs) for the "/test-1" endpoint and after line 43 [var subscription = await stream.SubscribeAsync...](https://github.com/IvansPhoto/MsOrleans.Steams/blob/master/MsOrleans.Steams.Main/Program.cs) for the "/test-2" endpoint.

### Stack trace for the /test-1 endpoint:
```
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'HTTP: GET test-1'
fail: Orleans.Runtime.Messaging.MessageCenter[101540]
      Error creating activation for grain pubsubrendezvous/StreamNS/StreamNS/StreamKey (interface: Orleans.Streams.IPubSubRendezvousGrain). Message Request [S127.0.0.1
:11111:70121202 consumer/IConsumer-1]->[S127.0.0.1:11111:70121202 pubsubrendezvous/StreamNS/StreamNS/StreamKey] Orleans.Streams.IPubSubRendezvousGrain.GetAllSubscriptions(StreamNS/StreamNS/StreamKey, consumer/IConsumer-1) #164
      System.InvalidOperationException: No service for type 'Orleans.Storage.IGrainStorage' has been registered.
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetRequiredKeyedService(Type serviceType, Object serviceKey, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService[T](IServiceProvider provider, Object serviceKey)    
         at Orleans.Streams.PubSubGrainStateStorageFactory.GetStorage(PubSubRendezvousGrain grain) in /_/src/Orleans.Streaming/PubSub/PubSubRendezvousGrain.cs:line 57 
         at lambda_method9(Closure, IServiceProvider, Object[])
         at Orleans.Runtime.DefaultGrainActivator.CreateInstance(IGrainContext context) in /_/src/Orleans.Runtime/Activation/DefaultGrainActivator.cs:line 30
         at Orleans.Runtime.ActivationDataActivatorProvider.ActivationDataActivator.CreateContext(GrainAddress activationAddress) in /_/src/Orleans.Runtime/Activation/ActivationDataActivatorProvider.cs:line 124
         at Orleans.Runtime.GrainContextActivator.CreateInstance(GrainAddress address) in /_/src/Orleans.Runtime/Activation/IGrainContextActivator.cs:line 61
         at Orleans.Runtime.Catalog.GetOrCreateActivation(GrainId& grainId, Dictionary`2 requestContextData, MigrationContext rehydrationContext) in /_/src/Orleans.Runtime/Catalog/Catalog.cs:line 265
         at Orleans.Runtime.Messaging.MessageCenter.ReceiveMessage(Message msg) in /_/src/Orleans.Runtime/Messaging/MessageCenter.cs:line 518
fail: Orleans.Grain[100513]
      Error activating grain [Activation: S127.0.0.1:11111:70121202/consumer/IConsumer-1@1228aec642df444f8981581f0c3890f2#GrainType=MsOrleans.Steams.Main.Consumer,MsOrleans.Steams.Main Placement=RandomPlacement State=Activating]
      System.InvalidOperationException: No service for type 'Orleans.Storage.IGrainStorage' has been registered.
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetRequiredKeyedService(Type serviceType, Object serviceKey, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService[T](IServiceProvider provider, Object serviceKey)    
         at Orleans.Streams.PubSubGrainStateStorageFactory.GetStorage(PubSubRendezvousGrain grain) in /_/src/Orleans.Streaming/PubSub/PubSubRendezvousGrain.cs:line 57 
         at lambda_method9(Closure, IServiceProvider, Object[])
         at Orleans.Runtime.DefaultGrainActivator.CreateInstance(IGrainContext context) in /_/src/Orleans.Runtime/Activation/DefaultGrainActivator.cs:line 30
         at Orleans.Runtime.ActivationDataActivatorProvider.ActivationDataActivator.CreateContext(GrainAddress activationAddress) in /_/src/Orleans.Runtime/Activation/ActivationDataActivatorProvider.cs:line 124
         at Orleans.Runtime.GrainContextActivator.CreateInstance(GrainAddress address) in /_/src/Orleans.Runtime/Activation/IGrainContextActivator.cs:line 61
         at Orleans.Runtime.Catalog.GetOrCreateActivation(GrainId& grainId, Dictionary`2 requestContextData, MigrationContext rehydrationContext) in /_/src/Orleans.Runtime/Catalog/Catalog.cs:line 265
         at Orleans.Runtime.Messaging.MessageCenter.ReceiveMessage(Message msg) in /_/src/Orleans.Runtime/Messaging/MessageCenter.cs:line 518
      --- End of stack trace from previous location ---
         at Orleans.Serialization.Invocation.ResponseCompletionSource`1.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 230
         at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
      --- End of stack trace from previous location ---
         at Orleans.Streams.StreamPubSubImpl.GetAllSubscriptions(QualifiedStreamId streamId, GrainId streamConsumer) in /_/src/Orleans.Streaming/PubSub/StreamPubSubImpl.cs:line 72
         at Orleans.Streams.StreamConsumer`1.GetAllSubscriptions() in /_/src/Orleans.Streaming/Internal/StreamConsumer.cs:line 194
         at MsOrleans.Steams.Main.Consumer.OnActivateAsync(CancellationToken cancellationToken) in C:\Users\guteh\RiderProjects\MsOrleans.Steams\MsOrleans.Steams.Main\Consumer.cs:line 54
         at Orleans.Internal.OrleansTaskExtentions.MakeCancellable(Task task, CancellationToken cancellationToken) in /_/src/Orleans.Core/Async/TaskExtensions.cs:line 187
         at Orleans.Internal.OrleansTaskExtentions.WithCancellation(Task taskToComplete, String message, CancellationToken cancellationToken) in /_/src/Orleans.Core/Async/TaskExtensions.cs:line 144
         at Orleans.Runtime.ActivationData.<ActivateAsync>g__CallActivateAsync|142_0(Dictionary`2 requestContextData, CancellationToken cancellationToken) in /_/src/Orleans.Runtime/Catalog/ActivationData.cs:line 1420
info: Microsoft.AspNetCore.Http.HttpResults.ProblemHttpResult[1]
      Setting HTTP status code 500.
info: Microsoft.AspNetCore.Http.HttpResults.ProblemHttpResult[3]
      Writing value of type 'ProblemDetails' as Json.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'HTTP: GET test-1'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5287/test-1 - 500 - application/problem+json 168.4531ms
```

**Comment by scalalang2** [comment]
You need to setup a grain storage named "PubSub".

**Comment by JonahL** [comment]
@scalalang2 Oh! I was under the impression that you could pick any name for the backing store and that was just the name they used for examples. I did not realize that there needed to be a store that was explicitly called that. 

That fixed it. Thanks!

**Comment by scalalang2** [comment]
> Oh! I was under the impression that you could pick any name for the backing store and that was just the name they used for examples.

I agree that the description of [official docs](https://learn.microsoft.com/en-us/dotnet/orleans/streaming/streams-quick-start?pivots=orleans-7-0) is pretty ambiguous 

btw, I'm glad to here that it helped you :)

**Comment by IvansPhoto** [comment]
@scalalang2 Thanks for the clarifications!
It would be nice to have a sentence in [the documentation](https://github.com/dotnet/orleans/issues/8920#issuecomment-2027273627) like that 

> silo.AddMemoryGrainStorage(ProviderConstants.DEFAULT_PUBSUB_PROVIDER_NAME) is required for pub-sub streaming.

**Comment by IvansPhoto** [comment]
@scalalang2 Thanks for the clarifications!
It would be nice to have a sentence in [the documentation](https://github.com/dotnet/orleans/issues/8920#issuecomment-2027273627) like that 

> silo.AddMemoryGrainStorage(ProviderConstants.DEFAULT_PUBSUB_PROVIDER_NAME) is required for pub-sub streaming.
