### ISSUE TITLE
[Aspire] Cannot start Orleans client project because UseOrleansClient() tries to configure storage providers

### ISSUE THREAD

**Issue by christiansparre** [dotnet/orleans#8932]
Hi

I have been playing around with Aspire and Orleans. but there is a problem when trying to use an Orleans client. 

The issue is that Aspire includes the `Orleans__GrainStorage__Default*` environment variables for the client project and then `UseOrleansClient()` will try to configure storage providers resulting in the following exception in the client startup

`Could not find GrainStorage provider named 'AzureBlobStorage'. This can indicate that either the 'Microsoft.Orleans.Sdk' package the provider's package are not referenced by your application.`

```
Unhandled exception. System.InvalidOperationException: Could not find GrainStorage provider named 'AzureBlobStorage'. This can indicate that either the 'Microsoft.Orleans.Sdk' package the provider's package are not referenced by your application.
   at Orleans.DefaultClientServices.<ApplyConfiguration>g__GetRequiredProvider|2_1(Dictionary`2 knownProviderTypes, String kind, String name) in /_/src/Orleans.Core/Core/DefaultClientServices.cs:line 203
   at Orleans.DefaultClientServices.<ApplyConfiguration>g__ConfigureProvider|2_0(IClientBuilder builder, Dictionary`2 knownProviderTypes, String kind, String name, IConfigurationSection configurationSection) in /_/src/Orleans.Core/Core/DefaultClientServices.cs:line 190
   at Orleans.DefaultClientServices.<ApplyConfiguration>g__ApplyNamedSubsections|2_4(IClientBuilder builder, IConfigurationSection cfg, Dictionary`2 knownProviderTypes, String sectionName) in /_/src/Orleans.Core/Core/DefaultClientServices.cs:line 237
   at Orleans.DefaultClientServices.ApplyConfiguration(IClientBuilder builder) in /_/src/Orleans.Core/Core/DefaultClientServices.cs:line 179
   at Orleans.DefaultClientServices.AddDefaultServices(IClientBuilder builder) in /_/src/Orleans.Core/Core/DefaultClientServices.cs:line 157
   at Orleans.Hosting.ClientBuilder..ctor(IServiceCollection services, IConfiguration configuration) in /_/src/Orleans.Core/Core/ClientBuilder.cs:line 21
   at Microsoft.Extensions.Hosting.OrleansClientGenericHostExtensions.AddOrleansClient(IServiceCollection services, IConfiguration configuration) in /_/src/Orleans.Core/Hosting/OrleansClientGenericHostExtensions.cs:line 204
   at Microsoft.Extensions.Hosting.OrleansClientGenericHostExtensions.AddOrleansClient(IServiceCollection services, IConfiguration configuration, Action`1 configureDelegate) in /_/src/Orleans.Core/Hosting/OrleansClientGenericHostExtensions.cs:line 183
   at Microsoft.Extensions.Hosting.OrleansClientGenericHostExtensions.UseOrleansClient(IHostApplicationBuilder hostAppBuilder, Action`1 configureDelegate) in /_/src/Orleans.Core/Hosting/OrleansClientGenericHostExtensions.cs:line 86
   at Microsoft.Extensions.Hosting.OrleansClientGenericHostExtensions.UseOrleansClient(IHostApplicationBuilder hostAppBuilder) in /_/src/Orleans.Core/Hosting/OrleansClientGenericHostExtensions.cs:line 65
   at Program.<Main>$(String[] args) in D:\Code\Misc\OrleansAspireTest\OrleansAspireTest.Client\Program.cs:line 21
```

I have a repro solution here: https://github.com/christiansparre/Aspire_Orleans_Client_Repro_20240403

A hack in the client is to remove the `Orleans__GrainStorage__Default*` environment variables during startup as demonstrated here: https://github.com/christiansparre/Aspire_Orleans_Client_Repro_20240403/blob/main/OrleansAspireTest.Client/Program.cs#L4-L15

**Comment by christiansparre** [comment]
Just a note for anyone looking at this issue 😉 It appears to still be an issue in 8.1.0, but a fix is coming on the Aspire side, but is not available yet as far as I can see.

https://github.com/dotnet/aspire/blob/main/playground/orleans/OrleansAppHost/Program.cs#L23

https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Orleans/OrleansServiceExtensions.cs#L335

**Comment by ReubenBond** [comment]
Yes, thank you @christiansparre!

**Comment by ReubenBond** [comment]
I'll close this since it's fixed even though the fix is not released quite yet
