### ISSUE TITLE
ObjectDisposedException at Orleans.Runtime.GrainTimer.ForwardToAsyncCallback

### ISSUE THREAD

**Issue by alrz** [dotnet/orleans#9014]
`Caught and ignored exception thrown from timer callback for timer GrainTimer.sys.svc.user.95B6CAE6/10.42.89.234:11111@75196383Timer TimerCallbackHandler:[SystemTarget: S10.42.89.234:11111:75196383/sys.svc.user.95B6CAE6/10.42.89.234:11111@75196383@0d73e76f00000000f69b786b00000000]->System.Threading.Tasks.Task <Start>b__11_0(System.Object)`
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
   at Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.GetService[TService](Object caller, ICodecProvider codecProvider) in /_/src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs:line 72
   at OrleansCodeGen.Orleans.Runtime.Proxy_IManagementGrain..ctor(GrainReferenceShared arg0, IdSpan arg1) in /_/src/Orleans.Core/Orleans.CodeGenerator/Orleans.CodeGenerator.OrleansSerializationSourceGenerator/Orleans.Core.orleans.g.cs:line 1115
   at Proxy_IManagementGrain(Object, GrainReferenceShared, IdSpan)
   at Orleans.GrainReferences.GrainReferenceActivatorProvider.GrainReferenceActivator.CreateReference(GrainId grainId) in /_/src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs:line 380
   at Orleans.GrainReferences.GrainReferenceActivator.CreateReference(GrainId grainId, GrainInterfaceType interfaceType) in /_/src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs:line 57
   at Orleans.GrainFactory.GetGrain(Type interfaceType, IdSpan grainKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 217
   at Orleans.GrainFactory.GetGrain[TGrainInterface](Int64 primaryKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 51
   at OrleansDashboard.SiloGrainService.CollectStatistics(Boolean canDeactivate)
   at Orleans.Runtime.GrainTimer.ForwardToAsyncCallback(Object state) in /_/src/Orleans.Runtime/Timers/GrainTimer.cs:line 116
```

**Comment by alrz** [comment]
With a slightly different stack from https://github.com/OrleansContrib/OrleansDashboard/issues/422

**Comment by EricSites** [comment]
I am getting the same thing on shutdown.

`[23:31:56 ERR] Caught and ignored exception thrown from timer callback for timer GrainTimer.sys.svc.user.95B6CAE6/127.0.0.1:11111@77254271Timer TimerCallbackHandler:[SystemTarget: S127.0.0.1:11111:77254271/sys.svc.user.95B6CAE6/127.0.0.1:11111@77254271@0d73e76f00000000925ba19900000000]->System.Threading.Tasks.Task <Start>b__11_0(System.Object) <s:Orleans.Runtime.GrainTimer>
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
   at Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.GetService[TService](Object caller, ICodecProvider codecProvider) in /_/src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs:line 57
   at OrleansCodeGen.Orleans.Runtime.Proxy_IManagementGrain..ctor(GrainReferenceShared arg0, IdSpan arg1) in /_/src/Orleans.Core/Orleans.CodeGenerator/Orleans.CodeGenerator.OrleansSerializationSourceGenerator/Orleans.Core.orleans.g.cs:line 1115
   at Proxy_IManagementGrain(Object, GrainReferenceShared, IdSpan)
   at Orleans.GrainReferences.GrainReferenceActivator.CreateReference(GrainId grainId, GrainInterfaceType interfaceType) in /_/src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs:line 57
   at Orleans.GrainFactory.GetGrain(Type interfaceType, IdSpan grainKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 217
   at Orleans.GrainFactory.GetGrain[TGrainInterface](Int64 primaryKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 51
   at OrleansDashboard.SiloGrainService.CollectStatistics(Boolean canDeactivate)
   at Orleans.Runtime.GrainTimer.ForwardToAsyncCallback(Object state) in /_/src/Orleans.Runtime/Timers/GrainTimer.cs:line 116
`

**Comment by ReubenBond** [comment]
I believe this has been fixed in main (there are nightly builds if you'd like to try those)

**Comment by ReubenBond** [comment]
Closing for now, since this ought to be fixed. Please open a new issue referencing this if you still see this after upgrading to Orleans v8.2.0
