### ISSUE TITLE
Cannot activate the grain after clearing its state.

### ISSUE THREAD

**Issue by scalalang2** [dotnet/orleans#9154]
## Environment
- `Persistent Storage Provider` : DynamoDB
- `Framework Version` : Orleans 8.2.0

## Background
The `ClearStateAsync` funcction doesn't remove the entry from storage by default.
Instead it only sets the state value to `null`,

If `ReadStateAsync()` is invoked when the value is `null,` 
then it occurs an error from Serializer. : `Insufficient data present in buffer.`

- `ReadStateAsync` is called when trying to activate the same grain
    - the serializer cannot read the value cleared by `ClearStateAsync`

## How to reproduce
```cs
public class TestGrain : Grain, ITestGrain
{
    private readonly IPersistentState<TestState> state;

    public TestGrain([PersistentState("Test")] IPersistentState<TestState> state)
    {
        this.state = state;
    }

    public async Task Test()
    {
        // Calling this method after clearing the state will trigger an error.
        await this.state.ReadStateAsync();

        if (this.state.Activated == false)
        {
            this.state.State.Activated = true;
            await this.state.WriteStateAsync();
        }
        else
        {
            await this.state.ClearStateAsync();
        }
    }
}
```

# Logs
```
System.InvalidOperationException: Insufficient data present in buffer.
   at Orleans.Serialization.Buffers.Reader`1.ThrowInsufficientData() in /_/src/Orleans.Serialization/Buffers/Reader.cs:line 741
   at Orleans.Serialization.Buffers.Reader`1.MoveNext() in /_/src/Orleans.Serialization/Buffers/Reader.cs:line 602
   at Orleans.Serialization.Buffers.Reader`1.ReadByteSlow(Reader`1& reader) in /_/src/Orleans.Serialization/Buffers/Reader.cs:line 643
   at Orleans.Serialization.Serializer.Deserialize[T](ReadOnlySpan`1 source) in /_/src/Orleans.Serialization/Serializer.cs:line 423
   at Orleans.Serialization.Serializer.Deserialize[T](ReadOnlyMemory`1 source) in /_/src/Orleans.Serialization/Serializer.cs:line 466
   at Orleans.Storage.OrleansGrainStorageSerializer.Deserialize[T](BinaryData input) in /_/src/Orleans.Core/Providers/StorageSerializer/OrleansGrainStateSerializer.cs:line 34
   at Orleans.Storage.GrainStorageSerializerExtensions.Deserialize[T](IGrainStorageSerializer serializer, ReadOnlyMemory`1 input) in /_/src/Orleans.Core/Providers/IGrainStorageSerializer.cs:line 43
   at Orleans.Storage.DynamoDBGrainStorage.ConvertFromStorageFormat[T](GrainStateRecord entity) in /_/src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs:line 330
2024-09-30 14:17:38 [ERR] Error from storage provider DynamoDBGrainStorage.Test during ReadStateAsync for grain test/Testnull - Orleans.Storage.DynamoDBGrainStorage
```

**Comment by scalalang2** [comment]
I had also investigated the AzureTableStorage code
it seems that same error should be triggerred.

Even if this is an intentional behavior
it needs to be fixed because it's currently causing issues with the Streaming functionality.

**Comment by scalalang2** [comment]
## My Suggestion.
- [Code to be fixed : DynamoDBGrainStorage](https://github.com/dotnet/orleans/blob/ad8d22d3e6427ebb6af5ffe32a5c3b911b7595ec/src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs#L330-L335)

```cs
T dataValue = default;
try
{
  if(entity.State.Length > 0)
      dataValue = this.options.GrainStorageSerializer.Deserialize<T>(entity.State);
  else
      return dataValue;
}
catch (Exception exc)
{
    var sb = new StringBuilder();
    sb.AppendFormat("Unable to convert from storage format GrainStateEntity.Data={0}", entity.State);

    if (dataValue != null)
    {
        sb.Append($"Data Value={dataValue} Type={dataValue.GetType()}");
    }

    var message = sb.ToString();
    this.logger.LogError(exc, "{Message}", message);
    throw new AggregateException(message, exc);
}
```

**Comment by scalalang2** [comment]
@ReubenBond If you agree with this, I'll take this job.

**Comment by scalalang2** [comment]
@ReubenBond Thanks for reply,
I understood that you suggested making changes as follows, Did I understand correctly? 

## [ReadStateAsync](https://github.com/dotnet/orleans/blob/ad8d22d3e6427ebb6af5ffe32a5c3b911b7595ec/src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs#L148-L156)

```cs
if (record != null)
{
    var loadedState = ConvertFromStorageFormat<T>(record);
    grainState.RecordExists = loadedState != null;
    grainState.State = loadedState ?? Activator.CreateInstance<T>();
    grainState.ETag = record.ETag.ToString();
}
else
{
    grainState.State = _activatorProvider.GetActivator<T>().Create()
}
```

## [ClearStateAsync](https://github.com/dotnet/orleans/blob/ad8d22d3e6427ebb6af5ffe32a5c3b911b7595ec/src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs#L284-L297)

```cs
if (this.options.DeleteStateOnClear)
{
    // codes
}
else
{
    // codes
}

grainState.State = _activatorProvider.GetActivator<T>().Create()
```
