### ISSUE TITLE
When clients dispose an IAsyncEnumerator, the AsyncEnumerableGrainExtension can throw a NotSupportedException

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/orleans#9185]
I've seen in my logs exceptions similar to this
```
[12:47:50 WRN] Orleans.Runtime.AsyncEnumerableRequest Failed to dispose async enumerator.
System.NotSupportedException: Specified method is not supported.
   at <my-iasyncenumerable-grain-method-using-the-c#-state-machine>+System.IAsyncDisposable.DisposeAsync()
   at Orleans.Runtime.AsyncEnumerableGrainExtension.DisposeAsync(Guid requestId) in /_/src/Orleans.Core/Runtime/AsyncEnumerableGrainExtension.cs:line 54
   at OrleansCodeGen.Orleans.Runtime.Invokable_IAsyncEnumerableGrainExtension_GrainReference_Ext_3C6D7209.InvokeInner() in /_/src/Orleans.Core.Abstractions/Orleans.CodeGenerator/Orleans.CodeGenerator.OrleansSerializationSourceGenerator/Orleans.Core.Abstractions.orleans.g.cs:line 241
   at Orleans.Runtime.Request.Invoke() in /_/src/Orleans.Core.Abstractions/Runtime/GrainReference.cs:line 592
--- End of stack trace from previous location ---
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Core/Core/GrainMethodInvoker.cs:line 132
   at OrleansDashboard.Implementation.GrainProfilerFilter.Invoke(IIncomingGrainCallContext context)
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Core/Core/GrainMethodInvoker.cs:line 94
   at Orleans.Runtime.InsideRuntimeClient.Invoke(IGrainContext target, Message message) in /_/src/Orleans.Runtime/Core/InsideRuntimeClient.cs:line 267
   at Orleans.Serialization.Invocation.ResponseCompletionSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 98
   at Orleans.Runtime.AsyncEnumeratorProxy`1.DisposeAsync() in /_/src/Orleans.Core.Abstractions/Runtime/AsyncEnumerableRequest.cs:line 210
```

As far as I can tell, the AsyncEnumerableGrainExtension has a bug, where the enumerator's DisposeAsync method is unconditionally called while there still might be an incomplete `enumerator.MoveNextAsync` task "running". https://github.com/dotnet/orleans/blob/148e4788df32ea332d7808bcd04bb95fd04608a7/src/Orleans.Core/Runtime/AsyncEnumerableGrainExtension.cs#L52-L55
The C# compiler's state machine for an `IAsyncEnumerable` contains an explicit check for this condition and throws a `NotSupportedException`. It's a bit cumbersome, but can be seen [here](https://sharplab.io/#v2:D4AQTAjAsAUCAMACEEAsBuWDkQHQCUBXAOwBcBLAWwFNcBhAe0oAdyAbagJwGUuA3cgGNqAZ0xwkKXABUAFp2oBDACbliAc3HYUAVnFYAzMjCI6iAN6xE15EZAAORAEkAgiICexQQFFihGpyKAEYcADxqpAB8iACyABQA2r7+XIqkDJx0il7UbGxp5AzEALqm2cJ5BUXSDADW1MSIguW5+RTVdQ0AlBZWNv0oEMgA7IioYPDi/QMAnMgAbLgAIrmK7nEQ8PAANE0tle3ENfXEXVPT1oMjiPMz59YAvrCwD0A)

**Comment by Tragetaschen** [comment]
I thought about this as fix before as well, but discarded it:
The grain method is not able to accept a `[EnumeratorCancellation] CancellationToken cancellationToken`. This in turn means it's neither stored/incorporated in the IAsyncEnumerable/IAsyncEnumerator state machine nor is it available in the grain method to cancel its own work. This essentially means the `await task.SuppressThrowing()` only completes when it generates another value, which it might not…

Or is there already support for native CancellationTokens on grain interfaces? 😁
