### ISSUE TITLE
Concurrent Writes State = TableStorage

### ISSUE THREAD

**Issue by ukluk** [dotnet/orleans#920]
We are seeing an exception thrown by TableStorage, and after investigation it seams that ETag is dirty meaning that we are seeing concurrent writes.

Q1) If the grains are single threaded how can it be that we are seeing ETag exceptions when Writing the state?
Q2) What is you recommendation to avoid Grain concurrency, as the client can get multiple requests almost simultaneously
Q3) What is your recommendation to handle state if we get non transient errors? Ignore? Clear? wait and retry?

This is the offending code
public async Task AggregateAsync(DateTime msgTimeUtc, Guid messageId, NodeState nodeState, Guid resourceId)
        {
                //some aggregation
                await WriteStateAsync();

And this is the unraveled exception:

Orleans.Runtime.OrleansException
Error from storage provider during WriteState for grain Type=Mesh.Ratatouille.Devices.SiteGrain Pk=*grn/A866C8EA/0000000000000000ffffffffffffffff03ffffffa866c8ea-0x4362189B Id=GrainReference:*grn/A866C8EA/ffffffff Error=UpdateConditionNotSatisfied
 
Exc level 0: Microsoft.WindowsAzure.Storage.StorageException: Message = The remote server returned an error: (412) Precondition Failed., HttpStatusCode = 412, HttpStatusMessage = Precondition Failed, ExtendedErrorInformation.ErrorCode = UpdateConditionNotSatisfied, ExtendedErrorInformation.ErrorMessage = The update condition specified in the request was not satisfied.
RequestId:e4453aae-0002-0036-4751-08fc92000000
Time:2015-10-16T20:30:49.3055925Z.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AzureUtils.AzureTableDataManager`1.<UpdateTableEntryAsync>d__1e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Storage.AzureTableStorage.GrainStateTableDataManager.<Write>d__1f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Storage.AzureTableStorage.<WriteStateAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Core.GrainStateStorageBridge.<WriteStateAsync>d__5.MoveNext()
Exc level 1: System.Net.WebException: The remote server returned an error: (412) Precondition Failed.
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableOperationPreProcess(TableResult result, TableOperation operation, HttpWebResponse resp, Exception ex)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)
   at Orleans.Core.GrainStateStorageBridge.<WriteStateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mesh.Ratatouille.Devices.SiteGrain.<UpdateFieldGatewayStateAsync>d__19.MoveNext() in c:\Users\Uriel\Source\Repos\ActiveSense\Mesh.Ratatouille.Devices\SiteGrain.cs:line 183
----------Inner Exception----------
Microsoft.WindowsAzure.Storage.StorageException
The remote server returned an error: (412) Precondition Failed.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.AzureUtils.AzureTableDataManager`1.<UpdateTableEntryAsync>d__1e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Storage.AzureTableStorage.GrainStateTableDataManager.<Write>d__1f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Storage.AzureTableStorage.<WriteStateAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Core.GrainStateStorageBridge.<WriteStateAsync>d__5.MoveNext()
	RequestResult:
		HTTPStatusCode:    412
		HttpStatusMessage: Precondition Failed
		TargetLocation:    Primary
		ServiceRequestID:  e4453aae-0002-0036-4751-08fc92000000
		ContentMd5:        
		Etag:              
		RequestDate:       Fri, 16 Oct 2015 20:30:48 GMT
		StartTime:         10/16/2015 8:30:49 PM
		EndTime:           10/16/2015 8:30:49 PM

----------Inner Exception----------
System.Net.WebException
The remote server returned an error: (412) Precondition Failed.
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableOperationPreProcess(TableResult result, TableOperation operation, HttpWebResponse resp, Exception ex)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)

**Comment by sergeybykov** [comment]
Q1) There is a small window during a silo failure when if you are unlucky you may get two activations of the same grain activated at the same time. One of them will get removed after the cluster state settles. You shouldn't see that in the absence of silo failures.

Q2) Again, shouldn't be a concern in general.

Q3) In case you got into an eTag mismatch, you have two basic options:
* Call ReadStateAsync() to reload the state object, then reapply changes, and call WriteStateAsync()
* Call DeactivateOnIdle() and then throw an exception. If the client retries, the request will be redelivered to a new activation with the latest persistent state.
