### ISSUE TITLE
Trying to replicate "Orleans: Microsoft's distributed systems framework for .NET" but with a Backend rather than Frontend project

### ISSUE THREAD

**Issue by joshcornejo** [dotnet/orleans#9241]
My Aspire AppHost:

```
var orleans_cache = builder.AddRedis("orleans-redis")
                                                .WithLifetime(ContainerLifetime.Persistent);

var orleans = builder.AddOrleans("cluster")
    .WithClustering(orleans_cache);

var apiService = builder.AddProject<md_api>("api")
    .WithReference(orleans)
    .WaitFor(orleans_cache);
```

My API:

```
builder.AddKeyedRedisDistributedCache("orleans-redis");
builder.UseOrleans();
```

My exception on startup (`Microsoft.Orleans.Sdk` is installed in the API project, and I am already using Redis in my code, so can't figure what "provider's package" means):

```
Unhandled exception. System.InvalidOperationException: Could not find Clustering provider named 'Redis'. This can indicate that either the 'Microsoft.Orleans.Sdk' or the provider's package are not referenced by your application.
   at Orleans.Hosting.DefaultSiloServices.<ApplyConfiguration>g__GetRequiredProvider|2_3(Dictionary`2 knownProviderTypes, String kind, String name) in /_/src/Orleans.Runtime/Hosting/DefaultSiloServices.cs:line 465
   at Orleans.Hosting.DefaultSiloServices.<ApplyConfiguration>g__ConfigureProvider|2_2(ISiloBuilder builder, Dictionary`2 knownProviderTypes, String kind, String name, IConfigurationSection configurationSection) in /_/src/Orleans.Runtime/Hosting/DefaultSiloServices.cs:line 452
   at Orleans.Hosting.DefaultSiloServices.<ApplyConfiguration>g__ApplySubsection|2_5(ISiloBuilder builder, IConfigurationSection cfg, Dictionary`2 knownProviderTypes, String sectionName) in /_/src/Orleans.Runtime/Hosting/DefaultSiloServices.cs:line 489
   at Orleans.Hosting.DefaultSiloServices.ApplyConfiguration(ISiloBuilder builder) in /_/src/Orleans.Runtime/Hosting/DefaultSiloServices.cs:line 442
   at Orleans.Hosting.DefaultSiloServices.AddDefaultServices(ISiloBuilder builder) in /_/src/Orleans.Runtime/Hosting/DefaultSiloServices.cs:line 416
   at Orleans.Hosting.SiloBuilder..ctor(IServiceCollection services, IConfiguration configuration) in /_/src/Orleans.Runtime/Hosting/SiloBuilder.cs:line 15
   at Microsoft.Extensions.Hosting.OrleansSiloGenericHostExtensions.AddOrleansCore(IServiceCollection services, IConfiguration configuration) in /_/src/Orleans.Runtime/Hosting/OrleansSiloGenericHostExtensions.cs:line 165
   at Microsoft.Extensions.Hosting.OrleansSiloGenericHostExtensions.UseOrleans(IHostApplicationBuilder hostAppBuilder, Action`1 configureDelegate) in /_/src/Orleans.Runtime/Hosting/OrleansSiloGenericHostExtensions.cs:line 58
   at Microsoft.Extensions.Hosting.OrleansSiloGenericHostExtensions.UseOrleans(IHostApplicationBuilder hostAppBuilder) in /_/src/Orleans.Runtime/Hosting/OrleansSiloGenericHostExtensions.cs:line 27
   at Program.<Main>$(String[] args) in /..../.../.../Program.cs:line 41
```

**Comment by joshcornejo** [comment]
Hi Reuben,

Thanks for answering so promptly ... I keep trying combinations of packages and still get that exception 

These are my packages:

Aspire:

```
    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.0.0" />
        <PackageReference Include="Aspire.Hosting.Orleans" Version="9.0.0" />
        <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="9.0.0" />
        <PackageReference Include="Aspire.Hosting.Redis" Version="9.0.0" />
        <PackageReference Include="Aspire.StackExchange.Redis" Version="9.0.0" />
        <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="9.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.0" />
        <PackageReference Include="Microsoft.Orleans.Core" Version="9.0.0" />
        <PackageReference Include="Microsoft.Orleans.Sdk" Version="9.0.0" />
    </ItemGroup>

```
The API server:
```
    <PackageReference Include="Aspire.StackExchange.Redis" Version="9.0.0" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="9.0.0-preview.9.24556.5" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.0" />
    <PackageReference Include="Microsoft.Orleans.Core" Version="9.0.0" />
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Orleans.Serialization" Version="9.0.0" />
    <PackageReference Include="Microsoft.Orleans.Serialization.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="9.0.0" />
    <PackageReference Include="Microsoft.Orleans.Sdk" Version="9.0.0" />
```

I've added this after your comment:
`    <PackageReference Include="Orleans.Clustering.Redis" Version="7.0.0" />`

**Comment by joshcornejo** [comment]
Sorted !
