### ISSUE TITLE
Unhandled exception. Orleans.Serialization.CodecNotFoundException

### ISSUE THREAD

**Issue by joshcornejo** [dotnet/orleans#9243]
On startup, I am getting the exception below. I searched for this problem before posting and changed all `IEnumerable<>` into `List<>`, and any `IDictionary<>` into `Dictionary<>`. This code worked before, and still does if I remove the line`builder.UseOrleans();` from Program.cs.

I have searched in the mentioned for what code is mine (`BaseRightsNode` ... `PolicyVersion` ... `PolicyRelease` ... `Agreement`) and they are all connected via inheritance (from left to right, left being the top ancestor, there are also 5 further ancestors to the left, but none mentioned)

When using Redis I didn't need to `[GenerateSerializer]`, but also added the Serialisation to all the classes:

```
[GenerateSerializer]
[Alias("MarketData.ApiService.Models.misc.BaseRightsNode")]
public class BaseRightsNode : BaseNode
{
    [Id(0)]
    protected Rule _rule;              // points at the current rule being validated
    [Id(1)]
    protected Agreement _agreement;    // the agreement
    [Id(2)]
    protected World _world;            // the world
```
(those attributes, it is a knowledge graph, so it has cyclical references, but not sure if they are the cause of the exception, in Redis they don't serialise as they're `protected`).

For context, my Grain is another object that has a list of Agreements and other BaseRightsNode descendants.

```
[Alias("MarketData.ApiService.Models.Deontic.IWorldGrain")]
public interface IWorldGrain : IGrainWithStringKey
...
public class World : Grain, IWorldGrain
```

Exception:

 ```
      -------------- Started silo S192.168.6.147:64649:91278225, ConsistentHashCode 7BDDE223 --------------
Unhandled exception. Orleans.Serialization.CodecNotFoundException: Could not find a codec for type MarketData.ApiService.Models.Deontic.World.
   at Orleans.Serialization.Serializers.CodecProvider.ThrowCodecNotFound(Type fieldType) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 673
   at Orleans.Serialization.Serializers.CodecProvider.GetCodec[TField]() in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 202
   at Orleans.Serialization.ServiceCollectionExtensions.FieldCodecHolder`1.get_Value() in /_/src/Orleans.Serialization/Hosting/ServiceCollectionExtensions.cs:line 152
   at Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.GetService[TService](Object caller, ICodecProvider codecProvider) in /_/src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs:line 75
   at OrleansCodeGen.MarketData.ApiService.Models.misc.Codec_BaseRightsNode..ctor(ICodecProvider codecProvider) in /Users/joshuacornejo/Desktop/Projects/aspire/MarketData/md.api/obj/Debug/net9.0/Orleans.CodeGenerator/Orleans.CodeGenerator.OrleansSerializationSourceGenerator/md.api.orleans.g.cs:line 5047
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.InvokeDirectByRefWithFewArgs(Span`1 copyOfArgs)
   at System.Reflection.ConstructorInvoker.InvokeDirectByRef(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.InvokeImpl(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.Invoke(Span`1 arguments)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
   at Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.GetService[TService](Object caller, ICodecProvider codecProvider) in /_/src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs:line 72
   at OrleansCodeGen.MarketData.ApiService.Models.Rights.Codec_PolicyVersion..ctor(ICodecProvider codecProvider) in /Users/joshuacornejo/Desktop/Projects/aspire/MarketData/md.api/obj/Debug/net9.0/Orleans.CodeGenerator/Orleans.CodeGenerator.OrleansSerializationSourceGenerator/md.api.orleans.g.cs:line 7344
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.InvokeDirectByRefWithFewArgs(Span`1 copyOfArgs)
   at System.Reflection.ConstructorInvoker.InvokeDirectByRef(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.InvokeImpl(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.Invoke(Span`1 arguments)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
   at Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.GetService[TService](Object caller, ICodecProvider codecProvider) in /_/src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs:line 72
   at OrleansCodeGen.MarketData.ApiService.Models.Rights.Codec_PolicyRelease..ctor(ICodecProvider codecProvider) in /Users/joshuacornejo/Desktop/Projects/aspire/MarketData/md.api/obj/Debug/net9.0/Orleans.CodeGenerator/Orleans.CodeGenerator.OrleansSerializationSourceGenerator/md.api.orleans.g.cs:line 7590
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.InvokeDirectByRefWithFewArgs(Span`1 copyOfArgs)
   at System.Reflection.ConstructorInvoker.InvokeDirectByRef(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.InvokeImpl(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.Invoke(Span`1 arguments)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
   at Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.GetService[TService](Object caller, ICodecProvider codecProvider) in /_/src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs:line 72
   at OrleansCodeGen.MarketData.ApiService.Models.Rights.Codec_Agreement..ctor(ICodecProvider codecProvider) in /Users/joshuacornejo/Desktop/Projects/aspire/MarketData/md.api/obj/Debug/net9.0/Orleans.CodeGenerator/Orleans.CodeGenerator.OrleansSerializationSourceGenerator/md.api.orleans.g.cs:line 7109
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.InvokeDirectByRefWithFewArgs(Span`1 copyOfArgs)
   at System.Reflection.ConstructorInvoker.InvokeDirectByRef(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.InvokeImpl(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.Invoke(Span`1 arguments)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Orleans.Serialization.Serializers.CodecProvider.GetServiceOrCreateInstance(Type type, Object[] constructorArguments) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 491
   at Orleans.Serialization.Serializers.CodecProvider.CreateCodecInstance(Type fieldType, Type searchType) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 558
   at Orleans.Serialization.Serializers.CodecProvider.TryCreateCodec(Type fieldType) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 181
   at Orleans.Serialization.Serializers.CodecProvider.TryGetCodec(Type fieldType) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 170
   at Orleans.Serialization.Serializers.CodecProvider.TryGetCodec[TField]() in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 145
   at Orleans.Serialization.Serializers.CodecProvider.GetCodec[TField]() in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 202
   at Orleans.Serialization.ServiceCollectionExtensions.FieldCodecHolder`1.get_Value() in /_/src/Orleans.Serialization/Hosting/ServiceCollectionExtensions.cs:line 152
   at Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.<UnwrapService>g__Unwrap|3_0[TService](TService val) in /_/src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs:line 120
   at Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.UnwrapService[TService](Object caller, TService service) in /_/src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs:line 109
   at Orleans.Serialization.Codecs.ListCodec`1..ctor(IFieldCodec`1 fieldCodec) in /_/src/Orleans.Serialization/Codecs/ListCodec.cs:line 30
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.InvokeDirectByRefWithFewArgs(Span`1 copyOfArgs)
   at System.Reflection.ConstructorInvoker.InvokeDirectByRef(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.InvokeImpl(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.Invoke(Span`1 arguments)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Orleans.Serialization.Serializers.CodecProvider.GetServiceOrCreateInstance(Type type, Object[] constructorArguments) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 491
   at Orleans.Serialization.Serializers.CodecProvider.CreateCodecInstance(Type fieldType, Type searchType) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 558
   at Orleans.Serialization.Serializers.CodecProvider.TryCreateCodec(Type fieldType) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 181
   at Orleans.Serialization.Serializers.CodecProvider.TryGetCodec(Type fieldType) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 170
   at Orleans.Serialization.SerializerConfigurationAnalyzer.<AnalyzeSerializerAvailability>g__VisitType|0_0(Type type, MethodInfo methodInfo, <>c__DisplayClass0_0&) in /_/src/Orleans.Serialization/Hosting/SerializerConfigurationAnalyzer.cs:line 63
   at Orleans.Serialization.SerializerConfigurationAnalyzer.AnalyzeSerializerAvailability(ICodecProvider codecProvider, TypeManifestOptions options) in /_/src/Orleans.Serialization/Hosting/SerializerConfigurationAnalyzer.cs:line 38
   at Orleans.SerializerConfigurationValidator.Orleans.IConfigurationValidator.ValidateConfiguration() in /_/src/Orleans.Core/Configuration/Validators/SerializerConfigurationValidator.cs:line 60
   at Orleans.Hosting.SiloHostedService.ValidateSystemConfiguration(IEnumerable`1 configurationValidators) in /_/src/Orleans.Runtime/Hosting/SiloHostedService.cs:line 41
   at Orleans.Hosting.SiloHostedService..ctor(Silo silo, IEnumerable`1 configurationValidators, ILogger`1 logger) in /_/src/Orleans.Runtime/Hosting/SiloHostedService.cs:line 20
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /Users/joshuacornejo/Desktop/Projects/aspire/MarketData/md.api/Program.cs:line 218

```

**Comment by joshcornejo** [comment]
I have started narrowing it down by starting from scratch.

Everything "starts" fine when the following methods in the interface are commented. With the first I get the exception as above, with the following 2, I get an error related to JsonObject.

I could get around the JsonObject by sending a string (inefficient, but it's OK), but I'm not sure I can get around the Add.

```
public Task Add(Agreement A, string actor);
```

```
public Task<bool> SetObjectValue(string uuid, JsonObject value, string actor);
public Task<bool> SetObjectByNameValue(string friendlyName, JsonObject value, string actor);
```

```
Unhandled exception. Orleans.Runtime.OrleansConfigurationException: Found unserializable or uncopyable types which are being referenced in grain interface signatures:
Type: System.Text.Json.Nodes.JsonObject has no serializer or copier and was referenced by the following:
```

**Comment by joshcornejo** [comment]
Seems to have found out what was the issue.

One of the base classes had a couple of:

`public string? some_attribute;`

 Once I removed the "?", it compiled and started without throwing an exception.

Now need to reintroduce all the rest of the code and test the rest.

**Comment by joshcornejo** [comment]
I had all the latest packages from NuGet - 9.0.0. I have seen now 9.0.1, updated and re-added the "?" and it did start up without an exception.

I've added [Microsoft.Orleans.Serialization.SystemTextJson](https://www.nuget.org/packages/Microsoft.Orleans.Serialization.SystemTextJson) and [Microsoft.Orleans.Serialization.NewtonsoftJson](https://www.nuget.org/packages/Microsoft.Orleans.Serialization.NewtonsoftJson) for safety, still getting:

```
Unhandled exception. Orleans.Runtime.OrleansConfigurationException: Found unserializable or uncopyable types which are being referenced in grain interface signatures:
Type: System.Text.Json.Nodes.JsonObject has no serializer or copier and was referenced by the following:
        * MarketData.ApiService.Models.Deontic.IMundusGrain,md.api methods: System.Threading.Tasks.Task`1[System.Boolean] SetObjectValue(System.String, System.Text.Json.Nodes.JsonObject, System.String), System.Threading.Tasks.Task`1[System.Boolean] SetObjectByNameValue(System.String, System.Text.Json.Nodes.JsonObject, System.String)
Ensure that all types which are used in grain interfaces have serializers available for them.

```

Cheers Reuben, you're a star!

**Comment by joshcornejo** [comment]
I made a mistake and used Newtonsoft last night. I fixed it, and it now starts without an exception:
 
```
builder.Services.AddSerializer(serializerBuilder =>
{
    serializerBuilder.AddJsonSerializer(
        isSupported: type => type.Namespace.StartsWith("MarketData.ApiService"));
});
```

Thank you very much!
