### ISSUE TITLE
Exceptions due to unsolicited connections from monitoring apps remain unmarked and are raised via UnobservedTaskException

### ISSUE THREAD

**Issue by d-jagoda** [dotnet/orleans#9245]
Hi we continue to see the following exception despite this fix https://github.com/dotnet/orleans/pull/8691/commits/9c708474df75ef63a55bda1ef911b2356f15f6e6

`System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Remote connection sent preamble length of 1230262351, which is greater than maximum allowed size of 1024.)
 ---> System.InvalidOperationException: Remote connection sent preamble length of 1230262351, which is greater than maximum allowed size of 1024.
   at Orleans.Runtime.Messaging.ConnectionPreambleHelper.Read(ConnectionContext connection) in /_/src/Orleans.Core/Networking/ConnectionPreamble.cs:line 96
   at Orleans.Runtime.Messaging.GatewayInboundConnection.RunInternal() in /_/src/Orleans.Runtime/Networking/GatewayInboundConnection.cs:line 110
   at Orleans.Runtime.Messaging.Connection.Run() in /_/src/Orleans.Core/Networking/Connection.cs:line 87
   --- End of inner exception stack trace ---ConnectionPreambleHelperConnectionPreambleGatewayInboundConnection`

The reason for this is the Task managed by this TaskCompletionSource not being observed https://github.com/dotnet/orleans/blob/main/src/Orleans.Core/Networking/Connection.cs#L152

An easy fix would be to observe it as it was done by earlier fix.
` _initializationTcs.Task.Ignore();`

Happy to to raise a PR.

Thanks in advance

**Comment by RyanWood18** [comment]
We're also seeing a similar issue and couldn't work out where it was coming from after we found the earlier fix. Would be great to get this resolved

**Comment by avnotaklu** [comment]
Any updates on this, i'm getting this but only when i deploy in production at render.com

**Comment by ReubenBond** [comment]
Resolved by #9280, merged January 28, 2025. The connection-close path now explicitly observes _initializationTcs.Task, implementing the fix proposed here and preventing its initialization failure from surfacing through UnobservedTaskException. The PR documents verification using a malformed connection followed by forced garbage collection. Invalid connections continue to be rejected and logged normally. Closing as resolved.
