### ISSUE TITLE
SqlStatisticsPublisher throws error on no statistics to publish

### ISSUE THREAD

**Issue by amccool** [dotnet/orleans#933]
ERROR  	100835	SiloLogStatistics	172.18.124.91:11111]	!!!!!!!!!! Exception occurred during Stats reporter.	
Exc level 0: System.Data.SqlClient.SqlException: Incorrect syntax near ';'.

is thrown when no statistics are passed to be published 

[2015-10-22 19:44:20.810 GMT    25	ERROR  	100835	SiloLogStatistics	172.18.124.91:11111]	!!!!!!!!!! Exception occurred during Stats reporter.	
Exc level 0: System.Data.SqlClient.SqlException: Incorrect syntax near ';'.
   at System.Data.SqlClient.SqlCommand.<ExecuteDbDataReaderAsync>b__24(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.SqlUtils.RelationalStorage.<ExecuteReaderAsync>d__e`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.SqlUtils.RelationalStorage.<ExecuteAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.SqlUtils.RelationalStorage.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where...

**Comment by veikkoeeva** [comment]
This was already discussed, but I'll add here just in case that there's two places to fix this. One on the hot path that Orleans uses, the hand-tuned queries grouped with the rest and one general one using reflection. Likely they need to to add a check zero length data is not being tried to insert.

Good work. :+1:
