### ISSUE TITLE
GrainState should not attempt to set property on the state if there is no setter method

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#951]
When performing a deep copy of the State, GrainState uses reflection to set properties, but doesn't check properly for the setter before setting value.
So on the grain state with calculated property ( get only) it will throw ArgumentException. Something like this

```
System.ArgumentExceptionProperty set method not found.
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Orleans.GrainState.SetAll(IDictionary`2 values)
   at Orleans.GrainState.DeepCopy()
   at DBCloud.ActorCollection.BaseDeletableGrain`1.<HardDeleteInternal>d__7.MoveNext() in BaseGrain.cs: line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DBCloud.ActorTests.Documents.DocumentGrainTests.<HardDelete_WhenAllGood_ThenCallsDelete>d__14.MoveNext() in DocumentGrainTests.cs: line 218
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at 
```

**Comment by ReubenBond** [comment]
Sounds good, how do you feel about makong a PR with a fix & test case

**Comment by ReubenBond** [comment]
Oh I see you did :) good stuff

**Comment by centur** [comment]
slowly getting there, learning how to do PRs on github...

**Comment by sergeybykov** [comment]
So long as you can push the fix to a branch in your fork of Orleans, a PR is nothing but just an URL to it.

**Comment by sergeybykov** [comment]
Resolved by https://github.com/dotnet/orleans/issues/952.
